-- Removing private schemas, FORCE RLS or runtime-role restrictions must fail this suite.
begin;
create extension if not exists pgtap with schema extensions;
set local search_path = extensions, pg_catalog;
select no_plan();
select ok(to_regnamespace('app') is not null, 'business schema exists privately');
select ok(to_regnamespace('internal') is not null, 'internal schema exists privately');
select ok(to_regnamespace('authorization') is not null, 'authorization schema exists privately');
select ok(to_regclass('app.schools') is not null, 'tenant records persist');
select ok(to_regclass('app.memberships') is not null, 'current membership is stored');
select ok(to_regclass('internal.audit_events') is not null, 'audit storage exists');
select ok(to_regclass('internal.idempotency_keys') is not null, 'command replay storage exists');
select ok(to_regclass('internal.outbox_events') is not null, 'outbox storage exists');
select ok(exists(select 1 from pg_roles where rolname='cuevo_api' and not rolsuper and not rolbypassrls), 'API role cannot bypass RLS');
select ok(exists(select 1 from pg_roles where rolname='cuevo_worker' and not rolsuper and not rolbypassrls), 'worker role cannot bypass RLS');
select ok(not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('app','internal') and c.relkind='r' and (not c.relrowsecurity or not c.relforcerowsecurity)), 'every business and internal table forces RLS');
select ok(not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.rolname in ('anon','authenticated','service_role') where n.nspname in ('app','internal') and c.relkind='r' and has_table_privilege(r.oid,c.oid,'SELECT,INSERT,UPDATE,DELETE')), 'Data API roles have no business-table privileges');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_roles r on r.rolname in ('anon','authenticated','service_role') where n.nspname in ('app','internal','authorization') and has_function_privilege(r.oid,p.oid,'EXECUTE')and not(r.rolname='authenticated'and p.oid=to_regprocedure('"authorization".community_realtime_topic(text)'))), 'Data API roles cannot execute private helpers except the explicit current-session private-channel policy predicate');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('internal','authorization') and p.prosecdef and not coalesce(p.proconfig @> array['search_path=""'],false)), 'privileged helpers pin an empty search path');
select ok(not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.oid=c.relowner where n.nspname in ('app','internal') and r.rolname in ('cuevo_api','cuevo_worker')), 'runtime roles own no business tables');
select is((select count(*) from app.memberships where school_id='10000000-0000-4000-8000-000000000001' and role='admin'),1::bigint,'reference seed has one admin');
select is((select count(*) from app.memberships where school_id='10000000-0000-4000-8000-000000000001' and role='coordinator'),2::bigint,'reference seed has two coordinators');
select is((select count(*) from app.memberships where school_id='10000000-0000-4000-8000-000000000001' and role='teacher'),8::bigint,'reference seed has eight teachers');
select is((select count(*) from app.memberships where school_id='10000000-0000-4000-8000-000000000001' and role='student'),60::bigint,'reference seed has sixty students');
select is((select count(*) from app.memberships where school_id='10000000-0000-4000-8000-000000000001' and role='parent'),60::bigint,'reference seed has sixty parents');
select is((select count(*) from app.year_groups where school_id='10000000-0000-4000-8000-000000000001'),4::bigint,'reference seed has four year groups');
select is((select count(*) from app.classes where school_id='10000000-0000-4000-8000-000000000001'),6::bigint,'reference seed has six classes');
select is((select count(*) from app.subjects where school_id='10000000-0000-4000-8000-000000000001'),8::bigint,'reference seed has eight subjects');
select ok((select bool_and(synthetic) from app.people),'all seeded people are explicitly synthetic');
create table public.foundation_grant_probe(id uuid);
select ok(not has_table_privilege('anon','public.foundation_grant_probe','SELECT,INSERT,UPDATE,DELETE'),'new postgres-owned public table is not automatically granted to anon');
select ok(not has_table_privilege('authenticated','public.foundation_grant_probe','SELECT,INSERT,UPDATE,DELETE'),'new public table is not automatically granted to authenticated');
select ok(not has_table_privilege('service_role','public.foundation_grant_probe','SELECT,INSERT,UPDATE,DELETE'),'new public table is not automatically granted to service_role');
create function "authorization".foundation_grant_probe() returns boolean language sql set search_path='' as 'select true';
select ok(not has_function_privilege('anon','"authorization".foundation_grant_probe()','EXECUTE'),'new private function is not automatically executable');
select * from finish();
rollback;
