import { LearningApiError } from '../../shared/api/client.ts';
export type Room = { id: string; classId: string; name: string; type: 'CLASS' | 'GROUP'; ownerId: string; status: 'ACTIVE'; canModerate: boolean; canPost: boolean; privateTopic: string };
export type RosterPerson = { id: string; displayName: string; role: 'admin' | 'coordinator' | 'teacher' | 'student' };
export type Post = { id: string; roomId: string; actorId: string; authorName: string; body: string | null; replyToId: string | null; createdAt: string; status: 'VISIBLE' | 'HIDDEN'; reactions: { reaction: 'THANKS' | 'HELPFUL' | 'ENCOURAGE'; count: number; mine: boolean }[] };
export type Announcement = { id: string; classId: string | null; title: string; body: string; parentVisible: boolean; createdAt: string; readAt: string | null };
export type Notification = { id: string; announcementId: string; kind: 'ANNOUNCEMENT'; createdAt: string; readAt: string | null };
export type Report = { id: string; postId: string; reporterId: string; reason: string; createdAt: string };
const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
const strings = (value: Record<string, unknown>, keys: string[]) => keys.every(key => typeof value[key] === 'string' && value[key] !== '');
const date = (value: unknown) => typeof value === 'string' && Number.isFinite(Date.parse(value));
export function parseRoom(value: unknown): Room { if (!object(value) || !strings(value, ['id', 'classId', 'name', 'ownerId', 'privateTopic']) || !['CLASS', 'GROUP'].includes(String(value.type)) || value.status !== 'ACTIVE' || typeof value.canModerate !== 'boolean' || typeof value.canPost !== 'boolean' || !String(value.privateTopic).startsWith('cuevo:') || !String(value.privateTopic).endsWith(`:room:${value.id}`)) throw new LearningApiError('invalid'); return value as Room; }
export function parsePost(value: unknown): Post { if (!object(value) || !strings(value, ['id', 'roomId', 'actorId', 'authorName']) || !(value.replyToId === null || typeof value.replyToId === 'string') || !date(value.createdAt) || !['VISIBLE', 'HIDDEN'].includes(String(value.status)) || (value.status === 'HIDDEN' ? value.body !== null : typeof value.body !== 'string') || !Array.isArray(value.reactions) || value.reactions.some(reaction => !object(reaction) || !['THANKS', 'HELPFUL', 'ENCOURAGE'].includes(String(reaction.reaction)) || typeof reaction.count !== 'number' || !Number.isInteger(reaction.count) || reaction.count < 0 || typeof reaction.mine !== 'boolean')) throw new LearningApiError('invalid'); return value as Post; }
export function parseRosterPerson(value: unknown): RosterPerson { if (!object(value) || !strings(value, ['id', 'displayName']) || !['admin', 'coordinator', 'teacher', 'student'].includes(String(value.role))) throw new LearningApiError('invalid'); return value as RosterPerson; }
export function parseAnnouncement(value: unknown): Announcement { if (!object(value) || !strings(value, ['id', 'title', 'body']) || !(value.classId === null || typeof value.classId === 'string') || typeof value.parentVisible !== 'boolean' || !date(value.createdAt) || !(value.readAt === null || date(value.readAt))) throw new LearningApiError('invalid'); return value as Announcement; }
export function parseNotification(value: unknown): Notification { if (!object(value) || !strings(value, ['id', 'announcementId']) || value.kind !== 'ANNOUNCEMENT' || !date(value.createdAt) || !(value.readAt === null || date(value.readAt))) throw new LearningApiError('invalid'); return value as Notification; }
export function parseReport(value: unknown): Report { if (!object(value) || !strings(value, ['id', 'postId', 'reporterId', 'reason']) || !date(value.createdAt)) throw new LearningApiError('invalid'); return value as Report; }
