import{describe,it,expect}from'vitest';import{createHash}from'node:crypto';import type{PoolClient}from'pg';import type{Database}from'../../src/platform/database/database';import type{IdentityService}from'../../src/platform/identity/identity.service';import{AssetService,type AssetStoragePort}from'../../src/modules/assets/assets.service';import{DomainError}from'@cuevo/domain';import{assetStageSchema}from'@cuevo/contracts';
const bytes=Buffer.from('Synthetic private work');const asset={id:'71000000-0000-4000-8000-000000000001',ownerId:'20000000-0000-4000-8000-000000000012',name:'work.txt',contentType:'text/plain',byteSize:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),state:'STAGED',objectPath:'school/learner/asset'};
const actor={userId:asset.ownerId,schoolId:'10000000-0000-4000-8000-000000000001',membershipId:'72000000-0000-4000-8000-000000000001',role:'student',entitlements:['portfolio']};
function store(state='STAGED'){let current={...asset,state};let writes=0;let commitLost=false;const database={actorTransaction:async(_a:string,_s:string,fn:(c:PoolClient)=>Promise<unknown>)=>{const result=await fn({query:async(sql:string)=>{if(sql.includes('can_manage_asset'))return{rows:[{allowed:true}]};if(sql.includes('asset_command')){writes++;current={...current,state:'AVAILABLE'};return{rows:[{receipt:current}]};}return{rows:[current]};}}as unknown as PoolClient);if(commitLost&&writes)throw Error('commit receipt lost');return result;}}as unknown as Database;return{database,retire:()=>{current={...current,state:'RETIRED'};},loseCommit:()=>{commitLost=true;},writes:()=>writes};}
const identity={resolve:async()=>actor}as unknown as IdentityService;
describe('private asset byte and receipt boundaries',()=>{
it('rejects retired source before storage upload',async()=>{const db=store('RETIRED');let uploads=0;const storage={upload:async()=>{uploads++;},download:async()=>bytes}as AssetStoragePort;await expect(new AssetService(identity,db.database,storage).finalize('Bearer token',actor.schoolId,asset.id,{contentBase64:bytes.toString('base64')},'asset-finalize-key','request')).rejects.toMatchObject({code:'ASSET_NOT_AVAILABLE'});expect(uploads).toBe(0);});
it('denies bytes when source retires during download',async()=>{const db=store('AVAILABLE');const storage={upload:async()=>{},download:async()=>{db.retire();return bytes;}}as AssetStoragePort;await expect(new AssetService(identity,db.database,storage).download('Bearer token',actor.schoolId,asset.id)).rejects.toMatchObject({code:'ASSET_NOT_AVAILABLE'});});
it('does not finalize readback checksum mismatch',async()=>{const db=store();const storage={upload:async()=>{},download:async()=>Buffer.from('Different')}as AssetStoragePort;await expect(new AssetService(identity,db.database,storage).finalize('Bearer token',actor.schoolId,asset.id,{contentBase64:bytes.toString('base64')},'asset-finalize-key','request')).rejects.toMatchObject({code:'ASSET_OUTCOME_UNKNOWN'});expect(db.writes()).toBe(0);});
it('preserves uncertain receipt when COMMIT cannot be confirmed',async()=>{const db=store();db.loseCommit();const storage={upload:async()=>{},download:async()=>bytes}as AssetStoragePort;await expect(new AssetService(identity,db.database,storage).finalize('Bearer token',actor.schoolId,asset.id,{contentBase64:bytes.toString('base64')},'asset-finalize-key','request')).rejects.toMatchObject({code:'ASSET_OUTCOME_UNKNOWN'});});
it('denies revoked session after upload verification without metadata write',async()=>{const db=store();let calls=0;const ids={resolve:async()=>{if(++calls>1)throw new DomainError('SESSION_REVOKED',401,'Sign in');return actor;}}as unknown as IdentityService;const storage={upload:async()=>{},download:async()=>bytes}as AssetStoragePort;await expect(new AssetService(ids,db.database,storage).finalize('Bearer token',actor.schoolId,asset.id,{contentBase64:bytes.toString('base64')},'asset-finalize-key','request')).rejects.toMatchObject({code:'SESSION_REVOKED'});expect(db.writes()).toBe(0);});
it('keeps storage unconfigured and rejects oversized metadata',async()=>{await expect(new AssetService(identity,store().database).download('Bearer token',actor.schoolId,asset.id)).rejects.toMatchObject({code:'ASSET_STORAGE_UNAVAILABLE'});expect(assetStageSchema.safeParse({ownerId:actor.userId,name:'work.txt',contentType:'text/plain',byteSize:524289,sha256:asset.sha256}).success).toBe(false);});
it('does not reupload an available object on a repeated finalize',async()=>{const db=store('AVAILABLE');let uploads=0;const storage={upload:async()=>{uploads++;},download:async()=>bytes}as AssetStoragePort;await new AssetService(identity,db.database,storage).finalize('Bearer token',actor.schoolId,asset.id,{contentBase64:bytes.toString('base64')},'asset-new-finalize-key','request');expect(uploads).toBe(0);expect(db.writes()).toBe(1);});
it('does not execute storage for forbidden parent actor',async()=>{let calls=0;const ids={resolve:async()=>({...actor,role:'parent'})}as unknown as IdentityService;const storage={upload:async()=>{calls++;},download:async()=>{calls++;return bytes;}}as AssetStoragePort;await expect(new AssetService(ids,store().database,storage).download('Bearer token',actor.schoolId,asset.id)).rejects.toMatchObject({status:403});expect(calls).toBe(0);});
it('preserves unknown upload transport outcome and no metadata authority',async()=>{const db=store();const storage={upload:async()=>{throw Error('private upstream credentials');},download:async()=>bytes}as AssetStoragePort;await expect(new AssetService(identity,db.database,storage).finalize('Bearer token',actor.schoolId,asset.id,{contentBase64:bytes.toString('base64')},'asset-upload-key','request')).rejects.toMatchObject({code:'ASSET_OUTCOME_UNKNOWN'});expect(db.writes()).toBe(0);});
});
