import{describe,it,expect}from'vitest';import{mkdtemp,writeFile,mkdir,rm,cp,readFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{createHash}from'node:crypto';import type{Database}from'../../src/platform/database/database';import type{ActorContext}from'@cuevo/domain';import*as packs from'../../src/modules/curriculum/packs';
describe('locked local curriculum bundles',()=>{
 it('rejects a snapshot path outside the pack root before reading it',async()=>{const root=await mkdtemp(join(tmpdir(),'cuevo-pack-'));try{const read=(packs as unknown as{loadLockedPack:(root:string,directory:string)=>Promise<unknown>}).loadLockedPack;expect(read).toBeDefined();await mkdir(join(root,'pack'));await writeFile(join(root,'pack','manifest.json'),JSON.stringify({snapshot:'../outside.txt'}));await expect(read(root,'pack')).rejects.toThrow();}finally{await rm(root,{recursive:true,force:true});}});
 it('loads the synthetic bundle with native numeric and rubric semantics and pinned version',async()=>{const read=(packs as unknown as{loadLockedPack:(root:string,directory:string)=>Promise<{pack:{version:string};assessment:{models:string[]}}>}).loadLockedPack;expect(read).toBeDefined();const result=await read('supabase/seed/curriculum','synthetic-primary-v1');expect(result.pack.version).toBe('synthetic-1');expect(result.assessment.models).toEqual(['numeric','rubric']);});
 it('refuses changed locked bytes even when the JSON stays structurally valid',async()=>{const root=await mkdtemp(join(tmpdir(),'cuevo-pack-'));try{await cp('supabase/seed/curriculum/synthetic-primary-v1',join(root,'pack'),{recursive:true});const path=join(root,'pack','assessment.json');await writeFile(path,(await readFile(path,'utf8')).replace('10','11'));await expect(packs.loadLockedPack(root,'pack')).rejects.toMatchObject({code:'CURRICULUM_REQUIRES_REVIEW'});}finally{await rm(root,{recursive:true,force:true});}});
 it('native adapter rejects wrong version and never creates normalization',async()=>{const bundle=await packs.loadLockedPack('supabase/seed/curriculum','synthetic-pathway-v1');const adapter=packs.createPackAdapter(bundle);expect(adapter.validateAssessmentConfiguration({version:'synthetic-1',model:'numeric',maxScore:10})).toBe(true);expect(adapter.validateAssessmentConfiguration({version:'other',model:'numeric',maxScore:10})).toBe(false);expect(bundle.assessment.numeric.normalization).toBeNull();});
 it('imports a valid child-before-parent artifact without losing its immutable parent relationship',async()=>{
  const root=await mkdtemp(join(tmpdir(),'cuevo-topology-'));try{
   await cp('supabase/seed/curriculum/synthetic-primary-v1',join(root,'pack'),{recursive:true});const normalized=JSON.parse(await readFile(join(root,'pack','normalized.json'),'utf8'))as{references:unknown[]};normalized.references.reverse();const bytes=JSON.stringify(normalized);await writeFile(join(root,'pack','normalized.json'),bytes);const manifest=JSON.parse(await readFile(join(root,'pack','manifest.json'),'utf8'));manifest.files['normalized.json']=createHash('sha256').update(bytes).digest('hex');await writeFile(join(root,'pack','manifest.json'),JSON.stringify(manifest));
   const writes:{type:string;parentId:string|null;id:string}[]=[];const ids:Record<string,string>={stage:'76000000-0000-4000-8000-000000000001',subject:'76000000-0000-4000-8000-000000000002',objective:'76000000-0000-4000-8000-000000000003'};
   const db={actorTransaction:async(_actor:string,_school:string,run:(client:unknown)=>Promise<unknown>)=>run({query:async(_sql:string,args:unknown[])=>{if(args[0]==='version.create')return{rows:[{receipt:{id:'75000000-0000-4000-8000-000000000001'}}]};const body=JSON.parse(String(args[2]));writes.push({type:body.type,parentId:body.parentId??null,id:ids[body.type]});return{rows:[{receipt:{id:ids[body.type]}}]};}})}as unknown as Database;
   const actor:ActorContext={userId:'20000000-0000-4000-8000-000000000001',schoolId:'10000000-0000-4000-8000-000000000001',membershipId:'21000000-0000-4000-8000-000000000001',role:'admin',entitlements:['curriculum']};await packs.importLockedPack(actor,db,root,'pack');
   expect(writes).toEqual([{type:'stage',parentId:null,id:ids.stage},{type:'subject',parentId:ids.stage,id:ids.subject},{type:'objective',parentId:ids.subject,id:ids.objective}]);
  }finally{await rm(root,{recursive:true,force:true});}
 });
 it('lists native subjects and validates exact version and reference ancestry for courses',async()=>{
  const bundle=await packs.loadLockedPack('supabase/seed/curriculum','synthetic-primary-v1');const adapter=packs.createPackAdapter(bundle)as unknown as{listSubjects:(context:{version?:string;stageKey?:string})=>{key:string}[];validateCourseConfiguration:(input:{version:string;subjectKey:string;referenceKey:string;stageKey?:string})=>{valid:boolean}};
  expect(adapter.listSubjects).toBeTypeOf('function');expect(adapter.validateCourseConfiguration).toBeTypeOf('function');expect(adapter.listSubjects({version:'synthetic-1',stageKey:'stage'}).map(subject=>subject.key)).toEqual(['mathematics']);expect(adapter.listSubjects({version:'wrong'})).toEqual([]);
  expect(adapter.validateCourseConfiguration({version:'synthetic-1',subjectKey:'mathematics',referenceKey:'explanation',stageKey:'stage'}).valid).toBe(true);for(const input of[{version:'wrong',subjectKey:'mathematics',referenceKey:'explanation'},{version:'synthetic-1',subjectKey:'unknown',referenceKey:'explanation'},{version:'synthetic-1',subjectKey:'mathematics',referenceKey:'stage'},{version:'synthetic-1',subjectKey:'mathematics',referenceKey:'explanation',stageKey:'unknown'}])expect(adapter.validateCourseConfiguration(input).valid).toBe(false);
 });
});
