import 'reflect-metadata';
import { afterEach, describe, expect, it } from 'vitest';
import { Module } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, type NestFastifyApplication } from '@nestjs/platform-fastify';
import type { PoolClient } from 'pg';
import type { Database } from '../../src/platform/database/database';
import { IdentityService } from '../../src/platform/identity/identity.service';
import { createLearnerObservationPolicyController } from '../../src/modules/learner-state/observation-policy.controller';
import { createApp } from '../../src/app';
import { parseServerConfig } from '@cuevo/config';
const schoolId='10000000-0000-4000-8000-000000000001';const userId='20000000-0000-4000-8000-000000000001';const sessionId='30000000-0000-4000-8000-000000000001';
const headers={authorization:'Bearer verified','x-school-id':schoolId,'idempotency-key':'reviewed-policy-original-key'};
let app:NestFastifyApplication;afterEach(async()=>{await app?.close();});
async function runtime(role='admin'){const queries:string[]=[];const identity=new IdentityService({verifyUser:async()=>({userId,sessionId}),isCurrentSession:async()=>true,currentMemberships:async()=>[{membership_id:sessionId,actor_id:userId,school_id:schoolId,school_name:'Reviewed school',display_name:'Current administrator',role,entitlement_codes:['school.context','learner.state']}]});const database={actorTransaction:async(_user:string,_school:string,run:(client:PoolClient)=>Promise<unknown>)=>run({query:async(sql:string)=>{queries.push(sql);return{rows:[{status:{schoolId,status:'UNCONFIGURED',policy:null},receipt:{id:sessionId,schoolId,version:1,developmentWindowDays:21,status:'APPROVED',refreshStatus:'PENDING'}}]};}}as unknown as PoolClient)}as unknown as Database;const controller=createLearnerObservationPolicyController(identity,database);@Module({controllers:[controller]})class FixtureModule{}app=await NestFactory.create<NestFastifyApplication>(FixtureModule,new FastifyAdapter({logger:false}),{logger:false});await app.init();await app.getHttpAdapter().getInstance().ready();return queries;}
describe('learner observation policy protected HTTP boundary',()=>{
 it('composes normal API GET/POST without credentials or outbound requests',async()=>{const normal=await createApp(parseServerConfig({},'api'));try{for(const method of ['GET','POST']as const){const response=await normal.app.inject({method,url:'/v1/learner-observation-policy',headers:{'x-school-id':schoolId},...(method==='POST'?{payload:{}}:{})});expect(response.statusCode).toBe(401);expect(response.headers['cache-control']).toBe('no-store');}}finally{await normal.close();}});
 it('requires school context and deliberate explicit approval',async()=>{const queries=await runtime();const missing=await app.inject({method:'GET',url:'/v1/learner-observation-policy',headers:{authorization:'Bearer verified'}});expect(missing.statusCode).toBe(400);const read=await app.inject({method:'GET',url:'/v1/learner-observation-policy',headers});expect(read.statusCode).toBe(200);expect(read.json()).toEqual({schoolId,status:'UNCONFIGURED',policy:null});const rejected=await app.inject({method:'POST',url:'/v1/learner-observation-policy',headers,payload:{developmentWindowDays:21,expectedVersion:0,reason:'Reviewed.',confirmApproval:false}});expect(rejected.statusCode).toBe(400);const approved=await app.inject({method:'POST',url:'/v1/learner-observation-policy',headers,payload:{developmentWindowDays:21,expectedVersion:0,reason:'Reviewed.',confirmApproval:true}});expect(approved.statusCode).toBe(200);expect(approved.headers['cache-control']).toBe('no-store');expect(approved.json()).toMatchObject({status:'APPROVED',refreshStatus:'PENDING'});expect(queries).toHaveLength(2);});
 it.each(['teacher','coordinator','student','parent'])('denies %s mutation before SQL',async role=>{const queries=await runtime(role);const response=await app.inject({method:'POST',url:'/v1/learner-observation-policy',headers,payload:{developmentWindowDays:21,expectedVersion:0,reason:'Reviewed.',confirmApproval:true}});expect(response.statusCode).toBe(403);expect(queries).toEqual([]);});
 it.each(['teacher','coordinator'])('allows current %s minimized setup read',async role=>{const queries=await runtime(role);const response=await app.inject({method:'GET',url:'/v1/learner-observation-policy',headers});expect(response.statusCode).toBe(200);expect(response.json()).toEqual({schoolId,status:'UNCONFIGURED',policy:null});expect(queries).toHaveLength(1);});
 it.each(['student','parent'])('denies %s administrative setup read',async role=>{const queries=await runtime(role);const response=await app.inject({method:'GET',url:'/v1/learner-observation-policy',headers});expect(response.statusCode).toBe(403);expect(queries).toEqual([]);});
});
