'use client';
import { useState } from 'react';
import { Button, CuevoIcon, Status } from '@cuevo/ui';
import { accessDirectoryEn, accessDirectoryAr } from '../access-directory-messages';
import type { AccessDirectoryKind, AccessDirectoryRow } from '../access-directory-model';

export function AccessDirectory({ locale, kind, rows, selectedId, query, locked, statusLabel, onKind, onQuery, onSelect }: { locale: 'en' | 'ar'; kind: AccessDirectoryKind; rows: AccessDirectoryRow[]; selectedId: string | null; query: string; locked: boolean; statusLabel: (value: unknown) => string; onKind: (kind: AccessDirectoryKind) => void; onQuery: (value: string) => void; onSelect: (row: AccessDirectoryRow) => void }) {
  const t = locale === 'ar' ? accessDirectoryAr : accessDirectoryEn;
  const [expanded, setExpanded] = useState(false);
  const labels = { person: t.people, enrollment: t.enrollment, assignment: t.assignment, guardian: t.guardian };
  return <section className="school-access-directory" aria-label={t.records} data-selected={!!selectedId} data-expanded={expanded}><div className="school-access-directory__groups" role="group" aria-label={t.title}>{(Object.keys(labels) as AccessDirectoryKind[]).map(key => <Button key={key} type="button" variant="quiet" aria-pressed={kind === key} disabled={locked} onClick={() => { setExpanded(false); onKind(key); }}>{labels[key]}</Button>)}</div>{selectedId ? <Button type="button" className="school-access-directory__change" variant="quiet" disabled={locked} aria-expanded={expanded} onClick={() => setExpanded(value => !value)}>{t.change}</Button> : null}<div className="school-access-directory__search field"><label htmlFor="school-access-directory-search">{t.search}</label><input id="school-access-directory-search" type="search" value={query} disabled={locked} onChange={event => onQuery(event.target.value)} /></div><p className="learning-form__note">{t.partial}</p><div className="school-access-directory__rows">{rows.length ? <ul>{rows.map(row => <li key={row.id}><button type="button" disabled={locked || row.requiresReview} aria-current={selectedId === row.id ? 'true' : undefined} aria-label={`${t.review}: ${row.title} · ${row.context}`} onClick={() => { setExpanded(false); onSelect(row); }}><CuevoIcon name={kind === 'guardian' ? 'parent' : kind === 'person' ? 'person' : 'school'} size={28}/><span><strong><bdi>{row.title}</bdi></strong><small><bdi>{row.context}</bdi></small></span><Status tone={row.status === 'active' ? 'positive' : 'neutral'}>{statusLabel(row.status)}</Status><CuevoIcon name="arrow" size={18} className="directional-icon" /></button></li>)}</ul> : <p role="status">{t.noMatches}</p>}</div></section>;
}
