'use client';
import { WorkspaceState } from '@cuevo/ui';
import { useCallback, useEffect, useState, useSyncExternalStore, type ReactNode } from 'react';
import { Button, CuevoIcon, Status } from '@cuevo/ui';
import { schoolTimetableForDate, type AttendanceRow, type SchoolPerson, type SchoolRow, type ScheduleRow } from '../model';
import { useApp } from '../../../shared/session/providers';
import { usePaginatedLearningQuery } from '../../../shared/hooks/use-paginated-query';
import { LoadMore } from '../../../shared/components/load-more';
import { CommandForm, type FormField } from '../../../shared/components/command-form';
import { schoolAr, schoolEn } from '../messages';
import { SchoolRecords } from './records';
import { RecordMaintenance } from './record-maintenance';
import { LearningApiError } from '../../../shared/api/client';
import { LearningError } from '../../../shared/components/feedback';
import { attendanceCreationCurrent, currentDailyReview, attendanceBody, attendanceDraftKey, attendancePath, attendanceRecovery, attendanceReview, attendanceRosterChoices, dailyAttendance, dailyCalendar, parseAttendanceReview, parseAttendanceRoster, validateAttendanceReceipt, type AttendanceReview } from '../daily-review-model';
import { DailyContextLayout } from './daily-context-layout';
import { schoolRecordChoices, schoolPersonChoices } from '../selection';
export type DailySource={loaded:boolean;loading:boolean;loadingMore:boolean;error:LearningApiError|null;moreError:LearningApiError|null;nextCursor:string|null;loadMore:()=>void};
type Sources={attendance:DailySource;timetable:DailySource;calendar:DailySource;periods:DailySource;classes:DailySource;subjects:DailySource;terms:DailySource;people:DailySource};
export function SchoolDaily({ attendance, timetable, calendar, periods, terms, classes, subjects, people, canAdmin, canAttend, onChanged, selectedClass, day, onDayChange, onClassChange, sources, classControl, pageHeading = false }: { attendance: AttendanceRow[]; timetable: SchoolRow[]; calendar: ScheduleRow[]; periods: SchoolRow[]; terms: SchoolRow[]; classes: SchoolRow[]; subjects: SchoolRow[]; people: SchoolPerson[]; canAdmin: boolean; canAttend: boolean; onChanged: () => void; selectedClass:string;day:string;onDayChange:(day:string)=>void;onClassChange:(classId:string)=>void;sources:Sources;classControl?:ReactNode;pageHeading?:boolean }) {
  const app=useApp();const {locale,membership,formDrafts,commandJournal}=app;const t=locale==='ar'?schoolAr:schoolEn;
  useSyncExternalStore(commandJournal.subscribe,commandJournal.getSnapshot,commandJournal.getSnapshot);
  const intentSlot=`${membership?.schoolId}:${membership?.userId}:${attendancePath}:intent`;
  const [review,setReview]=useState<AttendanceReview|null>(()=>parseAttendanceReview(formDrafts.model(intentSlot)));
  const [action,setAction]=useState<'attendance'|'timetable'|'calendar'|'report-periods'|null>(()=>review||commandJournal.get(attendancePath)?'attendance':(['timetable','calendar','report-periods']as const).find(value=>formDrafts.get(`${membership?.schoolId}:${membership?.userId}:/v1/school/${value}`))??null);
  const [learnerId,setLearnerId]=useState('');const[locked,setLocked]=useState(false);const [rosterRefresh,setRosterRefresh]=useState(0);
  const onLocked=useCallback((value:boolean)=>setLocked(value),[]);
  const retained=commandJournal.get(attendancePath),recovery=attendanceRecovery(retained);
  const sameReview=review&&recovery&&review.classId===recovery.review.classId&&review.learnerId===recovery.review.learnerId&&review.occurredOn===recovery.review.occurredOn&&review.expectedRevision===recovery.review.expectedRevision;
  const currentReview=recovery?(sameReview?review!:recovery.review):currentDailyReview(review,selectedClass,day);
  const sourceLocked=locked||!!retained;
  const editClass=currentReview?.classId??selectedClass;
  useEffect(()=>{setLearnerId('');},[selectedClass,day]);
  const rosterScope=JSON.stringify([app.apiUrl,membership?.schoolId,membership?.userId,membership?.role,app.accessToken,app.accessGeneration,app.online,editClass,rosterRefresh]);
  const parseRoster=useCallback((value:unknown)=>{const row=parseAttendanceRoster(value,editClass);return{id:row.id,scope:rosterScope,value:row};},[editClass,rosterScope]);
  const learners=usePaginatedLearningQuery(canAttend&&editClass?`/v1/school/attendance-roster?limit=100&classId=${encodeURIComponent(editClass)}`:null,parseRoster,rosterRefresh);
  const rosterRows=learners.data.flatMap(row=>row.scope===rosterScope?[row.value]:[]),choices=attendanceRosterChoices(rosterRows,locale);
  const rosterComplete=learners.loaded&&!learners.loading&&!learners.error&&!learners.moreError&&!learners.nextCursor;
  const classesComplete=sources.classes.loaded&&!sources.classes.loading&&!sources.classes.error&&!sources.classes.moreError&&!sources.classes.nextCursor;
  const attendanceComplete=sources.attendance.loaded&&!sources.attendance.loading&&!sources.attendance.error&&!sources.attendance.moreError&&!sources.attendance.nextCursor;
  const correction=currentReview?.sourceId?attendance.find(row=>row.id===currentReview.sourceId&&row.classId===currentReview.classId&&row.learnerId===currentReview.learnerId&&row.occurredOn===currentReview.occurredOn&&row.revision===currentReview.expectedRevision):null;
  const name=(row:SchoolRow,key:string)=>typeof row[key]==='string'&&String(row[key]).trim()?String(row[key]):t.nameUnavailable;
  const selectedClassRow=classes.find(row=>row.id===editClass);const className=typeof selectedClassRow?.name==='string'?selectedClassRow.name:null;
  const chosenLearner=currentReview?.learnerId??learnerId;
  const learner=rosterRows.find(row=>row.id===chosenLearner);
  const classChoices=schoolRecordChoices(classes,'classes',locale);
  const permittedChoice=classesComplete&&classChoices.some(choice=>choice.value===editClass&&!choice.requiresReview)&&!!className&&!String(className).includes(t.nameUnavailable)&&selectedClassRow?.status==='active'&&rosterComplete&&choices.some(choice=>choice.value===chosenLearner&&!choice.requiresReview);
  const creationCurrent=!currentReview||!!recovery||attendanceCreationCurrent(currentReview,attendance);
  const canReview=permittedChoice&&creationCurrent&&attendanceComplete&&!!currentReview&&(!currentReview.sourceId||!!correction||!!recovery)&&(!retained||!!recovery);
  useEffect(()=>{if(learners.error||sources.attendance.error){formDrafts.clearRead(`${membership?.schoolId}:${membership?.userId}:`,attendancePath);setReview(null);}},[learners.error,sources.attendance.error,formDrafts,membership?.schoolId,membership?.userId]);
  const names=Object.fromEntries([...rosterRows.map(row=>[row.id,row.displayName]),...classes.map(row=>[row.id,String(row.name)]),...subjects.map(row=>[row.id,String(row.name)]),...people.map(row=>[row.id,row.displayName])]);
  const options=(rows:SchoolRow[])=>rows.length&&'displayName'in rows[0]?schoolPersonChoices(rows as SchoolPerson[],locale).filter(choice=>!choice.requiresReview):schoolRecordChoices(rows,rows===classes?'classes':rows===terms?'terms':'subjects',locale).filter(choice=>!choice.requiresReview);const select=(field:string,label:string,rows:SchoolRow[]):FormField=>({name:field,label,type:'select',required:true,options:options(rows)});
  const adminFields:Record<'timetable'|'calendar'|'report-periods',FormField[]>={timetable:[select('classId',t.class,classes),select('subjectId',t.subject,subjects),select('teacherId',t.teacher,people.filter(person=>person.role==='teacher')),{name:'dayOfWeek',label:t.dayOfWeek,type:'select',required:true,options:Array.from({length:7},(_,value)=>({value:String(value),label:new Intl.DateTimeFormat(locale,{weekday:'long',timeZone:'UTC'}).format(new Date(Date.UTC(2026,0,4+value)))}))},{name:'startsAt',label:t.timeStart,type:'time',required:true},{name:'endsAt',label:t.timeEnd,type:'time',required:true},{name:'effectiveFrom',label:t.startsOn,type:'date',required:true},{name:'effectiveTo',label:t.endsOn,type:'date',required:true},{name:'location',label:t.location}],calendar:[{name:'classId',label:t.class,type:'select',options:options(classes)},{name:'title',label:t.name,required:true},{name:'description',label:t.description,type:'textarea',maxLength:2000},{name:'startsAt',label:t.startsAt,type:'datetime-local',required:true},{name:'endsAt',label:t.endsAt,type:'datetime-local',required:true},{name:'parentVisible',label:t.parentVisible,type:'checkbox'}],'report-periods':[select('termId',t.term,terms),{name:'name',label:t.name,required:true},{name:'startsOn',label:t.startsOn,type:'date',required:true},{name:'endsOn',label:t.endsOn,type:'date',required:true},{name:'parentVisible',label:t.parentVisible,type:'checkbox'}]};
  const adminSourcesComplete=[sources.classes,sources.subjects,sources.terms,sources.people].every(source=>source.loaded&&!source.loading&&!source.error&&!source.moreError&&!source.nextCursor);
  const adminTitles={timetable:t.createTimetable,calendar:t.createCalendar,'report-periods':t.createPeriod};
  function chooseReview(next:AttendanceReview|null){if(sourceLocked)return;if(next){onClassChange(next.classId);onDayChange(next.occurredOn);}setReview(next);if(next)formDrafts.saveModel(intentSlot,next);else formDrafts.remove(intentSlot);setAction('attendance');}
  function selectLearner(value:string){if(sourceLocked)return;setLearnerId(value);const row=attendance.find(row=>row.classId===selectedClass&&row.learnerId===value&&row.occurredOn===day);chooseReview(value&&selectedClass&&day?row?attendanceReview(row):{classId:selectedClass,learnerId:value,occurredOn:day,expectedRevision:0,sourceId:null}:null);}
  function saved(){formDrafts.remove(intentSlot);setReview(null);setAction(null);onChanged();}
  const fieldStatus:FormField={name:'status',label:t.status,type:'select',required:true,options:['present','absent','late','excused'].map(value=>({value,label:t[value as 'present']})),defaultValue:correction?.status};
  const fields:FormField[]=[fieldStatus,{name:'note',label:t.note,type:'textarea',maxLength:1000,defaultValue:correction?.note??''},...(currentReview&&currentReview.expectedRevision>0?[{name:'correctionReason',label:t.correctionReason,type:'textarea' as const,required:true,maxLength:1000}]:[])];
  const date=(value:string)=>new Intl.DateTimeFormat(locale,{dateStyle:'medium',...(value.includes('T')?{timeStyle:'short' as const}:{}),timeZone:'UTC'}).format(new Date(value));
  const records=dailyAttendance(attendance,selectedClass,day),sessions=schoolTimetableForDate(timetable.filter(row=>!selectedClass||row.classId===selectedClass),day),events=dailyCalendar(calendar,selectedClass,day);
  const sourceState=(source:DailySource)=>source.loading?<WorkspaceState kind="loading" icon="refresh" description={t.loading} role="status"/>:source.error?<LearningError error={source.error}/>:null;
  const more=(source:DailySource,label:string)=><><LoadMore query={source} label={label}/>{source.nextCursor||source.moreError?<WorkspaceState kind="review" icon="calendar" description={t.dailyPartial}/>:null}</>;
  return <div className='school-staff-day'><header className='school-day-heading'><CuevoIcon name='calendar' size={24}/><div>{pageHeading ? null : <h2>{t.daily}</h2>}<p>{t.attendanceNote}</p></div></header><DailyContextLayout classControl={classControl} dateControl={<div className='school-day-filter'><div className='field'><label htmlFor='staff-school-date'>{t.dailyDate}</label><input id='staff-school-date' type='date' value={day} disabled={sourceLocked} onChange={event=>{if(!sourceLocked)onDayChange(event.target.value);}}/></div><details className="school-daily-time-context"><summary>UTC</summary><p>{t.dailyUtc}</p></details></div>}/>
    <div className='learning-actions'>{canAttend?<Button type='button' disabled={sourceLocked} onClick={()=>{chooseReview(null);setLearnerId('');}}>{t.recordAttendance}</Button>:null}{canAdmin?(['timetable','calendar','report-periods']as const).map(key=><Button type='button' key={key} variant='secondary' disabled={sourceLocked||!adminSourcesComplete} onClick={()=>setAction(key)}>{adminTitles[key]}</Button>):null}</div>
    {action==='attendance'&&canAttend?<section className='school-day-panel school-attendance-editor' aria-label={t.attendanceReview}><h2>{t.attendanceReview}</h2>{retained&&!recovery?<WorkspaceState kind="review" icon="check" description={t.dailyRecoveryInvalid}/>:null}{recovery?<p className='notice'>{t.attendanceOriginal}</p>:null}<p><bdi>{className??t.nameUnavailable}</bdi> · <time dateTime={currentReview?.occurredOn??day}>{currentReview?.occurredOn?date(currentReview.occurredOn):day?date(day):t.dailyChooseDate}</time></p>
      {!selectedClass&&!currentReview?<WorkspaceState kind="unknown" icon="school" description={t.dailyChooseClass}/>:null}{currentReview?.sourceId||recovery?<h3><bdi>{learner?.displayName??t.nameUnavailable}</bdi></h3>:<div className='field'><label htmlFor='attendance-learner'>{t.student}</label><select id='attendance-learner' value={chosenLearner} disabled={sourceLocked||!classesComplete||!rosterComplete||!attendanceComplete} onChange={event=>selectLearner(event.target.value)}><option value=''>{t.dailyChooseLearner}</option>{choices.map(choice=><option key={choice.value} value={choice.value} disabled={choice.requiresReview}>{choice.label}</option>)}</select></div>}
      {learners.loading?<WorkspaceState kind="loading" icon="refresh" description={t.loading} role="status"/>:learners.error?<LearningError error={learners.error}/>:null}{learners.error?<Button type='button' variant='secondary' onClick={()=>setRosterRefresh(value=>value+1)}>{t.refresh}</Button>:null}{more(learners,t.student)}{!rosterComplete||!attendanceComplete||!classesComplete?<WorkspaceState kind="review" icon="check" description={t.dailyReviewSources}/>:null}{rosterComplete&&!rosterRows.length?<WorkspaceState kind="empty" icon="people" description={t.noClassLearners}/>:null}{((currentReview?.sourceId&&!correction&&!recovery)||!creationCurrent)&&attendanceComplete?<WorkspaceState kind="review" icon="check" description={t.dailySourceChanged}/>:null}
      {canReview?<><dl className='school-attendance-context'><div><dt>{t.class}</dt><dd><bdi>{className}</bdi></dd></div><div><dt>{t.occurredOn}</dt><dd>{date(currentReview!.occurredOn)}</dd></div><div><dt>{t.student}</dt><dd><bdi>{learner!.displayName}</bdi></dd></div></dl>{recovery?<p className='notice'>{t.status}: {t[recovery.input.status]} · {t.note}: {recovery.input.note}{recovery.input.correctionReason?<> · {t.correctionReason}: {recovery.input.correctionReason}</>:null}</p>:null}<CommandForm key={attendanceDraftKey(currentReview!)} title={currentReview!.expectedRevision?t.correctAttendance:t.recordAttendance} path={attendancePath} draftKey={attendanceDraftKey(currentReview!)} fields={fields} body={values=>attendanceBody(currentReview!,values)} validateReceipt={validateAttendanceReceipt} onLockedChange={onLocked} onSaved={saved} onCancel={()=>{setAction(null);setReview(null);formDrafts.remove(intentSlot);}} note={t.attendanceNote}/></>:null}
    </section>:null}
    {action&&action!=='attendance'&&canAdmin&&adminSourcesComplete?<CommandForm key={action} title={adminTitles[action]} path={`/v1/school/${action}`} fields={adminFields[action]} body={values=>{for(const field of adminFields[action].filter(field=>['classId','subjectId','teacherId','termId'].includes(field.name))){const selected=values.get(field.name);if(selected&&!field.options?.some(option=>option.value===selected))throw new LearningApiError('invalid');}return Object.fromEntries(adminFields[action].map(field=>[field.name,field.type==='checkbox'?values.get(field.name)==='on':field.name==='dayOfWeek'?Number(values.get(field.name)):field.type==='datetime-local'?new Date(String(values.get(field.name))).toISOString():field.name==='classId'&&!values.get(field.name)?null:String(values.get(field.name))]));}} onLockedChange={onLocked} onSaved={()=>{setAction(null);onChanged();}} onCancel={()=>setAction(null)}/>:null}
    <div className='school-staff-day-layout'><section className='school-day-panel' aria-label={t.attendance}><h2>{t.attendance}</h2>{sourceState(sources.attendance)}{!day?<WorkspaceState kind="unknown" icon="calendar" description={t.dailyChooseDate}/>:!sources.attendance.loading&&!sources.attendance.error?records.length?<ul className='school-attendance-list'>{records.map(row=><li key={row.id}><div><h3><bdi>{name(row,'learnerName')}</bdi></h3><p><bdi>{name(row,'className')}</bdi> · {date(row.occurredOn)}</p><Status>{t[row.status]}</Status><details><summary>{t.dailyRecordDetails}</summary><p>{t.note}: {row.note??t.dailyNoteUnavailable}</p><p>{t.dailyRevision}: {new Intl.NumberFormat(locale).format(row.revision)}</p><p>{t.dailyRecordedAt}: {date(row.recordedAt)} · UTC</p></details></div>{canAttend?<Button type='button' variant='secondary' disabled={sourceLocked} onClick={()=>chooseReview(attendanceReview(row))}>{t.correctAttendance}</Button>:null}</li>)}</ul>:<WorkspaceState kind={sources.attendance.nextCursor || sources.attendance.moreError ? "review" : "empty"} icon="check" description={t.dailyNoAttendance}/>:null}{more(sources.attendance,t.attendance)}<details><summary>{t.dailyLoadedAttendance}</summary><SchoolRecords names={names} title={t.dailyLoadedAttendance} rows={attendance} source={sources.attendance} columns={[{key:'learnerId',label:t.student},{key:'classId',label:t.class},{key:'occurredOn',label:t.occurredOn},{key:'status',label:t.status},{key:'revision',label:t.dailyRevision}]}/></details></section>
    <div className='school-day-side'><section className='school-day-panel' aria-label={t.timetable}><h2>{t.timetable}</h2><p>{t.dailyScheduleNote}</p>{sourceState(sources.timetable)}{!day?<WorkspaceState kind="unknown" icon="calendar" description={t.dailyChooseDate}/>:!sources.timetable.loading&&!sources.timetable.error?sessions.length?<ol className='school-day-timeline'>{sessions.map(row=><li key={row.id}><bdi dir='ltr'>{String(row.startsAt)}–{String(row.endsAt)}</bdi><article><h3><bdi>{name(row,'subjectName')}</bdi></h3><p>{name(row,'className')}</p><p>{t.teacher}: {name(row,'teacherName')}</p><p>{t.location}: {name(row,'location')}</p></article></li>)}</ol>:<WorkspaceState kind={sources.timetable.nextCursor || sources.timetable.moreError ? "review" : "empty"} icon="calendar" description={t.dailyNoTimetable}/>:null}{more(sources.timetable,t.timetable)}</section>
    <section className='school-day-panel' aria-label={t.calendar}><h2>{t.calendar}</h2>{sourceState(sources.calendar)}{!day?<WorkspaceState kind="unknown" icon="calendar" description={t.dailyChooseDate}/>:!sources.calendar.loading&&!sources.calendar.error?events.length?<ul className='school-calendar-list'>{events.map(event=><li key={event.id}><h3>{name(event,'title')}</h3><p>{date(event.startsAt)}–{date(event.endsAt)} · UTC</p><p>{event.classId===null?t.dailySchoolWide:name(event,'className')}</p>{event.description?<p>{String(event.description)}</p>:null}</li>)}</ul>:<WorkspaceState kind={sources.calendar.nextCursor || sources.calendar.moreError ? "review" : "empty"} icon="calendar" description={t.dailyNoEvents}/>:null}{more(sources.calendar,t.calendar)}</section>
    <section className='school-day-panel' aria-label={t.periods}><h2>{t.periods}</h2>{sourceState(sources.periods)}{!sources.periods.loading&&!sources.periods.error?periods.filter(row=>typeof row.startsOn==='string'&&typeof row.endsOn==='string'&&!!day&&row.startsOn<=day&&row.endsOn>=day).map(row=><article key={row.id}><h3>{name(row,'name')}</h3><p>{date(String(row.startsOn))}–{date(String(row.endsOn))}</p></article>):null}{more(sources.periods,t.periods)}</section></div></div>
    <details className='school-day-panel'><summary>{t.dailyAllSchedule}</summary><SchoolRecords names={names} title={t.timetable} rows={timetable} source={sources.timetable} columns={[{key:'classId',label:t.class},{key:'subjectId',label:t.subject},{key:'teacherId',label:t.teacher},{key:'dayOfWeek',label:t.dayOfWeek},{key:'startsAt',label:t.timeStart},{key:'endsAt',label:t.timeEnd},{key:'effectiveFrom',label:t.startsOn},{key:'effectiveTo',label:t.endsOn},{key:'location',label:t.location}]}/><SchoolRecords names={names} title={t.calendar} rows={calendar} source={sources.calendar} columns={[{key:'title',label:t.name},{key:'startsAt',label:t.startsAt},{key:'endsAt',label:t.endsAt}]}/><SchoolRecords names={names} title={t.periods} rows={periods} source={sources.periods} columns={[{key:'name',label:t.name},{key:'startsOn',label:t.startsOn},{key:'endsOn',label:t.endsOn}]}/></details>
    {canAdmin?<><RecordMaintenance resource='calendar' rows={calendar} onChanged={onChanged}/><RecordMaintenance resource='timetable' rows={timetable} onChanged={onChanged}/><RecordMaintenance resource='report-periods' rows={periods} onChanged={onChanged}/>{more(sources.terms,t.terms)}{more(sources.subjects,t.subjects)}{more(sources.people,t.people)}</>:null}
  </div>;
}
