'use client';
import { useState } from 'react';
import { Button } from '@cuevo/ui';
import type { AttendanceRow, SchoolPerson, SchoolRow, ScheduleRow } from '../model';
import { useApp } from '../../../shared/session/providers';
import { useApiQuery } from '../../../shared/hooks/use-api';
import { parseList } from '../../../shared/api/responses';
import { CommandForm, type FormField } from '../../../shared/components/command-form';
import { schoolAr, schoolEn } from '../messages';
import { SchoolRecords } from './records';
import { LearningApiError } from '../../../shared/api/client';
import { LearningError } from '../../../shared/components/feedback';
const learnerChoices = (value: unknown) => parseList(value, item => { if (!item || typeof item !== 'object' || !('userId' in item) || !('displayName' in item) || !('role' in item)) throw new LearningApiError('invalid'); return item as { userId: string; displayName: string; role: string }; });
export function SchoolDaily({ attendance, timetable, calendar, periods, terms, classes, subjects, people, canAdmin, canAttend, onChanged }: { attendance: AttendanceRow[]; timetable: SchoolRow[]; calendar: ScheduleRow[]; periods: SchoolRow[]; terms: SchoolRow[]; classes: SchoolRow[]; subjects: SchoolRow[]; people: SchoolPerson[]; canAdmin: boolean; canAttend: boolean; onChanged: () => void }) {
  const { locale } = useApp(); const t = locale === 'ar' ? schoolAr : schoolEn; const [action, setAction] = useState<'attendance' | 'timetable' | 'calendar' | 'report-periods' | null>(null);
  const learners = useApiQuery(canAttend && !canAdmin ? '/v1/people?limit=100' : null, learnerChoices, 0);
  const learnerRows = canAdmin ? people.filter(person => person.role === 'student') : (learners.data ?? []).filter(person => person.role === 'student').map(person => ({ id: person.userId, displayName: person.displayName }));
  const options = (rows: SchoolRow[]) => rows.map(row => ({ value: row.id, label: String(row.name ?? row.displayName) })); const select = (name: string, label: string, rows: SchoolRow[]): FormField => ({ name, label, type: 'select', required: true, options: options(rows) });
  const fields: Record<string, FormField[]> = { attendance: [select('classId', t.class, classes), select('studentId', t.student, learnerRows), { name: 'occurredOn', label: t.occurredOn, required: true }, { name: 'status', label: t.status, type: 'select', required: true, options: ['present', 'absent', 'late', 'excused'].map(value => ({ value, label: t[value as 'present'] })) }, { name: 'note', label: t.note, type: 'textarea', maxLength: 1000 }, { name: 'expectedRevision', label: t.revision, type: 'number', min: 0, required: true, defaultValue: 0 }, { name: 'correctionReason', label: t.correctionReason }], timetable: [select('classId', t.class, classes), select('subjectId', t.subject, subjects), select('teacherId', t.teacher, people.filter(person => person.role === 'teacher')), { name: 'dayOfWeek', label: t.dayOfWeek, type: 'number', min: 0, max: 6, required: true }, { name: 'startsAt', label: t.timeStart, required: true }, { name: 'endsAt', label: t.timeEnd, required: true }, { name: 'effectiveFrom', label: t.startsOn, required: true }, { name: 'effectiveTo', label: t.endsOn, required: true }, { name: 'location', label: t.location }], calendar: [{ name: 'classId', label: t.class, type: 'select', options: options(classes) }, { name: 'title', label: t.name, required: true }, { name: 'description', label: t.description, type: 'textarea', maxLength: 2000 }, { name: 'startsAt', label: t.startsAt, type: 'datetime-local', required: true }, { name: 'endsAt', label: t.endsAt, type: 'datetime-local', required: true }, { name: 'parentVisible', label: t.parentVisible, type: 'checkbox' }], 'report-periods': [{ name: 'termId', label: t.term, required: true }, { name: 'name', label: t.name, required: true }, { name: 'startsOn', label: t.startsOn, required: true }, { name: 'endsOn', label: t.endsOn, required: true }, { name: 'parentVisible', label: t.parentVisible, type: 'checkbox' }] };
  fields['report-periods'][0] = select('termId', t.term, terms);
  const titles = { attendance: t.recordAttendance, timetable: t.createTimetable, calendar: t.createCalendar, 'report-periods': t.createPeriod };
  if (canAttend && !canAdmin && learners.loading) return <p role="status">{t.loading}</p>;
  if (canAttend && !canAdmin && learners.error) return <LearningError error={learners.error} />;
  return <div><p className="notice">{t.attendanceNote}</p><div className="learning-actions">{canAttend ? <Button type="button" onClick={() => setAction('attendance')}>{t.recordAttendance}</Button> : null}{canAdmin ? (['timetable', 'calendar', 'report-periods'] as const).map(key => <Button type="button" key={key} variant="secondary" onClick={() => setAction(key)}>{titles[key]}</Button>) : null}</div>{action ? <CommandForm title={titles[action]} path={`/v1/school/${action}`} fields={fields[action]} body={values => Object.fromEntries(fields[action].filter(field => field.name !== 'correctionReason' || values.get(field.name)).map(field => [field.name, field.type === 'checkbox' ? values.get(field.name) === 'on' : field.type === 'number' ? Number(values.get(field.name)) : field.type === 'datetime-local' ? new Date(String(values.get(field.name))).toISOString() : field.name === 'classId' && !values.get(field.name) ? null : String(values.get(field.name))]))} onSaved={() => { setAction(null); onChanged(); }} onCancel={() => setAction(null)} note={action === 'attendance' ? t.attendanceNote : undefined} /> : null}<SchoolRecords title={t.attendance} rows={attendance} columns={[{ key: 'learnerId', label: t.student }, { key: 'occurredOn', label: t.occurredOn }, { key: 'status', label: t.status }, { key: 'revision', label: t.revision }]} /><SchoolRecords title={t.timetable} rows={timetable} columns={[{ key: 'classId', label: t.class }, { key: 'dayOfWeek', label: t.dayOfWeek }, { key: 'startsAt', label: t.timeStart }, { key: 'endsAt', label: t.timeEnd }, { key: 'location', label: t.location }]} /><SchoolRecords title={t.calendar} rows={calendar} columns={[{ key: 'title', label: t.name }, { key: 'startsAt', label: t.startsAt }, { key: 'endsAt', label: t.endsAt }]} /><SchoolRecords title={t.periods} rows={periods} columns={[{ key: 'name', label: t.name }, { key: 'startsOn', label: t.startsOn }, { key: 'endsOn', label: t.endsOn }]} /></div>;
}
