'use client';
import { useCallback, useEffect, useState } from 'react';
import { Button, CuevoIcon } from '@cuevo/ui';
import { useApp } from '../../../shared/session/providers';
import { useApiQuery } from '../../../shared/hooks/use-api';
import { usePaginatedLearningQuery } from '../../../shared/hooks/use-paginated-query';
import { LearningError } from '../../../shared/components/feedback';
import { LoadMore } from '../../../shared/components/load-more';
import { parseCurrentSchoolContext, currentSchoolRead, parseSchoolRow, parseSchoolPerson, parseCurrentAttendance, parseSchedule, parseTimetable } from '../model';
import { schoolAr, schoolEn } from '../messages';
import { SchoolSetup } from './setup';
import { SchoolAccess } from './access';
import { SchoolDaily } from './daily';
import { SchoolDayRecords } from './school-day-records';
import { schoolDayAr, schoolDayEn } from '../day-messages';
import { canOpenWorkspace } from '../../../shared/session/capabilities';
import { SchoolPolicyForm } from './policy';
import { SchoolRecords } from './records';
import { SchoolAudit } from './audit';
import { SchoolAutomationReview,type AutomationControl } from './automation';
import{ApprovedSchoolContext}from'./approved-context';
import { ParentLearningSupport } from './parent-learning-support';
import { useChildContext } from '../../../shared/hooks/use-child-context';
import { schoolClassName } from "../labels";
import { ChildSelector } from '../../../shared/components/child-selector';

type Tab = 'setup' | 'people' | 'daily' | 'policies' | 'audit' | 'approvedContext' | 'automation' | 'parentSupport';
export function SchoolWorkspace({onAutomationControl}:{onAutomationControl?:(control:Exclude<AutomationControl,'policies'>)=>void}={}) {
  const { membership } = useApp();
  return <CurrentSchoolWorkspace key={`${membership?.schoolId}:${membership?.userId}:${membership?.role}`} onAutomationControl={onAutomationControl} />;
}
function CurrentSchoolWorkspace({onAutomationControl}:{onAutomationControl?:(control:Exclude<AutomationControl,'policies'>)=>void}) {
  const { membership, locale, status, online, apiUrl, accessGeneration, accessToken } = useApp(); const t = locale === 'ar' ? schoolAr : schoolEn;
  const admin = membership?.role === 'admin'; const staff = admin || membership?.role === 'coordinator' || membership?.role === 'teacher'; const directory = admin || membership?.role === 'coordinator';
  const permitted = status === 'ready' && online && !!membership && canOpenWorkspace('school', membership.entitlements, membership.role);
  const [tab, setTab] = useState<Tab>(admin ? 'setup' : 'daily'); const [refresh, setRefresh] = useState(0);
  const [selectedClass, setSelectedClass] = useState('');
  const [selectedDay, setSelectedDay] = useState('');
  useEffect(() => { const current = new Date(); setSelectedDay(`${current.getFullYear()}-${String(current.getMonth() + 1).padStart(2, '0')}-${String(current.getDate()).padStart(2, '0')}`); }, []);
  const childContext = useChildContext(refresh);
  const childCurrent = childContext.query.loaded && !childContext.query.loading && !childContext.query.error && !childContext.query.moreError && !childContext.query.nextCursor;
  const dailyScope = childContext.parent ? childCurrent && childContext.child ? `&learnerId=${encodeURIComponent(childContext.child.id)}` : null : selectedClass ? `&classId=${encodeURIComponent(selectedClass)}` : membership?.role === 'student' ? `&learnerId=${encodeURIComponent(membership.userId)}` : '';
  const scope = `${apiUrl}:${membership?.schoolId}:${membership?.userId}:${membership?.role}:${accessToken ?? ''}:${online}:${accessGeneration}:${refresh}`;
  const parseContext = useCallback((value: unknown) => ({ scope, value: parseCurrentSchoolContext(value, membership?.schoolId ?? '') }), [scope, membership?.schoolId]);
  const contextRead = useApiQuery(permitted ? '/v1/school/context' : null, parseContext, refresh);
  const context = { ...contextRead, data: currentSchoolRead(contextRead.data, scope) };
  const dailyLearnerId = childContext.parent ? childCurrent ? childContext.child?.id : undefined : membership?.role === 'student' ? membership.userId : undefined;
  const parseAttendance = useCallback((value: unknown) => parseCurrentAttendance(value, dailyLearnerId), [dailyLearnerId]);
  const readDaily = permitted && tab === 'daily' && dailyScope !== null;
  const structures = staff && permitted && ['setup', 'people', 'daily'].includes(tab);
  const years = usePaginatedLearningQuery(structures ? '/v1/school/years?limit=100' : null, parseSchoolRow, refresh);
  const terms = usePaginatedLearningQuery(structures && (tab !== 'daily' || admin) ? '/v1/school/terms?limit=100' : null, parseSchoolRow, refresh);
  const groups = usePaginatedLearningQuery(structures ? '/v1/school/year-groups?limit=100' : null, parseSchoolRow, refresh);
  const classes = usePaginatedLearningQuery(structures ? '/v1/school/classes?limit=100' : null, parseSchoolRow, refresh);
  const subjects = usePaginatedLearningQuery(structures ? '/v1/school/subjects?limit=100' : null, parseSchoolRow, refresh);
  const people = usePaginatedLearningQuery(directory && permitted && (tab === 'people' || tab === 'daily' && admin) ? '/v1/school/people?limit=100' : null, parseSchoolPerson, refresh);
  const enrollments = usePaginatedLearningQuery(directory && permitted && tab === 'people' ? '/v1/school/enrollments?limit=100' : null, parseSchoolRow, refresh);
  const assignments = usePaginatedLearningQuery(directory && permitted && tab === 'people' ? '/v1/school/teacher-assignments?limit=100' : null, parseSchoolRow, refresh);
  const guardians = usePaginatedLearningQuery(directory && tab === 'people' ? '/v1/school/guardian-relationships?limit=100' : null, parseSchoolRow, refresh);
  const entitlements = usePaginatedLearningQuery(directory && permitted && tab === 'policies' ? '/v1/school/entitlements?limit=100' : null, parseSchoolRow, refresh);
  const attendance = usePaginatedLearningQuery(readDaily ? `/v1/school/attendance?limit=100${dailyScope}` : null, parseAttendance, refresh);
  const timetable = usePaginatedLearningQuery(readDaily ? `/v1/school/timetable?limit=100${dailyScope}` : null, parseTimetable, refresh);
  const calendar = usePaginatedLearningQuery(readDaily ? `/v1/school/calendar?limit=100${dailyScope}` : null, parseSchedule, refresh);
  const periods = usePaginatedLearningQuery(structures && tab === 'daily' ? '/v1/school/report-periods?limit=100' : null, parseSchoolRow, refresh);
  function reload() { setRefresh(value => value + 1); }
  if (!permitted) return null;
  if (context.loading || !context.data && !context.error) return <p role="status">{t.loading}</p>;
  if (context.error) return <><LearningError error={context.error} /><Button type="button" variant="secondary" onClick={reload}>{locale === 'ar' ? 'المحاولة مجددًا' : 'Try again'}</Button></>;
  if (!context.data) return null;
  const tabs: Tab[] = [...(staff ? ['setup' as const,'approvedContext'as const] : []), ...(directory ? ['people' as const, 'policies' as const, ...(admin ? ['audit' as const,'automation'as const] : [])] : []), ...(childContext.parent ? ['parentSupport' as const] : []), 'daily'];
  const labelledClasses = classes.data.map(row => ({ ...row, name: schoolClassName(row, years.data, groups.data, t.nameUnavailable) }));
  const activeQueries = tab==='approvedContext'||tab==='automation'||tab==='parentSupport'?[]:tab === 'setup' ? [years, terms, groups, classes, subjects] : tab === 'people' ? [people, enrollments, assignments, guardians, classes, subjects] : tab === 'daily' ? [attendance, timetable, calendar, ...(staff ? [periods, classes, subjects, years, groups] : []), ...(admin ? [people, terms] : [])] : [entitlements];
  const activeError = activeQueries.find(query => query.error || query.moreError);
  const activeFailure = activeError?.error ?? activeError?.moreError;
  const activeLoading = activeQueries.some(query => query.loading);
  return <div className={`school-workspace ${staff ? 'school-workspace--staff' : 'school-workspace--learner'}`}><ChildSelector context={childContext} /><div className="learning-toolbar"><div className="learning-tabs" role="group" aria-label={t.school}>{tabs.map(value => <button key={value} type="button" aria-pressed={tab === value} onClick={() => setTab(value)}>{t[value]}</button>)}</div><Button type="button" variant="quiet" onClick={reload}><CuevoIcon name="refresh" />{t.refresh}</Button></div>{membership?.role === 'parent' ? <p className="notice">{t.parentNote}</p> : null}{tab === 'daily' && staff ? <div className="field"><label htmlFor="daily-class-filter">{t.dailyClass}</label><select id="daily-class-filter" value={selectedClass} onChange={event => setSelectedClass(event.target.value)}><option value="">{t.allCurrentClasses}</option>{labelledClasses.map(row => <option key={row.id} value={row.id}>{String(row.name)}</option>)}</select><LoadMore query={classes} /></div> : null}{tab==='parentSupport'&&childContext.parent?childCurrent&&childContext.child?<ParentLearningSupport key={childContext.child.id} learnerId={childContext.child.id} learnerName={childContext.child.displayName} refresh={refresh}/>:<p>{t.chooseParentSupportChild}</p>:tab==='automation'?<SchoolAutomationReview onControl={control=>{if(control==='policies')setTab('policies');else onAutomationControl?.(control);}}/>:tab==='approvedContext'?<ApprovedSchoolContext key={refresh}/>:tab === 'audit' ? <SchoolAudit /> : activeFailure ? <LearningError error={activeFailure} /> : activeLoading ? <p role="status">{t.loading}</p> : tab === 'setup' ? <SchoolSetup context={context.data} years={years.data} terms={terms.data} groups={groups.data} classes={classes.data} subjects={subjects.data} canManage={admin} onChanged={reload} /> : tab === 'people' ? <SchoolAccess people={people.data} enrollments={enrollments.data} assignments={assignments.data} guardians={guardians.data} classes={labelledClasses} subjects={subjects.data} canManage={admin} onChanged={reload} /> : tab === 'policies' ? <><SchoolPolicyForm key={context.data.policy.version} context={context.data} canManage={admin} onChanged={reload} /><SchoolRecords title={t.entitlements} rows={entitlements.data} columns={[{ key: 'code', label: t.name }, { key: 'enabled', label: t.status }]} /></> : !staff ? childContext.parent && (!childCurrent || !childContext.child) ? <p className="notice">{locale === 'ar' ? schoolDayAr.chooseChild : schoolDayEn.chooseChild}</p> : <><header className="school-day-intro"><CuevoIcon name="school" variant="filled" size={36} /><div><h2>{locale === 'ar' ? childContext.parent ? schoolDayAr.parentTitle : schoolDayAr.title : childContext.parent ? schoolDayEn.parentTitle : schoolDayEn.title}</h2><p>{locale === 'ar' ? childContext.parent ? schoolDayAr.parentBody : schoolDayAr.body : childContext.parent ? schoolDayEn.parentBody : schoolDayEn.body}</p></div></header><SchoolDayRecords key={`${membership?.userId}:${childContext.child?.id ?? ''}`} attendance={attendance.data} timetable={timetable.data} calendar={calendar.data} policy={context.data.policy} day={selectedDay} onDayChange={setSelectedDay} partial={[attendance, timetable, calendar].some(query => !!query.nextCursor)} /></> : <SchoolDaily attendance={attendance.data} timetable={timetable.data} calendar={calendar.data} periods={periods.data} terms={terms.data} classes={labelledClasses} subjects={subjects.data} people={people.data} canAdmin={admin} canAttend={admin || membership?.role === 'teacher'} onChanged={reload} />}{(tab === 'setup' ? [{ query: years, label: t.years }, { query: terms, label: t.terms }, { query: groups, label: t.yearGroups }, { query: classes, label: t.classes }, { query: subjects, label: t.subjects }] : tab === 'people' ? [{ query: people, label: t.people }, { query: enrollments, label: t.enrollment }, { query: assignments, label: t.assignment }, { query: guardians, label: t.guardian }, { query: classes, label: t.classes }, { query: subjects, label: t.subjects }] : tab === 'daily' ? [{ query: attendance, label: t.attendance }, { query: timetable, label: t.timetable }, { query: calendar, label: t.calendar }, { query: periods, label: t.periods }, { query: classes, label: t.classes }, { query: subjects, label: t.subjects }, { query: terms, label: t.terms }, { query: people, label: t.people }] : [{ query: entitlements, label: t.entitlements }]).map(({ query, label }, index) => <div key={index}>{query.moreError ? <LearningError error={query.moreError} /> : null}{query.nextCursor ? <LoadMore query={query} label={label} /> : null}</div>)}</div>;
}
