'use client';
import { useState } from 'react';
import { Button } from '@cuevo/ui';
import type { SchoolContext, SchoolRow } from '../model';
import { useApp } from '../../../shared/session/providers';
import { CommandForm, type FormField } from '../../../shared/components/command-form';
import { schoolAr, schoolEn } from '../messages';
import { SchoolRecords } from './records';
import { schoolClassName } from '../labels';
export function SchoolSetup({ context, years, terms, groups, classes, subjects, canManage, onChanged }: { context: SchoolContext; years: SchoolRow[]; terms: SchoolRow[]; groups: SchoolRow[]; classes: SchoolRow[]; subjects: SchoolRow[]; canManage: boolean; onChanged: () => void }) {
  const { locale, membership, formDrafts } = useApp(); const t = locale === 'ar' ? schoolAr : schoolEn;
  const retainedAction = Object.keys({ details: 1, years: 1, terms: 1, 'year-groups': 1, classes: 1, subjects: 1 }).find(key => formDrafts.get(`${membership?.schoolId}:${membership?.userId}:/v1/school/${key}`));
  const [action, setAction] = useState<string | null>(retainedAction ?? null);
  const options = (rows: SchoolRow[]) => rows.map(row => ({ value: row.id, label: String(row.name) }));
  const dateFields: FormField[] = [{ name: 'startsOn', label: t.startsOn, type: 'date', required: true }, { name: 'endsOn', label: t.endsOn, type: 'date', required: true }];
  const fields: Record<string, FormField[]> = { details: [{ name: 'name', label: t.name, required: true, defaultValue: context.school.name }, { name: 'countryCode', label: t.countryCode, required: true, defaultValue: context.school.countryCode }, { name: 'languages', label: t.languages, type: 'select', required: true, defaultValue: context.school.languages.length === 2 ? 'both' : context.school.languages[0], options: [{ value: 'both', label: 'English / العربية' }, { value: 'en', label: 'English' }, { value: 'ar', label: 'العربية' }] }], years: [{ name: 'name', label: t.name, required: true }, ...dateFields], terms: [{ name: 'academicYearId', label: t.year, type: 'select', required: true, options: options(years) }, { name: 'name', label: t.name, required: true }, ...dateFields], 'year-groups': [{ name: 'name', label: t.name, required: true }, { name: 'ordinal', label: t.ordinal, type: 'number', min: 0, max: 100, required: true }], classes: [{ name: 'academicYearId', label: t.year, type: 'select', required: true, options: options(years) }, { name: 'yearGroupId', label: t.yearGroup, type: 'select', required: true, options: options(groups) }, { name: 'name', label: t.name, required: true }], subjects: [{ name: 'name', label: t.name, required: true }] };
  const titles: Record<string, string> = { details: t.details, years: t.createYear, terms: t.createTerm, 'year-groups': t.createYearGroup, classes: t.createClass, subjects: t.createSubject };
  return <div><h2>{context.school.name}</h2>{canManage ? <div className="learning-actions">{Object.entries(titles).map(([key, label]) => <Button key={key} type="button" variant="secondary" onClick={() => setAction(key)}>{label}</Button>)}</div> : null}{action ? <CommandForm title={titles[action]} path={`/v1/school/${action}`} fields={fields[action]} body={values => Object.fromEntries(fields[action].map(field => [field.name, field.name === 'ordinal' ? Number(values.get(field.name)) : field.name === 'languages' ? values.get(field.name) === 'both' ? ['en', 'ar'] : [String(values.get(field.name))] : String(values.get(field.name))]))} onSaved={() => { setAction(null); onChanged(); }} onCancel={() => setAction(null)} /> : null}<SchoolRecords title={t.years} rows={years} columns={[{ key: 'name', label: t.name }, { key: 'startsOn', label: t.startsOn }, { key: 'endsOn', label: t.endsOn }]} /><SchoolRecords title={t.terms} rows={terms} columns={[{ key: 'name', label: t.name }, { key: 'startsOn', label: t.startsOn }, { key: 'endsOn', label: t.endsOn }]} /><SchoolRecords title={t.yearGroups} rows={groups} columns={[{ key: 'name', label: t.name }, { key: 'ordinal', label: t.ordinal }]} /><SchoolRecords title={t.classes} rows={classes.map(row => ({ ...row, name: schoolClassName(row, years, groups, t.nameUnavailable) }))} columns={[{ key: 'name', label: t.name }, { key: 'status', label: t.status }]} /><SchoolRecords title={t.subjects} rows={subjects} columns={[{ key: 'name', label: t.name }]} /></div>;
}
