import assert from'node:assert/strict';import test from'node:test';import{registerHooks}from'node:module';import React,{createElement}from'react';import{renderToStaticMarkup}from'react-dom/server';import{CommandJournal,LearningApiError,captureCommandReceiptValidator,confirmCommandReceipt,type CommandReceiptValidator}from'../../../shared/api/client.ts';import{FormDrafts}from'../../../shared/session/form-drafts.ts';import{getDictionary}from'../../../shared/i18n/locale.ts';
const id='00000000-0000-4000-8000-000000000001',next='00000000-0000-4000-8000-000000000002';
const fixture={app:{}as Record<string,unknown>,forms:[]as {path:string;fields:unknown[];validateReceipt:CommandReceiptValidator}[]};Object.assign(globalThis,{React,portfolioNestedRecoveryFixture:fixture});
registerHooks({load(url,context,nextLoad){const path=url.replaceAll('\\','/');if(path.endsWith('/shared/session/providers.tsx'))return{format:'module',shortCircuit:true,source:'export function useApp(){return globalThis.portfolioNestedRecoveryFixture.app}'};if(path.endsWith('/shared/hooks/use-api.ts'))return{format:'module',shortCircuit:true,source:`export function useApi(){return {t:{errorDenied:'Denied'}}}export function useApiQuery(){return{data:null,loading:false,error:{kind:'denied'}}}`};if(path.endsWith('/shared/components/command-form.tsx'))return{format:'module',shortCircuit:true,source:'export function CommandForm(props){globalThis.portfolioNestedRecoveryFixture.forms.push(props);return null}'};return nextLoad(url,context);}});
const{PortfolioSourceWork}=await import('../components/source-work.tsx'),{PortfolioDocumentSelection}=await import('../components/document-selection.tsx');
const item={id,revisionId:id,revision:1,learnerId:id,evidenceId:id,resultId:id,submissionId:id,referenceId:id,referenceVersion:'v1',policyVersion:2,sourceModel:'numeric'as const,submissionKind:'TEXT'as const,responseKind:'TEXT'as const,artifactCount:0,title:'My explanation',reflection:'Private reflection.',createdAt:'2026-10-03T00:00:00Z',feedback:null,featured:false,approvalState:'AWAITING_REVIEW'as const,parentVisible:false,reviewedAt:null,nativeResult:{type:'numeric'as const,score:0,maxScore:10,policyVersion:2},assessmentTitle:'Explain a check',referenceTitle:'Check a method',identity:{status:'READY'as const,learnerName:'Lina',className:'Cedar',yearGroupName:'Year 4',academicYearName:'2026–2027',courseTitle:'Reasoning',assessmentTitle:'Explain a check',submittedAt:'2026-10-03T00:00:00Z',submissionRevision:1}};
test('denied nested text source owners expose exactly one original retry and validate its immutable receipt',()=>{
 for(const kind of ['review','reflection']as const){fixture.forms=[];const journal=new CommandJournal(),path=`/v1/portfolio/items/${id}/${kind}`,command=journal.prepare(path,path,{expectedRevision:1,feedback:'Original feedback',assetIds:[]});fixture.app={locale:'en',dictionary:getDictionary('en'),online:true,status:'ready',accessGeneration:2,accessToken:'synthetic',apiUrl:'https://fixture.invalid',membership:{schoolId:'school',userId:id,role:kind==='review'?'teacher':'student'},formDrafts:new FormDrafts(),commandJournal:journal};renderToStaticMarkup(kind==='review'?createElement(PortfolioSourceWork,{item,reviewing:true,onSaved(){},onCancel(){}}):createElement(PortfolioDocumentSelection,{item,onSaved(){},onCancel(){}}));
 assert.equal(fixture.forms.length,1);assert.deepEqual(fixture.forms[0].fields,[]);const validate=captureCommandReceiptValidator(command,fixture.forms[0].validateReceipt);const good={id,revisionId:kind==='review'?id:next,revision:kind==='review'?1:2,status:kind==='review'?'REVIEWED':'AWAITING_REVIEW'};
 for(const wrong of [{...good,id:next},{...good,revision:3},{...good,revisionId:kind==='review'?next:id}])assert.throws(()=>confirmCommandReceipt(journal,path,command.key,wrong,undefined,validate),LearningApiError);
 assert.equal(journal.get(path)?.key,command.key);assert.equal(confirmCommandReceipt(journal,path,command.key,good,undefined,validate),true);assert.equal(journal.get(path),undefined);
 }
});
