import { expectTrailWorkspace, signOutTrailWorkspace } from './trail-workspace';
import{test,expect,type Page,type Locator}from'@playwright/test';import{readFile}from'node:fs/promises';import AxeBuilder from'@axe-core/playwright';
type Account={role:string;email:string;password:string};async function find(page:Page,row:Locator){await expect(page.locator('main [role="status"]').filter({hasText:/^Loading/})).toHaveCount(0);for(let n=0;n<30&&!await row.count();n++){const more=page.getByRole('button',{name:'Load more',exact:true}).first();if(!await more.count())break;await more.click();await expect(page.getByRole('button',{name:'Loading more…',exact:true})).toHaveCount(0);}await expect(row).toBeVisible();}
test('current group member selects an exact mention recipient and recipient opens source before read',async({page})=>{
 test.setTimeout(30000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});const accounts=JSON.parse(await readFile('.local/synthetic-accounts.json','utf8'))as Account[];const teacher=accounts.find(account=>account.role==='teacher')!;const student=accounts.find(account=>account.role==='student')!;const key=process.env.SUPABASE_PUBLISHABLE_KEY;if(!key)throw Error('Synthetic Auth configuration required.');const auth=await page.request.post(`${process.env.SUPABASE_URL}/auth/v1/token?grant_type=password`,{headers:{apikey:key},data:{email:teacher.email,password:teacher.password}});const token=(await auth.json()).access_token;const title=`Explicit checking mention ${new Date().toISOString()}`;const created=await page.request.post('http://localhost:4000/v1/community/rooms',{headers:{Authorization:`Bearer ${token}`,'X-School-Id':'10000000-0000-4000-8000-000000000001','Idempotency-Key':crypto.randomUUID()},data:{classId:'30000000-0000-4000-8000-000000000001',name:title,type:'GROUP',memberIds:['20000000-0000-4000-8000-000000000012']}});expect(created.ok()).toBe(true);const room=(await created.json())as{id:string};let rosterRequests=0;page.on('request',request=>{if(new URL(request.url()).pathname===`/v1/community/rooms/${room.id}/roster`)rosterRequests++;});
 async function signIn(account:Account){await page.goto('/');await page.getByRole('button',{name:'English',exact:true}).click();await page.getByLabel('School email').fill(account.email);await page.getByLabel('Password',{exact:true}).fill(account.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expectTrailWorkspace(page, account.role);await page.locator('.workspace-chrome__navigation').getByRole('button',{name:'Community',exact:true}).click();}
 await signIn(student);const row=page.locator(`[data-room-id="${room.id}"]`);await find(page,row);const rosterResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/community/rooms/${room.id}/roster`&&response.request().method()==='GET');await row.getByRole('button',{name:'Open discussion',exact:true}).click();const roster=await rosterResponse;expect(roster.ok()).toBe(true);expect((await roster.json()).items.some((person:{role:string})=>person.role==='teacher')).toBe(true);const recipients=page.getByRole('group',{name:'Mention current members (at most five)',exact:true});await expect(recipients.getByRole('checkbox')).not.toHaveCount(0);await expect(page.getByText('Private updates connected',{exact:true})).toBeVisible();await expect(page.locator('main [role="status"]').filter({hasText:/^Loading/})).toHaveCount(0);await expect.poll(()=>rosterRequests,{timeout:3000,intervals:[100,200,400]}).toBeGreaterThan(0);const settledRosterRequests=rosterRequests;await recipients.getByRole('checkbox').first().check();await page.waitForTimeout(500);expect(rosterRequests).toBe(settledRosterRequests);const form=page.getByRole('region',{name:'Post to room',exact:true});await form.getByLabel('Message').fill('Please review this checking step with me.');const posted=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/community/rooms/${room.id}/posts`&&response.request().method()==='POST');await form.getByRole('button',{name:'Post to room',exact:true}).click();const post=await posted;expect(post.request().postDataJSON().mentionActorIds).toHaveLength(1);expect(post.ok()).toBe(true);await signOutTrailWorkspace(page);
 await signIn(teacher);await page.getByRole('button',{name:'Notifications',exact:true}).click();const notice=page.locator('.community-post').filter({has:page.getByRole('heading',{name:title,exact:true})});await find(page,notice);await notice.getByRole('button',{name:'Open mentioned post',exact:true}).click();await expect(notice.getByText('Please review this checking step with me.',{exact:true})).toBeVisible();await notice.getByRole('region',{name:'Confirm I read this post',exact:true}).getByRole('button',{name:'Confirm I read this post',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'العربية',exact:true}).click();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);expect(errors).toEqual([]);
});


