import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile, mkdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
type Account = { role: string; email: string; password: string };
test('current class discussion supports safe reactions, reporting and staff moderation with approved parent announcements', async ({ page }) => {
  test.setTimeout(90_000); const accounts = JSON.parse(await readFile('.local/synthetic-accounts.json', 'utf8')) as Account[]; const teacher = accounts.find(item => item.role === 'teacher')!; const student = accounts.find(item => item.role === 'student')!; const parent = accounts.find(item => item.role === 'parent')!;
  const signIn = async (account: Account) => { await page.goto('/'); if (await page.getByRole('button', { name: 'English', exact: true }).isVisible()) await page.getByRole('button', { name: 'English', exact: true }).click(); await page.getByLabel('School email').fill(account.email); await page.getByLabel('Password', { exact: true }).fill(account.password); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await page.getByRole('button', { name: 'Community', exact: true }).click(); };
  const signOut = async () => { await page.getByRole('button', { name: 'Sign out', exact: true }).last().click(); await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible(); };
  const title = `Community ${randomUUID().slice(0, 6)}`; const waitMutation = (suffix: string) => page.waitForResponse(response => response.url().endsWith(suffix) && response.request().method() === 'POST');
  await signIn(teacher); await expect(page.getByText('Loading community…', { exact: true })).toHaveCount(0); let roomName = title; const existing = page.locator('.community-room[data-room-type="CLASS"]').first(); let form;
  if (await existing.count()) roomName = await existing.getByRole('heading').innerText(); else { await page.getByRole('button', { name: 'Create teacher-led room', exact: true }).click(); form = page.getByRole('region', { name: 'Create teacher-led room', exact: true }); await form.getByLabel('Class', { exact: true }).selectOption('30000000-0000-4000-8000-000000000001'); await form.getByLabel('Room name', { exact: true }).fill(title); await form.getByLabel('Room type', { exact: true }).selectOption('CLASS'); await form.getByRole('button', { name: 'Save', exact: true }).click(); }
  const openRoom = async () => { const row = page.locator('.community-room').filter({ has: page.getByRole('heading', { name: roomName, exact: true }) }); await expect(row).toBeVisible(); await row.getByRole('button', { name: 'Open discussion', exact: true }).click(); };
  await openRoom(); await expect(page.getByText('Private updates connected', { exact: true })).toBeVisible({ timeout: 20_000 }); await signOut();
  await signIn(student); await openRoom(); form = page.getByRole('region', { name: 'Post to room', exact: true }); await form.getByLabel('Message', { exact: true }).fill(`${title} synthetic contribution`); const posted = waitMutation('/posts'); await form.getByRole('button', { name: 'Post to room', exact: true }).click(); const postResponse = await posted; expect(postResponse.ok()).toBe(true); const post = await postResponse.json() as { id: string }; let postRow = page.locator(`[data-post-id="${post.id}"]`); await expect(postRow).toContainText(`${title} synthetic contribution`); await postRow.getByRole('button', { name: 'Thanks', exact: true }).click(); await postRow.getByRole('button', { name: 'Report post', exact: true }).click(); form = page.getByRole('region', { name: 'Report post', exact: true }); await form.getByLabel('Reason', { exact: true }).fill('Synthetic staff review request.'); const refetched = page.waitForResponse(response => response.url().includes('/rooms/') && response.url().includes('/posts?')); await page.getByRole('button', { name: 'Refresh community', exact: true }).click(); expect((await refetched).ok()).toBe(true); await expect(form.getByLabel('Reason', { exact: true })).toHaveValue('Synthetic staff review request.'); await form.getByRole('button', { name: 'Save', exact: true }).click(); await signOut();
  await signIn(teacher); await openRoom(); postRow = page.locator(`[data-post-id="${post.id}"]`); await postRow.getByRole('button', { name: 'Hide post', exact: true }).click(); form = page.getByRole('region', { name: 'Staff review', exact: true }); await form.getByLabel('Reason', { exact: true }).fill('Staff chose to hide synthetic content.'); await expect(form.getByLabel('I approve this moderation action')).not.toBeChecked(); await form.getByLabel('I approve this moderation action').check(); await form.getByRole('button', { name: 'Save', exact: true }).click(); await expect(postRow).toContainText('This post was hidden by school moderation.'); await expect(postRow).not.toContainText(`${title} synthetic contribution`);
  await page.getByRole('button', { name: 'Back to rooms', exact: true }).click(); await page.getByRole('button', { name: 'Announcements', exact: true }).click(); await page.getByRole('button', { name: 'Publish announcement', exact: true }).click(); form = page.getByRole('region', { name: 'Publish announcement', exact: true }); await form.getByLabel('Class', { exact: true }).selectOption('30000000-0000-4000-8000-000000000001'); await form.getByLabel('Title', { exact: true }).fill(`${title} approved announcement`); await form.getByLabel('Message', { exact: true }).fill('Synthetic class update for current families.'); await expect(form.getByLabel('Approve this announcement for current parents / guardians')).not.toBeChecked(); await form.getByLabel('Approve this announcement for current parents / guardians').check(); await form.getByRole('button', { name: 'Save', exact: true }).click(); await signOut();
  await signIn(parent); await expect(page.getByRole('button', { name: 'Class rooms and groups', exact: true })).toHaveCount(0); await expect(page.getByRole('heading', { name: `${title} approved announcement`, exact: true })).toBeVisible(); await page.setViewportSize({ width: 390, height: 844 }); await page.getByRole('button', { name: 'العربية', exact: true }).click(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]); await mkdir('.local/technical-mvp-visuals', { recursive: true }); await page.screenshot({ path: '.local/technical-mvp-visuals/community-parent-ar-mobile.png' });
});
