import { test, expect, type Page } from '@playwright/test';
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'../..');
async function mount(page:Page,shared=false){
 const built=await build({stdin:{resolveDir:root,loader:'tsx',contents:`
 import React,{createContext,useContext,useState}from'react';import{createRoot}from'react-dom/client';import{CurriculumWorkspace}from'./apps/web/features/curriculum/components/curriculum-workspace';import{CommandForm}from'./apps/web/shared/components/command-form';import{CommandJournal}from'./apps/web/shared/api/client';import{FormDrafts}from'./apps/web/shared/session/form-drafts';const C=createContext(null);globalThis.configContext=C;globalThis.configUseContext=useContext;const id=n=>'b7000000-0000-4000-8000-'+String(n).padStart(12,'0'),journal=new CommandJournal(),drafts=new FormDrafts(),course={id:id(1),title:'School checking',classId:id(2),subjectId:id(3),description:'School-authored course',status:'PUBLISHED',createdAt:'2026-10-03T00:00:00Z',units:[],curriculumContext:{version:1,programmeId:null,referenceId:null}};globalThis.configFixture={journal,drafts,writes:[],reads:[],original:null};globalThis.fetch=async(input,init)=>{const f=globalThis.configFixture,path=String(input);f.reads.push(path);if(init?.method==='POST'){f.writes.push(path);throw Error('Configuration writes are forbidden')}return new Response(JSON.stringify(path.startsWith('/v1/courses/')?course:{items:path.startsWith('/v1/courses?')?[course]:path.startsWith('/v1/classes')?[{id:id(2),name:'Cedar'}]:path.startsWith('/v1/subjects')?[{id:id(3),name:'Mathematics'}]:[],nextCursor:null}),{status:200,headers:{'Content-Type':'application/json'}})};
 function Harness(){const[locale,setLocale]=useState('en'),[hide,setHide]=useState(false),[generation,setGeneration]=useState(1);return<C.Provider value={{locale,membership:{schoolId:id(10),userId:id(11),role:'admin',entitlements:['curriculum']},apiUrl:'',accessToken:'synthetic',accessGeneration:generation,status:'ready',online:true,formDrafts:drafts,commandJournal:journal,announce(){},reportDiagnostic(){},refreshAccess(){}}}><main dir={locale==='ar'?'rtl':'ltr'}><button id='locale' onClick={()=>setLocale(x=>x==='en'?'ar':'en')}>Language</button><button id='hide' onClick={()=>setHide(x=>!x)}>Heading treatment</button><button id='pending' onClick={()=>{const path=${shared?"'/v1/shared-heading'":"'/v1/curriculum/courses/'+id(1)"};globalThis.configFixture.original=structuredClone(journal.prepare(path,path,${shared?"{reason:'Unsent current reason'}":"{expectedVersion:1,programmeId:id(4),referenceId:id(5),confirmConfiguration:true}"}));setGeneration(x=>x+1)}}>Original pending</button>${shared?"<h1>Current form action</h1><CommandForm title='Current form action' regionLabel='Current named review' showHeading={!hide} path='/v1/shared-heading' fields={[{name:'reason',label:locale==='ar'?'سبب المراجعة':'Review reason',required:true}]} body={v=>({reason:String(v.get('reason'))})} onSaved={()=>{}}/>":'<CurriculumWorkspace/>'}</main></C.Provider>}createRoot(document.getElementById('root')).render(<Harness/>);
 `},bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',plugins:[{name:'current-config-owner',setup(bundler){bundler.onLoad({filter:/shared[\\/]session[\\/]providers\.tsx$/},()=>({loader:'js',contents:'export function useApp(){return globalThis.configUseContext(globalThis.configContext)}'}));bundler.onLoad({filter:/\.(png|webp|svg)$/},args=>({loader:'js',contents:'export default '+JSON.stringify({src:'data:image/webp;base64,'+readFileSync(args.path).toString('base64'),width:128,height:128})}));}}]});
 await page.setContent('<div id="root"></div>');await page.addScriptTag({content:"if(!crypto.randomUUID)crypto.randomUUID=()=> '30000000-0000-4000-8000-000000000001';"});await page.addScriptTag({content:built.outputFiles[0].text});
}
test('shared form keeps its default heading and hidden heading preserves region fields unsent input and original retry',async({page})=>{
 await mount(page,true);const form=page.getByRole('region',{name:'Current named review',exact:true});await expect(form.getByRole('heading',{name:'Current form action',level:3,exact:true})).toBeVisible();await form.getByLabel('Review reason',{exact:true}).fill('Unsent current reason');await page.locator('#hide').click();await expect(form.getByRole('heading')).toHaveCount(0);await expect(form.getByLabel('Review reason',{exact:true})).toHaveValue('Unsent current reason');await expect(form.getByRole('button',{name:'Save',exact:true})).toBeVisible();await page.locator('#locale').click();await expect(form.getByLabel('سبب المراجعة',{exact:true})).toHaveValue('Unsent current reason');await page.locator('#pending').click();await expect(form.getByRole('button',{name:'إعادة الإجراء نفسه',exact:true})).toBeVisible();await expect(form.getByLabel('سبب المراجعة',{exact:true})).toHaveValue('Unsent current reason');await page.locator('#hide').click();await expect(form.getByRole('heading',{name:'Current form action',level:3,exact:true})).toBeVisible();expect(await page.evaluate(()=>(globalThis as unknown as {configFixture:{journal:{pending:()=>unknown[]};original:unknown}}).configFixture.journal.pending())).toEqual([await page.evaluate(()=>(globalThis as unknown as {configFixture:{original:unknown}}).configFixture.original)]);expect(await page.evaluate(()=>(globalThis as unknown as {configFixture:{writes:unknown[]}}).configFixture.writes)).toEqual([]);
});
test('every current Curriculum configuration uses one page title without duplicated form headings in English and Arabic',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await mount(page);const actions=[['Record source context','تسجيل سياق مصدر'],['Create synthetic reference','إنشاء مرجع اصطناعي'],['Configure programme','إعداد برنامج'],['Link course context','ربط سياق مقرر'],['Assign learner programme','تعيين برنامج لطالب'],['Record framework overlay','تسجيل إطار مستقل']];for(const locale of['en','ar']){if(locale==='ar')await page.locator('#locale').click();for(const titles of actions){const title=titles[locale==='ar'?1:0];await page.locator('.curriculum-workspace__actions').getByRole('button',{name:title,exact:true}).click();if(titles[0]==='Link course context')await page.locator('#curriculum-course').selectOption('b7000000-0000-4000-8000-000000000001');await expect(page.locator('.curriculum-workspace__editor form')).toHaveCount(1);await expect(page.getByRole('heading',{name:title,exact:true})).toHaveCount(1);await expect(page.locator('.curriculum-workspace__editor .learning-form').getByRole('heading')).toHaveCount(0);await expect(page.locator('.curriculum-workspace__editor .learning-form form')).toBeVisible();await expect(page.locator('.curriculum-workspace__editor .learning-form button[type="submit"]')).toBeVisible();await page.locator('.curriculum-workspace__editor-heading button').click();}}await page.locator('#locale').click();await page.locator('.curriculum-workspace__actions').getByRole('button',{name:'Link course context',exact:true}).click();await page.locator('#curriculum-course').selectOption('b7000000-0000-4000-8000-000000000001');await page.locator('.curriculum-workspace__editor .learning-form input[name="confirmConfiguration"]').check();await page.locator('#pending').click();await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toBeVisible();await expect(page.locator('.curriculum-workspace__editor-heading button')).toBeDisabled();await expect(page.getByRole('heading',{name:'Link course context',exact:true})).toHaveCount(1);await expect(page.locator('.curriculum-workspace__editor .learning-form input[name="confirmConfiguration"]')).toBeChecked();expect(await page.evaluate(()=>(globalThis as unknown as {configFixture:{writes:unknown[]}}).configFixture.writes)).toEqual([]);expect(errors).toEqual([]);
});
