import { expectTrailWorkspace, signOutTrailWorkspace } from './trail-workspace';
import { test, expect, type Page, type Locator } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { createHash, randomUUID } from 'node:crypto';
import AxeBuilder from '@axe-core/playwright';
import { humanContextLabel, selectHumanChoice } from './human-choice';
type Account={role:string;email:string;password:string};const schoolId='10000000-0000-4000-8000-000000000001';
async function findPaged(page:Page,row:Locator){await expect.poll(async()=>await row.count()>0||await page.getByRole('button',{name:'Load more',exact:true}).count()>0).toBe(true);for(let pageNumber=0;pageNumber<30&&!await row.count();pageNumber++){const more=page.getByRole('button',{name:'Load more',exact:true}).first();if(!await more.count())break;await more.click();await expect(page.getByRole('button',{name:'Loading more…',exact:true})).toHaveCount(0);}await expect(row).toBeVisible(); const openTask = row.getByRole('button', { name: 'Open task', exact: true }); if (await openTask.count()) await openTask.click();}
test('learner uploads actual documents, teacher reviews exact work and parent downloads only the approved revision',async({page})=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);const accounts=JSON.parse(await readFile('.local/synthetic-accounts.json','utf8'))as Account[];const teacher=accounts.find(account=>account.role==='teacher')!;const student=accounts.find(account=>account.role==='student')!;const parent=accounts.find(account=>account.role==='parent')!;const key=process.env.SUPABASE_PUBLISHABLE_KEY;if(!key)throw Error('Synthetic Auth configuration required.');const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&/hydration|did not match/i.test(message.text()))errors.push(message.text());});
 async function token(account:Account){const response=await page.request.post(`${process.env.SUPABASE_URL}/auth/v1/token?grant_type=password`,{headers:{apikey:key!},data:{email:account.email,password:account.password}});expect(response.ok()).toBe(true);return(await response.json()).access_token as string;}
 const teacherToken=await token(teacher);async function command(path:string,body:Record<string,unknown>){const response=await page.request.post('http://localhost:4000'+path,{headers:{Authorization:`Bearer ${teacherToken}`,'X-School-Id':schoolId,'Idempotency-Key':randomUUID()},data:body});expect(response.ok(),`Synthetic setup ${response.status()}`).toBe(true);return await response.json()as{id:string;evidenceId:string};}
 const title=`Document checking explanation ${new Date().toISOString()}`;const bytes=Buffer.from('Actual document answer. راجعت الخطوة الأصلية.');const sha256=createHash('sha256').update(bytes).digest('hex');const file={name:'إجابة التحقق.txt',mimeType:'text/plain',buffer:bytes};const course=await command('/v1/courses',{classId:'30000000-0000-4000-8000-000000000001',subjectId:'43000000-0000-4000-8000-000000000001',title,description:'Synthetic document source regression.'});await command(`/v1/courses/${course.id}/publish`,{});const assessment=await command('/v1/assessments',{courseId:course.id,title,instructions:'Submit the actual explanation document.',maxScore:10});await command(`/v1/assessments/${assessment.id}/reference`,{referenceId:'61000000-0000-4000-8000-000000000001',expectedPolicyVersion:1});
 async function signIn(account:Account,destination:string){await page.goto('/');await page.getByRole('button',{name:'English',exact:true}).click();await page.getByLabel('School email').fill(account.email);await page.getByLabel('Password',{exact:true}).fill(account.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expectTrailWorkspace(page, account.role);await page.locator('.workspace-chrome__navigation').getByRole('button',{name:destination,exact:true}).click();}
 async function signOut(){await page.getByRole('button',{name:'English',exact:true}).click();await signOutTrailWorkspace(page);await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();}
 await signIn(student,'Learning');await page.getByRole('button',{name:'Assessments',exact:true}).click();let task=page.locator('.assessment-section').filter({has:page.getByRole('heading',{name:title,exact:true})});await findPaged(page,task);await task.getByRole('button',{name:'Attach work documents',exact:true}).click();let work=task.getByRole('region',{name:'Submit work with documents',exact:true});await expect(work.getByLabel('Response type')).toBeVisible();await work.getByLabel('Choose work document').setInputFiles(file);await work.getByRole('button',{name:'Upload and verify work document',exact:true}).click();await expect(work.getByText(file.name,{exact:true})).toBeVisible();await work.getByLabel('Response type').selectOption('FILE');await work.getByRole('button',{name:'Save work draft',exact:true}).click();let form=work.getByRole('region',{name:'Save work draft',exact:true});const draftSaved=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/assessments/${assessment.id}/work-draft`&&response.request().method()==='POST');await form.getByRole('button',{name:'Save work draft',exact:true}).click();expect((await draftSaved).ok()).toBe(true);
 await page.reload();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();await signIn(student,'Learning');await page.getByRole('button',{name:'Assessments',exact:true}).click();task=page.locator('.assessment-section').filter({has:page.getByRole('heading',{name:title,exact:true})});await findPaged(page,task);await task.getByRole('button',{name:'Attach work documents',exact:true}).click();work=task.getByRole('region',{name:'Submit work with documents',exact:true});await expect(work.getByLabel('Response type')).toHaveValue('FILE');await expect(work.getByText(file.name,{exact:true})).toBeVisible();form=work.getByRole('region',{name:'Submit document work',exact:true});const submittedResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/assessments/${assessment.id}/work-submissions`&&response.request().method()==='POST');await form.getByRole('button',{name:'Submit document work',exact:true}).click();const submission=await(await submittedResponse).json()as{id:string;artifacts:{id:string;sha256:string}[]};expect(submission.artifacts[0].sha256).toBe(sha256);await expect(task.getByRole('region',{name:'Submitted work',exact:true})).toBeVisible();await signOut();
 await signIn(teacher,'Academic');const queueItem=page.locator('.marking-queue__item').filter({hasText:title});await findPaged(page,queueItem);await queueItem.click();const marking=page.locator('.marking-detail');const exactDownload=page.waitForEvent('download');await marking.getByRole('button',{name:'Download work document',exact:true}).click();expect((await exactDownload).suggestedFilename()).toBe(file.name);
 form=marking.getByRole('region',{name:'Save marking draft',exact:true});await form.getByLabel('Score (0–10)',{exact:true}).fill('6');await form.getByLabel('Teacher feedback').fill('Teacher checked this exact submitted document.');await form.getByRole('button',{name:'Save marking draft',exact:true}).click();await expect(marking.getByRole('button',{name:'Release result',exact:true})).toBeVisible();await marking.getByRole('button',{name:'Release result',exact:true}).click();form=marking.getByRole('region',{name:'Release result',exact:true});await form.getByLabel('Approve this released result for the current parent / guardian view').check();const releasedResponse=page.waitForResponse(response=>/\/v1\/results\/[^/]+\/release$/.test(new URL(response.url()).pathname)&&response.request().method()==='POST');await form.getByRole('button',{name:'Release result',exact:true}).click();const released=await(await releasedResponse).json()as{id:string;evidenceId:string};await signOut();
 await signIn(student,'Portfolio');await page.getByRole('button',{name:'Select released work',exact:true}).click();form=page.getByRole('region',{name:'Select released work',exact:true});const releasedChoices=page.locator('.portfolio-workspace > .notice').filter({has:page.getByText('Released source evidence',{exact:true})});const releasedChoice=await selectHumanChoice(form.getByLabel('Released source evidence'),humanContextLabel(title),released.evidenceId,releasedChoices);expect(releasedChoice.label).toContain('Objective: Synthetic school-authored explanation objective');expect(releasedChoice.label).toContain('Result revision: 1');expect(releasedChoice.label).toContain('Released:');await form.getByLabel('Portfolio title').fill(title);await form.getByLabel('What I learned').fill('First exact document reflection.');const selectedResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/v1/portfolio/items'&&response.request().method()==='POST');await form.getByRole('button',{name:'Save',exact:true}).click();const item=await(await selectedResponse).json()as{id:string;revisionId:string};await signOut();
 await signIn(teacher,'Portfolio');let row=page.locator(`[data-portfolio-id="${item.id}"]`);await findPaged(page,row);await row.getByRole('button',{name:'Review selected work',exact:true}).click();const source=row.getByRole('region',{name:'Source work',exact:true});await expect(source.getByRole('region',{name:'Review selected work',exact:true})).toHaveCount(0);const reviewDownload=page.waitForEvent('download');await source.getByRole('button',{name:'Download selected work document',exact:true}).click();expect((await reviewDownload).suggestedFilename()).toBe(file.name);form=source.getByRole('region',{name:'Review selected work',exact:true});await form.getByLabel('I reviewed this exact submitted work and reflection').check();await form.getByLabel('Teacher feedback').fill('Reviewed exact document and reflection.');await form.getByLabel('Share this exact revision with current parents / guardians').check();await form.getByLabel('I approve parent sharing of this reviewed revision').check();await form.getByRole('button',{name:'Save',exact:true}).click();await expect(row.getByText('Teacher reviewed',{exact:true})).toBeVisible();await signOut();
 await signIn(parent,'Portfolio');await page.getByLabel('Child',{exact:true}).selectOption('20000000-0000-4000-8000-000000000012');row=page.locator(`[data-portfolio-id="${item.id}"]`);await findPaged(page,row);await row.getByRole('button',{name:'Source work',exact:true}).click();const parentDownload=page.waitForEvent('download');await row.getByRole('button',{name:'Download selected work document',exact:true}).click();const downloaded=await parentDownload;expect(downloaded.suggestedFilename()).toBe(file.name);const downloadedPath=await downloaded.path();if(!downloadedPath)throw Error('Exact parent document download required.');expect(createHash('sha256').update(await readFile(downloadedPath)).digest('hex')).toBe(sha256);await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'العربية',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);expect(errors).toEqual([]);await signOut();
 await signIn(teacher,'Portfolio');await findPaged(page,row);await row.getByRole('button',{name:'Revoke parent sharing',exact:true}).click();form=row.getByRole('region',{name:'Revoke parent sharing',exact:true});await form.getByLabel('Reason').fill('School revokes this exact document sharing.');await form.getByRole('button',{name:'Save',exact:true}).click();await signOut();await signIn(parent,'Portfolio');await page.getByLabel('Child',{exact:true}).selectOption('20000000-0000-4000-8000-000000000012');await expect(page.locator('main [role="status"]').filter({hasText:/^Loading/})).toHaveCount(0);await expect(row).toHaveCount(0);
});




test('closed returned document work remains readable with feedback and no editable draft',async({page})=>{
 test.setTimeout(60000);const accounts=JSON.parse(await readFile('.local/synthetic-accounts.json','utf8'))as Account[];const teacher=accounts.find(account=>account.role==='teacher')!;const student=accounts.find(account=>account.role==='student')!;const key=process.env.SUPABASE_PUBLISHABLE_KEY;if(!key)throw Error('Synthetic Auth configuration required.');
 async function token(account:Account){const response=await page.request.post(`${process.env.SUPABASE_URL}/auth/v1/token?grant_type=password`,{headers:{apikey:key!},data:{email:account.email,password:account.password}});expect(response.ok()).toBe(true);return(await response.json()).access_token as string;}
 const teacherToken=await token(teacher);const studentToken=await token(student);async function command(path:string,body:Record<string,unknown>,accessToken=teacherToken){const response=await page.request.post('http://localhost:4000'+path,{headers:{Authorization:`Bearer ${accessToken}`,'X-School-Id':schoolId,'Idempotency-Key':randomUUID()},data:body});expect(response.ok(),`Synthetic closed source setup ${response.status()}`).toBe(true);return await response.json()as{id:string};}
 const title=`Closed document feedback ${new Date().toISOString()}`;const bytes=Buffer.from('Historical returned document answer.');const sha256=createHash('sha256').update(bytes).digest('hex');const course=await command('/v1/courses',{classId:'30000000-0000-4000-8000-000000000001',subjectId:'43000000-0000-4000-8000-000000000001',title,description:'Synthetic returned source history.'});await command(`/v1/courses/${course.id}/publish`,{});const assessment=await command('/v1/assessments',{courseId:course.id,title,instructions:'Review returned historical document.',maxScore:10});const staged=await command(`/v1/assessments/${assessment.id}/work-assets`,{name:'Returned explanation.txt',contentType:'text/plain',byteSize:bytes.length,sha256},studentToken);await command(`/v1/assessments/${assessment.id}/work-assets/${staged.id}/finalize`,{contentBase64:bytes.toString('base64')},studentToken);const submission=await command(`/v1/assessments/${assessment.id}/work-submissions`,{responseKind:'FILE',content:'',assetIds:[staged.id]},studentToken);await command(`/v1/submissions/${submission.id}/return`,{feedback:'Check the second step when the teacher reopens this task.',expectedRevision:1});await command(`/v1/assessments/${assessment.id}/availability`,{availableFrom:null,availableUntil:null,allowLate:true,state:'CLOSED',expectedAvailabilityVersion:1});
 let draftReads=0;page.on('request',request=>{if(new URL(request.url()).pathname===`/v1/assessments/${assessment.id}/work-draft`)draftReads++;});await page.goto('/');await page.getByRole('button',{name:'English',exact:true}).click();await page.getByLabel('School email').fill(student.email);await page.getByLabel('Password',{exact:true}).fill(student.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expectTrailWorkspace(page);await page.locator('.workspace-chrome__navigation').getByRole('button',{name:'Learning',exact:true}).click();await page.getByRole('button',{name:'Assessments',exact:true}).click();const task=page.locator('.assessment-section').filter({has:page.getByRole('heading',{name:title,exact:true})});await findPaged(page,task);await expect(task.getByText('Check the second step when the teacher reopens this task.',{exact:false})).toBeVisible();await expect(task.getByRole('button',{name:'Attach work documents',exact:true})).toHaveCount(0);await expect(task.getByLabel('Response type')).toHaveCount(0);await expect(task.getByRole('region',{name:'Submit document work',exact:true})).toHaveCount(0);const download=page.waitForEvent('download');await task.getByRole('button',{name:'Download work document',exact:true}).click();const result=await download;expect(result.suggestedFilename()).toBe('Returned explanation.txt');expect(draftReads).toBe(0);await signOutTrailWorkspace(page);
});
