import { test, expect, type Page } from '@playwright/test';
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import AxeBuilder from '@axe-core/playwright';

const root=resolve(import.meta.dirname,'../..');
const css=['packages/ui/src/tokens.css','apps/web/app/globals.css','apps/web/features/development/styles.css'].map(file=>readFileSync(resolve(root,file),'utf8').replace(/@import[^;]+;/g,'')).join('\n');
async function mount(page:Page,pending=false){const script=(await build({stdin:{resolveDir:root,loader:'tsx',contents:`
import React,{createContext,useContext,useState}from'react';import{createRoot}from'react-dom/client';import{DevelopmentWorkspace}from'./apps/web/features/development/components/development-workspace';import{CommandJournal}from'./apps/web/shared/api/client';import{FormDrafts}from'./apps/web/shared/session/form-drafts';import{getDictionary}from'./apps/web/shared/i18n/locale';
if(!crypto.randomUUID)crypto.randomUUID=()=> 'ec000000-0000-4000-8000-000000000009';const C=createContext(null);globalThis.developmentStateC=C;globalThis.developmentStateUC=useContext;const learner='ec000000-0000-4000-8000-000000000001',period='ec000000-0000-4000-8000-000000000002',policy='ec000000-0000-4000-8000-000000000003',journal=new CommandJournal(),drafts=new FormDrafts();if('__PENDING__'==='yes')journal.prepare('/v1/development/leaderboard/participation','/v1/development/leaderboard/participation',{periodId:period,optIn:false,alias:'Original source alias'});const f=globalThis.developmentStateFixture={reads:[],writes:[],mode:'hold',release:null,journal,pending:journal.pending()};globalThis.fetch=async(input,init)=>{const u=new URL(String(input));if(init?.method==='POST'){f.writes.push(u.pathname);throw Error('No protected write permitted');}f.reads.push(u.pathname);if(u.pathname==='/v1/development/summary'){if(f.mode==='hold'){let release;const wait=new Promise(done=>release=done);f.release=()=>release();await wait;}if(f.mode==='summary-error'||f.mode==='ledger-error')return new Response(JSON.stringify({code:'SERVICE_UNAVAILABLE'}),{status:503});return new Response(JSON.stringify({learnerId:learner,periodId:period,status:'RECORDED_ONLY',totalPoints:0,leaderboardEnabled:false,streak:{status:'UNOBSERVED',basis:'VERIFIED_RECOGNIZED_ACTION_DAYS',timezone:'UTC',days:null,endingOn:null,recordedDays:null,sourceCount:null}}),{status:200});}if(u.pathname==='/v1/development/ledger'&&f.mode==='ledger-error')return new Response(JSON.stringify({code:'SERVICE_UNAVAILABLE'}),{status:503});const items=u.pathname==='/v1/development/periods'?[{id:period,classId:'ec000000-0000-4000-8000-000000000004',policyId:policy,title:'Current learning period',startsAt:'2026-10-01T00:00:00Z',endsAt:'2026-10-31T00:00:00Z'}]:[];return new Response(JSON.stringify({items,nextCursor:null}),{status:200});};function Harness(){const[locale,setLocale]=useState('en');globalThis.developmentStateLocale=setLocale;return<C.Provider value={{locale,dictionary:getDictionary(locale),membership:{schoolId:'ec000000-0000-4000-8000-000000000005',userId:learner,role:'student',entitlements:['learning','learner.state']},status:'ready',online:true,apiUrl:'https://fixture.invalid',accessToken:'synthetic',accessGeneration:1,commandJournal:journal,formDrafts:drafts,announce(){},reportDiagnostic(){},refreshAccess(){}}}><div className='workspace'><main className='workspace-main'><DevelopmentWorkspace/></main></div></C.Provider>}createRoot(document.getElementById('root')).render(<Harness/>);
`.replace('__PENDING__',pending?'yes':'no')},bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',loader:{'.webp':'dataurl','.png':'dataurl','.svg':'dataurl'},plugins:[{name:'actual-development-session-boundary',setup(b){b.onLoad({filter:/\.(webp|png|svg)$/},args=>({loader:'js',contents:'export default '+JSON.stringify({src:'data:image/webp;base64,'+readFileSync(args.path).toString('base64'),width:128,height:128})}));b.onLoad({filter:/shared[\\/]session[\\/]providers\.tsx$/},()=>({loader:'js',contents:'export function useApp(){return globalThis.developmentStateUC(globalThis.developmentStateC)}'}));}}]})).outputFiles[0].text;await page.setContent('<html lang="en"><head><title>Current Development source states</title><style>'+css+'</style></head><body><div id="root"></div></body></html>');page.on('pageerror',error=>{throw error});await page.addScriptTag({content:script});await expect(page.locator('main h1')).toHaveText('Development');await expect(page.getByLabel('Learning period',{exact:true}).locator('option')).toHaveCount(2);}

test('one current prerequisite replaces repeated ledger and milestone instructions while independent failures remain visible',async({page})=>{const errors:string[]=[];page.on('pageerror',()=>errors.push('pageerror'));page.on('console',message=>{if(['error','warning'].includes(message.type()))errors.push(message.type())});await mount(page);const primary=page.locator('.development-recognition'),ledger=page.locator('.development-section'),milestones=page.locator('.development-milestones');await expect(primary.locator('[data-state="unknown"]')).toHaveCount(1);await expect(page.getByText('Choose a learning period to open its recorded points, actions and milestones.',{exact:true})).toHaveCount(1);await expect(ledger).toHaveCount(0);await expect(milestones).toHaveCount(0);await expect(page.locator('.development-total')).toHaveCount(0);
 await page.getByLabel('Learning period',{exact:true}).selectOption('ec000000-0000-4000-8000-000000000002');await expect.poll(()=>page.evaluate(()=>typeof(globalThis as unknown as{developmentStateFixture:{release:unknown}}).developmentStateFixture.release)).toBe('function');await expect(primary.locator('[data-state="loading"]')).toHaveCount(1);await expect(ledger).toHaveCount(0);await expect(milestones).toHaveCount(0);
 await page.evaluate(()=>{const f=(globalThis as unknown as{developmentStateFixture:{mode:string;release:()=>void}}).developmentStateFixture;f.mode='ready';f.release();});await expect(primary.locator('.development-total strong')).toHaveText('0');await expect(ledger.locator('[data-state="empty"]')).toHaveCount(1);await expect(milestones.locator('[data-state="empty"]')).toHaveCount(1);
 await page.evaluate(()=>(globalThis as unknown as{developmentStateFixture:{mode:string}}).developmentStateFixture.mode='summary-error');await page.getByRole('button',{name:'Refresh development',exact:true}).click();await expect(primary.getByRole('alert')).toHaveCount(1);await expect(ledger).toHaveCount(0);await expect(milestones).toHaveCount(0);await expect(page.locator('.development-total')).toHaveCount(0);
 await page.evaluate(()=>(globalThis as unknown as{developmentStateFixture:{mode:string}}).developmentStateFixture.mode='ledger-error');await page.getByRole('button',{name:'Refresh development',exact:true}).click();await expect(primary.getByRole('alert')).toHaveCount(1);await expect(ledger.getByRole('alert')).toHaveCount(1);await expect(milestones).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{(globalThis as unknown as{developmentStateLocale:(locale:string)=>void}).developmentStateLocale('ar');document.documentElement.lang='ar';document.documentElement.dir='rtl';});await expect(page.locator('main h1')).toHaveText('النموّ');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include('main').withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);expect(await page.evaluate(()=>(globalThis as unknown as{developmentStateFixture:{writes:string[]}}).developmentStateFixture.writes)).toEqual([]);expect(errors).toEqual([]);
});
test('a pending original period command remains retryable outside the consolidated source prerequisite',async({page})=>{await mount(page,true);await expect(page.locator('.development-command-recovery')).toHaveCount(1);await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toHaveCount(1);await expect(page.getByLabel('Learning period',{exact:true})).toBeDisabled();await expect(page.locator('.development-section,.development-milestones')).toHaveCount(0);await page.evaluate(()=>{(globalThis as unknown as{developmentStateLocale:(locale:string)=>void}).developmentStateLocale('ar');document.documentElement.lang='ar';document.documentElement.dir='rtl';});await expect(page.locator('.development-command-recovery')).toHaveCount(1);expect(await page.evaluate(()=>{const f=(globalThis as unknown as{developmentStateFixture:{journal:{pending:()=>unknown[]};pending:unknown[];writes:string[]}}).developmentStateFixture;return{same:JSON.stringify(f.journal.pending())===JSON.stringify(f.pending),writes:f.writes};})).toEqual({same:true,writes:[]});});
