import { expectTrailWorkspace } from './trail-workspace';
import{test,expect}from'@playwright/test';
import{readFile}from'node:fs/promises';
import{randomUUID}from'node:crypto';
import AxeBuilder from'@axe-core/playwright';
type Account={role:string;email:string;password:string};
test('teacher reviews a named class grid and confirms per-source native releases with evidence',async({page})=>{
 test.setTimeout(90000);page.setDefaultTimeout(15000);const accounts=JSON.parse(await readFile('.local/synthetic-accounts.json','utf8'))as Account[];const run=randomUUID().slice(0,6);const title=`School gradebook ${run}`;const first=`Explain school method ${run}`;const second=`Check school method ${run}`;const tokens:Record<string,string>={};
 for(const role of ['teacher','student']){const account=accounts.find(item=>item.role===role)!;const auth=await page.request.post(`${process.env.SUPABASE_URL}/auth/v1/token?grant_type=password`,{headers:{apikey:process.env.SUPABASE_PUBLISHABLE_KEY!},data:{email:account.email,password:account.password}});expect(auth.ok()).toBe(true);tokens[role]=(await auth.json()).access_token;}
 const command=async(role:string,path:string,body:Record<string,unknown>)=>{const response=await page.request.post(`http://localhost:4000${path}`,{headers:{Authorization:`Bearer ${tokens[role]}`,'X-School-Id':'10000000-0000-4000-8000-000000000001','Idempotency-Key':randomUUID()},data:body});expect(response.ok(),`${path}: ${response.status()}`).toBe(true);return response.json();};
 const course=await command('teacher','/v1/courses',{classId:'30000000-0000-4000-8000-000000000001',subjectId:'43000000-0000-4000-8000-000000000001',title,description:'Synthetic class gradebook sources'});await command('teacher',`/v1/courses/${course.id}/publish`,{});
 for(const[name,score]of [[first,0],[second,7]]as const){const assessment=await command('teacher','/v1/assessments',{courseId:course.id,title:name,instructions:'Show the reviewed school example.',maxScore:10});await command('teacher',`/v1/assessments/${assessment.id}/reference`,{referenceId:'61000000-0000-4000-8000-000000000001',expectedPolicyVersion:1});const source=await command('student',`/v1/assessments/${assessment.id}/submissions`,{content:`${name}: exact source response.`});await command('teacher',`/v1/submissions/${source.id}/results`,{score,feedback:`${name}: reviewed native feedback.`,expectedPolicyVersion:2,expectedRevision:0,sourceEvidence:true});}
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'||/hydration|did not match/i.test(message.text()))errors.push(message.text());});const account=accounts.find(item=>item.role==='teacher')!;await page.goto('/');await page.getByRole('button',{name:'English',exact:true}).click();await page.getByLabel('School email',{exact:true}).fill(account.email);await page.getByLabel('Password',{exact:true}).fill(account.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expectTrailWorkspace(page);await page.locator('.workspace-chrome__navigation').getByRole('button',{name:'Academic',exact:true}).click();await page.getByRole('button',{name:'Class gradebook',exact:true}).click();await page.getByLabel('Course',{exact:true}).selectOption({label:title});const grid=page.getByRole('region',{name:'Class gradebook',exact:true});await expect(grid.getByRole('heading',{name:title,exact:true})).toBeVisible();const table=grid.getByRole('table',{name:'Class assessment results',exact:true});await expect(table).toContainText(first);await expect(table).toContainText(second);await expect(table).toContainText('No submitted work');
 const cells=table.locator('td').filter({has:page.getByRole('checkbox')});await expect(cells).toHaveCount(2);await expect(cells).toContainText(['Reviewed draft — not released','Reviewed draft — not released']);
 await cells.first().getByRole('button',{name:'Open learner work',exact:true}).click();const detail=grid.getByRole('region',{name:'Open learner work',exact:true});await expect(detail).toContainText('exact source response.');await detail.getByRole('button',{name:'Close learner detail',exact:true}).click();
 await cells.nth(0).getByRole('checkbox').check();await cells.nth(1).getByRole('checkbox').check();const previewResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/courses/${course.id}/gradebook/preview`&&response.request().method()==='POST');await grid.getByRole('button',{name:'Review selected releases (2)',exact:true}).click();expect((await previewResponse).status()).toBe(200);const preview=grid.getByRole('region',{name:'Review selected releases',exact:true});await expect(preview).toContainText(first);await expect(preview).toContainText(second);const form=preview.getByRole('region',{name:'Confirm selected releases',exact:true});const sharing=form.locator('input[type=checkbox]:not([required])');await expect(sharing).toHaveCount(2);await sharing.first().check();await form.getByLabel('I reviewed every selected source and approve these releases',{exact:true}).check();
 const released=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/courses/${course.id}/gradebook/release`&&response.request().method()==='POST');await form.getByRole('button',{name:'Release selected results',exact:true}).click();const response=await released;expect(response.status()).toBe(200);expect((await response.json()).items).toHaveLength(2);await expect(table.getByText('Released result',{exact:true})).toHaveCount(2);const evidenceResponse=page.waitForResponse(response=>/^\/v1\/evidence\/[^/]+$/.test(new URL(response.url()).pathname)&&response.request().method()==='GET');await table.getByRole('button',{name:'View evidence',exact:true}).first().click();const evidence=await evidenceResponse;expect(evidence.status()).toBe(200);expect((await evidence.json()).sourceType).toBe('SUBMISSION');await expect(grid.locator('.evidence-provenance')).toContainText('Teacher entered');
 await grid.locator('.gradebook-detail').getByRole('button',{name:'Close evidence',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'العربية',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(grid.getByRole('heading',{name:title,exact:true})).toBeVisible();const arabicTable=grid.getByRole('table',{name:'نتائج تقييمات الصف',exact:true});await expect(arabicTable).toBeVisible();await expect(arabicTable).toContainText(first);await expect(arabicTable).toContainText(second);await expect(arabicTable.getByText('نتيجة صادرة',{exact:true})).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);expect((await new AxeBuilder({page}).include('main').analyze()).violations).toEqual([]);expect(errors).toEqual([]);
});
