import{test,expect,type Page}from'@playwright/test';import{build}from'esbuild';import{readFileSync}from'node:fs';import{resolve}from'node:path';
const root=resolve(import.meta.dirname,'../..');
async function mount(page:Page,role:string,locale:string){
const built=await build({stdin:{resolveDir:root,loader:'tsx',contents:`
import React,{createContext,useContext,useState}from'react';import{createRoot}from'react-dom/client';import{ImprovementWorkspace}from'./apps/web/features/improvement/components/improvement-workspace';import{CommandJournal,LearningApiError}from'./apps/web/shared/api/client';import{FormDrafts}from'./apps/web/shared/session/form-drafts';const C=createContext(null);globalThis.partialC=C;globalThis.partialUC=useContext;const f=globalThis.partialFixture={mode:'partial',reads:[],writes:[],loads:0};globalThis.partialQuery=path=>{const source=path?.startsWith('/v1/recommendations?')||path?.startsWith('/v1/interventions?')||path?.startsWith('/v1/outcomes?');if(path)f.reads.push(path);return{data:[],context:'current',loaded:!!path&&f.mode!=='unobserved',loading:false,loadingMore:source&&f.mode==='loadingMore',error:source&&f.mode==='error'?new LearningApiError('unavailable'):null,moreError:source&&f.mode==='denied'?new LearningApiError('denied'):source&&f.mode==='moreError'?new LearningApiError('unavailable'):null,nextCursor:source&&f.mode!=='complete'?'b2000000-0000-4000-8000-000000000001':null,loadMore(){f.loads++;}}};const journal=new CommandJournal(),drafts=new FormDrafts();function H(){const[g,setG]=useState(1);globalThis.partialMode=mode=>{f.mode=mode;setG(x=>x+1)};return<C.Provider value={{locale:'${locale}',membership:{schoolId:'school',userId:'actor',role:'${role}',entitlements:['improvement','assessment','learning']},apiUrl:'https://fixture.invalid',accessToken:'fictional',accessGeneration:g,status:'ready',online:true,commandJournal:journal,formDrafts:drafts,announce(){},refreshAccess(){},reportDiagnostic(){}}}><main className='workspace'><ImprovementWorkspace/></main></C.Provider>}createRoot(document.getElementById('root')).render(<H/>);
`},bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',plugins:[{name:'partial-source-inputs',setup(b){b.onLoad({filter:/shared[\\/]session[\\/]providers\.tsx$/},()=>({loader:'js',contents:'export function useApp(){return globalThis.partialUC(globalThis.partialC)}'}));b.onLoad({filter:/shared[\\/]hooks[\\/]use-paginated-query\.ts$/},()=>({loader:'js',contents:'export function usePaginatedLearningQuery(path){return globalThis.partialQuery(path)}'}));b.onLoad({filter:/shared[\\/]hooks[\\/]use-api\.ts$/},()=>({loader:'js',contents:`import {commonEn,commonAr} from '${root.replaceAll('\\','/')}/apps/web/shared/i18n/common'; export function useApi(){const app=globalThis.partialUC(globalThis.partialC);return{journal:app.commandJournal,t:app.locale==='ar'?commonAr:commonEn,request(){globalThis.partialFixture.writes.push('blocked');throw Error('No writes allowed')}}}export function useApiQuery(){return{data:null,loading:false,error:null}}`}));b.onLoad({filter:/\.(webp|svg|png)$/},args=>({loader:'js',contents:'export default '+JSON.stringify({src:'data:image/webp;base64,'+readFileSync(args.path).toString('base64'),width:128,height:128})}));}}]});
const css=['packages/ui/src/tokens.css','apps/web/app/globals.css','apps/web/features/improvement/styles.css'].map(file=>readFileSync(resolve(root,file),'utf8')).join('\n');await page.setViewportSize({width:1366,height:900});await page.setContent(`<html lang='${locale}' dir='${locale==='ar'?'rtl':'ltr'}'><head><title>Current partial Improvement source</title><style>${css}</style></head><body><div id='root'></div></body></html>`);await page.addScriptTag({content:built.outputFiles[0].text});
}
for(const role of['admin','coordinator','student'])for(const locale of['en','ar'])test(`${role} ${locale}: incomplete current lists withhold false empty claims and retain native continuation`,async({page},info)=>{
const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await mount(page,role,locale);const cases=role==='student'?['interventions','outcomes']:['proposals','interventions','outcomes'];const labels=locale==='ar'?{proposals:'المقترحات',interventions:'مهام التدريب',outcomes:'النتائج'}:{proposals:'Proposals',interventions:'Practice tasks',outcomes:'Outcomes'};
for(const section of cases){
 await page.getByRole('button',{name:labels[section as keyof typeof labels],exact:true}).click();
 if(role==='coordinator'&&section==='outcomes'){await expect(page.locator('.cuevo-workspace-state[data-state="unknown"]')).toBeVisible();continue;}
 const container=section==='proposals'?page.locator('.proposal-directory'):section==='interventions'?page.locator('.practice-directory'):page.locator('.improvement-workspace');
 const empty=container.locator('.cuevo-workspace-state[data-state="empty"]'),unknown=container.locator('.cuevo-workspace-state[data-state="unknown"]');
 await expect(empty).toHaveCount(0);await expect(unknown).toHaveCount(1);await expect(page.getByRole('button',{name:locale==='ar'?'تحميل المزيد':'Load more',exact:true})).toBeEnabled();
 if(role==='admin'&&section==='proposals')await page.screenshot({path:info.outputPath('partial-admin-proposals.png'),fullPage:true});
 for(const mode of['loadingMore','moreError','unobserved']){await page.evaluate(mode=>(globalThis as unknown as{partialMode:(mode:string)=>void}).partialMode(mode),mode);await expect(empty).toHaveCount(0);await expect(unknown).toHaveCount(1);if(mode==='moreError'){await expect(page.locator('.improvement-workspace [role="alert"]')).toHaveCount(1);const before=await page.evaluate(()=>(globalThis as unknown as{partialFixture:{loads:number}}).partialFixture.loads);await page.getByRole('button',{name:locale==='ar'?'تحميل المزيد':'Load more',exact:true}).click();expect(await page.evaluate(()=>(globalThis as unknown as{partialFixture:{loads:number}}).partialFixture.loads)).toBe(before+1);}}
 for(const mode of['error','denied']){await page.evaluate(mode=>(globalThis as unknown as{partialMode:(mode:string)=>void}).partialMode(mode),mode);await expect(page.locator('.improvement-workspace [data-state="empty"]')).toHaveCount(0);await expect(page.locator('.improvement-workspace [role="alert"]')).toHaveCount(1);}
 await page.evaluate(()=>(globalThis as unknown as{partialMode:(mode:string)=>void}).partialMode('complete'));await expect(empty).toHaveCount(1);await expect(unknown).toHaveCount(0);
 await page.evaluate(()=>(globalThis as unknown as{partialMode:(mode:string)=>void}).partialMode('partial'));
}
expect(await page.evaluate(()=>(globalThis as unknown as{partialFixture:{writes:unknown[]}}).partialFixture.writes)).toEqual([]);expect(errors).toEqual([]);
});
