import { expectTrailWorkspace, signOutTrailWorkspace } from './trail-workspace';
import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
type Account = { role: string; email: string; password: string };
test('native rubric evidence produces a human-approved task and unknown-comparability reassessment in English and Arabic', async ({ page }, testInfo) => {
  test.setTimeout(90000); page.setDefaultTimeout(15000);
  const accounts = JSON.parse(await readFile('.local/synthetic-accounts.json', 'utf8')) as Account[];
  const teacher = accounts.find(account => account.role === 'teacher')!; const student = accounts.find(account => account.role === 'student')!; const admin = accounts.find(account => account.role === 'admin')!;
  const publicKey = process.env.SUPABASE_PUBLISHABLE_KEY; if (!publicKey) throw Error('Configured local public Auth key required.'); const school = '10000000-0000-4000-8000-000000000001';
  const token = async (account: Account) => { const response = await page.request.post(`${process.env.SUPABASE_URL ?? 'http://127.0.0.1:56321'}/auth/v1/token?grant_type=password`, { headers: { apikey: publicKey }, data: { email: account.email, password: account.password } }); expect(response.ok()).toBe(true); return (await response.json()).access_token as string; };
  const teacherToken = await token(teacher); const studentToken = await token(student); const adminToken = await token(admin);
  const command = async (path: string, body: Record<string, unknown>, access = teacherToken) => { const response = await page.request.post(`http://localhost:4000${path}`, { headers: { Authorization: `Bearer ${access}`, 'X-School-Id': school, 'Idempotency-Key': randomUUID() }, data: body }); expect(response.status(), path).toBe(200); return response.json(); };
  const readPolicy = async () => { const response = await page.request.get('http://localhost:4000/v1/intelligence/policy', { headers: { Authorization: `Bearer ${adminToken}`, 'X-School-Id': school } }); expect(response.status()).toBe(200); return (await response.json()).policy; };
  const original = await readPolicy(); await command('/v1/intelligence/policy', { purpose: 'NEXT_LEARNING_ACTION', dataClassification: 'SCHOOL_CUSTOM_NATIVE', fixtureEnabled: true, liveEnabled: false, allowedActions: ['GUIDED_PRACTICE', 'REVIEW_FEEDBACK'], expectedVersion: original.version, confirmApproval: true, reason: 'Explicit synthetic native rubric browser evaluation.' }, adminToken);
  try {
    const course = await command('/v1/courses', { classId: '30000000-0000-4000-8000-000000000001', subjectId: '43000000-0000-4000-8000-000000000001', title: `Native rubric browser ${randomUUID().slice(0, 8)}`, description: 'Synthetic native criterion evidence.' }); const unit = await command(`/v1/courses/${course.id}/units`, { title: 'Checking plan', sequence: 1 }); const lesson = await command(`/v1/units/${unit.id}/lessons`, { title: 'Checking example', sequence: 1, body: 'Explain the checking step.' }); await command(`/v1/lessons/${lesson.id}/activities`, { title: 'Native checking practice', kind: 'practice', instructions: 'Explain one checking step with the worked example.', sequence: 1 }); await command(`/v1/courses/${course.id}/publish`, {});
    const rubric = await command('/v1/rubrics', { courseId: course.id, title: 'Native checking rubric', version: 'school-v1', criteria: [{ key: 'check', title: 'Checking', levels: [{ key: 'shown', label: 'Demonstrated', description: 'Show one checking step.' }, { key: 'connected', label: 'Connected', description: 'Explain connected checks.' }] }] });
    const assessment = async (label: string) => { const row = await command('/v1/assessments', { courseId: course.id, title: label, instructions: 'Explain the checking step.', maxScore: 10 }); await command(`/v1/assessments/${row.id}/rubric`, { rubricId: rubric.id, expectedPolicyVersion: 1 }); await command(`/v1/assessments/${row.id}/reference`, { referenceId: '61000000-0000-4000-8000-000000000001', expectedPolicyVersion: 2 }); return row; };
    const release = async (assessmentId: string, level: string) => { const work = await command(`/v1/assessments/${assessmentId}/submissions`, { content: 'Synthetic checking explanation.' }, studentToken); const mark = await command(`/v1/submissions/${work.id}/results`, { nativeResult: { type: 'rubric', rubricId: rubric.id, criteria: [{ criterionKey: 'check', levelKey: level }] }, feedback: 'Teacher-reviewed criterion evidence.', expectedPolicyVersion: 3, expectedRevision: 0, sourceEvidence: true }); return command(`/v1/results/${mark.id}/release`, { expectedRevision: 1, parentVisible: false }); };
    const baselineAssessment = await assessment('Native baseline'); const baseline = await release(baselineAssessment.id, 'shown');
    await page.goto('/'); await page.getByLabel('School email').fill(teacher.email); await page.getByLabel('Password', { exact: true }).fill(teacher.password); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expectTrailWorkspace(page); await page.locator('.workspace-chrome__navigation').getByRole('button', { name: 'Next steps', exact: true }).click();
    await page.getByRole('button', { name: 'Request analysis', exact: true }).click(); const form = page.getByRole('region', { name: 'Request analysis', exact: true }); const select = form.getByLabel('Released baseline result', { exact: true });
    while (!await select.locator(`option[value="${baseline.id}"]`).count()) { const more = page.locator('.improvement-workspace').getByRole('button', { name: 'Load more', exact: true }); expect(await more.count()).toBeGreaterThan(0); await more.last().click(); await expect(page.getByRole('button', { name: 'Loading more…', exact: true })).toHaveCount(0); }
    await select.selectOption(baseline.id); const generated = page.waitForResponse(response => new URL(response.url()).pathname === '/v1/intelligence/analyze' && response.request().method() === 'POST'); await form.getByRole('button', { name: 'Request analysis', exact: true }).click(); const result = await generated; expect(result.ok()).toBe(true); const proposal = await result.json();
    const row = page.locator(`[data-recommendation-id="${proposal.id}"]`); await expect(row.getByRole('region', { name: 'Why this appeared', exact: true })).toBeVisible(); await row.getByRole('button', { name: 'Approve practice', exact: true }).click(); const approval = row.getByRole('region', { name: 'Approve practice', exact: true }); await approval.getByLabel('Decision reason', { exact: true }).fill('Teacher reviewed exact native criterion evidence.'); const decided = page.waitForResponse(response => new URL(response.url()).pathname === `/v1/recommendations/${proposal.id}/decision` && response.request().method() === 'POST'); await approval.getByRole('button', { name: 'Approve practice', exact: true }).click(); const decision = await decided; expect(decision.ok()).toBe(true); const approved = await decision.json();
    const signIn = async (account: Account) => { await signOutTrailWorkspace(page); await page.getByLabel('School email').fill(account.email); await page.getByLabel('Password', { exact: true }).fill(account.password); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expectTrailWorkspace(page, account.role); await page.locator('.workspace-chrome__navigation').getByRole('button', { name: 'Next steps', exact: true }).click(); };
    const load = async (target: ReturnType<typeof page.locator>) => { await expect(page.getByText('Loading next steps…', { exact: true })).toHaveCount(0); while (!await target.count()) { const more = page.locator('.improvement-workspace').getByRole('button', { name: 'Load more', exact: true }); expect(await more.count()).toBeGreaterThan(0); await more.first().click(); await expect(page.getByRole('button', { name: 'Loading more…', exact: true })).toHaveCount(0); } };
    await signIn(student);const task=page.locator(`[data-intervention-id="${approved.interventionId}"]`);await load(task);const completion=task.getByRole('region',{name:'Try this practice',exact:true});await completion.getByLabel('Reflection (optional)',{exact:true}).fill('I explained the checking step.');const completeResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/interventions/${approved.interventionId}/complete`&&response.request().method()==='POST');await completion.getByRole('button',{name:'Complete practice',exact:true}).click();expect((await completeResponse).ok()).toBe(true);
    const followupAssessment=await assessment('Native follow-up');await signIn(teacher);await page.getByRole('button',{name:'Practice tasks',exact:true}).click();const staffTask=page.locator(`[data-intervention-id="${approved.interventionId}"]`);await load(staffTask);await staffTask.getByRole('button',{name:'Link follow-up assessment',exact:true}).click();const linked=staffTask.getByRole('region',{name:'Link follow-up assessment',exact:true});await linked.getByLabel('Published follow-up assessment',{exact:true}).selectOption(followupAssessment.id);const linkResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/interventions/${approved.interventionId}/reassessment`&&response.request().method()==='POST');await linked.getByRole('button',{name:'Link follow-up assessment',exact:true}).click();expect((await linkResponse).ok()).toBe(true);const followup=await release(followupAssessment.id,'connected');
    const refreshed=page.waitForResponse(response=>new URL(response.url()).pathname==='/v1/results'&&response.request().method()==='GET');await page.getByRole('button',{name:'Refresh next steps',exact:true}).click();expect((await refreshed).ok()).toBe(true);await expect(page.getByText('Loading next steps…',{exact:true})).toHaveCount(0);await staffTask.getByRole('button',{name:'Measure observed change',exact:true}).click();const measurement=staffTask.getByRole('region',{name:'Measure observed change',exact:true});await measurement.getByLabel('Released follow-up result',{exact:true}).selectOption(followup.id);const measureResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/interventions/${approved.interventionId}/measure`&&response.request().method()==='POST');await measurement.getByRole('button',{name:'Measure observed change',exact:true}).click();const measured=await measureResponse;expect(measured.ok()).toBe(true);const outcome=await measured.json();
    const outcomesRead=page.waitForResponse(response=>new URL(response.url()).pathname==='/v1/outcomes'&&response.request().method()==='GET');await page.getByRole('button',{name:'Refresh next steps',exact:true}).click();expect((await outcomesRead).ok()).toBe(true);await page.getByRole('button',{name:'Outcomes',exact:true}).click();const evidence=page.locator(`[data-outcome-id="${outcome.id}"]`);await load(evidence);
    await expect(evidence.getByText('Comparability is unknown; no rubric level comparison rule is approved.', { exact: true })).toBeVisible(); await expect(evidence).toContainText('Demonstrated'); await expect(evidence).toContainText('Connected'); await page.getByRole('button', { name: 'العربية', exact: true }).click(); await expect(evidence.getByText('قابلية المقارنة مجهولة؛ لم تُعتمد قاعدة لمقارنة مستويات المعيار.', { exact: true })).toBeVisible();
  } finally { test.setTimeout(testInfo.timeout + 30000); const current = await readPolicy(); await command('/v1/intelligence/policy', { purpose: original.purpose, dataClassification: original.dataClassification, fixtureEnabled: original.fixtureEnabled, liveEnabled: original.liveEnabled, allowedActions: original.allowedActions, expectedVersion: current.version, confirmApproval: true, reason: 'Restore original synthetic native-policy setting.' }, adminToken); }
});
