import { test, expect, type Page } from '@playwright/test';
import { build } from 'esbuild';
import { resolve } from 'node:path';
import AxeBuilder from '@axe-core/playwright';
const root=resolve(import.meta.dirname,'../..');

async function mount(page:Page,locale:'en'|'ar'='en'){
 const script=(await build({stdin:{resolveDir:root,loader:'tsx',contents:`
import React,{createContext,useContext,useState}from'react';import{createRoot}from'react-dom/client';import{StudentLearningJourney}from'./apps/web/features/learning/components/student-learning-journey';import{CommandJournal}from'./apps/web/shared/api/client';import{FormDrafts}from'./apps/web/shared/session/form-drafts';const C=createContext(null);globalThis.jFocusC=C;globalThis.jFocusUC=useContext;const id=n=>'b7000000-0000-4000-8000-'+String(n).padStart(12,'0'),journal=new CommandJournal(),drafts=new FormDrafts(),f=globalThis.jFocus={hold:false,denied:false,submitted:false,release:[],writes:[]};globalThis.fetch=async(input,init)=>{const url=new URL(String(input));if(init?.method==='POST'){f.writes.push(url.pathname);throw Error('No domain writes')};if(f.hold)await new Promise(done=>f.release.push(done));if(f.denied)return Response.json({code:'FORBIDDEN'},{status:403});return Response.json(url.pathname.endsWith('/task')?{id:id(5),courseId:id(3),courseTitle:'Current school course',title:'Current linked assessment',instructions:'Exact current assessment instructions',status:'PUBLISHED',model:'numeric',maxScore:10,dueAt:null,policyVersion:1,referenceId:id(6),assignmentState:'OPEN',availabilityVersion:1,availableFrom:null,availableUntil:null,allowLate:true,submissionKind:'TEXT',currentSubmission:f.submitted?{id:id(10),assessmentId:id(5),learnerId:id(9),assessmentTitle:'Current linked assessment',learnerName:'Current learner',content:'Current submitted source',status:'SUBMITTED',submittedAt:'2026-10-05T00:00:00Z',revision:1}:null}:url.pathname.endsWith('/draft')?{id:null,assessmentId:id(5),content:'',revision:0,status:'DRAFT',updatedAt:null}:{items:[],nextCursor:null});};
function H(){const[locale,setLocale]=useState('${locale}'),[generation,setGeneration]=useState(1),[linked,setLinked]=useState(false),[revision,setRevision]=useState(1),[role,setRole]=useState('student');globalThis.jFocusChange=kind=>{if(kind==='locale')setLocale(value=>value==='en'?'ar':'en');else if(kind==='access')setGeneration(value=>value+1);else if(kind==='linked')setLinked(true);else if(kind==='source')setRevision(value=>value+1);else if(kind==='role')setRole('teacher')};const lesson={id:id(1),title:'Current school lesson',sequence:1,contentRevision:revision,body:'Read the current school example.',status:'PUBLISHED',activities:[{id:id(2),title:'Current school activity',sequence:1,contentRevision:revision,kind:linked?'assignment':'practice',assessmentId:linked?id(5):null,instructions:'Explain one current checking step.',completion:null}]};return<C.Provider value={{locale,membership:{schoolId:id(8),userId:id(9),role,entitlements:['learning','assessment','curriculum']},apiUrl:'https://fixture.invalid',accessToken:'synthetic',accessGeneration:generation,online:true,status:'ready',commandJournal:journal,formDrafts:drafts,announce(){},refreshAccess(){},reportDiagnostic(){}}}><main><button id='outside'>Other control</button><StudentLearningJourney courseId={id(3)} lesson={lesson} activityId={id(2)} onSelect={()=>{}} renderWork={()=> <section><h3>Current practice work</h3><input aria-label='Unsent current reflection'/></section>}/></main></C.Provider>}createRoot(document.getElementById('root')).render(<H/>);
`},bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',loader:{'.webp':'dataurl','.png':'dataurl','.svg':'dataurl'},plugins:[{name:'current-session-input',setup(b){b.onLoad({filter:/shared[\\/]session[\\/]providers\.tsx$/},()=>({loader:'js',contents:'export function useApp(){return globalThis.jFocusUC(globalThis.jFocusC)}'}));}}]})).outputFiles[0].text;await page.setViewportSize({width:390,height:844});await page.setContent('<div id="root"></div>');await page.addScriptTag({content:script});await expect(page.locator('.student-learning-journey')).toBeVisible();
}

for(const locale of['en','ar']as const)test(`deliberate keyboard entry focuses current named work and Back restores opener ${locale}`,async({page})=>{await mount(page,locale);const open=page.getByRole('button',{name:locale==='en'?'Open this task':'فتح هذه المهمة',exact:true});await open.focus();await page.keyboard.press('Enter');const work=page.getByRole('region',{name:locale==='en'?'Work on this task: Current school activity':'العمل على هذه المهمة: Current school activity',exact:true});await expect(work).toBeFocused();await expect(work.getByRole('heading',{name:'Current practice work',exact:true})).toBeVisible();await page.getByRole('button',{name:locale==='en'?'Back to your journey':'العودة إلى رحلتك',exact:true}).focus();await page.keyboard.press('Enter');await expect(open).toBeFocused();expect(await page.evaluate(()=>(globalThis as unknown as {jFocus:{writes:unknown[]}}).jFocus.writes)).toEqual([]);});

test('work region has a distinct localized landmark name without duplicate current panel semantics',async({page})=>{await mount(page);await page.getByRole('button',{name:'Open this task',exact:true}).click();await expect(page.getByRole('region',{name:'Current school activity',exact:true})).toHaveCount(1);await expect(page.getByRole('region',{name:'Work on this task: Current school activity',exact:true})).toHaveCount(1);expect((await new AxeBuilder({page}).withRules(['landmark-unique']).analyze()).violations).toEqual([]);});

test('source locale and membership changes close work without replaying an old focus intent',async({page})=>{
 for(const change of['source','locale','access']){await mount(page);const open=page.getByRole('button',{name:'Open this task',exact:true});await open.click();await expect(page.locator('.student-learning-journey__actual-work')).toBeFocused();await page.evaluate(change=>(globalThis as unknown as{jFocusChange:(change:string)=>void}).jFocusChange(change),change);await expect(page.locator('.student-learning-journey__actual-work')).toHaveCount(0);await expect(page.getByRole('button',{name:change==='locale'?'فتح هذه المهمة':'Open this task',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.activeElement?.tagName)).toBe('BODY');}
});

test('newer user focus before the scheduled work or Back handoff cancels it',async({page})=>{
 await mount(page);await page.evaluate(()=>{const queued:{id:number;callback:FrameRequestCallback}[]=[];let id=0;(globalThis as unknown as{jFocusFrames:unknown;jFocusFlush:()=>void}).jFocusFrames=queued;window.requestAnimationFrame=callback=>{queued.push({id:++id,callback});return id};window.cancelAnimationFrame=cancelled=>{const row=queued.findIndex(item=>item.id===cancelled);if(row>=0)queued.splice(row,1)};(globalThis as unknown as{jFocusFlush:()=>void}).jFocusFlush=()=>{for(const row of queued.splice(0))row.callback(performance.now())};});await page.getByRole('button',{name:'Open this task',exact:true}).click();await expect(page.locator('.student-learning-journey__actual-work')).toBeVisible();await page.locator('#outside').focus();await page.evaluate(()=>(globalThis as unknown as{jFocusFlush:()=>void}).jFocusFlush());await expect(page.locator('#outside')).toBeFocused();await page.getByRole('button',{name:'Back to your journey',exact:true}).click();await expect(page.getByRole('button',{name:'Open this task',exact:true})).toBeVisible();await page.locator('#outside').focus();await page.evaluate(()=>(globalThis as unknown as{jFocusFlush:()=>void}).jFocusFlush());await expect(page.locator('#outside')).toBeFocused();
});

test('a changed current source cancels an undelivered keyboard entry instead of reopening work',async({page})=>{
 await mount(page);await page.evaluate(()=>{const callbacks:FrameRequestCallback[]=[];window.requestAnimationFrame=callback=>{callbacks.push(callback);return callbacks.length};window.cancelAnimationFrame=()=>{};(globalThis as unknown as{jFocusFlush:()=>void}).jFocusFlush=()=>callbacks.splice(0).forEach(callback=>callback(performance.now()));});await page.getByRole('button',{name:'Open this task',exact:true}).click();await expect(page.locator('.student-learning-journey__actual-work')).toBeVisible();await page.evaluate(()=>(globalThis as unknown as{jFocusChange:(change:string)=>void}).jFocusChange('source'));await expect(page.locator('.student-learning-journey__actual-work')).toHaveCount(0);await page.locator('#outside').focus();await page.evaluate(()=>(globalThis as unknown as{jFocusFlush:()=>void}).jFocusFlush());await expect(page.locator('#outside')).toBeFocused();await expect(page.getByRole('button',{name:'Open this task',exact:true})).toBeVisible();
});

test('role replacement cancels queued work focus within the same actor source',async({page})=>{
 await mount(page);await page.evaluate(()=>{const callbacks:FrameRequestCallback[]=[];window.requestAnimationFrame=callback=>{callbacks.push(callback);return callbacks.length};window.cancelAnimationFrame=()=>{};(globalThis as unknown as{jFocusFlush:()=>void}).jFocusFlush=()=>callbacks.splice(0).forEach(callback=>callback(performance.now()));});await page.getByRole('button',{name:'Open this task',exact:true}).click();await expect(page.locator('.student-learning-journey__actual-work')).toBeVisible();await page.evaluate(()=>(globalThis as unknown as{jFocusChange:(change:string)=>void}).jFocusChange('role'));await expect(page.locator('.student-learning-journey__actual-work')).toHaveCount(0);await page.locator('#outside').focus();await page.evaluate(()=>(globalThis as unknown as{jFocusFlush:()=>void}).jFocusFlush());await expect(page.locator('#outside')).toBeFocused();
});

test('linked submitted work keeps current Back reachable while a read is pending or denied',async({page})=>{
 await mount(page);await page.evaluate(()=>{(globalThis as unknown as{jFocus:{submitted:boolean};jFocusChange:(change:string)=>void}).jFocus.submitted=true;(globalThis as unknown as{jFocusChange:(change:string)=>void}).jFocusChange('linked');});const open=page.getByRole('button',{name:'Open this task',exact:true});await expect(page.getByText('Current submitted source',{exact:true})).toBeVisible();await expect(open).toBeEnabled();await page.evaluate(()=>(globalThis as unknown as{jFocus:{hold:boolean}}).jFocus.hold=true);await open.click();await expect(page.locator('.student-learning-journey__actual-work')).toBeFocused();const back=page.getByRole('button',{name:'Back to your journey',exact:true});await expect(back).toBeEnabled();await expect.poll(()=>page.evaluate(()=>(globalThis as unknown as{jFocus:{release:(()=>void)[]}}).jFocus.release.length)).toBeGreaterThan(0);await page.evaluate(()=>{(globalThis as unknown as{jFocus:{denied:boolean;hold:boolean;release:(()=>void)[]}}).jFocus.denied=true;const current=(globalThis as unknown as{jFocus:{hold:boolean;release:(()=>void)[]}}).jFocus;current.hold=false;current.release.forEach(done=>done());current.release=[];});await expect(page.locator('.student-learning-journey__actual-work [role="alert"]')).toBeVisible();await back.focus();await page.keyboard.press('Enter');await expect(open).toBeFocused();expect(await page.evaluate(()=>(globalThis as unknown as{jFocus:{writes:unknown[]}}).jFocus.writes)).toEqual([]);
});
