import { test, expect } from '@playwright/test';
import { currentCoursePreparationOutline, openCurrentStaffAssessment } from './learning-source-navigation';
const id='fa100000-0000-4000-8000-000000000001',other='fa100000-0000-4000-8000-000000000002',courseId='fa200000-0000-4000-8000-000000000001';
const source={id,courseId,title:'Exact checking task',courseTitle:'Current school checking course',status:'DRAFT' as const};
function choice(value=source,disabled=false){return `<li data-assessment-choice="${value.id}"><button ${disabled?'disabled':''}><strong>${value.title}</strong><small>${value.courseTitle}</small></button></li>`;}
function shell(rows=choice(),open=true){return `<div class="learning-workspace"><section class="learning-staff-directory"><details class="learning-staff-choice-disclosure" ${open?'open':''}><summary>Choose current task</summary><ul>${rows}</ul></details></section><div id="reader"></div></div>`;}
const bind=`document.querySelectorAll('[data-assessment-choice] button').forEach(button=>button.onclick=async()=>{const row=button.closest('li'),response=await fetch('https://learning.fixture.invalid/v1/assessments/'+row.dataset.assessmentChoice);await response.json();button.setAttribute('aria-current','true');document.querySelector('#reader').innerHTML='<article class="assessment-section" data-assessment-id="'+row.dataset.assessmentChoice+'"><h2>'+button.querySelector('strong').textContent+'</h2></article>';});`;

test('explicit current staff choice opens only its human task/course receipt and a closed native disclosure',async({page})=>{
  await page.route('https://learning.fixture.invalid/**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(source)}));await page.setContent(shell(choice()+choice({...source,id:other,courseTitle:'Other current course'}),false)+`<script>${bind}</script>`);
  await expect(page.locator('.assessment-section')).toHaveCount(0);const row=await openCurrentStaffAssessment(page,source);await expect(row.getByRole('heading',{name:source.title,exact:true})).toBeVisible();await expect(page.locator(`[data-assessment-choice="${other}"] button`)).not.toHaveAttribute('aria-current','true');
});

test('current staff source refuses missing duplicate human context disabled choice and wrong exact read',async({page})=>{
  for(const state of ['missing','duplicate','disabled','wrongRead','denied']as const){await page.route('https://learning.fixture.invalid/**',route=>route.fulfill({status:state==='denied'?403:200,contentType:'application/json',body:JSON.stringify(state==='wrongRead'?{...source,courseId:other}:source)}));await page.setContent(shell(state==='missing'?'':state==='duplicate'?choice()+choice({...source,id:other}):choice(source,state==='disabled'))+`<script>${bind}</script>`);await expect(openCurrentStaffAssessment(page,source)).rejects.toThrow();if(['missing','duplicate','disabled'].includes(state))await expect(page.locator('.assessment-section')).toHaveCount(0);await page.unrouteAll({behavior:'wait'});}
});

test('own assessment continuation waits for delayed returned choices before another page and exact selection',async({page})=>{
  const prior={...source,id:other,title:'Earlier source'};let pages=0;await page.route('https://learning.fixture.invalid/**',route=>{const path=new URL(route.request().url()).pathname;if(path==='/v1/assessments'){pages++;return route.fulfill({contentType:'application/json',body:JSON.stringify({items:[source],nextCursor:null})});}return route.fulfill({contentType:'application/json',body:JSON.stringify(source)});});await page.setContent(shell(choice(prior))+`<div class="pagination-actions"><button id="more">Load more</button></div><script>${bind}document.querySelector('.learning-workspace').append(document.querySelector('.pagination-actions'));document.querySelector('#more').onclick=async()=>{await(await fetch('https://learning.fixture.invalid/v1/assessments?limit=100&cursor=${other}')).json();setTimeout(()=>{document.querySelector('ul').insertAdjacentHTML('beforeend',${JSON.stringify(choice())});document.querySelector('#more').remove();${bind}},100)};</script>`);await openCurrentStaffAssessment(page,source);expect(pages).toBe(1);
});

test('denied source status blocks selection and malformed continued identities are refused',async({page})=>{
  await page.setContent(shell().replace('<div id="reader">','<p role="alert">Current source denied</p><div id="reader">'));await expect(openCurrentStaffAssessment(page,source)).rejects.toThrow();await expect(page.locator('.assessment-section')).toHaveCount(0);
  await page.route('https://learning.fixture.invalid/**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({items:[{id:'not-a-current-id'}],nextCursor:null})}));await page.setContent(shell('')+'<script>const more=document.createElement("div");more.className="pagination-actions";more.innerHTML="<button>Load more</button>";document.querySelector(".learning-workspace").append(more);more.querySelector("button").onclick=()=>fetch("https://learning.fixture.invalid/v1/assessments?limit=100");</script>');await expect(openCurrentStaffAssessment(page,source)).rejects.toThrow();
});

test('same requested cursor and oversized continued assessment pages cannot become current choices',async({page})=>{
  for(const value of [{items:[],nextCursor:other},{items:Array.from({length:101},()=>({id:other})),nextCursor:null}]){await page.route('https://learning.fixture.invalid/**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(value)}));await page.setContent(shell('')+`<script>const more=document.createElement('div');more.className='pagination-actions';more.innerHTML='<button>Load more</button>';document.querySelector('.learning-workspace').append(more);more.querySelector('button').onclick=()=>fetch('https://learning.fixture.invalid/v1/assessments?limit=100&cursor=${other}')</script>`);await expect(openCurrentStaffAssessment(page,source)).rejects.toThrow();await expect(page.locator('.assessment-section')).toHaveCount(0);await page.unrouteAll({behavior:'wait'});}
});

test('course read loading settles before native hidden outline Back and preserves current unsent input',async({page})=>{
  for(const hidden of [false,true]){await page.setContent(`<div class="course-view"><h1>Exact current course</h1><p role="status">Loading learning…</p><input value="Unsent current source"></div><script>setTimeout(()=>{document.querySelector('[role=status]').remove();document.querySelector('.course-view').insertAdjacentHTML('beforeend',${JSON.stringify(`${hidden?'<button id="back">Back to course structure</button>':''}<nav aria-label="Course structure" ${hidden?'hidden':''}><button>Exact current course</button></nav>`)});${hidden?"document.querySelector('#back').onclick=()=>document.querySelector('nav').hidden=false;":''}},100)</script>`);const outline=await currentCoursePreparationOutline(page);await expect(outline).toBeVisible();await expect(page.locator('input')).toHaveValue('Unsent current source');}
});

test('course preparation refuses denied missing duplicate and pending Back instead of using another source',async({page})=>{
  for(const state of ['denied','missing','duplicate','pending']as const){await page.setContent(`<div class="course-view">${state==='denied'?'<p role="alert">Denied current source</p>':''}${state==='missing'?'':`<nav aria-label="Course structure" ${state==='pending'?'hidden':''}></nav>`}${state==='duplicate'?'<nav aria-label="Course structure"></nav>':''}${state==='pending'?'<button disabled>Back to course structure</button>':''}</div>`);await expect(currentCoursePreparationOutline(page)).rejects.toThrow();}
});
