import { expectTrailWorkspace, signOutTrailWorkspace, selectTrailPortfolioRecord } from './trail-workspace';
import {test,expect,type Page} from '@playwright/test';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import AxeBuilder from '@axe-core/playwright';
type Account={role:string;email:string;password:string};
const schoolId='10000000-0000-4000-8000-000000000001';
async function signIn(page:Page,account:Account){await page.goto('/');await page.getByRole('button',{name:'English',exact:true}).click();await page.getByLabel('School email').fill(account.email);await page.getByLabel('Password',{exact:true}).fill(account.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expectTrailWorkspace(page, account.role);await page.locator('.workspace-chrome__navigation').getByRole('button',{name:'Portfolio',exact:true}).click();}
async function signOut(page:Page){await page.getByRole('button',{name:'English',exact:true}).click();await signOutTrailWorkspace(page);await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();}
test('learner organizes selected work and the current teacher reviews the exact requested reflection',async({page})=>{
 test.setTimeout(120000);page.setDefaultTimeout(15000);const issues:string[]=[];page.on('pageerror',error=>issues.push(error.message));page.on('console',message=>{if(message.type()==='error'||message.type()==='warning')issues.push(message.text());});
 const accounts=JSON.parse(await readFile('.local/synthetic-accounts.json','utf8'))as Account[];const student=accounts.find(account=>account.role==='student')!;const teacher=accounts.find(account=>account.role==='teacher')!;const parent=accounts.find(account=>account.role==='parent')!;
 const publicKey=process.env.SUPABASE_PUBLISHABLE_KEY;if(!publicKey)throw Error('Synthetic Auth configuration required.');
 async function token(account:Account){const response=await page.request.post(`${process.env.SUPABASE_URL}/auth/v1/token?grant_type=password`,{headers:{apikey:publicKey!},data:{email:account.email,password:account.password}});expect(response.ok()).toBe(true);return(await response.json()).access_token as string;}
 const teacherToken=await token(teacher);const studentToken=await token(student);
 async function command(path:string,body:Record<string,unknown>,accessToken=teacherToken){const response=await page.request.post(`http://localhost:4000${path}`,{headers:{Authorization:`Bearer ${accessToken}`,'X-School-Id':schoolId,'Idempotency-Key':randomUUID()},data:body});expect(response.ok(),`Source setup ${response.status()}`).toBe(true);return await response.json()as{id:string;evidenceId:string};}
 const stamp=new Date().toISOString();const title=`Selected school checking ${stamp}`;const collectionName=`Checking examples ${stamp}`;const reflection='I checked one step using my school example. راجعت خطوة واحدة.';const content='My exact submitted checking explanation. <script>escaped source</script>';
 const course=await command('/v1/courses',{classId:'30000000-0000-4000-8000-000000000001',subjectId:'43000000-0000-4000-8000-000000000001',title,description:'Synthetic portfolio organization journey.'});await command(`/v1/courses/${course.id}/publish`,{});const assessment=await command('/v1/assessments',{courseId:course.id,title,instructions:'Explain one check.',maxScore:10});await command(`/v1/assessments/${assessment.id}/reference`,{referenceId:'61000000-0000-4000-8000-000000000001',expectedPolicyVersion:1});const submitted=await command(`/v1/assessments/${assessment.id}/submissions`,{content},studentToken);const marked=await command(`/v1/submissions/${submitted.id}/results`,{score:0,feedback:'Teacher reviewed submitted checking.',expectedPolicyVersion:2,expectedRevision:0,sourceEvidence:true});const result=await command(`/v1/results/${marked.id}/release`,{expectedRevision:1,parentVisible:false});
 await signIn(page,student);await page.getByRole('button',{name:'Select released work',exact:true}).click();let form=page.getByRole('region',{name:'Select released work',exact:true});for(let pass=0;pass<10&&!await form.getByLabel('Released source evidence').locator(`option[value="${result.evidenceId}"]`).count();pass++){const more=page.getByRole('button',{name:'Load more',exact:true}).last();if(!await more.count())break;await more.click();await expect(page.getByRole('button',{name:'Loading more…',exact:true})).toHaveCount(0);}await form.getByLabel('Released source evidence').selectOption(result.evidenceId);await form.getByLabel('Portfolio title').fill(title);await form.getByLabel('What I learned').fill(reflection);const selectedResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/v1/portfolio/items'&&response.request().method()==='POST');await form.getByRole('button',{name:'Save',exact:true}).click();const item=await(await selectedResponse).json()as{id:string;revisionId:string};
 const organization=page.getByRole('region',{name:'Organize selected work and feedback',exact:true});await organization.getByRole('button',{name:'Create named collection',exact:true}).click();form=organization.getByRole('region',{name:'Create named collection',exact:true});await form.getByLabel('Collection name').fill(collectionName);await form.getByLabel('Collection description').fill('My selected school examples.');const createdResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/v1/portfolio/collections'&&response.request().method()==='POST');await form.getByRole('button',{name:'Save',exact:true}).click();const collection=await(await createdResponse).json()as{id:string};await expect(organization.getByLabel('Selected portfolio work')).toBeVisible();await organization.getByLabel('Selected portfolio work').selectOption(item.id);await organization.getByRole('button',{name:'Place selected work',exact:true}).click();form=organization.getByRole('region',{name:'Place selected work',exact:true});await form.getByLabel('Collection name').selectOption(collection.id);await form.getByLabel('Order in collection').fill('2');const placementResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/portfolio/items/${item.id}/placement`&&response.request().method()==='POST');await form.getByRole('button',{name:'Save',exact:true}).click();expect((await placementResponse).ok()).toBe(true);
 await expect(organization.getByLabel('Selected portfolio work')).toBeVisible();await organization.getByLabel('Selected portfolio work').selectOption(item.id);await organization.getByLabel('Collection name',{exact:true}).first().selectOption(collection.id);await expect(organization.getByRole('heading',{name:collectionName,exact:true})).toBeVisible();await expect(organization).toContainText(reflection);await organization.getByRole('button',{name:'Request teacher feedback',exact:true}).click();form=organization.getByRole('region',{name:'Request teacher feedback',exact:true});await form.getByLabel('What feedback would help').fill('Please review the checking step and reflection.');const confirm=form.getByLabel('I request feedback on this exact reflection revision');await expect(confirm).not.toBeChecked();await confirm.focus();await page.keyboard.press('Space');await expect(confirm).toBeChecked();const requestResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/portfolio/items/${item.id}/feedback-request`&&response.request().method()==='POST');await form.getByRole('button',{name:'Save',exact:true}).click();const requested=await(await requestResponse).json()as{id:string};await expect(page.locator(`[data-portfolio-request-id="${requested.id}"]`)).toContainText('awaiting current teacher review');await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'العربية',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);await signOut(page);
 await signIn(page,teacher);const requestRow=page.locator(`[data-portfolio-request-id="${requested.id}"]`);await expect(requestRow).toBeVisible();await requestRow.getByRole('button',{name:'Open requested source work',exact:true}).click();const source=organization.getByRole('region',{name:'Open requested source work',exact:true});await expect(source.getByText(reflection,{exact:true})).toBeVisible();await expect(source.getByText(content,{exact:true})).toBeVisible();await expect(source.locator('script')).toHaveCount(0);form=source.getByRole('region',{name:'Review requested reflection',exact:true});await form.getByLabel('Teacher feedback').fill('Reviewed the exact checking explanation and reflection.');await expect(form.getByLabel('I reviewed this exact selected source and reflection')).not.toBeChecked();await form.getByLabel('I reviewed this exact selected source and reflection').focus();await page.keyboard.press('Space');const reviewResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/v1/portfolio/items/${item.id}/review`&&response.request().method()==='POST');await form.getByRole('button',{name:'Save',exact:true}).click();const review=await reviewResponse;expect(review.ok()).toBe(true);expect(review.request().postDataJSON()).toMatchObject({expectedRevision:1,parentVisible:false,confirmSourceReview:true});await expect(requestRow).toHaveCount(0);await signOut(page);
 await signIn(page,student);const selectedRow=await selectTrailPortfolioRecord(page,item.id,title);await expect(selectedRow).toContainText('Reviewed the exact checking explanation and reflection.');await expect(page.locator(`[data-portfolio-request-id="${requested.id}"]`)).toHaveCount(0);await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'العربية',exact:true}).click();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);const directory=resolve('.local/customer-readiness/portfolio-organization',stamp.replace(/[:.]/g,'-'));await mkdir(directory,{recursive:true});await selectedRow.scrollIntoViewIfNeeded();await page.screenshot({path:resolve(directory,'reviewed-portfolio-ar.png')});await signOut(page);
 await signIn(page,parent);await expect(page.getByRole('region',{name:'Organize selected work and feedback',exact:true})).toHaveCount(0);await expect(page.locator(`[data-portfolio-request-id="${requested.id}"]`)).toHaveCount(0);expect(issues).toEqual([]);
});
