import {test,expect} from '@playwright/test';
import {build} from 'esbuild';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'../..');
async function ownerSource(){const built=await build({stdin:{resolveDir:root,loader:'tsx',contents:`
 import React,{useState}from'react';import{createRoot}from'react-dom/client';import{InterventionList}from'./apps/web/features/improvement/components/interventions';import{CommandJournal,LearningApiError}from'./apps/web/shared/api/client';import{FormDrafts}from'./apps/web/shared/session/form-drafts';import{getDictionary}from'./apps/web/shared/i18n/locale';
 const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),journal=new CommandJournal(),drafts=new FormDrafts(),task=n=>({id:id(n),recommendationId:id(n+10),learnerId:id(20),referenceId:id(30),baselineResultId:id(40),title:'Checking task '+n,instructions:'Full instructions for task '+n,status:'ASSIGNED',createdAt:'2026-10-03T10:00:00Z',completedAt:null,followUpAssessmentId:null});
 globalThis.practiceFixture={tasks:[task(1),task(2)],writes:[],reads:[],people:[{id:id(20),userId:id(20),displayName:'Alex Reed',role:'student',classLabels:['Cedar · Year 4']}]};
 if(!crypto.randomUUID)Object.defineProperty(crypto,'randomUUID',{value:()=>id(99)});
 function Harness(){const[locale,setLocale]=useState('en'),[role,setRole]=useState('student'),[refresh,setRefresh]=useState(0);globalThis.practiceApp={locale,dictionary:getDictionary(locale),membership:{schoolId:id(50),userId:role==='student'?id(20):id(60),role,entitlements:['improvement']},status:'ready',online:true,apiUrl:'',accessToken:'synthetic',accessGeneration:refresh,commandJournal:journal,formDrafts:drafts,announce(){}};globalThis.practiceRefresh=()=>setRefresh(x=>x+1);globalThis.practiceJournal=journal;return<div className='workspace' dir={locale==='ar'?'rtl':'ltr'}><h1>Practice tasks</h1><button id='locale' onClick={()=>setLocale(x=>x==='en'?'ar':'en')}>Language</button><button id='teacher' onClick={()=>setRole('teacher')}>Teacher</button><InterventionList interventions={globalThis.practiceFixture.tasks} assessments={[]} results={[]} canManage={role==='teacher'} choicesComplete={true} refresh={refresh} onChanged={()=>setRefresh(x=>x+1)} pageHeading/></div>;}createRoot(document.getElementById('root')).render(<Harness/>);
 `},bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',plugins:[{name:'current-practice-boundaries',setup(b){
 b.onLoad({filter:/shared[\\/]session[\\/]providers\.tsx$/},()=>({loader:'js',contents:'export function useApp(){return globalThis.practiceApp}'}));
 b.onLoad({filter:/shared[\\/]hooks[\\/]use-api\.ts$/},()=>({loader:'js',contents:`import{commonEn,commonAr}from'${root.replaceAll('\\','/')}/apps/web/shared/i18n/common';import{LearningApiError}from'${root.replaceAll('\\','/')}/apps/web/shared/api/client';export function useApi(){const a=globalThis.practiceApp;return{t:a.locale==='ar'?commonAr:commonEn,journal:a.commandJournal,request(...args){globalThis.practiceFixture.writes.push(args);return Promise.reject(new LearningApiError('unavailable',true))}}}export function useApiQuery(path,parse){const f=globalThis.practiceFixture;if(!path)return{data:null,loading:false,error:null};f.reads.push(path);const id=path.split('/')[3];return{data:parse(path.endsWith('/help')?{id,interventionId:id,approval:{approvedAt:'2026-10-03T10:00:00Z',teacherName:'Maya Reed',learnerNote:null},help:null}:{id,interventionId:id,options:[],choice:null}),loading:false,error:null}}`}));
 b.onLoad({filter:/shared[\\/]hooks[\\/]use-paginated-query\.ts$/},()=>({loader:'js',contents:'export function usePaginatedLearningQuery(path,parse){return{data:path?globalThis.practiceFixture.people.map(parse):[],context:"current",loaded:true,loading:false,loadingMore:false,error:null,moreError:null,nextCursor:null,loadMore(){}}}'}));
 b.onLoad({filter:/\.(png|webp|svg)$/},args=>({loader:'js',contents:'export default '+JSON.stringify({src:'data:image/'+(args.path.endsWith('.svg')?'svg+xml':args.path.endsWith('.png')?'png':'webp')+';base64,'+readFileSync(args.path).toString('base64'),width:128,height:128})}));
 }}]});return built.outputFiles[0].text;}
async function open(page:import('@playwright/test').Page){await page.route('**/*',r=>r.abort());const css=['packages/ui/src/tokens.css','apps/web/app/globals.css','apps/web/features/improvement/styles.css'].map(p=>readFileSync(resolve(root,p),'utf8')).join('\n');await page.setContent(`<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'/><style>${css}</style></head><body><div id='root'></div></body></html>`);await page.addScriptTag({content:await ownerSource()});}
test('Student and staff practice directories open one exact reader and mobile Back restores source context',async({page})=>{
 await open(page);await expect(page.getByText('Full instructions for task 1',{exact:true})).toHaveCount(0);expect(await page.evaluate(()=>(globalThis as unknown as{practiceFixture:{reads:string[]}}).practiceFixture.reads)).toEqual([]);
 const choice=page.locator('[data-practice-choice="00000000-0000-4000-8000-000000000001"]');await choice.click();await expect(page.getByText('Full instructions for task 1',{exact:true})).toBeVisible();await expect(page.getByText('Full instructions for task 2',{exact:true})).toHaveCount(0);
 for(const width of[390,320]){await page.setViewportSize({width,height:844});await expect(page.locator('.practice-directory')).toBeHidden();await page.locator('#locale').click();await page.getByRole('button',{name:/Back to practice tasks|العودة إلى مهام التدريب/,exact:true}).click();await expect(choice).toBeFocused();await expect(page.locator('.practice-selected')).toHaveCount(0);await choice.click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.getByRole('button',{name:/Back to practice tasks|العودة إلى مهام التدريب/,exact:true}).click();await page.locator('#teacher').click();await choice.click();await expect(page.getByText('Full instructions for task 1',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Complete practice',exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>(globalThis as unknown as{practiceFixture:{writes:unknown[]}}).practiceFixture.writes)).toEqual([]);
});
test('Uncertain own practice completion locks switching and recovers from current completed readback',async({page})=>{
 await open(page);await page.locator('[data-practice-choice="00000000-0000-4000-8000-000000000001"]').click();const form=page.getByRole('region',{name:'Try this practice',exact:true});await form.getByLabel('Reflection (optional)').fill('I checked one step');await form.getByRole('button',{name:'Complete practice',exact:true}).click();await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Back to practice tasks',exact:true})).toBeDisabled();
 await page.evaluate(()=>{const g=globalThis as unknown as{practiceFixture:{tasks:Record<string,unknown>[]},practiceRefresh():void};g.practiceFixture.tasks[0].status='COMPLETED';g.practiceFixture.tasks[0].completedAt='2026-10-03T11:00:00Z';g.practiceRefresh()});await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toBeVisible();await expect(page.locator('.practice-selected form [name]')).toHaveCount(0);
 expect(await page.evaluate(()=>(globalThis as unknown as{practiceFixture:{writes:unknown[]}}).practiceFixture.writes.length)).toBe(1);
});
test('A retained staff measurement opens its original task and survives measured readback without a second command',async({page})=>{
 await open(page);await page.locator('#teacher').click();await page.evaluate(()=>{const g=globalThis as unknown as{practiceFixture:{tasks:Record<string,unknown>[]},practiceJournal:{prepare:(slot:string,path:string,body:Record<string,unknown>)=>void},practiceRefresh():void};const task=g.practiceFixture.tasks[1];task.status='MEASURED';task.completedAt='2026-10-03T11:00:00Z';task.followUpAssessmentId='00000000-0000-4000-8000-000000000090';const path='/v1/interventions/00000000-0000-4000-8000-000000000002/measure';g.practiceJournal.prepare(path,path,{followUpResultId:'00000000-0000-4000-8000-000000000091',minimumChange:1});g.practiceRefresh()});
 await expect(page.getByText('Full instructions for task 2',{exact:true})).toBeVisible();await expect(page.getByText('Full instructions for task 1',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toBeVisible();await expect(page.locator('.practice-selected form [name]')).toHaveCount(0);expect(await page.evaluate(()=>(globalThis as unknown as{practiceFixture:{writes:unknown[]}}).practiceFixture.writes)).toEqual([]);
});
