import type { Page } from '@playwright/test';
import { diagnosticSource } from './course-objective-diagnostics';

/** Current DOM/transport parity only; exclude names, selected values, IDs and source bodies. */
export function observeProgressFocus(page: Page, apiOrigin: string) {
  const reads:{path:string;status:number}[]=[];let truncated=false;
  page.on('response',response=>{const url=new URL(response.url());if(response.request().method()!=='GET'||url.origin!==apiOrigin||!(url.pathname==='/v1/people'||url.pathname==='/v1/classes'||url.pathname.endsWith('/learning-summary')||url.pathname.endsWith('/state')))return;if(reads.length>=20){truncated=true;return;}reads.push({path:diagnosticSource(response.url(),{api:apiOrigin,auth:null,web:''}).path,status:response.status()});});
  return async(expectedLabel:RegExp)=>({schemaVersion:'1',code:'PROGRESS_FOCUS_SOURCE_UNVERIFIED',reads,truncated,dom:await page.evaluate(source=>{const heading=document.querySelector<HTMLElement>('.learner-detail-heading'),selected=document.querySelector<HTMLSelectElement>('#summary-class'),focus=document.activeElement,tag=focus?.tagName??null;return{locale:['en','ar'].includes(document.documentElement.lang)?document.documentElement.lang:null,direction:['ltr','rtl'].includes(document.documentElement.dir)?document.documentElement.dir:null,headingCount:document.querySelectorAll('.learner-detail-heading').length,labelMatches:heading?new RegExp(source).test(heading.getAttribute('aria-label')??''):null,headingFocused:heading?focus===heading:null,focusTag:tag&&['BUTTON','INPUT','SELECT','TEXTAREA','A','H1','H2','H3','DIV','SECTION','SUMMARY','BODY','HTML'].includes(tag)?tag:tag?'OTHER':null,classSelected:selected?selected.value!== '':null,classDisabled:selected?selected.disabled:null,classRowCount:document.querySelectorAll('[data-class-learner-id]').length,loadingCount:[...document.querySelectorAll('[role="status"]')].filter(node=>/^(Loading|جارٍ تحميل)/.test(node.textContent??'')).length,alertCount:document.querySelectorAll('.progress-workspace [role="alert"]').length};},expectedLabel.source)});
}
