import { test, expect } from '@playwright/test';
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root=resolve(import.meta.dirname,'../..');
const failures=new WeakMap<import('@playwright/test').Page,string[]>();
test.beforeEach(async({page})=>{const errors:string[]=[];failures.set(page,errors);page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(['error','warning'].includes(e.type()))errors.push(e.text());});await page.route('**/*',route=>route.abort());});
test.afterEach(({page})=>expect(failures.get(page)).toEqual([]));
async function bundle(){const output=await build({stdin:{resolveDir:root,loader:'tsx',contents:`
 import React,{useState}from'react';import{createRoot}from'react-dom/client';import{ProposalList}from'./apps/web/features/improvement/components/proposals';import{CommandJournal,LearningApiError}from'./apps/web/shared/api/client';import{FormDrafts}from'./apps/web/shared/session/form-drafts';import{getDictionary}from'./apps/web/shared/i18n/locale';
 const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),journal=new CommandJournal(),drafts=new FormDrafts();
 const proposal=n=>({id:id(n),learnerId:id(10),referenceId:id(20),baselineResultId:id(30),origin:'TEACHER_AUTHORED',generationMode:'HUMAN',intelligenceRunId:null,observation:'Full private observation '+n,interpretation:'A possible explanation '+n,recommendation:'Try recorded checking '+n,rationale:'Based on the released work '+n,uncertainty:'One source cannot prove a cause '+n,activityTitle:'Check one step '+n,instructions:'Explain your checking step '+n,status:'AWAITING_HUMAN',evidenceIds:[id(40+n)],createdAt:'2026-10-03T10:00:00Z'});
 globalThis.proposalFixture={proposals:[proposal(1),proposal(2)],writes:[],denied:false,people:[{id:id(10),userId:id(10),displayName:'Alex Reed',role:'student',classLabels:['Cedar · Year 4']}]};
 if(!crypto.randomUUID)Object.defineProperty(crypto,'randomUUID',{value:()=>id(99)});
 function Harness(){const[locale,setLocale]=useState('en'),[refresh,setRefresh]=useState(0),[role,setRole]=useState('teacher');globalThis.proposalApp={locale,dictionary:getDictionary(locale),membership:{schoolId:id(50),userId:id(60),role,entitlements:['improvement']},apiUrl:'',accessToken:'synthetic',status:'ready',online:true,accessGeneration:refresh,commandJournal:journal,formDrafts:drafts,announce(){}};globalThis.proposalRefresh=()=>setRefresh(x=>x+1);return<div className='workspace' dir={locale==='ar'?'rtl':'ltr'}><h1>Proposals</h1><button id='locale' onClick={()=>setLocale(x=>x==='en'?'ar':'en')}>Language</button><button id='coordinator' onClick={()=>setRole('coordinator')}>Coordinator</button><ProposalList proposals={globalThis.proposalFixture.proposals} baselines={[]} canDecide={role==='teacher'} refresh={refresh} onChanged={()=>setRefresh(x=>x+1)} pageHeading/></div>;}createRoot(document.getElementById('root')).render(<Harness/>);
 `},write:false,bundle:true,platform:'browser',format:'iife',jsx:'automatic',plugins:[{name:'bounded-proposal-inputs',setup(b){
 b.onLoad({filter:/shared[\\/]session[\\/]providers\.tsx$/},()=>({loader:'js',contents:'export function useApp(){return globalThis.proposalApp}'}));
 b.onLoad({filter:/shared[\\/]hooks[\\/]use-api\.ts$/},()=>({loader:'js',contents:`import{commonEn,commonAr}from'${root.replaceAll('\\','/')}/apps/web/shared/i18n/common';import{LearningApiError}from'${root.replaceAll('\\','/')}/apps/web/shared/api/client';export function useApi(){const a=globalThis.proposalApp;return{t:a.locale==='ar'?commonAr:commonEn,journal:a.commandJournal,request(...args){globalThis.proposalFixture.writes.push(args);return Promise.reject(new LearningApiError('unavailable',true))}}}export function useApiQuery(path,parse){const f=globalThis.proposalFixture;if(path?.endsWith('/context')&&f.context){try{return{data:parse(f.context),loading:false,error:null}}catch{return{data:null,loading:false,error:new LearningApiError('invalid')}}};return{data:null,loading:false,error:null}}`}));
 b.onLoad({filter:/shared[\\/]hooks[\\/]use-paginated-query\.ts$/},()=>({loader:'js',contents:`import{LearningApiError}from'${root.replaceAll('\\','/')}/apps/web/shared/api/client';export function usePaginatedLearningQuery(path,parse){const f=globalThis.proposalFixture;return{data:path?f.people.map(parse):[],context:'people:'+globalThis.proposalApp.accessGeneration,loaded:true,loading:false,loadingMore:false,error:f.denied?new LearningApiError('denied'):null,moreError:null,nextCursor:null,loadMore(){}}}`}));
 b.onLoad({filter:/\.(webp|png|svg)$/},args=>({loader:'js',contents:'export default '+JSON.stringify({src:'data:image/'+(args.path.endsWith('.svg')?'svg+xml':args.path.endsWith('.png')?'png':'webp')+';base64,'+readFileSync(args.path).toString('base64'),width:128,height:128})}));
 }}]});return output.outputFiles[0].text;}
async function open(page:import('@playwright/test').Page){const css=['packages/ui/src/tokens.css','apps/web/app/globals.css','apps/web/features/improvement/styles.css'].map(p=>readFileSync(resolve(root,p),'utf8')).join('\n');await page.setContent(`<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'/><style>${css}</style></head><body><div id='root'></div></body></html>`);await page.addScriptTag({content:await bundle()});await page.locator('.proposal-workspace').waitFor();}

test('Proposal summaries open one exact reader and mobile Back restores the current directory',async({page})=>{
 await open(page);await expect(page.getByText('Full private observation 1',{exact:true})).toHaveCount(0);
 const directory=page.locator('.proposal-directory');await expect(directory).toBeVisible();
 await directory.getByRole('button').filter({hasText:'Try recorded checking 1'}).click();await expect(page.locator('.proposal-selected')).toHaveCount(1);await expect(page.getByText('Full private observation 1',{exact:true})).toBeVisible();await expect(page.getByText('Full private observation 2',{exact:true})).toHaveCount(0);
 for(const width of[390,320]){await page.setViewportSize({width,height:844});await expect(directory).toBeHidden();await page.locator('#locale').click();await page.getByRole('button',{name:/Back to proposals|العودة إلى المقترحات/,exact:true}).click();await expect(directory).toBeVisible();await expect(page.locator('.proposal-selected')).toHaveCount(0);await expect(directory.locator('button').first()).toBeFocused();await directory.locator('button').first().click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.getByRole('button',{name:/Back to proposals|العودة إلى المقترحات/,exact:true}).click();await page.locator('#coordinator').click();await directory.locator('button').first().click();await expect(page.getByRole('button',{name:'Approve practice',exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>(globalThis as unknown as{proposalFixture:{writes:unknown[]}}).proposalFixture.writes)).toEqual([]);
});

test('An unresolved proposal decision retains one original retry when refreshed status removes new approval',async({page})=>{
 await open(page);await page.locator('.proposal-directory').getByRole('button').filter({hasText:'Try recorded checking 1'}).click();await page.getByRole('button',{name:'Approve practice',exact:true}).click();
 const form=page.getByRole('region',{name:'Approve practice',exact:true});await form.getByLabel('Decision reason').fill('I reviewed the exact source');await form.getByRole('button',{name:'Approve practice',exact:true}).click();await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Back to proposals',exact:true})).toBeDisabled();
 await page.evaluate(()=>{const g=globalThis as unknown as{proposalFixture:{proposals:{status:string}[]},proposalRefresh():void};g.proposalFixture.proposals[0].status='APPROVED';g.proposalRefresh()});
 await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toBeVisible();await expect(page.locator('.proposal-selected form [name]')).toHaveCount(0);
 expect(await page.evaluate(()=>(globalThis as unknown as{proposalFixture:{writes:unknown[]}}).proposalFixture.writes.length)).toBe(1);
 await page.evaluate(()=>{const g=globalThis as unknown as{proposalFixture:{proposals:unknown[]},proposalRefresh():void};g.proposalFixture.proposals=[];g.proposalRefresh()});await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toHaveCount(0);await expect(page.getByText('Full private observation 1',{exact:true})).toHaveCount(0);
});

test('Selected demonstration detail preserves provenance and mismatched choice context cannot grant options',async({page})=>{
 await open(page);await page.evaluate(()=>{const g=globalThis as unknown as{proposalFixture:{proposals:Record<string,unknown>[];context:unknown},proposalRefresh():void};const p=g.proposalFixture.proposals[0];p.origin='AI_GENERATED';p.generationMode='FIXTURE';p.intelligenceRunId='00000000-0000-4000-8000-000000000070';p.selectedActivityId='00000000-0000-4000-8000-000000000071';g.proposalFixture.context={runId:'00000000-0000-4000-8000-000000000099',context:{schemaVersion:'1',learnerId:'00000000-0000-4000-8000-000000000010',courseId:'00000000-0000-4000-8000-000000000080',classId:'00000000-0000-4000-8000-000000000081',reference:{id:'00000000-0000-4000-8000-000000000020',version:'school-v1',title:'School objective'},recentResults:[{resultId:'00000000-0000-4000-8000-000000000030',evidenceId:'00000000-0000-4000-8000-000000000041',referenceId:'00000000-0000-4000-8000-000000000020',referenceVersion:'school-v1',score:0,maxScore:10}],observations:[],priorInterventions:[],learningOptions:[{activityId:'00000000-0000-4000-8000-000000000071',kind:'practice',title:'Current approved candidate',instructions:'Explain a check'}],coverage:'BOUNDED_AUTHORIZED_CONTEXT'}};g.proposalRefresh()});
 await page.locator('.proposal-directory').getByRole('button').filter({hasText:'Try recorded checking 1'}).click();await expect(page.locator('.proposal-selected')).toContainText('prepared example output');await expect(page.locator('.proposal-selected')).toContainText('does not establish live model performance');
 await page.getByRole('button',{name:'Approve practice',exact:true}).click();await expect(page.getByRole('checkbox',{name:'Current approved candidate',exact:true})).toHaveCount(0);
 await page.evaluate(()=>{const g=globalThis as unknown as{proposalFixture:{context:{runId:string}},proposalRefresh():void};g.proposalFixture.context.runId='00000000-0000-4000-8000-000000000070';g.proposalRefresh()});
 const candidate=page.getByRole('checkbox',{name:'Current approved candidate',exact:true});await expect(candidate).toBeVisible();await candidate.check();await expect(candidate).toBeChecked();
 await page.getByRole('region',{name:'Approve practice',exact:true}).getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Approve practice',exact:true}).click();await expect(candidate).not.toBeChecked();
});
