import { test, expect, type Page } from '@playwright/test';
import{build}from'esbuild';import{resolve}from'node:path';import{readFile}from'node:fs/promises';
declare global{interface Window{restrictedProbe:{change(kind:string):void;pending(kind:string):void;facts():{commands:{key:string;body:Record<string,unknown>}[];writes:number}}}}
// Real Restricted owner, parsers, forms and journals; fictional session/read inputs.
// Every URL is intercepted; no Auth/API/database/worker or command send is performed.
const repositoryRoot = resolve(import.meta.dirname, '../..');
let bundle = '', css = '';
const browserErrors = new WeakMap<Page, string[]>();
test.beforeEach(({ page }) => { const errors: string[] = []; browserErrors.set(page, errors); page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (['warning', 'error'].includes(message.type())) errors.push(message.text()); }); });
test.afterEach(({ page }) => { expect(browserErrors.get(page)).toEqual([]); });
test.beforeAll(async()=>{css = (await Promise.all(['packages/ui/src/tokens.css', 'apps/web/app/globals.css', 'apps/web/features/restricted-records/styles.css'].map(path => readFile(resolve(repositoryRoot, path), 'utf8')))).join('\n');const result=await build({write:false,bundle:true,platform:'browser',format:'iife',loader:{'.webp':'dataurl'},jsx:'automatic',stdin:{resolveDir:repositoryRoot,loader:'tsx',contents:`
import React,{createContext,useContext,useState,useEffect,useSyncExternalStore}from'react';import{createRoot}from'react-dom/client';import{RestrictedRecordsWorkspace}from'./apps/web/features/restricted-records/components/workspace';import{CommandJournal,LearningApiError}from'./apps/web/shared/api/client';import{FormDrafts}from'./apps/web/shared/session/form-drafts';import{commonEn,commonAr}from'./apps/web/shared/i18n/common';
const Context=createContext(null);globalThis.restrictedContext=Context;globalThis.restrictedUseContext=useContext;
const id=n=>'c5000000-0000-4000-8000-'+String(n).padStart(12,'0');const records=[1,2].map((n)=>({id:id(n+2),courseId:id(8),learnerId:id(n+10),title:'Classroom account '+n,note:'Private factual note '+n+' '.repeat(1)+'current source only.',occurredAt:'2026-10-05T10:00:00Z',revision:1,authorId:id(2),authorName:'Maya Reed',learnerName:'Alex Taylor '+n,courseTitle:'Current reasoning course',className:'Cedar',state:'AWAITING_REVIEW',followUpOwnerId:null,followUpOwnerName:null,followUpInstructions:null,followUpNote:null,retentionStatus:'SYNTHETIC_ONLY'}));let writes=0;const continuation={records:false,courses:false,people:false};globalThis.restrictedContinuation=continuation;
globalThis.restrictedQueries={single(path,parse){const app=useContext(Context);if(!path)return{data:null,loading:false,error:null};if(app.denied)return{data:null,loading:false,error:new LearningApiError('denied')};const value=path.endsWith('/policy')?{id:id(1),version:1,enabled:!app.disabled,purpose:'BASIC_INCIDENT_NOTE',retentionStatus:'SYNTHETIC_ONLY',ownerId:id(2),retentionNote:'Approved synthetic-only context'}:{items:[{id:id(40),revision:1,title:'Earlier current factual note',note:'Historical source note',state:'AWAITING_REVIEW',reason:'Source correction review',createdAt:'2026-10-05T10:00:00Z',actorName:'Maya Reed'}],nextCursor:null};return{data:parse(value),loading:false,error:null};},page(path,parse){const app=useContext(Context);const kind=path?.startsWith('/v1/restricted-records?')?'records':path?.startsWith('/v1/restricted-records/choices')?'courses':path?.includes('/courses/')?'people':null;let rows=path?.startsWith('/v1/restricted-records?')?records.map(row=>app.changed?{...row,revision:2,note:'Changed current factual note'}:row):path?.startsWith('/v1/restricted-records/choices')?[{id:id(8),title:'Current reasoning course',className:'Cedar'}]:path?.includes('/courses/')?[{id:id(11),displayName:'Alex Taylor 1',role:'student'},{id:id(2),displayName:'Maya Reed',role:'teacher'}]:[];return{data:path&&!app.denied?rows.map(parse):[],loaded:!!path,loading:false,loadingMore:false,error:path&&app.denied?new LearningApiError('denied'):null,moreError:null,nextCursor:kind&&continuation[kind]?id(90):null,loadMore(){if(kind){continuation[kind]=false;globalThis.restrictedRefresh();}}};},api(){const app=useContext(Context);return{t:app.locale==='ar'?commonAr:commonEn,journal:app.commandJournal,request:async()=>{writes++;throw new LearningApiError('unavailable',true);}}}};
function Fixture(){const[journal]=useState(()=>new CommandJournal()),[drafts]=useState(()=>new FormDrafts()),[state,setState]=useState({locale:'en',denied:false,changed:false,apiUrl:'https://fixture.invalid',accessToken:'fictional',accessGeneration:1,online:true,status:'ready',membership:{schoolId:id(1),userId:id(2),role:'admin',entitlements:['school.operations','restricted.records']},commandJournal:journal,formDrafts:drafts,refreshAccess(){},reportDiagnostic(){}});useEffect(()=>{document.documentElement.lang=state.locale;document.documentElement.dir=state.locale==='ar'?'rtl':'ltr';},[state.locale]);globalThis.restrictedRefresh=()=>setState(value=>({...value,fixtureRevision:(value.fixtureRevision??0)+1}));useSyncExternalStore(journal.subscribe,journal.getSnapshot,journal.getSnapshot);globalThis.restrictedProbe={change(kind){setState(value=>({...value,...(kind==='ar'?{locale:'ar'}:kind==='en'?{locale:'en'}:kind==='disabled'?{disabled:true}:kind==='enabled'?{disabled:false}:kind==='generation'?{accessGeneration:value.accessGeneration+1}:kind==='teacher'?{membership:{...value.membership,role:'teacher'}}:kind==='denied'?{denied:true}:kind==='source'?{changed:true}:{accessToken:'replacement',accessGeneration:2})}));},pending(kind){if(kind==='policy')journal.prepare('/v1/restricted-records/policy','/v1/restricted-records/policy',{enabled:true,expectedVersion:1,purpose:'BASIC_INCIDENT_NOTE',sourceBasis:'SCHOOL_AUTHORED',retentionStatus:'SYNTHETIC_ONLY',retentionNote:'Original retained policy',ownerId:id(2),reason:'Original policy reason',confirmApproval:true});else journal.prepare('/v1/restricted-records/'+id(3)+'/correct','/v1/restricted-records/'+id(3)+'/correct',{expectedRevision:1,title:'Original corrected title',note:'Original correction note',reason:'Original correction reason',confirmCorrection:true});},facts(){return{commands:journal.pending(),writes}}};return<Context.Provider value={state}><main className='workspace workspace-main' lang={state.locale} dir={state.locale==='ar'?'rtl':'ltr'}><RestrictedRecordsWorkspace/></main></Context.Provider>;}
createRoot(document.getElementById('root')).render(<Fixture/>);`},plugins:[{name:'fixture-session',setup(api){api.onLoad({filter:/shared[\\/]session[\\/]providers\.tsx$/},()=>({loader:'js',contents:'export function useApp(){return globalThis.restrictedUseContext(globalThis.restrictedContext)}'}));api.onLoad({filter:/shared[\\/]hooks[\\/]use-api\.ts$/},()=>({loader:'js',contents:'export function useApi(){return globalThis.restrictedQueries.api()}export function useApiQuery(path,parse){return globalThis.restrictedQueries.single(path,parse)}'}));api.onLoad({filter:/shared[\\/]hooks[\\/]use-paginated-query\.ts$/},()=>({loader:'js',contents:'export function usePaginatedLearningQuery(path,parse){return globalThis.restrictedQueries.page(path,parse)}'}));}}]});bundle=result.outputFiles[0].text;});
async function load(page: Page){await page.route('**/*',route=>route.request().url()==='http://localhost/restricted-focused'?route.fulfill({contentType:'text/html',body:`<!DOCTYPE html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}</style></head><body><div id="root"></div></body></html>`}):route.abort());await page.goto('http://localhost/restricted-focused');await page.addScriptTag({content:bundle});await expect(page.locator('.restricted-directory')).toBeVisible();}
test('actual Restricted summary directory opens one current reader and Back restores visible context EN AR 320 390',async({page})=>{await load(page);for(const width of[320,390]){await page.setViewportSize({width,height:844});for(const locale of['en','ar']){await page.evaluate(value=>window.restrictedProbe.change(value),locale);await expect(page.locator('.restricted-reader')).toHaveCount(0);await expect(page.getByText('Private factual note 1 current source only.',{exact:true})).toHaveCount(0);const choice=page.locator('.restricted-directory > button').filter({hasText:'Classroom account 1'});await choice.click();await expect(page.locator('.restricted-reader')).toHaveCount(1);await expect(page.locator('.restricted-reader')).toContainText('Private factual note 1');await expect(page.locator('.restricted-reader h2')).toBeFocused();await expect(page.locator('.restricted-directory')).toHaveCount(0);await page.getByRole('button',{name:locale==='ar'?'سجل المراجعات المقيّد':'Restricted revision history',exact:true}).click();await expect(page.getByText('Historical source note',{exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:locale==='ar'?'العودة إلى الملاحظات الحالية':'Back to current notes',exact:true}).click();await expect(choice).toBeFocused();await expect(page.locator('.restricted-reader')).toHaveCount(0); }}expect((await page.evaluate(()=>window.restrictedProbe.facts())).writes).toBe(0);});
test('changed denied and old-session selected Restricted sources withhold note and actions without replacement selection',async({page})=>{for(const kind of['source','denied','token']){await load(page);await page.locator('.restricted-directory > button').filter({hasText:'Classroom account 1'}).click();await page.evaluate(value=>window.restrictedProbe.change(value),kind);await expect(page.locator('.restricted-reader')).toHaveCount(0);await expect(page.getByText('Private factual note 1 current source only.',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Create factual correction revision',exact:true})).toHaveCount(0);expect((await page.evaluate(()=>window.restrictedProbe.facts())).writes).toBe(0);await page.unrouteAll();}});
test('policy opening is explicit exclusive and another original record command locks it while own policy retry remains',async({page})=>{await load(page);await expect(page.locator('form')).toHaveCount(0);await page.getByRole('button',{name:'Review restricted record policy',exact:true}).click();await expect(page.locator('form')).toHaveCount(1);await expect(page.locator('.restricted-directory')).toHaveCount(0);await page.getByRole('button',{name:'Back to current notes',exact:true}).click();await page.evaluate(()=>window.restrictedProbe.pending('record'));await expect(page.getByRole('button',{name:'Review restricted record policy',exact:true})).toBeDisabled();await expect(page.getByLabel('School-authored retention review note',{exact:true})).toHaveCount(0);const before=await page.evaluate(()=>window.restrictedProbe.facts());await page.unrouteAll();await load(page);await page.getByRole('button',{name:'Review restricted record policy',exact:true}).click();await page.evaluate(()=>window.restrictedProbe.pending('policy'));const key=await page.evaluate(()=>window.restrictedProbe.facts().commands[0].key);await page.evaluate(()=>window.restrictedProbe.change('generation'));await expect(page.getByRole('button',{name:'Retry the same action',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Back to current notes',exact:true})).toBeDisabled();expect((await page.evaluate(()=>window.restrictedProbe.facts())).commands[0].key).toBe(key);expect(before.commands[0].body.note).toBe('Original correction note');expect((await page.evaluate(()=>window.restrictedProbe.facts())).writes).toBe(0);});

 test('disabled Restricted policy Back restores its current opener and keeps private records absent EN AR', async ({ page }) => { await load(page); await page.evaluate(() => window.restrictedProbe.change('disabled')); await expect(page.locator('.restricted-directory')).toHaveCount(0); for (const locale of ['en', 'ar']) { await page.evaluate(value => window.restrictedProbe.change(value), locale); const opener = page.getByRole('button', { name: locale === 'ar' ? 'مراجعة سياسة السجلات المقيّدة' : 'Review restricted record policy', exact: true }); await opener.click(); await expect(page.locator('form')).toHaveCount(1); await page.getByRole('button', { name: locale === 'ar' ? 'العودة إلى الملاحظات الحالية' : 'Back to current notes', exact: true }).click(); await expect(opener).toBeFocused(); await expect(page.locator('.restricted-reader')).toHaveCount(0); await expect(page.locator('form')).toHaveCount(0); } expect((await page.evaluate(() => window.restrictedProbe.facts())).writes).toBe(0); });

test('a selected Restricted approval can complete every required current source before exposing assigned teacher consent',async({page})=>{
 await load(page);await page.evaluate(()=>{const current=globalThis as unknown as{restrictedContinuation:{records:boolean;courses:boolean;people:boolean};restrictedRefresh:()=>void};Object.assign(current.restrictedContinuation,{records:true,courses:true,people:true});current.restrictedRefresh();});await page.locator('.restricted-directory > button').filter({hasText:'Classroom account 1'}).click();const reader=page.locator('.restricted-reader');await reader.getByRole('button',{name:'Approve manual follow-up',exact:true}).click();await expect(reader.getByRole('region',{name:'Approve manual follow-up',exact:true})).toHaveCount(0);
 for(const label of['Current restricted notes','Current course and class','Assigned current teacher']){await reader.getByRole('button',{name:`Load more: ${label}`,exact:true}).click();}
 const form=reader.getByRole('region',{name:'Approve manual follow-up',exact:true});await expect(form.getByLabel('Assigned current teacher',{exact:true})).toBeEnabled();await expect(form.getByLabel('I reviewed this exact factual note and approve the assigned follow-up',{exact:true})).not.toBeChecked();expect((await page.evaluate(()=>window.restrictedProbe.facts())).writes).toBe(0);
});

test('selected Restricted source continuations stay locked by the exact original action and disappear on denial',async({page})=>{
 await load(page);await page.evaluate(()=>{const current=globalThis as unknown as{restrictedContinuation:{records:boolean;courses:boolean;people:boolean};restrictedRefresh:()=>void};Object.assign(current.restrictedContinuation,{records:true,courses:true,people:true});current.restrictedRefresh();});await page.locator('.restricted-directory > button').filter({hasText:'Classroom account 1'}).click();const reader=page.locator('.restricted-reader');await reader.getByRole('button',{name:'Approve manual follow-up',exact:true}).click();await page.evaluate(()=>window.restrictedProbe.pending('record'));await expect(reader.getByRole('button',{name:'Load more: Current restricted notes',exact:true})).toBeDisabled();await expect(reader.getByRole('button',{name:'Load more: Current course and class',exact:true})).toBeDisabled();const original=(await page.evaluate(()=>window.restrictedProbe.facts())).commands[0];await page.evaluate(()=>window.restrictedProbe.change('denied'));await expect(page.locator('.restricted-reader')).toHaveCount(0);expect((await page.evaluate(()=>window.restrictedProbe.facts())).commands[0]).toEqual(original);expect((await page.evaluate(()=>window.restrictedProbe.facts())).writes).toBe(0);
});
