import { test, expect } from '@playwright/test';
import { build } from 'esbuild';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '../..');
type ReadRequest = {path:string;method:string;aborted:boolean};
type SignOutFacts = {status:string;enabled:boolean;requests:ReadRequest[];events:{phase:string;aborted:boolean[];mutationAborted:boolean[]}[];revokeCount:number;membershipCount:number;userId:string|null;singleError:string|null;pageError:string|null;draft:string|null;command:string|null};
declare global { var probeFacts:()=>SignOutFacts; var prepareOriginal:()=>void; var beginLogout:()=>void; var finishLogout:(result:'success'|'failure')=>void; var tryRead:()=>Promise<string>; var refreshMembership:()=>void; var finishInitialSession:()=>void; var changeActor:(sameActor?:boolean)=>void; var emitSignedOut:()=>void; }

async function mount(page: import('@playwright/test').Page, scenario: 'queries' | 'membership' | 'initial-session' = 'queries') {
 const script=(await build({write:false,bundle:true,platform:'browser',format:'iife',jsx:'automatic',stdin:{resolveDir:root,loader:'tsx',contents:`
import React from'react';import{createRoot}from'react-dom/client';import{Providers,useApp}from'./apps/web/shared/session/providers';import{useApi,useApiQuery}from'./apps/web/shared/hooks/use-api';import{usePaginatedLearningQuery}from'./apps/web/shared/hooks/use-paginated-query';
const callbacks=[],events=[],requests=[];let finishInitialSession,finishLogout,revokeCount=0,membershipCount=0,changedActor=false,sameActorChange=false;const scenario='${scenario}';const session={access_token:'synthetic-old-token',user:{id:'e9000000-0000-4000-8000-000000000001'}};
// Controlled Auth input: changed-session cases intentionally omit a null event to isolate late promise settlement. Real SIGNED_OUT is separately emitted/tested and always authoritative.
const auth={onAuthStateChange(fn){callbacks.push(fn);queueMicrotask(()=>fn('SIGNED_IN',session));return{data:{subscription:{unsubscribe(){}}}}},getSession:async()=>scenario==='initial-session'?await new Promise(done=>finishInitialSession=()=>done({data:{session},error:null})):({data:{session},error:null}),signOut:async()=>{revokeCount++;events.push({phase:'sdk-logout',aborted:requests.filter(r=>r.method==='GET').map(r=>r.signal?.aborted??false),mutationAborted:requests.filter(r=>r.method==='POST').map(r=>r.signal?.aborted??false)});const result=await new Promise(done=>finishLogout=done);if(result==='success'&&!changedActor)for(const fn of callbacks)fn('SIGNED_OUT',null);return{error:result==='success'?null:{status:503}}}};globalThis.probeAuth={auth};
const membership={userId:session.user.id,schoolId:'e9000000-0000-4000-8000-000000000002',membershipId:'e9000000-0000-4000-8000-000000000003',role:'teacher',displayName:'Synthetic teacher',school:{id:'e9000000-0000-4000-8000-000000000002',name:'Synthetic school'},entitlements:['learning','curriculum']};
globalThis.fetch=(url,options={})=>{const path=new URL(url).pathname;if(path==='/v1/me'){membershipCount++;if(scenario==='membership'&&membershipCount>1)return new Promise((done,reject)=>{requests.push({path,method:'GET',signal:options.signal});options.signal?.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')));});return Promise.resolve(new Response(JSON.stringify(changedActor?{...membership,userId:sameActorChange?session.user.id:'e9000000-0000-4000-8000-000000000004',displayName:'New synthetic teacher'}:membership),{status:200}));}if(path==='/v1/diagnostics/config')return new Promise((done,reject)=>{requests.push({path,method:'GET',signal:options.signal});options.signal?.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')));});return new Promise((done,reject)=>{requests.push({path,method:options.method??'GET',signal:options.signal,done});options.signal?.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')));});};
const parse=value=>value;let appRef,requestRef;function Probe(){const app=useApp();appRef=app;const api=useApi();requestRef=api.request;const single=useApiQuery(app.status==='ready'?'/v1/curriculum/learning-availability':null,parse,0),page=usePaginatedLearningQuery(app.status==='ready'?'/v1/curriculum/programmes?limit=100':null,parse,0);globalThis.probeFacts=()=>({status:app.status,enabled:app.readLifecycle.enabled,requests:requests.map(r=>({path:r.path,method:r.method,aborted:r.signal?.aborted??false})),events,revokeCount,membershipCount,userId:app.membership?.userId??null,singleError:single.error?.kind??null,pageError:page.error?.kind??page.moreError?.kind??null,draft:app.formDrafts.get('original-private-work')?.values.text??null,command:app.commandJournal.get('/v1/original')?.key??null});return <input aria-label='Unsent original work' defaultValue='Original typed work'/>}
globalThis.finishInitialSession=()=>finishInitialSession();globalThis.emitSignedOut=()=>{for(const fn of callbacks)fn('SIGNED_OUT',null)};globalThis.prepareOriginal=()=>{appRef.formDrafts.save('original-private-work',{text:'Original private draft'},{});const command=appRef.commandJournal.prepare('/v1/original','/v1/original',{text:'Original command'});void requestRef('/v1/original',{command}).catch(()=>{});};globalThis.beginLogout=()=>{void appRef.signOut()};globalThis.refreshMembership=()=>appRef.refreshAccess();globalThis.changeActor=(same=false)=>{changedActor=true;sameActorChange=same;for(const fn of callbacks)fn('SIGNED_IN',{access_token:'new-synthetic-token',user:{id:same?session.user.id:'e9000000-0000-4000-8000-000000000004'}})};globalThis.finishLogout=result=>finishLogout(result);globalThis.tryRead=async()=>{try{await requestRef('/v1/curriculum/new');return'allowed';}catch{return'withheld'}};
createRoot(document.getElementById('root')).render(<Providers initialLocale='en' config={{supabaseUrl:'https://auth.fixture.invalid',supabasePublishableKey:'sb_publishable_fixture',apiUrl:'https://api.fixture.invalid'}}><Probe/></Providers>);
`},plugins:[{name:'synthetic-auth-input-only',setup(b){b.onLoad({filter:/shared[\\/]session[\\/]supabase\.ts$/},()=>({loader:'js',contents:'export function createAuthClient(){return globalThis.probeAuth}'}));}}]})).outputFiles[0].text;
 await page.route('**/*',route=>route.request().url()==='http://localhost/session-read-sign-out'?route.fulfill({contentType:'text/html',body:'<div id="root"></div>'}):route.abort());await page.goto('http://localhost/session-read-sign-out');await page.addScriptTag({content:script});await page.waitForFunction(()=>globalThis.probeFacts?.().status==='ready'&&globalThis.probeFacts().requests.filter(r=>r.path.startsWith('/v1/curriculum/')).length===2);await page.evaluate(()=>globalThis.prepareOriginal());
}
for(const result of ['success','failure'] as const)test(`${result}: protected reads stop before Auth revocation while original commands retain their own receipt`,async({page})=>{
 await mount(page);const before=await page.evaluate(()=>globalThis.probeFacts());await page.evaluate(()=>globalThis.beginLogout());await page.waitForFunction(()=>globalThis.probeFacts().events.length===1);const held=await page.evaluate(()=>globalThis.probeFacts());expect(held.events[0].aborted).not.toHaveLength(0);expect(held.events[0].aborted.every(Boolean)).toBe(true);expect(held.events[0].mutationAborted).toEqual([false]);expect(held.command).toBe(before.command);expect(held.draft).toBe('Original private draft');expect(held.singleError).toBeNull();expect(held.pageError).toBeNull();const count=held.requests.length;expect(await page.evaluate(()=>globalThis.tryRead())).toBe('withheld');expect((await page.evaluate(()=>globalThis.probeFacts())).requests).toHaveLength(count);await page.evaluate(value=>globalThis.finishLogout(value),result);await page.waitForFunction(value=>globalThis.probeFacts().status===(value==='success'?'signed-out':'ready')&&(value==='success'||globalThis.probeFacts().membershipCount>1),result);const after=await page.evaluate(()=>globalThis.probeFacts());if(result==='failure'){expect(after.command).toBe(before.command);expect(after.draft).toBe('Original private draft');expect(after.enabled).toBe(true);expect(after.singleError).toBeNull();expect(after.pageError).toBeNull();await expect(page.getByLabel('Unsent original work')).toHaveValue('Original typed work');}else{expect(after.command).toBeNull();expect(after.draft).toBeNull();expect(after.enabled).toBe(false);}expect(after.requests.filter(r=>r.method==='POST').every(r=>!r.aborted)).toBe(true);
});


test('membership revalidation aborts before revocation and its stale failure does not clear retained work', async ({ page }) => {
 await mount(page,'membership');await page.evaluate(()=>globalThis.refreshMembership());await page.waitForFunction(()=>globalThis.probeFacts().requests.some(r=>r.path==='/v1/me'));await page.evaluate(()=>globalThis.beginLogout());await page.waitForFunction(()=>globalThis.probeFacts().events.length===1);const held=await page.evaluate(()=>globalThis.probeFacts());expect(held.events[0].aborted.every(Boolean)).toBe(true);expect(held.status).toBe('ready');expect(held.draft).toBe('Original private draft');expect(held.command).not.toBeNull();await page.evaluate(()=>globalThis.finishLogout('success'));await page.waitForFunction(()=>globalThis.probeFacts().status==='signed-out');
});

for(const completion of ['failure','success'] as const)test(`a new actor receives fresh read verification after original logout ${completion} without reopening the old ticket`, async ({ page }) => {
 await mount(page);await page.evaluate(()=>globalThis.beginLogout());await page.waitForFunction(()=>globalThis.probeFacts().events.length===1);await page.evaluate(()=>globalThis.changeActor());await page.evaluate(value=>globalThis.finishLogout(value),completion);await page.waitForFunction(()=>globalThis.probeFacts().status==='ready'&&globalThis.probeFacts().membershipCount>1);const facts=await page.evaluate(()=>globalThis.probeFacts());expect(facts.enabled).toBe(true);expect(facts.userId).toBe('e9000000-0000-4000-8000-000000000004');expect(facts.command).toBeNull();expect(facts.draft).toBeNull();expect(facts.requests.slice(0,3).every(r=>r.aborted)).toBe(true);expect(facts.requests.filter(r=>r.method==='POST').every(r=>!r.aborted)).toBe(true);
});


for(const completion of ['failure','success'] as const)test(`a same actor fresh token survives older logout ${completion} with current source verification`,async({page})=>{
 await mount(page);const before=await page.evaluate(()=>globalThis.probeFacts());await page.evaluate(()=>globalThis.beginLogout());await page.waitForFunction(()=>globalThis.probeFacts().events.length===1);await page.evaluate(()=>globalThis.changeActor(true));await page.evaluate(value=>globalThis.finishLogout(value),completion);await page.waitForFunction(()=>globalThis.probeFacts().status==='ready'&&globalThis.probeFacts().membershipCount>1);const after=await page.evaluate(()=>globalThis.probeFacts());expect(after.enabled).toBe(true);expect(after.userId).toBe('e9000000-0000-4000-8000-000000000001');expect(after.command).toBe(before.command);expect(after.draft).toBe('Original private draft');expect(after.requests.slice(0,3).every(r=>r.aborted)).toBe(true);
});

for(const completion of ['success','failure'] as const)test(`offline and online events keep reads paused until logout ${completion} settles`,async({page})=>{
 await mount(page);await page.evaluate(()=>globalThis.beginLogout());await page.waitForFunction(()=>globalThis.probeFacts().events.length===1);await page.evaluate(()=>{dispatchEvent(new Event('offline'));dispatchEvent(new Event('online'));});await page.waitForFunction(()=>!globalThis.probeFacts().enabled);expect(await page.evaluate(()=>globalThis.tryRead())).toBe('withheld');await page.evaluate(value=>globalThis.finishLogout(value),completion);await page.waitForFunction(value=>globalThis.probeFacts().status===(value==='success'?'signed-out':'ready'),completion);expect((await page.evaluate(()=>globalThis.probeFacts())).enabled).toBe(completion==='failure');
});


test('a late initial Auth session read cannot resurrect the earlier actor after current sign-out',async({page})=>{
 await mount(page,'initial-session');await page.evaluate(()=>globalThis.beginLogout());await page.waitForFunction(()=>globalThis.probeFacts().events.length===1);await page.evaluate(()=>globalThis.finishLogout('success'));await page.waitForFunction(()=>globalThis.probeFacts().status==='signed-out');await page.evaluate(()=>globalThis.finishInitialSession());await page.evaluate(()=>new Promise(requestAnimationFrame));expect((await page.evaluate(()=>globalThis.probeFacts())).status).toBe('signed-out');expect((await page.evaluate(()=>globalThis.probeFacts())).enabled).toBe(false);
});


test('a genuine SIGNED_OUT after a newer Auth event stays authoritative when the older logout fails',async({page})=>{
 await mount(page);await page.evaluate(()=>globalThis.beginLogout());await page.waitForFunction(()=>globalThis.probeFacts().events.length===1);await page.evaluate(()=>{globalThis.changeActor();globalThis.emitSignedOut();});await page.waitForFunction(()=>globalThis.probeFacts().status==='signed-out');await page.evaluate(()=>globalThis.finishLogout('failure'));await page.evaluate(()=>new Promise(requestAnimationFrame));const facts=await page.evaluate(()=>globalThis.probeFacts());expect(facts.status).toBe('signed-out');expect(facts.enabled).toBe(false);expect(facts.command).toBeNull();expect(facts.draft).toBeNull();
});
