import{test,expect}from'@playwright/test';import{build}from'esbuild';import{readFileSync}from'node:fs';import{resolve}from'node:path';
const root=resolve(import.meta.dirname,'../..');
test('canonical Student task-edge artwork is contained after image decode across mobile and tablet boundaries',async({page})=>{
 const errors:string[]=[];page.on('pageerror',()=>errors.push('pageerror'));const bundled=await build({stdin:{resolveDir:root,loader:'tsx',contents:`
import React,{useState}from'react';import{createRoot}from'react-dom/client';import{StudentTrailView}from'./apps/web/features/home/components/student-trail';import{trailAssets}from'./apps/web/shared/characters/assets';function Harness(){const[locale,setLocale]=useState('en'),[visible,setVisible]=useState(true);globalThis.studentSceneLocale=value=>setLocale(value);const context={displayName:'Lina Al-Kuwari',schoolName:'Current school',availability:'ready',goal:null,task:{title:locale==='ar'?'اشرح خطوة التحقق':'Explain the checking step',description:locale==='ar'?'راجع المثال المدرسي ثم اشرح خطوتك.':'Review the school example and explain your step.',course:'School checking journey',unit:null,state:'available',primaryAction:{label:locale==='ar'?'فتح المهمة':'Open task',onClick(){}}},stages:[],feedback:null,upcoming:null,recognition:{status:'unavailable',totalPoints:null,periodLabel:null,entries:[],currentMilestone:null},classChallenge:null,help:null,companion:{visible,name:'Foxi',hideAction:{label:visible?'Hide character':'Show character',onClick:()=>setVisible(x=>!x)}}};return<div className='workspace'><StudentTrailView context={context} assets={trailAssets} locale={locale}/></div>}createRoot(document.getElementById('root')).render(<Harness/>);
`},bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',plugins:[{name:'canonical-art-bytes',setup(b){b.onLoad({filter:/\.(webp|png|svg)$/},a=>({loader:'js',contents:'export default '+JSON.stringify({src:'data:image/'+(a.path.endsWith('.svg')?'svg+xml':'webp')+';base64,'+readFileSync(a.path).toString('base64'),width:128,height:128})}));}}]});const css=['packages/ui/src/tokens.css','apps/web/app/globals.css','apps/web/features/home/student-desk.css'].map(file=>readFileSync(resolve(root,file),'utf8')).join('\n');await page.setContent('<html lang="en"><head><title>Canonical Student scene verification</title><style>'+css+'</style></head><body><div id="root"></div></body></html>');await page.addScriptTag({content:bundled.outputFiles[0].text});
 for(const width of[320,390,540,541,767,768,1101])for(const locale of['en','ar']){await page.setViewportSize({width,height:1024});await page.evaluate(value=>(globalThis as unknown as{studentSceneLocale:(locale:string)=>void}).studentSceneLocale(value),locale);await expect(page.locator('.student-trail')).toHaveAttribute('dir',locale==='ar'?'rtl':'ltr');await page.locator('.student-trail__task-art img').evaluateAll(images=>Promise.all(images.map(image=>(image as HTMLImageElement).decode())));const geometry=await page.locator('.student-trail').evaluate(root=>{const scene=root.querySelector('.student-trail__task-art')!.getBoundingClientRect(),intro=root.querySelector('.student-trail__intro')!.getBoundingClientRect(),task=root.querySelector('.student-trail__task')!.getBoundingClientRect(),art=[...root.querySelectorAll('.student-trail__work-subject,.student-trail__foxi-crop')].map(e=>e.getBoundingClientRect()),overlap=(a:DOMRect,b:DOMRect)=>a.left<b.right-1&&a.right>b.left+1&&a.top<b.bottom-1&&a.bottom>b.top+1;return{fits:art.every(a=>a.top>=scene.top-1&&a.bottom<=scene.bottom+1&&a.left>=scene.left-1&&a.right<=scene.right+1),clearIntro:art.every(a=>!overlap(a,intro)),clearTask:art.every(a=>!overlap(a,task)),taskFirst:root.querySelector('.student-trail__task')!.compareDocumentPosition(root.querySelector('.student-trail__task-art')!)===Node.DOCUMENT_POSITION_FOLLOWING,pageFits:document.documentElement.scrollWidth<=innerWidth+1,foxi:root.querySelectorAll('.student-trail__foxi').length,pedestal:root.querySelectorAll('.student-trail__pedestal').length,images:[...root.querySelectorAll<HTMLImageElement>('.student-trail__task-art img')].every(i=>i.complete&&i.naturalWidth>0)};});expect(geometry,locale+'/'+width).toEqual({fits:true,clearIntro:true,clearTask:true,taskFirst:true,pageFits:true,foxi:1,pedestal:1,images:true});}
 await page.getByRole('button',{name:'Hide character',exact:true}).click();await expect(page.locator('.student-trail__task-art')).toBeHidden();await expect(page.locator('.student-trail__task h2')).not.toBeEmpty();expect(errors).toEqual([]);
});
