'use client';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@cuevo/ui';
import type { SubmissionArtifact } from '@cuevo/contracts';
import { useApp } from '../../../shared/session/providers';
import { LearningError } from '../../../shared/components/feedback';
import { LearningApiError } from '../../../shared/api/client';
export function PortfolioArtifactDownload({itemId,revisionId,asset,onReviewed}:{itemId:string;revisionId:string;asset:SubmissionArtifact;onReviewed?:()=>void}){const{membership,locale,apiUrl,accessToken,online,accessGeneration}=useApp();const[error,setError]=useState<LearningApiError|null>(null);const path=`/v1/portfolio/items/${itemId}/revisions/${revisionId}/artifacts/${asset.id}/download`;const scope=`${membership?.schoolId}:${membership?.userId}:${accessToken??''}:${online}:${accessGeneration}:${path}`;const current=useRef(scope);current.current=scope;const controller=useRef<AbortController|null>(null);const mounted=useRef(false);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);useEffect(()=>()=>controller.current?.abort(),[scope]);async function download(){if(!membership||!accessToken||!online)return;const expected=scope;const active=new AbortController();controller.current?.abort();controller.current=active;try{const response=await fetch(apiUrl+path,{headers:{Authorization:`Bearer ${accessToken}`,'X-School-Id':membership.schoolId},cache:'no-store',credentials:'omit',signal:AbortSignal.any([active.signal,AbortSignal.timeout(15000)])});if(!response.ok)throw new LearningApiError(response.status===403?'denied':'unavailable');const bytes=await response.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');if(bytes.byteLength!==asset.byteSize||hash!==asset.sha256)throw new LearningApiError('invalid');if(!mounted.current||active.signal.aborted||current.current!==expected)return;const url=URL.createObjectURL(new Blob([bytes],{type:asset.contentType}));const anchor=document.createElement('a');anchor.href=url;anchor.download=asset.name;anchor.click();onReviewed?.();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(failure){if(mounted.current&&!active.signal.aborted&&current.current===expected)setError(failure instanceof LearningApiError?failure:new LearningApiError('unavailable'));}}return <div><bdi>{asset.name}</bdi>{asset.state==='AVAILABLE'?<Button type="button" variant="quiet" onClick={()=>void download()}>{locale==='ar'?'تنزيل العمل المختار':'Download selected work document'}</Button>:<p>{locale==='ar'?'المستند غير متاح':'Document unavailable'}</p>}{error?<LearningError error={error}/>:null}</div>;}

