'use client';
import {useEffect,useRef,useState} from 'react';
import {Button,CuevoIcon,Status} from '@cuevo/ui';
import {useApp} from '../../../shared/session/providers';
import {NativeResultView,EvidenceDetail} from '../../academic/ui';
import {PortfolioSourceWork} from './source-work';
import {currentParentPortfolioSelection,parentPortfolioChoices,parentPortfolioSelection,parentPortfolioSourceWorkAvailable,type ParentPortfolioSelection} from '../parent-reading-model';
import type {PortfolioItem} from '../model';
import {portfolioAr,portfolioEn,portfolioTrailAr,portfolioTrailEn,parentPortfolioAr,parentPortfolioEn} from '../messages';
export function ParentPortfolioReading({items,childId,current}:{items:PortfolioItem[];childId:string|null;current:boolean}){
 const{locale,membership,accessGeneration}=useApp(),t=locale==='ar'?portfolioAr:portfolioEn,trail=locale==='ar'?portfolioTrailAr:portfolioTrailEn,p=locale==='ar'?parentPortfolioAr:parentPortfolioEn;
 const[selection,setSelection]=useState<ParentPortfolioSelection|null>(null),[work,setWork]=useState(false),[evidence,setEvidence]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null),focusDetail=useRef(false),directory=useRef<HTMLHeadingElement>(null);
 const choices=parentPortfolioChoices(items,locale,t.unknownSource,t.revision),selected=currentParentPortfolioSelection(selection,childId,items,current);
 useEffect(()=>{setWork(false);setEvidence(false);},[childId,selection?.revisionId,accessGeneration]);
 useEffect(()=>{if(focusDetail.current&&selected&&heading.current){focusDetail.current=false;heading.current.focus({preventScroll:true});heading.current.scrollIntoView({block:'start',behavior:'instant'});}},[selected]);
 const date=(value:string)=>new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(value));
 function choose(item:PortfolioItem){setWork(false);setEvidence(false);focusDetail.current=true;setSelection(parentPortfolioSelection(item));}
 return <section className='parent-portfolio-reading'><div className='parent-portfolio-directory'><h3 ref={directory} tabIndex={-1}>{p.directory}</h3>{choices.some(choice=>choice.requiresReview)?<p className='notice'>{p.matching}</p>:null}<ul>{items.map(item=>{const choice=choices.find(choice=>choice.value===item.id)!;return<li key={item.id}><div><h4>{item.title}</h4><p>{choice.label}</p></div><Button type='button' variant={selected?.id===item.id?'primary':'secondary'} disabled={!current||choice.requiresReview} onClick={()=>choose(item)}>{p.open}</Button></li>;})}</ul></div>
 {selection&&!selected&&current?<p className='notice' role='status'>{p.changed}</p>:null}
 {selected?<article className='parent-portfolio-item' data-parent-portfolio-id={selected.id}><header className='portfolio-item-heading'><CuevoIcon name='portfolio' size={28}/><div><h2 ref={heading} tabIndex={-1}>{selected.title}</h2><p><bdi>{selected.identity.learnerName??t.unknownLearner}</bdi> · {selected.identity.className??t.unknownSource}</p></div><Status tone='positive'>{t.reviewed}</Status><Button type='button' variant='quiet' onClick={()=>{setSelection(null);setWork(false);setEvidence(false);directory.current?.focus({preventScroll:true});}}>{p.close}</Button></header>
 <div className='parent-portfolio-layout'><div className='parent-portfolio-main'><section className='parent-portfolio-feedback'><h3><CuevoIcon name='feedback' size={25}/>{trail.feedbackHeading}</h3>{selected.feedback?<blockquote><p dir='auto'>{selected.feedback}</p></blockquote>:<p>{trail.noFeedback}</p>}{selected.reviewedAt?<p className='portfolio-help'>{trail.reviewedOn}: <time dateTime={selected.reviewedAt}>{date(selected.reviewedAt)} · UTC</time></p>:null}<p className='portfolio-help'>{p.teacherUnavailable}</p></section><section className='parent-portfolio-reflection'><h3><CuevoIcon name='reflection' size={25}/>{trail.approvedReflection}</h3><p className='portfolio-revision-label'>{t.revision}: {new Intl.NumberFormat(locale).format(selected.revision)}</p><div className='portfolio-reflection-text'><p dir='auto'>{selected.reflection}</p></div></section><section className='parent-portfolio-selected-work'><h3><CuevoIcon name='learning' size={25}/>{trail.selectedHeading}</h3>{parentPortfolioSourceWorkAvailable(selected)?<Button type='button' variant='secondary' data-portfolio-focus={selected.id} aria-expanded={work} onClick={()=>setWork(value=>!value)}>{selected.responseKind==='FILE'?p.fileWork:t.sourceWork}</Button>:<p className='notice'>{p.sourceUnavailable}</p>}</section>{work&&parentPortfolioSourceWorkAvailable(selected)?<PortfolioSourceWork key={selected.revisionId} item={selected} onSaved={()=>undefined} onCancel={()=>setWork(false)} reviewing={false}/>:null}</div>
 <aside className='parent-portfolio-context'><h3>{p.about}</h3><dl className='portfolio-context-list'>{[[p.child,selected.identity.learnerName??t.unknownLearner],[trail.schoolContext,membership?.school.name??t.unknownSource],[p.course,selected.identity.courseTitle??t.unknownSource],[p.assessment,selected.identity.assessmentTitle??selected.assessmentTitle],[p.class,[selected.identity.className,selected.identity.yearGroupName,selected.identity.academicYearName].filter(Boolean).join(' · ')||t.unknownSource]].map(([label,value])=><div key={label}><dt>{label}</dt><dd><bdi>{value}</bdi></dd></div>)}</dl>{selected.identity.submittedAt?<p>{t.submittedOn}: <time dateTime={selected.identity.submittedAt}>{date(selected.identity.submittedAt)} · UTC</time></p>:null}<NativeResultView result={selected.nativeResult}/>{selected.identity.status!=='READY'?<p className='notice'>{t.identityUnknown}</p>:null}<Button type='button' variant='quiet' aria-expanded={evidence} onClick={()=>setEvidence(value=>!value)}>{t.source}</Button>{evidence?<EvidenceDetail key={`${selected.evidenceId}:${accessGeneration}`} evidenceId={selected.evidenceId}/>:null}</aside></div></article>:<p className='notice'>{p.choose}</p>}
 </section>;
}
