import { LearningApiError } from './learning-api.ts';

export type AcademicStateRow = { resultId: string; referenceId: string; referenceVersion: string; nativeResult: { type: 'numeric'; score: number; maxScore: number; policyVersion: number; normalized: null }; evidenceId: string; observedAt: string };
export type LearnerState = { learnerId: string; status: 'READY' | 'UNKNOWN'; freshness?: 'CURRENT' | 'STALE' | 'APPROVED_PROJECTION'; generatedAt: string | null; version: number | null; academic: AcademicStateRow[]; development: { practice: { count: number | null; observationIds: string[] }; revision: { count: number | null; observationIds: string[] }; reflection: { count: number | null; observationIds: string[] }; windowStart: string | null; windowEnd: string | null; completeness?: 'RECORDED_ONLY' }; engagement: { completedActivityCount: number | null; lastCompletedAt: string | null }; support: { activeInterventionIds: string[] }; impact: { status: 'unmeasured'; measurementIds: string[] }; sourceEventIds: string[] };
export type Observation = { id: string; learnerId: string; kind: 'practice' | 'revision' | 'reflection'; sourceType: string; sourceObjectId: string; occurredAt: string; sourceEventId: string };
export type Signal = { id: string; learnerId: string; type: 'practice_observed'; count: number; ruleVersion: number; createdAt: string; windowStart: string; windowEnd: string; sourceEventIds: string[]; observationIds: string[]; status: 'ACTIVE'; uncertainty: 'OBSERVATION_ONLY' };
function object(value: unknown): value is Record<string, unknown> { return !!value && typeof value === 'object' && !Array.isArray(value); }
function strings(value: Record<string, unknown>, keys: string[]) { return keys.every((key) => typeof value[key] === 'string' && value[key] !== ''); }
function ids(value: unknown): value is string[] { return Array.isArray(value) && value.every((id) => typeof id === 'string' && id !== ''); }
function date(value: unknown, nullable = false) { return nullable && value === null || typeof value === 'string' && Number.isFinite(Date.parse(value)); }
function count(value: unknown) { return value === null || typeof value === 'number' && Number.isInteger(value) && value >= 0; }
export function parseLearnerState(value: unknown): LearnerState {
  if (!object(value) || !strings(value, ['learnerId']) || !['READY', 'UNKNOWN'].includes(String(value.status)) || !date(value.generatedAt, true) || !(value.version === null || typeof value.version === 'number' && Number.isInteger(value.version) && value.version > 0) || !Array.isArray(value.academic) || !ids(value.sourceEventIds) || !object(value.development) || !object(value.engagement) || !object(value.support) || !object(value.impact)) throw new LearningApiError('invalid');
  for (const row of value.academic) {
    if (!object(row) || !strings(row, ['resultId', 'referenceId', 'referenceVersion', 'evidenceId']) || !date(row.observedAt) || !object(row.nativeResult) || row.nativeResult.type !== 'numeric' || typeof row.nativeResult.score !== 'number' || typeof row.nativeResult.maxScore !== 'number' || !Number.isFinite(row.nativeResult.score) || !Number.isFinite(row.nativeResult.maxScore) || row.nativeResult.maxScore <= 0 || row.nativeResult.score < 0 || row.nativeResult.score > row.nativeResult.maxScore || typeof row.nativeResult.policyVersion !== 'number' || !Number.isInteger(row.nativeResult.policyVersion) || row.nativeResult.policyVersion < 1 || row.nativeResult.normalized !== null) throw new LearningApiError('invalid');
  }
  for (const kind of ['practice', 'revision', 'reflection']) {
    const dimension = value.development[kind];
    if (!object(dimension) || !count(dimension.count) || !ids(dimension.observationIds)) throw new LearningApiError('invalid');
  }
  if (!date(value.development.windowStart, true) || !date(value.development.windowEnd, true) || !count(value.engagement.completedActivityCount) || !date(value.engagement.lastCompletedAt, true) || !ids(value.support.activeInterventionIds) || value.impact.status !== 'unmeasured' || !ids(value.impact.measurementIds)) throw new LearningApiError('invalid');
  if (value.freshness !== undefined && !['CURRENT', 'STALE', 'APPROVED_PROJECTION'].includes(String(value.freshness)) || value.development.completeness !== undefined && value.development.completeness !== 'RECORDED_ONLY') throw new LearningApiError('invalid');
  if (value.status === 'UNKNOWN' && (value.generatedAt !== null || value.version !== null || value.academic.length || value.sourceEventIds.length || value.engagement.completedActivityCount !== null || ['practice', 'revision', 'reflection'].some((kind) => (value.development as Record<string, Record<string, unknown>>)[kind].count !== null))) throw new LearningApiError('invalid');
  return value as LearnerState;
}
export function parseObservation(value: unknown): Observation { if (!object(value) || !strings(value, ['id', 'learnerId', 'sourceObjectId', 'sourceEventId']) || !['practice', 'reflection'].includes(String(value.kind)) || value.sourceType !== 'ACTIVITY_COMPLETION' || !date(value.occurredAt)) throw new LearningApiError('invalid'); return value as Observation; }
export function parseSignal(value: unknown): Signal { if (!object(value) || !strings(value, ['id', 'learnerId']) || typeof value.ruleVersion !== 'number' || !Number.isInteger(value.ruleVersion) || value.ruleVersion < 1 || value.type !== 'practice_observed' || typeof value.count !== 'number' || !count(value.count) || !date(value.createdAt) || !date(value.windowStart) || !date(value.windowEnd) || !ids(value.sourceEventIds) || !ids(value.observationIds) || value.status !== 'ACTIVE' || value.uncertainty !== 'OBSERVATION_ONLY') throw new LearningApiError('invalid'); return value as Signal; }
