'use client';
import'../demo-guide.css';
import{quickLoginSession}from'../../auth/model';
import{demoRevealScroll}from'../demo-guide-scroll';
import{DemoPersonalization}from'./demo-personalization';
import{DemoLearningPillars,type DemoPillarScene}from'./demo-learning-pillars';
import{createPortal}from'react-dom';
import{useEffect,useRef,useState}from'react';import{Button,CuevoIcon}from'@cuevo/ui';import{useApp}from'../../../shared/session/providers';import{parseDemoGuideManifest,type DemoGuideManifest}from'../../../shared/session/demo-guide';import{canOpenWorkspace}from'../../../shared/session/capabilities';import{navigationParameters}from'../../../shared/session/navigation-intent';import{getProductDemoSteps,type DemoGuideStep}from'../demo-guide-model';
type Story={manifest:DemoGuideManifest;index:number};
const pillarScenes:readonly DemoPillarScene[]=['learning-loop','rubric','self-regulation','institution','signals'];
const pillarScene=(target:string|undefined):DemoPillarScene|null=>pillarScenes.includes(target as DemoPillarScene)?target as DemoPillarScene:null;
const visible=(el:Element)=>el.getClientRects().length>0;
const clickable=(el:Element):el is HTMLButtonElement=>el instanceof HTMLButtonElement&&!el.disabled&&visible(el);
function exactButton(root:ParentNode,names:string[]){const choices=Array.from(root.querySelectorAll('button')).filter(el=>clickable(el)&&names.includes(el.textContent?.trim()??''));if(choices.length!==1)return false;choices[0].click();return true;}
function readSection(name:string){const button=document.querySelector(`[data-workspace-sections] [data-workspace-section="${name}"]`);if(button&&clickable(button)&&button.getAttribute('aria-pressed')!=='true'){button.click();return true;}return false;}
/** Only known reading controls are used. No save, submission or approval is clicked. */
export function revealDemoScene(step:DemoGuideStep,manifest:DemoGuideManifest):Element|null{
 const r=manifest.records,main=document.querySelector('main');if(!main)return null;
 if(step.target==='home')return main;
 if(step.target==='learning'||step.target==='task-focus'){
  const journey=main.querySelector(`.student-learning-journey[data-lesson-id="${r.lessonId}"]`);if(!journey){const lesson=main.querySelector(`[data-lesson-choice="${r.lessonId}"]`);if(lesson&&clickable(lesson))lesson.click();return null;}
  if(step.target==='task-focus'){const choice=journey.querySelector(`[data-activity-choice="${r.activityId}"]`);if(!choice||!clickable(choice)){const chooser=journey.querySelector('.student-learning-journey__change-step');if(chooser&&clickable(chooser)&&chooser.getAttribute('aria-expanded')!=='true')chooser.click();return null;}if(choice.getAttribute('aria-current')!=='step'){choice.click();return null;}return journey.querySelector('.student-learning-journey__thinking');}return journey;
 }
 if(step.target==='baseline'||step.target==='followup')return main.querySelector(`[data-result-id="${step.target==='baseline'?r.baselineResultId:r.followupResultId}"]`);
 if(step.target==='teacher-review'){const reader=main.querySelector('.marking-workbench');return reader&&!reader.querySelector('[data-state="loading"],[role="alert"]')?reader:null;}
 if(step.target==='objective'){const reader=main.querySelector('.marking-workbench__context');return reader?.querySelector('.marking-objective-description')&&!reader.querySelector('[data-state="loading"],[role="alert"]')?reader:null;}
 if(step.target==='personalization')return main.querySelector('[data-presentation-personalization][data-personalization-state="ready"]');
 if(['learning-loop','rubric','self-regulation','institution','signals'].includes(step.target))return main.querySelector(`[data-presentation-pillars="${step.target}"]`);
 if(step.target==='habits'){const reader=main.querySelector('#progress-observations'),details=reader?.closest('details');if(details&&!details.open)details.open=true;return reader&&!reader.querySelector('[data-state="loading"],[role="alert"]')&&reader.querySelector('article')?reader:null;}
 if(step.target==='agentic-proposal'||step.target==='agentic-context'){
  if(!r.agenticProposalId)return null;if(readSection('proposals'))return null;const selected=main.querySelector(`.proposal-selected [data-recommendation-id="${r.agenticProposalId}"]`);
  if(!selected){const choice=main.querySelector(`[data-proposal-choice="${r.agenticProposalId}"]`);if(choice&&clickable(choice))choice.click();return null;}
  if(step.target==='agentic-context'){const context=selected.querySelector('.insight-context');if(context&&visible(context))return context;const buttons=Array.from(selected.querySelectorAll('button')).filter(button=>['Show analysis source context','عرض سياق مصادر التحليل'].includes(button.textContent?.trim()??''));if(buttons.length===1&&clickable(buttons[0])&&buttons[0].getAttribute('aria-expanded')!=='true')buttons[0].click();return null;}return selected;
 }
 if(step.target==='agentic-practice')return r.agenticPracticeId?main.querySelector(`[data-intervention-id="${r.agenticPracticeId}"]`):null;
 if(step.target==='proposal'){if(readSection('proposals'))return null;const selected=main.querySelector(`.proposal-selected [data-recommendation-id="${r.proposalId}"]`);if(selected)return selected;const choice=main.querySelector(`[data-proposal-choice="${r.proposalId}"]`);if(choice&&clickable(choice))choice.click();return null;}
 if(step.target==='practice'){const selected=main.querySelector(`[data-intervention-id="${r.measuredPracticeId}"]`);if(selected){exactButton(selected,['Open this practice','فتح هذا التدريب']);return selected;}return null;}
 if(step.target==='outcome'){if(readSection('outcomes'))return null;const item=main.querySelector(`[data-outcome-id="${r.outcomeId}"]`);if(item){const disclosure=item.closest('details');if(disclosure&&!disclosure.open)disclosure.open=true;return item;}const record=Array.from(main.querySelectorAll('.coordinator-outcome-directory li')).find(el=>el.textContent?.includes('Practise a checking step'));if(record)exactButton(record,['Read measured outcome','قراءة النتيجة المقاسة']);return null;}
 if(step.target==='portfolio'){const selected=main.querySelector(`[data-portfolio-id="${r.portfolioId}"],[data-parent-portfolio-id="${r.portfolioId}"]`);if(selected)return selected;const choices=Array.from(main.querySelectorAll('button')).filter(el=>el.textContent?.includes('How I checked my work')&&clickable(el));if(choices.length===1){choices[0].click();return null;}const cards=Array.from(main.querySelectorAll('article,li')).filter(el=>el.querySelector('h2,h3')?.textContent==='How I checked my work');if(cards.length===1)exactButton(cards[0],['Open approved item','فتح العمل المعتمد','Open this work','فتح هذا العمل']);return null;}
 if(step.target==='development'){const select=Array.from(main.querySelectorAll('select')).find(el=>Array.from(el.options).some(opt=>opt.value===r.periodId));if(select&&!select.disabled&&select.value!==r.periodId){Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value')?.set?.call(select,r.periodId);select.dispatchEvent(new Event('change',{bubbles:true}));return null;}if(!select||select.value!==r.periodId||main.querySelector('[data-state="loading"]'))return null;return main.querySelector('.development-ledger,.development-progress-ledger');}
 if(step.target==='discussion'){const card=main.querySelector(`[data-room-id="${r.roomId}"]`);if(card){exactButton(card,['Open discussion','فتح النقاش']);return null;}const reader=main.querySelector('.community-discussion');return main.querySelector('h1')?.textContent==='Checking ideas - class discussion'&&reader&&!reader.querySelector('[data-state="loading"],[data-state="error"],[role="alert"]')&&reader.querySelector('.community-post')?reader:null;}
 if(step.target==='progress')return main.querySelector('.progress-workspace')??main;
 if(step.target==='notifications')return main.querySelector('.community-workspace');
 if(step.target==='school')return main.querySelector('.school-workspace')??main;
 return main;
}
export function DemoGuide({onBusy,onOpen}:{onBusy:(value:boolean)=>void;onOpen:(value:boolean)=>void}){
 const app=useApp(),latest=useRef(app),[available,setAvailable]=useState<DemoGuideManifest|null>(null),[story,setStory]=useState<Story|null>(null),[pending,setPending]=useState(false),[error,setError]=useState(''),[located,setLocated]=useState(false),[presentationHost,setPresentationHost]=useState<HTMLElement|null>(null),outline=useRef<Element|null>(null),panel=useRef<HTMLElement|null>(null),busy=useRef(false),generation=useRef(0);latest.current=app;
 const ar=app.locale==='ar',steps=story?getProductDemoSteps(app.locale,story.manifest):[],step=story?steps[story.index]:null;
 const presentationPermitted=!!story&&!!step&&app.status==='ready'&&app.online&&app.membership?.schoolId===story.manifest.schoolId&&app.membership?.userId===story.manifest.actors[step.role]&&app.membership?.role===step.role&&canOpenWorkspace(step.view,app.membership.entitlements,app.membership.role);
 const clear=()=>{outline.current?.removeAttribute('data-demo-highlight');outline.current=null;};
 useEffect(()=>{onOpen(!!story);return()=>onOpen(false);},[!!story,onOpen]);
 useEffect(()=>{const content=document.querySelector<HTMLElement>('[data-demo-content]'),guide=panel.current;if(!story||!content||!guide)return;const measure=()=>content.style.setProperty('--demo-guide-clearance',Math.ceil(innerHeight-guide.getBoundingClientRect().top+24)+'px');measure();const observer=new ResizeObserver(measure);observer.observe(guide);window.addEventListener('resize',measure);return()=>{observer.disconnect();window.removeEventListener('resize',measure);content.style.removeProperty('--demo-guide-clearance');};},[!!story]);
 useEffect(()=>{const host=presentationPermitted&&(step?.target==='personalization'||pillarScene(step?.target))?document.querySelector('main'):null;setPresentationHost(host);host?.setAttribute('data-demo-presentation-host','');return()=>host?.removeAttribute('data-demo-presentation-host');},[step?.key,presentationPermitted,app.accessGeneration]);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/testing/quick-login',{cache:'no-store',signal:controller.signal}).then(r=>r.json()).then(v=>{if(v.available===true){const manifest=parseDemoGuideManifest(v.guide);if(manifest)setAvailable(manifest);}}).catch(()=>{});return()=>controller.abort();},[]);
 useEffect(()=>{if(!story||!step||app.status!=='ready'||app.membership?.role!==step.role||app.membership.schoolId!==story.manifest.schoolId||app.membership.userId!==story.manifest.actors[step.role])return;if(!canOpenWorkspace(step.view,app.membership.entitlements,app.membership.role)){setError(ar?'لا تتيح الصلاحيات الحالية هذا المشهد.':'Current access does not permit this scene.');return;}
  const params=step.intent?navigationParameters(step.intent):new URLSearchParams(step.view==='overview'?{}:{view:step.view});window.history.pushState(null,'',location.pathname+(params.size?'?'+params:''));setLocated(false);clear();let count=0;
  const timer=setInterval(()=>{if(latest.current.status!=='ready'||latest.current.membership?.userId!==story.manifest.actors[step.role])return;const target=revealDemoScene(step,story.manifest);if(target&&visible(target)){target.setAttribute('data-demo-highlight','true');outline.current=target;const rect=target.getBoundingClientRect(),header=document.querySelector('.workspace-nav')?.getBoundingClientRect(),panelBox=panel.current?.getBoundingClientRect();const main=document.querySelector<HTMLElement>('main'),scroller=main&&['auto','scroll'].includes(getComputedStyle(main).overflowY)&&main.scrollHeight>main.clientHeight?main:null;const top=demoRevealScroll(rect,{height:innerHeight,scrollY:scroller?.scrollTop??scrollY,headerBottom:Math.max(header?.bottom??130,scroller?.getBoundingClientRect().top??0),panelTop:panelBox?.top??innerHeight});if(top!==null)(scroller??window).scrollTo({top,behavior:'instant'});setLocated(true);clearInterval(timer);}else if(++count>70){setError(ar?'تعذّر فتح المصدر الحالي. أعد المحاولة أو افتحه من مساحة العمل.':'The current source could not be opened. Retry or open it from the workspace.');clearInterval(timer);}},200);
  return()=>{clearInterval(timer);clear();};
 },[story,app.status,app.membership?.role,app.membership?.userId,app.membership?.schoolId,app.membership?.entitlements,app.accessGeneration,app.selectedChildId,app.locale]);
 async function go(index:number,manifest=story?.manifest??available){if(!manifest||busy.current)return;if(!app.online){setError(ar?'أعد الاتصال قبل فتح المشهد التالي.':'Reconnect before opening the next scene.');return;}const next=getProductDemoSteps(app.locale,manifest)[index];if(!next)return;const unsent=Array.from(document.querySelectorAll('main textarea,main input:not([type=checkbox]):not([type=radio])')).some(el=>el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement?el.value!==el.defaultValue&&el.value.trim()!=='':false);if(app.commandJournal.pending().length||app.formDrafts.hasWorkingInput()||unsent){setError(ar?'احفظ العمل غير المرسل أو ألغِه وأكمل الإجراء الجاري أولًا.':'Save or cancel unsent work and finish any pending action first.');return;}busy.current=true;setPending(true);setLocated(false);onBusy(true);document.querySelector('[data-demo-content]')?.setAttribute('inert','');setError('');clear();const run=++generation.current;
  try{if(app.membership?.role!==next.role||app.membership.schoolId!==manifest.schoolId||app.membership.userId!==manifest.actors[next.role]){if(!await app.signOut())throw Error('Signout unconfirmed');const response=await fetch('/api/testing/quick-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:next.role}),signal:AbortSignal.timeout(10000)});const session=quickLoginSession(await response.json(),next.role);if(run!==generation.current||latest.current.membership||latest.current.status!=='signed-out')throw Error('Session changed');if(!response.ok||!session||!await app.restoreSession(session))throw Error('Demo unavailable');}setStory({manifest,index});requestAnimationFrame(()=>panel.current?.focus({preventScroll:true}));}catch{setError(ar?'تعذّر فتح حساب العرض. أعد المحاولة.':'The demonstration account could not be opened. Please retry.');}finally{busy.current=false;setPending(false);onBusy(false);document.querySelector('[data-demo-content]')?.removeAttribute('inert');}}
 if(!available)return null;
 if(!story)return app.status==='ready'||error||pending?<aside className="demo-guide" data-demo-guide>{error?<p role="alert">{error}</p>:null}<Button type="button" disabled={pending} onClick={()=>void go(0)}><CuevoIcon name="learning" size={20}/>{error?(ar?'أعد المحاولة':'Retry'):(ar?'ابدأ عرض قصة كويفو':'Start product demo')}</Button></aside>:null;
 return <>{presentationHost&&presentationPermitted&&(step?.target==='personalization'||pillarScene(step?.target))?createPortal(step?.target==='personalization'?<DemoPersonalization key={generation.current} manifest={story.manifest}/>:<DemoLearningPillars key={step?.key} scene={pillarScene(step?.target)!} locale={app.locale}/>,presentationHost):null}<aside ref={panel} tabIndex={-1} lang={app.locale} dir={ar?'rtl':'ltr'} className="demo-guide demo-guide--open" aria-label={ar?'عرض قصة كويفو':'Cuevo product demonstration'} data-demo-guide>
  <div className="demo-guide__header"><small>{ar?'عرض قصة التعلّم ببيانات خيالية':'Fictional learning story'} · {story.index+1}/{steps.length}</small><Button type="button" variant="quiet" aria-label={ar?'إغلاق العرض':'Close demonstration'} disabled={pending} onClick={()=>{generation.current++;setStory(null);clear();}}>×</Button></div><h2>{step?.title}</h2><p>{step?.explain}</p><small role="status">{pending?(ar?'جارٍ فتح المشهد…':'Opening the next scene…'):located&&app.status==='ready'&&app.online?(ar?'المنطقة المحدّدة جاهزة للشرح.':'The highlighted area is ready to explain.'):(ar?'جارٍ العثور على المصدر الحالي…':'Locating the current source…')}</small>{error?<p role="alert">{error}</p>:null}<div className="demo-guide__actions"><Button type="button" variant="secondary" disabled={pending||story.index===0} onClick={()=>void go(story.index-1)}>{ar?'السابق':'Back'}</Button>{error?<Button type="button" variant="secondary" disabled={pending} onClick={()=>void go(story.index)}>{ar?'أعد المحاولة':'Retry'}</Button>:null}<Button type="button" disabled={pending||!located||app.status!=='ready'||!app.online} onClick={()=>story.index===steps.length-1?(setStory(null),clear()):void go(story.index+1)}>{story.index===steps.length-1?(ar?'إنهاء العرض':'Finish'):(ar?'المشهد التالي':'Next scene')}<CuevoIcon name="arrow" size={16}/></Button></div>
 </aside></>;
}
