import{z}from'zod';
export const automationPolicyIdSchema=z.enum(['LEARNER_STATE','ATTENTION','RECOGNITION','COMMUNICATION','INTELLIGENCE']);
export const automationFamilySchema=z.enum(['LEARNING_SOURCE','ACADEMIC_RELEASE','LEARNER_STATE','ATTENTION','RECOGNITION','COMMUNICATION']);
export const automationPolicySchema=z.object({id:automationPolicyIdSchema,version:z.number().int().positive().nullable(),configured:z.boolean(),enabled:z.boolean(),approvedBy:z.string().min(1).max(200).nullable(),approvedAt:z.iso.datetime({offset:true}).nullable(),conditions:z.object({windowDays:z.number().int().positive().max(365).nullable(),minimumDecline:z.number().positive().nullable(),maxScore:z.number().positive().nullable(),missingDueCount:z.number().int().positive().nullable(),practicePoints:z.number().int().nonnegative().nullable(),revisionPoints:z.number().int().nonnegative().nullable(),reflectionPoints:z.number().int().nonnegative().nullable(),parentCommunicationEnabled:z.boolean().nullable(),fixtureEnabled:z.boolean().nullable(),liveEnabled:z.boolean().nullable(),executionConfigured:z.boolean().nullable()}).strict()}).strict().refine(value=>value.configured?(value.version!==null):value.version===null&&!value.enabled,'Unconfigured policy cannot imply enabled automation.');
export const automationRunSchema=z.object({id:z.uuid(),family:automationFamilySchema,state:z.enum(['PENDING','PROCESSING','COMPLETED','FAILED']),attemptCount:z.number().int().nonnegative(),occurredAt:z.iso.datetime({offset:true}),completedAt:z.iso.datetime({offset:true}).nullable(),receiptRecorded:z.boolean(),error:z.enum(['REQUIRES_REVIEW','LEASE_EXHAUSTED','OTHER_FAILURE']).nullable()}).strict().refine(value=>value.receiptRecorded?value.state==='COMPLETED':true,'Processed receipt must match completed state.');
export const schoolAutomationSchema=z.object({windowStart:z.iso.datetime({offset:true}),windowEnd:z.iso.datetime({offset:true}),policies:z.array(automationPolicySchema).length(5),execution:z.object({scope:z.literal('RETURNED_ALLOWLIST_EVENTS_IN_WINDOW'),returned:z.number().int().nonnegative().max(2000),truncated:z.boolean(),pending:z.number().int().nonnegative(),processing:z.number().int().nonnegative(),completed:z.number().int().nonnegative(),failed:z.number().int().nonnegative(),retried:z.number().int().nonnegative(),receiptCount:z.number().int().nonnegative(),latestCompletionAt:z.iso.datetime({offset:true}).nullable(),runs:z.array(automationRunSchema).max(25)}).strict(),approvals:z.literal('EXISTING_HUMAN_APPROVALS_UNCHANGED')}).strict().superRefine((value,ctx)=>{const e=value.execution;if(e.pending+e.processing+e.completed+e.failed!==e.returned||e.retried>e.returned||e.receiptCount>e.completed||e.runs.length>e.returned||new Set(value.policies.map(policy=>policy.id)).size!==5||new Set(e.runs.map(run=>run.id)).size!==e.runs.length)ctx.addIssue({code:'custom',message:'Execution counts and policy identities must stay truthful.'});});
export type SchoolAutomation=z.infer<typeof schoolAutomationSchema>;


