import { z } from 'zod';
const title=z.string().trim().min(1).max(200);const reason=z.string().trim().min(1).max(1000);
export const learningContentResourceSchema=z.enum(['course','unit','lesson','activity']);
export const learningContentDraftSchema=z.object({resource:learningContentResourceSchema,expectedRevision:z.number().int().positive(),title,content:z.string().max(50000),kind:z.enum(['reading','practice','assignment','quiz','reflection']).nullable().default(null),assessmentId:z.uuid().nullable().default(null),reason}).strict().superRefine((value,ctx)=>{if(value.resource==='course'&&value.content.length>4000||value.resource==='unit'&&value.content!==''||value.resource!=='course'&&value.resource!=='unit'&&!value.content.trim()||value.resource==='activity'&&(value.content.length>10000||!value.kind||(value.kind==='assignment'||value.kind==='quiz')!==!!value.assessmentId)||value.resource!=='activity'&&(value.kind!==null||value.assessmentId!==null))ctx.addIssue({code:'custom',message:'Content kind and exact task must match the source.'});});
export const learningContentPublishSchema=z.object({expectedRevision:z.number().int().positive(),confirmPublication:z.literal(true)}).strict();
export const learningContentRetireSchema=z.object({expectedRevision:z.number().int().positive(),reason,confirmRetirement:z.literal(true)}).strict();
export const learningContentSchema=z.object({id:z.uuid(),courseId:z.uuid(),resource:learningContentResourceSchema,sourceId:z.uuid(),revision:z.number().int().positive(),title,content:z.string().max(50000),kind:z.enum(['reading','practice','assignment','quiz','reflection']).nullable(),assessmentId:z.uuid().nullable(),state:z.enum(['DRAFT','PUBLISHED','RETIRED']),createdAt:z.iso.datetime({offset:true}),publishedRevision:z.number().int().positive().nullable(),draftRevision:z.number().int().positive()}).strict();
export const learningContentQuerySchema=z.object({limit:z.coerce.number().int().min(1).max(25).default(25),cursor:z.uuid().optional()}).strict();
export type LearningContent=z.infer<typeof learningContentSchema>;export type LearningContentResource=z.infer<typeof learningContentResourceSchema>;

export const learningSourceContextSchema=z.object({sourceId:z.uuid(),contextStatus:z.enum(['AVAILABLE','UNKNOWN']),course:z.object({revisionId:z.uuid(),revision:z.number().int().positive(),title:z.string().min(1),content:z.string().max(4000)}).nullable(),lesson:z.object({revisionId:z.uuid(),revision:z.number().int().positive(),title:z.string().min(1),content:z.string().max(50000)}).nullable(),activity:z.object({revisionId:z.uuid(),revision:z.number().int().positive(),title:z.string().min(1),content:z.string().max(10000),kind:z.enum(['reading','practice','assignment','quiz','reflection'])}).nullable(),assessment:z.object({title:z.string().min(1),instructions:z.string().max(10000),preparationVersion:z.number().int().positive(),policyVersion:z.number().int().positive()}).nullable()}).strict().refine(value=>value.contextStatus==='AVAILABLE'?value.course!==null:value.course===null&&value.lesson===null&&value.activity===null&&value.assessment===null,'Unknown past content must remain explicit.');



