import{z}from'zod';
const reason=z.string().trim().min(1).max(1000);const title=z.string().trim().min(1).max(200);const note=z.string().trim().min(1).max(4000);
export const restrictedPolicySchema=z.object({enabled:z.boolean(),expectedVersion:z.number().int().nonnegative(),purpose:z.literal('BASIC_INCIDENT_NOTE'),sourceBasis:z.literal('SCHOOL_AUTHORED'),retentionStatus:z.literal('SYNTHETIC_ONLY'),retentionNote:reason,ownerId:z.uuid(),reason,confirmApproval:z.literal(true)}).strict();
export const restrictedRecordCreateSchema=z.object({courseId:z.uuid(),learnerId:z.uuid(),occurredAt:z.iso.datetime({offset:true}),title,note,confirmFactualRecord:z.literal(true)}).strict();
export const restrictedRecordCorrectionSchema=z.object({expectedRevision:z.number().int().positive(),title,note,reason,confirmCorrection:z.literal(true)}).strict();
export const restrictedFollowUpApprovalSchema=z.object({expectedRevision:z.number().int().positive(),followUpOwnerId:z.uuid(),instructions:note,reason,confirmApproval:z.literal(true)}).strict();
export const restrictedFollowUpSchema=z.object({expectedRevision:z.number().int().positive(),status:z.enum(['IN_PROGRESS','COMPLETED']),note,confirmManualAction:z.literal(true)}).strict();
export const restrictedRecordQuerySchema=z.object({limit:z.coerce.number().int().min(1).max(25).default(25),cursor:z.uuid().optional()}).strict();
export const restrictedPolicyResponseSchema=z.object({id:z.uuid(),version:z.number().int().nonnegative(),enabled:z.boolean(),purpose:z.literal('BASIC_INCIDENT_NOTE'),retentionStatus:z.literal('SYNTHETIC_ONLY'),ownerId:z.uuid().nullable(),retentionNote:z.string().max(1000).nullable()}).strict();
export const restrictedRecordResponseSchema=z.object({id:z.uuid(),courseId:z.uuid(),learnerId:z.uuid(),title,note,occurredAt:z.iso.datetime({offset:true}),revision:z.number().int().positive(),authorId:z.uuid(),authorName:title,learnerName:title,courseTitle:title,className:title,state:z.enum(['AWAITING_REVIEW','APPROVED_FOLLOW_UP','IN_PROGRESS','COMPLETED']),followUpOwnerId:z.uuid().nullable(),followUpOwnerName:title.nullable(),followUpInstructions:note.nullable(),followUpNote:note.nullable(),retentionStatus:z.literal('SYNTHETIC_ONLY')}).strict();
export type RestrictedRecord=z.infer<typeof restrictedRecordResponseSchema>;

export const restrictedHistorySchema=z.object({items:z.array(z.object({id:z.uuid(),revision:z.number().int().positive(),title,note,state:z.enum(['AWAITING_REVIEW','APPROVED_FOLLOW_UP','IN_PROGRESS','COMPLETED']),reason,createdAt:z.iso.datetime({offset:true}),actorName:title.optional(),policyId:z.uuid().optional(),policyVersion:z.number().int().positive().optional(),followUpOwnerName:title.nullable().optional(),followUpInstructions:note.nullable().optional(),followUpNote:note.nullable().optional()}).strict()).max(25),nextCursor:z.uuid().nullable()}).strict();
