import assert from 'node:assert/strict';
import test from 'node:test';
import {registerHooks} from 'node:module';
import React,{createElement}from'react';
import {renderToStaticMarkup}from'react-dom/server';
import{CommandJournal}from'../../../shared/api/client.ts';
import{FormDrafts}from'../../../shared/session/form-drafts.ts';
import{commonEn}from'../../../shared/i18n/common.ts';
const id=(value:number)=>`c5000000-0000-4000-8000-${String(value).padStart(12,'0')}`;
const policy={id:id(1),version:1,enabled:true,purpose:'BASIC_INCIDENT_NOTE',retentionStatus:'SYNTHETIC_ONLY',ownerId:id(2),retentionNote:'Reviewed synthetic retention'};
const record={id:id(3),courseId:id(4),learnerId:id(5),title:'Check the classroom account',note:'Full private factual context belongs only in the selected reader.',occurredAt:'2026-10-05T10:00:00Z',revision:1,authorId:id(2),authorName:'Maya Reed',learnerName:'Alex Taylor',courseTitle:'School reasoning',className:'Cedar',state:'AWAITING_REVIEW',followUpOwnerId:null,followUpOwnerName:null,followUpInstructions:null,followUpNote:null,retentionStatus:'SYNTHETIC_ONLY'};
const fixture={app:{}as Record<string,unknown>,policy,record};Object.assign(globalThis,{React,restrictedFocusedFixture:fixture,restrictedFocusedCommon:commonEn});
registerHooks({load(url,context,nextLoad){const path=url.replaceAll('\\','/');if(path.endsWith('/shared/session/providers.tsx'))return{format:'module',shortCircuit:true,source:'export function useApp(){return globalThis.restrictedFocusedFixture.app}'};if(path.endsWith('/shared/hooks/use-api.ts'))return{format:'module',shortCircuit:true,source:'export function useApi(){return {t:globalThis.restrictedFocusedCommon,journal:globalThis.restrictedFocusedFixture.app.commandJournal}};export function useApiQuery(path,parse){const f=globalThis.restrictedFocusedFixture;return {data:path?.endsWith("/policy")?parse(f.policy):null,loading:false,error:null}}'};if(path.endsWith('/shared/hooks/use-paginated-query.ts'))return{format:'module',shortCircuit:true,source:'export function usePaginatedLearningQuery(path,parse){const f=globalThis.restrictedFocusedFixture;return {data:path==="/v1/restricted-records?limit=25"?[parse(f.record)]:[],loaded:true,loading:false,loadingMore:false,error:null,moreError:null,nextCursor:null,loadMore(){}}}'};return nextLoad(url,context);}});
const{RestrictedRecordsWorkspace}=await import('../components/workspace.tsx');
function render(role:'admin'|'teacher',journal=new CommandJournal()){fixture.app={locale:'en',status:'ready',online:true,apiUrl:'https://fixture.invalid',accessToken:'fictional',accessGeneration:1,commandJournal:journal,formDrafts:new FormDrafts(),refreshAccess(){},reportDiagnostic(){},membership:{userId:id(2),schoolId:id(1),role,entitlements:['school.operations','restricted.records']}};return renderToStaticMarkup(createElement(RestrictedRecordsWorkspace));}
test('unselected Restricted directory presents human summary only and policy requires explicit opening',()=>{for(const role of['admin','teacher']as const){const html=render(role);assert.match(html,/Check the classroom account/);assert.match(html,/Alex Taylor/);assert.doesNotMatch(html,/Full private factual context belongs only|<textarea|restricted-reader/);assert.match(html,/restricted-directory/);}});
test('another retained record command cannot mount the Administrator policy editor',()=>{const journal=new CommandJournal();journal.prepare(`/v1/restricted-records/${record.id}/correct`,`/v1/restricted-records/${record.id}/correct`,{expectedRevision:1,title:record.title,note:record.note,reason:'Original correction',confirmCorrection:true});const html=render('admin',journal);assert.doesNotMatch(html,/School-authored retention review note/);assert.match(html,/disabled/);assert.equal(journal.pending().length,1);});
