import { LearningApiError } from '../../shared/api/client.ts';
export type Summary = { learnerId: string; status: 'DISABLED' | 'RECORDED_ONLY'; totalPoints: number | null; periodId: string | null; leaderboardEnabled: boolean };
export type Policy = { id: string; version: number; points: { practice: number; revision: number; reflection: number }; milestones: { key: string; title: string; minimumPoints: number }[]; approvedBy: string; approvedAt: string };
export type Period = { id: string; classId: string; policyId: string; title: string; startsAt: string; endsAt: string };
export type Ledger = { id: string; learnerId: string; periodId: string; observationId: string; kind: 'practice' | 'revision' | 'reflection'; points: number; occurredAt: string; policyId: string };
export type Achievement = { id: string; learnerId: string; periodId: string; policyId: string; key: string; title: string; minimumPoints: number; earnedAt: string };
export type Leaderboard = { periodId: string; status: 'OPT_IN_RECORDED_ACTIONS'; items: { alias: string; points: number; rank: number }[] };
const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
const strings = (row: Record<string, unknown>, keys: string[]) => keys.every(key => typeof row[key] === 'string' && row[key] !== '');
const count = (value: unknown) => typeof value === 'number' && Number.isInteger(value) && value >= 0;
const date = (value: unknown) => typeof value === 'string' && Number.isFinite(Date.parse(value));
export function parseSummary(value: unknown): Summary { if (!object(value) || !strings(value, ['learnerId']) || !['DISABLED', 'RECORDED_ONLY'].includes(String(value.status)) || !(value.periodId === null || typeof value.periodId === 'string') || typeof value.leaderboardEnabled !== 'boolean' || (value.status === 'DISABLED' ? value.totalPoints !== null : !count(value.totalPoints))) throw new LearningApiError('invalid'); return value as Summary; }
export function parsePolicy(value: unknown): Policy { if (!object(value) || !strings(value, ['id', 'approvedBy']) || !count(value.version) || Number(value.version) < 1 || !date(value.approvedAt) || !object(value.points) || ['practice', 'revision', 'reflection'].some(key => !count((value.points as Record<string, unknown>)[key])) || !Array.isArray(value.milestones) || value.milestones.some(item => !object(item) || !strings(item, ['key', 'title']) || !count(item.minimumPoints) || Number(item.minimumPoints) < 1)) throw new LearningApiError('invalid'); return value as Policy; }
export function parsePeriod(value: unknown): Period { if (!object(value) || !strings(value, ['id', 'classId', 'policyId', 'title']) || !date(value.startsAt) || !date(value.endsAt) || Date.parse(String(value.endsAt)) <= Date.parse(String(value.startsAt))) throw new LearningApiError('invalid'); return value as Period; }
export function parseLedger(value: unknown): Ledger { if (!object(value) || !strings(value, ['id', 'learnerId', 'periodId', 'observationId', 'policyId']) || !['practice', 'revision', 'reflection'].includes(String(value.kind)) || !count(value.points) || !date(value.occurredAt)) throw new LearningApiError('invalid'); return value as Ledger; }
export function parseAchievement(value: unknown): Achievement { if (!object(value) || !strings(value, ['id', 'learnerId', 'periodId', 'policyId', 'key', 'title']) || !count(value.minimumPoints) || Number(value.minimumPoints) < 1 || !date(value.earnedAt)) throw new LearningApiError('invalid'); return value as Achievement; }
export function parseLeaderboard(value: unknown): Leaderboard { if (!object(value) || !strings(value, ['periodId']) || value.status !== 'OPT_IN_RECORDED_ACTIONS' || !Array.isArray(value.items) || value.items.some(item => !object(item) || Object.keys(item).some(key => !['alias', 'points', 'rank'].includes(key)) || !strings(item, ['alias']) || !count(item.points) || !count(item.rank) || Number(item.rank) < 1)) throw new LearningApiError('invalid'); return value as Leaderboard; }
