import assert from 'node:assert/strict';
import test from 'node:test';
import { createElement } from 'react';
import * as React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import type { AdminTrailContext } from '../admin-trail-model.ts';
Object.assign(globalThis, { React });
const { AdminTrailHomeView } = await import('../components/admin-trail-home.tsx');
function context(): AdminTrailContext { return { availability: 'ready', schoolName: null, environmentLabel: null, dateLabel: null, facts: [], areas: [], people: { status: 'unavailable', records: [] }, policies: [], governance: null, execution: null, audit: { status: 'unavailable', records: [] } }; }
function render(value: AdminTrailContext, locale: 'en' | 'ar' = 'en') { return renderToStaticMarkup(createElement(AdminTrailHomeView, { context: value, locale })); }
test('unknown institution facts and audit are explicit, never false all-clear KPIs', () => { const html = render(context()); assert.match(html, /School information is not available/); assert.match(html, /Current audit records are not available/); assert.doesNotMatch(html, /0 errors|100%|No recent activity|All policies approved|Omar/); });
test('denied, offline and failed context hide current school people and audit facts', () => { for (const availability of ['denied', 'offline', 'error'] as const) { const value = context(); value.availability = availability; value.schoolName = 'Private school'; value.people = { status: 'ready', records: [{ key: 'private-id', name: 'Private person', context: 'Private role', action: { label: 'Edit private access', onClick() {} } }] }; const html = render(value); assert.doesNotMatch(html, /Private|private-id|private access/); } });
test('missing policy value remains unknown while explicit false stays disabled', () => { const value = context(); value.policies = [{ key: 'unknown', title: 'Unresolved policy', state: 'unknown', description: 'Current approval missing' }, { key: 'disabled', title: 'Student direct messages', state: 'disabled', description: 'School policy disables this capability' }]; const html = render(value); assert.match(html, /Unresolved policy/); assert.match(html, /Unknown/); assert.match(html, /Disabled/); assert.doesNotMatch(html, /Approved automatically/); });
test('worker completion is distinct from XP, learning outcome and live provider readiness', () => { const value = context(); value.execution = { state: 'processing', title: 'Current deterministic worker receipts', description: 'Returned authorized events only', receiptLabel: 'Handler processing completed', action: { label: 'Review execution receipts', onClick() {} } }; value.governance = { mode: 'fixture-only', title: 'Synthetic example environment', description: 'Live provider approval is not established', action: { label: 'Review governance', onClick() {} } }; const html = render(value); assert.match(html, /Queue completion does not establish a learner outcome or points/); assert.match(html, /Fixture-only context/); assert.doesNotMatch(html, /Live AI ready|Awarded XP|0 failures/); });
test('pending permitted controls stay disabled and rendering cannot grant permissions', () => { const value = context(); let calls = 0; const pending = { label: 'Review current policy', pending: true, onClick() { calls += 1; } }; value.primaryAction = pending; value.areas = [{ key: 'policy', title: 'Policies', description: 'Current approvals', icon: 'shield', action: pending }]; const html = render(value); assert.equal((html.match(/disabled="" aria-busy="true"/g) || []).length, 2); assert.equal(calls, 0); assert.doesNotMatch(html, /Create tenant|Service role|Release grades/); });
test('unavailable collections do not render stale person or audit rows', () => { const value = context(); value.audit.records = [{ key: 'old', actorName: 'Stale actor', targetName: 'Stale object', description: 'Stale action', dateLabel: null, outcome: 'succeeded' }]; assert.doesNotMatch(render(value), /Stale/); });
test('Arabic uses the same deterministic role composition and human labels', () => { const value = context(); value.schoolName = 'مدرسة حالية'; const html = render(value, 'ar'); assert.equal(html, render(value, 'ar')); assert.match(html, /lang="ar" dir="rtl"/); assert.match(html, /مدرسة حالية/); assert.match(html, /صورة واضحة لمدرستك/); });
