import { z } from 'zod';
import { attendanceInputSchema } from '@cuevo/contracts';
import { LearningApiError, type Command } from '../../shared/api/client.ts';
import { parseAttendance, parseSchoolRosterPerson, type AttendanceRow, type ScheduleRow, type SchoolRow, type SchoolPerson } from './model.ts';
import { schoolPersonChoices } from './selection.ts';
export const attendancePath='/v1/school/attendance';
const reviewSchema=z.object({classId:z.uuid(),learnerId:z.uuid(),occurredOn:z.iso.date(),expectedRevision:z.number().int().nonnegative(),sourceId:z.uuid().nullable()}).strict();
export type AttendanceReview=z.infer<typeof reviewSchema>;
export function attendanceReview(row:AttendanceRow):AttendanceReview{return reviewSchema.parse({classId:row.classId,learnerId:row.learnerId,occurredOn:row.occurredOn,expectedRevision:row.revision,sourceId:row.id});}
export function parseAttendanceReview(value:unknown):AttendanceReview|null{const parsed=reviewSchema.safeParse(value);return parsed.success?parsed.data:null;}
export function currentDailyReview(review:AttendanceReview|null,classId:string,day:string):AttendanceReview|null{return review&&review.classId===classId&&review.occurredOn===day?review:null;}
export function attendanceCreationCurrent(review:AttendanceReview,rows:AttendanceRow[]):boolean{return review.expectedRevision!==0||!rows.some(row=>row.classId===review.classId&&row.learnerId===review.learnerId&&row.occurredOn===review.occurredOn);}
export function attendanceDraftKey(review:AttendanceReview){return `${attendancePath}:review:${review.classId}:${review.occurredOn}:${review.learnerId}:${review.sourceId??'new'}`;}
export function attendanceRecovery(command:Command|undefined){if(command?.path!==attendancePath)return null;const input=attendanceInputSchema.safeParse(command.body);return input.success?{key:command.key,input:input.data,review:{classId:input.data.classId,learnerId:input.data.studentId,occurredOn:input.data.occurredOn,expectedRevision:input.data.expectedRevision,sourceId:null}as AttendanceReview}:null;}
export function attendanceBody(review:AttendanceReview,values:FormData){const input=attendanceInputSchema.safeParse({classId:review.classId,studentId:review.learnerId,occurredOn:review.occurredOn,expectedRevision:review.expectedRevision,status:String(values.get('status')??''),note:String(values.get('note')??''),...(String(values.get('correctionReason')??'').trim()?{correctionReason:String(values.get('correctionReason'))}:{})});if(!input.success)throw new LearningApiError('invalid');return input.data;}
export function validateAttendanceReceipt(value:unknown,original:Command):void{const input=attendanceInputSchema.safeParse(original.body);if(original.path!==attendancePath||!input.success)throw new LearningApiError('invalid');const row=parseAttendance(value);const detail=value as Record<string,unknown>;if(!z.uuid().safeParse(row.id).success||row.classId!==input.data.classId||row.learnerId!==input.data.studentId||row.occurredOn!==input.data.occurredOn||row.revision!==input.data.expectedRevision+1||row.status!==input.data.status||row.note!==input.data.note||(detail.correctionReason??null)!==(input.data.correctionReason??null))throw new LearningApiError('invalid');}
export type AttendanceRoster=SchoolRow&{displayName:string;classId:string;className:string|null;academicYearName:string|null};
export function parseAttendanceRoster(value:unknown,classId:string):AttendanceRoster{if(!value||typeof value!=='object'||Array.isArray(value))throw new LearningApiError('invalid');const row=value as Record<string,unknown>;if(row.classId!==classId)throw new LearningApiError('invalid');if(row.selectionContext!==undefined)return {...row,...parseSchoolRosterPerson(value),classId:String(row.classId),className:row.className as string|null,academicYearName:row.academicYearName as string|null} as AttendanceRoster;if(!['id','displayName','className','academicYearName'].every(key=>typeof row[key]==='string'&&String(row[key]).trim()))throw new LearningApiError('invalid');return row as AttendanceRoster;}
export function dailyAttendance(rows:AttendanceRow[],classId:string,day:string){return !day?[]:rows.filter(row=>(!classId||row.classId===classId)&&row.occurredOn===day);}
export function dailyCalendar(rows:ScheduleRow[],classId:string,day:string){if(!/^\d{4}-\d\d-\d\d$/.test(day)||!Number.isFinite(Date.parse(day))||new Date(day).toISOString().slice(0,10)!==day)return[];const start=Date.parse(day+'T00:00:00Z'),end=start+86400000;return rows.filter(row=>(!classId||row.classId===null||row.classId===classId)&&Date.parse(row.startsAt)<end&&Date.parse(row.endsAt)>=start);}
export function attendanceRosterChoices(rows:AttendanceRoster[],locale:'en'|'ar'='en'){const choices=schoolPersonChoices(rows.map(row=>({...row,role:'student',status:'active',effectiveFrom:'',effectiveTo:null,synthetic:false,selectionContext:row.selectionContext??{status:'REQUIRES_REVIEW',enrollmentState:'UNAVAILABLE',classes:[]}}))as SchoolPerson[],locale);return choices;}
