import { z } from 'zod';
import { restrictedRecordCreateSchema,restrictedRecordCorrectionSchema,restrictedFollowUpApprovalSchema,restrictedFollowUpSchema,restrictedRecordResponseSchema,restrictedPolicySchema,restrictedPolicyResponseSchema,type RestrictedRecord } from '@cuevo/contracts';
import { LearningApiError,type Command } from '../../shared/api/client.ts';
export const restrictedPath='/v1/restricted-records';
type ReadContext={apiUrl:string;membership:{schoolId:string;userId:string;role:string;entitlements:readonly string[]}|null;accessToken:string|null;online:boolean;status:string;accessGeneration:number};
export function restrictedReadScope(app:ReadContext,path:string|null,refresh:number):string|null{if(!path||!app.online||app.status!=='ready'||!app.accessToken||!app.membership||!['admin','teacher'].includes(app.membership.role)||!['school.operations','restricted.records'].every(code=>app.membership!.entitlements.includes(code)))return null;return JSON.stringify([app.apiUrl,app.membership.schoolId,app.membership.userId,app.membership.role,app.accessToken,app.accessGeneration,path,refresh]);}
export function currentRestrictedRead<T>(value:{scope:string|null;value:T}|null|undefined,scope:string|null):T|null{return scope&&value?.scope===scope?value.value:null;}
const courseChoice=z.object({id:z.uuid(),title:z.string().trim().min(1).max(200),className:z.string().trim().min(1).max(200)}).strict();
const personChoice=z.object({id:z.uuid(),displayName:z.string().trim().min(1).max(200),role:z.enum(['student','teacher'])}).strict();
export function parseRestrictedCourseChoice(value:unknown){const parsed=courseChoice.safeParse(value);if(!parsed.success)throw new LearningApiError('invalid');return parsed.data;}
export function parseRestrictedPersonChoice(value:unknown){const parsed=personChoice.safeParse(value);if(!parsed.success)throw new LearningApiError('invalid');return parsed.data;}
export function restrictedChoices(rows:readonly{id:string;label:string}[]){return rows.map(row=>({value:row.id,label:row.label,requiresReview:!row.label.trim()||rows.filter(other=>other.label===row.label).length!==1}));}
export function restrictedDraftKey(courseId:string,learnerId:string){return `${restrictedPath}:create:${courseId}:${learnerId}`;}
const actionSchema=z.object({id:z.uuid(),kind:z.enum(['correct','approve','followup']),courseId:z.uuid(),learnerId:z.uuid(),revision:z.number().int().positive(),occurredAt:z.iso.datetime({offset:true}),authorId:z.uuid()}).strict();
export type RestrictedReview=z.infer<typeof actionSchema>;
export function restrictedReview(record:RestrictedRecord,kind:RestrictedReview['kind']):RestrictedReview{return{ id:record.id,kind,courseId:record.courseId,learnerId:record.learnerId,revision:record.revision,occurredAt:record.occurredAt,authorId:record.authorId};}
export function parseRestrictedReview(value:unknown):RestrictedReview|null{const parsed=actionSchema.safeParse(value);return parsed.success?parsed.data:null;}
export function restrictedActionPath(action:Pick<RestrictedReview,'id'|'kind'>){return `${restrictedPath}/${action.id}/${action.kind==='followup'?'follow-up':action.kind}`;}
export function restrictedRecovery(command:Command|undefined){if(!command)return null;if(command.path===restrictedPath){const input=restrictedRecordCreateSchema.safeParse(command.body);return input.success?{kind:'create' as const,key:command.key,input:input.data}:null;}const path=command.path.match(/^\/v1\/restricted-records\/([^/]+)\/(correct|approve|follow-up)$/);if(!path||!z.uuid().safeParse(path[1]).success)return null;const kind=path[2]==='follow-up'?'followup':path[2];const parsed=(kind==='correct'?restrictedRecordCorrectionSchema:kind==='approve'?restrictedFollowUpApprovalSchema:restrictedFollowUpSchema).safeParse(command.body);return parsed.success?{kind:kind as RestrictedReview['kind'],key:command.key,id:path[1],input:parsed.data}:null;}
/** Commands return the current authorized projection on replay, which may be later.
 * Immutable identity is always checked; command-owned fields are checked only
 * when the returned revision is exactly the command's resulting revision. */
export function validateRestrictedReceipt(value:unknown,original:Command,actorId:string,basis?:Pick<RestrictedRecord,'id'|'courseId'|'learnerId'|'occurredAt'|'authorId'>):void{
 if(original.path===restrictedPath+'/policy'){const input=restrictedPolicySchema.safeParse(original.body),receipt=restrictedPolicyResponseSchema.safeParse(value);if(!input.success||!receipt.success||receipt.data.version<input.data.expectedVersion+1||receipt.data.version===input.data.expectedVersion+1&&(receipt.data.ownerId!==input.data.ownerId||receipt.data.enabled!==input.data.enabled||receipt.data.retentionNote!==input.data.retentionNote))throw new LearningApiError('invalid');return;}
 const recovery=restrictedRecovery(original),parsed=restrictedRecordResponseSchema.safeParse(value);if(!recovery||!parsed.success)throw new LearningApiError('invalid');const receipt=parsed.data;
 if(recovery.kind==='create'){const input=recovery.input;if(receipt.courseId!==input.courseId||receipt.learnerId!==input.learnerId||receipt.authorId!==actorId||Date.parse(receipt.occurredAt)!==Date.parse(input.occurredAt)||receipt.revision===1&&(receipt.title!==input.title||receipt.note!==input.note||receipt.state!=='AWAITING_REVIEW'))throw new LearningApiError('invalid');return;}
 if(receipt.id!==recovery.id||basis&&(receipt.id!==basis.id||receipt.courseId!==basis.courseId||receipt.learnerId!==basis.learnerId||receipt.authorId!==basis.authorId||Date.parse(receipt.occurredAt)!==Date.parse(basis.occurredAt)))throw new LearningApiError('invalid');
 const input=original.body,expected=Number(input.expectedRevision)+1;if(receipt.revision<expected)throw new LearningApiError('invalid');if(receipt.revision!==expected)return;
 if(recovery.kind==='correct'&&(receipt.title!==input.title||receipt.note!==input.note||receipt.state!=='AWAITING_REVIEW')||recovery.kind==='approve'&&(receipt.followUpOwnerId!==input.followUpOwnerId||receipt.followUpInstructions!==input.instructions||receipt.state!=='APPROVED_FOLLOW_UP')||recovery.kind==='followup'&&(receipt.followUpNote!==input.note||receipt.state!==input.status||receipt.followUpOwnerId!==actorId))throw new LearningApiError('invalid');
}
