import{createHash}from'node:crypto';import{z}from'zod';import{DomainError,requireCapability,type ActorContext}from'@cuevo/domain';import{restrictedPolicySchema,restrictedRecordCreateSchema,restrictedRecordCorrectionSchema,restrictedFollowUpApprovalSchema,restrictedFollowUpSchema,restrictedRecordQuerySchema,restrictedPolicyResponseSchema,restrictedRecordResponseSchema,idempotencyKeySchema}from'@cuevo/contracts';import type{Database}from'../../platform/database/database';
export const restrictedCommands={policy:restrictedPolicySchema,create:restrictedRecordCreateSchema,correct:restrictedRecordCorrectionSchema,approve:restrictedFollowUpApprovalSchema,followup:restrictedFollowUpSchema};export type RestrictedCommand=keyof typeof restrictedCommands;
const parse=<T>(schema:z.ZodType<T>,value:unknown)=>{const parsed=schema.safeParse(value);if(!parsed.success)throw new DomainError('INVALID_INPUT',400,'Review the restricted record fields.');return parsed.data;};const safe=(error:unknown)=>{if(error instanceof DomainError)return error;const code=error&&typeof error==='object'&&'code'in error?String(error.code):'';return new DomainError(code==='42501'?'FORBIDDEN':['22023','55000','23505'].includes(code)?'RESTRICTED_RECORD_REQUIRES_REVIEW':'REQUEST_UNAVAILABLE',code==='42501'?403:['22023','55000','23505'].includes(code)?409:503,'The restricted record requires current purpose access or human review.');};
export class RestrictedRecordsService{constructor(private readonly database:Database){}
 async policy(actor:ActorContext){requireCapability(actor,actor.schoolId,'restricted.records',['admin','teacher']);try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>parse(restrictedPolicyResponseSchema,(await c.query('select internal.read_restricted_policy()as response')).rows[0]?.response));}catch(error){throw safe(error);}}
 async list(actor:ActorContext,query:unknown){requireCapability(actor,actor.schoolId,'restricted.records',['admin','teacher']);const page=parse(restrictedRecordQuerySchema,query);try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>{const response=(await c.query('select internal.read_restricted_records($1,$2)as response',[page.limit,page.cursor??null])).rows[0]?.response;return parse(z.object({items:z.array(restrictedRecordResponseSchema).max(25),nextCursor:z.uuid().nullable()}).strict(),response);});}catch(error){throw safe(error);}}
 async history(actor:ActorContext,id:string,query:unknown){requireCapability(actor,actor.schoolId,'restricted.records',['admin','teacher']);parse(z.uuid(),id);const page=parse(restrictedRecordQuerySchema,query);try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>(await c.query('select internal.read_restricted_history($1,$2,$3)as response',[id,page.limit,page.cursor??null])).rows[0]?.response);}catch(error){throw safe(error);}}
 async choices(actor:ActorContext,courseId:string|null,query:unknown){requireCapability(actor,actor.schoolId,'restricted.records',['admin','teacher']);if(courseId)parse(z.uuid(),courseId);const page=parse(restrictedRecordQuerySchema,query);try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>(await c.query('select internal.read_restricted_choices($1,$2,$3)as response',[courseId,page.limit,page.cursor??null])).rows[0]?.response);}catch(error){throw safe(error);}}
 async command(actor:ActorContext,kind:RestrictedCommand,target:string|null,body:unknown,key:unknown,requestId:string){requireCapability(actor,actor.schoolId,'restricted.records',kind==='policy'||kind==='approve'?['admin']:['admin','teacher']);if(target)parse(z.uuid(),target);const input=parse(restrictedCommands[kind]as z.ZodType<Record<string,unknown>>,body);const identity=parse(idempotencyKeySchema,key);const fingerprint=createHash('sha256').update(JSON.stringify({kind,target,input})).digest('hex');try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>{const response=(await c.query('select internal.restricted_record_command($1,$2,$3::jsonb,$4,$5,$6)as response',[kind,target,JSON.stringify(input),identity,fingerprint,requestId])).rows[0]?.response;const checked=(kind==='policy'?restrictedPolicyResponseSchema:restrictedRecordResponseSchema).safeParse(response);if(!checked.success)throw new DomainError('RESTRICTED_RECORD_OUTCOME_UNKNOWN',503,'The restricted action receipt is unconfirmed. Retry the same action.');return checked.data;});}catch(error){throw safe(error);}}
}

