'use client';
import {useCallback,useEffect,useState,type Ref} from 'react';
import {Button, WorkspaceState} from '@cuevo/ui';
import {useApp} from '../../../shared/session/providers';
import {canOpenWorkspace} from '../../../shared/session/capabilities';
import {useApiQuery} from '../../../shared/hooks/use-api';
import {usePaginatedLearningQuery} from '../../../shared/hooks/use-paginated-query';
import {LoadMore} from '../../../shared/components/load-more';
import {LearningError} from '../../../shared/components/feedback';
import {parseProgramme,programmeChoice} from '../../curriculum/model';
import {parseCourse} from '../../learning/model';
import {parseIntervention,parseOutcome} from '../../improvement/model';
import {OutcomeList} from '../../improvement/ui';
import {NativeResultView} from '../../academic/ui';
import {CoordinatorTrailHomeView} from './coordinator-trail-home';
import {coordinatorHomeChoices,coordinatorHomeChoicesReady,coordinatorHomeCourseChoices,coordinatorHomePeriod,coordinatorHomeOutcome,coordinatorHomeReadScope,currentCoordinatorHomeRead,parseCoordinatorHomeCoverage,coordinatorHomePlanIsCurrent} from '../coordinator-home-binding-model';
import {parentHomeSourceDenial,parentHomeSourceUsable,type ParentHomeSourceDenial,type ParentHomeSourceState} from '../parent-home-binding-model';
import type {CoordinatorTrailContext} from '../coordinator-trail-model';
import type {HomeDestination,HomeTarget} from '../model';
const copy={en:{refresh:'Refresh current review records',course:'Course to review',period:'School report period',chooseCourse:'Choose a current course',choosePeriod:'Choose a current period',review:'Review current curriculum sources',programmeLimit:'Recorded school programme and assessment context for this course.',coverageLimit:'A declared school plan does not establish official curriculum coverage.',outcome:'Current school follow-up',outcomeLimit:'This outcome belongs to its own approved practice source. It is not attributed to the selected course or period.',programmes:'All loaded programme records',outcomes:'All loaded native outcomes',evidence:'Read exact released result',plans:'Declared plans and source review',planCurrent:'Current declared source',planReview:'This declared plan requires review. Its evidence is not presented as current plan coverage.',planRevision:'Recorded school period revision',nextPage:'Next declared plan page',firstPage:'First declared plan page',changed:'The selected source requires current review.',followUp:'Open current follow-up',context:'Current source context',more:'Some current pages or supporting sources remain unavailable.',ambiguous:'Matching or missing names require school source review.'},ar:{refresh:'تحديث سجلات المراجعة الحالية',course:'المقرر للمراجعة',period:'فترة التقرير المدرسي',chooseCourse:'اختر مقررًا حاليًا',choosePeriod:'اختر فترة حالية',review:'مراجعة مصادر المنهج الحالية',programmeLimit:'بيانات البرنامج المدرسي والتقييم المسجّلة لهذا المقرر.',coverageLimit:'الخطة المدرسية المعلنة لا تثبت تغطية المنهج الرسمي.',outcome:'المتابعة المدرسية الحالية',outcomeLimit:'تتبع هذه النتيجة مصدر تدريبها المعتمد. لا تُنسب إلى المقرر أو الفترة المختارين.',programmes:'كل سجلات البرامج المحمّلة',outcomes:'كل النتائج الأصلية المحمّلة',evidence:'قراءة النتيجة الصادرة المحددة',plans:'الخطط المعلنة ومراجعة المصادر',planCurrent:'المصدر المعلن الحالي',planReview:'تتطلب هذه الخطة المعلنة المراجعة. لا تُعرض شواهدها كتغطية حالية للخطة.',planRevision:'إصدار الفترة المدرسية المسجل',nextPage:'صفحة الخطط المعلنة التالية',firstPage:'صفحة الخطط المعلنة الأولى',changed:'يتطلب المصدر المختار مراجعة حالية.',followUp:'فتح المتابعة الحالية',context:'سياق المصدر الحالي',more:'بعض الصفحات الحالية أو المصادر الداعمة غير متاحة بعد.',ambiguous:'تحتاج الأسماء المتشابهة أو المفقودة إلى مراجعة مصادر المدرسة.'}};
const sourceCopy={en:{loading:'Checking current source…',choose:'Choose a current course and period to inspect declared plan evidence.',complete:'Load all current course, programme and period choices before selecting the exact context.',noEvidence:'This page has no released result evidence for its current plans. Missing sources do not establish an evidence-gap total.',class:'Class',programme:'Programme',year:'School year',version:'Curriculum source version',unknown:'Current source context unavailable'},ar:{loading:'جارٍ التحقق من المصدر الحالي…',choose:'اختر مقررًا وفترة حالية لفحص شواهد الخطة المعلنة.',complete:'حمّل خيارات المقرر والبرنامج والفترة كاملة قبل اختيار السياق المحدد.',noEvidence:'لا تتضمن هذه الصفحة شواهد نتائج صادرة للخطط الحالية. غياب المصادر لا يثبت إجمالي فجوات الشواهد.',class:'الصف',programme:'البرنامج',year:'العام الدراسي',version:'إصدار مصدر المنهج',unknown:'سياق المصدر الحالي غير متاح'}};
export function CoordinatorTrailHomeConnected({onNavigate,headingRef}:{onNavigate:(target:HomeDestination)=>void;headingRef?:Ref<HTMLHeadingElement>}) {
 const{membership,apiUrl}=useApp();return <CurrentCoordinatorHome key={`${apiUrl}:${membership?.schoolId}:${membership?.userId}:${membership?.role}`} onNavigate={onNavigate} headingRef={headingRef}/>;
}
function useCurrentCoordinatorSource<T extends ParentHomeSourceState>(query:T,scope:string|null):T&{usable:boolean;denied:boolean} {
 const [denial,setDenial]=useState<ParentHomeSourceDenial|null>(null),current=parentHomeSourceDenial(denial,scope,query);if(current!==denial)setDenial(current);
 return {...query,error:current?.error??query.error,usable:parentHomeSourceUsable(query,current),denied:!!current};
}
function CurrentCoordinatorHome({onNavigate,headingRef}:{onNavigate:(target:HomeDestination)=>void;headingRef?:Ref<HTMLHeadingElement>}) {
 const app=useApp();const{membership,locale}=app;const t=copy[locale],s=sourceCopy[locale];const[refresh,setRefresh]=useState(0),[courseId,setCourseId]=useState(''),[periodId,setPeriodId]=useState(''),[cursor,setCursor]=useState<string|null>(null),[now,setNow]=useState<number|null>(null);useEffect(()=>setNow(Date.now()),[refresh,app.accessGeneration]);
 const can=(target:HomeTarget)=>!!membership&&canOpenWorkspace(target,membership.entitlements,membership.role);
 const ready=app.online&&app.status==='ready'&&membership?.role==='coordinator';
 const programmePath=ready&&can('curriculum')?'/v1/curriculum/programmes?limit=25':null;const programmeScope=coordinatorHomeReadScope(app,'','',programmePath,refresh);const programmeParser=useCallback((value:unknown)=>{const item=parseProgramme(value);return{id:item.id,scope:programmeScope,value:item};},[programmeScope]);const programmes=useCurrentCoordinatorSource(usePaginatedLearningQuery(programmeScope?programmePath:null,programmeParser,refresh),programmeScope);const programmeRows=programmes.usable?programmes.data.flatMap(row=>{const item=currentCoordinatorHomeRead(row,programmeScope);return item?[item]:[];}):[];
 const coursePath=ready&&can('curriculum')?'/v1/courses?limit=25':null;const courseScope=coordinatorHomeReadScope(app,'','',coursePath,refresh);const courseParser=useCallback((value:unknown)=>{const item=parseCourse(value);return{id:item.id,scope:courseScope,value:item};},[courseScope]);const courses=useCurrentCoordinatorSource(usePaginatedLearningQuery(courseScope?coursePath:null,courseParser,refresh),courseScope);const courseRows=courses.usable?courses.data.flatMap(row=>{const item=currentCoordinatorHomeRead(row,courseScope);return item?[item]:[];}):[];const courseChoices=coordinatorHomeCourseChoices(courseRows,programmeRows,s.unknown),courseReady=coordinatorHomeChoicesReady(courses)&&coordinatorHomeChoicesReady(programmes);const selectedCourse=courseReady?courseRows.find(row=>row.id===courseId&&!courseChoices.find(choice=>choice.value===row.id)?.requiresReview):undefined;
 const periodPath=ready&&can('school')?'/v1/school/report-periods?limit=25':null;const periodScope=coordinatorHomeReadScope(app,'','',periodPath,refresh);const periodParser=useCallback((value:unknown)=>{const item=coordinatorHomePeriod(value);return{id:item.id,scope:periodScope,value:item};},[periodScope]);const periods=useCurrentCoordinatorSource(usePaginatedLearningQuery(periodScope?periodPath:null,periodParser,refresh),periodScope);const periodRows=periods.usable?periods.data.flatMap(row=>{const item=currentCoordinatorHomeRead(row,periodScope);return item?[item]:[];}):[];const periodChoices=coordinatorHomeChoices(periodRows,row=>[row.name,row.startsOn,row.endsOn].filter(value=>typeof value==='string').join(' · '));const periodReady=coordinatorHomeChoicesReady(periods);const selectedPeriod=periodReady?periodRows.find(row=>row.id===periodId&&!periodChoices.find(choice=>choice.value===row.id)?.requiresReview&&Number.isInteger(row.revision)&&Number(row.revision)>0):undefined;
 const coveragePath=ready&&selectedCourse&&selectedPeriod?`/v1/curriculum/courses/${courseId}/coverage?periodId=${periodId}&limit=25${cursor?`&cursor=${cursor}`:''}`:null;const coverageScope=coordinatorHomeReadScope(app,courseId,periodId,coveragePath,refresh);const coverageParser=useCallback((value:unknown)=>({scope:coverageScope,value:parseCoordinatorHomeCoverage(value,courseId,periodId,Number(selectedPeriod?.revision))}),[coverageScope,courseId,periodId,selectedPeriod?.revision]);const coverageRead=useApiQuery(coverageScope?coveragePath:null,coverageParser,refresh);const coverage=!coverageRead.loading&&!coverageRead.error?currentCoordinatorHomeRead(coverageRead.data,coverageScope):null;
 const taskPath=ready&&can('improvement')?'/v1/interventions?limit=25':null;const taskScope=coordinatorHomeReadScope(app,'','',taskPath,refresh);const taskParser=useCallback((value:unknown)=>{const item=parseIntervention(value);return{id:item.id,scope:taskScope,value:item};},[taskScope]);const tasks=useCurrentCoordinatorSource(usePaginatedLearningQuery(taskScope?taskPath:null,taskParser,refresh),taskScope);const taskRows=tasks.usable?tasks.data.flatMap(row=>{const item=currentCoordinatorHomeRead(row,taskScope);return item?[item]:[];}):[];
 const outcomePath=ready&&can('improvement')?'/v1/outcomes?limit=25':null;const outcomeScope=coordinatorHomeReadScope(app,'','',outcomePath,refresh);const outcomeParser=useCallback((value:unknown)=>{const item=parseOutcome(value);return{id:item.id,scope:outcomeScope,value:item};},[outcomeScope]);const outcomes=useCurrentCoordinatorSource(usePaginatedLearningQuery(outcomeScope?outcomePath:null,outcomeParser,refresh),outcomeScope);const outcomeRows=outcomes.usable?outcomes.data.flatMap(row=>{const item=currentCoordinatorHomeRead(row,outcomeScope);return item?[item]:[];}):[];const latest=coordinatorHomeOutcome(outcomeRows,taskRows);
 const queries=[programmes,courses,periods,tasks,outcomes];const errors=queries.flatMap(q=>q.error?[q.error]:[]);const loading=queries.some(q=>q.loading);const partial=queries.some(q=>q.nextCursor||q.moreError)||!!coverageRead.error;
 const programmeContext=selectedCourse?programmeRows.filter(p=>p.classId===selectedCourse.classId&&p.subjectId===selectedCourse.subjectId):programmeRows;
 const records=coverage?.items.flatMap(plan=>coordinatorHomePlanIsCurrent(plan,coverage.periodRevision)?plan.evidence.map(source=>({key:source.id,title:plan.referenceTitle,learnerName:source.learnerName,contextLabel:coverage.className+' · '+coverage.periodName,teacherName:null,feedback:null,nativeResultView:<NativeResultView result={source.nativeResult}/>,action:{label:t.evidence,onClick:()=>onNavigate({view:'academic',source:'result',id:source.resultId})}})):[])??[];
 const refreshAction=()=>{setCursor(null);setRefresh(value=>value+1);};
 const sourceControls=(query:Parameters<typeof LoadMore>[0]['query']&{error:ParentHomeSourceState['error'];denied:boolean},label:string)=>query.error?<div className="coordinator-trail__source-controls"><LearningError error={query.error}/><Button type="button" variant="quiet" onClick={refreshAction}>{t.refresh}</Button></div>:query.loading?<WorkspaceState kind="loading" description={s.loading} role="status"/>:!query.denied&&(query.nextCursor||query.moreError)?<div className="coordinator-trail__source-controls"><p>{t.more}</p><LoadMore query={query} label={label}/></div>:null;
 const coverageControls=coverageRead.error?<><LearningError error={coverageRead.error}/><Button type="button" variant="quiet" onClick={refreshAction}>{t.refresh}</Button></>:coverageRead.loading?<WorkspaceState kind="loading" description={s.loading} role="status"/>:coverage?<>{cursor?<Button type="button" variant="quiet" onClick={()=>setCursor(null)}>{t.firstPage}</Button>:null}{coverage.nextCursor?<Button type="button" variant="secondary" onClick={()=>setCursor(coverage.nextCursor)}>{t.nextPage}</Button>:null}</>:<WorkspaceState kind="unknown" description={s.choose}/>;
 const context:CoordinatorTrailContext={availability:!app.online?'offline':!ready?'denied':loading||errors.length||partial?'partial':'ready',classLabel:coverage?.className??(selectedCourse&&programmeContext.length===1?programmeContext[0].className:null),periodLabel:selectedPeriod?.name??null,dateLabel:now===null?null:new Intl.DateTimeFormat(locale,{dateStyle:'full'}).format(new Date(now)),selector:<><div className="field"><label htmlFor="coordinator-home-course">{t.course}</label><select id="coordinator-home-course" disabled={!courseReady} value={selectedCourse?courseId:''} onChange={event=>{setCourseId(event.target.value);setCursor(null);}}><option value="">{t.chooseCourse}</option>{courseChoices.map(choice=><option key={choice.value} value={choice.value} disabled={choice.requiresReview}>{choice.label}</option>)}</select></div><div className="field"><label htmlFor="coordinator-home-period">{t.period}</label><select id="coordinator-home-period" disabled={!periodReady} value={selectedPeriod?periodId:''} onChange={event=>{setPeriodId(event.target.value);setCursor(null);}}><option value="">{t.choosePeriod}</option>{periodChoices.map(choice=><option key={choice.value} value={choice.value} disabled={choice.requiresReview}>{choice.label}</option>)}</select></div>{!courseReady||!periodReady?<WorkspaceState kind="unknown" description={s.complete}/>:courseChoices.some(c=>c.requiresReview)||periodChoices.some(c=>c.requiresReview)?<WorkspaceState kind="review" description={t.ambiguous}/>:null}{sourceControls(courses,t.course)}{sourceControls(periods,t.period)}{sourceControls(programmes,t.programmes)}</>,recovery:{label:t.refresh,onClick:refreshAction},primaryAction:can('curriculum')?{label:t.review,onClick:()=>onNavigate('curriculum')}:undefined,programmes:programmeContext.slice(0,3).map(p=>({key:p.id,name:p.name,contextLabel:programmeChoice(p),status:'requires-review',statusLabel:''})),programmeControls:sourceControls(programmes,t.programmes),
 sourceContext:{title:t.context,fields:[{label:t.course,value:selectedCourse?.title??t.chooseCourse},{label:s.class,value:coverage?.className??(selectedCourse&&programmeContext.length===1?programmeContext[0].className:s.unknown)},{label:t.period,value:selectedPeriod?`${selectedPeriod.name} · ${selectedPeriod.startsOn}–${selectedPeriod.endsOn}`:t.choosePeriod},...(selectedCourse&&programmeContext.length===1?[{label:s.programme,value:programmeContext[0].name},{label:s.year,value:`${programmeContext[0].yearGroupName} · ${programmeContext[0].academicYearName}`},{label:s.version,value:programmeContext[0].packVersion}]:[])],description:t.programmeLimit},
 evidence:{status:coverageRead.error?'unavailable':coverageRead.loading?'loading':coverage?.nextCursor?'partial':coverage?'ready':'unavailable',coverage:'not-established',gap:{status:'unknown',count:null,basis:null},description:t.coverageLimit,records:records.slice(0,3),controls:<>{!records.length&&coverage?<WorkspaceState kind="unknown" description={coverage.nextCursor?t.more:s.noEvidence}/>:null}{coverageControls}</>},outcome:latest?{title:latest.task.title,nativeKind:'difference'in latest.outcome?'numeric':'rubric',comparisonView:<OutcomeList outcomes={[latest.outcome]} headingLevel={4}/>,baselineDate:null,followUpDate:new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(new Date(latest.outcome.measuredAt)),observationLabel:t.outcomeLimit,action:{label:t.followUp,onClick:()=>onNavigate({view:'improvement',source:'intervention',id:latest.task.id})}}:null,outcomeControls:<>{sourceControls(outcomes,t.outcomes)}{sourceControls(tasks,t.context)}</>,review:null};
 return <div><CoordinatorTrailHomeView context={context} locale={locale} headingRef={headingRef}/>{ready ? <div className="home-overview-controls"><Button type="button" variant="quiet" onClick={refreshAction}>{t.refresh}</Button></div> : null}</div>;
}
