'use client';
import{useState}from'react';
import{Button}from'@cuevo/ui';
import{useApp}from'../../../shared/session/providers';
import{CommandForm}from'../../../shared/components/command-form';
import{currentReleasedResultId,type MarkingItem}from'../model';
import{academicEn,academicAr}from'../messages';
import{ResultHistory}from'./result-history';
export function ClosedCorrection({item,onChanged}:{item:MarkingItem;onChanged:()=>void}){
 const{locale}=useApp();const t=locale==='ar'?academicAr:academicEn;const[open,setOpen]=useState(false);const current=item.currentResult;const resultId=currentReleasedResultId(current);
 return <section><p className="notice">{t.closedCorrectionNote}</p><Button type="button" variant="secondary" onClick={()=>setOpen(value=>!value)}>{current?t.correctClosed:t.markClosed}</Button>{open?<CommandForm title={current?t.correctClosed:t.markClosed} path={`/v1/submissions/${item.id}/closed-result`} fields={[...(item.model==='numeric'?[{name:'score',label:`${t.score} (0–${item.maxScore})`,type:'number'as const,min:0,max:item.maxScore,step:'any'as const,required:true,defaultValue:current?.model==='numeric'?current.score:undefined}]:item.rubric.criteria.map(criterion=>({name:`criterion:${criterion.key}`,label:criterion.title,type:'select'as const,required:true,options:criterion.levels.map(level=>({value:level.key,label:`${level.label} — ${level.description}`})),defaultValue:current?.model==='rubric'?current.nativeResult.criteria.find(choice=>choice.criterionKey===criterion.key)?.levelKey:undefined}))),{name:'feedback',label:t.feedback,type:'textarea',required:true,defaultValue:current?.feedback,maxLength:10000},{name:'reason',label:t.correctionReason,type:'textarea',required:true,maxLength:2000},{name:'parentVisible',label:t.parentVisible,type:'checkbox'},{name:'confirmCorrection',label:t.confirmClosedCorrection,type:'checkbox',required:true}]} body={values=>({...(item.model==='numeric'?{score:Number(values.get('score'))}:{nativeResult:{type:'rubric',rubricId:item.rubric.id,criteria:item.rubric.criteria.map(criterion=>({criterionKey:criterion.key,levelKey:String(values.get(`criterion:${criterion.key}`))}))}}),feedback:String(values.get('feedback')),reason:String(values.get('reason')),parentVisible:values.get('parentVisible')==='on',expectedPolicyVersion:item.policyVersion,expectedRevision:current?.revision??0,expectedSubmissionRevision:item.submissionRevision,expectedResultId:resultId,expectedResultRevision:current?.status==='RELEASED'?current.revision:0,sourceEvidence:true})} actionLabel={t.confirmAndRelease} onSaved={()=>{setOpen(false);onChanged();}} onCancel={()=>setOpen(false)} note={t.closedCorrectionNote}/>:null}{resultId?<ResultHistory resultId={resultId} anchor={{submissionId:item.id,assessmentId:item.assessmentId,learnerId:item.learnerId}}/>:null}</section>;
}
