import{Controller,Get,Post,Req,Res,type Type}from'@nestjs/common';import{ApiBearerAuth,ApiHeader,ApiBody}from'@nestjs/swagger';import{z}from'zod';import type{FastifyRequest,FastifyReply}from'fastify';import{DomainError}from'@cuevo/domain';import{recognitionPolicySchema,recognitionPeriodSchema,leaderboardParticipationSchema,recognitionBackfillSchema}from'@cuevo/contracts';import type{IdentityService}from'../../platform/identity/identity.service';import type{Database}from'../../platform/database/database';import{DevelopmentService,type DevelopmentCommand,type DevelopmentResource}from'./development.service';
const body=(schema:z.ZodType)=>ApiBody({required:true,schema:z.toJSONSchema(schema,{target:'openapi-3.0'})as never});
export function createDevelopmentController(identity:IdentityService,database:Database):Type<unknown>{const service=new DevelopmentService(database);
 @Controller('/v1/development')@ApiBearerAuth()@ApiHeader({name:'X-School-Id',required:false})class DevelopmentController{
 private async respond(req:FastifyRequest,res:FastifyReply,run:(actor:Awaited<ReturnType<IdentityService['resolve']>>)=>Promise<unknown>){try{const school=req.headers['x-school-id'];if(Array.isArray(school))throw new DomainError('INVALID_INPUT',400,'School selection is invalid.');const actor=await identity.resolve(req.headers.authorization,school);return res.code(200).header('Cache-Control','no-store').send(await run(actor));}catch(error){const safe=error instanceof DomainError?error:new DomainError('REQUEST_UNAVAILABLE',503,'Recognition services are temporarily unavailable.');return res.code(safe.status).header('Cache-Control','no-store').send({code:safe.code,message:safe.message,requestId:req.id});}}
 private command(req:FastifyRequest,res:FastifyReply,command:DevelopmentCommand){return this.respond(req,res,a=>service.command(a,command,req.body,req.headers['idempotency-key'],req.id));}
 @Get('/:resource')read(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,a=>{const resource=(r.params as{resource:DevelopmentResource}).resource;if(!['summary','policies','periods','ledger','achievements','leaderboard'].includes(resource))throw new DomainError('NOT_FOUND',404,'Recognition view is unavailable.');return service.read(a,resource,r.query);});}
 @Post('/policies')@body(recognitionPolicySchema)@ApiHeader({name:'Idempotency-Key',required:true})policy(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'policy');}
 @Post('/periods')@body(recognitionPeriodSchema)@ApiHeader({name:'Idempotency-Key',required:true})period(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'period');}
 @Post('/leaderboard/participation')@body(leaderboardParticipationSchema)@ApiHeader({name:'Idempotency-Key',required:true})participation(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'participation');}
 @Post('/periods/backfill')@body(recognitionBackfillSchema)@ApiHeader({name:'Idempotency-Key',required:true})backfill(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'backfill');}
 }return DevelopmentController;
}
