import'reflect-metadata';import{beforeAll,afterAll,describe,it,expect}from'vitest';import{Module}from'@nestjs/common';import{NestFactory}from'@nestjs/core';import{FastifyAdapter,type NestFastifyApplication}from'@nestjs/platform-fastify';import{createClient}from'@supabase/supabase-js';import{readFileSync}from'node:fs';import{config as dotenv}from'dotenv';import{Pool}from'pg';import{classLearningSummarySchema}from'@cuevo/contracts';import{parseServerConfig}from'@cuevo/config';import{Database}from'../../src/platform/database/database';import{IdentityService,type MembershipRow}from'../../src/platform/identity/identity.service';import{createUserVerifier}from'../../src/platform/identity/supabase-auth';import{createLearnerStateController}from'../../src/modules/learner-state/learner-state.controller';import{seedReferenceScenarios}from'../../../../scripts/seed-reference-scenarios';import{OutboxProcessor}from'../../../worker/src/jobs/outbox/processor';
dotenv({path:'.env.local',quiet:true});const cfg=parseServerConfig(process.env);const enabled=process.env.CUEVO_REQUIRE_INTEGRATION==='1'&&Boolean(cfg.databaseUrl&&cfg.workerDatabaseUrl&&cfg.supabaseUrl&&new URL(cfg.supabaseUrl).hostname==='127.0.0.1');if(process.env.CUEVO_REQUIRE_INTEGRATION==='1'&&!enabled)throw Error('Cuevo local integration required');const school='10000000-0000-4000-8000-000000000001';const classId='30000000-0000-4000-8000-000000000001';
describe.skipIf(!enabled)('current staff class learning summary actual Auth source77',()=>{
 let app:NestFastifyApplication;let db:Database;let worker:Pool;let owner:Pool;const tokens:Record<string,string>={};
 beforeAll(async()=>{
  const url=new URL(cfg.databaseUrl!);const workerUrl=new URL(cfg.workerDatabaseUrl!);if(url.hostname!=='127.0.0.1'||url.port!=='56322'||workerUrl.hostname!=='127.0.0.1'||workerUrl.port!=='56322'||workerUrl.username!=='cuevo_worker')throw Error('Cuevo local source and restricted worker required');await seedReferenceScenarios(cfg.databaseUrl!);url.username='postgres';url.password='postgres';owner=new Pool({connectionString:url.toString()});worker=new Pool({connectionString:cfg.workerDatabaseUrl});const processor=new OutboxProcessor(worker);for(let turn=0;turn<60;turn++){await processor.tick();const health=(await worker.query('select internal.worker_health()health')).rows[0].health;if(health.pendingCount===0)break;if(turn===59)throw Error('Bounded fixture source delivery unavailable');}
  const actors=(JSON.parse(readFileSync('supabase/seed/identities.json','utf8'))as{actors:{actorId:string;email:string}[]}).actors;const password=(JSON.parse(readFileSync('.local/runtime-secrets.json','utf8'))as{syntheticPassword:string}).syntheticPassword;for(const[role,suffix]of Object.entries({coordinator:'002',teacher:'004',student:'012',parent:'072',foreign:'133'})){const actor=actors.find(a=>a.actorId.endsWith(suffix))!;const auth=createClient(cfg.supabaseUrl!,cfg.supabasePublishableKey!,{auth:{persistSession:false,autoRefreshToken:false}});const session=await auth.auth.signInWithPassword({email:actor.email,password});if(!session.data.session)throw Error('Synthetic auth unavailable');tokens[role]=session.data.session.access_token;}
  db=new Database(cfg.databaseUrl);const identity=new IdentityService({verifyUser:createUserVerifier(cfg),currentMemberships:actor=>db.actorTransaction(actor,undefined,async c=>(await c.query<MembershipRow>('select*from "authorization".current_memberships()')).rows),isCurrentSession:(actor,session)=>db.actorTransaction(actor,undefined,async c=>Boolean((await c.query('select "authorization".is_current_session($1)active',[session])).rows[0]?.active))});@Module({controllers:[createLearnerStateController(identity,db)]})class App{}app=await NestFactory.create<NestFastifyApplication>(App,new FastifyAdapter({logger:false}),{logger:false});await app.init();await app.getHttpAdapter().getInstance().ready();
 },60000);afterAll(async()=>{await app?.close();await db?.close();await worker?.end();await owner?.end();});
 const request=(role:string,id=classId)=>app.inject({url:`/v1/classes/${id}/learning-summary?limit=100`,headers:{authorization:`Bearer ${tokens[role]}`,'x-school-id':school}});
 it('shows source77 native evidence, recorded actions and measured outcomes as separate class dimensions',async()=>{
  const response=await request('coordinator');expect(response.statusCode,response.body).toBe(200);expect(response.headers['cache-control']).toBe('no-store');const summary=classLearningSummarySchema.parse(response.json());expect(summary).toMatchObject({classId,scope:'CURRENT_CLASS_PAGE',coverage:'NOT_ESTABLISHED',observationCoverage:'RECORDED_ONLY'});
  const row=(suffix:string)=>summary.items.find(item=>item.learnerId.endsWith(suffix))!;expect(row('018').observed.practice.count).toBeGreaterThanOrEqual(4);expect(row('018').observed.reflection.count).toBeGreaterThanOrEqual(2);expect(row('024').academic.sources.some(source=>source.nativeResult.type==='numeric'&&source.nativeResult.score===3)).toBe(true);expect(row('048').academic.rubricCount).toBeGreaterThanOrEqual(1);expect(row('048').academic.sources.some(source=>source.nativeResult.type==='rubric'&&source.nativeResult.normalized===null)).toBe(true);expect(row('036').outcomes.improvedCount).toBeGreaterThanOrEqual(1);expect(row('042').outcomes.noMeaningfulChangeCount).toBeGreaterThanOrEqual(1);expect(summary).not.toHaveProperty('classGrade');expect(summary).not.toHaveProperty('intelligenceScore');
 });
 it('denies student/parent/foreign and unassigned teacher class summaries',async()=>{for(const role of['student','parent','foreign'])expect((await request(role)).statusCode).toBe(403);expect((await request('teacher','30000000-0000-4000-8000-000000000002')).statusCode).toBe(403);});
 it('keeps current class membership separate from revoked source programme authority',async()=>{
  const learner='20000000-0000-4000-8000-000000000048';const prior=(await owner.query('select programme_id,status,approved_by,updated_at from app.programme_learners where school_id=$1 and learner_id=$2',[school,learner])).rows;const before=classLearningSummarySchema.parse((await request('coordinator')).json()).items.find(item=>item.learnerId===learner)!;const sourceIds=new Set(before.academic.sources.map(source=>source.resultId));expect(before.academic.rubricCount).toBeGreaterThan(0);
  try{await owner.query("update app.programme_learners set status='revoked'where school_id=$1 and learner_id=$2",[school,learner]);const response=await request('coordinator');expect(response.statusCode,response.body).toBe(200);const after=classLearningSummarySchema.parse(response.json()).items.find(item=>item.learnerId===learner)!;expect(after).toBeDefined();expect(after.academic.sources.filter(source=>sourceIds.has(source.resultId))).toEqual([]);expect(after.academic.rubricCount).toBe(0);}finally{for(const row of prior)await owner.query('update app.programme_learners set status=$4,approved_by=$5,updated_at=$6 where school_id=$1 and learner_id=$2 and programme_id=$3',[school,learner,row.programme_id,row.status,row.approved_by,row.updated_at]);}
 });
});
