import{afterAll,beforeAll,describe,expect,it}from'vitest';import{randomUUID}from'node:crypto';import{createCustomerContext,customerCourse,customerActor,type CustomerContext}from'./customer-test-context';
const enabled=process.env.CUEVO_REQUIRE_INTEGRATION==='1';
describe.skipIf(!enabled)('reviewed technical curriculum lifecycle',()=>{
 let context:CustomerContext;let packId:string;let replacementId:string;let referenceId:string;let programmeId:string;let courseId:string;let academicId:string;let assessmentId:string;let submissionId:string;let resultId:string;let evidenceId:string;
 const initialTaskKey=randomUUID();const initialTaskBody={title:'Retained old source task',instructions:'Show the school check.',maxScore:10};
 async function pack(version:string){const source=await context.command('coordinator','/v1/curriculum/versions',{packId:'school-lifecycle',kind:'school_custom',framework:'School Custom',programme:'School lifecycle programme',version,scope:'synthetic-school-lifecycle',sourceStatus:'VERIFIED',rightsStatus:'PERMITTED',sourceLocation:'repo:school-authored-review',sourceChecksum:null,synthetic:true,reason:'School-authored source only; official acceptance remains unknown.'});const reference=await context.command('coordinator','/v1/curriculum/references',{packVersionId:source.id,parentId:null,type:'objective',title:'School checking objective',description:'Explain a school-authored check.',code:null,sequence:1,subjectId:context.subject,yearGroupId:context.group});return{sourceId:source.id,referenceId:reference.id};}
 const transition=(id:string,state:string,expectedRevision:number,replacementVersionId:string|null=null)=>context.command('coordinator',`/v1/curriculum/versions/${id}/lifecycle`,{state,expectedRevision,reviewBasis:'SCHOOL_AUTHORED',artifactDirectory:null,replacementVersionId,reason:'Explicit school source lifecycle review.',confirmTransition:true});
 beforeAll(async()=>{context=await createCustomerContext();courseId=(await customerCourse(context,'School lifecycle course')).courseId;const created=await pack('school-life-1');packId=created.sourceId;referenceId=created.referenceId;},30000);
 afterAll(async()=>{await context?.close();});
 it('requires actual human source review before new programme configuration and denies official claims',async()=>{
  const programme={packVersionId:packId,name:'School lifecycle class',classId:context.classId,subjectId:context.subject,yearGroupId:context.group,confirmConfiguration:true};expect((await context.request('coordinator','/v1/curriculum/programmes',programme)).statusCode).toBe(409);
  for(const role of ['teacher','strong','parent']as const)expect((await context.request(role,`/v1/curriculum/versions/${packId}/lifecycle`,{state:'APPROVED',expectedRevision:1,reviewBasis:'SCHOOL_AUTHORED',artifactDirectory:null,replacementVersionId:null,reason:'Unauthorized approval.',confirmTransition:true})).statusCode).toBe(403);
  await transition(packId,'APPROVED',1);await transition(packId,'ACTIVE',2);programmeId=(await context.command('coordinator','/v1/curriculum/programmes',programme)).id;academicId=String((await context.command('coordinator',`/v1/curriculum/courses/${courseId}`,{programmeId,referenceId,expectedVersion:1,confirmConfiguration:true})).academicReferenceId);await context.command('coordinator','/v1/curriculum/learners',{programmeId,learnerId:customerActor(12),status:'active',confirmAccessChange:true});
  expect((await context.request('coordinator','/v1/curriculum/references',{packVersionId:packId,parentId:null,type:'objective',title:'Late hierarchy addition',description:'Reviewed hierarchy cannot silently change.',code:null,sequence:2,subjectId:context.subject,yearGroupId:context.group})).statusCode).toBe(409);
  const official=await context.command('coordinator','/v1/curriculum/versions',{packId:'unverified-life-'+randomUUID(),kind:'curriculum',framework:'Repository official context',programme:'Requires external review',version:'UNKNOWN',scope:'unknown',sourceStatus:'UNKNOWN',rightsStatus:'UNKNOWN',sourceLocation:'repo:unknown',sourceChecksum:null,synthetic:false,reason:'No official approval evidence.'});expect((await context.request('coordinator',`/v1/curriculum/versions/${official.id}/lifecycle`,{state:'APPROVED',expectedRevision:1,reviewBasis:'SCHOOL_AUTHORED',artifactDirectory:null,replacementVersionId:null,reason:'Cannot infer approval.',confirmTransition:true})).statusCode).toBe(409);
 });
 it('supersedes new configuration while preserving ongoing work and historical native evidence',async()=>{
  const replacement=await pack('school-life-2');replacementId=replacement.sourceId;await transition(replacementId,'APPROVED',1);await transition(replacementId,'ACTIVE',2);
  const created=await context.request('teacher','/v1/assessments',{courseId,...initialTaskBody},initialTaskKey);expect(created.statusCode,created.body).toBe(200);const task=created.json();assessmentId=task.id;await context.command('teacher',`/v1/assessments/${assessmentId}/reference`,{referenceId:academicId,expectedPolicyVersion:1});
  await transition(packId,'SUPERSEDED',3,replacementId);
  expect((await context.request('coordinator','/v1/curriculum/programmes',{packVersionId:packId,name:'Denied new programme',classId:context.classId,subjectId:context.subject,yearGroupId:context.group,confirmConfiguration:true})).statusCode).toBe(409);
  const source=await context.command('strong',`/v1/assessments/${assessmentId}/submissions`,{content:'Ongoing work remains valid after supersession.'});submissionId=source.id;const mark=await context.command('teacher',`/v1/submissions/${submissionId}/results`,{score:0,feedback:'Explicit old-context native source.',expectedPolicyVersion:2,expectedRevision:0,sourceEvidence:true});const release=await context.command('teacher',`/v1/results/${mark.id}/release`,{expectedRevision:1,parentVisible:true});resultId=release.id;evidenceId=String(release.evidenceId);
  expect((await context.request('coordinator',`/v1/curriculum/versions/${packId}/lifecycle`,{state:'RETIRED',expectedRevision:4,reviewBasis:'SCHOOL_AUTHORED',artifactDirectory:null,replacementVersionId:null,reason:'Open learner work must first resolve.',confirmTransition:true})).statusCode).toBe(409);
 });
 it('retires only resolved work and keeps current authorized parent evidence readable',async()=>{
  await context.command('teacher',`/v1/submissions/${submissionId}/close`,{expectedRevision:1});await context.command('teacher',`/v1/assessments/${assessmentId}/availability`,{availableFrom:null,availableUntil:null,allowLate:false,state:'CLOSED',expectedAvailabilityVersion:1});
  await transition(packId,'RETIRED',4);
  const state=await context.request('coordinator',`/v1/curriculum/versions/${packId}/lifecycle?limit=25`);expect(state.statusCode,state.body).toBe(200);expect(state.json()).toMatchObject({state:'RETIRED',configurationAllowed:false,retainedEvidenceAllowed:true,customerReady:false});
  expect((await context.request('teacher','/v1/assessments',{courseId,title:'Denied retired task',instructions:'Retired source cannot gain new work.',maxScore:10})).statusCode).toBe(409);
  expect((await context.request('teacher','/v1/assessments',{courseId,...initialTaskBody},initialTaskKey)).statusCode).toBe(409);
  const availability=await context.request('strong',`/v1/curriculum/learning-availability?courseIds=${courseId}`);expect(availability.statusCode,availability.body).toBe(200);expect(availability.json().items).toContainEqual({id:courseId,readOnly:true});
  expect((await context.request('strong',`/v1/curriculum/learning-availability?courseIds=${Array.from({length:101},()=>courseId).join(',')}`)).statusCode).toBe(400);
  const evidence=await context.request('parent',`/v1/evidence/${evidenceId}`);expect(evidence.statusCode,evidence.body).toBe(200);expect(evidence.json()).toMatchObject({resultId,referenceId:academicId});
  const history=await context.request('parent',`/v1/results/${resultId}/history?limit=25`);expect(history.statusCode,history.body).toBe(200);expect(history.json().items).toHaveLength(1);
 });
});
