import{afterAll,beforeAll,describe,expect,it}from'vitest';
import{randomUUID}from'node:crypto';
import{createCustomerContext,customerCourse,customerAssessment,customerRoles,type CustomerContext}from'./customer-test-context';
const enabled=process.env.CUEVO_REQUIRE_INTEGRATION==='1';
describe.skipIf(!enabled)('class gradebook and selected reviewed releases',()=>{
 let context:CustomerContext;let courseId:string;let numeric:Record<string,unknown>;let rubric:Record<string,unknown>;let selections:Record<string,unknown>[];
 beforeAll(async()=>{
  context=await createCustomerContext();await context.client.query("update app.people set display_name='Unique gradebook learner'where school_id=$1 and actor_id='20000000-0000-4000-8000-000000000013'",[context.school]);courseId=(await customerCourse(context,'Current class gradebook')).courseId;
  const assessmentId=await customerAssessment(context,courseId,'Numeric school task');const source=await context.command('strong',`/v1/assessments/${assessmentId}/submissions`,{content:'Exact numeric learner source'});numeric=await context.command('teacher',`/v1/submissions/${source.id}/results`,{score:0,feedback:'Zero recorded explicitly.',expectedPolicyVersion:2,expectedRevision:0,sourceEvidence:true});
  const assessment=await context.command('teacher','/v1/assessments',{courseId,title:'Rubric school task',instructions:'School criterion',maxScore:10});await context.command('teacher',`/v1/assessments/${assessment.id}/reference`,{referenceId:context.referenceId,expectedPolicyVersion:1});
  const definition=await context.command('teacher','/v1/rubrics',{courseId,title:'School explanation rubric',version:'school-gradebook-1',criteria:[{key:'explanation',title:'Explanation',levels:[{key:'shown',label:'Shown',description:'The checking explanation is shown.'}]}]});await context.command('teacher',`/v1/assessments/${assessment.id}/rubric`,{rubricId:definition.id,expectedPolicyVersion:2});
  const rubricSource=await context.command('observed',`/v1/assessments/${assessment.id}/submissions`,{content:'Exact criterion learner source'});rubric=await context.command('teacher',`/v1/submissions/${rubricSource.id}/results`,{nativeResult:{type:'rubric',rubricId:definition.id,criteria:[{criterionKey:'explanation',levelKey:'shown'}]},feedback:'Criterion recorded natively.',expectedPolicyVersion:3,expectedRevision:0,sourceEvidence:true});
  selections=[{markingId:numeric.id,submissionId:source.id,expectedRevision:1,expectedSubmissionRevision:1,expectedPolicyVersion:2,parentVisible:true},{markingId:rubric.id,submissionId:rubricSource.id,expectedRevision:1,expectedSubmissionRevision:1,expectedPolicyVersion:3,parentVisible:false}];
 },30000);
 afterAll(async()=>{await context?.close();});
 it('shows named bounded native cells, missing work and exact protected source details',async()=>{
  const grid=await context.request('teacher',`/v1/courses/${courseId}/gradebook?learnerLimit=1&assessmentLimit=1`);expect(grid.statusCode,grid.body).toBe(200);expect(grid.json()).toMatchObject({courseId,courseTitle:'Current class gradebook',learnerTotal:Object.values(customerRoles).filter(actor=>actor>=12&&actor<72).length,assessmentTotal:2});expect(grid.json().items).toHaveLength(1);expect(grid.json().assessments).toHaveLength(1);expect(grid.json().nextLearnerCursor).toEqual(expect.any(String));expect(grid.json().nextAssessmentCursor).toEqual(expect.any(String));expect(grid.body).not.toContain('Exact numeric learner source');
  const full=await context.request('teacher',`/v1/courses/${courseId}/gradebook?learnerLimit=25&assessmentLimit=10`);expect(full.statusCode,full.body).toBe(200);const cells=full.json().items.flatMap((row:{cells:Record<string,unknown>[]})=>row.cells);expect(cells.some((cell:{state:string;nativeResult?:{score?:number}})=>cell.state==='REVIEW'&&cell.nativeResult?.score===0)).toBe(true);expect(cells.some((cell:{state:string;nativeResult:unknown})=>cell.state==='NO_SUBMISSION'&&cell.nativeResult===null)).toBe(true);
  const detail=await context.request('teacher',`/v1/submissions/${selections[0].submissionId}/gradebook-source`);expect(detail.statusCode,detail.body).toBe(200);expect(detail.json()).toMatchObject({content:'Exact numeric learner source',currentResult:{id:numeric.id,status:'REVIEW',score:0}});
  for(const role of ['otherTeacher','strong','parent','coordinator']as const)expect((await context.request(role,`/v1/courses/${courseId}/gradebook?learnerLimit=25&assessmentLimit=10`)).statusCode).toBe(403);
  expect((await context.request('otherTeacher',`/v1/submissions/${selections[0].submissionId}/gradebook-source`)).statusCode).toBe(403);
 });
 it('preview is read only and one stale selection makes the whole confirmed batch roll back',async()=>{
  const preview=await context.request('teacher',`/v1/courses/${courseId}/gradebook/preview`,{selections});expect(preview.statusCode,preview.body).toBe(200);expect(preview.json().items).toHaveLength(2);expect(preview.json().items[0]).toMatchObject({nativeResult:{type:'numeric',score:0},referenceTitle:'Synthetic explanation objective'});expect(preview.json().items[1].nativeResult).toMatchObject({type:'rubric',normalized:null});
  const before=(await context.client.query('select count(*)::integer count from app.result_revisions where school_id=$1',[context.school])).rows[0].count;
  const failed=await context.request('teacher',`/v1/courses/${courseId}/gradebook/release`,{selections:[selections[0],{...selections[1],expectedRevision:2}],confirmRelease:true});expect(failed.statusCode,failed.body).toBe(409);
  expect((await context.client.query('select count(*)::integer count from app.result_revisions where school_id=$1',[context.school])).rows[0].count).toBe(before);expect((await context.client.query('select count(*)::integer count from app.rubric_result_revisions where school_id=$1',[context.school])).rows[0].count).toBe(0);expect((await context.client.query("select count(*)::integer count from internal.outbox_events where school_id=$1 and type in('result.released','rubric.result.released')",[context.school])).rows[0].count).toBe(0);
  const scopeLost=await context.request('otherTeacher',`/v1/courses/${courseId}/gradebook/release`,{selections,confirmRelease:true});expect(scopeLost.statusCode).toBe(403);
  await context.client.query("update app.people set display_name=(select display_name from app.people where school_id=$1 and actor_id='20000000-0000-4000-8000-000000000012')where school_id=$1 and actor_id='20000000-0000-4000-8000-000000000013'",[context.school]);
  const singleRow=await context.request('teacher',`/v1/courses/${courseId}/gradebook?learnerLimit=1&assessmentLimit=1`);expect(singleRow.statusCode,singleRow.body).toBe(200);expect(singleRow.json().items[0].identityRequiresReview).toBe(true);
  const identityDenied=await context.request('teacher',`/v1/courses/${courseId}/gradebook/release`,{selections,confirmRelease:true});expect(identityDenied.statusCode,identityDenied.body).toBe(409);
  expect((await context.client.query('select count(*)::integer count from app.result_revisions where school_id=$1',[context.school])).rows[0].count).toBe(before);
  await context.client.query("update app.people set display_name='Unique gradebook learner'where school_id=$1 and actor_id='20000000-0000-4000-8000-000000000013'",[context.school]);
  await context.client.query("update app.enrollments set effective_to=now()-interval '1 minute'where school_id=$1 and class_id=$2 and student_actor_id='20000000-0000-4000-8000-000000000013'",[context.school,context.classId]);
  const withdrawn=await context.request('teacher',`/v1/courses/${courseId}/gradebook/release`,{selections,confirmRelease:true});expect(withdrawn.statusCode,withdrawn.body).toBe(403);
  expect((await context.client.query('select count(*)::integer count from app.result_revisions where school_id=$1',[context.school])).rows[0].count).toBe(before);
  await context.client.query("update app.enrollments set effective_to=null where school_id=$1 and class_id=$2 and student_actor_id='20000000-0000-4000-8000-000000000013'",[context.school,context.classId]);
 });
 it('releases mixed native drafts once with per-source sharing and retains released values during later review',async()=>{
  const key=randomUUID();const body={selections,confirmRelease:true};const receipt=await context.request('teacher',`/v1/courses/${courseId}/gradebook/release`,body,key);expect(receipt.statusCode,receipt.body).toBe(200);expect(receipt.json().items).toHaveLength(2);
  const replay=await context.request('teacher',`/v1/courses/${courseId}/gradebook/release`,body,key);expect(replay.statusCode,replay.body).toBe(200);expect(replay.json()).toEqual(receipt.json());
  expect((await context.client.query("select count(*)::integer count from internal.outbox_events where school_id=$1 and type in('result.released','rubric.result.released')",[context.school])).rows[0].count).toBe(2);expect((await context.client.query("select count(*)::integer count from internal.audit_events where school_id=$1 and action='result.release'",[context.school])).rows[0].count).toBe(2);
  const parent=await context.request('parent','/v1/results?limit=100');expect(parent.statusCode).toBe(200);expect(parent.json().items).toHaveLength(1);expect(parent.json().items[0]).toMatchObject({model:'numeric',score:0});
  await context.command('teacher',`/v1/submissions/${selections[0].submissionId}/results`,{score:3,feedback:'New reviewed correction draft.',expectedPolicyVersion:2,expectedRevision:1,sourceEvidence:true});
  const grid=await context.request('teacher',`/v1/courses/${courseId}/gradebook?learnerLimit=25&assessmentLimit=10`);expect(grid.statusCode,grid.body).toBe(200);const cell=grid.json().items.flatMap((row:{cells:Record<string,unknown>[]})=>row.cells).find((value:{submissionId:string})=>value.submissionId===selections[0].submissionId);expect(cell).toMatchObject({state:'REVIEW',nativeResult:{score:3},releasedResult:{nativeResult:{score:0}}});
 });
});
