import{afterAll,beforeAll,describe,expect,it}from'vitest';import{config as dotenv}from'dotenv';import{Database}from'../../src/platform/database/database';import{createCustomerContext,customerActor,customerCourse,customerReleased,type CustomerContext}from'./customer-test-context';
dotenv({path:'.env.local',quiet:true});
const budgetManifest={version:'teacher-insight-1',purpose:'NEXT_LEARNING_ACTION',capabilities:['GROUNDED_EXPLANATION','RECOMMENDATION'],mode:'LIVE',provider:'azure-foundry',model:'configured-no-call',promptId:'next-learning-action',promptVersion:'2',promptDigest:'1f892110e486d0f8117e53ef9d9cf0a884b7c155821dd8eb1284cef22b9f0de4',promptSource:'SOURCE_CONTROLLED_TASK_POLICY',promptEffectiveAt:'2026-10-02T00:00:00Z',evaluationVersion:'source-78-checked-evidence-1',dataClassification:'SCHOOL_CUSTOM_NUMERIC',providerDataPolicy:'SYNTHETIC_ONLY',maxOutputTokens:1000,timeoutMs:30000,maxCost:1};
const approveBudgetExecution=(database:Database,school:string)=>database.actorTransaction(customerActor(1),school,async client=>{await client.query('select internal.approve_intelligence_execution($1::jsonb,$2)',[JSON.stringify(budgetManifest),'explicit-no-model-budget-fixture']);});
describe.skipIf(process.env.CUEVO_REQUIRE_INTEGRATION!=='1')('shared live reservations without model execution',()=>{
 let context:CustomerContext;let db:Database;beforeAll(async()=>{context=await createCustomerContext({committed:true});db=new Database(process.env.DATABASE_URL);await context.client.query('update app.intelligence_policies set live_enabled=true where school_id=$1',[context.school]);},60000);afterAll(async()=>{await db?.close();await context?.close();});
 it('requires administrator approval and atomically enforces same-actor daily reservation ceilings',async()=>{
  const input={currency:'USD',schoolDailyLimit:1,actorDailyLimit:1,maxConcurrentRuns:2,expectedVersion:0,confirmApproval:true,reason:'Synthetic budget contention only; no provider call.'};
  expect((await context.request('teacher','/v1/intelligence/budget',input)).statusCode).toBe(403);await context.command('admin','/v1/intelligence/budget',input);
  await approveBudgetExecution(db,context.school);
  const course=await customerCourse(context,'Reservation contention');const baseline=await customerReleased(context,'strong',course.courseId,'Current budget source',3);await context.drain();
  const reserve=(key:string)=>db.actorTransaction(customerActor(4),context.school,async client=>(await client.query('select internal.begin_teacher_insight_run($1,$2,$3,$4::jsonb,$5)as run',[key,'a'.repeat(64),baseline.resultId,JSON.stringify({mode:'LIVE',provider:'azure-foundry',model:'configured-no-call',promptId:'next-learning-action',promptVersion:'2',promptDigest:'1f892110e486d0f8117e53ef9d9cf0a884b7c155821dd8eb1284cef22b9f0de4',policyVersion:1,timeoutMs:30000,maxTokens:1000,maxCost:1,costBasis:'BUDGET_RESERVATION',syntheticOnly:true,executionManifest:budgetManifest,globalDailyBudget:1000000}),'budget-fixture'])).rows[0].run);
  const result=await Promise.allSettled([reserve('budget-a'),reserve('budget-b')]);expect(result.filter(item=>item.status==='fulfilled')).toHaveLength(1);expect(result.filter(item=>item.status==='rejected')).toHaveLength(1);
  const status=await context.request('admin','/v1/intelligence/budget');expect(status.statusCode).toBe(200);expect(status.json()).toMatchObject({currency:'USD',schoolReserved:1,billedCost:null});
  const row=(await context.client.query('select run_id from internal.intelligence_budget_reservations where school_id=$1',[context.school])).rows[0];const run=(await context.client.query('select command_key,lease_token from app.intelligence_runs where school_id=$1 and id=$2',[context.school,row.run_id])).rows[0];
  expect((await reserve(run.command_key)).state).toBe('IN_PROGRESS');expect((await context.client.query('select count(*)::integer count from internal.intelligence_budget_reservations where school_id=$1',[context.school])).rows[0].count).toBe(1);
  await db.actorTransaction(customerActor(4),context.school,async client=>{await client.query('select internal.fail_intelligence_run($1,$2,$3,$4)',[row.run_id,run.lease_token,'INTELLIGENCE_TIMEOUT','budget-fixture-timeout']);});
  expect((await context.request('admin','/v1/intelligence/budget')).json().schoolReserved).toBe(1);
  await expect(reserve('budget-after-timeout')).rejects.toBeDefined();expect((await context.client.query('select count(*)::integer count from app.recommendations where school_id=$1',[context.school])).rows[0].count).toBe(0);
 });
 it('serializes a shared school cap across different authorized actors',async()=>{
  const school=await createCustomerContext({committed:true});try{
   await school.client.query('update app.intelligence_policies set live_enabled=true where school_id=$1',[school.school]);
   await school.command('admin','/v1/intelligence/budget',{currency:'USD',schoolDailyLimit:1,actorDailyLimit:1,maxConcurrentRuns:10,expectedVersion:0,confirmApproval:true,reason:'Explicit cross-actor synthetic reservation case.'});
   await approveBudgetExecution(db,school.school);
   const course=await customerCourse(school,'Shared actors');const baseline=await customerReleased(school,'strong',course.courseId,'Shared school budget source',3);await school.drain();
   for(const actor of[4,1])expect(await db.actorTransaction(customerActor(actor),school.school,async client=>(await client.query('select "authorization".can_manage_baseline($1,$2)as allowed',[school.school,baseline.resultId])).rows[0].allowed),`Actor ${actor} must be authorized for the exact shared source`).toBe(true);
   const reserve=(actor:number)=>db.actorTransaction(customerActor(actor),school.school,async client=>(await client.query('select internal.begin_teacher_insight_run($1,$2,$3,$4::jsonb,$5)as run',[`shared-actor-${actor}`,'a'.repeat(64),baseline.resultId,JSON.stringify({mode:'LIVE',provider:'azure-foundry',model:'configured-no-call',promptId:'next-learning-action',promptVersion:'2',promptDigest:'1f892110e486d0f8117e53ef9d9cf0a884b7c155821dd8eb1284cef22b9f0de4',policyVersion:1,timeoutMs:30000,maxTokens:1000,maxCost:1,costBasis:'BUDGET_RESERVATION',syntheticOnly:true,executionManifest:budgetManifest,globalDailyBudget:1000000}),'cross-actor-budget'])).rows[0].run);
   const results=await Promise.allSettled([reserve(4),reserve(1)]);expect(results.filter(value=>value.status==='fulfilled')).toHaveLength(1);const denied=results.find(value=>value.status==='rejected')as PromiseRejectedResult;expect(denied.reason).toMatchObject({code:'22023',message:'Live reservation budget exceeded'});
   expect((await school.request('admin','/v1/intelligence/budget')).json().schoolReserved).toBe(1);
  }finally{await school.close();}
 },60000);
 it('enforces a global cap across synthetic schools and a separate outstanding-run limit',async()=>{
  const first=await createCustomerContext({committed:true});const second=await createCustomerContext({committed:true});try{
   for(const school of[first,second]){await school.client.query('update app.intelligence_policies set live_enabled=true where school_id=$1',[school.school]);await school.command('admin','/v1/intelligence/budget',{currency:'USD',schoolDailyLimit:10,actorDailyLimit:10,maxConcurrentRuns:1,expectedVersion:0,confirmApproval:true,reason:'Global and concurrency synthetic boundary; no model call.'});await approveBudgetExecution(db,school.school);}
   const firstCourse=await customerCourse(first,'Global first');const firstBaseline=await customerReleased(first,'strong',firstCourse.courseId,'Global first source',3);await first.drain();
   const secondCourse=await customerCourse(second,'Global second');const secondBaseline=await customerReleased(second,'strong',secondCourse.courseId,'Global second source',3);await second.drain();
   const used=Number((await first.client.query("select coalesce(sum(max_cost),0)as amount from app.intelligence_runs where generation_mode='LIVE'and(created_at at time zone 'UTC')::date=(clock_timestamp()at time zone 'UTC')::date")).rows[0].amount);
   const reserve=(school:CustomerContext,baseline:string,key:string,global:number)=>db.actorTransaction(customerActor(4),school.school,async client=>(await client.query('select internal.begin_teacher_insight_run($1,$2,$3,$4::jsonb,$5)as run',[key,'a'.repeat(64),baseline,JSON.stringify({mode:'LIVE',provider:'azure-foundry',model:'configured-no-call',promptId:'next-learning-action',promptVersion:'2',promptDigest:'1f892110e486d0f8117e53ef9d9cf0a884b7c155821dd8eb1284cef22b9f0de4',policyVersion:1,timeoutMs:30000,maxTokens:1000,maxCost:1,costBasis:'BUDGET_RESERVATION',syntheticOnly:true,executionManifest:budgetManifest,globalDailyBudget:global}),'global-budget'])).rows[0].run);
   const results=await Promise.allSettled([reserve(first,firstBaseline.resultId,'global-first',used+1),reserve(second,secondBaseline.resultId,'global-second',used+1)]);expect(results.filter(value=>value.status==='fulfilled')).toHaveLength(1);expect((results.find(value=>value.status==='rejected')as PromiseRejectedResult).reason).toMatchObject({code:'22023'});
   const index=results.findIndex(value=>value.status==='fulfilled');const school=index===0?first:second;const baseline=index===0?firstBaseline:secondBaseline;const active=(results[index]as PromiseFulfilledResult<{runId:string;leaseToken:string}>).value;
   await expect(reserve(school,baseline.resultId,'concurrency-denied',1000000)).rejects.toMatchObject({code:'22023'});
   await db.actorTransaction(customerActor(4),school.school,async client=>{await client.query('select internal.fail_intelligence_run($1,$2,$3,$4)',[active.runId,active.leaseToken,'INTELLIGENCE_TIMEOUT','concurrency-close']);});
   expect((await reserve(school,baseline.resultId,'after-concurrency-close',1000000)).state).toBe('NEW');expect((await school.request('admin','/v1/intelligence/budget')).json().schoolReserved).toBe(2);
  }finally{await second.close();await first.close();}
 },60000);
});
