import{afterAll,beforeAll,describe,it,expect}from'vitest';import{createCustomerContext,customerCourse,customerReleased,customerActor,type CustomerContext}from'./customer-test-context';
describe.skipIf(process.env.CUEVO_REQUIRE_INTEGRATION!=='1')('learner portfolio organization and requested feedback',()=>{
 let context:CustomerContext;let itemId:string;let revisionId:string;let collectionId:string;let requestId:string;const feedbackKey='portfolio-exact-feedback-replay';
 beforeAll(async()=>{context=await createCustomerContext();const course=await customerCourse(context,'Organized portfolio source');const released=await customerReleased(context,'strong',course.courseId,'Selected explanation',5);const selected=await context.command('strong','/v1/portfolio/items',{sourceModel:'numeric',evidenceId:released.evidenceId,title:'School selected checking',reflection:'I explained one school check.'});itemId=selected.id;revisionId=String(selected.revisionId);},30000);afterAll(async()=>{await context?.close();});
 it('owns collections and exact source placement without duplicating evidence or sharing authority',async()=>{
  collectionId=(await context.command('strong','/v1/portfolio/collections',{title:'Checking explanations',description:'My selected school examples.'})).id;await context.command('strong',`/v1/portfolio/items/${itemId}/placement`,{collectionId,expectedRevision:0,position:2});const placement=await context.request('strong',`/v1/portfolio/items/${itemId}/placement`);expect(placement.statusCode,placement.body).toBe(200);expect(placement.json()).toMatchObject({collectionId,revision:1,position:2});
  expect((await context.request('strong','/v1/portfolio/collections',{title:'Checking explanations',description:'An ambiguous duplicate name.'})).statusCode).toBe(409);
  expect((await context.request('strong',`/v1/portfolio/items/${itemId}/placement`,{collectionId:false,expectedRevision:1,position:1})).statusCode).toBe(400);
  const collection=await context.request('strong',`/v1/portfolio/collections/${collectionId}/items?limit=25`);expect(collection.statusCode,collection.body).toBe(200);expect(collection.json().items).toMatchObject([{id:itemId,title:'School selected checking',position:2}]);
  expect((await context.request('observed',`/v1/portfolio/items/${itemId}/placement`,{collectionId,expectedRevision:1,position:1})).statusCode).toBe(403);expect((await context.request('parent','/v1/portfolio/collections?limit=25')).statusCode).toBe(403);
  expect((await context.request('strong',`/v1/portfolio/items/${itemId}/placement`,{collectionId:null,expectedRevision:0,position:1})).statusCode).toBe(409);expect((await context.client.query('select count(*)::integer count from app.portfolio_items where school_id=$1',[context.school])).rows[0].count).toBe(1);
 });
 it('requests current exact reflection feedback and admits only its authorized teacher source',async()=>{
  // This case tests requested-source authority; duplicate learner identities are covered separately.
  const confirmedNames=(await context.client.query<{actor_id:string;display_name:string}>('update app.people set display_name=case when actor_id=$2 then $4 else $5 end where school_id=$1 and actor_id in($2,$3)and synthetic is true returning actor_id,display_name',[context.school,customerActor(12),customerActor(13),'Lina Al-Kuwari','Omar Al-Kuwari'])).rows.sort((left,right)=>left.actor_id.localeCompare(right.actor_id));
  expect(confirmedNames).toEqual([{actor_id:customerActor(12),display_name:'Lina Al-Kuwari'},{actor_id:customerActor(13),display_name:'Omar Al-Kuwari'}]);
  expect(new Set(confirmedNames.map(person=>person.display_name)).size).toBe(2);
  requestId=(await context.command('strong',`/v1/portfolio/items/${itemId}/feedback-request`,{revisionId,expectedRevision:1,message:'Please review my school checking explanation.',confirmRequest:true},feedbackKey)).id;
  const queue=await context.request('teacher','/v1/portfolio/feedback-requests?limit=25');expect(queue.statusCode,queue.body).toBe(200);expect(queue.json().items).toMatchObject([{id:requestId,itemId,revisionId,state:'PENDING'}]);const other=await context.request('otherTeacher','/v1/portfolio/feedback-requests?limit=25');expect(other.statusCode).toBe(200);expect(other.json().items).toEqual([]);
  const work=await context.request('teacher',`/v1/portfolio/feedback-requests/${requestId}/source-work`);expect(work.statusCode,work.body).toBe(200);expect(work.json()).toMatchObject({requestId,itemId,revisionId,reflection:'I explained one school check.',work:{source:{kind:'TEXT'}}});expect((await context.request('otherTeacher',`/v1/portfolio/feedback-requests/${requestId}/source-work`)).statusCode).toBe(403);
  await context.client.query("update app.enrollments set status='revoked'where school_id=$1 and class_id=$2 and student_actor_id=$3",[context.school,context.classId,customerActor(12)]);
  expect((await context.request('teacher','/v1/portfolio/feedback-requests?limit=25')).json().items).toEqual([]);expect((await context.request('strong','/v1/portfolio/feedback-requests?limit=25')).json().items).toEqual([]);
  expect((await context.request('teacher',`/v1/portfolio/feedback-requests/${requestId}/source-work`)).statusCode).toBe(403);
  await context.client.query("update app.enrollments set status='active'where school_id=$1 and class_id=$2 and student_actor_id=$3",[context.school,context.classId,customerActor(12)]);
  const portfolio=await context.request('teacher','/v1/portfolio/items?limit=100');expect(portfolio.statusCode).toBe(200);expect(portfolio.json().items.find((item:{id:string})=>item.id===itemId)).toMatchObject({id:itemId,revisionId,learnerId:customerActor(12),identity:{status:'READY',learnerName:'Lina Al-Kuwari'}});
  await context.command('teacher',`/v1/portfolio/items/${itemId}/review`,{expectedRevision:1,feedback:'The checking explanation is reviewed.',featured:false,parentVisible:false,confirmSourceReview:true,confirmParentApproval:false});expect((await context.request('teacher','/v1/portfolio/feedback-requests?limit=25')).json().items).toEqual([]);
  expect((await context.command('strong',`/v1/portfolio/items/${itemId}/feedback-request`,{revisionId,expectedRevision:1,message:'Please review my school checking explanation.',confirmRequest:true},feedbackKey)).id).toBe(requestId);
  expect((await context.request('strong',`/v1/portfolio/items/${itemId}/feedback-request`,{revisionId,expectedRevision:1,message:'Already reviewed request must not disappear silently.',confirmRequest:true})).statusCode).toBe(409);
 });
 it('requires the selected current revision and keeps placement/feedback history immutable',async()=>{
  const updated=await context.command('strong',`/v1/portfolio/items/${itemId}/reflection`,{title:'New school reflection',reflection:'I revised the school explanation.',expectedRevision:1});expect((await context.request('strong',`/v1/portfolio/items/${itemId}/feedback-request`,{revisionId,expectedRevision:1,message:'Cannot request stale source.',confirmRequest:true})).statusCode).toBe(409);
  const next=await context.command('strong',`/v1/portfolio/items/${itemId}/feedback-request`,{revisionId:updated.revisionId,expectedRevision:2,message:'Review my revised school reflection.',confirmRequest:true});expect(next.id).not.toBe(requestId);expect((await context.request('teacher',`/v1/portfolio/feedback-requests/${requestId}/source-work`)).statusCode).toBe(403);await context.drain();const events=(await context.client.query("select event.state,exists(select 1 from internal.processed_events processed where processed.event_id=event.id)as processed from internal.outbox_events event where event.school_id=$1 and event.type='portfolio.organization.changed'",[context.school])).rows;expect(events.length).toBeGreaterThanOrEqual(4);expect(events.every(event=>event.state==='COMPLETED'&&event.processed)).toBe(true);
 });
});
