import'reflect-metadata';import{afterAll,beforeAll,describe,it,expect}from'vitest';import{Module}from'@nestjs/common';import{NestFactory}from'@nestjs/core';import{FastifyAdapter,type NestFastifyApplication}from'@nestjs/platform-fastify';import{createClient}from'@supabase/supabase-js';import{readFileSync}from'node:fs';import{randomUUID}from'node:crypto';import{config as dotenv}from'dotenv';import{Pool}from'pg';
import{Database}from'../../src/platform/database/database';import{IdentityService,type MembershipRow}from'../../src/platform/identity/identity.service';import{createUserVerifier}from'../../src/platform/identity/supabase-auth';import{createSchoolLearningController}from'../../src/modules/school-learning/learning.controller';import{createAcademicController}from'../../src/modules/academic/academic.controller';import{createPortfolioController}from'../../src/modules/portfolio/portfolio.controller';import{createDevelopmentController}from'../../src/modules/development/development.controller';import{parseServerConfig}from'@cuevo/config';
dotenv({path:'.env.local',quiet:true});const config=parseServerConfig(process.env);const enabled=process.env.CUEVO_REQUIRE_INTEGRATION==='1'&&Boolean(config.databaseUrl&&config.supabaseUrl&&new URL(config.supabaseUrl).hostname==='127.0.0.1');if(process.env.CUEVO_REQUIRE_INTEGRATION==='1'&&!enabled)throw Error('Cuevo local required');
describe.skipIf(!enabled)('portfolio approved revisions and observed recognition actual API',()=>{
 let app:NestFastifyApplication;let db:Database;let admin:Pool;const tokens:Record<string,string>={};const school='10000000-0000-4000-8000-000000000001';
 beforeAll(async()=>{const accounts=(JSON.parse(readFileSync('supabase/seed/identities.json','utf8'))as{actors:{actorId:string;email:string}[]}).actors;const password=(JSON.parse(readFileSync('.local/runtime-secrets.json','utf8'))as{syntheticPassword:string}).syntheticPassword;for(const[role,suffix]of Object.entries({teacher:'004',student:'012',parent:'072',admin:'001',peer:'013'})){const actor=accounts.find(a=>a.actorId.endsWith(suffix))!;const auth=createClient(config.supabaseUrl!,config.supabasePublishableKey!,{auth:{persistSession:false,autoRefreshToken:false}});const session=await auth.auth.signInWithPassword({email:actor.email,password});if(!session.data.session)throw Error('Synthetic auth failed');tokens[role]=session.data.session.access_token;}
 const url=new URL(config.databaseUrl!);if(url.port!=='56322'||url.hostname!=='127.0.0.1')throw Error('Cuevo local required');url.username='postgres';url.password='postgres';admin=new Pool({connectionString:url.toString()});await admin.query("insert into app.entitlements(school_id,code,enabled,effective_from)values($1,'portfolio',true,'2026-09-01')on conflict(school_id,code)do update set enabled=true",[school]);db=new Database(config.databaseUrl);const identity=new IdentityService({verifyUser:createUserVerifier(config),currentMemberships:a=>db.actorTransaction(a,undefined,async c=>(await c.query<MembershipRow>('select*from "authorization".current_memberships()')).rows),isCurrentSession:(a,s)=>db.actorTransaction(a,undefined,async c=>Boolean((await c.query('select "authorization".is_current_session($1)active',[s])).rows[0]?.active))});@Module({controllers:[createSchoolLearningController(identity,db),createAcademicController(identity,db),createPortfolioController(identity,db),createDevelopmentController(identity,db)]})class App{}app=await NestFactory.create<NestFastifyApplication>(App,new FastifyAdapter({logger:false}),{logger:false});await app.init();await app.getHttpAdapter().getInstance().ready();},30000);
 afterAll(async()=>{await app?.close();await db?.close();await admin?.end();});const request=(role:string,url:string,payload?:Record<string,unknown>,key=randomUUID())=>app.inject({method:payload===undefined?'GET':'POST',url,headers:{authorization:`Bearer ${tokens[role]}`,'x-school-id':school,'idempotency-key':key},payload});const command=async(role:string,url:string,payload:Record<string,unknown>,key=randomUUID())=>{const r=await request(role,url,payload,key);expect(r.statusCode,r.body).toBe(200);return r.json();};
 it('preserves parent approved reflection after learner edit and revokes future reads',async()=>{
 const course=await command('teacher','/v1/courses',{classId:'30000000-0000-4000-8000-000000000001',subjectId:'43000000-0000-4000-8000-000000000001',title:'Portfolio synthetic verification',description:'Synthetic'});await command('teacher',`/v1/courses/${course.id}/publish`,{});const assessment=await command('teacher','/v1/assessments',{courseId:course.id,title:'Selected work',instructions:'School task',maxScore:10});await command('teacher',`/v1/assessments/${assessment.id}/reference`,{referenceId:'61000000-0000-4000-8000-000000000001',expectedPolicyVersion:1});const submission=await command('student',`/v1/assessments/${assessment.id}/submissions`,{content:'Original selected work'});const marking=await command('teacher',`/v1/submissions/${submission.id}/results`,{score:0,feedback:'Human reviewed',expectedPolicyVersion:2,expectedRevision:0,sourceEvidence:true});const result=await command('teacher',`/v1/results/${marking.id}/release`,{expectedRevision:1,parentVisible:true});const key=randomUUID();const body={sourceModel:'numeric',evidenceId:result.evidenceId,title:'My explanation',reflection:'Initial reflection'};const selected=await command('student','/v1/portfolio/items',body,key);expect((await request('student','/v1/portfolio/items',body,key)).json()).toEqual(selected);await command('teacher',`/v1/portfolio/items/${selected.id}/review`,{expectedRevision:1,feedback:'Teacher portfolio feedback',featured:true,parentVisible:true,confirmParentApproval:true,confirmSourceReview:true});await command('student',`/v1/portfolio/items/${selected.id}/reflection`,{title:'Edited reflection',reflection:'New unapproved reflection',expectedRevision:1});
 const parent=await request('parent','/v1/portfolio/items?limit=100');expect(parent.statusCode,parent.body).toBe(200);const parentItem=parent.json().items.find((i:{id:string})=>i.id===selected.id);expect(parentItem).toMatchObject({revision:1,reflection:'Initial reflection',feedback:'Teacher portfolio feedback'});const own=await request('student','/v1/portfolio/items?limit=100');expect(own.json().items.find((i:{id:string})=>i.id===selected.id)).toMatchObject({revision:2,reflection:'New unapproved reflection',approvalState:'AWAITING_REVIEW'});const peer=await request('peer','/v1/portfolio/items?limit=100');expect(peer.json().items.some((i:{id:string})=>i.id===selected.id)).toBe(false);await command('teacher',`/v1/portfolio/items/${selected.id}/parent-revoke`,{reason:'School reviewed visibility'});expect((await request('parent','/v1/portfolio/items?limit=100')).json().items.some((i:{id:string})=>i.id===selected.id)).toBe(false);
 },30000);
 it('requires admin policy and explicit class-period opt-in with no client point grant',async()=>{
 const bad=await request('student','/v1/development/policies',{expectedVersion:0,points:{practice:5,revision:5,reflection:3},milestones:[],confirmApproval:true});expect(bad.statusCode).toBe(403);expect((await request('parent','/v1/development/summary')).statusCode).toBe(403);
 const summary=await request('student','/v1/development/summary');expect(summary.statusCode,summary.body).toBe(200);expect(summary.json()).toHaveProperty('status');expect(summary.json()).not.toHaveProperty('grade');
 });
});
