import 'reflect-metadata';
import { createHash, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { isAbsolute } from 'node:path';
import { Pool, type PoolClient } from 'pg';
import { Module } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, type NestFastifyApplication } from '@nestjs/platform-fastify';
import { createClient } from '@supabase/supabase-js';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { thinkingFocusResponseSchema, thinkingFocusSnapshotSchema } from '@cuevo/contracts';
import type { Database } from '../../src/platform/database/database';
import { IdentityService, type MembershipRow } from '../../src/platform/identity/identity.service';
import { createUserVerifier } from '../../src/platform/identity/supabase-auth';
import { createSchoolLearningController } from '../../src/modules/school-learning/learning.controller';
import { createLearningContentController } from '../../src/modules/school-learning/content.controller';
import { createThinkingFocusController } from '../../src/modules/school-learning/thinking-focus.controller';
import { createAcademicController } from '../../src/modules/academic/academic.controller';
import { createLearningResourceController } from '../../src/modules/school-learning/resource.controller';
import { isolatedThinkingFocusRuntime, standardThinkingFocusRuntime, thinkingFocusTestMode, readThinkingFocusJson } from './thinking-focus-test-runtime';
import { withFixtureCleanup } from './fixture-cleanup';

const runtimeMode=thinkingFocusTestMode(process.env);
const enabled=runtimeMode!==null;
const actors={admin:1,coordinator:2,teacher:4,wrongTeacher:5,student:12,parent:72} as const;
type Role=keyof typeof actors;
type Row=Record<string,unknown>&{id:string};
const actorId=(role:Role)=>`20000000-0000-4000-8000-${String(actors[role]).padStart(12,'0')}`;
const focus={taxonomyVersion:'revised-bloom-2001-cuevo-v1',primaryProcess:'APPLY',additionalProcesses:['UNDERSTAND']};

describe.skipIf(!enabled)('reviewed thinking focus — real Auth/controllers/Postgres',()=>{
  let owner:Pool;let client:PoolClient;let app:NestFastifyApplication;const school=randomUUID(),classId=randomUUID(),subject=randomUUID(),year=randomUUID(),group=randomUUID();let referenceId:string;let beforeReviewDownload:(()=>Promise<void>)|null=null;
  const tokens:Partial<Record<Role,string>>={};
  beforeAll(async()=>{
    const actorIds=Object.fromEntries((Object.keys(actors)as Role[]).map(role=>[role,actorId(role)]));
    const path=process.env.CUEVO_THINKING_FOCUS_TEST_RUNTIME;
    if(runtimeMode==='ISOLATED'&&(!path||!isAbsolute(path)))throw Error('Explicit absolute isolated thinking-focus runtime file required.');
    const runtime=runtimeMode==='ISOLATED'?isolatedThinkingFocusRuntime(path,await readThinkingFocusJson(()=>readFile(path??'','utf8')),actorIds):standardThinkingFocusRuntime(process.env,await readThinkingFocusJson(()=>readFile('supabase/seed/identities.json','utf8')),await readThinkingFocusJson(()=>readFile('.local/runtime-secrets.json','utf8')),actorIds);
    const config=runtime.config;
    owner=new Pool({connectionString:runtime.ownerDatabaseUrl,max:1});client=await owner.connect();
    for(const role of Object.keys(actors)as Role[]){const account=runtime.accounts.find(row=>row.actorId===actorId(role));if(!account)throw Error('Verified synthetic identity missing.');const auth=createClient(config.supabaseUrl!,config.supabasePublishableKey!,{auth:{persistSession:false,autoRefreshToken:false}});const login=await auth.auth.signInWithPassword({email:account.email,password:account.password});if(!login.data.session||login.data.user?.id!==actorId(role))throw Error('Verified synthetic sign-in failed.');tokens[role]=login.data.session.access_token;}
    await client.query('BEGIN');
    await client.query("insert into app.schools(id,name,country_code)values($1,'Thinking focus integration rollback school','QA')",[school]);
    for(const role of Object.keys(actors)as Role[]){await client.query("insert into app.memberships(school_id,actor_id,role,effective_from)values($1,$2,$3,now()-interval '1 day')",[school,actorId(role),role==='wrongTeacher'?'teacher':role]);await client.query('insert into app.people(school_id,actor_id,display_name,synthetic)values($1,$2,$3,true)',[school,actorId(role),`Reviewed ${role}`]);}
    for(const code of ['school.context','learning','assessment','curriculum','learner.state'])await client.query("insert into app.entitlements(school_id,code,enabled,effective_from)values($1,$2,true,now()-interval '1 day')",[school,code]);
    await client.query("insert into app.academic_years(school_id,id,name,starts_on,ends_on)values($1,$2,'Reviewed year','2026-01-01','2027-12-31')",[school,year]);await client.query("insert into app.year_groups(school_id,id,name,ordinal)values($1,$2,'Reviewed year group',1)",[school,group]);
    await client.query("insert into app.classes(school_id,id,academic_year_id,year_group_id,name)values($1,$2,$3,$4,'Reviewed class')",[school,classId,year,group]);await client.query("insert into app.subjects(school_id,id,name)values($1,$2,'Reviewed subject')",[school,subject]);
    await client.query("insert into app.teacher_assignments(school_id,class_id,subject_id,teacher_actor_id,effective_from)values($1,$2,$3,$4,now()-interval '1 day')",[school,classId,subject,actorId('teacher')]);
    await client.query("insert into app.enrollments(school_id,class_id,student_actor_id,effective_from)values($1,$2,$3,now()-interval '1 day')",[school,classId,actorId('student')]);await client.query("insert into app.parent_relationships(school_id,parent_actor_id,student_actor_id,relationship_type,effective_from)values($1,$2,$3,'parent',now()-interval '1 day')",[school,actorId('parent'),actorId('student')]);
    const database={actorTransaction:async<T>(actor:string,selectedSchool:string|undefined,run:(connection:PoolClient)=>Promise<T>)=>{await client.query('SAVEPOINT thinking_request');await client.query('set local role cuevo_api');try{await client.query("set local statement_timeout='5s'");await client.query("select set_config('app.actor_id',$1,true),set_config('app.school_id',$2,true)",[actor,selectedSchool??'']);const result=await run(client);await client.query('reset role');await client.query("set local statement_timeout='0'");await client.query('RELEASE SAVEPOINT thinking_request');return result;}catch(error){await client.query('ROLLBACK TO SAVEPOINT thinking_request');await client.query('reset role');await client.query('RELEASE SAVEPOINT thinking_request');throw error;}}}as unknown as Database;
    const identity=new IdentityService({verifyUser:createUserVerifier(config),currentMemberships:actor=>database.actorTransaction(actor,undefined,async c=>(await c.query<MembershipRow>('select *from "authorization".current_memberships()')).rows),isCurrentSession:(actor,session)=>database.actorTransaction(actor,undefined,async c=>Boolean((await c.query('select "authorization".is_current_session($1)active',[session])).rows[0]?.active))});
    // Only private blob transport is in memory; real resource authorization,
    // content checks, immutable revisions, audit and outbox remain production SQL.
    const blobs=new Map<string,Buffer>();
    const storage={upload:async(path:string,bytes:Buffer)=>{blobs.set(path,Buffer.from(bytes));},download:async(path:string)=>{const bytes=blobs.get(path);if(!bytes)throw Error('Test resource unavailable.');const change=beforeReviewDownload;beforeReviewDownload=null;if(change)await change();return Buffer.from(bytes);}};
    @Module({controllers:[createSchoolLearningController(identity,database),createLearningContentController(identity,database),createThinkingFocusController(identity,database,{},storage),createAcademicController(identity,database),createLearningResourceController(identity,database,{},storage)]})class ThinkingTestModule{}
    app=await NestFactory.create<NestFastifyApplication>(ThinkingTestModule,new FastifyAdapter({logger:false}),{logger:false});await app.init();await app.getHttpAdapter().getInstance().ready();
    const reference=await command('teacher','/v1/academic-references',{version:'school-review-v1',title:'Reviewed procedure objective',description:'School-authored synthetic objective.'});referenceId=reference.id;await command('coordinator',`/v1/academic-references/${referenceId}/approve`,{});
  },60000);
  afterAll(async()=>withFixtureCleanup(async()=>{},[async()=>{if(app)await app.close();},async()=>{if(client)await client.query('ROLLBACK');},()=>{if(client)client.release();},async()=>{if(owner)await owner.end();}]));
  async function request(role:Role,path:string,body?:Record<string,unknown>,key:string=randomUUID()){return app.inject({method:body===undefined?'GET':'POST',url:path,headers:{authorization:`Bearer ${tokens[role]}`,'x-school-id':school,'idempotency-key':key},payload:body});}
  async function command(role:Role,path:string,body:Record<string,unknown>,key?:string):Promise<Row>{const response=await request(role,path,body,key);expect(response.statusCode,`HTTP ${response.statusCode} ${path}`).toBe(200);return response.json()as Row;}
  async function read(role:Role,path:string){const response=await request(role,path);expect(response.statusCode,`HTTP ${response.statusCode} ${path}`).toBe(200);return thinkingFocusResponseSchema.parse(response.json());}
  async function course(){const c=await command('teacher','/v1/courses',{classId,subjectId:subject,title:'Reviewed procedure course',description:'Isolated rollback fixture.'});const u=await command('teacher',`/v1/courses/${c.id}/units`,{title:'Procedure unit',sequence:1});const l=await command('teacher',`/v1/units/${u.id}/lessons`,{title:'Procedure lesson',body:'Read the school example.',sequence:1});const a=await command('teacher',`/v1/lessons/${l.id}/activities`,{title:'Use the procedure',instructions:'Use the school example for a new problem.',kind:'practice',sequence:1});await command('teacher',`/v1/courses/${c.id}/publish`,{});return{courseId:c.id,lessonId:l.id,activityId:a.id};}
  async function classify(path:string){const current=await read('teacher',path);const body={expectedRevision:current.revision,expectedSourceVersion:current.sourceVersion,focus,rationale:'Use the given procedure in a new example.'};const draft=await command('teacher',path+'/draft',body);const reviewBody={expectedRevision:draft.revision,expectedSourceVersion:current.sourceVersion,decision:'APPROVE',reason:'Reviewed the exact school-authored task.',confirmReview:true};const key=randomUUID();const approved=await command('coordinator',path+'/review',reviewBody,key);return{current,body,draft,reviewBody,key,approved};}

  it('keeps private review, exact replay, changed-source and immutable completion boundaries',async()=>{
    const source=await course(),path=`/v1/thinking-focus/activity/${source.activityId}`;const counts=(await client.query('select(select count(*)from app.xp_ledger where school_id=$1)xp,(select count(*)from app.learner_state_snapshots where school_id=$1)states',[school])).rows[0];const reviewed=await classify(path);
    expect((await request('student',path+'/history')).statusCode).toBe(403);expect((await request('wrongTeacher',path+'/draft',reviewed.body)).statusCode).toBe(403);expect((await request('teacher',path+'/review',reviewed.reviewBody)).statusCode).toBe(403);
    expect(await command('coordinator',path+'/review',reviewed.reviewBody,reviewed.key)).toEqual(reviewed.approved);expect((await request('coordinator',path+'/review',{...reviewed.reviewBody,reason:'Changed request'},reviewed.key)).statusCode).toBe(409);
    const complete=await command('student',`/v1/activities/${source.activityId}/complete`,{});const snapshotPath=`/v1/thinking-focus/sources/completion/${complete.id}`;const before=(await request('student',snapshotPath)).json();expect(thinkingFocusSnapshotSchema.parse(before).items[0].classification?.id).toBe(reviewed.approved.id);
    const contentPath=`/v1/learning-content/activity/${source.activityId}`,original=(await request('teacher',contentPath)).json();const draft=await command('teacher',contentPath+'/draft',{resource:'activity',expectedRevision:original.revision,title:'Compare alternatives',content:'Compare the approaches in this task.',kind:'practice',assessmentId:null,reason:'Task demand changes.'});
    expect((await read('teacher',path)).status).toBe('SOURCE_CHANGED');expect((await read('student',path)).status).toBe('APPROVED');expect((await request('coordinator',path+'/review',reviewed.reviewBody,reviewed.key)).statusCode).toBe(409);expect((await request('coordinator',`/v1/courses/${source.courseId}`)).statusCode).toBe(200);await command('teacher',contentPath+'/publish',{expectedRevision:draft.revision,confirmPublication:true});expect((await read('student',path)).status).toBe('UNCLASSIFIED');expect((await request('student',snapshotPath)).json()).toEqual(before);
    const current=await read('admin',path);await command('admin',path+'/draft',{expectedRevision:current.revision,expectedSourceVersion:current.sourceVersion,focus,rationale:'Current admin-authored exact task demand.'});expect((await request('admin',path+'/review',{expectedRevision:current.revision+1,expectedSourceVersion:current.sourceVersion,decision:'APPROVE',reason:'Self review',confirmReview:true})).statusCode).toBe(403);
    expect((await client.query('select(select count(*)from app.xp_ledger where school_id=$1)xp,(select count(*)from app.learner_state_snapshots where school_id=$1)states',[school])).rows[0]).toEqual(counts);
  },30000);

  it('preserves native zero and exact parent-publication/enrollment authority after metadata withdrawal',async()=>{
    const source=await course();const assessment=await command('teacher','/v1/assessments',{courseId:source.courseId,title:'Reviewed native zero task',instructions:'Use and explain the procedure.',maxScore:10});await command('teacher',`/v1/assessments/${assessment.id}/reference`,{referenceId,expectedPolicyVersion:1});const path=`/v1/thinking-focus/assessment/${assessment.id}`,reviewed=await classify(path);const submission=await command('student',`/v1/assessments/${assessment.id}/submissions`,{content:'My actual worked explanation.'});const mark=await command('teacher',`/v1/submissions/${submission.id}/results`,{score:0,feedback:'Reviewed native zero.',expectedPolicyVersion:2,expectedRevision:0,sourceEvidence:true});const released=await command('teacher',`/v1/results/${mark.id}/release`,{expectedRevision:1,parentVisible:true});expect(released.nativeResult).toMatchObject({type:'numeric',score:0,maxScore:10});
    const resultPath=`/v1/thinking-focus/sources/result/${released.id}`;const response=await request('parent',resultPath);expect(response.statusCode).toBe(200);const snapshot=thinkingFocusSnapshotSchema.parse(response.json());expect(snapshot).toMatchObject({id:submission.id,resultId:released.id,recorded:true});expect(snapshot.items[0].classification?.id).toBe(reviewed.approved.id);expect((await request('parent',`/v1/thinking-focus/sources/submission/${submission.id}`)).statusCode).toBe(403);
    const current=await read('coordinator',path);await command('coordinator',path+'/review',{expectedRevision:current.revision,expectedSourceVersion:current.sourceVersion,decision:'WITHDRAW',reason:'Review requires renewal.',confirmReview:true});expect((await read('student',path)).status).toBe('UNCLASSIFIED');expect((await request('parent',resultPath)).json()).toEqual(snapshot);
    await client.query("update app.parent_relationships set status='revoked'where school_id=$1 and parent_actor_id=$2",[school,actorId('parent')]);expect((await request('parent',resultPath)).statusCode).toBe(403);await client.query("update app.parent_relationships set status='active'where school_id=$1 and parent_actor_id=$2",[school,actorId('parent')]);await client.query("update app.enrollments set status='revoked'where school_id=$1 and student_actor_id=$2",[school,actorId('student')]);expect((await request('parent',resultPath)).statusCode).toBe(403);await client.query("update app.enrollments set status='active'where school_id=$1 and student_actor_id=$2",[school,actorId('student')]);expect((await request('parent',resultPath)).statusCode).toBe(200);
  },30000);

  it('invalidates changed published materials without rewriting recorded demand or permitting a stale review replay',async()=>{
    const source=await course();const path=`/v1/thinking-focus/activity/${source.activityId}`;
    async function asset(text:string){const bytes=Buffer.from(text,'utf8');const staged=await command('teacher',`/v1/courses/${source.courseId}/resource-assets`,{name:'Procedure guide.txt',contentType:'text/plain',byteSize:bytes.byteLength,sha256:createHash('sha256').update(bytes).digest('hex')});await command('teacher',`/v1/courses/${source.courseId}/resource-assets/${staged.id}/finalize`,{contentBase64:bytes.toString('base64')});return staged.id;}
    const first=await asset('School procedure guide, reviewed original steps.');const attached=await command('teacher',`/v1/courses/${source.courseId}/resources/activity/${source.activityId}`,{assetId:first,title:'Procedure guide',sequence:1});const publishedResource=await command('teacher',`/v1/courses/${source.courseId}/resources/${attached.id}/publish`,{expectedRevision:attached.revision,confirmPublication:true});const reviewed=await classify(path);const materialsPath=`${path}/materials?sourceVersion=${reviewed.current.sourceVersion}`;const manifest=await request('coordinator',materialsPath);expect(manifest.statusCode).toBe(200);expect(manifest.json().items[0]).toMatchObject({title:'Procedure guide',name:'Procedure guide.txt',revisionId:publishedResource.revisionId});expect(manifest.body).not.toContain('objectPath');expect((await request('student',materialsPath)).statusCode).toBe(403);expect((await request('parent',materialsPath)).statusCode).toBe(403);expect((await request('coordinator',`${path}/materials?sourceVersion=stale`)).statusCode).toBe(409);
    const downloadPath=`${path}/materials/${attached.id}/${publishedResource.revisionId}/download?sourceVersion=${reviewed.current.sourceVersion}`;const download=await request('coordinator',downloadPath);expect(download.statusCode).toBe(200);expect(download.body).toBe('School procedure guide, reviewed original steps.');expect(download.headers['content-type']).toContain('text/plain');expect(download.headers['cache-control']).toBe('no-store');expect((await request('coordinator',`/v1/learning-resources/${attached.id}/revisions/${publishedResource.revisionId}/download`)).statusCode).toBe(403);
    const completion=await command('student',`/v1/activities/${source.activityId}/complete`,{});const snapshotPath=`/v1/thinking-focus/sources/completion/${completion.id}`,before=(await request('student',snapshotPath)).json();
    beforeReviewDownload=async()=>{await client.query('SAVEPOINT material_race');await client.query("update app.memberships set status='revoked'where school_id=$1 and actor_id=$2",[school,actorId('coordinator')]);};expect((await request('coordinator',downloadPath)).statusCode).toBe(403);await client.query('ROLLBACK TO SAVEPOINT material_race');await client.query('RELEASE SAVEPOINT material_race');
    beforeReviewDownload=async()=>{await client.query('SAVEPOINT material_source_race');await command('teacher',`/v1/courses/${source.courseId}/resources/${attached.id}/remove`,{expectedRevision:publishedResource.revision,reason:'Source changed during inspection.',confirmRemoval:true});};expect((await request('coordinator',downloadPath)).statusCode).toBe(409);await client.query('ROLLBACK TO SAVEPOINT material_source_race');await client.query('RELEASE SAVEPOINT material_source_race');
    const second=await asset('School procedure guide changed to compare alternatives.');const replaced=await command('teacher',`/v1/courses/${source.courseId}/resources/${attached.id}/replace`,{assetId:second,expectedRevision:2,reason:'School changes the source material.'});expect((await read('teacher',path)).status).toBe('SOURCE_CHANGED');await command('teacher',`/v1/courses/${source.courseId}/resources/${attached.id}/publish`,{expectedRevision:replaced.revision,confirmPublication:true});expect((await read('student',path)).status).toBe('UNCLASSIFIED');expect((await request('coordinator',path+'/review',reviewed.reviewBody,reviewed.key)).statusCode).toBe(409);expect((await request('student',snapshotPath)).json()).toEqual(before);
  },30000);

  it('pins rubric criterion demand through publication and native parent evidence without a scalar score',async()=>{
    const source=await course();const rubric=await command('teacher','/v1/rubrics',{courseId:source.courseId,title:'School comparison rubric',version:'school-1',criteria:[{key:'comparison',title:'Comparison',levels:[{key:'shown',label:'Shown',description:'Compare the supplied alternatives.'}]}]});const assessment=await command('teacher','/v1/assessments',{courseId:source.courseId,title:'Criterion task',instructions:'Compare two approaches and justify one.',maxScore:10,preparation:true,intendedModel:'rubric',intendedSubmissionKind:'TEXT'});await command('teacher',`/v1/assessments/${assessment.id}/preparation`,{title:'Criterion task',instructions:'Compare two approaches and justify one.',dueAt:null,maxScore:10,referenceId,rubricId:rubric.id,expectedPreparationVersion:1});
    const path=`/v1/thinking-focus/criterion/${assessment.id}?criterionKey=comparison`;const current=await read('teacher',path);const draft=await command('teacher',`/v1/thinking-focus/criterion/${assessment.id}/draft?criterionKey=comparison`,{expectedRevision:current.revision,expectedSourceVersion:current.sourceVersion,focus:{...focus,primaryProcess:'ANALYZE'},rationale:'Compare the supplied alternatives.'});await command('coordinator',`/v1/thinking-focus/criterion/${assessment.id}/review?criterionKey=comparison`,{expectedRevision:draft.revision,expectedSourceVersion:current.sourceVersion,decision:'APPROVE',reason:'Reviewed the exact task and school criterion.',confirmReview:true});const prepared=(await request('teacher',`/v1/assessments/${assessment.id}`)).json();await command('teacher',`/v1/assessments/${assessment.id}/publish`,{expectedPreparationVersion:prepared.preparationVersion,expectedPolicyVersion:prepared.policyVersion,expectedAvailabilityVersion:prepared.availabilityVersion});
    const published=await read('teacher',path);expect(published).toMatchObject({status:'APPROVED',revision:3,source:{criterionTitle:'Comparison'}});const submission=await command('student',`/v1/assessments/${assessment.id}/submissions`,{content:'I compare the supplied alternatives.'});const mark=await command('teacher',`/v1/submissions/${submission.id}/results`,{nativeResult:{type:'rubric',rubricId:rubric.id,criteria:[{criterionKey:'comparison',levelKey:'shown'}]},feedback:'School-native comparison evidence.',expectedPolicyVersion:prepared.policyVersion,expectedRevision:0,sourceEvidence:true});const released=await command('teacher',`/v1/results/${mark.id}/release`,{expectedRevision:1,parentVisible:true});expect(released).not.toHaveProperty('score');expect(released.nativeResult).toMatchObject({type:'rubric',normalized:null});const parent=await request('parent',`/v1/thinking-focus/sources/result/${released.id}`);expect(parent.statusCode).toBe(200);const snapshot=thinkingFocusSnapshotSchema.parse(parent.json());expect(snapshot.items[0]).toMatchObject({target:{kind:'CRITERION',id:assessment.id,criterionKey:'comparison'},source:{criterionTitle:'Comparison'}});expect(snapshot.items[0].classification?.focus.primaryProcess).toBe('ANALYZE');
  },30000);
  it('raw approval denies unavailable material atomically while rejection remains allowed',async()=>{
    const source=await course(),path=`/v1/thinking-focus/activity/${source.activityId}`;const bytes=Buffer.from('School material awaiting review.');const staged=await command('teacher',`/v1/courses/${source.courseId}/resource-assets`,{name:'Review basis.txt',contentType:'text/plain',byteSize:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});await command('teacher',`/v1/courses/${source.courseId}/resource-assets/${staged.id}/finalize`,{contentBase64:bytes.toString('base64')});const attached=await command('teacher',`/v1/courses/${source.courseId}/resources/activity/${source.activityId}`,{assetId:staged.id,title:'Review basis',sequence:1});await command('teacher',`/v1/courses/${source.courseId}/resources/${attached.id}/publish`,{expectedRevision:attached.revision,confirmPublication:true});const current=await read('teacher',path);const draft=await command('teacher',path+'/draft',{expectedRevision:0,expectedSourceVersion:current.sourceVersion,focus,rationale:'Apply the supplied source procedure.'});await client.query("update app.private_assets set state='RETIRED'where school_id=$1 and id=$2",[school,staged.id]);const before=(await client.query("select(select count(*)from app.thinking_focus_revisions where school_id=$1 and source_id=$2)revisions,(select count(*)from internal.audit_events where school_id=$1 and action='thinking_focus.review')audits",[school,source.activityId])).rows[0];const review={expectedRevision:draft.revision,expectedSourceVersion:current.sourceVersion,decision:'APPROVE',reason:'Human confirms review.',confirmReview:true};expect((await request('coordinator',path+'/review',review)).statusCode).toBe(409);expect((await client.query("select(select count(*)from app.thinking_focus_revisions where school_id=$1 and source_id=$2)revisions,(select count(*)from internal.audit_events where school_id=$1 and action='thinking_focus.review')audits",[school,source.activityId])).rows[0]).toEqual(before);expect((await command('coordinator',path+'/review',{...review,decision:'REJECT',reason:'Source material unavailable for approval.'})).status).toBe('REJECTED');
  },30000);
});
