import {createHash}from'node:crypto';import{z}from'zod';
import{DomainError,requireCapability,type ActorContext}from'@cuevo/domain';
import{schoolDetailsSchema,academicYearInputSchema,termInputSchema,yearGroupInputSchema,classInputSchema,subjectInputSchema,personConfigureSchema,enrollmentInputSchema,teacherAssignmentInputSchema,guardianRelationshipInputSchema,attendanceInputSchema,timetableInputSchema,calendarInputSchema,reportPeriodInputSchema,schoolPolicyInputSchema,schoolListQuerySchema,idempotencyKeySchema,schoolRecordEditSchema,schoolRecordCancelSchema}from'@cuevo/contracts';
import type{Database}from'../../platform/database/database';
export const schoolCommandSchemas={'details.update':schoolDetailsSchema,'year.create':academicYearInputSchema,'term.create':termInputSchema,'yeargroup.create':yearGroupInputSchema,'class.create':classInputSchema,'subject.create':subjectInputSchema,'person.configure':personConfigureSchema,'enrollment.configure':enrollmentInputSchema,'assignment.configure':teacherAssignmentInputSchema,'guardian.configure':guardianRelationshipInputSchema,'attendance.record':attendanceInputSchema,'timetable.create':timetableInputSchema,'calendar.create':calendarInputSchema,'reportperiod.create':reportPeriodInputSchema,'policy.approve':schoolPolicyInputSchema};
export type SchoolCommand=keyof typeof schoolCommandSchemas;
export const schoolResources=['years','terms','year-groups','classes','subjects','people','enrollments','teacher-assignments','guardian-relationships','attendance','attendance-roster','timetable','calendar','report-periods','policies','entitlements','audit']as const;
export type SchoolResource=typeof schoolResources[number];
function parse<T>(schema:z.ZodType<T>,input:unknown){const r=schema.safeParse(input);if(!r.success)throw new DomainError('INVALID_INPUT',400,'Review the school operation fields.');return r.data;}
function safe(error:unknown):DomainError{if(error instanceof DomainError)return error;const code=typeof error==='object'&&error!==null&&'code'in error?String(error.code):'';if(code==='42501')return new DomainError('FORBIDDEN',403,'Your current access does not permit this school operation.');if(['22023','23505','55000'].includes(code))return new DomainError('SCHOOL_CONFLICT',409,'Review the current source, version or access window.');if(['23503','23514','23502','22P02'].includes(code))return new DomainError('INVALID_INPUT',400,'Review the school operation context.');return new DomainError('REQUEST_UNAVAILABLE',503,'School operations are temporarily unavailable.');}
export class SchoolService{
 constructor(private readonly database:Database){}
 async maintain(actor:ActorContext,target:string,body:unknown,cancel:boolean,key:unknown,requestId:string){requireCapability(actor,actor.schoolId,'school.operations',['admin']);parse(z.uuid(),target);const input=parse(cancel?schoolRecordCancelSchema:schoolRecordEditSchema,body);const identity=parse(idempotencyKeySchema,key);const fingerprint=createHash('sha256').update(JSON.stringify({target,cancel,input})).digest('hex');try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async client=>(await client.query('select internal.maintain_school_record($1,$2::jsonb,$3,$4,$5,$6)as response',[target,JSON.stringify(input),cancel,identity,fingerprint,requestId])).rows[0]?.response);}catch(error){throw safe(error);}}
 async context(actor:ActorContext){requireCapability(actor,actor.schoolId,'school.operations',['admin','coordinator','teacher','student','parent']);try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>(await c.query('select internal.school_context()as context')).rows[0]?.context);}catch(e){throw safe(e);}}
 async list(actor:ActorContext,resource:SchoolResource,query:unknown){requireCapability(actor,actor.schoolId,'school.operations',['admin','coordinator','teacher','student','parent']);const page=parse(schoolListQuerySchema,query);if(resource==='attendance-roster'&&!page.classId)throw new DomainError('INVALID_INPUT',400,'Select a current class for attendance.');if(resource==='audit'&&actor.role!=='admin')throw new DomainError('FORBIDDEN',403,'School audit requires administrator access.');try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>(await c.query(resource==='audit'?'select internal.read_school_audit($1::jsonb)as page':'select internal.named_school_page($1,$2::jsonb)as page',resource==='audit'?[JSON.stringify(page)]:[resource,JSON.stringify(page)])).rows[0]?.page);}catch(e){throw safe(e);}}
 async command(actor:ActorContext,command:SchoolCommand,target:string|undefined,body:unknown,key:unknown,requestId:string){requireCapability(actor,actor.schoolId,'school.operations',command==='attendance.record'?['admin','teacher']:['admin']);const input=parse(schoolCommandSchemas[command]as z.ZodType<Record<string,unknown>>,body);if(target!==undefined)parse(z.uuid(),target);const identity=parse(idempotencyKeySchema,key);const fingerprint=createHash('sha256').update(JSON.stringify({command,target:target??null,input})).digest('hex');try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>{const row=(await c.query('select internal.school_command($1,$2,$3::jsonb,$4,$5,$6)as response',[command,target??null,JSON.stringify(input),identity,fingerprint,requestId])).rows[0];if(!row?.response)throw new DomainError('REQUEST_UNAVAILABLE',503,'School operation receipt is unavailable. Reconcile the original request.');return row.response;});}catch(e){throw safe(e);}}
}
