import{z}from'zod';import{Controller,Get,Post,Req,Res,type Type}from'@nestjs/common';import{ApiBearerAuth,ApiBody,ApiHeader}from'@nestjs/swagger';import type{FastifyRequest,FastifyReply}from'fastify';import{DomainError}from'@cuevo/domain';import type{IdentityService}from'../../platform/identity/identity.service';import type{Database}from'../../platform/database/database';import{SchoolService,schoolResources,schoolCommandSchemas,type SchoolCommand,type SchoolResource}from'./school.service';
const body=(name:SchoolCommand)=>ApiBody({required:true,schema:z.toJSONSchema(schoolCommandSchemas[name],{target:'openapi-3.0'})as never});
export function createSchoolController(identity:IdentityService,database:Database):Type<unknown>{const service=new SchoolService(database);
 @Controller('/v1/school')@ApiBearerAuth()@ApiHeader({name:'X-School-Id',required:false})class SchoolController{
 private async respond(req:FastifyRequest,res:FastifyReply,fn:(actor:Awaited<ReturnType<IdentityService['resolve']>>)=>Promise<unknown>){try{const h=req.headers['x-school-id'];if(Array.isArray(h))throw new DomainError('INVALID_SCHOOL',400,'School selection is invalid.');const actor=await identity.resolve(req.headers.authorization,h);return res.code(200).header('Cache-Control','no-store').send(await fn(actor));}catch(e){const safe=e instanceof DomainError?e:new DomainError('REQUEST_UNAVAILABLE',503,'School operations are temporarily unavailable.');return res.code(safe.status).header('Cache-Control','no-store').send({code:safe.code,message:safe.message,requestId:req.id});}}
 private command(req:FastifyRequest,res:FastifyReply,command:SchoolCommand){return this.respond(req,res,actor=>service.command(actor,command,(req.params as{id?:string}).id,req.body,req.headers['idempotency-key'],req.id));}
 @Get('/context')context(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,a=>service.context(a));}
 @Get('/:resource')list(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,a=>{const resource=(r.params as{resource:SchoolResource}).resource;if(!schoolResources.includes(resource))throw new DomainError('NOT_FOUND',404,'School resource is unavailable.');return service.list(a,resource,r.query);});}
 @Post('/details')@body('details.update')@ApiHeader({name:'Idempotency-Key',required:true})details(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'details.update');}
 @Post('/years')@body('year.create')@ApiHeader({name:'Idempotency-Key',required:true})years(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'year.create');}
 @Post('/terms')@body('term.create')@ApiHeader({name:'Idempotency-Key',required:true})terms(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'term.create');}
 @Post('/year-groups')@body('yeargroup.create')@ApiHeader({name:'Idempotency-Key',required:true})yearGroups(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'yeargroup.create');}
 @Post('/classes')@body('class.create')@ApiHeader({name:'Idempotency-Key',required:true})classes(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'class.create');}
 @Post('/subjects')@body('subject.create')@ApiHeader({name:'Idempotency-Key',required:true})subjects(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'subject.create');}
 @Post('/people/:id/configure')@body('person.configure')@ApiHeader({name:'Idempotency-Key',required:true})people(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'person.configure');}
 @Post('/enrollments')@body('enrollment.configure')@ApiHeader({name:'Idempotency-Key',required:true})enrollments(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'enrollment.configure');}
 @Post('/teacher-assignments')@body('assignment.configure')@ApiHeader({name:'Idempotency-Key',required:true})assignments(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'assignment.configure');}
 @Post('/guardian-relationships')@body('guardian.configure')@ApiHeader({name:'Idempotency-Key',required:true})guardians(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'guardian.configure');}
 @Post('/attendance')@body('attendance.record')@ApiHeader({name:'Idempotency-Key',required:true})attendance(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'attendance.record');}
 @Post('/timetable')@body('timetable.create')@ApiHeader({name:'Idempotency-Key',required:true})timetable(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'timetable.create');}
 @Post('/calendar')@body('calendar.create')@ApiHeader({name:'Idempotency-Key',required:true})calendar(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'calendar.create');}
 @Post('/report-periods')@body('reportperiod.create')@ApiHeader({name:'Idempotency-Key',required:true})periods(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'reportperiod.create');}
 @Post('/policies')@body('policy.approve')@ApiHeader({name:'Idempotency-Key',required:true})policies(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.command(r,p,'policy.approve');}
 }return SchoolController;}
