import{Controller,Get,Post,Req,Res,type Type}from'@nestjs/common';import{ApiBearerAuth,ApiBody,ApiHeader}from'@nestjs/swagger';import{z}from'zod';import type{FastifyRequest,FastifyReply}from'fastify';import{createHash}from'node:crypto';import{DomainError,requireCapability,type ActorContext}from'@cuevo/domain';import{campusInputSchema,classCampusSchema,campusRetireSchema,learningSupportSchema,learningSupportRevokeSchema,schoolSupportQuerySchema,idempotencyKeySchema}from'@cuevo/contracts';import type{IdentityService}from'../../platform/identity/identity.service';import type{Database}from'../../platform/database/database';
const schemas={'campus.create':campusInputSchema,'campus.retire':campusRetireSchema,'class.campus':classCampusSchema,'support.create':learningSupportSchema,'support.revoke':learningSupportRevokeSchema};type Command=keyof typeof schemas;
function parse<T>(schema:z.ZodType<T>,value:unknown){const result=schema.safeParse(value);if(!result.success)throw new DomainError('INVALID_INPUT',400,'Review the school-approved learning context.');return result.data;}
export function createSchoolSupportController(identity:IdentityService,database:Database):Type<unknown>{
 @Controller('/v1/school')@ApiBearerAuth()class SchoolSupportController{
  private async respond(req:FastifyRequest,res:FastifyReply,run:(actor:ActorContext)=>Promise<unknown>){try{const school=req.headers['x-school-id'];if(Array.isArray(school))throw new DomainError('INVALID_INPUT',400,'School selection is invalid.');const actor=await identity.resolve(req.headers.authorization,school);requireCapability(actor,actor.schoolId,'school.operations',['admin','coordinator','teacher','student','parent']);return res.code(200).header('Cache-Control','no-store').send(await run(actor));}catch(error){const code=error&&typeof error==='object'&&'code'in error?String(error.code):'';const safe=error instanceof DomainError?error:new DomainError(code==='42501'?'FORBIDDEN':['22023','23505','55000'].includes(code)?'SCHOOL_CONTEXT_REQUIRES_REVIEW':'REQUEST_UNAVAILABLE',code==='42501'?403:['22023','23505','55000'].includes(code)?409:503,'School context requires current access or review.');return res.code(safe.status).header('Cache-Control','no-store').send({code:safe.code,message:safe.message,requestId:req.id});}}
  private command(command:Command,req:FastifyRequest,res:FastifyReply){return this.respond(req,res,async actor=>{requireCapability(actor,actor.schoolId,'school.operations',command.startsWith('support.')?['admin','coordinator']:['admin']);const id=(req.params as{id?:string}).id;if(id)parse(z.uuid(),id);const body=parse(schemas[command]as z.ZodType<Record<string,unknown>>,req.body);const key=parse(idempotencyKeySchema,req.headers['idempotency-key']);const fingerprint=createHash('sha256').update(JSON.stringify({command,id,body})).digest('hex');return database.actorTransaction(actor.userId,actor.schoolId,async client=>(await client.query('select internal.campus_support_command($1,$2,$3::jsonb,$4,$5,$6)as receipt',[command,id??null,JSON.stringify(body),key,fingerprint,req.id])).rows[0]?.receipt);});}
  @Get('/campuses')campuses(@Req()req:FastifyRequest,@Res()res:FastifyReply){return this.respond(req,res,async actor=>{requireCapability(actor,actor.schoolId,'school.operations',['admin','coordinator']);const page=parse(schoolSupportQuerySchema,req.query);return database.actorTransaction(actor.userId,actor.schoolId,async client=>(await client.query('select internal.read_campus_page($1,$2)as page',[page.limit,page.cursor??null])).rows[0]?.page);});}
  @Post('/campuses')@ApiBody({schema:z.toJSONSchema(campusInputSchema,{target:'openapi-3.0'})as never})@ApiHeader({name:'Idempotency-Key',required:true})createCampus(@Req()req:FastifyRequest,@Res()res:FastifyReply){return this.command('campus.create',req,res);}
  @Post('/campuses/:id/retire')@ApiBody({schema:z.toJSONSchema(campusRetireSchema,{target:'openapi-3.0'})as never})@ApiHeader({name:'Idempotency-Key',required:true})retireCampus(@Req()req:FastifyRequest,@Res()res:FastifyReply){return this.command('campus.retire',req,res);}
  @Get('/classes/:id/campus')classCampus(@Req()req:FastifyRequest,@Res()res:FastifyReply){return this.respond(req,res,actor=>{const id=parse(z.uuid(),(req.params as{id:string}).id);return database.actorTransaction(actor.userId,actor.schoolId,async client=>(await client.query('select internal.read_class_campus($1)as campus',[id])).rows[0]?.campus);});}
  @Post('/classes/:id/campus')@ApiBody({schema:z.toJSONSchema(classCampusSchema,{target:'openapi-3.0'})as never})@ApiHeader({name:'Idempotency-Key',required:true})assignCampus(@Req()req:FastifyRequest,@Res()res:FastifyReply){return this.command('class.campus',req,res);}
  @Get('/learning-support')support(@Req()req:FastifyRequest,@Res()res:FastifyReply){return this.respond(req,res,async actor=>{const page=parse(schoolSupportQuerySchema,req.query);return database.actorTransaction(actor.userId,actor.schoolId,async client=>(await client.query('select internal.read_learning_support($1::jsonb)as page',[JSON.stringify(page)])).rows[0]?.page);});}
  @Post('/learning-support')@ApiBody({schema:z.toJSONSchema(learningSupportSchema,{target:'openapi-3.0'})as never})@ApiHeader({name:'Idempotency-Key',required:true})approveSupport(@Req()req:FastifyRequest,@Res()res:FastifyReply){return this.command('support.create',req,res);}
  @Post('/learning-support/:id/revoke')@ApiBody({schema:z.toJSONSchema(learningSupportRevokeSchema,{target:'openapi-3.0'})as never})@ApiHeader({name:'Idempotency-Key',required:true})revokeSupport(@Req()req:FastifyRequest,@Res()res:FastifyReply){return this.command('support.revoke',req,res);}
 }
 return SchoolSupportController;
}
