'use client';
import {useCallback,useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {Button,Status,WorkspacePageHeading,WorkspaceState} from '@cuevo/ui';
import {useApp} from '../../../shared/session/providers';
import {useApiQuery} from '../../../shared/hooks/use-api';
import {usePaginatedLearningQuery} from '../../../shared/hooks/use-paginated-query';
import {CommandForm,type FormField} from '../../../shared/components/command-form';
import {LearningError} from '../../../shared/components/feedback';
import {LoadMore} from '../../../shared/components/load-more';
import {LearningApiError} from '../../../shared/api/client';
import {parseRestrictedPolicy,parseRestrictedRecord,parseRestrictedHistory} from '../model';
import {restrictedRecordCreateSchema,restrictedRecordCorrectionSchema,restrictedFollowUpApprovalSchema,restrictedFollowUpSchema,type RestrictedRecord} from '@cuevo/contracts';
import {restrictedPath,restrictedReadScope,currentRestrictedRead,restrictedDraftKey,restrictedRecovery,restrictedReview,parseRestrictedReview,restrictedActionPath,restrictedChoices,parseRestrictedCourseChoice,parseRestrictedPersonChoice,validateRestrictedReceipt,type RestrictedReview} from '../review-model';
import {restrictedEn,restrictedAr} from '../messages';
function usePrivatePage<T extends{id:string}>(path:string|null,parse:(value:unknown)=>T,refresh:number){const app=useApp(),scope=restrictedReadScope(app,path,refresh);const parser=useCallback((value:unknown)=>{const row=parse(value);return{id:row.id,scope,value:row};},[parse,scope]);const query=usePaginatedLearningQuery(scope?path:null,parser,refresh);return{...query,data:query.loading||query.error||query.moreError?[]:query.data.flatMap(row=>{const current=currentRestrictedRead(row,scope);return current?[current]:[];})};}
export function RestrictedRecordsWorkspace(){const app=useApp(),t=app.locale==='ar'?restrictedAr:restrictedEn;if(!restrictedReadScope(app,restrictedPath,0))return <WorkspacePageHeading title={t.title}/>;return <CurrentRestrictedWorkspace key={`${app.apiUrl}:${app.membership!.schoolId}:${app.membership!.userId}:${app.membership!.role}`}/>;}
function CurrentRestrictedWorkspace(){
 const app=useApp(),{membership,locale,formDrafts,commandJournal}=app,t=locale==='ar'?restrictedAr:restrictedEn;
 useSyncExternalStore(commandJournal.subscribe,commandJournal.getSnapshot,commandJournal.getSnapshot);
 const intentSlot=`${membership!.schoolId}:${membership!.userId}:${restrictedPath}:intent`,savedIntent=formDrafts.model<{courseId?:string;learnerId?:string;action?:unknown}>(intentSlot);
 const originalCreate=restrictedRecovery(commandJournal.get(restrictedPath));
 const originalAction=commandJournal.pending().map(restrictedRecovery).find(item=>item&&item.kind!=='create');
 const selectionScope=restrictedReadScope(app,restrictedPath,0);
 const [policyOpen,setPolicyOpen]=useState(!!commandJournal.get(restrictedPath+'/policy'));
 const [selection,setSelection]=useState<{record:RestrictedReview;scope:string|null}|null>(()=>{const retained=parseRestrictedReview(savedIntent?.action);return retained?{record:retained,scope:selectionScope}:null;});
 const opener=useRef<HTMLButtonElement|null>(null),openerId=useRef<string|null>(null),directoryButtons=useRef(new Map<string,HTMLButtonElement>()),workspaceHeading=useRef<HTMLHeadingElement>(null),directoryHeading=useRef<HTMLHeadingElement>(null),readerHeading=useRef<HTMLHeadingElement>(null),focusReader=useRef(false),focusDirectory=useRef(false);
 const [refresh,setRefresh]=useState(0),[courseId,setCourseId]=useState(originalCreate?.kind==='create'?originalCreate.input.courseId:savedIntent?.courseId??''),[learnerId,setLearnerId]=useState(originalCreate?.kind==='create'?originalCreate.input.learnerId:savedIntent?.learnerId??'');
 const [creating,setCreating]=useState(!!originalCreate||!!savedIntent?.courseId&&!savedIntent?.action),[action,setAction]=useState<RestrictedReview|null>(()=>parseRestrictedReview(savedIntent?.action));
 const [historyId,setHistoryId]=useState<string|null>(null),[historyCursor,setHistoryCursor]=useState<string|null>(null),[locked,setLocked]=useState(false);
 const onLocked=useCallback((value:boolean)=>setLocked(value),[]),retainedCreate=commandJournal.get(restrictedPath),createRecovery=restrictedRecovery(retainedCreate),pending=locked||commandJournal.pending().some(command=>command.path.startsWith(restrictedPath));
 const otherPolicyPending=commandJournal.pending().some(command=>command.path.startsWith(restrictedPath)&&command.path!==restrictedPath+'/policy');
 const policyPath=restrictedPath+'/policy',policyScope=restrictedReadScope(app,policyPath,refresh),policyParser=useCallback((value:unknown)=>({scope:policyScope,value:parseRestrictedPolicy(value)}),[policyScope]);
 const policyQuery=useApiQuery(policyScope?policyPath:null,policyParser,refresh),policy=currentRestrictedRead(policyQuery.data,policyScope),enabled=!!policy?.enabled;
 const records=usePrivatePage(enabled?restrictedPath+'?limit=25':null,parseRestrictedRecord,refresh),courses=usePrivatePage(enabled?restrictedPath+'/choices?limit=25':null,parseRestrictedCourseChoice,refresh);
 const selectedCourseId=createRecovery?.kind==='create'?createRecovery.input.courseId:action?.courseId??courseId;
 const selectedLearnerId=createRecovery?.kind==='create'?createRecovery.input.learnerId:learnerId;
 const people=usePrivatePage(enabled&&selectedCourseId?`${restrictedPath}/courses/${selectedCourseId}/choices?limit=25`:null,parseRestrictedPersonChoice,refresh);
 const historyRecord=selection?.scope===selectionScope?records.data.find(record=>record.id===historyId&&record.id===selection.record.id&&record.courseId===selection.record.courseId&&record.learnerId===selection.record.learnerId&&record.authorId===selection.record.authorId&&record.occurredAt===selection.record.occurredAt&&(record.revision===selection.record.revision||originalAction?.id===record.id)):null;
 const historyPath=historyRecord?`${restrictedPath}/${historyRecord.id}/history?limit=25${historyCursor?'&cursor='+historyCursor:''}`:null,historyScope=restrictedReadScope(app,enabled?historyPath:null,refresh),historyParser=useCallback((value:unknown)=>({scope:historyScope,value:parseRestrictedHistory(value)}),[historyScope]);
 const historyQuery=useApiQuery(historyScope?historyPath:null,historyParser,refresh),history=currentRestrictedRead(historyQuery.data,historyScope);
 const complete=(query:typeof courses|typeof records|typeof people)=>query.loaded&&!query.loading&&!query.loadingMore&&!query.error&&!query.moreError&&!query.nextCursor;
 const courseChoices=restrictedChoices(courses.data.map(course=>({id:course.id,label:`${course.title} · ${course.className}`}))),personChoices=restrictedChoices(people.data.filter(person=>person.role==='student').map(person=>({id:person.id,label:person.displayName}))),ownerChoices=restrictedChoices(people.data.filter(person=>person.role==='teacher').map(person=>({id:person.id,label:person.displayName})));
 const selectedCourse=courses.data.find(course=>course.id===selectedCourseId),selectedLearner=people.data.find(person=>person.id===selectedLearnerId&&person.role==='student');
 const currentChoices=complete(courses)&&complete(people)&&!!selectedCourse&&courseChoices.some(choice=>choice.value===selectedCourseId&&!choice.requiresReview)&&personChoices.some(choice=>choice.value===selectedLearnerId&&!choice.requiresReview);
 const sourceErrors=[records.error,records.moreError,courses.error,courses.moreError,people.error,people.moreError],sourceError=sourceErrors.find(error=>error?.kind==='denied'||error?.kind==='unauthorized')??sourceErrors.find(Boolean);
 const sourceReady=enabled&&!sourceError;
 useEffect(()=>{if(sourceError){formDrafts.clearRead(`${membership!.schoolId}:${membership!.userId}:`,restrictedPath);setAction(null);}},[sourceError,formDrafts,membership]);
 useEffect(()=>{if(action&&selection?.scope===selectionScope||!originalAction||originalAction.kind==='create'||!complete(records))return;const record=records.data.find(record=>record.id===originalAction.id);if(record){const reviewed=restrictedReview(record,originalAction.kind);reviewed.revision=Number(originalAction.input.expectedRevision);setPolicyOpen(false);setSelection({record:restrictedReview(record,originalAction.kind),scope:selectionScope});setAction(reviewed);}},[action,selection,originalAction,records.loaded,records.loading,records.error,records.nextCursor,selectionScope]);
 function remember(nextCourse:string,nextLearner:string,nextAction:RestrictedReview|null=null){formDrafts.saveModel(intentSlot,{courseId:nextCourse,learnerId:nextLearner,action:nextAction});}
 function saved(){formDrafts.remove(intentSlot);setCreating(false);setAction(null);setSelection(null);setPolicyOpen(false);focusDirectory.current=true;setRefresh(value=>value+1);}
 function openAction(record:RestrictedRecord,kind:RestrictedReview['kind']){if(pending)return;const next=restrictedReview(record,kind);setCreating(false);setCourseId(record.courseId);setAction(next);remember(record.courseId,record.learnerId,next);}
 const currentRecord=action?records.data.find(record=>record.id===action.id&&record.courseId===action.courseId&&record.learnerId===action.learnerId&&record.authorId===action.authorId):null;
 const actionPath=action?restrictedActionPath(action):null,retainedAction=actionPath?commandJournal.get(actionPath):undefined;
 const actionRecovery=restrictedRecovery(retainedAction);
 const actionPermitted=!!action&&!!currentRecord&&(action.kind==='correct'?currentRecord.authorId===membership!.userId:action.kind==='approve'?membership!.role==='admin'&&policy?.ownerId===membership!.userId:membership!.role==='teacher'&&currentRecord.followUpOwnerId===membership!.userId);
 const actionReady=sourceReady&&complete(records)&&actionPermitted&&(!!actionRecovery||currentRecord!.revision===action!.revision)&&(action!.kind!=='approve'||complete(people)&&!!selectedCourse&&complete(courses));
 const selectedBasis=selection?.scope===selectionScope?selection.record:null;
 const selectedRecord=selectedBasis&&sourceReady?records.data.find(record=>record.id===selectedBasis.id&&record.courseId===selectedBasis.courseId&&record.learnerId===selectedBasis.learnerId&&record.authorId===selectedBasis.authorId&&record.occurredAt===selectedBasis.occurredAt&&(record.revision===selectedBasis.revision||!!actionRecovery)):null;
 useEffect(()=>{if(focusReader.current&&selectedRecord){focusReader.current=false;readerHeading.current?.focus({preventScroll:true});readerHeading.current?.scrollIntoView({block:'start',behavior:'instant'});}if(focusDirectory.current&&!selection&&!creating&&!policyOpen){focusDirectory.current=false;const currentOpener=openerId.current?directoryButtons.current.get(openerId.current):opener.current;const available=(control:HTMLButtonElement|null|undefined)=>!!control?.isConnected&&!control.disabled&&control.tabIndex>=0&&control.getClientRects().length>0;const target=available(currentOpener)?currentOpener:available(opener.current)?opener.current:directoryHeading.current??workspaceHeading.current;target?.focus({preventScroll:true});target?.scrollIntoView({block:'nearest',behavior:'instant'});}},[selectedRecord,selection,creating,policyOpen,records.loading]);
 function back(){if(pending)return;setSelection(null);setAction(null);setCreating(false);setPolicyOpen(false);setHistoryId(null);setHistoryCursor(null);formDrafts.remove(intentSlot);focusDirectory.current=true;}
 function openRecord(record:RestrictedRecord,control:HTMLButtonElement){if(pending)return;opener.current=control;openerId.current=record.id;focusReader.current=true;setPolicyOpen(false);setCreating(false);setAction(null);setHistoryId(null);setHistoryCursor(null);setSelection({record:restrictedReview(record,'correct'),scope:selectionScope});}
 const date=(value:string)=>new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(value));
 const actionFields:FormField[]=action?.kind==='approve'?[{name:'followUpOwnerId',label:t.owner,type:'select',required:true,options:ownerChoices.filter(choice=>!choice.requiresReview).map(({value,label})=>({value,label}))},{name:'instructions',label:t.instructions,type:'textarea',required:true,maxLength:4000},{name:'reason',label:t.reason,type:'textarea',required:true,maxLength:1000},{name:'confirmApproval',label:t.confirmApprove,type:'checkbox',required:true}]:action?.kind==='correct'?[{name:'title',label:t.recordTitle,required:true,defaultValue:currentRecord?.title},{name:'note',label:t.note,type:'textarea',required:true,defaultValue:currentRecord?.note,maxLength:4000},{name:'reason',label:t.reason,type:'textarea',required:true,maxLength:1000},{name:'confirmCorrection',label:t.confirmCorrection,type:'checkbox',required:true}]:[{name:'status',label:t.status,type:'select',required:true,options:[{value:'IN_PROGRESS',label:t.progress},{value:'COMPLETED',label:t.completed}]},{name:'note',label:t.note,type:'textarea',required:true,maxLength:4000},{name:'confirmManualAction',label:t.confirmManual,type:'checkbox',required:true}];
 if(policyQuery.loading||!policy&&!policyQuery.error)return <section><WorkspacePageHeading title={t.title}/><WorkspaceState kind="loading" icon="refresh" description={t.loading} role="status"/></section>;
 if(policyQuery.error)return <section><WorkspacePageHeading title={t.title}/><LearningError error={policyQuery.error}/><Button type='button' onClick={()=>setRefresh(value=>value+1)}>{t.refresh}</Button></section>;
 return <section className='restricted-workspace' aria-label={t.title}><WorkspacePageHeading title={t.title} headingRef={workspaceHeading} actions={<Button type='button' variant='quiet' onClick={()=>setRefresh(value=>value+1)}>{t.refresh}</Button>}/><p className='notice'>{t.notice}</p>
 {membership!.role==='admin'?<Button type='button' variant='quiet' disabled={pending||otherPolicyPending} onClick={event=>{if(pending||otherPolicyPending)return;opener.current=event.currentTarget;openerId.current=null;setSelection(null);setCreating(false);setAction(null);setPolicyOpen(true);}}>{t.policy}</Button>:null}
 {policyOpen&&membership!.role==='admin'&&!otherPolicyPending?<><Button type='button' variant='quiet' disabled={pending} onClick={back}>{t.back}</Button><CommandForm key={policy!.version} title={t.policy} path={policyPath} fields={[{name:'enabled',label:t.enable,type:'checkbox',defaultChecked:policy!.enabled},{name:'retentionNote',label:t.retention,type:'textarea',required:true,maxLength:1000},{name:'reason',label:t.reason,type:'textarea',required:true,maxLength:1000},{name:'confirmApproval',label:t.confirmPolicy,type:'checkbox',required:true}]} body={values=>{if(otherPolicyPending)throw new LearningApiError('conflict');return {enabled:values.get('enabled')==='on',expectedVersion:policy!.version,purpose:'BASIC_INCIDENT_NOTE',sourceBasis:'SCHOOL_AUTHORED',retentionStatus:'SYNTHETIC_ONLY',retentionNote:String(values.get('retentionNote')),ownerId:membership!.userId,reason:String(values.get('reason')),confirmApproval:values.get('confirmApproval')==='on'};}} validateReceipt={(receipt,original)=>validateRestrictedReceipt(receipt,original,membership!.userId)} onLockedChange={onLocked} onSaved={saved} onCancel={back}/></>:null}
 {!enabled?<WorkspaceState kind="unavailable" icon="shield" description={t.disabled}/>:!policyOpen?<><Button type='button' disabled={pending||!!sourceError} onClick={()=>{setCreating(true);setSelection(null);setAction(null);remember(courseId,learnerId);}}>{t.create}</Button>{sourceError?<LearningError error={sourceError}/>:null}
 {creating&&sourceReady?<section><Button type='button' variant='quiet' disabled={pending} onClick={back}>{t.back}</Button><div className='field'><label htmlFor='restricted-course'>{t.course}</label><select id='restricted-course' value={selectedCourseId} disabled={pending||courses.loading} onChange={event=>{if(pending)return;setCourseId(event.target.value);setLearnerId('');remember(event.target.value,'');}}><option value=''>{t.course}</option>{courseChoices.map(choice=><option key={choice.value} value={choice.value} disabled={choice.requiresReview}>{choice.label}</option>)}</select></div><LoadMore query={courses} label={t.course}/><div className='field'><label htmlFor='restricted-learner'>{t.learner}</label><select id='restricted-learner' value={selectedLearnerId} disabled={pending||!complete(courses)||!complete(people)} onChange={event=>{if(pending)return;setLearnerId(event.target.value);remember(courseId,event.target.value);}}><option value=''>{t.learner}</option>{personChoices.map(choice=><option key={choice.value} value={choice.value} disabled={choice.requiresReview}>{choice.label}</option>)}</select></div><LoadMore query={people} label={t.learner}/>{people.loading||courses.loading?<WorkspaceState kind="loading" icon="refresh" description={t.loading} role="status"/>:null}{!complete(courses)||!complete(people)?<WorkspaceState kind="review" icon="people" description={t.completeChoices}/>:null}{courseChoices.some(choice=>choice.requiresReview)||personChoices.some(choice=>choice.requiresReview)?<WorkspaceState kind="review" icon="people" description={t.choiceReview}/>:null}
 {retainedCreate?createRecovery?<p className='notice'>{t.originalAction}</p>:<WorkspaceState kind="review" icon="shield" description={t.invalidOriginal}/>:null}{currentChoices&&(!retainedCreate||createRecovery?.kind==='create')?<><p><bdi>{selectedLearner!.displayName} · {selectedCourse!.title} · {selectedCourse!.className}</bdi></p>{createRecovery?.kind==='create'?<p className='notice'>{createRecovery.input.title} · {createRecovery.input.note} · {date(createRecovery.input.occurredAt)} · UTC</p>:null}<CommandForm key={restrictedDraftKey(selectedCourseId,selectedLearnerId)} title={t.create} path={restrictedPath} draftKey={restrictedDraftKey(selectedCourseId,selectedLearnerId)} fields={[{name:'occurredAt',label:t.occurred,type:'datetime-local',required:true},{name:'title',label:t.recordTitle,required:true},{name:'note',label:t.note,type:'textarea',required:true,maxLength:4000},{name:'confirmFactualRecord',label:t.confirmFact,type:'checkbox',required:true}]} body={values=>{if(!currentChoices)throw new LearningApiError('conflict');return restrictedRecordCreateSchema.parse({courseId:selectedCourseId,learnerId:selectedLearnerId,occurredAt:new Date(String(values.get('occurredAt'))).toISOString(),title:String(values.get('title')),note:String(values.get('note')),confirmFactualRecord:values.get('confirmFactualRecord')==='on'});}} validateReceipt={(receipt,original)=>validateRestrictedReceipt(receipt,original,membership!.userId)} onLockedChange={onLocked} onSaved={saved} onCancel={()=>{setCreating(false);formDrafts.remove(intentSlot);}}/></>:complete(people)&&complete(courses)?<WorkspaceState kind="review" icon="people" description={t.choiceReview}/>:null}</section>:null}
 {!creating&&!selection?<section className='restricted-directory' aria-label={t.directory}><h2 ref={directoryHeading} tabIndex={-1}>{t.directory}</h2><p>{t.chooseRecord}</p>{records.loading?<WorkspaceState kind="loading" icon="refresh" description={t.loading} role="status"/>:sourceReady?records.data.map(record=><button className='button button--quiet' key={record.id} ref={control=>{if(control)directoryButtons.current.set(record.id,control);else directoryButtons.current.delete(record.id);}} type='button' disabled={pending} onClick={event=>openRecord(record,event.currentTarget)}><span><strong><bdi>{record.title}</bdi></strong><small><bdi>{record.learnerName} · {record.courseTitle} · {record.className}</bdi></small><small>{date(record.occurredAt)} · UTC · {t.revision} {record.revision}</small></span></button>):null}<LoadMore query={records} label={t.directory}/>{complete(records)&&!records.data.length?<WorkspaceState kind="empty" icon="shield" description={t.empty}/>:null}</section>:null}
 {selection&&!creating?<><Button type='button' variant='quiet' disabled={pending} onClick={back}>{t.back}</Button>{records.loading?<WorkspaceState kind="loading" icon="refresh" description={t.loading} role="status"/>:!selectedRecord?<WorkspaceState kind={sourceError?"unavailable":"review"} icon="shield" description={sourceError?t.recordUnavailable:t.sourceChanged} role="status"/>:null}</>:null}
 {selectedRecord&&!creating?[selectedRecord].map(record=><article className='restricted-reader' key={record.id}><h2 ref={readerHeading} tabIndex={-1}>{record.title}</h2><p><bdi>{record.learnerName} · {record.courseTitle} · {record.className}</bdi></p><p><bdi>{record.authorName}</bdi> · <time dateTime={record.occurredAt}>{date(record.occurredAt)} · UTC</time></p><p className='lesson-content' dir='auto'>{record.note}</p><Status>{record.state==='AWAITING_REVIEW'?t.awaiting:record.state==='APPROVED_FOLLOW_UP'?t.approved:record.state==='COMPLETED'?t.completed:t.progress}</Status>{record.followUpInstructions?<p dir='auto'>{record.followUpInstructions}</p>:null}{record.followUpNote?<p dir='auto'>{record.followUpNote}</p>:null}<Button type='button' variant='quiet' disabled={pending} onClick={()=>{setHistoryCursor(null);setHistoryId(historyId===record.id?null:record.id);}}>{t.history}</Button>
 {historyId===record.id?<section>{historyQuery.loading?<WorkspaceState kind="loading" icon="refresh" description={t.loading} role="status"/>:historyQuery.error?<LearningError error={historyQuery.error}/>:history?.items.map(revision=><article key={revision.id}><h4>{revision.title}</h4><p>{t.revision}: {revision.revision}</p><p dir='auto'>{revision.note}</p><p dir='auto'>{revision.reason}</p><p>{revision.actorName??t.nameUnavailable} · {date(revision.createdAt)} · UTC</p>{revision.followUpOwnerName?<p>{revision.followUpOwnerName}</p>:null}{revision.followUpInstructions?<p>{revision.followUpInstructions}</p>:null}{revision.followUpNote?<p>{revision.followUpNote}</p>:null}{revision.policyVersion?<details><summary>{t.provenance}</summary><p>{t.policyVersion}: {revision.policyVersion}</p><bdi>{revision.policyId}</bdi></details>:null}</article>)}{history?.nextCursor?<Button type='button' variant='quiet' disabled={pending} onClick={()=>setHistoryCursor(history.nextCursor)}>{t.moreHistory}</Button>:null}</section>:null}
 <div className='learning-actions'>{membership!.role==='admin'&&policy!.ownerId===membership!.userId&&record.state==='AWAITING_REVIEW'?<Button type='button' disabled={pending} onClick={()=>openAction(record,'approve')}>{t.approve}</Button>:null}{record.authorId===membership!.userId?<Button type='button' variant='quiet' disabled={pending} onClick={()=>openAction(record,'correct')}>{t.correct}</Button>:null}{membership!.role==='teacher'&&record.followUpOwnerId===membership!.userId&&['APPROVED_FOLLOW_UP','IN_PROGRESS'].includes(record.state)?<Button type='button' disabled={pending} onClick={()=>openAction(record,'followup')}>{t.followup}</Button>:null}</div>
 {action?.id===record.id?<section><p>{t.currentRevision}: {action.revision}</p>{retainedAction?<><p className='notice'>{t.originalAction}</p><p className='restricted-original-input' dir='auto'>{[retainedAction.body.title,retainedAction.body.note,retainedAction.body.instructions,retainedAction.body.reason].filter(value=>typeof value==='string').join(' · ')}</p></>:record.revision!==action.revision?<WorkspaceState kind="review" icon="shield" description={t.sourceChanged}/>:null}<fieldset disabled={pending}>{!complete(records)?<><WorkspaceState kind="unknown" icon="refresh" description={t.completeChoices}/><LoadMore query={records} label={t.directory}/></>:null}{action.kind==='approve'&&!complete(courses)?<><WorkspaceState kind="unknown" icon="learning" description={t.completeChoices}/><LoadMore query={courses} label={t.course}/></>:null}</fieldset>{action.kind==='approve'?<><fieldset disabled={pending}><LoadMore query={people} label={t.owner}/></fieldset>{!complete(people)?<WorkspaceState kind="review" icon="people" description={t.completeChoices}/>:null}</>:null}{actionReady&&actionPath?<CommandForm key={`${actionPath}:${action.revision}`} title={action.kind==='approve'?t.approve:action.kind==='correct'?t.correct:t.followup} path={actionPath} draftKey={`${actionPath}:review:${action.revision}`} fields={actionFields} body={values=>{if(!actionPermitted||record.revision!==action.revision)throw new LearningApiError('conflict');const input:Record<string,unknown>={expectedRevision:action.revision,...(action.kind==='approve'?{followUpOwnerId:String(values.get('followUpOwnerId')),instructions:String(values.get('instructions')),reason:String(values.get('reason')),confirmApproval:values.get('confirmApproval')==='on'}:action.kind==='correct'?{title:String(values.get('title')),note:String(values.get('note')),reason:String(values.get('reason')),confirmCorrection:values.get('confirmCorrection')==='on'}:{status:String(values.get('status')),note:String(values.get('note')),confirmManualAction:values.get('confirmManualAction')==='on'})};if(action.kind==='approve'&&!ownerChoices.some(choice=>choice.value===input.followUpOwnerId&&!choice.requiresReview))throw new LearningApiError('conflict');return(action.kind==='correct'?restrictedRecordCorrectionSchema:action.kind==='approve'?restrictedFollowUpApprovalSchema:restrictedFollowUpSchema).parse(input);}} validateReceipt={(receipt,original)=>validateRestrictedReceipt(receipt,original,membership!.userId,action)} onLockedChange={onLocked} onSaved={saved} onCancel={()=>{setAction(null);formDrafts.remove(intentSlot);}}/>:null}</section>:null}
 </article>):null}{selection&&!selectedRecord&&!creating?<LoadMore query={records} label={t.directory}/>:null}{originalAction&&!action&&!sourceError?<WorkspaceState kind="review" icon="shield" description={t.pendingRecordNotLoaded}/>:null}</>:null}
 </section>;
}
