import { createHash } from 'node:crypto';
import { mkdir, open, readFile, lstat, realpath } from 'node:fs/promises';
import { join, resolve, isAbsolute } from 'node:path';
import { z } from 'zod';
import { canonicalReleaseExecutionJson } from '../verification/release-review';
import { readBackendReleaseAdmission } from '../verification/backend-release-admission';
import { validatePreparedBackendReleaseIntent, type BackendReleaseExpected } from '../verification/backend-release-contracts';
import { readHostedMigrationProvider, hostedMigrationEndpointSchema, requireCurrentHostedMigrationEndpoint } from './hosted-migration-provider';
import { canonicalHostedMigrationPlan, readCanonicalMigrationSources, type HostedMigrationPlanV1 } from './hosted-migration-plan';
import { admitHostedMigrationStageFiles } from './hosted-migration-stage-files';
import { verifyHostedMigrationHistory } from './hosted-migration-history';
import { createHostedMigrationDatabase, hostedSyntheticSeedSha256, readOriginalSyntheticSeed } from './hosted-migration-database';
import { readHostedOperatorStorageInventory } from './hosted-operator-storage-inventory';
import { validateHostedReferencePopulation } from './hosted-reference-population';
const same=(left:unknown,right:unknown)=>canonicalReleaseExecutionJson(left)===canonicalReleaseExecutionJson(right);
import type { HostedMigrationWorkdirs } from './hosted-migration-workdirs';

const failure=()=>Error('Hosted initial synthetic population requires review; contents withheld.'),hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');

const digest=z.string().regex(/^[a-f0-9]{64}$/),token=z.string().min(20).max(4096).regex(/^[\x21-\x7e]+$/);
const schema=z.object({repoRoot:z.string(),endpoint:hostedMigrationEndpointSchema,expected:z.unknown(),preparedApproval:z.unknown(),githubToken:token,providerToken:token,journalStorageKey:token,operatorStoragePolicyPath:z.string(),certificate:z.object({path:z.string(),sha256:digest}).strict(),migrationPassword:token,plan:z.unknown(),finalStage:z.unknown()}).strict();
export type HostedSyntheticPopulationResult={status:'POPULATED_CONFIRMED'|'NOOP'|'REQUIRES_REVIEW';commitment:'CONFIRMED'|'UNKNOWN'|'NOT_ATTEMPTED';seedSha256:string;operationSha256:string|null;receiptPath:string|null;cleanupCode:'LOCK_RELEASE_UNCONFIRMED'|null;hostedAcceptance:false};
/** Original seed execution only. Local append-only receipts are retained by the
 * workflow. Unknown original intent cannot become a new automatic seed attempt. */
export async function seedHostedSyntheticPopulation(value:unknown):Promise<HostedSyntheticPopulationResult>{
 const result:HostedSyntheticPopulationResult={status:'REQUIRES_REVIEW',commitment:'NOT_ATTEMPTED',seedSha256:hostedSyntheticSeedSha256,operationSha256:null,receiptPath:null,cleanupCode:null,hostedAcceptance:false};let attempted=false;
 try{const input=schema.parse(JSON.parse(canonicalReleaseExecutionJson(value))),root=input.repoRoot;if(!isAbsolute(root)||resolve(root)!==root||await realpath(root)!==root)throw failure();const expected=input.expected as BackendReleaseExpected,prepared=validatePreparedBackendReleaseIntent(input.preparedApproval,{...expected,now:Date.now()}),plan=JSON.parse(canonicalHostedMigrationPlan(input.plan as HostedMigrationPlanV1).json) as HostedMigrationPlanV1,stage=input.finalStage as HostedMigrationWorkdirs['stages'][number];if(stage.id!=='remaining'||plan.source.sha!==expected.releaseSha||plan.source.tree!==expected.treeSha||plan.projectRef!==expected.targets.supabase.projectRef||canonicalHostedMigrationPlan(plan).sha256!==expected.fingerprints.migrationPlanSha256)throw failure();const loaded=readCanonicalMigrationSources({repoRoot:root,sourceSha:expected.releaseSha,treeSha:expected.treeSha});await readOriginalSyntheticSeed(root);const manifestBytes=await readFile(join(root,'supabase/seed/identities.json'));if(hash(manifestBytes)!=='7464b3487adc3998d8f4ad4582ffd08ebafbdc8fd9a568433ddc687f4f03ac21')throw failure();const manifest=JSON.parse(manifestBytes.toString()) as Parameters<typeof validateHostedReferencePopulation>[1];const identity={projectRef:plan.projectRef,sourceSha:expected.releaseSha,treeSha:expected.treeSha,planSha256:canonicalHostedMigrationPlan(plan).sha256,stageId:stage.id,stageSha256:hash(JSON.stringify({included:stage.included.map(row=>({name:row.name,version:row.version,sha256:row.sha256})),configSha256:stage.configSha256})),databaseUrl:`postgresql://${input.endpoint.kind==='direct'?'postgres':'postgres.'+plan.projectRef}@${input.endpoint.host}:5432/postgres?sslmode=verify-full`,approvalDigest:prepared.sha256,ciRunId:expected.ciRunId,certificateSha256:input.certificate.sha256};const operation={purpose:'CUEVO_INITIAL_SYNTHETIC_POPULATION',...identity,seedSha256:hostedSyntheticSeedSha256},operationSha256=hash(canonicalReleaseExecutionJson(operation));result.operationSha256=operationSha256;const receiptRoot=join(root,'.local/hosted-release','population-'+plan.projectRef),intentPath=join(receiptRoot,'intent.json'),outcomePath=join(receiptRoot,'outcome.json');result.receiptPath=outcomePath;
 const official=async()=>{const current=await readBackendReleaseAdmission({effectScope:'SCHEMA_AND_SYNTHETIC_AUTH',repoRoot:root,expected,prepared,githubToken:input.githubToken});if(current.provenance!=='OFFICIAL_GITHUB_AND_VERIFIED_GIT_SOURCE'||current.approval.packageSha256!==prepared.sha256)throw failure();};await official();const provider=await readHostedMigrationProvider({projectRef:plan.projectRef,boundProjectRef:expected.targets.supabase.projectRef,providerToken:input.providerToken});if(provider.observedAtMs>Date.now()||Date.now()-provider.observedAtMs>30000||requireCurrentHostedMigrationEndpoint(input.endpoint,provider,expected.fingerprints.migrationEndpointSha256).host!==new URL(identity.databaseUrl).hostname)throw failure();const db=await createHostedMigrationDatabase({repoRoot:root,projectRef:plan.projectRef,databaseUrl:identity.databaseUrl,certificate:input.certificate,password:input.migrationPassword});
 const persist=async(path:string,record:unknown)=>{const handle=await open(path,'wx',0o600);try{await handle.writeFile(canonicalReleaseExecutionJson(record));await handle.sync();}finally{await handle.close();}const dir=await open(receiptRoot,'r');try{await dir.sync();}finally{await dir.close();}};
 const revalidate=async()=>{await official();const provider=await readHostedMigrationProvider({projectRef:plan.projectRef,boundProjectRef:expected.targets.supabase.projectRef,providerToken:input.providerToken});requireCurrentHostedMigrationEndpoint(input.endpoint,provider,expected.fingerprints.migrationEndpointSha256);await readOriginalSyntheticSeed(root);await admitHostedMigrationStageFiles({repoRoot:root,sourceSha:expected.releaseSha,treeSha:expected.treeSha,plan,stage});const target=await db.observeTarget();verifyHostedMigrationHistory({sources:loaded.sources,included:stage.included,expectedVersions:stage.expectedAfterVersions,history:target.historyPresent?target.history:null});const post=await db.observeStage({stageId:'remaining',expectedAfterVersions:stage.expectedAfterVersions});if(post.observedAtMs>Date.now()||Date.now()-post.observedAtMs>30000||target.observedAtMs>Date.now()||Date.now()-target.observedAtMs>30000||Object.values(post.checks).some(check=>check!==true)||target.authUsers!==0)throw failure();const storage=await readHostedOperatorStorageInventory({repoRoot:root,sourceSha:expected.releaseSha,treeSha:expected.treeSha,projectRef:plan.projectRef,boundProjectRef:expected.targets.supabase.projectRef,providerToken:input.providerToken,storageKey:input.journalStorageKey,identity,expectedVersions:stage.expectedAfterVersions});if(storage.observedAtMs>Date.now()||Date.now()-storage.observedAtMs>30000||Date.now()-target.observedAtMs>30000||Date.now()-post.observedAtMs>30000||storage.applicationStorageObjects!==0||storage.totalStorageObjects!==target.storageObjects||storage.operations.some(operation=>operation.state!=='COMMITTED'))throw failure();return db.observeSyntheticPopulation();};
 const released=await db.withLock(`${plan.projectRef}:HOSTED_SCHEMA_MIGRATION`,async()=>{let prior=false;try{await lstat(receiptRoot);prior=true;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw failure();}if(prior){const dirStat=await lstat(receiptRoot);if(!dirStat.isDirectory()||dirStat.isSymbolicLink()||await realpath(receiptRoot)!==receiptRoot)throw failure();for(const path of [intentPath,outcomePath]){const stat=await lstat(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size>16384||await realpath(path)!==path)throw failure();}const intent=JSON.parse((await readFile(intentPath)).toString()),outcome=JSON.parse((await readFile(outcomePath)).toString());if(!same(intent.operation,operation)||outcome.status!=='POPULATED_CONFIRMED'||!same(outcome.operation,operation))throw failure();validateHostedReferencePopulation(await revalidate(),manifest);result.status='NOOP';result.commitment='CONFIRMED';return;}const before=await revalidate();if(before.authUsers.length||Object.values(before.population).some(rows=>rows.length))throw failure();await mkdir(receiptRoot,{mode:0o700});await persist(intentPath,{version:1,state:'INTENT',operation,operationSha256});const finalBefore=await revalidate();if(finalBefore.authUsers.length||Object.values(finalBefore.population).some(rows=>rows.length))throw failure();attempted=true;result.commitment='UNKNOWN';try{await db.executeOriginalSyntheticSeed();const after=await revalidate();validateHostedReferencePopulation(after,manifest);await persist(outcomePath,{version:1,status:'POPULATED_CONFIRMED',operation,operationSha256});result.status='POPULATED_CONFIRMED';result.commitment='CONFIRMED';}catch{await persist(outcomePath,{version:1,status:'REQUIRES_REVIEW',operation,operationSha256}).catch(()=>undefined);throw failure();}});if(released.kind!=='RELEASED'){result.status='REQUIRES_REVIEW';result.cleanupCode='LOCK_RELEASE_UNCONFIRMED';}return result;
 }catch{return{...result,status:'REQUIRES_REVIEW',commitment:attempted?'UNKNOWN':'NOT_ATTEMPTED'};}
}
