import assert from 'node:assert/strict';
import {test} from 'node:test';
import {originalNativeIntentFixture} from './hosted-original-native-intent.fixture';
test('strict original native template retains exact original record bytes and produces only an evidence fingerprint',async()=>{
 const subject:Record<string,unknown>=await import('./hosted-original-native-intent').catch(()=>({}));assert.equal(typeof subject.parseOriginalNativeIntentTemplate,'function');const parse=subject.parseOriginalNativeIntentTemplate as(v:unknown)=>ReturnType<typeof originalNativeIntentFixture>,fingerprint=subject.originalNativeIntentFingerprint as(v:unknown)=>Record<string,unknown>,value=originalNativeIntentFixture(),parsed=parse(value);assert.equal(parsed.ownerJson,value.ownerJson);assert.equal(parsed.record1Json,value.record1Json);assert.equal(fingerprint(value).beforeCount,123);assert.equal(fingerprint(value).afterCount,124);assert.equal(fingerprint(value).originalOperationSha256,value.selection.originalOperationSha256);assert.equal(Object.hasOwn(fingerprint(value),'effectAuthority'),false);
});
test('altered original bytes history source stage clocks protocol and extra fields refuse',async()=>{
 const subject=await import('./hosted-original-native-intent');for(const mode of ['owner','record','history','source','stage','pending','clock','protocol','selection','unknown']){const value=originalNativeIntentFixture();if(mode==='owner')value.ownerJson+=' ';if(mode==='record')value.record1Json=value.record1Json.replace('INTENT','COMMITTED');if(mode==='history')value.beforeHistorySha256='f'.repeat(64);if(mode==='source')value.originalIdentity.sourceSha='f'.repeat(40);if(mode==='stage')value.stageRows[0].sha256='f'.repeat(64);if(mode==='pending')value.pendingRow={...value.stageRows[0]};if(mode==='clock')value.originalResult.effectCompletedAt=value.originalPackage.expiresAt;if(mode==='protocol')value.originalResult.protocol.commitment='UNKNOWN';if(mode==='selection')value.selection.runAttempt=2;if(mode==='unknown')Object.assign(value,{effectAuthority:true});assert.throws(()=>subject.parseOriginalNativeIntentTemplate(value),mode);}
});
test('fresh package keeps current source separate while exact original native stage bytes and executable identity remain required',async()=>{
 const s=await import('./hosted-original-native-intent'),t=originalNativeIntentFixture(),targets={supabase:{projectRef:t.originalIdentity.projectRef}},hash=(await import('node:crypto')).createHash('sha256').update((await import('../verification/release-review')).canonicalReleaseExecutionJson(targets)).digest('hex');t.originalPackage.targetsSha256=hash;const fingerprint=s.originalNativeIntentFingerprint(t),current={version:2,delivery:{kind:'DATABASE_ONLY',apiRoot:null,edgeRoot:null},expected:{repository:t.selection.repository,executionScope:'schema-and-accounts',releaseSha:'a'.repeat(40),treeSha:'b'.repeat(40),releaseRunId:'51',runAttempt:1,installedSchema:{sourceSha:t.originalIdentity.sourceSha,treeSha:t.originalIdentity.treeSha,migrationCount:123},schemaRecovery:t.schemaRecovery,originalNativeIntentRecovery:fingerprint,targets,fingerprints:{apiArtifactSha256:null,edgeArtifactSha256:null,denoLockSha256:null}},plan:{mode:'INCREMENTAL',projectRef:t.originalIdentity.projectRef,source:{sha:'a'.repeat(40),tree:'b'.repeat(40)},migrations:t.stageRows,applied:t.stageRows.slice(0,123).map(({version,sha256})=>({version,sha256})),stages:[{id:'prefix',names:[]},{id:'native',names:[t.pendingRow.name]},{id:'pre-observability',names:[]},{id:'remaining',names:[]}],dispatch:'DISABLED',seed:'DISABLED',vault:'DISABLED'},stages:[{}, {id:'native',included:t.stageRows,pending:[t.pendingRow],configSha256:t.configSha256,workdir:'/fresh/native',commandArgs:t.commandArgs.map(v=>v==='<WORKDIR>'?'/fresh/native':v)},{},{}],migrationEndpoint:t.migrationEndpoint,toolchain:{...t.toolchain,sourceSha:'a'.repeat(40),treeSha:'b'.repeat(40)}};assert.equal(s.validateOriginalNativeIntentPackageCompatibility(t,current).effectAuthority,false);
 for(const mode of ['source','count','rows','pending','config','endpoint','toolchain','mixed','binding']){const c=structuredClone(current);if(mode==='source')c.expected.releaseSha=t.originalIdentity.sourceSha;if(mode==='count')c.expected.installedSchema.migrationCount=124;if(mode==='rows')c.plan.migrations[0].sha256='f'.repeat(64);if(mode==='pending')c.plan.stages[1].names.push(t.stageRows[0].name);if(mode==='config')(c.stages[1]as{configSha256:string}).configSha256='f'.repeat(64);if(mode==='endpoint')c.migrationEndpoint.host='db.'+t.originalIdentity.projectRef+'.supabase.co';if(mode==='toolchain')c.toolchain.cli.binarySha256='f'.repeat(64);if(mode==='mixed')Object.assign(c.expected,{pendingRuntimeConfirmation:{}});if(mode==='binding')c.expected.originalNativeIntentRecovery.templateSha256='f'.repeat(64);assert.throws(()=>s.validateOriginalNativeIntentPackageCompatibility(t,c),mode);}
});
test('linked terminal requires exact selected template history current identity run and ordered proof clocks',async()=>{
 const subject:Record<string,unknown>=await import('./hosted-original-native-intent'),t=originalNativeIntentFixture();assert.equal(typeof subject.validateOriginalNativeIntentTerminal,'function');const validate=subject.validateOriginalNativeIntentTerminal as(v:unknown,c:unknown)=>{version:number;state:string},fingerprint=(subject.originalNativeIntentFingerprint as(v:unknown)=>{templateSha256:string;selectionSha256:string})(t),currentIdentity={...t.originalIdentity,sourceSha:'a'.repeat(40),treeSha:'b'.repeat(40),planSha256:'c'.repeat(64),ciRunId:'52',approvalDigest:'d'.repeat(64)},context={template:t,currentIdentity,currentRunId:'53',currentRunAttempt:1},terminal={version:2,identity:t.originalIdentity,state:'COMMITTED',schemaHistoryAtomic:false,evidence:'SUPPLIED_PORT_EXECUTION_ONLY',originalIntentExecution:{version:1,purpose:'CUEVO_ORIGINAL_NATIVE_INTENT_EXECUTION',originalOperationSha256:t.originalOperationSha256,originalIntentSha256:t.originalIntentSha256,templateSha256:fingerprint.templateSha256,selectionSha256:fingerprint.selectionSha256,currentExecutionIdentity:currentIdentity,runId:'53',runAttempt:1,approvalObservedAtMs:100,nativeProofBeganAtMs:101,beforeHistorySha256:t.beforeHistorySha256,afterHistorySha256:t.afterHistorySha256}};assert.equal(validate(terminal,context).state,'COMMITTED');assert.equal(validate({...terminal,state:'REQUIRES_REVIEW'},context).state,'REQUIRES_REVIEW');
 for(const mode of ['before-history','after-history','template','selection','run','attempt','current-source','original-source','intent','clock','version','extra-context']){const value=structuredClone(terminal),expected=structuredClone(context);if(mode==='before-history')value.originalIntentExecution.beforeHistorySha256='f'.repeat(64);if(mode==='after-history')value.originalIntentExecution.afterHistorySha256='f'.repeat(64);if(mode==='template')value.originalIntentExecution.templateSha256='f'.repeat(64);if(mode==='selection')value.originalIntentExecution.selectionSha256='f'.repeat(64);if(mode==='run')value.originalIntentExecution.runId='54';if(mode==='attempt')value.originalIntentExecution.runAttempt=2;if(mode==='current-source')value.originalIntentExecution.currentExecutionIdentity.sourceSha='f'.repeat(40);if(mode==='original-source')value.identity.sourceSha='f'.repeat(40);if(mode==='intent')value.originalIntentExecution.originalIntentSha256='f'.repeat(64);if(mode==='clock')value.originalIntentExecution.nativeProofBeganAtMs=99;if(mode==='version')value.version=1;if(mode==='extra-context')Object.assign(expected,{owned:true});assert.throws(()=>validate(value,expected),mode);}
});
test('original native attempt fence binds conservative state original hashes current identity and one current run',async()=>{
 const subject:Record<string,unknown>=await import('./hosted-original-native-intent'),t=originalNativeIntentFixture();assert.equal(typeof subject.validateOriginalNativeIntentAttempt,'function');const validate=subject.validateOriginalNativeIntentAttempt as(v:unknown,c:unknown)=>Record<string,unknown>,fingerprint=(subject.originalNativeIntentFingerprint as(v:unknown)=>{templateSha256:string;selectionSha256:string})(t),currentIdentity={...t.originalIdentity,sourceSha:'a'.repeat(40),treeSha:'b'.repeat(40),planSha256:'c'.repeat(64),ciRunId:'52',approvalDigest:'d'.repeat(64)},context={template:t,currentIdentity,currentRunId:'53',currentRunAttempt:1},attempt={version:1,purpose:'CUEVO_ORIGINAL_NATIVE_INTENT_ATTEMPT_FENCE',state:'MAY_HAVE_STARTED',originalOperationSha256:t.originalOperationSha256,originalIntentSha256:t.originalIntentSha256,templateSha256:fingerprint.templateSha256,selectionSha256:fingerprint.selectionSha256,currentExecutionIdentity:currentIdentity,runId:'53',runAttempt:1,beforeHistorySha256:t.beforeHistorySha256,afterHistorySha256:t.afterHistorySha256,reservedAtMs:200};assert.deepEqual(validate(attempt,context),attempt);assert.equal(Object.hasOwn(validate(attempt,context),'effectAuthority'),false);
 for(const mode of ['operation','intent','template','selection','before-history','after-history','current-source','run','attempt','state','clock-negative','clock-unsafe','clock-fraction','extra','extra-context']){const value=structuredClone(attempt),expected=structuredClone(context);if(mode==='operation')value.originalOperationSha256='f'.repeat(64);if(mode==='intent')value.originalIntentSha256='f'.repeat(64);if(mode==='template')value.templateSha256='f'.repeat(64);if(mode==='selection')value.selectionSha256='f'.repeat(64);if(mode==='before-history')value.beforeHistorySha256='f'.repeat(64);if(mode==='after-history')value.afterHistorySha256='f'.repeat(64);if(mode==='current-source')value.currentExecutionIdentity.sourceSha='f'.repeat(40);if(mode==='run')value.runId='54';if(mode==='attempt')value.runAttempt=2;if(mode==='state')value.state='CONFIRMED';if(mode==='clock-negative')value.reservedAtMs=-1;if(mode==='clock-unsafe')value.reservedAtMs=Number.MAX_SAFE_INTEGER+1;if(mode==='clock-fraction')value.reservedAtMs=200.5;if(mode==='extra')Object.assign(value,{cliActuallyStarted:true});if(mode==='extra-context')Object.assign(expected,{owned:true});assert.throws(()=>validate(value,expected),mode);}
});
