import { Client } from 'pg';
import { createHash, randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { lstat, open, realpath } from 'node:fs/promises';
import { isAbsolute, join, relative, resolve } from 'node:path';
import { TLSSocket, checkServerIdentity } from 'node:tls';
import { types } from 'node:util';
import { z } from 'zod';
import type { HostedExecutionPorts } from './hosted-migration-execution';

// node-postgres supports a per-query read timeout; its declarations omit it.
declare module 'pg' { interface QueryConfig { query_timeout?: number } }

const failure=()=>new Error('Hosted migration database identity, TLS or lock requires review; contents withheld.');
const digest=z.string().regex(/^[a-f0-9]{64}$/);
const inputSchema=z.object({repoRoot:z.string(),projectRef:z.string().regex(/^[a-z]{20}$/),databaseUrl:z.string().max(400),certificate:z.object({path:z.string(),sha256:digest}).strict(),password:z.string().min(1).max(24576).refine(value=>value.trim().length>0&&[...value].every(c=>c.charCodeAt(0)>31&&c.charCodeAt(0)!==127))}).strict();
const rawHistoryRow=z.object({version:z.string().regex(/^\d{14}$/),name:z.string().max(200),statements:z.array(z.string().max(2*1024*1024)).max(20000)}).strict();
const identityRow=z.object({operator:z.literal('postgres'),database:z.literal('postgres'),ssl:z.literal(true),serverVersion:z.number().int().min(170000).max(179999)}).strict();
type Input=z.infer<typeof inputSchema>;
export type HostedMigrationDatabaseObservation={operator:'postgres';database:'postgres';serverVersion:number;tls:{kind:'PEER_VERIFIED';host:string;certificateSha256:string;peerCertificateSha256:string;protocol:string};historyPresent:boolean;history:z.infer<typeof rawHistoryRow>[]};
export type HostedMigrationStageId='prefix'|'native'|'pre-observability'|'remaining';
export type HostedMigrationTargetObservation=HostedMigrationDatabaseObservation&{observedAtMs:number;authUsers:number;storageObjects:number;appSchemas:('app'|'authorization'|'internal')[];runtimeRoles:('cuevo_api'|'cuevo_worker')[];schools:number|null};
export type HostedMigrationStageObservation={observedAtMs:number;stageId:HostedMigrationStageId;checks:{foundation:boolean|null;rls:boolean|null;privateRelations:boolean|null;privateFunctions:boolean|null;runtimeRoles:boolean|null;nativeSourceBridge:boolean|null;curriculumLifecycle:boolean|null;dispatchInactive:boolean|null;analyticsInactive:boolean|null;recoveryCronInactive:boolean|null;transportPrivate:boolean|null}};
export type HostedMigrationDatabase=Pick<HostedExecutionPorts,'withLock'>&{readonly signal:AbortSignal;observe():Promise<HostedMigrationDatabaseObservation>;observeTarget():Promise<HostedMigrationTargetObservation>;observeStage(input:{stageId:HostedMigrationStageId;expectedAfterVersions:string[]}):Promise<HostedMigrationStageObservation>};
const count=z.union([z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),z.string().regex(/^(0|[1-9][0-9]*)$/).refine(value=>Number.isSafeInteger(Number(value)))]).transform(value=>Number(value));
const targetSchema=z.object({authUsers:count,storageObjects:count,appSchemas:z.array(z.enum(['app','authorization','internal'])).max(3),runtimeRoles:z.array(z.enum(['cuevo_api','cuevo_worker'])).max(2),schoolsPresent:z.boolean()});
const baseStageSchema=z.object({foundation:z.boolean(),rls:z.boolean(),privateRelations:z.boolean(),privateFunctions:z.boolean(),runtimeRoles:z.boolean()});
const capabilities={foundation:'20260930234201',native:'20261002021737',lifecycle:'20261002021206',wake:'20261002122236',analytics:'20261002182213',transport:'20261005132902'};
function stageInput(value:unknown){
 if(!value||typeof value!=='object'||types.isProxy(value)||![Object.prototype,null].includes(Object.getPrototypeOf(value)))throw failure();const keys=Reflect.ownKeys(value);if(keys.length!==2||!keys.includes('stageId')||!keys.includes('expectedAfterVersions'))throw failure();const fields=keys.map(key=>Object.getOwnPropertyDescriptor(value,key));if(fields.some(field=>!field||!('value'in field)||!field.enumerable))throw failure();const stageId=z.enum(['prefix','native','pre-observability','remaining']).parse(Object.getOwnPropertyDescriptor(value,'stageId')!.value),array=Object.getOwnPropertyDescriptor(value,'expectedAfterVersions')!.value;if(!Array.isArray(array)||types.isProxy(array)||array.length>1000||Reflect.ownKeys(array).length!==array.length+1)throw failure();const versions:string[]=[];for(let i=0;i<array.length;i++){const field=Object.getOwnPropertyDescriptor(array,String(i));if(!field||!('value'in field)||!field.enumerable)throw failure();versions.push(z.string().regex(/^[0-9]{14}$/).parse(field.value));}if(new Set(versions).size!==versions.length)throw failure();return{stageId,versions};
}
const baseStageSql=`/* CUEVO_STAGE_BASE: source000_foundation_contract, no data projection */
select
 current_setting('check_function_bodies')='on' and (select count(*) from pg_namespace where nspname in('app','internal','authorization'))=3
 and to_regclass('app.schools') is not null and to_regclass('app.memberships') is not null and to_regclass('internal.audit_events') is not null and to_regclass('internal.idempotency_keys') is not null and to_regclass('internal.outbox_events') is not null as foundation,
 not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('app','internal') and c.relkind in('r','p') and(not c.relrowsecurity or not c.relforcerowsecurity)) as rls,
 not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.rolname in('anon','authenticated','service_role') where n.nspname in('app','internal','authorization') and c.relkind in('r','v','m','f','p','S') and(case when c.relkind='S' then has_sequence_privilege(r.oid,c.oid,'USAGE,SELECT,UPDATE') else has_table_privilege(r.oid,c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN') or has_any_column_privilege(r.oid,c.oid,'SELECT,INSERT,UPDATE,REFERENCES') end))
 and not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault(case when c.relkind='S' then 'S'::"char" else 'r'::"char" end,c.relowner)))a where n.nspname in('app','internal','authorization') and c.relkind in('r','v','m','f','p','S') and a.grantee=0)
 and not exists(select 1 from pg_attribute col join pg_class c on c.oid=col.attrelid join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(col.attacl)a where n.nspname in('app','internal','authorization') and col.attnum>0 and not col.attisdropped and a.grantee=0) as "privateRelations",
 not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_roles r on r.rolname in('anon','authenticated','service_role') where n.nspname in('app','internal','authorization') and has_function_privilege(r.oid,p.oid,'EXECUTE') and not coalesce(r.rolname='authenticated' and p.oid=to_regprocedure('authorization.community_realtime_topic(text)'),false))
 and not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a where n.nspname in('app','internal','authorization') and a.grantee=0 and a.privilege_type='EXECUTE')
 and not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('internal','authorization') and p.prosecdef and not coalesce(p.proconfig @> array['search_path=""'],false)) as "privateFunctions",
 (select count(*) from pg_roles where rolname in('cuevo_api','cuevo_worker') and not rolsuper and not rolbypassrls and not rolcreaterole and not rolcreatedb and not rolreplication and not rolinherit and not rolcanlogin)=2
 and not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.oid=c.relowner where n.nspname in('app','internal','authorization') and r.rolname in('cuevo_api','cuevo_worker'))
 and not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_roles r on r.oid=p.proowner where n.nspname in('app','internal','authorization') and r.rolname in('cuevo_api','cuevo_worker'))
 and not exists(select 1 from pg_namespace n join pg_roles r on r.oid=n.nspowner where n.nspname in('app','internal','authorization') and r.rolname in('cuevo_api','cuevo_worker'))
 and not exists(select 1 from pg_auth_members membership join pg_roles member on member.oid=membership.member where member.rolname in('cuevo_api','cuevo_worker')) as "runtimeRoles"`;
const nativeBridgeSql=`/* CUEVO_NATIVE_BRIDGE: migration20261002021737/test163 */ select
 coalesce((select relkind='r' and relrowsecurity and relforcerowsecurity from pg_class where oid=to_regclass('internal.academic_result_sources')),false)
 and (select count(*) from pg_trigger where not tgisinternal and tgname='register_native_academic_source' and tgrelid in(to_regclass('app.result_revisions'),to_regclass('app.rubric_result_revisions')) and tgfoid=to_regprocedure('internal.register_native_academic_source()') and tgenabled in('O','A'))=2
 and (select count(*) from pg_trigger where not tgisinternal and tgrelid=to_regclass('internal.academic_result_sources') and tgname in('academic_source_immutable','academic_source_no_truncate') and tgfoid=to_regprocedure('internal.academic_history_immutable()') and tgenabled in('O','A'))=2
 and to_regprocedure('internal.native_academic_source(uuid,uuid)') is not null and to_regprocedure('internal.native_academic_source_allowed(uuid,uuid,boolean)') is not null and to_regprocedure('internal.read_native_academic_source(uuid)') is not null
 and not has_table_privilege('cuevo_api','internal.academic_result_sources','SELECT,INSERT,UPDATE,DELETE') and not has_table_privilege('cuevo_worker','internal.academic_result_sources','SELECT,INSERT,UPDATE,DELETE') and not has_function_privilege('cuevo_api','internal.native_academic_source(uuid,uuid)','EXECUTE') and has_function_privilege('cuevo_api','internal.read_native_academic_source(uuid)','EXECUTE') as "nativeSourceBridge"`;
const lifecycleSql=`/* CUEVO_CURRICULUM_LIFECYCLE: migration20261002021206/test164 */ select
 coalesce((select relkind='r' and relrowsecurity and relforcerowsecurity from pg_class where oid=to_regclass('app.curriculum_lifecycle_revisions')),false)
 and to_regprocedure('internal.curriculum_open_work_count(uuid,uuid)') is not null and to_regprocedure('internal.current_curriculum_lifecycle(uuid,uuid)') is not null
 and (select count(*) from pg_trigger where not tgisinternal and tgrelid=to_regclass('app.curriculum_lifecycle_revisions') and tgname in('lifecycle_immutable','lifecycle_no_truncate') and tgfoid=to_regprocedure('internal.academic_history_immutable()') and tgenabled in('O','A'))=2
 and not has_table_privilege('cuevo_api','app.curriculum_lifecycle_revisions','SELECT') as "curriculumLifecycle"`;

const hash=(bytes:Uint8Array|string)=>createHash('sha256').update(bytes).digest('hex');
function privateProcessEnvironment(){if(Object.keys(process.env).some(key=>/^PG/i.test(key)&&process.env[key]!==undefined&&process.env[key]!==''))throw failure();}
function json(value:unknown,depth=0):unknown{
 if(depth>6)throw failure();
 if(value===null||typeof value==='string'||typeof value==='number'||typeof value==='boolean')return value;
 if(!value||typeof value!=='object'||types.isProxy(value)||Array.isArray(value)||![Object.prototype,null].includes(Object.getPrototypeOf(value)))throw failure();
 const output:Record<string,unknown>=Object.create(null);
 for(const key of Reflect.ownKeys(value)){const field=Object.getOwnPropertyDescriptor(value,key);if(typeof key!=='string'||!field||!('value'in field)||!field.enumerable)throw failure();output[key]=json(field.value,depth+1);}
 return output;
}
async function finalTransportBody(repoRoot:string):Promise<string>{
 const file='supabase/migrations/20261005132902_worker_transport_provider_trust_boundary.sql',env=Object.fromEntries(['PATH','Path','SystemRoot','WINDIR','TEMP','TMP'].filter(key=>process.env[key]!==undefined).map(key=>[key,process.env[key]]).concat([['GIT_CONFIG_NOSYSTEM','1'],['GIT_CONFIG_GLOBAL',process.platform==='win32'?'NUL':'/dev/null'],['GIT_NO_REPLACE_OBJECTS','1']]));
 const bytes=execFileSync('git',['-C',repoRoot,'show','HEAD:'+file],{env,stdio:['ignore','pipe','ignore'],timeout:5000,maxBuffer:64*1024,windowsHide:true,shell:false});if(hash(bytes)!=='b936391be7ae4adc8469e0a30602cb1e3e263dbafc454841129a33dce829b0ac')throw failure();const source=new TextDecoder('utf8',{fatal:true}).decode(bytes),marker="create or replace function internal.worker_transport_private()returns boolean\nlanguage plpgsql stable security definer set search_path=''as "+String.fromCharCode(36,36),start=source.indexOf(marker),end=source.indexOf('end'+String.fromCharCode(36,36)+';',start+marker.length);if(start<0||end<0||source.indexOf(marker,start+1)>=0)throw failure();return source.slice(start+marker.length,end+3);
}
async function certificate(input:Input):Promise<string>{
 const root=input.repoRoot,path=input.certificate.path,part=relative(root,path);
 if(!isAbsolute(root)||resolve(root)!==root||await realpath(root)!==root||!isAbsolute(path)||resolve(path)!==path||!part||isAbsolute(part)||part.split(/[\\/]/).some(p=>!p||p==='.'||p==='..')||!part.replaceAll('\\','/').startsWith('.local/hosted-release/'))throw failure();
 let current=root;const pieces=part.split(/[\\/]/);
 for(const[index,piece]of pieces.entries()){current=join(current,piece);const stat=await lstat(current);if(stat.isSymbolicLink()||await realpath(current)!==current||(index===pieces.length-1?!stat.isFile()||stat.nlink!==1:!stat.isDirectory()))throw failure();if(process.platform!=='win32'&&index===pieces.length-1&&(stat.mode&0o077)!==0)throw failure();}
 const gitEnvironment=Object.fromEntries(['PATH','Path','SystemRoot','WINDIR','TEMP','TMP'].filter(key=>process.env[key]!==undefined).map(key=>[key,process.env[key]]).concat([['GIT_CONFIG_NOSYSTEM','1'],['GIT_CONFIG_GLOBAL',process.platform==='win32'?'NUL':'/dev/null'],['GIT_NO_REPLACE_OBJECTS','1']]));
 const checkIgnore=execFileSync('git',['-C',root,'check-ignore','--no-index','--stdin'],{input:part.replaceAll('\\','/')+'\n',encoding:'utf8',stdio:['pipe','pipe','ignore'],timeout:5000,windowsHide:true,shell:false,env:gitEnvironment}).trim();
 if(checkIgnore!==part.replaceAll('\\','/'))throw failure();
 if(execFileSync('git',['-C',root,'ls-files','--cached','--',part.replaceAll('\\','/')],{encoding:'utf8',stdio:['ignore','pipe','ignore'],timeout:5000,windowsHide:true,shell:false,env:gitEnvironment}).length)throw failure();
 const handle=await open(path,'r');try{const before=await handle.stat(),bytes=await handle.readFile();const after=await handle.stat();if(before.ino!==after.ino||before.dev!==after.dev||before.size!==after.size||before.mtimeMs!==after.mtimeMs||before.size>512*1024||hash(bytes)!==input.certificate.sha256||!bytes.toString().includes('-----BEGIN CERTIFICATE-----'))throw failure();return bytes.toString('utf8');}finally{await handle.close();}
}
/** Actual operator connection and session lock. It reads catalog/history only; SQL migration execution remains in its exact CLI consumer. */
export async function createHostedMigrationDatabase(value:unknown):Promise<HostedMigrationDatabase>{
 let input:Input,url:URL,ca:string;
 try{privateProcessEnvironment();input=inputSchema.parse(json(value));url=new URL(input.databaseUrl);const direct=url.hostname===`db.${input.projectRef}.supabase.co`&&url.username==='postgres',pooler=/^aws-[0-9]+-[a-z0-9]+(?:-[a-z0-9]+)*\.pooler\.supabase\.com$/.test(url.hostname)&&url.username===`postgres.${input.projectRef}`;if(url.protocol!=='postgresql:'||url.password||url.port!=='5432'||url.pathname!=='/postgres'||url.search!=='?sslmode=verify-full'||url.hash||!(direct||pooler)||url.toString()!==input.databaseUrl)throw failure();ca=await certificate(input);}catch{throw failure();}
 const controller=new AbortController();let entered=false,active:Client|null=null,leaseLive=false,ending=false,unlocking=false;
 const check=()=>{if(!active||!leaseLive||controller.signal.aborted||unlocking)throw failure();};
 const peerTls=()=>{const stream=active!.connection.stream as TLSSocket;if(!stream.encrypted||stream.authorized!==true)throw failure();const protocol=stream.getProtocol(),peer=stream.getPeerCertificate();if(!protocol||!['TLSv1.2','TLSv1.3'].includes(protocol)||!peer?.raw?.length||checkServerIdentity(url.hostname,peer))throw failure();return{kind:'PEER_VERIFIED' as const,host:url.hostname,certificateSha256:input.certificate.sha256,peerCertificateSha256:hash(peer.raw),protocol};};
 const tls=()=>{check();return peerTls();};
 async function identity(){check();const response=await active!.query(`select session_user::text as operator,current_database()::text as database,(select ssl from pg_stat_ssl where pid=pg_backend_pid()) as ssl,current_setting('server_version_num')::integer as "serverVersion"`);check();if(response.rows.length!==1)throw failure();return identityRow.parse(response.rows[0]);}
 const observe=async()=>{try{check();if(unlocking)throw failure();await certificate(input);const peer=tls(),who=await identity();const presence=await active!.query(`select to_regclass('supabase_migrations.schema_migrations') is not null as "historyPresent"`);check();if(presence.rows.length!==1||typeof presence.rows[0].historyPresent!=='boolean')throw failure();const historyPresent=presence.rows[0].historyPresent as boolean;let history:z.infer<typeof rawHistoryRow>[]=[];if(historyPresent){const result=await active!.query(`select version,coalesce(name,'') as name,statements from supabase_migrations.schema_migrations order by version limit 1001`);check();history=z.array(rawHistoryRow).max(1000).parse(result.rows);if(new Set(history.map(row=>row.version)).size!==history.length||Buffer.byteLength(JSON.stringify(history))>8*1024*1024)throw failure();}return{...who,tls:peer,historyPresent,history};}catch{throw failure();}};
 const withLock:HostedExecutionPorts['withLock']=async(key,run)=>{
  privateProcessEnvironment();if(entered||key!==`${input.projectRef}:HOSTED_SCHEMA_MIGRATION`||controller.signal.aborted)throw failure();entered=true;
  const client=new Client({host:url.hostname,port:5432,database:'postgres',user:url.username,password:input.password,ssl:{rejectUnauthorized:true,ca,minVersion:'TLSv1.2'},options:'-c search_path=pg_catalog',client_encoding:'UTF8',application_name:'cuevo-hosted-migration-operator',connectionTimeoutMillis:10000,statement_timeout:5000,query_timeout:7000,lock_timeout:2000,keepAlive:true});
  active=client;const lost=()=>{if(!ending){leaseLive=false;controller.abort();}};client.on('error',lost);client.on('end',lost);
  let released=false,cleanupStarted=false;try{await client.connect();leaseLive=true;tls();await identity();const locked=await client.query(`select pg_try_advisory_lock(hashtextextended($1,0)) as locked`,[key]);check();if(locked.rows.length!==1||locked.rows[0].locked!==true)throw failure();await run({kind:'HELD',id:randomUUID(),key});check();cleanupStarted=true;
   // Process closure cannot prove that its PostgreSQL statement has stopped.
   // Observe all same-operator client sessions conservatively; no session is cancelled.
   const deadline=performance.now()+5000;let quiescent=false;
   do{check();tls();if(performance.now()>=deadline)break;const remaining=Math.max(1,Math.floor(deadline-performance.now()));const observed=await client.query({text:`/* CUEVO_NATIVE_QUIESCENCE */ select not exists(select 1 from pg_stat_activity where pid<>pg_backend_pid() and datname=current_database() and usename=session_user and backend_type='client backend' and(state is distinct from 'idle' or xact_start is not null)) as quiescent`,query_timeout:Math.min(1000,remaining)});check();tls();if(observed.rows.length!==1||typeof observed.rows[0].quiescent!=='boolean'||performance.now()>=deadline)break;if(observed.rows[0].quiescent===true){quiescent=true;break;}if(performance.now()>=deadline)break;await new Promise(done=>setTimeout(done,Math.min(100,Math.max(1,deadline-performance.now()))));}while(performance.now()<deadline);
   if(quiescent){check();tls();unlocking=true;const unlock=await client.query(`select pg_advisory_unlock(hashtextextended($1,0)) as released`,[key]);if(controller.signal.aborted||!leaseLive)throw failure();peerTls();released=unlock.rows.length===1&&unlock.rows[0].released===true;}
  }catch{if(!cleanupStarted)throw failure();released=false;}finally{leaseLive=false;ending=true;controller.abort();try{await client.end();}catch{released=false;}active=null;}
  return released?{kind:'RELEASED'}:{kind:'RELEASE_UNCONFIRMED'};
 };
 const row=async(sql:string)=>{check();const result=await active!.query(sql);check();if(result.rows.length!==1)throw failure();return result.rows[0] as unknown;};
 const observeTarget=async():Promise<HostedMigrationTargetObservation>=>{try{const observed=await observe();const facts=targetSchema.parse(await row(`/* CUEVO_TARGET_COUNTS */ select (select count(*) from auth.users) as "authUsers",(select count(*) from storage.objects) as "storageObjects",coalesce((select array_agg(nspname::text order by nspname) from pg_namespace where nspname in('app','internal','authorization')),array[]::text[]) as "appSchemas",coalesce((select array_agg(rolname::text order by rolname) from pg_roles where rolname in('cuevo_api','cuevo_worker')),array[]::text[]) as "runtimeRoles",to_regclass('app.schools') is not null as "schoolsPresent"`));if(new Set(facts.appSchemas).size!==facts.appSchemas.length||new Set(facts.runtimeRoles).size!==facts.runtimeRoles.length)throw failure();const schools=facts.schoolsPresent?z.object({schools:count}).parse(await row('/* CUEVO_TARGET_SCHOOLS */ select count(*) as schools from app.schools')).schools:null;check();return{...observed,observedAtMs:Date.now(),authUsers:facts.authUsers,storageObjects:facts.storageObjects,appSchemas:facts.appSchemas,runtimeRoles:facts.runtimeRoles,schools};}catch{throw failure();}};
 const observeStage=async(value:{stageId:HostedMigrationStageId;expectedAfterVersions:string[]}):Promise<HostedMigrationStageObservation>=>{try{const selected=stageInput(value),observed=await observe(),actual=observed.history.map(row=>row.version).sort();if(JSON.stringify(actual)!==JSON.stringify([...selected.versions].sort()))throw failure();const expected=new Set(selected.versions),checks:HostedMigrationStageObservation['checks']={foundation:null,rls:null,privateRelations:null,privateFunctions:null,runtimeRoles:null,nativeSourceBridge:null,curriculumLifecycle:null,dispatchInactive:null,analyticsInactive:null,recoveryCronInactive:null,transportPrivate:null};
 if(expected.has(capabilities.foundation)){Object.assign(checks,baseStageSchema.parse(await row(baseStageSql)));}
 if(expected.has(capabilities.native)){checks.nativeSourceBridge=z.object({nativeSourceBridge:z.boolean()}).parse(await row(nativeBridgeSql)).nativeSourceBridge;}
 if(expected.has(capabilities.lifecycle)){checks.curriculumLifecycle=z.object({curriculumLifecycle:z.boolean()}).parse(await row(lifecycleSql)).curriculumLifecycle;}
 if(expected.has(capabilities.wake)){const dispatch=z.object({count,disabled:z.boolean()}).parse(await row(`/* CUEVO_DISPATCH_INACTIVE */ select count(*) as count,coalesce(bool_and(singleton and not enabled and state='DISABLED' and endpoint is null and vault_secret_name is null and not allow_local and wake_id is null and lease_expires_at is null and network_request_id is null),false) and to_regprocedure('internal.configure_worker_dispatch(boolean,text,text,boolean)') is not null and to_regprocedure('internal.send_worker_wake(uuid,text,text)') is not null and to_regprocedure('internal.request_worker_wake()') is not null and to_regprocedure('internal.worker_transport_private()') is not null as disabled from internal.worker_dispatch_control`));checks.dispatchInactive=dispatch.count===1&&dispatch.disabled;}
 const cron=z.object({present:z.boolean()}).parse(await row(`/* CUEVO_RECOVERY_CRON_PRESENCE */ select to_regclass('cron.job') is not null as present`));checks.recoveryCronInactive=cron.present?z.object({inactive:z.boolean()}).parse(await row(`/* CUEVO_RECOVERY_CRON */ select not exists(select 1 from cron.job where active and (command ilike '%request_worker_wake%' or command ilike '%configure_worker_dispatch%' or jobname ilike 'cuevo%')) as inactive`)).inactive:true;
 if(expected.has(capabilities.analytics)){const analytics=z.object({count,disabled:z.boolean()}).parse(await row(`/* CUEVO_ANALYTICS_INACTIVE */ select count(*) as count,not exists(select 1 from internal.posthog_school_activation where enabled) as disabled from internal.posthog_school_activation`));checks.analyticsInactive=analytics.disabled;}
 // The historical strict guard would reject provider service grants; only the accepted final replacement may attest final transport posture.
 if(expected.has(capabilities.transport)){const body=await finalTransportBody(input.repoRoot);check();const actual=z.object({body:z.string().min(1).max(64*1024),valid:z.boolean()}).parse(await row(`/* CUEVO_TRANSPORT_SOURCE */ select p.prosrc as body,p.prosecdef and p.provolatile='s' and p.prorettype='boolean'::regtype and r.rolname='postgres' and l.lanname='plpgsql' and p.proconfig @> array['search_path=""'] and not exists(select 1 from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') and not exists(select 1 from pg_roles caller where caller.rolname in('anon','authenticated','service_role','cuevo_api','cuevo_worker') and has_function_privilege(caller.oid,p.oid,'EXECUTE')) as valid from pg_proc p join pg_roles r on r.oid=p.proowner join pg_language l on l.oid=p.prolang where p.oid=to_regprocedure('internal.worker_transport_private()')`));if(!actual.valid||hash(actual.body)!==hash(body))throw failure();checks.transportPrivate=z.object({transportPrivate:z.boolean()}).parse(await row('/* CUEVO_TRANSPORT_PRIVATE */ select internal.worker_transport_private() as "transportPrivate"')).transportPrivate;}
 check();return{observedAtMs:Date.now(),stageId:selected.stageId,checks};}catch{throw failure();}};
 return{signal:controller.signal,observe,observeTarget,observeStage,withLock};
}
