import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { registerHooks } from 'node:module';
import { transformSync } from 'esbuild';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import type { HostedExecutionJournal } from './hosted-migration-execution';
import { planHostedMigrations, canonicalHostedMigrationPlan, readCanonicalMigrationSources, type HostedMigrationPlanV1 } from './hosted-migration-plan';
import { prepareHostedOperatorStoragePolicy } from './hosted-operator-storage-policy';

const hash = (value: string | Uint8Array) => createHash('sha256').update(value).digest('hex');
const ref = 'mqxdjvsyckzocokuikmx', secret = 'private-native-composition-canary';
type State = { events: string[]; journal: HostedExecutionJournal | null; journals: Map<string, HostedExecutionJournal | null>; after: boolean; lost: boolean; failures: string[]; input?: Record<string, unknown>; sources: { name: string; bytes: Uint8Array }[]; stage?: Record<string, unknown>; controller: AbortController; commands: number; phaseVersions: string[][]; seenIntent: boolean; driftFiles: boolean };
const state: State = { events: [], journal: null, journals: new Map(), after: false, lost: false, failures: [], sources: [], controller: new AbortController(), commands: 0, phaseVersions: [], seenIntent: false, driftFiles: false };
let canonicalSources: State['sources'] | undefined;

// Only native I/O imports are intercepted in this test module. The real protocol,
// connection preparation, raw-history verifier, filesystem and factory run.
const replacements: Record<string, string> = {
  'backend-release-admission.ts': 'export const readBackendReleaseAdmission=globalThis.nativeCompositionFixture.admission;',
  'backend-release-contracts.ts': 'export const validatePreparedBackendReleaseIntent=globalThis.nativeCompositionFixture.prepared;',
  'hosted-migration-provider.ts': 'export const readHostedMigrationProvider=globalThis.nativeCompositionFixture.provider;',
  'hosted-migration-stage-files.ts': 'export const admitHostedMigrationStageFiles=globalThis.nativeCompositionFixture.files;',
  'hosted-migration-database.ts': 'export const createHostedMigrationDatabase=globalThis.nativeCompositionFixture.database;',
  'hosted-migration-native-process.ts': 'export const createHostedMigrationNativeProcess=globalThis.nativeCompositionFixture.process;',
  'hosted-migration-journal.ts': 'export const createHostedMigrationJournal=globalThis.nativeCompositionFixture.journal;',
  'hosted-migration-durable-journal.ts': 'export const createHostedMigrationDurableJournal=globalThis.nativeCompositionFixture.durable;',
  'hosted-operator-storage-inventory.ts': 'export const readHostedOperatorStorageInventory=globalThis.nativeCompositionFixture.inventory;',
};
registerHooks({ resolve(specifier, context, next) { if (specifier.endsWith('/hosted-migration-provider')) return { shortCircuit: true, url: new URL('./hosted-migration-provider.ts', context.parentURL).href }; return next(specifier, context); }, load(url, context, next) { const name = url.split('/').at(-1)!; if (replacements[name]) return { format: 'module', shortCircuit: true, source: replacements[name] }; if (name === 'hosted-migration-executor.ts') return { format: 'module', shortCircuit: true, source: transformSync(readFileSync(new URL(url), 'utf8'), { loader: 'ts', format: 'esm' }).code }; return next(url, context); } });
const clone = <T,>(value: T): T => structuredClone(value);
const fail = (name: string) => { if (state.failures.includes(name)) throw Error(secret); };
const versions = () => (state.stage![state.after ? 'expectedAfterVersions' : 'expectedBeforeVersions'] as string[]);
function rawHistory() { return versions().map(version => { const source = state.sources.find(row => row.name.startsWith(version))!; const text = new TextDecoder().decode(source.bytes).trim(); return { version, name: source.name.slice(15, -4), statements: text ? [text] : [] }; }); }
function storageCount() { return state.journal ? state.journal.state === 'INTENT' ? 2 : 3 : 0; }
function target() { return { observedAtMs: Date.now(), operator: 'postgres', database: 'postgres', serverVersion: 170011, tls: { kind: 'PEER_VERIFIED', host: `db.${ref}.supabase.co`, certificateSha256: 'a'.repeat(64), peerCertificateSha256: 'b'.repeat(64), protocol: 'TLSv1.3' }, historyPresent: versions().length > 0, history: rawHistory(), authUsers: state.failures.includes('population') ? 1 : 0, storageObjects: storageCount() + (state.failures.includes('inventory-foreign-intent') ? 2 : 0), appSchemas: versions().length ? ['app', 'authorization', 'internal'] : [], runtimeRoles: versions().length ? ['cuevo_api', 'cuevo_worker'] : [], schools: versions().length ? 0 : null }; }
function checks() { const current = versions(), has = (prefix: string) => current.includes(prefix); return { foundation: current.length ? true : null, rls: current.length ? true : null, privateRelations: current.length ? true : null, privateFunctions: current.length ? true : null, runtimeRoles: current.length ? true : null, nativeSourceBridge: has('20261002021737') ? true : null, curriculumLifecycle: has('20261002021206') ? true : null, dispatchInactive: has('20261002122236') ? true : null, analyticsInactive: has('20261002182213') ? true : null, recoveryCronInactive: true, transportPrivate: has('20261005132902') ? true : null }; }
Object.assign(globalThis, { nativeCompositionFixture: {
  prepared: (value: unknown) => clone(value),
  admission: async () => { state.events.push('official'); fail('official'); if (state.seenIntent) fail('official-after-intent'); if (state.failures.includes('late-file-drift') && state.phaseVersions.length === 2 && state.events.at(-2) === 'postconditions') state.driftFiles = true; return { expected: clone(state.input!.expected), approval: { purpose: 'BACKEND_SYNTHETIC_STAGING', state: 'approved', packageSha256: (state.input!.preparedApproval as { sha256: string }).sha256 }, observedAt: new Date().toISOString(), provenance: 'OFFICIAL_GITHUB_AND_VERIFIED_GIT_SOURCE' }; },
  provider: async () => { state.events.push('provider'); fail('provider'); return { evidence: 'OFFICIAL_SUPABASE_PROJECT_METADATA', observedAtMs: Date.now(), projectRef: ref, projectName: 'Cuevo', projectStatus: 'ACTIVE_HEALTHY', directEndpoint: { projectRef: ref, kind: 'direct', host: `db.${ref}.supabase.co`, port: 5432, database: 'postgres' } }; },
  files: async () => { state.events.push('files'); fail('files'); if (state.driftFiles) throw Error(secret); if (state.failures.includes('late-inventory-clock') && state.phaseVersions.length === 2) (globalThis as unknown as { nativeCompositionAdvanceClock?: () => void }).nativeCompositionAdvanceClock?.(); return { evidence: 'VERIFIED_GIT_AND_PHYSICAL_STAGE', sources: state.sources, stageSha256: hash(JSON.stringify({ included: state.stage!.included, configSha256: state.stage!.configSha256 })), planSha256: canonicalHostedMigrationPlan(state.input!.plan as Parameters<typeof canonicalHostedMigrationPlan>[0]).sha256 }; },
  database: async () => ({ signal: state.controller.signal, withLock: async (key: string, run: (lease: unknown) => Promise<void>) => { state.events.push('lock'); fail('lock'); try { await run({ kind: 'HELD', key, id: 'native-current-lease' }); state.events.push('unlock'); fail('unlock'); return { kind: 'RELEASED' }; } finally { state.controller.abort(); } }, observeTarget: async () => { state.events.push('target'); fail('target'); if (state.lost) { state.controller.abort(); throw Error(secret); } const result = target(); return state.after && state.failures.includes('after-history') ? { ...result, history: [] } : result; }, observeStage: async (input: { stageId: string; expectedAfterVersions: string[] }) => { state.events.push('postconditions'); state.phaseVersions.push(clone(input.expectedAfterVersions)); assert.deepEqual(input.expectedAfterVersions, versions()); const result = checks(); return { observedAtMs: Date.now(), stageId: input.stageId, checks: { ...result, ...(state.failures.includes('postconditions') || state.after && state.failures.includes('after-postconditions') ? { rls: false } : {}) } }; } }),
  process: async (_value: unknown, options: { signal: AbortSignal }) => ({ runCli: async (args: string[], env: Record<string, string>) => { state.events.push('cli'); state.commands++; assert.equal(options.signal, state.controller.signal); assert.equal(env.PGPASSWORD, secret); assert.equal(args.some(arg => arg.includes(secret)), false); assert.ok(args.includes('--skip-vault')); fail('cli'); state.after = true; return state.failures.includes('timeout') ? { kind: 'TIMEOUT' } : { kind: 'EXITED', exitCode: 0 }; } }),
  journal: async ({ journalRoot }: { journalRoot: string }) => ({ readJournal: async () => { state.events.push('journal-read'); fail('journal-read'); return clone(state.journals.get(journalRoot) ?? state.journal); }, writeJournal: async (value: HostedExecutionJournal) => { state.events.push('journal:' + value.state); if (value.state === 'INTENT') state.seenIntent = true; state.journal = clone(value); state.journals.set(journalRoot, clone(value)); return state.failures.includes('journal-sync') ? { kind: 'UNCONFIRMED' } : { kind: 'SYNCED', sha256: hash(JSON.stringify(value)) }; } }),
  durable: async (input: { journalRoot: string; storageKey: string; providerToken: string }) => { state.events.push('durable'); assert.equal(input.storageKey, 'journal-only-credential-canary'); assert.equal(input.providerToken, secret); const journal = (globalThis as unknown as { nativeCompositionFixture: { journal: (input: { journalRoot: string }) => Promise<unknown> } }).nativeCompositionFixture.journal; return journal(input); },
  inventory: async (input: { identity: HostedExecutionJournal['identity']; expectedVersions: string[]; storageKey: string }) => { state.events.push('inventory'); fail('inventory'); assert.equal(input.storageKey, 'journal-only-credential-canary'); assert.deepEqual(input.expectedVersions, versions()); if (state.phaseVersions.length === 2) { if (state.failures.includes('inventory-file-drift')) state.driftFiles = true; if (state.failures.includes('inventory-policy-drift')) await writeFile(state.input!.operatorStoragePolicyPath as string, '{}'); if (state.failures.includes('inventory-toolchain-drift')) await writeFile(state.input!.toolchainManifestPath as string, '{}'); } const foreign = state.failures.includes('inventory-foreign-intent') ? 2 : 0, now = Date.now(); return { evidence: 'VERIFIED_INITIAL_OPERATOR_STORAGE_INVENTORY', projectRef: ref, sourceSha: input.identity.sourceSha, treeSha: input.identity.treeSha, approvalDigest: input.identity.approvalDigest, ciRunId: input.identity.ciRunId, planSha256: input.identity.planSha256, stageId: input.identity.stageId, stageSha256: input.identity.stageSha256, expectedVersionsSha256: hash(JSON.stringify([...input.expectedVersions].sort())), observedAtMs: state.failures.includes('old-inventory') ? now - 31000 : now, startedAtMs: now, bytesVerificationStartedAtMs: now, bytesVerifiedAtMs: now, countsVerifiedAtMs: now, completedAtMs: now, totalStorageObjects: storageCount() + foreign + (state.failures.includes('count-mismatch') ? 1 : 0), verifiedOperatorObjects: storageCount() + foreign, applicationStorageObjects: state.failures.includes('application-storage') ? 1 : 0, bucketMetadataSha256: '1'.repeat(64), objectSetSha256: '2'.repeat(64), remoteProjectSha256: '3'.repeat(64), operations: [...(state.journal ? [{ operation: hash(JSON.stringify(input.identity)), state: state.journal.state, identitySha256: hash(JSON.stringify(input.identity)), chainSha256: '4'.repeat(64), objectCount: state.failures.includes('inventory-sum') ? 1 : storageCount() }] : []), ...(foreign ? [{ operation: '5'.repeat(64), state: 'INTENT', identitySha256: '5'.repeat(64), chainSha256: '6'.repeat(64), objectCount: 2 }] : [])] }; },
} });

async function api() { let module: Record<string, unknown> = {}; try { module = await import(pathToFileURL(resolve(import.meta.dirname, 'hosted-migration-executor.ts')).href); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ERR_MODULE_NOT_FOUND') throw error; } assert.equal(typeof module.executeNativeHostedMigrationStage, 'function', 'native stage composition export must exist'); return module as typeof import('./hosted-migration-executor'); }
function git(root: string, ...args: string[]) { return execFileSync('git', ['-C', root, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], windowsHide: true }).trim(); }
async function fixture(run: (input: Record<string, unknown>, root: string) => Promise<void>) {
  const root = await mkdtemp(join(tmpdir(), 'cuevo-native-composition-'));
  try {
    Object.assign(state, { events: [], journal: null, journals: new Map(), after: false, lost: false, failures: [], controller: new AbortController(), commands: 0, phaseVersions: [], seenIntent: false, driftFiles: false });
    const repository = resolve(import.meta.dirname, '../..'), sha = git(repository, 'rev-parse', 'HEAD'), tree = git(repository, 'rev-parse', 'HEAD^{tree}'); canonicalSources ??= readCanonicalMigrationSources({ repoRoot: repository, sourceSha: sha, treeSha: tree }).sources; state.sources = canonicalSources;
    await mkdir(join(root, '.local/hosted-release'), { recursive: true }); await writeFile(join(root, '.gitignore'), '.local/\n');
    const lock = { lockfileVersion: 3, packages: { '': { devDependencies: { supabase: '2.119.0' } }, 'node_modules/supabase': { version: '2.119.0', integrity: 'sha512-canonical', resolved: 'https://registry.npmjs.org/supabase/-/supabase-2.119.0.tgz' }, [`node_modules/@supabase/cli-${process.platform === 'win32' ? 'windows' : process.platform}-${process.arch}`]: { version: '2.119.0', integrity: 'sha512-platform', resolved: 'https://registry.npmjs.org/@supabase/cli-platform.tgz' } } }; const lockBytes = JSON.stringify(lock) + '\n'; await writeFile(join(root, 'package-lock.json'), lockBytes); git(root, 'init', '--quiet'); git(root, 'add', '.'); git(root, '-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgsign=false', 'commit', '--quiet', '-m', 'Source');
    const sourceSha = git(root, 'rev-parse', 'HEAD'), treeSha = git(root, 'rev-parse', 'HEAD^{tree}'), now = Date.now(); const plan = planHostedMigrations({ sources: state.sources, source: { sha: sourceSha, tree: treeSha }, now, target: { projectRef: ref, boundProjectRef: ref, projectName: 'Cuevo', projectStatus: 'ACTIVE_HEALTHY', deploymentEnvironment: 'synthetic-staging', observedAt: new Date(now).toISOString(), authUsers: 0, storageObjects: 0, appSchemas: [], migrationVersions: [], dispatchDisabled: true, population: 'EMPTY' } });
    const included = plan.migrations.slice(0, plan.stages[0].names.length).map(({ name, version, sha256 }) => ({ name, version, sha256 })); const stage = { id: 'prefix', workdir: join(root, '.local/hosted-release/migration-fixture/prefix'), included, pending: included, expectedBeforeVersions: [], expectedAfterVersions: included.map(row => row.version).sort(), configSha256: 'c'.repeat(64), commandArgs: [] }; state.stage = stage;
    const manifest = { version: 1, purpose: 'CUEVO_HOSTED_MIGRATION_TOOLCHAIN', sourceSha, treeSha, sourceLockSha256: hash(lockBytes), cliVersion: '2.119.0', platform: `${process.platform}-${process.arch}`, cli: { shimSha256: 'd'.repeat(64), binarySha256: 'e'.repeat(64), sidecarSha256: 'f'.repeat(64) } }; const manifestPath = join(root, '.local/hosted-release/toolchain-fixture.json'), manifestBytes = JSON.stringify(manifest) + '\n'; await writeFile(manifestPath, manifestBytes, { mode: 0o600 });
    const policy = prepareHostedOperatorStoragePolicy({ sourceSha, treeSha, projectRef: ref }), operatorStoragePolicyPath = join(root, '.local/hosted-release/operator-policy.json'); await writeFile(operatorStoragePolicyPath, policy.canonicalJson, { mode: 0o600 });
    const expected = { releaseSha: sourceSha, treeSha, currentMainSha: sourceSha, ciRunId: '31', targets: { supabase: { projectRef: ref } }, fingerprints: { migrationPlanSha256: canonicalHostedMigrationPlan(plan).sha256, migrationHistorySha256: plan.observedHistorySha256, migrationToolchainSha256: hash(manifestBytes), operatorStoragePolicySha256: policy.sha256 }, now }; const body = { ...expected, purpose: 'BACKEND_SYNTHETIC_STAGING', expiresAt: new Date(now + 3600000).toISOString() }; const canonicalJson = JSON.stringify(body); const preparedApproval = { status: 'PREPARED_ONLY', canonicalJson, sha256: hash(canonicalJson), base64: Buffer.from(canonicalJson).toString('base64'), comment: 'controlled official exact package' };
    const input = { repoRoot: root, plan, stage, preparedApproval, expected, certificate: { path: join(root, '.local/hosted-release/ca.pem'), sha256: 'a'.repeat(64) }, toolchainManifestPath: manifestPath, operatorStoragePolicyPath, journalStorageKey: 'journal-only-credential-canary', githubToken: secret, providerToken: secret, migrationPassword: secret, toolchain: {} }; state.input = input; await run(input, root);
  } finally { await rm(root, { recursive: true, force: true }); }
}

test('native factory wires exact fresh authority, durable intent, one CLI and current after-state without upgrading protocol evidence', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async input => { const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'COMMITTED', JSON.stringify({ result, events: state.events })); assert.equal(result.protocol?.evidence, 'SUPPLIED_PORT_EXECUTION_ONLY'); assert.equal(result.schemaHistoryAtomic, false); assert.equal(result.hostedAcceptance, false); assert.equal(state.commands, 1); assert.deepEqual(state.phaseVersions, [state.stage!.expectedBeforeVersions, state.stage!.expectedBeforeVersions, state.stage!.expectedAfterVersions]); assert.ok(state.events.indexOf('journal:INTENT') < state.events.indexOf('cli')); assert.ok(state.events.lastIndexOf('postconditions') < state.events.indexOf('journal:COMMITTED')); assert.equal(JSON.stringify(result).includes(secret), false); }); });
test('accessor, supplied readiness and unapproved toolchain fingerprints cannot reach native consumers', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async input => { let reads = 0; const getter = { ...input, get migrationPassword() { reads++; return secret; } }; assert.equal((await executeNativeHostedMigrationStage(getter)).status, 'REQUIRES_REVIEW'); assert.equal(reads, 0); assert.equal(state.commands, 0); const extra = { ...input, satisfied: true }; assert.equal((await executeNativeHostedMigrationStage(extra)).status, 'REQUIRES_REVIEW'); await writeFile(input.toolchainManifestPath as string, '{}'); assert.equal((await executeNativeHostedMigrationStage(input)).status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); }); });
test('unavailable provider, nonempty initial target and actual false postconditions refuse before intent or CLI', async () => { const { executeNativeHostedMigrationStage } = await api(); for (const failure of ['provider', 'population', 'postconditions']) await fixture(async input => { state.failures = [failure]; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); assert.equal(state.events.includes('journal:INTENT'), false); }); });
test('timeout and lock cleanup failure retain unknown commitment and separate protocol errors without retry', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async input => { state.failures = ['timeout', 'unlock']; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(result.protocol?.commitment, 'UNKNOWN'); assert.equal(result.protocol?.primaryCode, 'CLI_UNCONFIRMED'); assert.equal(result.protocol?.cleanupCode, 'LOCK_RELEASE_UNCONFIRMED'); assert.equal(state.commands, 1); assert.equal(JSON.stringify(result).includes(secret), false); }); });
test('same-project unresolved prior journal blocks a changed source or approval rather than allocating another intent', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async (input, root) => { const directory = join(root, '.local/hosted-release/journal-prior-attempt'); await mkdir(directory); const identity = { projectRef: ref, sourceSha: '1'.repeat(40), treeSha: '2'.repeat(40), planSha256: '3'.repeat(64), stageId: 'prefix', stageSha256: '4'.repeat(64), databaseUrl: `postgresql://postgres@db.${ref}.supabase.co:5432/postgres?sslmode=verify-full`, approvalDigest: '5'.repeat(64), ciRunId: '30', certificateSha256: '6'.repeat(64) }; await writeFile(join(directory, 'owner.json'), JSON.stringify({ version: 1, purpose: 'CUEVO_HOSTED_SCHEMA_MIGRATION_JOURNAL', identity })); state.journals.set(directory, { version: 1, identity, state: 'INTENT', schemaHistoryAtomic: false, evidence: 'SUPPLIED_PORT_EXECUTION_ONLY' } as HostedExecutionJournal); const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); assert.equal(state.events.includes('journal:INTENT'), false); }); });
test('empty pending stage cannot invoke a fresh CLI without a confirmed original journal', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async input => { state.stage!.pending = []; state.stage!.expectedBeforeVersions = state.stage!.expectedAfterVersions; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); assert.equal(state.events.includes('cli'), false); }); });
test('confirmed original journal reconciles exact after-state as NOOP without a second CLI', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async input => { assert.equal((await executeNativeHostedMigrationStage(input)).status, 'COMMITTED'); state.controller = new AbortController(); state.phaseVersions = []; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'NOOP'); assert.equal(state.commands, 1); assert.deepEqual(state.phaseVersions, [state.stage!.expectedAfterVersions]); state.controller = new AbortController(); state.failures = ['after-history']; assert.equal((await executeNativeHostedMigrationStage(input)).status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 1); }); });
test('authority changed after intent and a late physical artifact drift cannot reach CLI', async () => { const { executeNativeHostedMigrationStage } = await api(); for (const failure of ['official-after-intent', 'late-file-drift']) await fixture(async input => { state.failures = [failure]; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); }); });
test('actual history or postconditions lost after CLI cannot publish a COMMITTED journal', async () => { const { executeNativeHostedMigrationStage } = await api(); for (const failure of ['after-history', 'after-postconditions']) await fixture(async input => { state.failures = [failure]; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(result.protocol?.commitment, 'UNKNOWN'); assert.equal(state.commands, 1); assert.equal(state.journal?.state, 'REQUIRES_REVIEW'); assert.equal(state.events.includes('journal:COMMITTED'), false); }); });
test('lost native lease and unconfirmed durable journal both stop before CLI', async () => { const { executeNativeHostedMigrationStage } = await api(); for (const failure of ['lost', 'journal-sync']) await fixture(async input => { if (failure === 'lost') state.lost = true; else state.failures = [failure]; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); }); });
test('unknown journal ownership and unapproved source lock refuse without journal replacement', async () => { const { executeNativeHostedMigrationStage } = await api(); for (const failure of ['owner', 'source-lock']) await fixture(async (input, root) => { if (failure === 'owner') { const directory = join(root, '.local/hosted-release/journal-corrupt'); await mkdir(directory); await writeFile(join(directory, 'owner.json'), JSON.stringify({ version: 1, purpose: 'OTHER_PURPOSE', identity: {} })); } else { const manifestPath = input.toolchainManifestPath as string, manifest = JSON.parse(await import('node:fs/promises').then(fs => fs.readFile(manifestPath, 'utf8'))) as Record<string, unknown>; manifest.sourceLockSha256 = '0'.repeat(64); const bytes = JSON.stringify(manifest) + '\n'; await writeFile(manifestPath, bytes); (input.expected as { fingerprints: { migrationToolchainSha256: string } }).fingerprints.migrationToolchainSha256 = hash(bytes); } const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); assert.equal(state.events.includes('journal:INTENT'), false); }); });
test('final whole-stage postconditions require current transport privacy rather than historical guard availability', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async input => { const plan = input.plan as HostedMigrationPlanV1; const included = plan.migrations.map(({ name, version, sha256 }) => ({ name, version, sha256 })); state.stage!.id = 'remaining'; state.stage!.included = included; state.stage!.pending = included; state.stage!.expectedAfterVersions = included.map(row => row.version).sort(); input.stage = state.stage; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'COMMITTED', JSON.stringify(result)); assert.equal(state.commands, 1); assert.deepEqual(state.phaseVersions.at(-1), state.stage!.expectedAfterVersions); }); });
test('operator inventory and exact policy cannot be omitted, stale or treated as an arbitrary Storage exclusion', async () => { const { executeNativeHostedMigrationStage } = await api(); for (const failure of ['inventory', 'old-inventory', 'count-mismatch', 'application-storage', 'inventory-sum', 'policy']) await fixture(async input => { if (failure === 'policy') await writeFile(input.operatorStoragePolicyPath as string, '{}'); else state.failures = [failure]; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); }); });
test('physical stage, policy or toolchain mutation during final inventory await cannot reach CLI', async () => { const { executeNativeHostedMigrationStage } = await api(); for (const failure of ['inventory-file-drift', 'inventory-policy-drift', 'inventory-toolchain-drift']) await fixture(async input => { state.failures = [failure]; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); }); });
test('earlier inventory and database observations cannot be refreshed after late pre-CLI source verification', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async input => { const originalNow = Date.now; let now = originalNow(); Date.now = () => now; Object.assign(globalThis, { nativeCompositionAdvanceClock: () => { now += 31000; } }); try { state.failures = ['late-inventory-clock']; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 0); } finally { Date.now = originalNow; delete (globalThis as unknown as { nativeCompositionAdvanceClock?: () => void }).nativeCompositionAdvanceClock; } }); });
test('matching committed journal cannot become NOOP when inventory discovers another unresolved operation', async () => { const { executeNativeHostedMigrationStage } = await api(); await fixture(async input => { assert.equal((await executeNativeHostedMigrationStage(input)).status, 'COMMITTED'); state.controller = new AbortController(); state.failures = ['inventory-foreign-intent']; const result = await executeNativeHostedMigrationStage(input); assert.equal(result.status, 'REQUIRES_REVIEW'); assert.equal(state.commands, 1); }); });
