import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, rm,access } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { registerHooks } from 'node:module';
import { transformSync } from 'esbuild';
import { readFileSync } from 'node:fs';
import type { HostedExecutionJournal } from './hosted-migration-execution';

const ref = 'mqxdjvsyckzocokuikmx', secret = 'private-durable-journal-canary', hash = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
const identity: HostedExecutionJournal['identity'] = { projectRef: ref, sourceSha: 'a'.repeat(40), treeSha: 'b'.repeat(40), planSha256: 'c'.repeat(64), stageId: 'prefix', stageSha256: 'd'.repeat(64), databaseUrl: `postgresql://postgres@db.${ref}.supabase.co:5432/postgres?sslmode=verify-full`, approvalDigest: 'e'.repeat(64), ciRunId: '31', certificateSha256: 'f'.repeat(64) };
const payload = (state: HostedExecutionJournal['state']): HostedExecutionJournal => ({ version: 1, identity, state, schemaHistoryAtomic: false, evidence: 'SUPPLIED_PORT_EXECUTION_ONLY' });
let permitFixture:{permit:object;live:boolean}|null=null;
Object.assign(globalThis,{durablePermitTransportFixture:(value:unknown,current:HostedExecutionJournal['identity'],safety:boolean)=>{if(!permitFixture||value!==permitFixture.permit||JSON.stringify(current)!==JSON.stringify(identity)||!safety&&!permitFixture.live)throw Error('Controlled unavailable native permit');return{originalIdentity:identity,originalOperationSha256:'a'.repeat(64),originalChainSha256:'b'.repeat(64),receiptSha256:'c'.repeat(64)};}});
type State = { local: HostedExecutionJournal | null; remote: HostedExecutionJournal | null; events: string[]; failure: string | null; hold: Promise<void> | null; readDrift: boolean; remoteWrites: number; localWrites: number;remoteInput:unknown };
const state: State = { local: null, remote: null, events: [], failure: null, hold: null, readDrift: false, remoteWrites: 0, localWrites: 0,remoteInput:null };
Object.assign(globalThis, { durableJournalFixture: {
  local: async () => ({ readJournal: async () => { state.events.push('local-read'); if (state.failure === 'local-read') throw Error(secret); return structuredClone(state.local); }, writeJournal: async (value: HostedExecutionJournal) => { state.events.push('local-write:' + value.state); state.localWrites++; if (state.hold) await state.hold; state.local = structuredClone(value); return state.failure === 'local-write' ? { kind: 'UNCONFIRMED' } : { kind: 'SYNCED', sha256: hash(value) }; } }),
  remote: async (input:unknown) => {state.remoteInput=input;return({ readOwnedSafetyJournal:async()=>structuredClone(state.remote),readJournal: async () => { state.events.push('remote-read'); if (state.failure === 'remote-read') throw Error(secret); const result = structuredClone(state.readDrift ? payload('REQUIRES_REVIEW') : state.remote); if (state.failure === 'between-read-drift') state.local = payload('REQUIRES_REVIEW'); return result; }, writeJournal: async (value: HostedExecutionJournal) => { state.events.push('remote-write:' + value.state); state.remoteWrites++; state.remote = structuredClone(value); if (state.failure === 'drift') state.readDrift = true; return state.failure === 'remote-write' || state.failure === 'remote-commit' && value.state === 'COMMITTED' ? { kind: 'UNCONFIRMED' } : { kind: 'SYNCED', sha256: state.failure === 'hash' ? '0'.repeat(64) : hash(value) }; }, inspectProject: async () => ({ evidence: 'VERIFIED_OPERATOR_STORAGE_BYTES_AND_METADATA', projectRef: ref, observedAtMs: Date.now(), sha256: 'a'.repeat(64), operations: [] }) });},
} });
registerHooks({ load(url, context, next) { const name = url.split('/').at(-1);if(url.endsWith('/hosted-migration-database.ts'))return{format:'module',shortCircuit:true,source:`import * as actual from './hosted-migration-database.ts?actual-native-permit';
export const assertNativeMigrationEffectPermit=(value,current)=>globalThis.durablePermitTransportFixtureActive?globalThis.durablePermitTransportFixture(value,current,false):actual.assertNativeMigrationEffectPermit(value,current);
export const assertNativeReconciliationPermit=(value,current)=>globalThis.durablePermitTransportFixtureActive?globalThis.durablePermitTransportFixture(value,current,false):actual.assertNativeReconciliationPermit(value,current);
export const assertNativeReconciliationSafetyRecord=(value,current)=>globalThis.durablePermitTransportFixtureActive?globalThis.durablePermitTransportFixture(value,current,true):actual.assertNativeReconciliationSafetyRecord(value,current);`}; if (name === 'hosted-migration-journal.ts') return { format: 'module', shortCircuit: true, source: 'export const createHostedMigrationJournal=globalThis.durableJournalFixture.local;' }; if (name === 'hosted-migration-remote-journal.ts') return { format: 'module', shortCircuit: true, source: 'export const createHostedMigrationRemoteJournal=globalThis.durableJournalFixture.remote;' }; if (name === 'hosted-migration-durable-journal.ts') return { format: 'module', shortCircuit: true, source: transformSync(readFileSync(new URL(url), 'utf8'), { loader: 'ts', format: 'esm' }).code }; return next(url, context); } });
async function api() { let module: Record<string, unknown> = {}; try { module = await import(pathToFileURL(resolve(import.meta.dirname, 'hosted-migration-durable-journal.ts')).href); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ERR_MODULE_NOT_FOUND') throw error; } assert.equal(typeof module.createHostedMigrationDurableJournal, 'function', 'concrete local and remote journal factory exists'); return module as typeof import('./hosted-migration-durable-journal'); }
async function fixture(run: (input: Record<string, unknown>) => Promise<void>) { const root = await mkdtemp(join(tmpdir(), 'cuevo-durable-journal-')); try { Object.assign(state, { local: null, remote: null, events: [], failure: null, hold: null, readDrift: false, remoteWrites: 0, localWrites: 0,remoteInput:null }); await mkdir(join(root, '.local/hosted-release'), { recursive: true }); await run({ repoRoot: root, journalRoot: join(root, '.local/hosted-release/journal-current-operation'), projectRef: ref, boundProjectRef: ref, identity, storageKey: secret, providerToken: secret }); } finally { await rm(root, { recursive: true, force: true }); } }

test('confirmed original intent returns SYNCED only after ordered local and remote exact acknowledgements and readback', async () => { const { createHostedMigrationDurableJournal } = await api(); await fixture(async input => { const journal = await createHostedMigrationDurableJournal(input); assert.equal(await journal.readJournal(), null); assert.deepEqual(await journal.writeJournal(payload('INTENT')), { kind: 'SYNCED', sha256: hash(payload('INTENT')) }); const local = state.events.indexOf('local-write:INTENT'), remote = state.events.indexOf('remote-write:INTENT'); assert.ok(local < remote); assert.equal(state.events.slice(remote + 1).includes('local-read'), true); assert.equal(state.events.slice(remote + 1).includes('remote-read'), true); assert.deepEqual(await journal.writeJournal(payload('COMMITTED')), { kind: 'SYNCED', sha256: hash(payload('COMMITTED')) }); assert.deepEqual(await journal.readJournal(), payload('COMMITTED')); assert.equal(JSON.stringify(state.local).includes(secret), false); }); });
test('local write failure prevents remote write and permanently latches dual acknowledgement uncertainty', async () => { const { createHostedMigrationDurableJournal } = await api(); await fixture(async input => { const journal = await createHostedMigrationDurableJournal(input); state.failure = 'local-write'; assert.deepEqual(await journal.writeJournal(payload('INTENT')), { kind: 'UNCONFIRMED' }); assert.equal(state.remoteWrites, 0); state.failure = null; assert.deepEqual(await journal.writeJournal(payload('INTENT')), { kind: 'UNCONFIRMED' }); await assert.rejects(journal.readJournal()); assert.equal(state.localWrites, 1); }); });
test('local committed with remote failure cannot produce confirmed commitment or repeat either publication', async () => { const { createHostedMigrationDurableJournal } = await api(); await fixture(async input => { const journal = await createHostedMigrationDurableJournal(input); assert.equal((await journal.writeJournal(payload('INTENT'))).kind, 'SYNCED'); state.failure = 'remote-commit'; assert.deepEqual(await journal.writeJournal(payload('COMMITTED')), { kind: 'UNCONFIRMED' }); assert.equal(state.local?.state, 'COMMITTED'); const counts = [state.localWrites, state.remoteWrites]; state.failure = null; assert.deepEqual(await journal.writeJournal(payload('COMMITTED')), { kind: 'UNCONFIRMED' }); assert.deepEqual([state.localWrites, state.remoteWrites], counts); }); });
test('different local and remote snapshots or a missing one are never reconciled by overwrite', async () => { const { createHostedMigrationDurableJournal } = await api(); for (const [local, remote] of [[payload('COMMITTED'), null], [null, payload('COMMITTED')], [payload('INTENT'), payload('COMMITTED')]] as const) await fixture(async input => { state.local = structuredClone(local); state.remote = structuredClone(remote); const journal = await createHostedMigrationDurableJournal(input); await assert.rejects(journal.readJournal()); assert.deepEqual(await journal.writeJournal(payload('INTENT')), { kind: 'UNCONFIRMED' }); assert.equal(state.localWrites + state.remoteWrites, 0); }); });
test('matching previous COMMITTED is readable but matching previous INTENT cannot be automatically completed or retried', async () => { const { createHostedMigrationDurableJournal } = await api(); for (const prior of ['COMMITTED', 'INTENT', 'REQUIRES_REVIEW'] as const) await fixture(async input => { state.local = payload(prior); state.remote = payload(prior); const journal = await createHostedMigrationDurableJournal(input); if (prior === 'COMMITTED') assert.deepEqual(await journal.readJournal(), payload(prior)); else { await assert.rejects(journal.readJournal()); assert.deepEqual(await journal.writeJournal(payload('COMMITTED')), { kind: 'UNCONFIRMED' }); assert.equal(state.localWrites + state.remoteWrites, 0); } }); });
test('preexisting local owner-only is unknown while a newly constructed owner and absent remote are fresh', async () => { const { createHostedMigrationDurableJournal } = await api(); await fixture(async input => { await mkdir(input.journalRoot as string); const journal = await createHostedMigrationDurableJournal(input); await assert.rejects(journal.readJournal()); assert.deepEqual(await journal.writeJournal(payload('INTENT')), { kind: 'UNCONFIRMED' }); }); });
test('getters, wrong original identity and injected proof ports are refused before native construction or writes', async () => { const { createHostedMigrationDurableJournal } = await api(); await fixture(async input => { let traps = 0; await assert.rejects(createHostedMigrationDurableJournal({ ...input, get storageKey() { traps++; return secret; } })); await assert.rejects(createHostedMigrationDurableJournal({ ...input, ports: { writeJournal() {} } })); assert.equal(traps, 0); const journal = await createHostedMigrationDurableJournal(input); assert.deepEqual(await journal.writeJournal({ ...payload('INTENT'), identity: { ...identity, approvalDigest: '0'.repeat(64) } }), { kind: 'UNCONFIRMED' }); assert.equal(state.localWrites + state.remoteWrites, 0); }); });
test('wrong remote acknowledgement hash and late actual readback drift remain unconfirmed', async () => { const { createHostedMigrationDurableJournal } = await api(); for (const mode of ['hash', 'drift']) await fixture(async input => { const journal = await createHostedMigrationDurableJournal(input); state.failure = mode; assert.deepEqual(await journal.writeJournal(payload('INTENT')), { kind: 'UNCONFIRMED' }); }); });
test('an overlapping write cannot publish while original local acknowledgement is in flight', async () => { const { createHostedMigrationDurableJournal } = await api(); await fixture(async input => { let release: () => void = () => {}; state.hold = new Promise<void>(done => { release = done; }); const journal = await createHostedMigrationDurableJournal(input), first = journal.writeJournal(payload('INTENT')); while (!state.events.includes('local-write:INTENT')) await new Promise<void>(done => setTimeout(done, 0)); assert.deepEqual(await journal.writeJournal(payload('INTENT')), { kind: 'UNCONFIRMED' }); release(); assert.equal((await first).kind, 'UNCONFIRMED'); assert.equal(state.remoteWrites, 0); }); });
test('terminal idempotence and recreated committed read require both original confirmed snapshots', async () => { const { createHostedMigrationDurableJournal } = await api(); await fixture(async input => { const journal = await createHostedMigrationDurableJournal(input); assert.equal((await journal.writeJournal(payload('INTENT'))).kind, 'SYNCED'); assert.equal((await journal.writeJournal(payload('COMMITTED'))).kind, 'SYNCED'); const counts = [state.localWrites, state.remoteWrites]; assert.equal((await journal.writeJournal(payload('COMMITTED'))).kind, 'SYNCED'); assert.deepEqual([state.localWrites, state.remoteWrites], counts); const recreated = await createHostedMigrationDurableJournal(input); assert.deepEqual(await recreated.readJournal(), payload('COMMITTED')); state.remote = payload('REQUIRES_REVIEW'); await assert.rejects(recreated.readJournal()); assert.deepEqual(await recreated.writeJournal(payload('COMMITTED')), { kind: 'UNCONFIRMED' }); }); });
test('local commitment changed while remote read awaited cannot be returned as a matching pair', async () => { const { createHostedMigrationDurableJournal } = await api(); await fixture(async input => { state.local = payload('COMMITTED'); state.remote = payload('COMMITTED'); const journal = await createHostedMigrationDurableJournal(input); state.failure = 'between-read-drift'; await assert.rejects(journal.readJournal()); assert.equal(state.localWrites + state.remoteWrites, 0); }); });

test('fabricated native permits refuse durable construction before local owner or intent publication',async()=>{const{createHostedMigrationDurableJournal}=await api();
 for(const kind of ['metadata','proxy']as const)await fixture(async input=>{
  let traps=0;const reconciliationPermit=kind==='metadata'?Object.freeze({originalOperationSha256:'a'.repeat(64),receiptSha256:'b'.repeat(64)}):new Proxy({},{get(){traps++;return true;},ownKeys(){traps++;return[];},getPrototypeOf(){traps++;return Object.prototype;}});
  await assert.rejects(createHostedMigrationDurableJournal({...input,reconciliationPermit}),/require review; contents withheld/);assert.equal(state.localWrites+state.remoteWrites,0);assert.equal(state.remoteInput,null);await assert.rejects(access(input.journalRoot as string));assert.equal(traps,0);
 });
});

test('after permit expiry durable safety review needs its same confirmed intent and equal original snapshots',async()=>{const{createHostedMigrationDurableJournal}=await api();
 for(const kind of ['equal','drift','unowned']as const)await fixture(async input=>{
  const permit=Object.freeze({});permitFixture={permit,live:true};Object.assign(globalThis,{durablePermitTransportFixtureActive:true});
  try{const journal=await createHostedMigrationDurableJournal({...input,reconciliationPermit:permit});
   if(kind==='unowned'){state.local=payload('INTENT');state.remote=payload('INTENT');}else assert.equal((await journal.writeJournal(payload('INTENT'))).kind,'SYNCED');
   permitFixture.live=false;assert.deepEqual(await journal.writeJournal(payload('COMMITTED')),{kind:'UNCONFIRMED'});if(kind==='drift')state.remote=payload('COMMITTED');
   const result=await journal.writeJournal(payload('REQUIRES_REVIEW'));assert.equal(result.kind,kind==='equal'?'SYNCED':'UNCONFIRMED');if(kind==='equal'){assert.equal(state.local?.state,'REQUIRES_REVIEW');assert.equal(state.remote?.state,'REQUIRES_REVIEW');}else assert.equal(state.local?.state,'INTENT');
   assert.deepEqual(await journal.writeJournal(payload('COMMITTED')),{kind:'UNCONFIRMED'});
  }finally{permitFixture=null;delete(globalThis as{durablePermitTransportFixtureActive?:boolean}).durablePermitTransportFixtureActive;}
 });
});
