import { canonicalReleaseExecutionJson } from '../verification/release-review';
export type HostedSyntheticPopulationObservation={observedAtMs:number;population:Record<string,unknown[]>;authUsers:{id:string;email:string;emailConfirmedAt:string|null;synthetic:boolean;isAnonymous:boolean;deletedAt:string|null;bannedUntil:string|null}[]};
const failure=()=>Error('Hosted reference population requires review; contents withheld.');
function fresh(value:number){if(!Number.isSafeInteger(value)||value>Date.now()||Date.now()-value>30000)throw failure();}
const sorted=(rows:unknown[])=>rows.map(row=>canonicalReleaseExecutionJson(row)).sort();
const same=(left:unknown,right:unknown)=>canonicalReleaseExecutionJson(left)===canonicalReleaseExecutionJson(right);
const id=(prefix:string,index:number)=>prefix+String(index).padStart(12,'0'),school=id('10000000-0000-4000-8000-',1),isolation=id('10000000-0000-4000-8000-',2),actor=(index:number)=>id('20000000-0000-4000-8000-',index);
/** Full seeded identity/relationship mapping. Values are source-locked technical
 * fixtures; counts alone cannot attest the population. */
export function validateHostedReferencePopulation(observed:HostedSyntheticPopulationObservation,manifest:{actors:{actorId:string;schoolId:string;role:string;displayName:string}[]}) {
 fresh(observed.observedAtMs);const p=observed.population,expected:Record<string,unknown[]>={schools:[{id:school,name:'Cuevo Reference Academy – Doha',countryCode:'QA',languages:['en','ar'],status:'active'},{id:isolation,name:'Synthetic Isolation School',countryCode:'QA',languages:['en','ar'],status:'active'}],people:manifest.actors.map(row=>({schoolId:row.schoolId,actorId:row.actorId,displayName:row.displayName,synthetic:true})),memberships:manifest.actors.map((row,index)=>({id:id('21000000-0000-4000-8000-',index+1),schoolId:row.schoolId,actorId:row.actorId,role:row.role,status:'active',effectiveFrom:'2026-09-01T00:00:00.000000Z',effectiveTo:null})),academicYears:[1,2].map(index=>({schoolId:index===1?school:isolation,id:id('40000000-0000-4000-8000-',index),name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-07-01'})),terms:[1,2].map(index=>({schoolId:index===1?school:isolation,id:id('41000000-0000-4000-8000-',index),academicYearId:id('40000000-0000-4000-8000-',index),name:'Autumn term',startsOn:'2026-09-01',endsOn:'2026-12-20'})),yearGroups:[1,2,3,4,5].map(index=>({schoolId:index<5?school:isolation,id:id('42000000-0000-4000-8000-',index),name:index<5?'Year '+index:'Isolation Year Group',ordinal:index<5?index:1})),classes:[1,2,3,4,5,6,7].map(index=>({schoolId:index<7?school:isolation,id:id('30000000-0000-4000-8000-',index),academicYearId:id('40000000-0000-4000-8000-',index<7?1:2),yearGroupId:id('42000000-0000-4000-8000-',index<7?(index-1)%4+1:5),name:['Year 1 · Cedar','Year 2 · Maple','Year 3 · Willow','Year 4 · Oak','Year 1 · Olive','Year 2 · Palm','Isolation Class'][index-1],status:'active'})),subjects:[1,2,3,4,5,6,7,8,9].map(index=>({schoolId:index<9?school:isolation,id:id('43000000-0000-4000-8000-',index),name:['Mathematics','English','Arabic','Science','Computing','Art','Physical Education','School Custom Project','Isolation Subject'][index-1]}))};
 const temporal=(rows:unknown[])=>rows.map(value=>{const row=value as Record<string,unknown>;return{...row,effectiveFrom:typeof row.effectiveFrom==='string'?new Date(row.effectiveFrom).toISOString():row.effectiveFrom,effectiveTo:row.effectiveTo};});
 for(const[name,rows]of Object.entries(expected))if(!p[name]||!same(sorted(name==='memberships'?temporal(p[name]):p[name]),sorted(name==='memberships'?temporal(rows):rows)))throw failure();
 const relation=(schoolId:string,fields:Record<string,unknown>)=>({schoolId,...fields,status:'active',effectiveFrom:'2026-09-01T00:00:00.000Z',effectiveTo:null});
 const enrollments=[...Array.from({length:60},(_,index)=>relation(school,{classId:id('30000000-0000-4000-8000-',index%6+1),studentActorId:actor(index+12)})),relation(isolation,{classId:id('30000000-0000-4000-8000-',7),studentActorId:actor(133)})];
 const teachers=Array.from({length:8},(_,index)=>relation(school,{classId:id('30000000-0000-4000-8000-',index%6+1),subjectId:id('43000000-0000-4000-8000-',index+1),teacherActorId:actor(index+4)}));
 const guardians=Array.from({length:60},(_,index)=>relation(school,{parentActorId:actor(index+72),studentActorId:actor(index+12),relationshipType:'guardian'}));
 for(const[name,rows]of Object.entries({enrollments,teacherAssignments:teachers,parentRelationships:guardians}))if(!same(sorted(temporal(p[name]??[])),sorted(rows)))throw failure();
 const entitlements=[...['school.context','learning','assessment','curriculum','learner.state','improvement','school.operations','community','portfolio'].flatMap(code=>[school,isolation].map(schoolId=>({schoolId,code,enabled:true,effectiveFrom:'2026-09-01T00:00:00.000Z',effectiveTo:null}))),{schoolId:school,code:'restricted.records',enabled:true,effectiveFrom:'2026-09-01T00:00:00.000Z',effectiveTo:null}];
 if(!same(sorted(temporal(p.entitlements??[])),sorted(entitlements)))throw failure();
 const policies=[{schoolId:school,version:1,developmentWindowDays:14,approvedBy:actor(2)},{schoolId:isolation,version:1,developmentWindowDays:14,approvedBy:actor(132)}];if(!same(sorted(p.learnerStatePolicies??[]),sorted(policies)))throw failure();
 const intelligence=policies.map(row=>({schoolId:row.schoolId,version:1,fixtureEnabled:true,liveEnabled:false,approvedBy:row.approvedBy}));if(!same(sorted(p.intelligencePolicies??[]),sorted(intelligence)))throw failure();
 const versionId=id('60000000-0000-4000-8000-',1),referenceId=id('61000000-0000-4000-8000-',1);
 if(!same(p.schoolCustomVersions,[{schoolId:school,id:versionId,version:'synthetic-school-1',sourceType:'SCHOOL_AUTHORED',rightsStatus:'PERMITTED',createdBy:actor(2)}]))throw failure();
 const refs=(p.schoolCustomReferences??[]).map(value=>{const row=value as Record<string,unknown>;return{...row,approvedAt:new Date(String(row.approvedAt)).toISOString()};});if(!same(refs,[{schoolId:school,id:referenceId,versionId,title:'Synthetic school-authored explanation objective',description:'Demonstration objective created by the synthetic school; not an official curriculum standard.',code:null,status:'APPROVED',createdBy:actor(2),approvedBy:actor(2),approvedAt:'2026-10-01T00:00:00.000Z'}]))throw failure();
 return{schools:2,people:133,memberships:133,sourceIdentity:'EXACT_REFERENCE_FIXTURE' as const};
}
