import { createHash } from 'node:crypto';
import { types } from 'node:util';
import { z } from 'zod';
import { canonicalHostedMigrationPlan, readVerifiedCompletedMigrationSources, verifyPriorSchemaPrefix, type HostedMigrationPlanV1, readCanonicalMigrationSources } from './hosted-migration-plan';
import { replayPlan, posthogIntelligenceMigration } from './replay-plan';
import type {HostedMigrationStorageProjectObservation} from './hosted-migration-storage-observation';
import type { HostedExecutionJournal } from './hosted-migration-execution';
import {deriveHostedMigrationBatches} from './hosted-migration-batches';
import type {HostedMigrationBatchStage} from './hosted-migration-batches';
import {parseReconciliationTemplate,verifyReconciledPrefix} from './hosted-schema-reconciliation';

const bucket='cuevo-release-operator',failure=()=>Error('Hosted operator Storage inventory, source or metadata requires review; contents withheld.');
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
const digest=z.string().regex(/^[a-f0-9]{64}$/),sha=z.string().regex(/^[a-f0-9]{40}$/),ref=z.string().regex(/^[a-z]{20}$/),version=z.string().regex(/^[0-9]{14}$/);
const token=z.string().min(20).max(4096).regex(/^[\x21-\x7e]+$/).refine(v=>!v.startsWith('sb_publishable_'));
const identity=z.object({projectRef:ref,sourceSha:sha,treeSha:sha,planSha256:digest,stageId:z.enum(['prefix','native','pre-observability','remaining']),stageSha256:digest,databaseUrl:z.string().max(400),approvalDigest:digest,ciRunId:z.string().regex(/^[1-9][0-9]*$/).max(30),certificateSha256:digest}).strict();
export const schema=z.object({repoRoot:z.string(),sourceSha:sha,treeSha:sha,projectRef:ref,boundProjectRef:ref,providerToken:token,storageKey:token,identity,expectedVersions:z.array(version).max(1000),plan:z.unknown().optional(),batchStage:z.unknown().optional(),batchIndex:z.number().int().positive().optional()}).strict();
const count=z.union([z.number().int().nonnegative().max(1000),z.string().regex(/^(0|[1-9][0-9]*)$/).refine(v=>Number(v)<=1000)]).transform(Number);
export const countsSchema=z.object({bucketCount:count,totalObjects:count,operatorObjects:count,otherObjects:count,invalidOperatorPaths:count}).strict();
export const bucketSchema=z.object({id:z.string().max(100),name:z.string().max(100),public:z.boolean(),type:z.string().max(30),file_size_limit:z.number().int().positive(),allowed_mime_types:z.array(z.string().max(100)).max(10)}).strict();
export const objectSchema=z.object({id:z.uuid(),name:z.string().max(200),version:z.string().min(1).max(100),size:z.string().regex(/^[1-9][0-9]*$/).refine(v=>Number(v)<=49152),mimetype:z.literal('application/json'),createdAt:z.string().min(1).max(100),updatedAt:z.string().min(1).max(100)}).strict();
export const nativeHostedOperatorStorageCountsSchema=countsSchema;
const nativeBucketLimit=z.string().regex(/^[1-9][0-9]*$/).refine(value=>Number.isSafeInteger(Number(value))).transform(Number);
export const nativeHostedOperatorStorageBucketsSchema=z.array(bucketSchema.omit({file_size_limit:true}).extend({file_size_limit:nativeBucketLimit}).strict()).max(3);
export const nativeHostedOperatorStorageObjectsSchema=z.array(objectSchema.extend({bucket_id:z.literal(bucket)}).strict()).max(1000);
export type NativeHostedOperatorStorageSnapshot={observedAtMs:number;counts:z.infer<typeof countsSchema>;buckets:z.infer<typeof bucketSchema>[];rows:(z.infer<typeof objectSchema>&{bucket_id:typeof bucket})[]};
export type HostedOperatorStorageInventory={evidence:'VERIFIED_INITIAL_OPERATOR_STORAGE_INVENTORY';projectRef:string;sourceSha:string;treeSha:string;approvalDigest:string;ciRunId:string;planSha256:string;stageId:HostedExecutionJournal['identity']['stageId'];stageSha256:string;expectedVersionsSha256:string;observedAtMs:number;startedAtMs:number;bytesVerificationStartedAtMs:number;bytesVerifiedAtMs:number;countsVerifiedAtMs:number;completedAtMs:number;totalStorageObjects:number;verifiedOperatorObjects:number;applicationStorageObjects:0;bucketMetadataSha256:string;objectSetSha256:string;remoteProjectSha256:string;operations:{operation:string;state:'INTENT'|'COMMITTED'|'REQUIRES_REVIEW'|'OWNER_ONLY';identity:HostedExecutionJournal['identity'];identitySha256:string;chainSha256:string;objectCount:number}[]};
export function own(value:unknown,depth=0):unknown{
 if(depth>12)throw failure();if(value===null||typeof value==='string'||typeof value==='boolean'||typeof value==='number'&&Number.isFinite(value))return value;
 if(!value||typeof value!=='object'||types.isProxy(value)||!Array.isArray(value)&&![Object.prototype,null].includes(Object.getPrototypeOf(value)))throw failure();
 if(Array.isArray(value)){if(value.length>1000||Reflect.ownKeys(value).length!==value.length+1)throw failure();for(let i=0;i<value.length;i++){const field=Object.getOwnPropertyDescriptor(value,String(i));if(!field||!('value'in field)||!field.enumerable)throw failure();}}
 const output:Record<string,unknown>|unknown[]=Array.isArray(value)?[]:Object.create(null);for(const key of Reflect.ownKeys(value)){if(Array.isArray(value)&&key==='length')continue;const field=Object.getOwnPropertyDescriptor(value,key);if(typeof key!=='string'||!field||!('value'in field)||!field.enumerable)throw failure();Object.defineProperty(output,key,{value:own(field.value,depth+1),enumerable:true});}return output;
}
export const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
export function validTimestamp(value:string){if(!/^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{6}Z$/.test(value))return false;const date=new Date(value);return Number.isFinite(date.getTime())&&date.toISOString().slice(0,19)===value.slice(0,19);}
export function sourcePolicy(input:z.infer<typeof schema>){return sourcePolicyFromLoaded(input,readCanonicalMigrationSources(input));}
function sourcePolicyFromLoaded(input:z.infer<typeof schema>,loaded:ReturnType<typeof readCanonicalMigrationSources>){
 const replay=replayPlan(loaded.sources),names=[...replay.before,replay.prerequisite,...replay.remaining],all=names.map(n=>n.slice(0,14)),stop=replay.remaining.indexOf(posthogIntelligenceMigration);
 const supplied=input.plan===undefined?undefined:JSON.parse(canonicalHostedMigrationPlan(input.plan as HostedMigrationPlanV1).json) as HostedMigrationPlanV1;
 let completedSource:ReturnType<typeof readVerifiedCompletedMigrationSources>=null;
 if(supplied){if(supplied.source.sha!==input.sourceSha||supplied.source.tree!==input.treeSha||supplied.projectRef!==input.projectRef||canonicalHostedMigrationPlan(supplied).sha256!==input.identity.planSha256)throw failure();if(supplied.priorSchemaRelease){if(!verifyPriorSchemaPrefix(input.repoRoot,supplied))throw failure();}else{completedSource=readVerifiedCompletedMigrationSources(input.repoRoot,supplied);if(!completedSource)throw failure();}}
 const boundaries=[0,replay.before.length,replay.before.length+1,replay.before.length+1+stop,all.length].map(n=>Math.max(n,supplied?.applied.length??0));if(stop<0||new Set(input.expectedVersions).size!==input.expectedVersions.length||!boundaries.includes(input.expectedVersions.length)&&!input.batchStage||!same([...input.expectedVersions].sort(),all.slice(0,input.expectedVersions.length).sort()))throw failure();
 const stageIndex=['prefix','native','pre-observability','remaining'].indexOf(input.identity.stageId);if(input.batchStage){if(!supplied||!input.batchIndex)throw failure();const parent=input.batchStage as HostedMigrationBatchStage,batchCompletedSource=supplied.priorCompletedRelease&&parent.expectedBeforeVersions.length===supplied.priorCompletedRelease.migrationCount?completedSource:undefined,derived=deriveHostedMigrationBatches({sources:loaded.sources,stage:parent,...(batchCompletedSource?{completedSource:batchCompletedSource}:{}),...(supplied.reconciliationTemplate?{reconciliationTemplate:supplied.reconciliationTemplate}:{})}),child=derived.batches[input.batchIndex-1];if(!child||parent.id!==input.identity.stageId||derived.stageSha256!==input.identity.stageSha256||![child.expectedBeforeVersions,child.expectedAfterVersions].some(versions=>same(versions,[...input.expectedVersions].sort())))throw failure();}else if(![boundaries[stageIndex],boundaries[stageIndex+1]].includes(input.expectedVersions.length)||input.batchIndex)throw failure();
 const original=loaded.sources.find(s=>s.name==='20261001091554_private_asset_implementation.sql'),tightened=loaded.sources.find(s=>s.name==='20261001094217_private_asset_semantic_integrity.sql');
 if(!original||!tightened||hash(original.bytes)!=='5f9cef3b0f4e94decb55142a9adebf0452d9102d7139c4691f6bad1dd0a34f14'||hash(tightened.bytes)!=='a924f633d282b61bff17b50f646e288d05b59287c6fb560a3b665194e7ea0068')throw failure();
 const expected=[{id:bucket,name:bucket,public:false,type:'STANDARD',file_size_limit:49152,allowed_mime_types:['application/json']}];
 if(input.expectedVersions.includes('20261001091554'))expected.push({id:'learner-private',name:'learner-private',public:false,type:'STANDARD',file_size_limit:input.expectedVersions.includes('20261001094217')?524288:2097152,allowed_mime_types:['text/plain','image/png','image/jpeg','application/pdf']});
 return expected.sort((a,b)=>a.id.localeCompare(b.id));
}
/** Source-derived comparison policy only; no credentials, native authority or
 * provider observation is accepted or produced. */
export function nativeHostedOperatorStorageBucketPolicy(value:unknown):z.infer<typeof bucketSchema>[]{
 try{const selected=schema.omit({providerToken:true,storageKey:true}).extend({reconciliationTemplate:z.unknown().optional()}).strict().parse(own(value)),{reconciliationTemplate,...input}=selected;if(input.projectRef!==input.boundProjectRef||input.projectRef!==input.identity.projectRef||input.sourceSha!==input.identity.sourceSha||input.treeSha!==input.identity.treeSha)throw failure();if(reconciliationTemplate){const template=parseReconciliationTemplate(reconciliationTemplate),loaded=readCanonicalMigrationSources(input),replay=replayPlan(loaded.sources),rows=[...replay.before,replay.prerequisite,...replay.remaining].map(name=>({name,version:name.slice(0,14),sha256:hash(loaded.sources.find(row=>row.name===name)!.bytes)}));verifyReconciledPrefix(template,rows);if(input.batchStage||input.batchIndex||input.identity.stageId!=='prefix'||input.identity.projectRef!==template.originalIdentity.projectRef||input.identity.stageSha256!==template.originalIdentity.stageSha256||input.identity.sourceSha!==template.recoverySource.sourceSha||input.identity.treeSha!==template.recoverySource.treeSha||input.identity.ciRunId!==template.recoverySource.ciRunId||![template.prefixRows.map(row=>row.version).sort(),template.stageRows.map(row=>row.version).sort()].some(versions=>same(versions,[...input.expectedVersions].sort())))throw failure();return sourcePolicyFromLoaded({...input,expectedVersions:template.stageRows.map(row=>row.version).sort(),providerToken:'not-used-comparison-only',storageKey:'not-used-comparison-only'},loaded);}return sourcePolicy({...input,providerToken:'not-used-comparison-only',storageKey:'not-used-comparison-only'});}catch{throw failure();}
}
/** Compares actual collected observations. This result is metadata only;
 * execution still requires the database owner's opaque current permit. */
export function prepareNativeHostedOperatorStorageInventory(value:unknown):HostedOperatorStorageInventory{
 try{
  const snapshot=z.object({observedAtMs:z.number().int().safe().nonnegative(),counts:nativeHostedOperatorStorageCountsSchema,buckets:z.array(bucketSchema).max(3),rows:nativeHostedOperatorStorageObjectsSchema}).strict(),input=z.object({identity,expectedVersions:z.array(version).max(1000),before:snapshot,after:snapshot,storage:z.unknown(),expectedBuckets:z.array(bucketSchema).max(3)}).strict().parse(own(value)),before=input.before,after=input.after,storage=own(input.storage) as HostedMigrationStorageProjectObservation;
  if(storage.evidence!=='READ_ONLY_STORAGE_PROJECT_COMPARISON'||storage.projectRef!==input.identity.projectRef||!Number.isSafeInteger(storage.observedAtMs)||!Number.isSafeInteger(storage.completedAtMs)||storage.observedAtMs<before.observedAtMs||storage.completedAtMs<storage.observedAtMs||after.observedAtMs<storage.completedAtMs||!same(before.counts,after.counts)||!same(before.buckets,after.buckets)||!same(before.rows,after.rows)||!same(before.buckets,input.expectedBuckets)||before.counts.bucketCount!==input.expectedBuckets.length||before.counts.totalObjects!==before.counts.operatorObjects||before.counts.otherObjects!==0||before.counts.invalidOperatorPaths!==0||before.rows.length!==before.counts.totalObjects||new Set(input.expectedVersions).size!==input.expectedVersions.length)throw failure();
  const expectedOperator=input.expectedBuckets.find(row=>row.id===bucket);if(!expectedOperator)throw failure();const observedBucket=z.object({id:z.literal(bucket),name:z.literal(bucket),public:z.literal(false),type:z.literal('STANDARD').optional(),file_size_limit:z.literal(49152),allowed_mime_types:z.array(z.literal('application/json')).length(1)}).strict().parse(storage.bucket);if(!same({id:observedBucket.id,name:observedBucket.name,public:observedBucket.public,type:observedBucket.type??expectedOperator.type,file_size_limit:observedBucket.file_size_limit,allowed_mime_types:observedBucket.allowed_mime_types},expectedOperator))throw failure();
  const objects=z.array(z.object({path:z.string().max(200),id:z.string().min(1),version:z.string().min(1).max(100).nullable(),size:z.number().int().positive().max(49152),mimetype:z.literal('application/json'),sha256:digest,bytes:z.string().max(49152)}).strict()).max(1000).parse(storage.objects),ordered=[...objects].sort((a,b)=>a.path.localeCompare(b.path));if(objects.length!==before.rows.length||new Set(objects.map(row=>row.path)).size!==objects.length||!same(objects,ordered))throw failure();
  const pathPattern=new RegExp('^migration/v1/'+input.identity.projectRef+'/[a-f0-9]{64}/(owner[.]json|00000[1-3][.]record[.]json)$');let previous='';const ids=new Set<string>();for(const[index,row]of before.rows.entries()){const observed=objects[index];if(!pathPattern.test(row.name)||row.name<=previous||ids.has(row.id)||!validTimestamp(row.createdAt)||!validTimestamp(row.updatedAt)||!observed||observed.path!==row.name||observed.id!==row.id||observed.version!==null&&observed.version!==row.version||observed.size!==Number(row.size)||observed.mimetype!==row.mimetype||Buffer.byteLength(observed.bytes)!==observed.size||hash(observed.bytes)!==observed.sha256)throw failure();previous=row.name;ids.add(row.id);}
  const operations=z.array(z.object({operation:digest,identity,state:z.enum(['INTENT','COMMITTED','REQUIRES_REVIEW','OWNER_ONLY']),chainSha256:digest,ownerBytes:z.string().max(49152),records:z.array(z.object({bytes:z.string().max(49152),payload:z.object({version:z.literal(1),identity,state:z.enum(['INTENT','COMMITTED','REQUIRES_REVIEW']),schemaHistoryAtomic:z.literal(false),evidence:z.literal('SUPPLIED_PORT_EXECUTION_ONLY')}).strict()}).strict()).max(3),objects:z.array(z.object({path:z.string(),sha256:digest,size:z.number().int().positive().max(49152)}).strict()).min(1).max(4)}).strict()).max(1000).parse(storage.operations);
  if(operations.reduce((count,row)=>count+row.objects.length,0)!==objects.length||new Set(operations.map(row=>row.operation)).size!==operations.length)throw failure();for(const row of operations){const prefix='migration/v1/'+input.identity.projectRef+'/'+row.operation+'/',owner=JSON.stringify({version:1,purpose:'CUEVO_HOSTED_SCHEMA_MIGRATION_JOURNAL',identity:row.identity})+'\n';if(row.identity.projectRef!==input.identity.projectRef||row.operation!==hash(JSON.stringify(row.identity))||row.ownerBytes!==owner||row.chainSha256!==hash(row.ownerBytes+row.records.map(record=>record.bytes).join(''))||row.state!==(row.records.at(-1)?.payload.state??'OWNER_ONLY')||row.objects.length!==row.records.length+1||!objects.some(object=>object.path===prefix+'owner.json'&&object.bytes===row.ownerBytes))throw failure();let previousSha:string|null=null,previousState:string|undefined;for(const[index,record]of row.records.entries()){const raw=JSON.parse(record.bytes),expected={version:1,purpose:'CUEVO_HOSTED_SCHEMA_MIGRATION_JOURNAL',sequence:index+1,previousSha256:previousSha,payload:record.payload,payloadSha256:hash(JSON.stringify(record.payload))};if(record.bytes!==JSON.stringify(expected)+'\n'||!same(raw,expected)||!same(record.payload.identity,row.identity)||(previousState===undefined?record.payload.state!=='INTENT':previousState==='INTENT'?!['COMMITTED','REQUIRES_REVIEW'].includes(record.payload.state):previousState!=='COMMITTED'||record.payload.state!=='REQUIRES_REVIEW')||!objects.some(object=>object.path===prefix+String(index+1).padStart(6,'0')+'.record.json'&&object.bytes===record.bytes))throw failure();previousSha=hash(record.bytes);previousState=record.payload.state;}if(row.objects.some(object=>!objects.some(observed=>observed.path===object.path&&observed.sha256===object.sha256&&observed.size===object.size)))throw failure();}
  const receiptOperations=operations.map(row=>({operation:row.operation,identity:row.identity,state:row.state,chainSha256:row.chainSha256,objects:row.objects}));return{evidence:'VERIFIED_INITIAL_OPERATOR_STORAGE_INVENTORY',projectRef:input.identity.projectRef,sourceSha:input.identity.sourceSha,treeSha:input.identity.treeSha,approvalDigest:input.identity.approvalDigest,ciRunId:input.identity.ciRunId,planSha256:input.identity.planSha256,stageId:input.identity.stageId,stageSha256:input.identity.stageSha256,expectedVersionsSha256:hash(JSON.stringify([...input.expectedVersions].sort())),observedAtMs:storage.observedAtMs,startedAtMs:before.observedAtMs,bytesVerificationStartedAtMs:storage.observedAtMs,bytesVerifiedAtMs:storage.completedAtMs,countsVerifiedAtMs:after.observedAtMs,completedAtMs:after.observedAtMs,totalStorageObjects:before.counts.totalObjects,verifiedOperatorObjects:objects.length,applicationStorageObjects:0,bucketMetadataSha256:hash(JSON.stringify(before.buckets)),objectSetSha256:hash(JSON.stringify(before.rows)),remoteProjectSha256:hash(JSON.stringify(receiptOperations)),operations:operations.map(row=>({operation:row.operation,identity:row.identity,state:row.state,identitySha256:hash(JSON.stringify(row.identity)),chainSha256:row.chainSha256,objectCount:row.objects.length}))};
 }catch{throw failure();}
}
