import assert from 'node:assert/strict';import{test}from'node:test';import{installedPopulationFingerprint,readInstalledPopulationReceipt}from'./hosted-installed-state';import{hostedSyntheticSeedSha256}from'./hosted-migration-database';
const receipt={version:1 as const,purpose:'CUEVO_INSTALLED_SYNTHETIC_POPULATION' as const,projectRef:'mqxdjvsyckzocokuikmx',sourceSha:'a'.repeat(40),treeSha:'b'.repeat(40),seedSha256:hostedSyntheticSeedSha256 as typeof hostedSyntheticSeedSha256,manifestSha256:'c'.repeat(64)};
test('installed-state receipt retains its original source and is not an inferred population count',()=>{const rows=[{state:'COMPLETED',fingerprint:installedPopulationFingerprint(receipt),response:receipt}];assert.deepEqual(readInstalledPopulationReceipt(rows,receipt.projectRef),receipt);for(const changed of[[],[{...rows[0],state:'IN_PROGRESS'}],[{...rows[0],fingerprint:'0'.repeat(64)}],[{...rows[0],response:{...receipt,seedSha256:'0'.repeat(64)}}]])assert.throws(()=>readInstalledPopulationReceipt(changed,receipt.projectRef));assert.throws(()=>readInstalledPopulationReceipt(rows,'c'.repeat(20)));});

test('partial schema receipt remains exact stage progress and refuses forged completion or private fields',async()=>{
 const subject=await import('./hosted-installed-state');assert.equal(typeof subject.readInstalledSchemaReceipt,'function');
 const saved={version:1,purpose:'CUEVO_INSTALLED_SCHEMA_STAGE',projectRef:receipt.projectRef,sourceSha:receipt.sourceSha,treeSha:receipt.treeSha,migrationCount:1,migrations:[{version:'20261002021129',sha256:'d'.repeat(64)}],stageId:'prefix',stageSha256:'e'.repeat(64)};
 assert.deepEqual(subject.readInstalledSchemaReceipt([{decrypted_secret:JSON.stringify(saved)}],receipt.projectRef),saved);assert.equal(subject.readInstalledSchemaReceipt([],receipt.projectRef),null);
 for(const change of [{...saved,purpose:'CUEVO_COMPLETED_INSTALLED_MIGRATIONS'},{...saved,migrationCount:2},{...saved,password:'private'},{...saved,stageId:'unknown'}])assert.throws(()=>subject.readInstalledSchemaReceipt([{decrypted_secret:JSON.stringify(change)}],receipt.projectRef));
});

test('Vault prerequisite resolves actual managed signatures and verifies defaults for the reduced-argument calls',async()=>{const{installedSchemaStorageQuery}=await import('./hosted-installed-state');assert.match(installedSchemaStorageQuery,/vault\.create_secret\(text,text,text,uuid\)/);assert.match(installedSchemaStorageQuery,/vault\.update_secret\(uuid,text,text,text,uuid\)/);assert.match(installedSchemaStorageQuery,/pronargdefaults\s*>=\s*1/);assert.match(installedSchemaStorageQuery,/supabase_admin/);assert.doesNotMatch(installedSchemaStorageQuery,/to_regprocedure\('vault\.create_secret\(text,text,text\)'/);});
