import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, readdir, rm, symlink, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { readCanonicalMigrationSources, planHostedMigrations } from './hosted-migration-plan';
import { createHostedMigrationWorkdirs } from './hosted-migration-workdirs';

const ref='mqxdjvsyckzocokuikmx';
const git=(root:string,...args:string[])=>execFileSync('git',['-C',root,...args],{encoding:'utf8',stdio:['ignore','pipe','ignore'],windowsHide:true}).trim();
async function api(){let value:Record<string,unknown>={};try{value=await import(pathToFileURL(resolve(import.meta.dirname,'hosted-migration-stage-files.ts')).href);}catch(e){if((e as NodeJS.ErrnoException).code!=='ERR_MODULE_NOT_FOUND')throw e;}assert.equal(typeof value.admitHostedMigrationStageFiles,'function');return value as typeof import('./hosted-migration-stage-files');}
async function fixture(run:(input:Parameters<typeof import('./hosted-migration-stage-files').admitHostedMigrationStageFiles>[0],built:Awaited<ReturnType<typeof createHostedMigrationWorkdirs>>)=>Promise<void>,additionalSources=0){const root=await mkdtemp(join(tmpdir(),'cuevo-stage-admission-'));try{const repository=resolve(import.meta.dirname,'../..'),sourceSha=git(repository,'rev-parse','HEAD'),treeSha=git(repository,'rev-parse','HEAD^{tree}'),loaded=readCanonicalMigrationSources({repoRoot:repository,sourceSha,treeSha});const sources=[...loaded.sources,...Array.from({length:additionalSources},(_,index)=>({name:'20261007'+String(index).padStart(6,'0')+'_bounded_execution_metadata_'+String(index).padStart(3,'0')+'.sql',bytes:Buffer.from('-- Metadata-size fixture; never executed.\nselect '+index+';\n')}))];await mkdir(join(root,'supabase/migrations'),{recursive:true});await writeFile(join(root,'.gitignore'),'.local/\n');await writeFile(join(root,'.gitattributes'),'supabase/migrations/* -text\n');for(const source of sources)await writeFile(join(root,'supabase/migrations',source.name),source.bytes);git(root,'init','--quiet');git(root,'add','.');git(root,'-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','Immutable synthetic migration source');const sha=git(root,'rev-parse','HEAD'),tree=git(root,'rev-parse','HEAD^{tree}'),now=Date.now(),plan=planHostedMigrations({sources,source:{sha,tree},now,target:{projectRef:ref,boundProjectRef:ref,projectName:'Cuevo',projectStatus:'ACTIVE_HEALTHY',deploymentEnvironment:'synthetic-staging',observedAt:new Date(now).toISOString(),authUsers:0,storageObjects:0,appSchemas:[],migrationVersions:[],dispatchDisabled:true,population:'EMPTY'}}),built=await createHostedMigrationWorkdirs({repoRoot:root,sourceSha:sha,treeSha:tree,plan,outputRoot:join(root,'.local/hosted-release')});await run({repoRoot:root,sourceSha:sha,treeSha:tree,plan,stage:built.stages[0]},built);}finally{await rm(root,{recursive:true,force:true});}}
test('native stage admission binds exact clean Git source and every physical CLI input before returning a source receipt',async()=>{const{admitHostedMigrationStageFiles}=await api();await fixture(async(input,built)=>{for(const stage of built.stages){const receipt=await admitHostedMigrationStageFiles({...input,stage});assert.equal(receipt.evidence,'VERIFIED_GIT_AND_PHYSICAL_STAGE');assert.equal(receipt.sources.length,229);assert.equal(receipt.stageSha256,createHash('sha256').update(JSON.stringify({included:stage.included,configSha256:stage.configSha256})).digest('hex'));}});});
test('tampered bytes, extra inputs, reordered versions and alias workdirs fail without repairing the stage',async()=>{const{admitHostedMigrationStageFiles}=await api();await fixture(async(input)=>{const file=join(input.stage.workdir,'supabase/migrations',input.stage.included[0].name),before=await readFile(file);await writeFile(file,'select 999;');await assert.rejects(admitHostedMigrationStageFiles(input));await writeFile(file,before);const extra=join(input.stage.workdir,'supabase/migrations/extra.sql');await writeFile(extra,'select 1;');await assert.rejects(admitHostedMigrationStageFiles(input));await rm(extra);await assert.rejects(admitHostedMigrationStageFiles({...input,stage:{...input.stage,expectedAfterVersions:[...input.stage.expectedAfterVersions].reverse()}}));const config=join(input.stage.workdir,'supabase/config.toml'),text=await readFile(config);await writeFile(config,text.toString().replace('enabled = false','enabled = true'));await assert.rejects(admitHostedMigrationStageFiles(input));assert.ok((await readFile(config,'utf8')).includes('enabled = true'));});});
test('unrelated authored drift and symlinked inputs cannot attest a clean release source',async()=>{const{admitHostedMigrationStageFiles}=await api();await fixture(async(input)=>{await writeFile(join(input.repoRoot,'unreviewed.txt'),'unreviewed source');await assert.rejects(admitHostedMigrationStageFiles(input));await rm(join(input.repoRoot,'unreviewed.txt'));const config=join(input.stage.workdir,'supabase');await rm(config,{recursive:true,force:true});await symlink(join(input.repoRoot,'supabase'),config,process.platform==='win32'?'junction':'dir');await assert.rejects(admitHostedMigrationStageFiles(input));assert.ok((await readdir(input.stage.workdir)).includes('supabase'));});});

test('valid native execution metadata above the approval-package limit still admits exact Git and physical files',async()=>{const{admitHostedMigrationStageFiles}=await api();await fixture(async(input,built)=>{assert.ok(Buffer.byteLength(JSON.stringify(input.plan.migrations))>48*1024);const stage=built.stages.at(-1)!;assert.ok(Buffer.byteLength(JSON.stringify(stage.included))>48*1024);const receipt=await admitHostedMigrationStageFiles({...input,stage});assert.equal(receipt.sources.length,349);assert.equal(receipt.stageSha256,createHash('sha256').update(JSON.stringify({included:stage.included,configSha256:stage.configSha256})).digest('hex'));},120);});
