import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, readdir, rm, symlink, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { readCanonicalMigrationSources, planHostedMigrations, createCanonicalHostedMigrationPlan } from './hosted-migration-plan';
import { createHostedMigrationWorkdirs,createHostedMigrationBatchWorkdirs } from './hosted-migration-workdirs';

const ref='mqxdjvsyckzocokuikmx';
const git=(root:string,...args:string[])=>execFileSync('git',['-C',root,...args],{encoding:'utf8',stdio:['ignore','pipe','ignore'],windowsHide:true}).trim();
async function api(){let value:Record<string,unknown>={};try{value=await import(pathToFileURL(resolve(import.meta.dirname,'hosted-migration-stage-files.ts')).href);}catch(e){if((e as NodeJS.ErrnoException).code!=='ERR_MODULE_NOT_FOUND')throw e;}assert.equal(typeof value.admitHostedMigrationStageFiles,'function');return value as typeof import('./hosted-migration-stage-files');}
async function fixture(run:(input:Parameters<typeof import('./hosted-migration-stage-files').admitHostedMigrationStageFiles>[0],built:Awaited<ReturnType<typeof createHostedMigrationWorkdirs>>)=>Promise<void>,additionalSources=0){const root=await mkdtemp(join(tmpdir(),'cuevo-stage-admission-'));try{const repository=resolve(import.meta.dirname,'../..'),sourceSha=git(repository,'rev-parse','HEAD'),treeSha=git(repository,'rev-parse','HEAD^{tree}'),loaded=readCanonicalMigrationSources({repoRoot:repository,sourceSha,treeSha});const sources=[...loaded.sources,...Array.from({length:additionalSources},(_,index)=>({name:'20261007'+String(index).padStart(6,'0')+'_bounded_execution_metadata_'+String(index).padStart(3,'0')+'.sql',bytes:Buffer.from('-- Metadata-size fixture; never executed.\nselect '+index+';\n')}))];await mkdir(join(root,'supabase/migrations'),{recursive:true});await writeFile(join(root,'.gitignore'),'.local/\n');await writeFile(join(root,'.gitattributes'),'supabase/migrations/* -text\n');for(const source of sources)await writeFile(join(root,'supabase/migrations',source.name),source.bytes);git(root,'init','--quiet');git(root,'add','.');git(root,'-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','Immutable synthetic migration source');const sha=git(root,'rev-parse','HEAD'),tree=git(root,'rev-parse','HEAD^{tree}'),now=Date.now(),plan=planHostedMigrations({sources,source:{sha,tree},now,target:{projectRef:ref,boundProjectRef:ref,projectName:'Cuevo',projectStatus:'ACTIVE_HEALTHY',deploymentEnvironment:'synthetic-staging',observedAt:new Date(now).toISOString(),authUsers:0,storageObjects:0,appSchemas:[],migrationVersions:[],dispatchDisabled:true,population:'EMPTY'}}),built=await createHostedMigrationWorkdirs({repoRoot:root,sourceSha:sha,treeSha:tree,plan,outputRoot:join(root,'.local/hosted-release')});await run({repoRoot:root,sourceSha:sha,treeSha:tree,plan,stage:built.stages[0]},built);}finally{await rm(root,{recursive:true,force:true});}}
test('native stage admission binds exact clean Git source and every physical CLI input before returning a source receipt',async()=>{const{admitHostedMigrationStageFiles}=await api();await fixture(async(input,built)=>{for(const stage of built.stages){const receipt=await admitHostedMigrationStageFiles({...input,stage});assert.equal(receipt.evidence,'VERIFIED_GIT_AND_PHYSICAL_STAGE');assert.equal(receipt.sources.length,input.plan.migrations.length);assert.equal(receipt.stageSha256,createHash('sha256').update(JSON.stringify({included:stage.included,configSha256:stage.configSha256})).digest('hex'));}});});
test('tampered bytes, extra inputs, reordered versions and alias workdirs fail without repairing the stage',async()=>{const{admitHostedMigrationStageFiles}=await api();await fixture(async(input)=>{const file=join(input.stage.workdir,'supabase/migrations',input.stage.included[0].name),before=await readFile(file);await writeFile(file,'select 999;');await assert.rejects(admitHostedMigrationStageFiles(input));await writeFile(file,before);const extra=join(input.stage.workdir,'supabase/migrations/extra.sql');await writeFile(extra,'select 1;');await assert.rejects(admitHostedMigrationStageFiles(input));await rm(extra);await assert.rejects(admitHostedMigrationStageFiles({...input,stage:{...input.stage,expectedAfterVersions:[...input.stage.expectedAfterVersions].reverse()}}));const config=join(input.stage.workdir,'supabase/config.toml'),text=await readFile(config);await writeFile(config,text.toString().replace('enabled = false','enabled = true'));await assert.rejects(admitHostedMigrationStageFiles(input));assert.ok((await readFile(config,'utf8')).includes('enabled = true'));});});
test('unrelated authored drift and symlinked inputs cannot attest a clean release source',async()=>{const{admitHostedMigrationStageFiles}=await api();await fixture(async(input)=>{await writeFile(join(input.repoRoot,'unreviewed.txt'),'unreviewed source');await assert.rejects(admitHostedMigrationStageFiles(input));await rm(join(input.repoRoot,'unreviewed.txt'));const config=join(input.stage.workdir,'supabase');await rm(config,{recursive:true,force:true});await symlink(join(input.repoRoot,'supabase'),config,process.platform==='win32'?'junction':'dir');await assert.rejects(admitHostedMigrationStageFiles(input));assert.ok((await readdir(input.stage.workdir)).includes('supabase'));});});

test('valid native execution metadata above the approval-package limit still admits exact Git and physical files',async()=>{const{admitHostedMigrationStageFiles}=await api();await fixture(async(input,built)=>{assert.ok(Buffer.byteLength(JSON.stringify(input.plan.migrations))>48*1024);const stage=built.stages.at(-1)!;assert.ok(Buffer.byteLength(JSON.stringify(stage.included))>48*1024);const receipt=await admitHostedMigrationStageFiles({...input,stage});assert.equal(receipt.sources.length,input.plan.migrations.length);assert.equal(receipt.stageSha256,createHash('sha256').update(JSON.stringify({included:stage.included,configSha256:stage.configSha256})).digest('hex'));},120);});

test('physical stage admission independently verifies completed prior Git prefix before a populated append-only delta',async()=>{
 const{admitHostedMigrationStageFiles}=await api();await fixture(async input=>{
  const prior=input.plan,priorSha=input.sourceSha,priorTree=input.treeSha,count=prior.migrations.length,name='20261007122000_completed_physical_delta.sql';
  await writeFile(join(input.repoRoot,'supabase/migrations',name),'begin;\nselect 1;\ncommit;\n');git(input.repoRoot,'add','.');git(input.repoRoot,'-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','append immutable native source');
  const sourceSha=git(input.repoRoot,'rev-parse','HEAD'),treeSha=git(input.repoRoot,'rev-parse','HEAD^{tree}'),now=Date.now();
  const priorReceipt={projectRef:ref,sourceSha:priorSha,treeSha:priorTree,migrations:prior.migrations.map(({version,sha256})=>({version,sha256})),completedSourceMigrationCount:count};
  const target={projectRef:ref,boundProjectRef:ref,projectName:'Cuevo',projectStatus:'ACTIVE_HEALTHY',deploymentEnvironment:'synthetic-staging',observedAt:new Date(now).toISOString(),authUsers:133,storageObjects:12,appSchemas:['app','authorization','internal'],migrationVersions:prior.migrations.map(row=>row.version),dispatchDisabled:true,population:'GUARDED_SYNTHETIC'};
  const{plan}=createCanonicalHostedMigrationPlan({repoRoot:input.repoRoot,sourceSha,treeSha,target,priorReceipt,now});
  const built=await createHostedMigrationWorkdirs({repoRoot:input.repoRoot,sourceSha,treeSha,plan,outputRoot:join(input.repoRoot,'.local/hosted-release')});
  for(const stage of built.stages){const receipt=await admitHostedMigrationStageFiles({repoRoot:input.repoRoot,sourceSha,treeSha,plan,stage});assert.equal(receipt.sources.length,count+1);}
  const batchWork=await createHostedMigrationBatchWorkdirs({repoRoot:input.repoRoot,sourceSha,treeSha,plan,stage:built.stages[3],outputRoot:join(input.repoRoot,'.local/hosted-release')});assert.equal(batchWork.batches.length,1);const batch=batchWork.batches[0];assert.deepEqual(batch.pending.map(row=>row.name),[name]);const batchReceipt=await(await api()).admitHostedMigrationBatchFiles({repoRoot:input.repoRoot,sourceSha,treeSha,plan,stage:built.stages[3],batch});assert.equal(batchReceipt.evidence,'VERIFIED_GIT_AND_PHYSICAL_BATCH');assert.equal(batchReceipt.batchSha256,batch.batchSha256);
  await assert.rejects((await api()).admitHostedMigrationBatchFiles({repoRoot:input.repoRoot,sourceSha,treeSha,plan:{...plan,priorCompletedRelease:{...plan.priorCompletedRelease!,treeSha:'0'.repeat(40)}},stage:built.stages[3],batch}));
  await assert.rejects(admitHostedMigrationStageFiles({repoRoot:input.repoRoot,sourceSha,treeSha,plan:{...plan,priorCompletedRelease:{...plan.priorCompletedRelease!,sourceSha:'0'.repeat(40)}},stage:built.stages[0]}));
  const final=built.stages.at(-1)!,file=join(final.workdir,'supabase/migrations',name);await writeFile(file,'select 999;\n');await assert.rejects(admitHostedMigrationStageFiles({repoRoot:input.repoRoot,sourceSha,treeSha,plan,stage:final}));
 });
});

const recoveryProjectRef='mqxdjvsyckzocokuikmx',recoveryHash=(value:string)=>createHash('sha256').update(value).digest('hex');
function reconciliationTemplateFor(rows:{name:string;version:string;sha256:string}[],recovery:{sha:string;tree:string}){
 const originalIdentity={projectRef:recoveryProjectRef,sourceSha:'d87455114cac2d22d63d040ce5b13e6b2e74e743',treeSha:'1e85393d46beb4f5356e07277a13a7ef33cc67d9',planSha256:'413d23ed86f7379b3e88b90e09370762ce576d0395f4c4fceaa44d0f3abf3cf1',stageId:'prefix',stageSha256:'5f9e1d7804d816dc3ee387f126f946a0ee0ac3b192b3d4973774cbf33b2ba506',databaseUrl:'postgresql://postgres.mqxdjvsyckzocokuikmx@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=verify-full',approvalDigest:'d46d4616c1b9eecdcd474b080bfefac98ee959fb7c54819d510773fc661a98de',ciRunId:'37702851953',certificateSha256:'700723581420dd1ac98fd7e9ac529f0ef210eadcaf87fc868a3ad7d114c2f3b7'};
 const ownerJson=JSON.stringify({version:1,purpose:'CUEVO_HOSTED_SCHEMA_MIGRATION_JOURNAL',identity:originalIdentity})+'\n',payload=(state:string)=>({version:1,identity:originalIdentity,state,schemaHistoryAtomic:false,evidence:'SUPPLIED_PORT_EXECUTION_ONLY'});
 const first=JSON.stringify({version:1,purpose:'CUEVO_HOSTED_SCHEMA_MIGRATION_JOURNAL',sequence:1,previousSha256:null,payload:payload('INTENT'),payloadSha256:recoveryHash(JSON.stringify(payload('INTENT')))})+'\n',second=JSON.stringify({version:1,purpose:'CUEVO_HOSTED_SCHEMA_MIGRATION_JOURNAL',sequence:2,previousSha256:recoveryHash(first),payload:payload('REQUIRES_REVIEW'),payloadSha256:recoveryHash(JSON.stringify(payload('REQUIRES_REVIEW')))})+'\n';
 return{version:1,purpose:'CUEVO_UNKNOWN_PREFIX_RECONCILIATION_TEMPLATE',recoverySource:{sourceSha:recovery.sha,treeSha:recovery.tree,ciRunId:'37710000000',releaseRunId:'37710000001',runAttempt:1},originalRunId:'37703459549',originalRunAttempt:1,originalIdentity,ownerJson,recordJson:[first,second],stageRows:rows.slice(0,123),prefixRows:rows.slice(0,120),configSha256:'cc91534b07b96e61b993f179225a9929b65e965d19a5a02e242c79126166b4ff',historySha256:'e'.repeat(64),cataloguePolicySha256:'f'.repeat(64),catalogueSha256:'1'.repeat(64),absencePolicySha256:'2'.repeat(64),endpointSha256:'3'.repeat(64)};
}


test('physical stage admission accepts only exact original120 template recovery and rejects removal or pending drift',async()=>{
 const {admitHostedMigrationStageFiles}=await api(),repository=resolve(import.meta.dirname,'../..'),root=await mkdtemp(join(tmpdir(),'cuevo-reconciliation-stage-'));
 try{git(root,'clone','--shared','--no-checkout','--quiet',repository,'.');git(root,'checkout','--quiet','--detach','d87455114cac2d22d63d040ce5b13e6b2e74e743');
  const sourceSha=git(root,'rev-parse','HEAD'),treeSha=git(root,'rev-parse','HEAD^{tree}'),loaded=readCanonicalMigrationSources({repoRoot:root,sourceSha,treeSha}),now=Date.parse('2026-10-08T01:00:00Z'),source={sha:sourceSha,tree:treeSha};
  const empty={projectRef:recoveryProjectRef,boundProjectRef:recoveryProjectRef,projectName:'Cuevo',projectStatus:'ACTIVE_HEALTHY',deploymentEnvironment:'synthetic-staging',observedAt:new Date(now).toISOString(),authUsers:0,storageObjects:0,appSchemas:[],migrationVersions:[],dispatchDisabled:true,population:'EMPTY'},initial=planHostedMigrations({sources:loaded.sources,source,target:empty,now}),prefix=initial.migrations.slice(0,120),priorReceipt={projectRef:recoveryProjectRef,sourceSha,treeSha,migrations:prefix.map(({version,sha256})=>({version,sha256}))},template=reconciliationTemplateFor(initial.migrations,source);
  const plan=createCanonicalHostedMigrationPlan({repoRoot:root,sourceSha,treeSha,now,target:{...empty,population:'SCHEMA_ONLY',appSchemas:['app','authorization','internal'],migrationVersions:prefix.map(r=>r.version)},priorReceipt,reconciliationTemplate:template}).plan,built=await createHostedMigrationWorkdirs({repoRoot:root,sourceSha,treeSha,plan,outputRoot:join(root,'.local/hosted-release')}),input={repoRoot:root,sourceSha,treeSha,plan,stage:built.stages[0]};
  const receipt=await admitHostedMigrationStageFiles(input);assert.equal(receipt.evidence,'VERIFIED_GIT_AND_PHYSICAL_STAGE');assert.equal(input.stage.pending.length,3);
  await assert.rejects(admitHostedMigrationStageFiles({...input,plan:{...plan,reconciliationTemplate:undefined}}));
  await assert.rejects(admitHostedMigrationStageFiles({...input,stage:{...input.stage,pending:input.stage.pending.slice(1)}}));
 }finally{await rm(root,{recursive:true,force:true});}
});

test('batch admission rederives parent identity and exact cumulative files while rejecting drift and arbitrary cursors',async()=>{
 const subject=await api();assert.equal(typeof subject.admitHostedMigrationBatchFiles,'function');
 await fixture(async(input,built)=>{const stage=built.stages[3],batches=await createHostedMigrationBatchWorkdirs({...input,stage,outputRoot:join(input.repoRoot,'.local/hosted-release')});assert.deepEqual(batches.batches.map(batch=>batch.pending.length),[20,20,10]);
  for(const batch of batches.batches){const result=await subject.admitHostedMigrationBatchFiles({...input,stage,batch});assert.equal(result.stageSha256,batches.stageSha256);assert.equal(result.batchSha256,batch.batchSha256);assert.equal(result.planSha256,batches.planSha256);}
  const batch=batches.batches[0],file=join(batch.workdir,'supabase/migrations',batch.cumulativeIncluded[0].name),original=await readFile(file);await writeFile(file,'select 999;');await assert.rejects(subject.admitHostedMigrationBatchFiles({...input,stage,batch}));await writeFile(file,original);
  await assert.rejects(subject.admitHostedMigrationBatchFiles({...input,stage,batch:{...batch,index:2}}));await assert.rejects(subject.admitHostedMigrationBatchFiles({...input,stage,batch:{...batch,expectedBeforeVersions:batch.expectedBeforeVersions.slice(1)}}));
  const extra=join(batch.workdir,'supabase/migrations/extra.sql');await writeFile(extra,'select 1;');await assert.rejects(subject.admitHostedMigrationBatchFiles({...input,stage,batch}));await rm(extra);
  const first=join(batch.workdir,'supabase/migrations',batch.cumulativeIncluded[0].name),saved=await readFile(first);await rm(first);await symlink(join(stage.workdir,'supabase/migrations'),first,process.platform==='win32'?'junction':'dir');await assert.rejects(subject.admitHostedMigrationBatchFiles({...input,stage,batch}));await rm(first);await writeFile(first,saved);
  const originalManifest=await readFile(batch.manifestPath),forged=JSON.parse(originalManifest.toString());forged.index='1';const forgedBytes=(await import('../verification/release-review')).canonicalReleaseExecutionJson(forged)+'\n';await writeFile(batch.manifestPath,forgedBytes);await assert.rejects(subject.admitHostedMigrationBatchFiles({...input,stage,batch:{...batch,index:'1',manifestSha256:createHash('sha256').update(forgedBytes).digest('hex')}} as never));await writeFile(batch.manifestPath,originalManifest);
  const bytes=await readFile(batch.manifestPath);await writeFile(batch.manifestPath,bytes.toString().replace('NOT_EXECUTED','VERIFIED'));await assert.rejects(subject.admitHostedMigrationBatchFiles({...input,stage,batch}));
 });
});
