import {Controller,Get,Post,Req,Res,type Type}from'@nestjs/common';import{ApiBearerAuth,ApiHeader,ApiBody}from'@nestjs/swagger';import{z}from'zod';import type{FastifyRequest,FastifyReply}from'fastify';import{DomainError}from'@cuevo/domain';import{resourceStageSchema,assetFinalizeSchema,assetRetireSchema,submissionWorkInputSchema,submissionWorkDraftSchema,submissionWorkResubmitSchema}from'@cuevo/contracts';import type{IdentityService}from'../../platform/identity/identity.service';import type{Database}from'../../platform/database/database';import{createAssetStorage,assetContentDisposition,type AssetStoragePort}from'../assets/public';import{SubmissionAssetService}from'./submission-asset.service';
const body=(schema:z.ZodType)=>ApiBody({required:true,schema:z.toJSONSchema(schema,{target:'openapi-3.0'})as never});
export function createSubmissionAssetController(identity:IdentityService,database:Database,config:{url?:string;secret?:string},storage?:AssetStoragePort):Type<unknown>{const service=new SubmissionAssetService(identity,database,storage??createAssetStorage(config));@Controller('/v1')@ApiBearerAuth()class SubmissionAssetController{
 private context(r:FastifyRequest){const school=r.headers['x-school-id'];if(Array.isArray(school))throw new DomainError('INVALID_INPUT',400,'School selector invalid.');return{header:r.headers.authorization,school};}
 private async respond(r:FastifyRequest,p:FastifyReply,run:()=>Promise<unknown>){try{return p.code(200).header('Cache-Control','no-store').send(await run());}catch(error){const code=error&&typeof error==='object'&&'code'in error?String(error.code):'';const safe=error instanceof DomainError?error:new DomainError(code==='42501'?'FORBIDDEN':['22023','23505','55000'].includes(code)?'SUBMISSION_WORK_REQUIRES_REVIEW':'REQUEST_UNAVAILABLE',code==='42501'?403:['22023','23505','55000'].includes(code)?409:503,'Submitted work is unavailable or requires review.');return p.code(safe.status).header('Cache-Control','no-store').send({code:safe.code,message:safe.message,requestId:r.id});}}
 @Post('/assessments/:id/work-assets')@body(resourceStageSchema)@ApiHeader({name:'Idempotency-Key',required:true})stage(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,()=>{const c=this.context(r);return service.stage(c.header,c.school,(r.params as{id:string}).id,r.body,r.headers['idempotency-key'],r.id);});}
 @Post('/assessments/:id/work-assets/:assetId/finalize')@body(assetFinalizeSchema)@ApiHeader({name:'Idempotency-Key',required:true})finalize(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,()=>{const c=this.context(r);const s=r.params as{id:string;assetId:string};return service.finalize(c.header,c.school,s.id,s.assetId,r.body,r.headers['idempotency-key'],r.id);});}
 @Post('/assessments/:id/work-assets/:assetId/retire')@body(assetRetireSchema)@ApiHeader({name:'Idempotency-Key',required:true})retire(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,()=>{const c=this.context(r);const s=r.params as{id:string;assetId:string};return service.retire(c.header,c.school,s.id,s.assetId,r.body,r.headers['idempotency-key'],r.id);});}
 @Get('/assessments/:id/work-draft')draft(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,()=>{const c=this.context(r);return service.draft(c.header,c.school,(r.params as{id:string}).id);});}
 @Post('/assessments/:id/work-draft')@body(submissionWorkDraftSchema)@ApiHeader({name:'Idempotency-Key',required:true})saveDraft(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.work(r,p,'draft');}
 @Post('/assessments/:id/work-submissions')@body(submissionWorkInputSchema)@ApiHeader({name:'Idempotency-Key',required:true})submit(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.work(r,p,'submit');}
 @Post('/assessments/:id/work-submissions/:submissionId/resubmit')@body(submissionWorkResubmitSchema)@ApiHeader({name:'Idempotency-Key',required:true})resubmit(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.work(r,p,'resubmit');}
 private work(r:FastifyRequest,p:FastifyReply,kind:'draft'|'submit'|'resubmit'){return this.respond(r,p,()=>{const c=this.context(r);const s=r.params as{id:string;submissionId?:string};return service.work(c.header,c.school,kind,s.id,s.submissionId??null,r.body,r.headers['idempotency-key'],r.id);});}
 @Get('/submissions/:id/source-work')source(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,()=>{const c=this.context(r);return service.source(c.header,c.school,(r.params as{id:string}).id);});}
 @Get('/submissions/:id/artifacts/:assetId/download')download(@Req()r:FastifyRequest,@Res()p:FastifyReply){return this.respond(r,p,async()=>{const c=this.context(r);const s=r.params as{id:string;assetId:string};const result=await service.download(c.header,c.school,s.id,s.assetId);p.header('Content-Type',result.asset.contentType).header('Content-Disposition',assetContentDisposition(result.asset.name)).header('X-Content-Type-Options','nosniff');return result.bytes;});}
 }return SubmissionAssetController;}

