import{createHash}from'node:crypto';import{z}from'zod';import{DomainError,requireCapability,type ActorContext}from'@cuevo/domain';import{communityRoomSchema,communityMembershipSchema,communityPostSchema,communityReactionSchema,communityReportSchema,communityModerationSchema,communityRestrictionSchema,communityAnnouncementSchema,communityReadSchema,communityQuerySchema,idempotencyKeySchema}from'@cuevo/contracts';import type{Database}from'../../platform/database/database';
export const communitySchemas={'room.create':communityRoomSchema,'member.configure':communityMembershipSchema,'post.create':communityPostSchema,'reaction.configure':communityReactionSchema,'report.create':communityReportSchema,'post.moderate':communityModerationSchema,'room.restrict':communityRestrictionSchema,'announcement.create':communityAnnouncementSchema,'notification.read':communityReadSchema};export type CommunityCommand=keyof typeof communitySchemas;export type CommunityResource='rooms'|'roster'|'posts'|'reports'|'announcements'|'notifications';
function parse<T>(s:z.ZodType<T>,v:unknown){const r=s.safeParse(v);if(!r.success)throw new DomainError('INVALID_INPUT',400,'Review the community fields.');return r.data;}
function safe(e:unknown){if(e instanceof DomainError)return e;const code=typeof e==='object'&&e!==null&&'code'in e?String(e.code):'';if(code==='42501')return new DomainError('FORBIDDEN',403,'Your current access does not permit this community action.');if(code==='P0003')return new DomainError('COMMUNITY_RATE_LIMITED',429,'Wait before sending another community action.');if(['22023','23505','55000'].includes(code))return new DomainError('COMMUNITY_CONFLICT',409,'Review the current room, post or membership.');return new DomainError('REQUEST_UNAVAILABLE',503,'Community services are temporarily unavailable.');}
export class CommunityService{constructor(private readonly database:Database){}
async announcement(actor:ActorContext,target:string){requireCapability(actor,actor.schoolId,'community',['admin','coordinator','teacher','student','parent']);parse(z.uuid(),target);try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>(await c.query('select internal.read_community_announcement($1)as source',[target])).rows[0]?.source);}catch(e){throw safe(e);}}
async list(actor:ActorContext,resource:CommunityResource,target:string|undefined,query:unknown){requireCapability(actor,actor.schoolId,'community',['admin','coordinator','teacher','student','parent']);if(target)parse(z.uuid(),target);const page=parse(communityQuerySchema,query);try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>(await c.query('select internal.community_list($1,$2,$3::jsonb)as response',[resource,target??null,JSON.stringify(page)])).rows[0]?.response);}catch(e){throw safe(e);}}
async command(actor:ActorContext,command:CommunityCommand,target:string|undefined,body:unknown,key:unknown,request:string){const roles=command==='room.create'||command==='member.configure'||command==='post.moderate'||command==='room.restrict'||command==='announcement.create'?['admin','teacher']as const:command==='notification.read'?['admin','coordinator','teacher','student','parent']as const:['admin','teacher','student']as const;requireCapability(actor,actor.schoolId,'community',roles);const input=parse(communitySchemas[command]as z.ZodType<Record<string,unknown>>,body);if(target)parse(z.uuid(),target);const identity=parse(idempotencyKeySchema,key);const hash=createHash('sha256').update(JSON.stringify({command,target:target??null,input})).digest('hex');try{return await this.database.actorTransaction(actor.userId,actor.schoolId,async c=>{const response=(await c.query('select internal.community_command($1,$2,$3::jsonb,$4,$5,$6)as response',[command,target??null,JSON.stringify(input),identity,hash,request])).rows[0]?.response;if(!response)throw new DomainError('REQUEST_UNAVAILABLE',503,'Community command receipt is unconfirmed.');return response;});}catch(e){throw safe(e);}}
}
