begin;
create table app.course_objective_plans(
 school_id uuid not null,id uuid not null default gen_random_uuid(),course_id uuid not null,reference_id uuid not null,period_id uuid not null,period_revision integer not null check(period_revision>0),period_context jsonb not null,reason text not null check(length(btrim(reason))between 1 and 2000),created_by uuid not null,created_at timestamptz not null default clock_timestamp(),
 primary key(school_id,id),unique(school_id,course_id,reference_id,period_id,period_revision),foreign key(school_id,course_id)references app.courses(school_id,id),foreign key(school_id,reference_id)references app.school_custom_references(school_id,id),foreign key(school_id,period_id)references app.report_periods(school_id,id),foreign key(school_id,created_by)references app.memberships(school_id,actor_id),check(jsonb_typeof(period_context)='object')
);
create table app.objective_taught_records(
 school_id uuid not null,id uuid not null default gen_random_uuid(),plan_id uuid not null,lesson_id uuid not null,taught_on date not null,note text not null check(length(btrim(note))between 1 and 2000),created_by uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,plan_id,lesson_id,taught_on),foreign key(school_id,plan_id)references app.course_objective_plans(school_id,id),foreign key(school_id,lesson_id)references app.lessons(school_id,id),foreign key(school_id,created_by)references app.memberships(school_id,actor_id)
);
create table app.objective_plan_assessments(
 school_id uuid not null,id uuid not null default gen_random_uuid(),plan_id uuid not null,assessment_id uuid not null,policy_version integer not null check(policy_version>0),reason text not null check(length(btrim(reason))between 1 and 2000),created_by uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,plan_id,assessment_id),foreign key(school_id,plan_id)references app.course_objective_plans(school_id,id),foreign key(school_id,assessment_id)references app.assessments(school_id,id),foreign key(school_id,created_by)references app.memberships(school_id,actor_id)
);
do $$declare tab text;begin foreach tab in array array['course_objective_plans','objective_taught_records','objective_plan_assessments']loop
 execute format('alter table app.%I enable row level security',tab);execute format('alter table app.%I force row level security',tab);
 execute format('revoke all on app.%I from public,anon,authenticated,service_role,cuevo_api,cuevo_worker',tab);
 execute format('create trigger plan_immutable before update or delete on app.%I for each row execute function internal.academic_history_immutable()',tab);execute format('create trigger plan_no_truncate before truncate on app.%I for each statement execute function internal.academic_history_immutable()',tab);
end loop;end$$;
create function internal.objective_plan_assessment_frozen()returns trigger language plpgsql security definer set search_path=''as $$begin
 if(new.course_id is distinct from old.course_id or new.academic_reference_id is distinct from old.academic_reference_id or new.policy_version is distinct from old.policy_version)and exists(select 1 from app.objective_plan_assessments inclusion where inclusion.school_id=old.school_id and inclusion.assessment_id=old.id)then raise exception 'Planned assessment objective/policy is immutable'using errcode='55000';end if;return new;
end$$;
create trigger objective_plan_assessment_frozen before update on app.assessments for each row execute function internal.objective_plan_assessment_frozen();
create function internal.require_objective_plan_course(target_course uuid,write_access boolean)returns void language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();begin
 perform internal.require_course_objective_access(target_course,false);
 if not"authorization".academic_access(school)or not"authorization".school_operations_access(school)or(write_access and("authorization".current_role(school)not in('teacher','admin')or not"authorization".can_manage_course(school,target_course)))then raise exception 'Objective planning access denied'using errcode='42501';end if;
end$$;
create function internal.objective_plan_period(target_course uuid,target_period uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();period jsonb;begin
 period:=internal.school_record_current('report-periods',target_period);
 if period is null or period->>'recordState'='CANCELLED'or not exists(select 1 from app.courses course join app.classes class on class.school_id=course.school_id and class.id=course.class_id join app.terms term on term.school_id=class.school_id and term.academic_year_id=class.academic_year_id where course.school_id=school and course.id=target_course and term.id=(period->>'termId')::uuid)then raise exception 'Current report period and course year require review'using errcode='22023';end if;return period;
end$$;
create function internal.record_objective_plan(command_name text,target_id uuid,payload jsonb,command_key text,fingerprint text,request_id text)returns jsonb language plpgsql security definer set search_path=''as $$
declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();plan app.course_objective_plans;period jsonb;planned_course uuid;rid uuid;reservation jsonb;receipt jsonb;begin
 if command_name='plan.create'then planned_course:=target_id;else select*into plan from app.course_objective_plans where school_id=school and id=target_id;planned_course:=plan.course_id;end if;
 perform internal.require_objective_plan_course(planned_course,true);
 if payload is null or jsonb_typeof(payload)<>'object'or jsonb_typeof(payload->'expectedPeriodRevision')is distinct from'number'or payload->>'expectedPeriodRevision'!~'^[1-9][0-9]*$'then raise exception 'Explicit current period required'using errcode='22023';end if;
 perform pg_advisory_xact_lock(hashtextextended(school::text||':school-record-maintenance',0));perform internal.lock_academic_course(school,planned_course);perform internal.require_objective_plan_course(planned_course,true);
 if command_name='plan.create'then
  if payload-'referenceId'-'periodId'-'expectedPeriodRevision'-'reason'-'confirmPlanning'<>'{}'::jsonb or payload->'confirmPlanning'is distinct from'true'::jsonb or jsonb_typeof(payload->'reason')is distinct from'string'or length(btrim(payload->>'reason'))not between 1 and 2000 then raise exception 'Human objective plan confirmation required'using errcode='22023';end if;
  period:=internal.objective_plan_period(planned_course,(payload->>'periodId')::uuid);
  if not exists(select 1 from app.school_custom_references reference where reference.school_id=school and reference.id=(payload->>'referenceId')::uuid and reference.status='APPROVED')or(exists(select 1 from app.programme_course_contexts pinned where pinned.school_id=school and pinned.course_id=planned_course)and not exists(select 1 from app.course_objective_approvals approval where approval.school_id=school and approval.course_id=planned_course and approval.academic_reference_id=(payload->>'referenceId')::uuid))then raise exception 'Approved course objective required'using errcode='22023';end if;
 elsif command_name='plan.revalidate'then
  if payload-'expectedPeriodRevision'-'reason'-'confirmPlanning'<>'{}'::jsonb or payload->'confirmPlanning'is distinct from'true'::jsonb or jsonb_typeof(payload->'reason')is distinct from'string'or length(btrim(payload->>'reason'))not between 1 and 2000 then raise exception 'Explicit replan review required'using errcode='22023';end if;
  select*into plan from app.course_objective_plans where school_id=school and id=target_id for update;
  period:=internal.objective_plan_period(planned_course,plan.period_id);
 else
  select*into plan from app.course_objective_plans where school_id=school and id=target_id for update;
  period:=internal.objective_plan_period(planned_course,plan.period_id);if(period->>'revision')::integer<>plan.period_revision then raise exception 'Planned period context changed'using errcode='22023';end if;
 end if;
 if(period->>'revision')::integer is distinct from(payload->>'expectedPeriodRevision')::integer then raise exception 'Report period version changed'using errcode='22023';end if;
 if command_name='taught.create'then
  if payload-'lessonId'-'taughtOn'-'expectedPeriodRevision'-'note'-'confirmTeaching'<>'{}'::jsonb or payload->'confirmTeaching'is distinct from'true'::jsonb or jsonb_typeof(payload->'note')is distinct from'string'or jsonb_typeof(payload->'taughtOn')is distinct from'string'or length(btrim(payload->>'note'))not between 1 and 2000 or(payload->>'taughtOn')::date<(period->>'startsOn')::date or(payload->>'taughtOn')::date>(period->>'endsOn')::date or(payload->>'taughtOn')::date>(clock_timestamp()at time zone'UTC')::date or not exists(select 1 from app.lessons lesson join app.units unit on unit.school_id=lesson.school_id and unit.id=lesson.unit_id where lesson.school_id=school and lesson.id=(payload->>'lessonId')::uuid and unit.course_id=planned_course)then raise exception 'Explicit taught course lesson and period date required'using errcode='22023';end if;
 elsif command_name='assessment.create'then
  if payload-'assessmentId'-'expectedPolicyVersion'-'expectedPeriodRevision'-'reason'-'confirmInclusion'<>'{}'::jsonb or payload->'confirmInclusion'is distinct from'true'::jsonb or jsonb_typeof(payload->'reason')is distinct from'string'or length(btrim(payload->>'reason'))not between 1 and 2000 or not exists(select 1 from app.assessments assessment where assessment.school_id=school and assessment.id=(payload->>'assessmentId')::uuid and assessment.course_id=planned_course and assessment.academic_reference_id=plan.reference_id and assessment.status='PUBLISHED'and assessment.policy_version=(payload->>'expectedPolicyVersion')::integer)then raise exception 'Exact published planned assessment required'using errcode='22023';end if;
 elsif command_name not in('plan.create','plan.revalidate')then raise exception 'Unknown planning command'using errcode='22023';end if;
 reservation:=internal.begin_command(command_key,'objective.'||command_name,fingerprint);if reservation->>'state'='COMPLETED'then return reservation->'response';end if;if reservation->>'state'<>'NEW'then raise exception 'Planning command in progress'using errcode='22023';end if;
 if command_name='plan.revalidate'and((period->>'revision')::integer<=plan.period_revision or exists(select 1 from app.course_objective_plans newer where newer.school_id=school and newer.course_id=plan.course_id and newer.period_id=plan.period_id and newer.reference_id=plan.reference_id and newer.period_revision>plan.period_revision))then raise exception 'Latest changed period plan requires explicit review'using errcode='22023';end if;
 if command_name='plan.create'then insert into app.course_objective_plans(school_id,course_id,reference_id,period_id,period_revision,period_context,reason,created_by)values(school,planned_course,(payload->>'referenceId')::uuid,(payload->>'periodId')::uuid,(period->>'revision')::integer,period,btrim(payload->>'reason'),actor)returning id into rid;
 elsif command_name='plan.revalidate'then insert into app.course_objective_plans(school_id,course_id,reference_id,period_id,period_revision,period_context,reason,created_by)values(school,planned_course,plan.reference_id,plan.period_id,(period->>'revision')::integer,period,btrim(payload->>'reason'),actor)returning id into rid;
 elsif command_name='taught.create'then insert into app.objective_taught_records(school_id,plan_id,lesson_id,taught_on,note,created_by)values(school,plan.id,(payload->>'lessonId')::uuid,(payload->>'taughtOn')::date,btrim(payload->>'note'),actor)returning id into rid;
 else insert into app.objective_plan_assessments(school_id,plan_id,assessment_id,policy_version,reason,created_by)values(school,plan.id,(payload->>'assessmentId')::uuid,(payload->>'expectedPolicyVersion')::integer,btrim(payload->>'reason'),actor)returning id into rid;end if;
 receipt:=jsonb_build_object('id',rid,'courseId',planned_course,'periodRevision',(period->>'revision')::integer);
 perform internal.append_audit('objective.'||command_name,'curriculum',rid,request_id,'succeeded',jsonb_build_object('courseId',planned_course));perform internal.enqueue_event('curriculum.configured','curriculum',planned_course,1,jsonb_build_object('planningSourceId',rid),md5('objective-plan:'||actor::text||':'||command_name||':'||command_key));perform internal.finish_command(command_key,'objective.'||command_name,fingerprint,receipt);return receipt;
end$$;
create function internal.read_period_objective_coverage(target_course uuid,target_period uuid,page_limit integer,page_cursor uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$
declare school uuid:="authorization".school_id();period jsonb;context jsonb;learner_count integer;planned_count integer;items jsonb;next_cursor uuid;status text;begin
 perform internal.require_objective_plan_course(target_course,false);
 if page_limit is null or page_limit not between 1 and 25 then raise exception 'Bounded planned coverage required'using errcode='22023';end if;
 period:=internal.school_record_current('report-periods',target_period);
 if period is null or not exists(select 1 from app.courses course join app.classes class on class.school_id=course.school_id and class.id=course.class_id join app.terms term on term.school_id=class.school_id and term.academic_year_id=class.academic_year_id where course.school_id=school and course.id=target_course and term.id=(period->>'termId')::uuid)then raise exception 'Selected period/course scope denied'using errcode='42501';end if;
 select jsonb_build_object('courseId',course.id,'courseTitle',course.title,'className',class.name,'periodId',target_period,'periodName',period->>'name','startsOn',period->>'startsOn','endsOn',period->>'endsOn','periodRevision',(period->>'revision')::integer)into context from app.courses course join app.classes class on class.school_id=course.school_id and class.id=course.class_id where course.school_id=school and course.id=target_course;
 select count(distinct enrollment.student_actor_id)into learner_count from app.enrollments enrollment join app.courses course on course.school_id=enrollment.school_id and course.class_id=enrollment.class_id where course.school_id=school and course.id=target_course and"authorization".current_learner_course(school,target_course,enrollment.student_actor_id);
 select count(distinct reference_id)into planned_count from app.course_objective_plans where school_id=school and course_id=target_course and period_id=target_period;
 status:=case when planned_count=0 then'NOT_ESTABLISHED'when period->>'recordState'='CANCELLED'or exists(select 1 from app.course_objective_plans plan where plan.school_id=school and plan.course_id=target_course and plan.period_id=target_period and plan.period_revision<>(period->>'revision')::integer and not exists(select 1 from app.course_objective_plans newer where newer.school_id=plan.school_id and newer.course_id=plan.course_id and newer.period_id=plan.period_id and newer.reference_id=plan.reference_id and newer.period_revision>plan.period_revision))then'REQUIRES_REVIEW'else'DECLARED'end;
 with plans as materialized(select plan.*from app.course_objective_plans plan where plan.school_id=school and plan.course_id=target_course and plan.period_id=target_period and not exists(select 1 from app.course_objective_plans newer where newer.school_id=plan.school_id and newer.course_id=plan.course_id and newer.period_id=plan.period_id and newer.reference_id=plan.reference_id and newer.period_revision>plan.period_revision)and(page_cursor is null or plan.id>page_cursor)order by plan.id limit page_limit+1),visible as(select*from plans order by id limit page_limit),sources as materialized(
  select inclusion.plan_id,result.id,result.evidence_id,result.learner_id,result.native_result,person.display_name
  from app.objective_plan_assessments inclusion join app.course_objective_plans plan on plan.school_id=inclusion.school_id and plan.id=inclusion.plan_id join visible on visible.id=plan.id
  join app.assessments assessment on assessment.school_id=inclusion.school_id and assessment.id=inclusion.assessment_id and assessment.academic_reference_id=plan.reference_id and assessment.policy_version=inclusion.policy_version
  join lateral(
   select result.id,result.evidence_id,result.learner_id,jsonb_build_object('type','numeric','score',result.score,'maxScore',result.max_score,'policyVersion',result.policy_version)native_result from app.current_results current_result join app.result_revisions result on result.school_id=current_result.school_id and result.id=current_result.result_id join app.current_submissions pointer on pointer.school_id=result.school_id and pointer.submission_id=result.submission_id join app.academic_evidence evidence on evidence.school_id=result.school_id and evidence.id=result.evidence_id and evidence.result_id=result.id and evidence.source_object_id=result.submission_id and evidence.learner_id=result.learner_id join app.school_custom_references reference on reference.school_id=result.school_id and reference.id=result.reference_id and reference.status='APPROVED'join app.school_custom_versions version on version.school_id=reference.school_id and version.id=reference.version_id and version.version=result.reference_version where result.school_id=school and result.assessment_id=assessment.id and result.reference_id=plan.reference_id and result.policy_version=inclusion.policy_version and"authorization".current_learner_course(school,target_course,result.learner_id)
   union all
   select result.id,result.evidence_id,result.learner_id,result.native_result from app.current_rubric_results current_result join app.rubric_result_revisions result on result.school_id=current_result.school_id and result.id=current_result.result_id join app.current_submissions pointer on pointer.school_id=result.school_id and pointer.submission_id=result.submission_id join app.rubric_evidence evidence on evidence.school_id=result.school_id and evidence.id=result.evidence_id and evidence.result_id=result.id and evidence.source_object_id=result.submission_id and evidence.learner_id=result.learner_id join app.school_custom_references reference on reference.school_id=result.school_id and reference.id=result.reference_id and reference.status='APPROVED'join app.school_custom_versions version on version.school_id=reference.school_id and version.id=reference.version_id and version.version=result.reference_version where result.school_id=school and result.assessment_id=assessment.id and result.reference_id=plan.reference_id and result.policy_version=inclusion.policy_version and"authorization".current_learner_course(school,target_course,result.learner_id)
  )result on true join app.people person on person.school_id=school and person.actor_id=result.learner_id
 )
 select coalesce(jsonb_agg(jsonb_build_object('id',plan.id,'referenceId',plan.reference_id,'referenceTitle',reference.title,'referenceDescription',reference.description,'periodRevision',plan.period_revision,'sourceStatus',case when period->>'recordState'='CANCELLED'or plan.period_revision<>(period->>'revision')::integer then'REQUIRES_REVIEW'else'CURRENT'end,'reason',plan.reason,
 'taughtCount',(select count(*)from app.objective_taught_records taught where taught.school_id=school and taught.plan_id=plan.id),'assessmentCount',(select count(*)from app.objective_plan_assessments inclusion where inclusion.school_id=school and inclusion.plan_id=plan.id),'evidenceLearnerCount',(select count(distinct source.learner_id)from sources source where source.plan_id=plan.id),'evidenceCount',(select count(*)from sources source where source.plan_id=plan.id),
 'taught',(select coalesce(jsonb_agg(jsonb_build_object('id',record.id,'lessonTitle',record.title,'taughtOn',record.taught_on,'note',record.note)order by record.id),'[]'::jsonb)from(select taught.id,lesson.title,taught.taught_on,taught.note from app.objective_taught_records taught join app.lessons lesson on lesson.school_id=taught.school_id and lesson.id=taught.lesson_id where taught.school_id=school and taught.plan_id=plan.id order by taught.id limit 10)record),
 'assessments',(select coalesce(jsonb_agg(jsonb_build_object('id',record.id,'title',record.title,'policyVersion',record.policy_version)order by record.id),'[]'::jsonb)from(select assessment.id,assessment.title,inclusion.policy_version from app.objective_plan_assessments inclusion join app.assessments assessment on assessment.school_id=inclusion.school_id and assessment.id=inclusion.assessment_id where inclusion.school_id=school and inclusion.plan_id=plan.id order by assessment.id limit 10)record),
 'evidence',(select coalesce(jsonb_agg(jsonb_build_object('id',record.evidence_id,'resultId',record.id,'learnerName',record.display_name,'nativeResult',record.native_result)order by record.id),'[]'::jsonb)from(select source.*from sources source where source.plan_id=plan.id order by source.id limit 10)record))order by plan.id),'[]'::jsonb),case when(select count(*)from plans)>page_limit then(select id from visible order by id desc limit 1)end into items,next_cursor from visible plan join app.school_custom_references reference on reference.school_id=plan.school_id and reference.id=plan.reference_id;
 context:=context||jsonb_build_object('planStatus',status,'plannedTotal',case when planned_count=0 then null else planned_count end,'learnerTotal',learner_count,'items',items,'nextCursor',next_cursor,'limitation','DECLARED_PLAN_NOT_OFFICIAL_CURRICULUM_COVERAGE');if octet_length(context::text)>500000 then raise exception 'Choose a smaller objective coverage page'using errcode='22023';end if;return context;
end$$;
revoke execute on function internal.objective_plan_assessment_frozen(),internal.require_objective_plan_course(uuid,boolean),internal.objective_plan_period(uuid,uuid),internal.record_objective_plan(text,uuid,jsonb,text,text,text),internal.read_period_objective_coverage(uuid,uuid,integer,uuid)from public,anon,authenticated,service_role,cuevo_api,cuevo_worker;
grant execute on function internal.record_objective_plan(text,uuid,jsonb,text,text,text),internal.read_period_objective_coverage(uuid,uuid,integer,uuid)to cuevo_api;
commit;
