-- Ignored mention/source notification authoring; root promotes/applies after review.
begin;
create table app.community_post_mentions(school_id uuid not null,id uuid not null default gen_random_uuid(),post_id uuid not null,recipient_id uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,post_id,recipient_id),foreign key(school_id,post_id)references app.community_posts(school_id,id),foreign key(school_id,recipient_id)references app.memberships(school_id,actor_id));
create table app.community_mention_reads(school_id uuid not null,mention_id uuid not null,actor_id uuid not null,read_at timestamptz not null default clock_timestamp(),primary key(school_id,mention_id,actor_id),foreign key(school_id,mention_id)references app.community_post_mentions(school_id,id),foreign key(school_id,actor_id)references app.memberships(school_id,actor_id));
create index community_mentions_recipient_page on app.community_post_mentions(school_id,recipient_id,id);
create function internal.validate_community_mentions(target_room uuid,mentions jsonb)returns void language plpgsql security definer set search_path=''as $$declare school uuid:="authorization".school_id();recipient uuid;begin
 if mentions is null or jsonb_typeof(mentions)<>'array'or jsonb_array_length(mentions)>5 or exists(select 1 from jsonb_array_elements(mentions)entry where jsonb_typeof(entry)<>'string')or jsonb_array_length(mentions)<>(select count(distinct value)from jsonb_array_elements_text(mentions)value)then raise exception 'Bounded unique current member mentions required'using errcode='22023';end if;
 for recipient in select value::uuid from jsonb_array_elements_text(mentions)value order by value loop
  if recipient="authorization".actor_id()or"authorization".community_member(school,recipient)is null or "authorization".community_member(school,recipient)not in('teacher','student')or not"authorization".community_room(school,target_room,recipient,false)then raise exception 'Current room mention recipient required'using errcode='42501';end if;
  perform 1 from app.memberships m where m.school_id=school and m.actor_id=recipient for share;
  perform 1 from app.community_members m where m.school_id=school and m.room_id=target_room and m.actor_id=recipient for share;perform 1 from app.enrollments e join app.community_rooms r on r.school_id=e.school_id and r.class_id=e.class_id where r.school_id=school and r.id=target_room and e.student_actor_id=recipient for share of e;perform 1 from app.teacher_assignments t join app.community_rooms r on r.school_id=t.school_id and r.class_id=t.class_id where r.school_id=school and r.id=target_room and t.teacher_actor_id=recipient order by t.subject_id for share of t;
  if "authorization".community_member(school,recipient)is null or "authorization".community_member(school,recipient)not in('teacher','student')or not"authorization".community_room(school,target_room,recipient,false)then raise exception 'Current mention recipient changed'using errcode='42501';end if;
 end loop;
end$$;
create function internal.read_community_post_source(target_post uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();post app.community_posts;source jsonb;begin
 select p.*into post from app.community_posts p where p.school_id=school and p.id=target_post;if not found or not internal.community_room_readable(school,post.room_id,actor)or internal.community_post_hidden(school,post.id)then raise exception 'Current visible post source denied'using errcode='42501';end if;
 select jsonb_build_object('id',post.id,'roomId',post.room_id,'actorId',post.actor_id,'authorName',person.display_name,'body',post.body,'replyToId',post.reply_to_id,'createdAt',post.created_at,'status','VISIBLE','reactions','[]'::jsonb)into source from app.people person where person.school_id=school and person.actor_id=post.actor_id;return source;
end$$;
create function internal.community_mention_allowed(target_mention uuid)returns boolean language sql stable security definer set search_path=''as $$select coalesce(exists(select 1 from app.community_post_mentions m join app.community_posts p on p.school_id=m.school_id and p.id=m.post_id where m.school_id="authorization".school_id()and m.id=target_mention and m.recipient_id="authorization".actor_id()and"authorization".community_member(m.school_id,m.recipient_id)in('teacher','student')and internal.community_group_current(m.school_id,p.room_id)->>'state'='ACTIVE'and internal.community_room_readable(m.school_id,p.room_id,m.recipient_id)and not internal.community_post_hidden(m.school_id,p.id)),false)$$;
create function internal.read_community_mention_source(target_mention uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare mention app.community_post_mentions;begin
 if not internal.community_mention_allowed(target_mention)then raise exception 'Current mention source denied'using errcode='42501';end if;select m.*into mention from app.community_post_mentions m where m.school_id="authorization".school_id()and m.id=target_mention;return internal.read_community_post_source(mention.post_id);
end$$;
create function internal.read_community_notifications(page_limit integer,page_cursor uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();items jsonb;begin
 if not"authorization".can_access_school(school)or"authorization".community_member(school,actor)is null or page_limit is null or page_limit not between 1 and 100 then raise exception 'Current bounded notifications required'using errcode='42501';end if;
 with candidates as materialized(
  select a.id,jsonb_build_object('id',a.id,'announcementId',a.id,'title',source->>'title','revision',(source->>'revision')::integer,'kind','ANNOUNCEMENT','createdAt',a.created_at,'readAt',source->'readAt')item from(with permitted as materialized(select a.id,a.created_at from app.community_announcements a where a.school_id=school and(page_cursor is null or a.id>page_cursor)and internal.community_announcement_current_allowed(school,a.id,actor))select*from permitted)a cross join lateral(select internal.read_community_announcement(a.id)source)current
  union all select m.id,jsonb_build_object('id',m.id,'postId',p.id,'roomId',p.room_id,'title',internal.community_group_current(school,p.room_id)->>'name','kind','MENTION','createdAt',m.created_at,'readAt',(select r.read_at from app.community_mention_reads r where r.school_id=m.school_id and r.mention_id=m.id and r.actor_id=actor))item from app.community_post_mentions m join app.community_posts p on p.school_id=m.school_id and p.id=m.post_id where m.school_id=school and m.recipient_id=actor and(page_cursor is null or m.id>page_cursor)and internal.community_mention_allowed(m.id)
 ),bounded as(select*from candidates order by id limit page_limit+1)
 select coalesce(jsonb_agg(item order by id),'[]'::jsonb)into items from bounded;if octet_length(items::text)>500000 then raise exception 'Notification page requires smaller view'using errcode='22023';end if;return jsonb_build_object('items',case when jsonb_array_length(items)>page_limit then items-page_limit else items end,'nextCursor',case when jsonb_array_length(items)>page_limit then items->(page_limit-1)->>'id'else null end);
end$$;
create function internal.community_mention_read(target uuid,command_key text,fingerprint text,request_id text)returns jsonb language plpgsql security definer set search_path=''as $$declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();reservation jsonb;receipt jsonb;inserted integer;begin
 perform internal.require_context();perform 1 from app.community_posts p join app.community_post_mentions m on m.school_id=p.school_id and m.post_id=p.id join app.community_rooms r on r.school_id=p.school_id and r.id=p.room_id where m.school_id=school and m.id=target for update of r;if not internal.community_mention_allowed(target)then raise exception 'Current mention read denied'using errcode='42501';end if;perform 1 from app.memberships member where member.school_id=school and member.actor_id=actor for share;
 perform 1 from app.community_members member join app.community_posts p on p.school_id=member.school_id and p.room_id=member.room_id join app.community_post_mentions mention on mention.school_id=p.school_id and mention.post_id=p.id where mention.school_id=school and mention.id=target and member.actor_id=actor for share of member;
 perform 1 from app.enrollments enrollment join app.community_rooms room on room.school_id=enrollment.school_id and room.class_id=enrollment.class_id join app.community_posts p on p.school_id=room.school_id and p.room_id=room.id join app.community_post_mentions mention on mention.school_id=p.school_id and mention.post_id=p.id where mention.school_id=school and mention.id=target and enrollment.student_actor_id=actor for share of enrollment;
 perform 1 from app.teacher_assignments assignment join app.community_rooms room on room.school_id=assignment.school_id and room.class_id=assignment.class_id join app.community_posts p on p.school_id=room.school_id and p.room_id=room.id join app.community_post_mentions mention on mention.school_id=p.school_id and mention.post_id=p.id where mention.school_id=school and mention.id=target and assignment.teacher_actor_id=actor order by assignment.subject_id for share of assignment;
 if not internal.community_mention_allowed(target)then raise exception 'Current mention recipient changed'using errcode='42501';end if;
 perform internal.read_community_mention_source(target);
 reservation:=internal.begin_command(command_key,'community.mention.read',fingerprint);if reservation->>'state'='COMPLETED'then return reservation->'response';elsif reservation->>'state'<>'NEW'then raise exception 'Mention read pending'using errcode='22023';end if;
 insert into app.community_mention_reads(school_id,mention_id,actor_id)values(school,target,actor)on conflict do nothing;get diagnostics inserted=row_count;receipt:=jsonb_build_object('id',target,'status','READ');if inserted>0 then perform internal.append_audit('community.mention.read','community_mention',target,request_id,'succeeded','{}');perform internal.enqueue_event('community.mention.read','community_mention',target,1,'{}','community-mention-read:'||target::text||':'||actor::text);end if;perform internal.finish_command(command_key,'community.mention.read',fingerprint,receipt);return receipt;
end$$;
do $$declare definition text;anchor text;begin
 definition:=pg_get_functiondef('internal.community_command(text,uuid,jsonb,text,text,text)'::regprocedure);anchor:='when''post.create''then array[''body'',''replyToId'']';if position(anchor in definition)=0 then raise exception 'Post mention payload entry changed'using errcode='22023';end if;definition:=replace(definition,anchor,'when''post.create''then array[''body'',''replyToId'',''mentionActorIds'']');
 anchor:='reservation:=internal.begin_command';if position(anchor in definition)=0 then raise exception 'Post mention replay boundary changed'using errcode='22023';end if;definition:=replace(definition,anchor,'if command_name=''post.create''then perform internal.validate_community_mentions(target,coalesce(payload->''mentionActorIds'',''[]''::jsonb));end if;'||chr(10)||anchor);
 anchor:='response:=jsonb_build_object(''id'',rid,''command'',command_name);';if position(anchor in definition)=0 then raise exception 'Post mention source receipt shape changed'using errcode='22023';end if;definition:=replace(definition,anchor,'if command_name=''post.create''then insert into app.community_post_mentions(school_id,post_id,recipient_id)select school,rid,value::uuid from jsonb_array_elements_text(coalesce(payload->''mentionActorIds'',''[]''::jsonb))value;end if;'||chr(10)||anchor);execute definition;
 definition:=pg_get_functiondef('internal.community_list(text,uuid,jsonb)'::regprocedure);anchor:=' if resource in(''announcements'',''notifications'')';if position(anchor in definition)=0 then raise exception 'Essential notification dispatcher changed'using errcode='22023';end if;execute replace(definition,anchor,' if resource=''notifications''then return internal.read_community_notifications((filters->>''limit'')::integer,(filters->>''cursor'')::uuid);end if;'||chr(10)||anchor);
end$$;
do $$declare tab text;begin foreach tab in array array['community_post_mentions','community_mention_reads']loop execute format('alter table app.%I enable row level security',tab);execute format('alter table app.%I force row level security',tab);execute format('revoke all on app.%I from public,anon,authenticated,service_role,cuevo_api,cuevo_worker',tab);execute format('create trigger immutable_history before update or delete on app.%I for each row execute function internal.academic_history_immutable()',tab);execute format('create trigger immutable_truncate before truncate on app.%I for each statement execute function internal.academic_history_immutable()',tab);end loop;end$$;
revoke execute on function internal.validate_community_mentions(uuid,jsonb),internal.read_community_post_source(uuid),internal.community_mention_allowed(uuid),internal.read_community_mention_source(uuid),internal.read_community_notifications(integer,uuid),internal.community_mention_read(uuid,text,text,text)from public,anon,authenticated,service_role,cuevo_api,cuevo_worker;
grant execute on function internal.read_community_mention_source(uuid),internal.community_mention_read(uuid,text,text,text)to cuevo_api;
do $$declare definition text;anchor text;begin definition:=pg_get_functiondef('internal.process_learner_event(uuid,uuid)'::regprocedure);anchor:='begin'||chr(10);if position(anchor in definition)=0 then raise exception 'Mention read event dispatcher changed'using errcode='22023';end if;definition:=replace(definition,anchor,'begin'||chr(10)||' if exists(select 1 from internal.outbox_events event where event.id=target_event and event.type=''community.mention.read'')then select*into e from internal.outbox_events where id=target_event for update;if e.state<>''PROCESSING''or e.lease_token is distinct from current_lease or e.lease_until<=clock_timestamp()or e.entity_type<>''community_mention''or e.version<>1 or not exists(select 1 from app.community_mention_reads r where r.school_id=e.school_id and r.mention_id=e.entity_id and r.actor_id=e.actor_id)then raise exception ''Mention source receipt invalid''using errcode=''22023'';end if;insert into internal.processed_events(event_id,school_id)values(e.id,e.school_id)on conflict(event_id)do nothing;if internal.complete_outbox(e.id,current_lease)is distinct from true then raise exception ''Mention source lease changed''using errcode=''22023'';end if;return jsonb_build_object(''status'',''ACKNOWLEDGED'');end if;'||chr(10));execute definition;end$$;
commit;







