-- Ignored controlled community maintenance authoring; root promotes/applies after review.
begin;
create table app.community_group_revisions(school_id uuid not null,id uuid not null default gen_random_uuid(),room_id uuid not null,revision integer not null check(revision>1),name text not null check(length(btrim(name))between 1 and 200),state text not null check(state in('ACTIVE','CLOSED')),reason text not null check(length(btrim(reason))between 1 and 1000),actor_id uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,room_id,revision),foreign key(school_id,room_id)references app.community_rooms(school_id,id),foreign key(school_id,actor_id)references app.memberships(school_id,actor_id));
create table app.community_report_reviews(school_id uuid not null,id uuid not null default gen_random_uuid(),report_id uuid not null,revision integer not null check(revision>0),outcome text not null check(outcome in('RESOLVED','REQUIRES_FOLLOW_UP','REOPENED')),reason text not null check(length(btrim(reason))between 1 and 1000),actor_id uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,report_id,revision),foreign key(school_id,report_id)references app.community_reports(school_id,id),foreign key(school_id,actor_id)references app.memberships(school_id,actor_id));
create table app.community_announcement_revisions(school_id uuid not null,id uuid not null default gen_random_uuid(),announcement_id uuid not null,revision integer not null check(revision>1),title text not null check(length(btrim(title))between 1 and 200),body text not null check(length(btrim(body))between 1 and 4000),parent_visible boolean not null,state text not null check(state in('PUBLISHED','WITHDRAWN')),reason text not null check(length(btrim(reason))between 1 and 1000),actor_id uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,announcement_id,revision),foreign key(school_id,announcement_id)references app.community_announcements(school_id,id),foreign key(school_id,actor_id)references app.memberships(school_id,actor_id));
create table app.community_announcement_revision_reads(school_id uuid not null,announcement_id uuid not null,revision integer not null check(revision>0),actor_id uuid not null,read_at timestamptz not null default clock_timestamp(),primary key(school_id,announcement_id,revision,actor_id),foreign key(school_id,announcement_id)references app.community_announcements(school_id,id),foreign key(school_id,actor_id)references app.memberships(school_id,actor_id));
create function internal.community_group_current(target_school uuid,target_room uuid)returns jsonb language sql stable security definer set search_path=''as $$select jsonb_build_object('name',coalesce(revision.name,room.name),'state',coalesce(revision.state,case when room.status='ACTIVE'then'ACTIVE'else'CLOSED'end),'revision',coalesce(revision.revision,1))from app.community_rooms room left join lateral(select r.name,r.state,r.revision from app.community_group_revisions r where r.school_id=room.school_id and r.room_id=room.id order by r.revision desc limit 1)revision on true where room.school_id=target_school and room.id=target_room$$;
create function internal.community_group_staff(target_school uuid,target_room uuid)returns boolean language sql stable security definer set search_path=''as $$select coalesce(exists(select 1 from app.community_rooms r where r.school_id=target_school and r.id=target_room and r.type='GROUP'and"authorization".community_class(target_school,r.class_id,"authorization".actor_id())and("authorization".current_role(target_school)='admin'or r.owner_id="authorization".actor_id()and"authorization".current_role(target_school)='teacher')),false)$$;
create function internal.community_room_readable(target_school uuid,target_room uuid,target_actor uuid)returns boolean language sql stable security definer set search_path=''as $$select coalesce(exists(select 1 from app.community_rooms r where r.school_id=target_school and r.id=target_room and"authorization".community_class(target_school,r.class_id,target_actor)and(r.type='CLASS'or"authorization".community_member(target_school,target_actor)='admin'or r.owner_id=target_actor and"authorization".community_member(target_school,target_actor)='teacher'or exists(select 1 from app.community_members m where m.school_id=r.school_id and m.room_id=r.id and m.actor_id=target_actor and m.status='active'))and("authorization".community_member(target_school,target_actor)in('admin','teacher')or"authorization".community_restriction(target_school,target_room,target_actor)<>'RESTRICTED')),false)$$;
create function internal.community_announcement_current(target_school uuid,target uuid)returns jsonb language sql stable security definer set search_path=''as $$select jsonb_build_object('id',a.id,'classId',a.class_id,'title',coalesce(r.title,a.title),'body',coalesce(r.body,a.body),'parentVisible',coalesce(r.parent_visible,a.parent_visible),'createdAt',a.created_at,'revision',coalesce(r.revision,1),'state',coalesce(r.state,'PUBLISHED'))from app.community_announcements a left join lateral(select r.title,r.body,r.parent_visible,r.state,r.revision from app.community_announcement_revisions r where r.school_id=a.school_id and r.announcement_id=a.id order by r.revision desc limit 1)r on true where a.school_id=target_school and a.id=target$$;
create function internal.community_announcement_current_allowed(target_school uuid,target uuid,target_actor uuid)returns boolean language plpgsql stable security definer set search_path=''as $$declare source jsonb;begin source:=internal.community_announcement_current(target_school,target);return coalesce(source is not null and source->>'state'='PUBLISHED'and"authorization".community_announcement(target_school,(source->>'classId')::uuid,(source->>'parentVisible')::boolean,target_actor),false);end$$;
create function internal.community_announcement_staff(target_school uuid,target uuid)returns boolean language sql stable security definer set search_path=''as $$select coalesce(exists(select 1 from app.community_announcements a where a.school_id=target_school and a.id=target and("authorization".community_member(target_school,"authorization".actor_id())='admin'or a.actor_id="authorization".actor_id()and"authorization".community_member(target_school,"authorization".actor_id())='teacher'and a.class_id is not null and"authorization".community_class(target_school,a.class_id,"authorization".actor_id()))),false)$$;
create function internal.community_maintenance_command(command_name text,target uuid,payload jsonb,command_key text,fingerprint text,request_id text)returns jsonb language plpgsql security definer set search_path=''as $$declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();room app.community_rooms;report app.community_reports;post app.community_posts;announcement app.community_announcements;current_source jsonb;version integer;rid uuid;reservation jsonb;receipt jsonb;begin
 perform internal.require_context();if not"authorization".has_entitlement(school,'community')or"authorization".current_role(school)is null or"authorization".current_role(school)not in('admin','teacher')then raise exception 'Community maintenance staff required'using errcode='42501';end if;
 if command_name='group'then select r.*into room from app.community_rooms r where r.school_id=school and r.id=target for update;if not found or not internal.community_group_staff(school,room.id)then raise exception 'Current group owner required'using errcode='42501';end if;current_source:=internal.community_group_current(school,target);version:=(current_source->>'revision')::integer;
 elsif command_name='report'then select r.*into report from app.community_reports r where r.school_id=school and r.id=target;select p.*into post from app.community_posts p where p.school_id=school and p.id=report.post_id;select r.*into room from app.community_rooms r where r.school_id=school and r.id=post.room_id for update;if report.id is null or not internal.community_room_readable(school,room.id,actor)or not("authorization".community_member(school,actor)='admin'or room.owner_id=actor and"authorization".community_member(school,actor)='teacher')then raise exception 'Exact report staff review required'using errcode='42501';end if;select coalesce(max(r.revision),0)into version from app.community_report_reviews r where r.school_id=school and r.report_id=target;
 elsif command_name in('announcement','withdraw')then select a.*into announcement from app.community_announcements a where a.school_id=school and a.id=target for update;if not found or not internal.community_announcement_staff(school,target)then raise exception 'Current announcement author required'using errcode='42501';end if;current_source:=internal.community_announcement_current(school,target);version:=(current_source->>'revision')::integer;
 else raise exception 'Community maintenance command invalid'using errcode='22023';end if;
 if payload is null or jsonb_typeof(payload)<>'object'or jsonb_typeof(payload->'expectedRevision')is distinct from'number'or(payload->>'expectedRevision')!~'^[0-9]+$'or jsonb_typeof(payload->'reason')is distinct from'string'or length(btrim(payload->>'reason'))not between 1 and 1000 then raise exception 'Current source version and reason required'using errcode='22023';end if;
 reservation:=internal.begin_command(command_key,'community.maintenance.'||command_name,fingerprint);if reservation->>'state'='COMPLETED'then return reservation->'response';elsif reservation->>'state'<>'NEW'then raise exception 'Maintenance command pending'using errcode='22023';end if;
 if version is distinct from(payload->>'expectedRevision')::integer then raise exception 'Community current revision changed'using errcode='22023';end if;
 if command_name='group'then
  if payload-array['name','state','expectedRevision','reason','confirmChange']<>'{}'::jsonb or payload->'confirmChange'is distinct from'true'::jsonb or jsonb_typeof(payload->'name')is distinct from'string'or length(btrim(payload->>'name'))not between 1 and 200 or jsonb_typeof(payload->'state')is distinct from'string'or payload->>'state'not in('ACTIVE','CLOSED')then raise exception 'Group lifecycle review required'using errcode='22023';end if;
  insert into app.community_group_revisions(school_id,room_id,revision,name,state,reason,actor_id)values(school,target,version+1,payload->>'name',payload->>'state',payload->>'reason',actor)returning id into rid;receipt:=jsonb_build_object('id',target,'revision',version+1,'status',payload->>'state');
 elsif command_name='report'then
  if payload-array['outcome','expectedRevision','reason','confirmReview']<>'{}'::jsonb or payload->'confirmReview'is distinct from'true'::jsonb or jsonb_typeof(payload->'outcome')is distinct from'string'or payload->>'outcome'not in('RESOLVED','REQUIRES_FOLLOW_UP','REOPENED')then raise exception 'Explicit report review required'using errcode='22023';end if;insert into app.community_report_reviews(school_id,report_id,revision,outcome,reason,actor_id)values(school,target,version+1,payload->>'outcome',payload->>'reason',actor)returning id into rid;receipt:=jsonb_build_object('id',target,'revision',version+1,'status',payload->>'outcome');
 else
  if command_name='withdraw'then if payload-array['expectedRevision','reason','confirmWithdrawal']<>'{}'::jsonb or payload->'confirmWithdrawal'is distinct from'true'::jsonb then raise exception 'Explicit announcement withdrawal required'using errcode='22023';end if;
  else if payload-array['title','body','parentVisible','expectedRevision','reason','confirmPublication']<>'{}'::jsonb or payload->'confirmPublication'is distinct from'true'::jsonb or jsonb_typeof(payload->'title')is distinct from'string'or length(btrim(payload->>'title'))not between 1 and 200 or jsonb_typeof(payload->'body')is distinct from'string'or length(btrim(payload->>'body'))not between 1 and 4000 or jsonb_typeof(payload->'parentVisible')is distinct from'boolean'then raise exception 'Reviewed announcement fields required'using errcode='22023';end if;end if;
  insert into app.community_announcement_revisions(school_id,announcement_id,revision,title,body,parent_visible,state,reason,actor_id)values(school,target,version+1,case when command_name='withdraw'then current_source->>'title'else payload->>'title'end,case when command_name='withdraw'then current_source->>'body'else payload->>'body'end,case when command_name='withdraw'then(current_source->>'parentVisible')::boolean else(payload->>'parentVisible')::boolean end,case when command_name='withdraw'then'WITHDRAWN'else'PUBLISHED'end,payload->>'reason',actor)returning id into rid;receipt:=jsonb_build_object('id',target,'revision',version+1,'status',case when command_name='withdraw'then'WITHDRAWN'else'PUBLISHED'end);
 end if;
 perform internal.append_audit('community.maintenance.'||command_name,'community_maintenance',rid,request_id,'succeeded',jsonb_build_object('sourceId',target,'revision',version+1,'kind',command_name));perform internal.enqueue_event('community.maintenance.changed','community_maintenance',rid,version+1,jsonb_build_object('kind',command_name,'sourceId',target),'community-maintenance:'||rid::text);perform internal.finish_command(command_key,'community.maintenance.'||command_name,fingerprint,receipt);return receipt;
end$$;
create function internal.community_maintenance_history(kind text,target uuid,page_limit integer,page_cursor uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();items jsonb;room uuid;begin
 if page_limit is null or page_limit not between 1 and 100 then raise exception 'Bounded community history required'using errcode='22023';end if;
 if kind='group'then if not internal.community_group_staff(school,target)then raise exception 'Group history staff required'using errcode='42501';end if;select coalesce(jsonb_agg(jsonb_build_object('id',id,'revision',revision,'name',name,'state',state,'reason',reason,'createdAt',created_at)order by id),'[]'::jsonb)into items from(select*from app.community_group_revisions where school_id=school and room_id=target and(page_cursor is null or id>page_cursor)order by id limit page_limit+1)r;
 elsif kind='announcement'then if not internal.community_announcement_staff(school,target)then raise exception 'Announcement history author required'using errcode='42501';end if;select coalesce(jsonb_agg(jsonb_build_object('id',id,'revision',revision,'title',title,'body',body,'parentVisible',parent_visible,'state',state,'reason',reason,'createdAt',created_at)order by id),'[]'::jsonb)into items from(select*from app.community_announcement_revisions where school_id=school and announcement_id=target and(page_cursor is null or id>page_cursor)order by id limit page_limit+1)r;
 elsif kind='report'then select p.room_id into room from app.community_reports r join app.community_posts p on p.school_id=r.school_id and p.id=r.post_id where r.school_id=school and r.id=target;if not"authorization".community_staff(school,room,"authorization".actor_id())then raise exception 'Report history staff required'using errcode='42501';end if;select coalesce(jsonb_agg(jsonb_build_object('id',id,'revision',revision,'outcome',outcome,'reason',reason,'createdAt',created_at)order by id),'[]'::jsonb)into items from(select*from app.community_report_reviews where school_id=school and report_id=target and(page_cursor is null or id>page_cursor)order by id limit page_limit+1)r;
 else raise exception 'Community history type invalid'using errcode='22023';end if;if octet_length(items::text)>500000 then raise exception 'History requires a smaller page'using errcode='22023';end if;return jsonb_build_object('items',case when jsonb_array_length(items)>page_limit then items-page_limit else items end,'nextCursor',case when jsonb_array_length(items)>page_limit then items->(page_limit-1)->>'id'else null end);
end$$;
create or replace function internal.read_community_announcement(target uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();source jsonb;read_at timestamptz;begin
 if not internal.community_announcement_current_allowed(school,target,actor)then raise exception 'Current announcement source denied'using errcode='42501';end if;source:=internal.community_announcement_current(school,target);
 select r.read_at into read_at from app.community_announcement_revision_reads r where r.school_id=school and r.announcement_id=target and r.revision=(source->>'revision')::integer and r.actor_id=actor;if read_at is null and(source->>'revision')::integer=1 then select r.read_at into read_at from app.community_notification_reads r where r.school_id=school and r.announcement_id=target and r.actor_id=actor;end if;return source-'state'||jsonb_build_object('readAt',read_at,'canManage',internal.community_announcement_staff(school,target));
end$$;
create function internal.read_current_community_announcements(resource text,page_limit integer,page_cursor uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();items jsonb;begin
 if not"authorization".can_access_school(school)or"authorization".community_member(school,actor)is null or resource is null or resource not in('announcements','notifications')or page_limit is null or page_limit not between 1 and 100 then raise exception 'Current announcement page denied'using errcode='42501';end if;
 select coalesce(jsonb_agg(case when resource='announcements'then internal.read_community_announcement(a.id)else jsonb_build_object('id',a.id,'announcementId',a.id,'title',internal.community_announcement_current(school,a.id)->>'title','revision',(internal.community_announcement_current(school,a.id)->>'revision')::integer,'kind','ANNOUNCEMENT','createdAt',a.created_at,'readAt',internal.read_community_announcement(a.id)->'readAt')end order by a.id),'[]'::jsonb)into items from(select a.id,a.created_at from app.community_announcements a where a.school_id=school and(page_cursor is null or a.id>page_cursor)and internal.community_announcement_current_allowed(school,a.id,actor)order by a.id limit page_limit+1)a;
 if octet_length(items::text)>500000 then raise exception 'Announcement page requires a smaller view'using errcode='22023';end if;return jsonb_build_object('items',case when jsonb_array_length(items)>page_limit then items-page_limit else items end,'nextCursor',case when jsonb_array_length(items)>page_limit then items->(page_limit-1)->>'id'else null end);
end$$;
create function internal.community_announcement_revision_read(target uuid,payload jsonb,command_key text,fingerprint text,request_id text)returns jsonb language plpgsql security definer set search_path=''as $$declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();source jsonb;version integer;reservation jsonb;result jsonb;inserted integer;begin
 perform internal.require_context();perform 1 from app.community_announcements a where a.school_id=school and a.id=target for update;if not found or not internal.community_announcement_current_allowed(school,target,actor)then raise exception 'Current exact announcement read denied'using errcode='42501';end if;source:=internal.community_announcement_current(school,target);version:=(source->>'revision')::integer;
 if payload is null or jsonb_typeof(payload)<>'object'or payload-array['expectedRevision']<>'{}'::jsonb or(payload?'expectedRevision'and(jsonb_typeof(payload->'expectedRevision')is distinct from'number'or(payload->>'expectedRevision')!~'^[1-9][0-9]*$')) or(payload->>'expectedRevision'is null and version<>1)or(payload->>'expectedRevision'is not null and(payload->>'expectedRevision')::integer<>version)then raise exception 'Review the current exact announcement revision'using errcode='22023';end if;
 reservation:=internal.begin_command(command_key,'community.notification.read',fingerprint);if reservation->>'state'='COMPLETED'then return reservation->'response';elsif reservation->>'state'<>'NEW'then raise exception 'Read command pending'using errcode='22023';end if;
 insert into app.community_announcement_revision_reads(school_id,announcement_id,revision,actor_id)values(school,target,version,actor)on conflict do nothing;get diagnostics inserted=row_count;result:=jsonb_build_object('id',target,'status','READ','revision',version);
 if inserted>0 then perform internal.append_audit('community.notification.read','community',target,request_id,'succeeded',jsonb_build_object('revision',version));perform internal.enqueue_event('community.changed','community',target,1,jsonb_build_object('roomId',null),'community-read:'||target::text||':'||version::text||':'||actor::text);end if;perform internal.finish_command(command_key,'community.notification.read',fingerprint,result);return result;
end$$;
do $$declare definition text;anchor text;begin
 definition:=pg_get_functiondef('internal.community_command(text,uuid,jsonb,text,text,text)'::regprocedure);anchor:='begin'||chr(10);if position(anchor in definition)=0 then raise exception 'Community command dispatch shape changed'using errcode='22023';end if;definition:=replace(definition,anchor,'begin'||chr(10)||' if command_name=''notification.read''then return internal.community_announcement_revision_read(target,payload,command_key,fingerprint,request_id);end if;'||chr(10));execute definition;
 definition:=pg_get_functiondef('internal.community_list(text,uuid,jsonb)'::regprocedure);anchor:='begin'||chr(10);if position(anchor in definition)=0 then raise exception 'Community list current projection changed'using errcode='22023';end if;definition:=replace(definition,anchor,'begin'||chr(10)||' if resource in(''announcements'',''notifications'')then return internal.read_current_community_announcements(resource,(filters->>''limit'')::integer,(filters->>''cursor'')::uuid);end if;'||chr(10));execute definition;
end$$;
create function internal.community_room_staff_read(target_school uuid,target_room uuid,target_actor uuid)returns boolean language sql stable security definer set search_path=''as $$select coalesce(exists(select 1 from app.community_rooms r where r.school_id=target_school and r.id=target_room and"authorization".community_class(target_school,r.class_id,target_actor)and("authorization".community_member(target_school,target_actor)='admin'or r.owner_id=target_actor and"authorization".community_member(target_school,target_actor)='teacher')),false)$$;
create function internal.community_maintenance_replace(definition text,anchor text,replacement text)returns text language plpgsql immutable set search_path=''as $$begin if position(anchor in definition)=0 then raise exception 'Community lifecycle source anchor changed'using errcode='22023';end if;return replace(definition,anchor,replacement);end$$;
-- Current group state gates live interaction/private Realtime; historical reads have a distinct same-member policy.
do $$declare definition text;anchor text;begin
 definition:=pg_get_functiondef('"authorization".community_room(uuid,uuid,uuid,boolean)'::regprocedure);anchor:='r.status=''ACTIVE''and';if position(anchor in definition)=0 then raise exception 'Room current status guard changed'using errcode='22023';end if;execute replace(definition,anchor,anchor||' coalesce(internal.community_group_current(target_school,target_room)->>''state'',''CLOSED'')=''ACTIVE'' and ');
 definition:=pg_get_functiondef('internal.community_list(text,uuid,jsonb)'::regprocedure);anchor:='if resource in(''roster'',''posts'',''reports'')and not"authorization".community_room(school,target_room,actor,false)';if position(anchor in definition)=0 then raise exception 'Room historical read entry changed'using errcode='22023';end if;definition:=replace(definition,anchor,'if resource in(''roster'',''posts'',''reports'') and not internal.community_room_readable(school,target_room,actor)');
 anchor:='"authorization".community_room(r.school_id,r.id,$2)'; -- keep dynamic role-specific source patterns explicit below
 definition:=internal.community_maintenance_replace(definition,'if resource=''reports''and not"authorization".community_staff(school,target_room,actor)','if resource=''reports'' and not internal.community_room_staff_read(school,target_room,actor)');
 definition:=internal.community_maintenance_replace(definition,'"authorization".community_room(r.school_id,r.id,$2,false)','internal.community_room_readable(r.school_id,r.id,$2)');
 definition:=internal.community_maintenance_replace(definition,'''name'''',r.name','''name'''',internal.community_group_current(r.school_id,r.id)->>''''name''''');
 definition:=internal.community_maintenance_replace(definition,'''status'''',r.status','''status'''',internal.community_group_current(r.school_id,r.id)->>''''state'''',''''revision'''',(internal.community_group_current(r.school_id,r.id)->>''''revision'''')::integer');
 definition:=internal.community_maintenance_replace(definition,'''canModerate'''',"authorization".community_staff(r.school_id,r.id,$2)','''canModerate'''',case when r.type=''''GROUP''''then internal.community_group_staff(r.school_id,r.id)else"authorization".community_staff(r.school_id,r.id,$2)end');
 definition:=internal.community_maintenance_replace(definition,'"authorization".community_room(m.school_id,$3,m.actor_id,false)','internal.community_room_readable(m.school_id,$3,m.actor_id)');
 definition:=internal.community_maintenance_replace(definition,'''reason'''',r.reason,''''createdAt'''',r.created_at','''reason'''',r.reason,''''createdAt'''',r.created_at,''''reviewRevision'''',coalesce((select review.revision from app.community_report_reviews review where review.school_id=r.school_id and review.report_id=r.id order by review.revision desc limit 1),0),''''reviewState'''',coalesce((select review.outcome from app.community_report_reviews review where review.school_id=r.school_id and review.report_id=r.id order by review.revision desc limit 1),''''AWAITING_REVIEW'''')');
 execute definition;
end$$;
do $$declare tab text;begin foreach tab in array array['community_group_revisions','community_report_reviews','community_announcement_revisions','community_announcement_revision_reads']loop execute format('alter table app.%I enable row level security',tab);execute format('alter table app.%I force row level security',tab);execute format('revoke all on app.%I from public,anon,authenticated,service_role,cuevo_api,cuevo_worker',tab);execute format('create trigger immutable_history before update or delete on app.%I for each row execute function internal.academic_history_immutable()',tab);execute format('create trigger immutable_truncate before truncate on app.%I for each statement execute function internal.academic_history_immutable()',tab);end loop;end$$;
revoke execute on function internal.community_maintenance_replace(text,text,text),internal.community_room_staff_read(uuid,uuid,uuid),internal.community_group_current(uuid,uuid),internal.community_group_staff(uuid,uuid),internal.community_room_readable(uuid,uuid,uuid),internal.community_announcement_current(uuid,uuid),internal.community_announcement_current_allowed(uuid,uuid,uuid),internal.community_announcement_staff(uuid,uuid),internal.community_maintenance_command(text,uuid,jsonb,text,text,text),internal.community_maintenance_history(text,uuid,integer,uuid),internal.read_current_community_announcements(text,integer,uuid),internal.community_announcement_revision_read(uuid,jsonb,text,text,text)from public,anon,authenticated,service_role,cuevo_api,cuevo_worker;
grant execute on function internal.community_maintenance_command(text,uuid,jsonb,text,text,text),internal.community_maintenance_history(text,uuid,integer,uuid)to cuevo_api;
do $$declare definition text;anchor text;begin definition:=pg_get_functiondef('internal.process_learner_event(uuid,uuid)'::regprocedure);anchor:='begin'||chr(10);if position(anchor in definition)=0 then raise exception 'Community maintenance dispatcher shape changed'using errcode='22023';end if;definition:=replace(definition,anchor,'begin'||chr(10)||' if exists(select 1 from internal.outbox_events event where event.id=target_event and event.type=''community.maintenance.changed'')then select*into e from internal.outbox_events where id=target_event for update;if e.state<>''PROCESSING''or e.lease_token is distinct from current_lease or e.lease_until<=clock_timestamp()or e.entity_type<>''community_maintenance''or not exists(select 1 from internal.audit_events audit where audit.school_id=e.school_id and audit.actor_id=e.actor_id and audit.entity_id=e.entity_id and audit.entity_type=''community_maintenance''and(audit.metadata->>''revision'')::integer=e.version and audit.action=(''community.maintenance.''||(e.metadata->>''kind''))and audit.metadata->''sourceId''=e.metadata->''sourceId'')then raise exception ''Community maintenance source invalid''using errcode=''22023'';end if;insert into internal.processed_events(event_id,school_id)values(e.id,e.school_id)on conflict(event_id)do nothing;if internal.complete_outbox(e.id,current_lease)is distinct from true then raise exception ''Community maintenance lease changed''using errcode=''22023'';end if;return jsonb_build_object(''status'',''ACKNOWLEDGED'');end if;'||chr(10));execute definition;end$$;
commit;







