begin;
create table app.curriculum_lifecycle_revisions(
 school_id uuid not null,id uuid not null default gen_random_uuid(),version_id uuid not null,revision integer not null check(revision>0),state text not null check(state in('DRAFT','APPROVED','ACTIVE','SUPERSEDED','RETIRED')),replacement_version_id uuid,reason text not null check(length(btrim(reason))between 1 and 2000),artifact_digest text,created_by uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,version_id,revision),foreign key(school_id,version_id)references app.curriculum_versions(school_id,id),foreign key(school_id,replacement_version_id)references app.curriculum_versions(school_id,id),foreign key(school_id,created_by)references app.memberships(school_id,actor_id),check(artifact_digest is null or artifact_digest~'^[a-f0-9]{64}$')
);
alter table app.curriculum_lifecycle_revisions enable row level security;alter table app.curriculum_lifecycle_revisions force row level security;revoke all on app.curriculum_lifecycle_revisions from public,anon,authenticated,service_role,cuevo_api,cuevo_worker;
create trigger lifecycle_immutable before update or delete on app.curriculum_lifecycle_revisions for each row execute function internal.academic_history_immutable();create trigger lifecycle_no_truncate before truncate on app.curriculum_lifecycle_revisions for each statement execute function internal.academic_history_immutable();
insert into app.curriculum_lifecycle_revisions(school_id,version_id,revision,state,reason,created_by)select school_id,id,1,case when synthetic and kind='school_custom'and source_status='VERIFIED'and rights_status='PERMITTED'then'ACTIVE'else'DRAFT'end,'Existing source configuration retained for compatibility; no official or customer-ready acceptance.',created_by from app.curriculum_versions;
create function internal.current_curriculum_lifecycle(target_school uuid,target_version uuid)returns text language sql stable security definer set search_path=''as $$select coalesce((select state from app.curriculum_lifecycle_revisions where school_id=target_school and version_id=target_version order by revision desc limit 1),'DRAFT')$$;
create function internal.record_initial_curriculum_lifecycle()returns trigger language plpgsql security definer set search_path=''as $$begin insert into app.curriculum_lifecycle_revisions(school_id,version_id,revision,state,reason,created_by)values(new.school_id,new.id,1,'DRAFT','New source awaits explicit technical review and activation.',new.created_by);return new;end$$;
create trigger lifecycle_initial after insert on app.curriculum_versions for each row execute function internal.record_initial_curriculum_lifecycle();
create function internal.programme_configuration_allowed(target_school uuid,target_course uuid)returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from app.courses where school_id=target_school and id=target_course)and(not exists(select 1 from app.programme_course_contexts where school_id=target_school and course_id=target_course)or exists(select 1 from app.programme_course_contexts pinned join app.programme_instances programme on programme.school_id=pinned.school_id and programme.id=pinned.programme_id where pinned.school_id=target_school and pinned.course_id=target_course and internal.current_curriculum_lifecycle(target_school,programme.pack_version_id)='ACTIVE'))$$;
create function internal.programme_academic_write_allowed(target_school uuid,target_course uuid)returns boolean language sql volatile security definer set search_path=''as $$select exists(select 1 from app.courses where school_id=target_school and id=target_course)and(not exists(select 1 from app.programme_course_contexts where school_id=target_school and course_id=target_course)or exists(select 1 from app.programme_course_contexts pinned join app.programme_instances programme on programme.school_id=pinned.school_id and programme.id=pinned.programme_id where pinned.school_id=target_school and pinned.course_id=target_course and internal.current_curriculum_lifecycle(target_school,programme.pack_version_id)in('ACTIVE','SUPERSEDED')) )$$;
create or replace function internal.lock_academic_course(target_school uuid,target_course uuid)returns void language plpgsql security definer set search_path=''as $$begin
 if target_course is null or not"authorization".can_read_course(target_school,target_course)then raise exception 'Current academic course denied'using errcode='42501';end if;
 perform 1 from app.courses where school_id=target_school and id=target_course for update;
 if not internal.programme_academic_write_allowed(target_school,target_course)then raise exception 'Retired curriculum source is read only'using errcode='22023';end if;
end$$;
create function internal.curriculum_configuration_guard()returns trigger language plpgsql security definer set search_path=''as $$declare pack uuid;begin
 if tg_table_name='programme_instances'then pack:=new.pack_version_id;
 elsif tg_table_name in('programme_course_contexts','programme_learners')then select pack_version_id into pack from app.programme_instances where school_id=new.school_id and id=new.programme_id;
 elsif tg_table_name='course_objective_approvals'then select programme.pack_version_id into pack from app.programme_course_contexts pinned join app.programme_instances programme on programme.school_id=pinned.school_id and programme.id=pinned.programme_id where pinned.school_id=new.school_id and pinned.course_id=new.course_id;
  if not found then if not exists(select 1 from app.courses course where course.school_id=new.school_id and course.id=new.course_id)then raise exception 'Current source course required'using errcode='22023';end if;return new;end if;
 else if not internal.programme_configuration_allowed(new.school_id,new.course_id)then raise exception 'Active curriculum source required for new configuration'using errcode='22023';end if;return new;end if;
 if tg_table_name='programme_learners'and new.status='revoked'then return new;end if;
 if pack is null or internal.current_curriculum_lifecycle(new.school_id,pack)<>'ACTIVE'then raise exception 'Active curriculum source required for new configuration'using errcode='22023';end if;return new;
end$$;
create trigger lifecycle_programme_configuration before insert on app.programme_instances for each row execute function internal.curriculum_configuration_guard();
create trigger lifecycle_course_configuration before insert on app.programme_course_contexts for each row execute function internal.curriculum_configuration_guard();
create trigger lifecycle_learner_configuration before insert or update on app.programme_learners for each row execute function internal.curriculum_configuration_guard();
create trigger lifecycle_objective_configuration before insert on app.course_objective_approvals for each row execute function internal.curriculum_configuration_guard();
create trigger lifecycle_plan_configuration before insert on app.course_objective_plans for each row execute function internal.curriculum_configuration_guard();
create function internal.curriculum_reference_draft_guard()returns trigger language plpgsql security definer set search_path=''as $$begin
 if internal.current_curriculum_lifecycle(new.school_id,new.pack_version_id)<>'DRAFT'then raise exception 'Reviewed curriculum hierarchy is immutable; create a new source version'using errcode='22023';end if;return new;
end$$;
create trigger lifecycle_reference_draft before insert on app.curriculum_references for each row execute function internal.curriculum_reference_draft_guard();
create function internal.curriculum_academic_write_guard()returns trigger language plpgsql security definer set search_path=''as $$declare course uuid;begin
 if tg_table_name='assessments'then course:=new.course_id;
 elsif tg_table_name in('submissions','submission_drafts')then select course_id into course from app.assessments where school_id=new.school_id and id=new.assessment_id;
 elsif tg_table_name='activity_completions'then select unit.course_id into course from app.activities activity join app.lessons lesson on lesson.school_id=activity.school_id and lesson.id=activity.lesson_id join app.units unit on unit.school_id=lesson.school_id and unit.id=lesson.unit_id where activity.school_id=new.school_id and activity.id=new.activity_id;
 elsif tg_table_name='interventions'then select (internal.native_academic_source(new.school_id,new.baseline_result_id)->>'courseId')::uuid into course;
 elsif tg_table_name in('objective_taught_records','objective_plan_assessments')then select plan.course_id into course from app.course_objective_plans plan where plan.school_id=new.school_id and plan.id=new.plan_id;
 else select assessment.course_id into course from app.submissions submission join app.assessments assessment on assessment.school_id=submission.school_id and assessment.id=submission.assessment_id where submission.school_id=new.school_id and submission.id=new.submission_id;end if;
 if course is null then raise exception 'Exact academic source course required'using errcode='22023';end if;
 if tg_op='INSERT'then perform internal.lock_academic_course(new.school_id,course);end if;
 if not internal.programme_academic_write_allowed(new.school_id,course)then raise exception 'Retired curriculum source is read only'using errcode='22023';end if;return new;
end$$;
create trigger lifecycle_assessment_write before insert or update on app.assessments for each row execute function internal.curriculum_academic_write_guard();
create trigger lifecycle_submission_write before insert on app.submissions for each row execute function internal.curriculum_academic_write_guard();
create trigger lifecycle_numeric_mark_write before insert on app.marking_revisions for each row execute function internal.curriculum_academic_write_guard();
create trigger lifecycle_rubric_mark_write before insert on app.rubric_marking_revisions for each row execute function internal.curriculum_academic_write_guard();
create trigger lifecycle_activity_write before insert on app.activity_completions for each row execute function internal.curriculum_academic_write_guard();
create trigger lifecycle_draft_write before insert or update on app.submission_drafts for each row execute function internal.curriculum_academic_write_guard();
create trigger lifecycle_support_write before insert on app.interventions for each row execute function internal.curriculum_academic_write_guard();
create trigger lifecycle_taught_write before insert on app.objective_taught_records for each row execute function internal.curriculum_academic_write_guard();
create trigger lifecycle_plan_task_write before insert on app.objective_plan_assessments for each row execute function internal.curriculum_academic_write_guard();
create function internal.require_curriculum_academic_write(target_course uuid)returns void language plpgsql security definer set search_path=''as $$declare school uuid:="authorization".school_id();begin
 if not"authorization".has_entitlement(school,'learning')or not"authorization".can_read_course(school,target_course)or"authorization".current_role(school)is null or not("authorization".current_role(school)in('admin','teacher')and"authorization".can_manage_course(school,target_course)or"authorization".current_role(school)='student'and"authorization".can_learn_course(school,target_course))then raise exception 'Academic source write course denied'using errcode='42501';end if;
 perform internal.lock_academic_course(school,target_course);
 if not internal.programme_academic_write_allowed(school,target_course)then raise exception 'Retired curriculum source is read only'using errcode='22023';end if;
end$$;
create function internal.read_course_retired(target_course uuid)returns boolean language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();begin
 if not"authorization".can_read_course(school,target_course)then raise exception 'Course availability denied'using errcode='42501';end if;return not internal.programme_academic_write_allowed(school,target_course);
end$$;
create function internal.read_learning_lifecycle_availability(target_courses uuid[])returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();items jsonb;begin
 if target_courses is null or cardinality(target_courses)>100 or not"authorization".has_entitlement(school,'learning')or not"authorization".can_access_school(school)then raise exception 'Learning source availability denied'using errcode='42501';end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',course.id,'readOnly',not internal.programme_academic_write_allowed(school,course.id))order by course.id),'[]'::jsonb)into items from app.courses course where course.school_id=school and course.id=any(target_courses)and"authorization".can_read_course(school,course.id)and not internal.programme_academic_write_allowed(school,course.id);return jsonb_build_object('items',items);
end$$;
do $$declare signature text;definition text;anchor text;begin
 foreach signature in array array['internal.mark_submission(uuid,numeric,text,integer,integer,boolean)','internal.mark_rubric_submission(uuid,uuid,jsonb,text,integer,integer,boolean)']loop
  definition:=pg_get_functiondef(signature::regprocedure);anchor:='begin';if position(anchor in definition)=0 then raise exception 'Native marking entry changed'using errcode='22023';end if;
  definition:=overlay(definition placing 'begin'||chr(10)||' perform internal.lock_academic_course("authorization".school_id(),(select assessment.course_id from app.submissions submission join app.assessments assessment on assessment.school_id=submission.school_id and assessment.id=submission.assessment_id where submission.school_id="authorization".school_id()and submission.id=target_submission));' from position(anchor in definition)for length(anchor));execute definition;
 end loop;
end$$;
do $$declare signature text;definition text;anchor text;begin
 foreach signature in array array['internal.configure_assessment_availability(uuid,timestamp with time zone,timestamp with time zone,boolean,text,integer)','internal.create_learning_submission(uuid,text)','internal.save_submission_draft(uuid,text,integer)','internal.submit_quiz_attempt(uuid,uuid,jsonb)','internal.release_marking(uuid,integer,boolean)','internal.release_rubric_marking(uuid,integer,boolean)']loop
  definition:=pg_get_functiondef(signature::regprocedure);anchor:='begin';if position(anchor in definition)=0 then raise exception 'Academic lifecycle entry changed'using errcode='22023';end if;
  if signature like'%release_%'then
   definition:=overlay(definition placing 'begin'||chr(10)||' perform internal.require_curriculum_academic_write((select assessment.course_id from(select submission_id from app.marking_revisions where school_id="authorization".school_id()and id=target_marking union all select submission_id from app.rubric_marking_revisions where school_id="authorization".school_id()and id=target_marking)mark join app.submissions submission on submission.school_id="authorization".school_id()and submission.id=mark.submission_id join app.assessments assessment on assessment.school_id=submission.school_id and assessment.id=submission.assessment_id));' from position(anchor in definition)for length(anchor));
  else definition:=overlay(definition placing 'begin'||chr(10)||' perform internal.require_curriculum_academic_write("authorization".assessment_course("authorization".school_id(),target_assessment));' from position(anchor in definition)for length(anchor));end if;execute definition;
 end loop;
end$$;
-- Configuration and lifecycle use the same school transition lock before course locks.
do $$declare definition text;anchor text;begin
 definition:=pg_get_functiondef('internal.submission_work_command(text,uuid,uuid,jsonb,text,text,text)'::regprocedure);anchor:='begin';if position(anchor in definition)=0 then raise exception 'Document work entry changed'using errcode='22023';end if;definition:=overlay(definition placing 'begin'||chr(10)||' perform internal.require_curriculum_academic_write("authorization".assessment_course("authorization".school_id(),target_assessment));'from position(anchor in definition)for length(anchor));execute definition;
 definition:=pg_get_functiondef('internal.submission_document_command(text,uuid,uuid,jsonb,text,text,text)'::regprocedure);anchor:='begin';if position(anchor in definition)=0 then raise exception 'Document asset entry changed'using errcode='22023';end if;definition:=overlay(definition placing 'begin'||chr(10)||' if command_name<>''retire''then perform internal.require_curriculum_academic_write("authorization".assessment_course("authorization".school_id(),target_assessment));end if;'from position(anchor in definition)for length(anchor));execute definition;
end$$;
do $$declare signature text;definition text;anchor text;begin
 foreach signature in array array['internal.configure_curriculum(text,uuid,jsonb,text,text,text)','internal.approve_course_objective(uuid,jsonb,text,text,text)','internal.record_objective_plan(text,uuid,jsonb,text,text,text)']loop
  definition:=pg_get_functiondef(signature::regprocedure);anchor:='begin';if position(anchor in definition)=0 then raise exception 'Curriculum command entry changed'using errcode='22023';end if;
  definition:=overlay(definition placing 'begin'||chr(10)||' perform pg_advisory_xact_lock(hashtextextended("authorization".school_id()::text||'':curriculum-lifecycle'',0));' from position(anchor in definition)for length(anchor));execute definition;
end loop;
end$$;
do $$declare definition text;anchor text;begin
 definition:=pg_get_functiondef('internal.configure_curriculum(text,uuid,jsonb,text,text,text)'::regprocedure);anchor:='reservation:=internal.begin_command';
 if position(anchor in definition)=0 then raise exception 'Curriculum replay boundary changed'using errcode='22023';end if;
 definition:=replace(definition,anchor,'if command_name=''reference.create''and internal.current_curriculum_lifecycle(school,pack.id)<>''DRAFT''then raise exception ''Reviewed source hierarchy immutable''using errcode=''22023'';end if;if command_name in(''programme.create'',''course.configure'',''learner.configure'')and not(command_name=''learner.configure''and payload->>''status''=''revoked'')and internal.current_curriculum_lifecycle(school,pack.id)<>''ACTIVE''then raise exception ''Active source required before replay''using errcode=''22023'';end if;'||anchor);execute definition;
 definition:=pg_get_functiondef('internal.approve_course_objective(uuid,jsonb,text,text,text)'::regprocedure);anchor:='reservation:=internal.begin_command';definition:=replace(definition,anchor,'if not internal.programme_configuration_allowed(school,target_course)then raise exception ''Active source objective approval required''using errcode=''22023'';end if;'||anchor);execute definition;
 definition:=pg_get_functiondef('internal.record_objective_plan(text,uuid,jsonb,text,text,text)'::regprocedure);anchor:='reservation:=internal.begin_command';definition:=replace(definition,anchor,'if not internal.programme_configuration_allowed(school,planned_course)then raise exception ''Active source planning required''using errcode=''22023'';end if;'||anchor);execute definition;
end$$;
create function internal.curriculum_open_work_count(target_school uuid,target_version uuid)returns integer language sql stable security definer set search_path=''as $$select count(*)::integer from app.assessments assessment join app.programme_course_contexts pinned on pinned.school_id=assessment.school_id and pinned.course_id=assessment.course_id join app.programme_instances programme on programme.school_id=pinned.school_id and programme.id=pinned.programme_id where programme.school_id=target_school and programme.pack_version_id=target_version and(assessment.status='PUBLISHED'and assessment.assignment_state='OPEN'or exists(select 1 from app.current_submissions pointer where pointer.school_id=assessment.school_id and pointer.assessment_id=assessment.id and pointer.state in('SUBMITTED','RESUBMITTED','RETURNED'))or exists(select 1 from app.interventions intervention join internal.academic_result_sources baseline on baseline.school_id=intervention.school_id and baseline.id=intervention.baseline_result_id where baseline.school_id=assessment.school_id and internal.native_academic_source(baseline.school_id,baseline.id)->>'assessmentId'=assessment.id::text and intervention.status='ASSIGNED'))$$;
create function internal.require_curriculum_lifecycle(target_version uuid,manage boolean)returns void language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();begin if not"authorization".has_entitlement(school,'curriculum')or not"authorization".can_access_school(school)or"authorization".current_role(school)is null or"authorization".current_role(school)not in('admin','coordinator','teacher')or(manage and"authorization".current_role(school)not in('admin','coordinator'))or not exists(select 1 from app.curriculum_versions where school_id=school and id=target_version)then raise exception 'Curriculum lifecycle access denied'using errcode='42501';end if;end$$;
create function internal.read_curriculum_lifecycle(target_version uuid,page_limit integer,page_cursor uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();current app.curriculum_lifecycle_revisions;items jsonb;next_cursor uuid;begin
 perform internal.require_curriculum_lifecycle(target_version,false);if page_limit is null or page_limit not between 1 and 25 then raise exception 'Bounded lifecycle history required'using errcode='22023';end if;
 select*into current from app.curriculum_lifecycle_revisions where school_id=school and version_id=target_version order by revision desc limit 1;
 with bounded as materialized(select*from app.curriculum_lifecycle_revisions where school_id=school and version_id=target_version and(page_cursor is null or id>page_cursor)order by id limit page_limit+1),visible as(select*from bounded order by id limit page_limit)
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'state',state,'revision',revision,'reason',reason,'createdAt',created_at)order by id),'[]'::jsonb),case when(select count(*)from bounded)>page_limit then(select id from visible order by id desc limit 1)end into items,next_cursor from visible;
 return jsonb_build_object('versionId',target_version,'state',current.state,'revision',current.revision,'customerReady',false,'configurationAllowed',current.state='ACTIVE','retainedEvidenceAllowed',true,'programmeCount',(select count(*)from app.programme_instances where school_id=school and pack_version_id=target_version),'courseCount',(select count(*)from app.programme_course_contexts pinned join app.programme_instances programme on programme.school_id=pinned.school_id and programme.id=pinned.programme_id where programme.school_id=school and programme.pack_version_id=target_version),'openAssessmentCount',internal.curriculum_open_work_count(school,target_version),'reason',current.reason,'history',items,'nextCursor',next_cursor);
end$$;
create function internal.transition_curriculum_lifecycle(target_version uuid,payload jsonb,artifact jsonb,command_key text,fingerprint text,request_id text)returns jsonb language plpgsql security definer set search_path=''as $$
declare school uuid:="authorization".school_id();pack app.curriculum_versions;replacement app.curriculum_versions;current app.curriculum_lifecycle_revisions;reservation jsonb;receipt jsonb;state_value text:=payload->>'state';begin
 perform internal.require_curriculum_lifecycle(target_version,true);
 if payload is null or jsonb_typeof(payload)<>'object'or payload-'state'-'expectedRevision'-'reviewBasis'-'artifactDirectory'-'replacementVersionId'-'reason'-'confirmTransition'<>'{}'::jsonb or payload->'confirmTransition'is distinct from'true'::jsonb or payload->>'reviewBasis'is null or payload->>'reviewBasis'not in('SCHOOL_AUTHORED','LOCKED_ARTIFACT')or state_value is null or state_value not in('DRAFT','APPROVED','ACTIVE','SUPERSEDED','RETIRED')or jsonb_typeof(payload->'reason')is distinct from'string'or length(btrim(payload->>'reason'))not between 1 and 2000 or jsonb_typeof(payload->'expectedRevision')is distinct from'number'or payload->>'expectedRevision'!~'^[1-9][0-9]*$'then raise exception 'Explicit lifecycle review required'using errcode='22023';end if;
 perform pg_advisory_xact_lock(hashtextextended(school::text||':curriculum-lifecycle',0));
 select*into pack from app.curriculum_versions where school_id=school and id=target_version for update;
 perform 1 from app.courses course join app.programme_course_contexts pinned on pinned.school_id=course.school_id and pinned.course_id=course.id join app.programme_instances programme on programme.school_id=pinned.school_id and programme.id=pinned.programme_id where course.school_id=school and programme.pack_version_id=target_version order by course.id for update of course;
 perform internal.require_curriculum_lifecycle(target_version,true);
 select*into current from app.curriculum_lifecycle_revisions where school_id=school and version_id=target_version order by revision desc limit 1;
 if not pack.synthetic or pack.kind<>'school_custom'or pack.source_status<>'VERIFIED'or pack.rights_status<>'PERMITTED'then raise exception 'Official/source acceptance is not established'using errcode='22023';end if;
 if state_value in('APPROVED','ACTIVE')and payload->>'reviewBasis'='SCHOOL_AUTHORED'then
  if artifact is not null or payload->'artifactDirectory'is distinct from'null'::jsonb or not exists(select 1 from app.curriculum_references reference where reference.school_id=school and reference.pack_version_id=pack.id and reference.type in('objective','outcome','criterion'))or exists(select 1 from app.curriculum_references reference where reference.school_id=school and reference.pack_version_id=pack.id and(length(btrim(reference.title))not between 1 and 200 or length(btrim(reference.description))not between 1 and 4000))then raise exception 'Complete school-authored hierarchy and explicit review required'using errcode='22023';end if;
 end if;
 if state_value in('APPROVED','ACTIVE')and payload->>'reviewBasis'='LOCKED_ARTIFACT'then
  if artifact is null or jsonb_typeof(artifact)is distinct from'object'or jsonb_typeof(artifact->'references')is distinct from'array'then raise exception 'Exact locked artifact structure required'using errcode='22023';end if;
  if (select count(distinct item->>'title')from jsonb_array_elements(artifact->'references')item)<>jsonb_array_length(artifact->'references')or exists(select 1 from app.curriculum_references where school_id=school and pack_version_id=pack.id group by title having count(*)>1)then raise exception 'Ambiguous locked hierarchy identity requires review'using errcode='22023';end if;
  if artifact is null or artifact->>'packId'is distinct from pack.pack_id or artifact->>'version'is distinct from pack.version or artifact->>'scope'is distinct from pack.scope or artifact->>'framework'is distinct from pack.framework or artifact->>'programme'is distinct from pack.programme or artifact->>'sourceChecksum'is distinct from pack.source_checksum or artifact->>'digest'is null or jsonb_typeof(artifact->'references')is distinct from'array'or(jsonb_array_length(artifact->'references'))<>(select count(*)from app.curriculum_references where school_id=school and pack_version_id=pack.id)then raise exception 'Exact locked technical artifact required'using errcode='22023';end if;
 if exists(select 1 from jsonb_array_elements(artifact->'references')source where not exists(select 1 from app.curriculum_references reference left join app.curriculum_references parent on parent.school_id=reference.school_id and parent.id=reference.parent_id where reference.school_id=school and reference.pack_version_id=pack.id and reference.title=source->>'title'and reference.description=source->>'description'and reference.type=source->>'type'and reference.sequence=(source->>'sequence')::integer and parent.title is not distinct from source->>'parentTitle'))or exists(select 1 from app.curriculum_references reference left join app.curriculum_references parent on parent.school_id=reference.school_id and parent.id=reference.parent_id where reference.school_id=school and reference.pack_version_id=pack.id and not exists(select 1 from jsonb_array_elements(artifact->'references')source where reference.title=source->>'title'and reference.description=source->>'description'and reference.type=source->>'type'and reference.sequence=(source->>'sequence')::integer and parent.title is not distinct from source->>'parentTitle'))then raise exception 'Locked hierarchy differs from stored source'using errcode='22023';end if;
 end if;
 if state_value='SUPERSEDED'then select*into replacement from app.curriculum_versions where school_id=school and id=(payload->>'replacementVersionId')::uuid;if replacement.id is null or replacement.id=pack.id or replacement.pack_id<>pack.pack_id or replacement.framework<>pack.framework or replacement.programme<>pack.programme or replacement.scope<>pack.scope or not replacement.synthetic or internal.current_curriculum_lifecycle(school,replacement.id)<>'ACTIVE'then raise exception 'Exact active replacement context required'using errcode='22023';end if;end if;
 reservation:=internal.begin_command(command_key,'curriculum.lifecycle.transition',fingerprint);if reservation->>'state'='COMPLETED'then return reservation->'response';end if;
 if reservation->>'state'<>'NEW'or current.revision is distinct from(payload->>'expectedRevision')::integer or not(current.state='DRAFT'and state_value='APPROVED'or current.state='APPROVED'and state_value='ACTIVE'or current.state='ACTIVE'and state_value in('SUPERSEDED','RETIRED')or current.state='SUPERSEDED'and state_value='RETIRED')then raise exception 'Lifecycle revision or transition requires review'using errcode='22023';end if;
 if state_value='RETIRED'and internal.curriculum_open_work_count(school,target_version)>0 then raise exception 'Resolve open academic work before retirement'using errcode='22023';end if;
 insert into app.curriculum_lifecycle_revisions(school_id,version_id,revision,state,replacement_version_id,reason,artifact_digest,created_by)values(school,target_version,current.revision+1,state_value,(payload->>'replacementVersionId')::uuid,btrim(payload->>'reason'),artifact->>'digest',"authorization".actor_id());
 receipt:=jsonb_build_object('id',target_version,'state',state_value,'revision',current.revision+1,'customerReady',false);perform internal.append_audit('curriculum.lifecycle.transition','curriculum',target_version,request_id,'succeeded',jsonb_build_object('state',state_value));perform internal.enqueue_event('curriculum.configured','curriculum',target_version,current.revision+1,'{}',md5('curriculum-lifecycle:'||"authorization".actor_id()::text||':'||command_key));perform internal.finish_command(command_key,'curriculum.lifecycle.transition',fingerprint,receipt);return receipt;
end$$;
revoke execute on function internal.current_curriculum_lifecycle(uuid,uuid),internal.record_initial_curriculum_lifecycle(),internal.programme_configuration_allowed(uuid,uuid),internal.programme_academic_write_allowed(uuid,uuid),internal.curriculum_configuration_guard(),internal.curriculum_reference_draft_guard(),internal.curriculum_academic_write_guard(),internal.require_curriculum_academic_write(uuid),internal.read_course_retired(uuid),internal.read_learning_lifecycle_availability(uuid[]),internal.curriculum_open_work_count(uuid,uuid),internal.require_curriculum_lifecycle(uuid,boolean),internal.read_curriculum_lifecycle(uuid,integer,uuid),internal.transition_curriculum_lifecycle(uuid,jsonb,jsonb,text,text,text)from public,anon,authenticated,service_role,cuevo_api,cuevo_worker;
grant execute on function internal.require_curriculum_academic_write(uuid),internal.read_course_retired(uuid),internal.read_learning_lifecycle_availability(uuid[]),internal.read_curriculum_lifecycle(uuid,integer,uuid),internal.transition_curriculum_lifecycle(uuid,jsonb,jsonb,text,text,text)to cuevo_api;
commit;
