begin;
-- Selected released evidence and reviewed reflection revisions are separate from academic authority.
create table app.portfolio_items(school_id uuid not null,id uuid not null default gen_random_uuid(),learner_id uuid not null,source_model text not null check(source_model in('numeric','rubric')),evidence_id uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,learner_id,source_model,evidence_id),foreign key(school_id,learner_id)references app.memberships(school_id,actor_id));
create table app.portfolio_revisions(school_id uuid not null,id uuid not null default gen_random_uuid(),item_id uuid not null,revision integer not null check(revision>0),title text not null check(length(btrim(title))between 1 and 200),reflection text not null check(length(btrim(reflection))between 1 and 10000),created_by uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,item_id,revision),unique(school_id,id,item_id),foreign key(school_id,item_id)references app.portfolio_items(school_id,id),foreign key(school_id,created_by)references app.memberships(school_id,actor_id));
create table app.portfolio_reviews(school_id uuid not null,id uuid not null default gen_random_uuid(),item_id uuid not null,revision_id uuid not null,feedback text not null check(length(btrim(feedback))between 1 and 10000),featured boolean not null,parent_visible boolean not null,reviewed_by uuid not null,reviewed_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,revision_id),foreign key(school_id,revision_id,item_id)references app.portfolio_revisions(school_id,id,item_id),foreign key(school_id,reviewed_by)references app.memberships(school_id,actor_id));
create table app.portfolio_current(school_id uuid not null,item_id uuid not null,revision_id uuid not null,parent_revision_id uuid,primary key(school_id,item_id),foreign key(school_id,revision_id,item_id)references app.portfolio_revisions(school_id,id,item_id),foreign key(school_id,parent_revision_id,item_id)references app.portfolio_revisions(school_id,id,item_id));
create table app.portfolio_parent_revocations(school_id uuid not null,id uuid not null default gen_random_uuid(),item_id uuid not null,reason text not null check(length(btrim(reason))between 1 and 2000),actor_id uuid not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),foreign key(school_id,item_id)references app.portfolio_items(school_id,id),foreign key(school_id,actor_id)references app.memberships(school_id,actor_id));
create function internal.portfolio_source(target_model text,target_evidence uuid,for_parent boolean)returns jsonb language plpgsql security definer set search_path=''as $$declare source jsonb;begin
 if not"authorization".can_access_school("authorization".school_id())or not"authorization".has_entitlement("authorization".school_id(),'portfolio')then raise exception 'Portfolio source denied'using errcode='42501';end if;
 if target_model='numeric'then
  select jsonb_build_object('learnerId',r.learner_id,'evidenceId',e.id,'resultId',r.id,'submissionId',r.submission_id,'referenceId',r.reference_id,'referenceVersion',r.reference_version,'policyVersion',r.policy_version,'nativeResult',jsonb_build_object('type','numeric','score',r.score,'maxScore',r.max_score,'policyVersion',r.policy_version),'parentVisible',r.parent_visible,'assessmentTitle',a.title,'referenceTitle',ref.title)into source from app.academic_evidence e join app.result_revisions r on r.school_id=e.school_id and r.id=e.result_id join app.assessments a on a.school_id=r.school_id and a.id=r.assessment_id join app.school_custom_references ref on ref.school_id=r.school_id and ref.id=r.reference_id where e.school_id="authorization".school_id()and e.id=target_evidence and e.learner_id=r.learner_id and e.source_object_id=r.submission_id and"authorization".can_read_academic(r.school_id,r.learner_id,r.parent_visible)and"authorization".can_read_course(r.school_id,a.course_id)and(not for_parent or(r.parent_visible and e.parent_visible));
 elsif target_model='rubric'then
  select jsonb_build_object('learnerId',r.learner_id,'evidenceId',e.id,'resultId',r.id,'submissionId',r.submission_id,'referenceId',r.reference_id,'referenceVersion',r.reference_version,'policyVersion',r.policy_version,'nativeResult',r.native_result,'parentVisible',r.parent_visible,'assessmentTitle',a.title,'referenceTitle',ref.title)into source from app.rubric_evidence e join app.rubric_result_revisions r on r.school_id=e.school_id and r.id=e.result_id join app.assessments a on a.school_id=r.school_id and a.id=r.assessment_id join app.school_custom_references ref on ref.school_id=r.school_id and ref.id=r.reference_id where e.school_id="authorization".school_id()and e.id=target_evidence and e.learner_id=r.learner_id and e.source_object_id=r.submission_id and"authorization".can_read_academic(r.school_id,r.learner_id,r.parent_visible)and"authorization".can_read_course(r.school_id,a.course_id)and(not for_parent or(r.parent_visible and e.parent_visible));
 end if;
 if source is null or not exists(select 1 from app.school_custom_references ref join app.school_custom_versions version on version.school_id=ref.school_id and version.id=ref.version_id where ref.school_id="authorization".school_id()and ref.id=(source->>'referenceId')::uuid and ref.status='APPROVED'and version.version=source->>'referenceVersion')then raise exception 'Released portfolio evidence unavailable'using errcode='42501';end if;return source;
end$$;

create table app.recognition_policies(school_id uuid not null,id uuid not null default gen_random_uuid(),version integer not null check(version>0),practice_points integer not null check(practice_points between 0 and 1000),revision_points integer not null check(revision_points between 0 and 1000),reflection_points integer not null check(reflection_points between 0 and 1000),milestones jsonb not null check(jsonb_typeof(milestones)='array'and jsonb_array_length(milestones)<=20),approved_by uuid not null,approved_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,version),foreign key(school_id,approved_by)references app.memberships(school_id,actor_id));
create table app.recognition_periods(school_id uuid not null,id uuid not null default gen_random_uuid(),class_id uuid not null,policy_id uuid not null,title text not null check(length(btrim(title))between 1 and 200),starts_at timestamptz not null,ends_at timestamptz not null,approved_by uuid not null,approved_at timestamptz not null default clock_timestamp(),primary key(school_id,id),foreign key(school_id,class_id)references app.classes(school_id,id),foreign key(school_id,policy_id)references app.recognition_policies(school_id,id),foreign key(school_id,approved_by)references app.memberships(school_id,actor_id),check(ends_at>starts_at));
create table app.xp_ledger(school_id uuid not null,id uuid not null default gen_random_uuid(),learner_id uuid not null,period_id uuid not null,policy_id uuid not null,observation_id uuid not null,kind text not null check(kind in('practice','revision','reflection')),points integer not null check(points between 0 and 1000),occurred_at timestamptz not null,awarded_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,observation_id,period_id),foreign key(school_id,learner_id)references app.memberships(school_id,actor_id),foreign key(school_id,period_id)references app.recognition_periods(school_id,id),foreign key(school_id,policy_id)references app.recognition_policies(school_id,id),foreign key(school_id,observation_id)references app.habit_observations(school_id,id));
create table app.learner_achievements(school_id uuid not null,id uuid not null default gen_random_uuid(),learner_id uuid not null,period_id uuid not null,policy_id uuid not null,milestone_key text not null,title text not null,minimum_points integer not null,earned_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,learner_id,period_id,milestone_key),foreign key(school_id,learner_id)references app.memberships(school_id,actor_id),foreign key(school_id,period_id)references app.recognition_periods(school_id,id),foreign key(school_id,policy_id)references app.recognition_policies(school_id,id));
create table app.leaderboard_participation(school_id uuid not null,period_id uuid not null,learner_id uuid not null,opt_in boolean not null default false,alias text not null check(length(alias)<=50),updated_at timestamptz not null default clock_timestamp(),primary key(school_id,period_id,learner_id),foreign key(school_id,period_id)references app.recognition_periods(school_id,id),foreign key(school_id,learner_id)references app.memberships(school_id,actor_id),check(not opt_in or length(btrim(alias))>0));
create function internal.recognition_enabled(target_school uuid,leaderboard boolean)returns boolean language sql stable security definer set search_path=''as $$select coalesce("authorization".can_access_school(target_school)and"authorization".has_entitlement(target_school,'learner.state')and exists(select 1 from app.school_policy_versions p where p.school_id=target_school and p.version=(select max(version)from app.school_policy_versions where school_id=target_school)and p.recognition_enabled and(not leaderboard or p.leaderboard_enabled)),false)$$;
create function internal.current_period_scope(target_period uuid,target_learner uuid)returns boolean language sql stable security definer set search_path=''as $$select coalesce(exists(select 1 from app.recognition_periods p join app.enrollments e on e.school_id=p.school_id and e.class_id=p.class_id join app.memberships m on m.school_id=e.school_id and m.actor_id=e.student_actor_id join app.classes c on c.school_id=p.school_id and c.id=p.class_id where p.school_id="authorization".school_id()and p.id=target_period and e.student_actor_id=target_learner and e.status='active'and e.effective_from<=now()and(e.effective_to is null or e.effective_to>now())and m.role='student'and m.status='active'and m.effective_from<=now()and(m.effective_to is null or m.effective_to>now())and c.status='active'),false)$$;
-- Called by authorized admin backfill or by a validated habit event, never by the browser directly.
create function internal.award_recognition_observation(target_school uuid,target_observation uuid,target_period uuid)returns integer language plpgsql security definer set search_path=''as $$
declare o app.habit_observations;p app.recognition_periods;policy app.recognition_policies;points integer;awarded uuid;total integer;milestone jsonb;
begin
 select*into o from app.habit_observations where school_id=target_school and id=target_observation;select*into p from app.recognition_periods where school_id=target_school and id=target_period;
 if o.id is null or p.id is null or o.occurred_at<p.starts_at or o.occurred_at>=p.ends_at or not exists(select 1 from internal.processed_events pe where pe.event_id=o.source_event_id and pe.school_id=o.school_id)or not exists(select 1 from app.enrollments e join app.memberships m on m.school_id=e.school_id and m.actor_id=e.student_actor_id join app.classes c on c.school_id=e.school_id and c.id=e.class_id where e.school_id=p.school_id and e.class_id=p.class_id and e.student_actor_id=o.learner_id and e.status='active'and e.effective_from<=now()and(e.effective_to is null or e.effective_to>now())and m.role='student'and m.status='active'and m.effective_from<=now()and(m.effective_to is null or m.effective_to>now())and c.status='active')then return 0;end if;
 if(o.source_type='ACTIVITY_COMPLETION'and not exists(select 1 from app.activity_completions completion join app.activities activity on activity.school_id=completion.school_id and activity.id=completion.activity_id where completion.school_id=o.school_id and completion.id=o.source_object_id and completion.learner_id=o.learner_id and completion.completed_at=o.occurred_at and activity.kind=o.kind))or(o.source_type='SUBMISSION_REVISION'and not exists(select 1 from app.submissions submission join app.submission_returns returned on returned.school_id=submission.school_id and returned.id=submission.return_id where submission.school_id=o.school_id and submission.id=o.source_object_id and submission.learner_id=o.learner_id and submission.submitted_at=o.occurred_at and returned.submission_id=submission.previous_submission_id and o.kind='revision'))then return 0;end if;
 select*into policy from app.recognition_policies where school_id=p.school_id and id=p.policy_id;points:=case o.kind when'practice'then policy.practice_points when'revision'then policy.revision_points when'reflection'then policy.reflection_points end;
 if points is null then raise exception 'Recognition policy unavailable'using errcode='22023';end if;
 perform pg_advisory_xact_lock(hashtextextended(target_school::text||':recognition:'||p.id::text||':'||o.learner_id::text,0));
 insert into app.xp_ledger(school_id,learner_id,period_id,policy_id,observation_id,kind,points,occurred_at)values(target_school,o.learner_id,p.id,policy.id,o.id,o.kind,points,o.occurred_at)on conflict(school_id,observation_id,period_id)do nothing returning id into awarded;
 if awarded is null then return 0;end if;
 select coalesce(sum(x.points),0)::integer into total from app.xp_ledger x where x.school_id=target_school and x.period_id=p.id and x.learner_id=o.learner_id;
 for milestone in select*from jsonb_array_elements(policy.milestones)loop if total>=(milestone->>'minimumPoints')::integer then insert into app.learner_achievements(school_id,learner_id,period_id,policy_id,milestone_key,title,minimum_points)values(target_school,o.learner_id,p.id,policy.id,milestone->>'key',milestone->>'title',(milestone->>'minimumPoints')::integer)on conflict(school_id,learner_id,period_id,milestone_key)do nothing;end if;end loop;
 return 1;
end$$;
create function internal.process_recognition_event(target_event uuid,current_lease uuid)returns jsonb language plpgsql security definer set search_path=''as $$declare e internal.outbox_events;o app.habit_observations;p app.recognition_periods;awards integer:=0;enabled boolean;begin
 select*into e from internal.outbox_events where id=target_event for update;if not found or e.state<>'PROCESSING'or e.lease_token is distinct from current_lease or e.lease_until<=clock_timestamp()or e.type<>'habit.observed'or e.entity_type<>'observation'then raise exception 'Invalid recognition event lease'using errcode='22023';end if;
 select*into o from app.habit_observations where school_id=e.school_id and id=e.entity_id;if not found or not exists(select 1 from internal.processed_events pe where pe.school_id=o.school_id and pe.event_id=o.source_event_id)then raise exception 'Verified observation source required'using errcode='22023';end if;
 if(o.source_type='ACTIVITY_COMPLETION'and not exists(select 1 from app.activity_completions completion join app.activities activity on activity.school_id=completion.school_id and activity.id=completion.activity_id where completion.school_id=o.school_id and completion.id=o.source_object_id and completion.learner_id=o.learner_id and completion.completed_at=o.occurred_at and activity.kind=o.kind))or(o.source_type='SUBMISSION_REVISION'and not exists(select 1 from app.submissions submission join app.submission_returns returned on returned.school_id=submission.school_id and returned.id=submission.return_id where submission.school_id=o.school_id and submission.id=o.source_object_id and submission.learner_id=o.learner_id and submission.submitted_at=o.occurred_at and returned.submission_id=submission.previous_submission_id and o.kind='revision'))then raise exception 'Observation ownership or action mismatch'using errcode='22023';end if;
 select exists(select 1 from app.schools s where s.id=e.school_id and s.status='active')and exists(select 1 from app.entitlements entitlement where entitlement.school_id=e.school_id and entitlement.code='learner.state'and entitlement.enabled and entitlement.effective_from<=now()and(entitlement.effective_to is null or entitlement.effective_to>now()))and exists(select 1 from app.school_policy_versions policy where policy.school_id=e.school_id and policy.version=(select max(version)from app.school_policy_versions where school_id=e.school_id)and policy.recognition_enabled)into enabled;
 if enabled then for p in select*from app.recognition_periods where school_id=e.school_id and o.occurred_at>=starts_at and o.occurred_at<ends_at loop awards:=awards+internal.award_recognition_observation(e.school_id,o.id,p.id);end loop;end if;
 if internal.complete_outbox(e.id,current_lease)is distinct from true then raise exception 'Lease expired before recognition acknowledgement'using errcode='22023';end if;return jsonb_build_object('status',case when enabled then'AWARDED'else'ACKNOWLEDGED_DISABLED'end,'awards',awards);
end$$;
create function internal.development_command(command_name text,payload jsonb,command_key text,fingerprint text,request_id text)returns jsonb language plpgsql security definer set search_path=''as $$
declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();reservation jsonb;receipt jsonb;rid uuid;p app.recognition_periods;current_version integer;awards integer:=0;o record;
begin
 if not internal.recognition_enabled(school,false)and not(command_name='participation'and(payload->>'optIn')::boolean is false and"authorization".can_access_school(school)and"authorization".has_entitlement(school,'learner.state'))then raise exception 'School recognition approval required'using errcode='42501';end if;
 if command_name='participation'then if"authorization".current_role(school)<>'student'or not internal.current_period_scope((payload->>'periodId')::uuid,actor)or((payload->>'optIn')::boolean and not internal.recognition_enabled(school,true))then raise exception 'Leaderboard opt-in denied'using errcode='42501';end if;
 else if"authorization".current_role(school)<>'admin'then raise exception 'Admin recognition approval required'using errcode='42501';end if;end if;
 if command_name in('period','backfill')and(payload->>'confirmApproval')::boolean is distinct from true then raise exception 'Recognition confirmation required'using errcode='22023';end if;
 if command_name in('backfill','participation')then select*into p from app.recognition_periods where school_id=school and id=(payload->>'periodId')::uuid;if not found then raise exception 'Recognition period denied'using errcode='42501';end if;end if;
 if command_name='period'and(not exists(select 1 from app.recognition_policies where school_id=school and id=(payload->>'policyId')::uuid)or not exists(select 1 from app.classes where school_id=school and id=(payload->>'classId')::uuid and status='active'))then raise exception 'Recognition period context denied'using errcode='42501';end if;
 reservation:=internal.begin_command(command_key,'development.'||command_name,fingerprint);if reservation->>'state'='COMPLETED'then return reservation->'response';end if;if reservation->>'state'<>'NEW'then raise exception 'Recognition command pending'using errcode='22023';end if;
 if command_name='policy'then
  if(payload->>'confirmApproval')::boolean is distinct from true or jsonb_typeof(payload->'milestones')<>'array'or jsonb_array_length(payload->'milestones')>20 then raise exception 'Approved bounded recognition policy required'using errcode='22023';end if;
  perform pg_advisory_xact_lock(hashtextextended(school::text||':recognition-policy',0));select coalesce(max(version),0)into current_version from app.recognition_policies where school_id=school;if current_version<>(payload->>'expectedVersion')::integer then raise exception 'Recognition policy changed'using errcode='22023';end if;
  insert into app.recognition_policies(school_id,version,practice_points,revision_points,reflection_points,milestones,approved_by)values(school,current_version+1,(payload->'points'->>'practice')::integer,(payload->'points'->>'revision')::integer,(payload->'points'->>'reflection')::integer,payload->'milestones',actor)returning id into rid;
 elsif command_name='period'then
  if not exists(select 1 from app.recognition_policies where school_id=school and id=(payload->>'policyId')::uuid)or not exists(select 1 from app.classes where school_id=school and id=(payload->>'classId')::uuid and status='active')then raise exception 'Recognition period context denied'using errcode='42501';end if;
  perform pg_advisory_xact_lock(hashtextextended(school::text||':recognition-period',0));if exists(select 1 from app.recognition_periods where school_id=school and class_id=(payload->>'classId')::uuid and starts_at<(payload->>'endsAt')::timestamptz and ends_at>(payload->>'startsAt')::timestamptz)then raise exception 'Recognition period overlaps'using errcode='22023';end if;
  insert into app.recognition_periods(school_id,class_id,policy_id,title,starts_at,ends_at,approved_by)values(school,(payload->>'classId')::uuid,(payload->>'policyId')::uuid,payload->>'title',(payload->>'startsAt')::timestamptz,(payload->>'endsAt')::timestamptz,actor)returning id into rid;
 elsif command_name='participation'then
  insert into app.leaderboard_participation(school_id,period_id,learner_id,opt_in,alias)values(school,(payload->>'periodId')::uuid,actor,(payload->>'optIn')::boolean,payload->>'alias')on conflict(school_id,period_id,learner_id)do update set opt_in=excluded.opt_in,alias=excluded.alias,updated_at=clock_timestamp();rid:=(payload->>'periodId')::uuid;
 elsif command_name='backfill'then
  select*into p from app.recognition_periods where school_id=school and id=(payload->>'periodId')::uuid;if not found then raise exception 'Recognition period denied'using errcode='42501';end if;
  if(select count(*)from(select id from app.habit_observations where school_id=school and occurred_at>=p.starts_at and occurred_at<p.ends_at limit 1001)bounded)>1000 then raise exception 'Recognition backfill requires bounded review'using errcode='22023';end if;
  for o in select id from app.habit_observations where school_id=school and occurred_at>=p.starts_at and occurred_at<p.ends_at loop awards:=awards+internal.award_recognition_observation(school,o.id,p.id);end loop;rid:=p.id;
 else raise exception 'Unknown development command'using errcode='22023';end if;
 receipt:=jsonb_build_object('id',rid,'command',command_name,'awards',awards);perform internal.append_audit('development.'||command_name,'development',rid,request_id,'succeeded','{}');perform internal.enqueue_event('development.updated','development',rid,1,'{}','development:'||actor::text||':'||command_key);perform internal.finish_command(command_key,'development.'||command_name,fingerprint,receipt);return receipt;
end$$;
create function internal.development_read(resource text,filters jsonb)returns jsonb language plpgsql security definer set search_path=''as $$
declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();role_name text:="authorization".current_role("authorization".school_id());learner uuid;period uuid;lim integer;cursor_id uuid;items jsonb;enabled boolean;
begin
 if not"authorization".can_access_school(school)or not"authorization".has_entitlement(school,'learner.state')or role_name not in('admin','coordinator','teacher','student')then raise exception 'Recognition read denied'using errcode='42501';end if;
 learner:=coalesce((filters->>'learnerId')::uuid,case when role_name='student'then actor end);period:=(filters->>'periodId')::uuid;lim:=(filters->>'limit')::integer;cursor_id:=(filters->>'cursor')::uuid;if lim is null or lim not between 1 and 100 then raise exception 'Bounded recognition view required'using errcode='22023';end if;
 if learner is not null and not"authorization".can_view_person(school,learner)then raise exception 'Recognition learner denied'using errcode='42501';end if;enabled:=internal.recognition_enabled(school,false);
 if resource='summary'then
  if learner is null then raise exception 'Select a learner for personal progress'using errcode='22023';end if;
  return jsonb_build_object('learnerId',learner,'status',case when enabled then'RECORDED_ONLY'else'DISABLED'end,'totalPoints',case when enabled then(select coalesce(sum(points),0)from app.xp_ledger where school_id=school and learner_id=learner and(period is null or period_id=period))else null end,'periodId',period,'leaderboardEnabled',internal.recognition_enabled(school,true));
 elsif resource='leaderboard'then
  if not internal.recognition_enabled(school,true)or period is null or(role_name='student'and not internal.current_period_scope(period,actor))or(role_name='teacher'and not exists(select 1 from app.recognition_periods p where p.school_id=school and p.id=period and"authorization".can_view_class(school,p.class_id)))then raise exception 'Class leaderboard denied'using errcode='42501';end if;
  select coalesce(jsonb_agg(jsonb_build_object('alias',alias,'points',points,'rank',rank)order by rank,alias),'[]'::jsonb)into items from(select participation.alias,coalesce(sum(ledger.points),0)points,dense_rank()over(order by coalesce(sum(ledger.points),0)desc)rank from app.leaderboard_participation participation left join app.xp_ledger ledger on ledger.school_id=participation.school_id and ledger.period_id=participation.period_id and ledger.learner_id=participation.learner_id where participation.school_id=school and participation.period_id=period and participation.opt_in and internal.current_period_scope(period,participation.learner_id)group by participation.learner_id,participation.alias order by points desc,alias limit lim)board;
  return jsonb_build_object('periodId',period,'items',items,'status','OPT_IN_RECORDED_ACTIONS');
 elsif resource='policies'then
  if role_name not in('admin','coordinator','teacher')then raise exception 'Recognition policy read denied'using errcode='42501';end if;
  select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'version',p.version,'points',jsonb_build_object('practice',p.practice_points,'revision',p.revision_points,'reflection',p.reflection_points),'milestones',p.milestones,'approvedBy',p.approved_by,'approvedAt',p.approved_at)order by p.id),'[]'::jsonb)into items from(select*from app.recognition_policies where school_id=school and(cursor_id is null or id>cursor_id)order by id limit lim+1)p;
 elsif resource='periods'then
  select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'classId',p.class_id,'policyId',p.policy_id,'title',p.title,'startsAt',p.starts_at,'endsAt',p.ends_at)order by p.id),'[]'::jsonb)into items from(select*from app.recognition_periods where school_id=school and(cursor_id is null or id>cursor_id)and"authorization".can_view_class(school,class_id)order by id limit lim+1)p;
 elsif resource in('ledger','achievements')then
  if learner is null then raise exception 'Select a learner for recognition sources'using errcode='22023';end if;
  if not enabled then return jsonb_build_object('items','[]'::jsonb,'nextCursor',null,'status','DISABLED');end if;
  if resource='ledger'then select coalesce(jsonb_agg(jsonb_build_object('id',id,'learnerId',learner_id,'periodId',period_id,'observationId',observation_id,'kind',kind,'points',points,'occurredAt',occurred_at,'policyId',policy_id)order by id),'[]'::jsonb)into items from(select*from app.xp_ledger where school_id=school and learner_id=learner and(period is null or period_id=period)and(cursor_id is null or id>cursor_id)order by id limit lim+1)x;
  else select coalesce(jsonb_agg(jsonb_build_object('id',id,'learnerId',learner_id,'periodId',period_id,'policyId',policy_id,'key',milestone_key,'title',title,'minimumPoints',minimum_points,'earnedAt',earned_at)order by id),'[]'::jsonb)into items from(select*from app.learner_achievements where school_id=school and learner_id=learner and(period is null or period_id=period)and(cursor_id is null or id>cursor_id)order by id limit lim+1)x;end if;
 else raise exception 'Unknown recognition resource'using errcode='22023';end if;
 if octet_length(items::text)>500000 then raise exception 'Recognition page requires smaller view'using errcode='22023';end if;
 return jsonb_build_object('items',(select coalesce(jsonb_agg(item),'[]'::jsonb)from jsonb_array_elements(items)with ordinality value(item,ordinal)where ordinal<=lim),'nextCursor',case when jsonb_array_length(items)>lim then items->(lim-1)->>'id'else null end);
end$$;
create function internal.portfolio_command(command_name text,target_item uuid,payload jsonb,command_key text,fingerprint text,request_id text)returns jsonb language plpgsql security definer set search_path=''as $$
declare school uuid:="authorization".school_id();actor uuid:="authorization".actor_id();item app.portfolio_items;current_item app.portfolio_current;revision app.portfolio_revisions;source jsonb;receipt jsonb;reservation jsonb;rid uuid;iid uuid;
begin
 if not"authorization".has_entitlement(school,'portfolio')then raise exception 'Portfolio entitlement required'using errcode='42501';end if;
 if command_name='create'then source:=internal.portfolio_source(payload->>'sourceModel',(payload->>'evidenceId')::uuid,false);if"authorization".current_role(school)<>'student'or(source->>'learnerId')::uuid<>actor then raise exception 'Own evidence selection required'using errcode='42501';end if;
 else
  select*into item from app.portfolio_items where school_id=school and id=target_item;if not found then raise exception 'Portfolio item denied'using errcode='42501';end if;source:=internal.portfolio_source(item.source_model,item.evidence_id,false);
  if command_name='reflection'then if"authorization".current_role(school)<>'student'or item.learner_id<>actor then raise exception 'Own reflection required'using errcode='42501';end if;
  elsif command_name in('review','revoke')then if"authorization".current_role(school)not in('admin','teacher')or not"authorization".can_mark_submission(school,(source->>'submissionId')::uuid)then raise exception 'Portfolio review denied'using errcode='42501';end if;
  else raise exception 'Unknown portfolio command'using errcode='22023';end if;
 end if;
 reservation:=internal.begin_command(command_key,'portfolio.'||command_name,fingerprint);if reservation->>'state'='COMPLETED'then return reservation->'response';end if;if reservation->>'state'<>'NEW'then raise exception 'Portfolio command pending'using errcode='22023';end if;
 if command_name='create'then
  insert into app.portfolio_items(school_id,learner_id,source_model,evidence_id)values(school,actor,payload->>'sourceModel',(payload->>'evidenceId')::uuid)returning id into iid;
  insert into app.portfolio_revisions(school_id,item_id,revision,title,reflection,created_by)values(school,iid,1,payload->>'title',payload->>'reflection',actor)returning id into rid;insert into app.portfolio_current(school_id,item_id,revision_id)values(school,iid,rid);
 else
  select*into current_item from app.portfolio_current where school_id=school and item_id=item.id for update;select*into revision from app.portfolio_revisions where school_id=school and id=current_item.revision_id;
  if command_name<>'revoke'and((payload->>'expectedRevision')::integer is null or(payload->>'expectedRevision')::integer<>revision.revision)then raise exception 'Portfolio revision changed'using errcode='22023';end if;iid:=item.id;
  if command_name='reflection'then insert into app.portfolio_revisions(school_id,item_id,revision,title,reflection,created_by)values(school,iid,revision.revision+1,payload->>'title',payload->>'reflection',actor)returning id into rid;update app.portfolio_current set revision_id=rid where school_id=school and item_id=iid;
  elsif command_name='review'then
   if(payload->>'parentVisible')::boolean and((payload->>'confirmParentApproval')::boolean is distinct from true or(source->>'parentVisible')::boolean is distinct from true)then raise exception 'Explicit source and parent approval required'using errcode='22023';end if;
   insert into app.portfolio_reviews(school_id,item_id,revision_id,feedback,featured,parent_visible,reviewed_by)values(school,iid,revision.id,payload->>'feedback',(payload->>'featured')::boolean,(payload->>'parentVisible')::boolean,actor)returning id into rid;
   if(payload->>'parentVisible')::boolean then update app.portfolio_current set parent_revision_id=revision.id where school_id=school and item_id=iid;end if;
  else insert into app.portfolio_parent_revocations(school_id,item_id,reason,actor_id)values(school,iid,payload->>'reason',actor)returning id into rid;update app.portfolio_current set parent_revision_id=null where school_id=school and item_id=iid;
  end if;
 end if;
 receipt:=jsonb_build_object('id',iid,'revisionId',case when command_name='create'or command_name='reflection'then rid else revision.id end,'revision',case when command_name='create'then 1 when command_name='reflection'then revision.revision+1 else revision.revision end,'status',case when command_name='review'then'REVIEWED'when command_name='revoke'then'PARENT_REVOKED'else'AWAITING_REVIEW'end);
 perform internal.append_audit('portfolio.'||command_name,'portfolio',iid,request_id,'succeeded','{}');perform internal.enqueue_event('portfolio.updated','portfolio',iid,1,'{}','portfolio:'||actor::text||':'||command_key);perform internal.finish_command(command_key,'portfolio.'||command_name,fingerprint,receipt);return receipt;
end$$;
create function internal.read_portfolio_page(page_limit integer,page_cursor uuid,target_learner uuid,history_item uuid)returns jsonb language plpgsql security definer set search_path=''as $$
declare school uuid:="authorization".school_id();role_name text:="authorization".current_role("authorization".school_id());row_item record;source jsonb;result jsonb:='[]';count_rows integer:=0;item_filter app.portfolio_items;
begin
 if not"authorization".has_entitlement(school,'portfolio')or page_limit is null or page_limit not between 1 and 100 then raise exception 'Portfolio read denied'using errcode='42501';end if;
 if target_learner is not null and not"authorization".can_view_person(school,target_learner)then raise exception 'Portfolio learner denied'using errcode='42501';end if;
 if history_item is not null then select*into item_filter from app.portfolio_items where school_id=school and id=history_item;if not found or role_name='parent'then raise exception 'Portfolio history denied'using errcode='42501';end if;perform internal.portfolio_source(item_filter.source_model,item_filter.evidence_id,false);end if;
 for row_item in select i.id,i.learner_id,i.source_model,i.evidence_id,r.id revision_id,r.revision,r.title,r.reflection,r.created_at,review.feedback,review.featured,review.parent_visible,review.reviewed_at
 from app.portfolio_items i join app.portfolio_current current_item on current_item.school_id=i.school_id and current_item.item_id=i.id join app.portfolio_revisions r on r.school_id=i.school_id and r.item_id=i.id and((history_item is not null)or r.id=case when role_name='parent'then current_item.parent_revision_id else current_item.revision_id end)left join app.portfolio_reviews review on review.school_id=r.school_id and review.revision_id=r.id
 where i.school_id=school and(target_learner is null or i.learner_id=target_learner)and(history_item is null or i.id=history_item)and(page_cursor is null or r.id>page_cursor)and"authorization".can_view_person(school,i.learner_id)and(role_name<>'parent'or review.parent_visible)order by r.id
 loop
  begin source:=internal.portfolio_source(row_item.source_model,row_item.evidence_id,role_name='parent');exception when insufficient_privilege then continue;end;
  count_rows:=count_rows+1;result:=result||jsonb_build_array(source||jsonb_build_object('id',row_item.id,'revisionId',row_item.revision_id,'revision',row_item.revision,'learnerId',row_item.learner_id,'sourceModel',row_item.source_model,'title',row_item.title,'reflection',row_item.reflection,'createdAt',row_item.created_at,'feedback',row_item.feedback,'featured',coalesce(row_item.featured,false),'approvalState',case when row_item.feedback is null then'AWAITING_REVIEW'else'REVIEWED'end,'parentVisible',coalesce(row_item.parent_visible,false),'reviewedAt',row_item.reviewed_at));
  exit when count_rows>page_limit;
 end loop;
 if octet_length(result::text)>500000 then raise exception 'Portfolio page requires smaller view'using errcode='22023';end if;
 return jsonb_build_object('items',(select coalesce(jsonb_agg(item),'[]'::jsonb)from jsonb_array_elements(result)with ordinality value(item,ordinal)where ordinal<=page_limit),'nextCursor',case when count_rows>page_limit then result->(page_limit-1)->>'revisionId'else null end);
end$$;
do $$declare tab text;begin
 foreach tab in array array['portfolio_items','portfolio_revisions','portfolio_reviews','portfolio_current','portfolio_parent_revocations','recognition_policies','recognition_periods','xp_ledger','learner_achievements','leaderboard_participation']loop execute format('alter table app.%I enable row level security',tab);execute format('alter table app.%I force row level security',tab);execute format('revoke all on app.%I from public,anon,authenticated,service_role,cuevo_api,cuevo_worker',tab);end loop;
 foreach tab in array array['portfolio_items','portfolio_revisions','portfolio_reviews','portfolio_parent_revocations','recognition_policies','recognition_periods','xp_ledger','learner_achievements']loop execute format('create trigger immutable_history before update or delete on app.%I for each row execute function internal.academic_history_immutable()',tab);execute format('create trigger immutable_truncate before truncate on app.%I for each statement execute function internal.academic_history_immutable()',tab);end loop;
end$$;
-- Private source functions are the only read/write surface, so no raw table privilege is granted.
revoke execute on function internal.portfolio_source(text,uuid,boolean),internal.portfolio_command(text,uuid,jsonb,text,text,text),internal.read_portfolio_page(integer,uuid,uuid,uuid),internal.recognition_enabled(uuid,boolean),internal.current_period_scope(uuid,uuid),internal.award_recognition_observation(uuid,uuid,uuid),internal.process_recognition_event(uuid,uuid),internal.development_command(text,jsonb,text,text,text),internal.development_read(text,jsonb)from public,anon,authenticated,service_role,cuevo_api,cuevo_worker;
grant execute on function internal.portfolio_command(text,uuid,jsonb,text,text,text),internal.read_portfolio_page(integer,uuid,uuid,uuid),internal.development_command(text,jsonb,text,text,text),internal.development_read(text,jsonb)to cuevo_api;
grant execute on function internal.process_recognition_event(uuid,uuid)to cuevo_worker;
commit;

