-- Deterministic source-linked projections; observed behavior never changes academic results.
begin;
create table app.learner_state_policies(school_id uuid primary key references app.schools(id),development_window_days integer not null check(development_window_days between 1 and 365),version integer not null check(version>0),approved_by uuid not null,foreign key(school_id,approved_by)references app.memberships(school_id,actor_id));
create table app.habit_observations(school_id uuid not null,id uuid not null default gen_random_uuid(),learner_id uuid not null,kind text not null check(kind in('practice','reflection')),source_type text not null default 'ACTIVITY_COMPLETION'check(source_type='ACTIVITY_COMPLETION'),source_object_id uuid not null,occurred_at timestamptz not null,source_event_id uuid not null references internal.outbox_events(id),primary key(school_id,id),unique(school_id,source_object_id,kind),foreign key(school_id,learner_id)references app.memberships(school_id,actor_id),foreign key(school_id,source_object_id)references app.activity_completions(school_id,id));
create table app.learner_state_snapshots(school_id uuid not null,learner_id uuid not null,version integer not null,generated_at timestamptz not null default clock_timestamp(),academic jsonb not null,development jsonb not null,engagement jsonb not null,support jsonb not null,impact jsonb not null,source_event_ids uuid[]not null,primary key(school_id,learner_id),foreign key(school_id,learner_id)references app.memberships(school_id,actor_id),check(jsonb_typeof(academic)='array'and jsonb_typeof(development)='object'));
create table app.learner_signals(school_id uuid not null,id uuid not null default gen_random_uuid(),learner_id uuid not null,type text not null default 'practice_observed'check(type='practice_observed'),count integer not null check(count>0),rule_version integer not null,window_start timestamptz not null,window_end timestamptz not null,source_event_ids uuid[]not null,observation_ids uuid[]not null,created_at timestamptz not null default clock_timestamp(),primary key(school_id,id),unique(school_id,learner_id,type),foreign key(school_id,learner_id)references app.memberships(school_id,actor_id));
create table internal.processed_events(event_id uuid primary key references internal.outbox_events(id),school_id uuid not null references app.schools(id),source_type text,source_id uuid,processed_at timestamptz not null default clock_timestamp(),unique(school_id,source_type,source_id));
create function internal.process_learner_event(target_event uuid,current_lease uuid)returns jsonb language plpgsql security definer set search_path='' as $$
declare e internal.outbox_events;r app.result_revisions;c app.activity_completions;a app.activities;p app.learner_state_policies;learner uuid;source_kind text;source_id uuid;obs uuid;start_at timestamptz;academic_rows jsonb;development_state jsonb;engagement_state jsonb;events uuid[];count_practice integer;count_reflection integer;ids_practice uuid[];ids_reflection uuid[];completed integer;last_completed timestamptz;signal_id uuid;
begin
 select *into e from internal.outbox_events where id=target_event for update;
 if not found or e.state<>'PROCESSING'or e.lease_token is distinct from current_lease or e.lease_until<=clock_timestamp()then raise exception 'Invalid event lease'using errcode='22023';end if;
 if exists(select 1 from internal.processed_events where event_id=e.id)then perform internal.complete_outbox(e.id,current_lease);return jsonb_build_object('status','DUPLICATE');end if;
 if e.type='result.released'then
  select *into r from app.result_revisions where school_id=e.school_id and id=e.entity_id;
  if not found or e.entity_type<>'result'or e.actor_id<>r.created_by or not exists(select 1 from app.academic_evidence ev where ev.school_id=r.school_id and ev.id=r.evidence_id and ev.result_id=r.id and ev.learner_id=r.learner_id and ev.source_object_id=r.submission_id)then raise exception 'Invalid released source'using errcode='22023';end if;
  learner:=r.learner_id;source_kind:='RESULT';source_id:=r.id;
 elsif e.type='activity.complete'then
  select *into c from app.activity_completions where school_id=e.school_id and id=e.entity_id;
  if not found or e.actor_id<>c.learner_id or e.entity_type<>'activity'then raise exception 'Invalid completion source'using errcode='22023';end if;
  select *into a from app.activities where school_id=c.school_id and id=c.activity_id;learner:=c.learner_id;source_kind:='COMPLETION';source_id:=c.id;
 elsif e.type in('course.create','course.publish','unit.create','lesson.create','activity.create','assessment.create','submission.create','reference.create','reference.approve','assessment.reference','assessment.marked','learner_state.updated','habit.observed','school.updated')then
  insert into internal.processed_events(event_id,school_id)values(e.id,e.school_id);perform internal.complete_outbox(e.id,current_lease);return jsonb_build_object('status','ACKNOWLEDGED');
 else raise exception 'Unsupported domain event'using errcode='22023';end if;
 if exists(select 1 from internal.processed_events where school_id=e.school_id and source_type=source_kind and source_id=source_id)then insert into internal.processed_events(event_id,school_id)values(e.id,e.school_id);perform internal.complete_outbox(e.id,current_lease);return jsonb_build_object('status','DUPLICATE_SOURCE');end if;
 if not exists(select 1 from app.schools where id=e.school_id and status='active')or not exists(select 1 from app.entitlements where school_id=e.school_id and code='learner.state'and enabled and effective_from<=now()and(effective_to is null or effective_to>now()))then raise exception 'Learner state policy unavailable'using errcode='42501';end if;
 select *into p from app.learner_state_policies where school_id=e.school_id;if not found then raise exception 'Approved development window required'using errcode='22023';end if;
 perform pg_advisory_xact_lock(hashtextextended(e.school_id::text||':learner:'||learner::text,0));
 if source_kind='COMPLETION'and a.kind in('practice','reflection')then
  insert into app.habit_observations(school_id,learner_id,kind,source_object_id,occurred_at,source_event_id)values(e.school_id,learner,a.kind,c.id,c.completed_at,e.id)on conflict(school_id,source_object_id,kind)do nothing returning id into obs;
 end if;
 insert into internal.processed_events(event_id,school_id,source_type,source_id)values(e.id,e.school_id,source_kind,source_id);
 start_at:=clock_timestamp()-make_interval(days=>p.development_window_days);
 select coalesce(jsonb_agg(jsonb_build_object('resultId',rr.id,'referenceId',rr.reference_id,'referenceVersion',rr.reference_version,'nativeResult',jsonb_build_object('type','numeric','score',rr.score,'maxScore',rr.max_score,'policyVersion',rr.policy_version,'normalized',null),'evidenceId',rr.evidence_id,'observedAt',rr.created_at)order by rr.created_at),'[]'::jsonb)into academic_rows from app.current_results cr join app.result_revisions rr on rr.school_id=cr.school_id and rr.id=cr.result_id where cr.school_id=e.school_id and cr.learner_id=learner;
 select count(*)filter(where kind='practice'),count(*)filter(where kind='reflection'),coalesce(array_agg(id)filter(where kind='practice'),array[]::uuid[]),coalesce(array_agg(id)filter(where kind='reflection'),array[]::uuid[])into count_practice,count_reflection,ids_practice,ids_reflection from app.habit_observations where school_id=e.school_id and learner_id=learner and occurred_at>=start_at;
 select count(*),max(completed_at)into completed,last_completed from app.activity_completions where school_id=e.school_id and learner_id=learner;
 -- Counts reflect persisted records in an approved window, not psychological or attainment labels.
 development_state:=jsonb_build_object('practice',jsonb_build_object('count',count_practice,'observationIds',ids_practice),'reflection',jsonb_build_object('count',count_reflection,'observationIds',ids_reflection),'revision',jsonb_build_object('count',null,'observationIds',array[]::uuid[]),'windowStart',start_at,'windowEnd',clock_timestamp());
 engagement_state:=jsonb_build_object('completedActivityCount',completed,'lastCompletedAt',last_completed);
 select coalesce(array_agg(event_id order by processed_at),array[]::uuid[])into events from internal.processed_events where school_id=e.school_id and source_type in('RESULT','COMPLETION')and((source_type='RESULT'and source_id in(select id from app.result_revisions where school_id=e.school_id and learner_id=learner))or(source_type='COMPLETION'and source_id in(select id from app.activity_completions where school_id=e.school_id and learner_id=learner)));
 insert into app.learner_state_snapshots(school_id,learner_id,version,academic,development,engagement,support,impact,source_event_ids)values(e.school_id,learner,1,academic_rows,development_state,engagement_state,'{"activeInterventionIds":[]}','{"status":"unmeasured","measurementIds":[]}',events)on conflict(school_id,learner_id)do update set version=app.learner_state_snapshots.version+1,generated_at=clock_timestamp(),academic=excluded.academic,development=excluded.development,engagement=excluded.engagement,source_event_ids=excluded.source_event_ids;
 if count_practice>0 then insert into app.learner_signals(school_id,learner_id,count,rule_version,window_start,window_end,source_event_ids,observation_ids)values(e.school_id,learner,count_practice,p.version,start_at,clock_timestamp(),events,ids_practice)on conflict(school_id,learner_id,type)do update set count=excluded.count,window_start=excluded.window_start,window_end=excluded.window_end,source_event_ids=excluded.source_event_ids,observation_ids=excluded.observation_ids,created_at=clock_timestamp()returning id into signal_id;end if;
 insert into internal.outbox_events(school_id,actor_id,type,entity_type,entity_id,version,metadata,deduplication_key)values(e.school_id,e.actor_id,'learner_state.updated','learner',learner,1,jsonb_build_object('learnerId',learner),'state:'||e.id::text)on conflict(school_id,deduplication_key)do nothing;
 if obs is not null then insert into internal.outbox_events(school_id,actor_id,type,entity_type,entity_id,version,metadata,deduplication_key)values(e.school_id,e.actor_id,'habit.observed','observation',obs,1,jsonb_build_object('learnerId',learner),'habit:'||e.id::text)on conflict(school_id,deduplication_key)do nothing;end if;
 perform internal.complete_outbox(e.id,current_lease);return jsonb_build_object('status','PROCESSED','learnerId',learner);
end$$;
create function internal.worker_health()returns jsonb language sql security definer set search_path=''as $$select jsonb_build_object('ready',exists(select 1 from pg_roles where rolname=session_user and not rolsuper and not rolbypassrls)and has_function_privilege(session_user,'internal.process_learner_event(uuid,uuid)','EXECUTE'),'pendingCount',(select count(*)from internal.outbox_events where state='PENDING'),'failedCount',(select count(*)from internal.outbox_events where state='FAILED'),'oldestPendingAt',(select min(occurred_at)from internal.outbox_events where state='PENDING'))$$;
do $$declare tab text;begin foreach tab in array array['learner_state_policies','habit_observations','learner_state_snapshots','learner_signals']loop execute format('alter table app.%I enable row level security',tab);execute format('alter table app.%I force row level security',tab);end loop;end$$;
alter table internal.processed_events enable row level security;alter table internal.processed_events force row level security;
create policy state_read on app.learner_state_snapshots for select to cuevo_api using("authorization".can_view_person(school_id,learner_id)and"authorization".has_entitlement(school_id,'learner.state')and"authorization".current_role(school_id)<>'parent');
create policy observation_read on app.habit_observations for select to cuevo_api using("authorization".can_view_person(school_id,learner_id)and"authorization".has_entitlement(school_id,'learner.state')and"authorization".current_role(school_id)<>'parent');
create policy signal_read on app.learner_signals for select to cuevo_api using("authorization".can_view_person(school_id,learner_id)and"authorization".has_entitlement(school_id,'learner.state')and"authorization".current_role(school_id)<>'parent');
revoke all on app.learner_state_policies,app.habit_observations,app.learner_state_snapshots,app.learner_signals,internal.processed_events from public,anon,authenticated,service_role,cuevo_api,cuevo_worker;
grant select on app.habit_observations,app.learner_state_snapshots,app.learner_signals to cuevo_api;
revoke execute on function internal.process_learner_event(uuid,uuid),internal.worker_health()from public,anon,authenticated,service_role,cuevo_api;
grant execute on function internal.process_learner_event(uuid,uuid),internal.worker_health()to cuevo_worker;
commit;
