begin;
create function internal.curriculum_programme_readable(target_programme uuid)returns boolean language sql stable security definer set search_path=''as $$
 select coalesce("authorization".can_access_school("authorization".school_id())and"authorization".has_entitlement("authorization".school_id(),'curriculum')and"authorization".current_role("authorization".school_id())in('admin','coordinator','teacher')and exists(
  select 1 from app.programme_instances programme join app.classes class on class.school_id=programme.school_id and class.id=programme.class_id join app.curriculum_versions version on version.school_id=programme.school_id and version.id=programme.pack_version_id
  where programme.school_id="authorization".school_id()and programme.id=target_programme and class.status='active'and"authorization".can_view_class(programme.school_id,programme.class_id)and version.synthetic and version.source_status='VERIFIED'and version.rights_status='PERMITTED'
  and("authorization".current_role(programme.school_id)in('admin','coordinator')or exists(select 1 from app.teacher_assignments assignment where assignment.school_id=programme.school_id and assignment.class_id=programme.class_id and assignment.subject_id=programme.subject_id and assignment.teacher_actor_id="authorization".actor_id()and assignment.status='active'and assignment.effective_from<=now()and(assignment.effective_to is null or assignment.effective_to>now())))),false)
$$;
create function internal.curriculum_programme_projection(target_programme uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare result jsonb;begin
 if not internal.curriculum_programme_readable(target_programme)then raise exception 'Current curriculum programme scope denied'using errcode='42501';end if;
 select jsonb_build_object('id',programme.id,'packVersionId',programme.pack_version_id,'name',programme.name,'classId',programme.class_id,'className',class.name,'subjectId',programme.subject_id,'subjectName',subject.name,'yearGroupId',programme.year_group_id,'yearGroupName',year_group.name,'academicYearName',academic_year.name,'framework',version.framework,'packProgramme',version.programme,'packVersion',version.version)into result
 from app.programme_instances programme join app.classes class on class.school_id=programme.school_id and class.id=programme.class_id join app.subjects subject on subject.school_id=programme.school_id and subject.id=programme.subject_id join app.year_groups year_group on year_group.school_id=programme.school_id and year_group.id=programme.year_group_id join app.academic_years academic_year on academic_year.school_id=class.school_id and academic_year.id=class.academic_year_id join app.curriculum_versions version on version.school_id=programme.school_id and version.id=programme.pack_version_id where programme.school_id="authorization".school_id()and programme.id=target_programme;
 return result;
end$$;
create function internal.read_curriculum_programmes(page_limit integer,page_cursor uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();rows jsonb;begin
 if not"authorization".can_access_school(school)or not"authorization".has_entitlement(school,'curriculum')or"authorization".current_role(school)is null or"authorization".current_role(school)not in('admin','coordinator','teacher')then raise exception 'Current curriculum staff scope required'using errcode='42501';end if;
 if page_limit is null or page_limit not between 1 and 100 then raise exception 'Bounded programme page required'using errcode='22023';end if;
 select coalesce(jsonb_agg(internal.curriculum_programme_projection(candidate.id)order by candidate.id),'[]'::jsonb)into rows from(select programme.id from app.programme_instances programme where programme.school_id=school and(page_cursor is null or programme.id>page_cursor)and internal.curriculum_programme_readable(programme.id)order by programme.id limit page_limit+1)candidate;
 if octet_length(rows::text)>250000 then raise exception 'Programme context requires smaller page'using errcode='22023';end if;
 return jsonb_build_object('items',case when jsonb_array_length(rows)>page_limit then rows-page_limit else rows end,'nextCursor',case when jsonb_array_length(rows)>page_limit then rows->(page_limit-1)->>'id'else null end);
end$$;
create function internal.read_curriculum_programme_learners(target_programme uuid,page_limit integer,page_cursor uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare school uuid:="authorization".school_id();programme app.programme_instances;rows jsonb;begin
 if not internal.curriculum_programme_readable(target_programme)then raise exception 'Current programme assignment scope denied'using errcode='42501';end if;
 if page_limit is null or page_limit not between 1 and 100 then raise exception 'Bounded assignment page required'using errcode='22023';end if;
 select*into programme from app.programme_instances where school_id=school and id=target_programme;
 with admitted as materialized(select assignment.*from app.programme_learners assignment join app.memberships member on member.school_id=assignment.school_id and member.actor_id=assignment.learner_id join app.enrollments enrollment on enrollment.school_id=assignment.school_id and enrollment.student_actor_id=assignment.learner_id and enrollment.class_id=programme.class_id
  where assignment.school_id=school and assignment.programme_id=target_programme and(page_cursor is null or assignment.learner_id>page_cursor)and member.role='student'and member.status='active'and member.effective_from<=now()and(member.effective_to is null or member.effective_to>now())and enrollment.status='active'and enrollment.effective_from<=now()and(enrollment.effective_to is null or enrollment.effective_to>now())and"authorization".can_view_person(school,assignment.learner_id)order by assignment.learner_id limit page_limit+1)
 select coalesce(jsonb_agg(jsonb_build_object('id',assignment.learner_id,'programmeId',assignment.programme_id,'learnerId',assignment.learner_id,'learnerName',learner.display_name,'status',assignment.status,'approvedByName',approver.display_name,'updatedAt',assignment.updated_at)order by assignment.learner_id),'[]'::jsonb)into rows from admitted assignment join app.people learner on learner.school_id=assignment.school_id and learner.actor_id=assignment.learner_id join app.people approver on approver.school_id=assignment.school_id and approver.actor_id=assignment.approved_by;
 if octet_length(rows::text)>250000 then raise exception 'Programme assignment context requires smaller page'using errcode='22023';end if;
 return jsonb_build_object('programme',internal.curriculum_programme_projection(target_programme),'items',case when jsonb_array_length(rows)>page_limit then rows-page_limit else rows end,'nextCursor',case when jsonb_array_length(rows)>page_limit then rows->(page_limit-1)->>'id'else null end);
end$$;
revoke execute on function internal.curriculum_programme_readable(uuid),internal.curriculum_programme_projection(uuid),internal.read_curriculum_programmes(integer,uuid),internal.read_curriculum_programme_learners(uuid,integer,uuid)from public,anon,authenticated,service_role,cuevo_api,cuevo_worker;
grant execute on function internal.read_curriculum_programmes(integer,uuid),internal.read_curriculum_programme_learners(uuid,integer,uuid)to cuevo_api;
commit;
