'use client';
import{useState}from'react';import{Button,Status}from'@cuevo/ui';
import{intelligenceRunStatusSchema}from'@cuevo/contracts';import{useApp}from'../../../shared/session/providers';import{usePaginatedLearningQuery}from'../../../shared/hooks/use-paginated-query';import{LearningError}from'../../../shared/components/feedback';import{LoadMore}from'../../../shared/components/load-more';
const parseRun=(value:unknown)=>intelligenceRunStatusSchema.parse(value);
export function IntelligenceRunStatusPanel({refreshKey=0}:{refreshKey?:number}={}){
 const{locale}=useApp();const ar=locale==='ar';const[refresh,setRefresh]=useState(0);const runs=usePaginatedLearningQuery('/v1/intelligence/runs?limit=25',parseRun,refresh+refreshKey);
 const status={REASONING:ar?'التحليل قيد التنفيذ':'Analysis in progress',PROPOSAL_READY:ar?'المقترح جاهز للمراجعة البشرية':'Proposal ready for human review',FAILED:ar?'لم يكتمل التحليل':'Analysis did not complete'};
 return <section aria-label={ar?'حالة التحليلات':'Analysis run status'}><header className="cuevo-section-header"><div className="cuevo-section-header__context"><h2>{ar?'حالة التحليلات':'Analysis run status'}</h2><p>{ar?'لا تؤدي مراجعة الحالة إلى إعادة طلب النموذج. تُغلق المهلة المنتهية بإيصال فشل محفوظ؛ اطلب محاولة جديدة فقط بعد مراجعة المصدر والسياسة.':'Checking status does not retry the model. Expired attempts close with a durable failure receipt; request a new analysis only after reviewing source and policy.'}</p></div><Button type="button" variant="quiet" onClick={()=>setRefresh(value=>value+1)}>{ar?'تحديث حالة التحليلات':'Refresh analysis status'}</Button></header>{runs.loading?<p role="status">{ar?'جارٍ التحقق من الحالة…':'Checking run status…'}</p>:runs.error?<LearningError error={runs.error}/>:runs.data.map(run=><article key={run.id} data-intelligence-run-id={run.id}><h3>{run.assessmentTitle}</h3><p><bdi>{run.learnerName}</bdi></p><Status tone={run.state==='FAILED'?'warning':'neutral'}>{status[run.state]}</Status>{run.state==='FAILED'?<p>{ar?'راجع المصدر والسياسة ثم اطلب تحليلاً جديدًا بشكل صريح. لم يُنشأ تدريب تلقائيًا.':'Review source and policy, then explicitly request a new analysis. No practice was assigned automatically.'}</p>:null}<p>{ar?'تكلفة الفاتورة مجهولة؛ المبلغ المحجوز ليس تكلفة فعلية.':'Billed cost is unknown; reserved budget is not actual spend.'}</p><details><summary>{ar?'تفاصيل التشغيل':'Run details'}</summary><p><bdi>{run.id}</bdi></p><p>{run.provider} · {run.model} · {run.generationMode}</p>{run.failureCode?<p>{run.failureCode}</p>:null}<p>{ar?'مبلغ محجوز':'Reserved budget'}: {run.reservedBudget}</p></details></article>)}{!runs.loading&&!runs.error&&!runs.data.length?<p>{ar?'لا توجد تحليلات ضمن مصادرك الحالية المسموحة.':'No runs are available under your current authorized sources.'}</p>:null}<LoadMore query={runs}/></section>;
}
