'use client';
import { useCallback, useState,useSyncExternalStore } from 'react';
import { approvedPracticeChoiceOptions, currentImprovementRead, improvementReadScope, parseCurrentInterventionChoices, validateInterventionChoiceReceipt } from '../model';
import { useApp } from '../../../shared/session/providers';
import { useApiQuery } from '../../../shared/hooks/use-api';
import { CommandForm } from '../../../shared/components/command-form';
import { LearningError } from '../../../shared/components/feedback';

export function InterventionTaskChoices({ interventionId, canChoose, canRecover=canChoose }: { interventionId: string; canChoose: boolean;canRecover?:boolean }) {
  const app=useApp();const { locale } = app; const ar = locale === 'ar'; const [refresh, setRefresh] = useState(0);const path=`/v1/interventions/${interventionId}/choices`;const scope=improvementReadScope(app,path,refresh);
  useSyncExternalStore(app.commandJournal.subscribe,app.commandJournal.getSnapshot,app.commandJournal.getSnapshot);
  const original=app.commandJournal.get(path);
  const parse=useCallback((value:unknown)=>({scope,value:parseCurrentInterventionChoices(value,interventionId)}),[scope,interventionId]);const read=useApiQuery(scope?path:null,parse,refresh);const current={...read,data:currentImprovementRead(read.data,scope)};
  if (current.loading||!current.error&&!current.data) return <p role="status">{ar ? 'جارٍ تحميل التدريب المعتمد…' : 'Loading approved practices…'}</p>;
  if (current.error) return <LearningError error={current.error} />;
  if (!current.data) return null;
  const { options, choice } = current.data;const selectable=approvedPracticeChoiceOptions(current.data);
  const ambiguous=options.some(option=>option.available&&!selectable.some(candidate=>candidate.value===option.activityId));
  return <section className="support-task-choices" aria-label={ar ? 'خيارات التدريب المعتمدة' : 'Approved practice choices'}><h3>{ar ? 'خيارات التدريب المعتمدة' : 'Approved practice choices'}</h3>{choice ? <><p>{ar ? 'التدريب الذي اخترته' : 'Your selected practice'}: {choice.title}</p><p className="lesson-content">{choice.instructions}</p><p>{ar ? 'اختيارك محفوظ. أكمل هذا التدريب قبل تأكيد الإنجاز.' : 'Your choice is recorded. Complete this practice before confirming completion.'}</p></> : options.length ? <><p>{ar ? 'اعتمد المعلّم هذه التدريبات للهدف نفسه. اختر واحدًا فقط، أو استخدم المهمة الأصلية.' : 'Your teacher approved these practices for the same objective. Choose one, or use the original task.'}</p>{options.map(option => <article key={option.activityId}><h4>{option.title}</h4><p>{option.instructions}</p>{!option.available ? <p className="notice">{ar ? 'يتطلب هذا المصدر مراجعة المعلّم.' : 'This source requires teacher review.'}</p> : null}</article>)}{ambiguous?<p className="notice">{ar?'تحتاج عناوين الخيارات إلى مراجعة المعلّم قبل الاختيار.':'The option titles need teacher review before you can choose.'}</p>:null}{canChoose && selectable.length>0 ? <CommandForm title={ar ? 'اختيار تدريب معتمد' : 'Choose approved practice'} path={`/v1/interventions/${interventionId}/choices`} fields={[{ name: 'activityId', label: ar ? 'التدريب المعتمد' : 'Approved practice', type: 'select', required: true, options: selectable }, { name: 'confirmChoice', label: ar ? 'أؤكد اختيار هذا التدريب للمهمة' : 'I confirm this practice for my task', type: 'checkbox', required: true }]} body={values => ({ activityId: String(values.get('activityId')), confirmChoice: values.get('confirmChoice') === 'on' })} validateReceipt={(receipt,command)=>validateInterventionChoiceReceipt(receipt,interventionId,command.body)} onSaved={() => setRefresh(value => value + 1)} /> : null}</> : <p>{ar ? 'لم تُعتمد خيارات بديلة لهذه المهمة.' : 'No alternative practices were approved for this task.'}</p>}{original&&choice&&canRecover?<CommandForm title={ar?'التحقّق من الاختيار الأصلي':'Check original practice choice'} path={path} fields={[]} body={()=>{throw new Error('Original choice only');}} validateReceipt={(receipt,command)=>validateInterventionChoiceReceipt(receipt,interventionId,command.body)} onSaved={()=>setRefresh(value=>value+1)}/>:null}</section>;
}
