import {createHash} from 'node:crypto';
import {z} from 'zod';
import {canonicalReleaseExecutionJson} from './release-review';
import {Client} from 'pg';
import {checkServerIdentity,type TLSSocket} from 'node:tls';
import {readBackendReleaseAdmission} from './backend-release-admission';
import {validatePreparedBackendReleaseIntent,type BackendReleaseExpected} from './backend-release-contracts';
import {prepareHostedRuntimeRecipients} from './backend-provider-deploy';
import {readHostedMigrationProvider,requireCurrentHostedMigrationEndpoint} from '../database/hosted-migration-provider';
import {initialRuntimeRolesSql} from '../database/hosted-runtime-role-membership';
import {providerDeploymentStateSchema,providerStateSha256} from '../database/hosted-provider-state';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';

const sha=z.string().regex(/^[a-f0-9]{40}$/),digest=z.string().regex(/^[a-f0-9]{64}$/),id=z.string().regex(/^[1-9][0-9]*$/),positive=z.number().int().positive().max(Number.MAX_SAFE_INTEGER),timestamp=z.iso.datetime({offset:true}),ref=z.string().regex(/^[a-z]{20}$/);
const fail=()=>Error('Installed active runtime requires original native evidence and fresh approval; contents withheld.');
const hash=(value:unknown)=>createHash('sha256').update(canonicalReleaseExecutionJson(value)).digest('hex');
const identitySchema=z.object({sourceSha:sha,treeSha:sha,originalRunId:id,originalRunAttempt:positive,originalPackageSha256:digest,runtimeSha256:digest,apiDeploymentId:z.string().regex(/^dpl_[A-Za-z0-9]+$/),apiUrl:z.string().url(),edgeId:z.string().min(1).max(200),edgeVersion:positive,activationId:z.uuid(),vaultSecretName:z.string().regex(/^cuevo_worker_[a-f0-9]{32}$/),endpoint:z.string().url(),createdAt:timestamp}).strict();
const activationSchema=z.object({status:z.literal('ACTIVATED_SIGNED_SOURCE_VERIFIED'),sourceSha:sha,projectRef:ref,runId:id,runAttempt:positive,packageSha256:digest,runtimeSha256:digest,apiDeploymentId:z.string(),edgeVersion:positive,jobId:positive,sourceProcessed:z.literal(true),duplicateWakeDenied:z.literal(true),originalCommandReplayed:z.literal(true),recoveryScheduled:z.literal(true),scheduledRecoveryVerified:z.literal(true),configurationEvidenceObservedManual:z.literal(true),sessionsClosed:z.literal(true),keyOperation:z.literal('CONFIRMED'),dispatchOperation:z.literal('CONFIRMED'),probeEventId:z.uuid(),observedAt:timestamp}).passthrough();
const cleanupSchema=z.object({purpose:z.literal('CUEVO_HOSTED_WORKER_ACTIVATION_CLEANUP').optional(),status:z.literal('ACTIVATED_SIGNED_SOURCE_VERIFIED'),sourceSha:sha,projectRef:ref,runId:id,runAttempt:positive,lockReleased:z.literal(true),sessionsClosed:z.literal(true),resultSha256:digest,observedAt:timestamp}).strict();
const common=z.object({version:z.literal(1),purpose:z.literal('CUEVO_PRIVATE_ACTIVE_RUNTIME_STATE'),projectRef:ref,phase:z.enum(['INTENT','CONFIGURED','CONFIRMED','REQUIRES_REVIEW']),identity:identitySchema,jobId:positive.nullable(),activation:activationSchema.nullable(),cleanup:cleanupSchema.nullable()}).strict();
export const activeRuntimeStateSchema=common.extend({wakeKey:digest,runtimeConfig:z.unknown().optional()}).strict();
export type ActiveRuntimeState=z.infer<typeof activeRuntimeStateSchema>;
export function activeRuntimePublicQuery(projectRef:string){ref.parse(projectRef);return `/* CUEVO_INSTALLED_ACTIVE_RUNTIME */ select (decrypted_secret::jsonb-'wakeKey'-'runtimeConfig') as state from vault.decrypted_secrets where name='cuevo_active_runtime_${projectRef}'`;}

function terminal(state:z.infer<typeof common>){
 const a=state.activation,c=state.cleanup,i=state.identity;
 if(state.phase!=='CONFIRMED'||!a||!c||state.jobId!==a.jobId||a.sourceSha!==i.sourceSha||a.projectRef!==state.projectRef||a.runId!==i.originalRunId||a.runAttempt!==i.originalRunAttempt||a.packageSha256!==i.originalPackageSha256||a.runtimeSha256!==i.runtimeSha256||a.apiDeploymentId!==i.apiDeploymentId||a.edgeVersion!==i.edgeVersion||c.sourceSha!==i.sourceSha||c.projectRef!==state.projectRef||c.runId!==i.originalRunId||c.runAttempt!==i.originalRunAttempt||c.resultSha256!==hash(a)||Date.parse(a.observedAt)<Date.parse(i.createdAt)||Date.parse(c.observedAt)<Date.parse(a.observedAt)||i.endpoint!==`https://${state.projectRef}.supabase.co/functions/v1/cuevo-worker`||i.vaultSecretName!=='cuevo_worker_'+i.activationId.replaceAll('-','')||!/^https:\/\/[a-z0-9-]+\.vercel\.app$/.test(i.apiUrl))throw fail();
}

/** Public package metadata contains hashes and original identities only. */
export function readInstalledRuntimeMetadata(value:unknown,projectRef:string){
 try{const rows=z.array(z.object({state:common}).strict()).length(1).parse(JSON.parse(canonicalReleaseExecutionJson(value))),state=rows[0].state;if(state.projectRef!==projectRef)throw fail();terminal(state);const{createdAt:_createdAt,...identity}=state.identity;void _createdAt;return{version:1 as const,purpose:'CUEVO_INSTALLED_ACTIVE_RUNTIME' as const,...identity,jobId:state.jobId!,activationReceiptSha256:hash(state.activation)};}catch{throw fail();}
}

export function validateActiveRuntimeTransition(beforeValue:unknown|null,afterValue:unknown,projectRef:string):ActiveRuntimeState{
 try{const after=activeRuntimeStateSchema.parse(JSON.parse(canonicalReleaseExecutionJson(afterValue)));if(after.projectRef!==projectRef)throw fail();if(beforeValue===null){if(after.phase!=='INTENT'||after.jobId!==null||after.activation!==null||after.cleanup!==null)throw fail();return after;}
 const before=activeRuntimeStateSchema.parse(JSON.parse(canonicalReleaseExecutionJson(beforeValue)));if(before.projectRef!==projectRef||hash(before.identity)!==hash(after.identity)||before.wakeKey!==after.wakeKey||hash(before.runtimeConfig??null)!==hash(after.runtimeConfig??null))throw fail();
 if(before.phase===after.phase){if(hash(before)!==hash(after))throw fail();return after;}
 if(before.phase==='INTENT'&&after.phase==='CONFIGURED'){if(!after.activation||!after.jobId||after.cleanup!==null)throw fail();}
 else if(before.phase==='CONFIGURED'&&after.phase==='CONFIRMED'){terminal(after);if(hash(before.activation)!==hash(after.activation)||before.jobId!==after.jobId)throw fail();}
 else if(!['INTENT','CONFIGURED'].includes(before.phase)||after.phase!=='REQUIRES_REVIEW')throw fail();return after;
 }catch{throw fail();}
}

async function readJson(url:string,token:string){const signal=AbortSignal.timeout(10000),response=await fetch(url,{method:'GET',headers:{Authorization:'Bearer '+token},redirect:'error',credentials:'omit',cache:'no-store',signal});if(response.status!==200||response.redirected||response.url&&response.url!==url||!response.body)throw fail();const declared=response.headers.get('content-length');if(declared!==null&&(!/^\d+$/.test(declared)||Number(declared)>131072))throw fail();const reader=response.body.getReader(),parts:Uint8Array[]=[];let bytes=0;try{for(;;){const value=await new Promise<ReadableStreamReadResult<Uint8Array>>((done,reject)=>{const abort=()=>{signal.removeEventListener('abort',abort);reject(fail());};if(signal.aborted)return abort();signal.addEventListener('abort',abort,{once:true});void reader.read().then(value=>{signal.removeEventListener('abort',abort);if(signal.aborted)reject(fail());else done(value);},()=>{signal.removeEventListener('abort',abort);reject(fail());});});if(value.done)break;bytes+=value.value.length;if(bytes>131072)throw fail();parts.push(value.value);}return JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(Buffer.concat(parts))) as unknown;}finally{void reader.cancel().catch(()=>undefined);try{reader.releaseLock();}catch{/* Cancellation owns cleanup. */}}}
export type ActiveRuntimeRevalidation={status:'INSTALLED_RUNTIME_REVALIDATED'|'REQUIRES_REVIEW';purpose:'CUEVO_ACTIVE_RUNTIME_CONTINUATION';sourceSha:string|null;runId:string|null;runAttempt:number|null;packageSha256:string|null;original:ReturnType<typeof readInstalledRuntimeMetadata>|null;activation:unknown|null;cleanup:unknown|null;observedAt:string;nativeExecutionVerified:boolean;lockReleased:boolean;hostedAcceptance:false};

/** Fixed GET/native observation, authenticated operator TLS and a live lock.
 * It never recreates a key, deploys a provider, disables dispatch or awards work. */
export async function revalidateActiveRuntime(value:unknown):Promise<ActiveRuntimeRevalidation>{
 const result:ActiveRuntimeRevalidation={status:'REQUIRES_REVIEW',purpose:'CUEVO_ACTIVE_RUNTIME_CONTINUATION',sourceSha:null,runId:null,runAttempt:null,packageSha256:null,original:null,activation:null,cleanup:null,observedAt:new Date().toISOString(),nativeExecutionVerified:false,lockReleased:false,hostedAcceptance:false};let client:Client|undefined,locked=false,lost=false,ending=false,lockKey='';
 try{
  const input=z.object({repoRoot:z.string(),expected:z.unknown(),preparedApproval:z.unknown(),githubToken:z.string().min(1).max(24576),providerToken:z.string().min(20).max(24576),vercelToken:z.string().min(20).max(24576),runtimeConfig:z.unknown(),operatorDatabaseUrl:z.string(),operatorPassword:z.string().min(1).max(4096)}).strict().parse(JSON.parse(canonicalReleaseExecutionJson(value))),expected=input.expected as BackendReleaseExpected;
  const installed=z.object({version:z.literal(1),purpose:z.literal('CUEVO_INSTALLED_ACTIVE_RUNTIME'),sourceSha:sha,treeSha:sha,originalRunId:id,originalRunAttempt:positive,originalPackageSha256:digest,runtimeSha256:digest,apiDeploymentId:z.string(),apiUrl:z.string(),edgeId:z.string(),edgeVersion:positive,activationId:z.uuid(),vaultSecretName:z.string(),jobId:positive,endpoint:z.string(),activationReceiptSha256:digest}).strict().parse((expected as BackendReleaseExpected&{installedRuntime?:unknown}).installedRuntime);
  if(installed.sourceSha!==expected.releaseSha||installed.treeSha!==expected.treeSha)throw fail();const prepared=validatePreparedBackendReleaseIntent(input.preparedApproval,{...expected,now:Date.now()}),runtime=prepareHostedRuntimeRecipients(input.runtimeConfig,expected),project=expected.targets.supabase.projectRef;
  if(runtime.runtimeSha256!==installed.runtimeSha256)throw fail();await readBackendReleaseAdmission({repoRoot:input.repoRoot,expected,prepared,githubToken:input.githubToken});const provider=await readHostedMigrationProvider({projectRef:project,boundProjectRef:project,providerToken:input.providerToken}),url=new URL(input.operatorDatabaseUrl),endpoint=requireCurrentHostedMigrationEndpoint({projectRef:project,kind:url.hostname===`db.${project}.supabase.co`?'direct':'session-pooler',host:url.hostname,port:5432,database:'postgres'},provider,expected.fingerprints.migrationEndpointSha256);
  if(url.protocol!=='postgresql:'||url.password||url.port!=='5432'||url.pathname!=='/postgres'||url.search!=='?sslmode=verify-full'||url.hash||decodeURIComponent(url.username)!==(endpoint.kind==='direct'?'postgres':'postgres.'+project)||provider.observedAtMs>Date.now()||Date.now()-provider.observedAtMs>30000)throw fail();
  client=new Client({host:url.hostname,port:5432,database:'postgres',user:decodeURIComponent(url.username),password:input.operatorPassword,ssl:{rejectUnauthorized:true,ca:runtime.api.CUEVO_DATABASE_TLS_CA,minVersion:'TLSv1.2'},connectionTimeoutMillis:5000,statement_timeout:5000,query_timeout:7000,lock_timeout:2000,application_name:'cuevo-active-runtime-observer'});client.on('error',()=>{if(!ending)lost=true;});client.on('end',()=>{if(!ending)lost=true;});await client.connect();
  const live=()=>{if(!client||lost)throw fail();const stream=client.connection.stream as TLSSocket,peer=stream.getPeerCertificate();if(!stream.encrypted||stream.authorized!==true||!['TLSv1.2','TLSv1.3'].includes(stream.getProtocol()??'')||!peer?.raw?.length||checkServerIdentity(url.hostname,peer))throw fail();};
  const query=async(sql:string,args:unknown[]=[])=>{live();const rows=(await client!.query(sql,args)).rows;live();return rows;};lockKey=project+':HOSTED_SCHEMA_MIGRATION';const lock=await query('select pg_try_advisory_lock(hashtextextended($1,0))as locked',[lockKey]);if(lock.length!==1||lock[0].locked!==true)throw fail();locked=true;
  const read=async()=>{const rows=await query('/* CUEVO_ACTIVE_RUNTIME_READ */ select decrypted_secret from vault.decrypted_secrets where name=$1',['cuevo_active_runtime_'+project]);if(rows.length!==1||typeof rows[0].decrypted_secret!=='string'||Buffer.byteLength(rows[0].decrypted_secret)>49152)throw fail();const state=activeRuntimeStateSchema.parse(JSON.parse(rows[0].decrypted_secret));const publicState=common.parse(Object.fromEntries(Object.entries(state).filter(([key])=>!['wakeKey','runtimeConfig'].includes(key)))),metadata=readInstalledRuntimeMetadata([{state:publicState}],project);if(hash(metadata)!==hash(installed)||state.runtimeConfig!==undefined&&prepareHostedRuntimeRecipients(state.runtimeConfig,expected).runtimeSha256!==runtime.runtimeSha256)throw fail();return state;};
  const original=await read();const source=z.array(z.object({operator:z.literal('postgres'),database:z.literal('postgres'),ssl:z.literal(true),transportPrivate:z.literal(true),synthetic:z.literal(true),currentActors:z.literal(true),runtimeRoles:z.literal(true),analyticsDisabled:z.literal(true)}).strict()).length(1).parse(await query('/* CUEVO_ACTIVE_RUNTIME_SOURCE */ select session_user::text as operator,current_database()::text as database,(select ssl from pg_stat_ssl where pid=pg_backend_pid()) as ssl,internal.worker_transport_private() as "transportPrivate",not exists(select 1 from app.people where synthetic is distinct from true) as synthetic,not exists(select 1 from app.memberships m join app.people p on p.actor_id=m.actor_id and p.school_id=m.school_id where p.synthetic is distinct from true) as "currentActors",not exists(select 1 from pg_roles where rolname in(\'cuevo_api\',\'cuevo_worker\') and(not rolcanlogin or rolsuper or rolbypassrls or rolcreaterole or rolcreatedb or rolreplication or rolinherit)) as "runtimeRoles",not exists(select 1 from internal.posthog_school_activation where enabled) as "analyticsDisabled"'));if(!source.length)throw fail();
  const manifestBytes=await readFile(join(input.repoRoot,'supabase/seed/identities.json'));if(createHash('sha256').update(manifestBytes).digest('hex')!=='7464b3487adc3998d8f4ad4582ffd08ebafbdc8fd9a568433ddc687f4f03ac21')throw fail();const manifest=z.object({actors:z.array(z.object({actorId:z.uuid(),schoolId:z.uuid(),role:z.string(),email:z.string().email()}).passthrough()).length(133)}).passthrough().parse(JSON.parse(manifestBytes.toString('utf8')));
  z.array(z.object({peopleMatching:z.literal(true),authMatching:z.literal(true),currentMemberships:z.literal(true)}).strict()).length(1).parse(await query(`/* CUEVO_ACTIVE_RUNTIME_ACTORS */ select not exists(select 1 from app.people p full join jsonb_to_recordset($1::jsonb) e("actorId" uuid,"schoolId" uuid) on p.actor_id=e."actorId" and p.school_id=e."schoolId" where p.actor_id is null or e."actorId" is null or p.synthetic is distinct from true) as "peopleMatching",not exists(select 1 from auth.users u full join jsonb_to_recordset($1::jsonb)e("actorId" uuid,email text)on u.id=e."actorId" where u.id is null or e."actorId" is null or u.email is distinct from e.email or u.email_confirmed_at is null or u.deleted_at is not null or u.is_anonymous or u.banned_until>now() or u.raw_user_meta_data->'synthetic' is distinct from 'true'::jsonb) as "authMatching",not exists(select 1 from jsonb_to_recordset($1::jsonb)e("actorId" uuid,"schoolId" uuid,role text) where not exists(select 1 from app.memberships m where m.actor_id=e."actorId" and m.school_id=e."schoolId" and m.role=e.role and m.status='active' and m.effective_from<=now() and(m.effective_to is null or m.effective_to>now()))) as "currentMemberships"`,[JSON.stringify(manifest.actors)]));
  const providerRows=await query('/* CUEVO_ACTIVE_RUNTIME_PROVIDER */ select decrypted_secret from vault.decrypted_secrets where name=$1',['cuevo_provider_'+project]);if(providerRows.length!==1||typeof providerRows[0].decrypted_secret!=='string'||Buffer.byteLength(providerRows[0].decrypted_secret)>49152)throw fail();const providerState=providerDeploymentStateSchema.parse(JSON.parse(providerRows[0].decrypted_secret)),operation=providerState.operations.at(-1);if(!operation||providerState.projectRef!==project||operation.phases.length!==4||operation.phases.some(row=>row.state!=='CONFIRMED')||operation.identity.sourceSha!==expected.releaseSha||operation.identity.treeSha!==expected.treeSha||operation.identity.apiArtifactSha256!==expected.fingerprints.apiArtifactSha256||operation.identity.edgeArtifactSha256!==expected.fingerprints.edgeArtifactSha256||operation.identity.denoLockSha256!==expected.fingerprints.denoLockSha256||operation.identity.runtimeSha256!==runtime.runtimeSha256)throw fail();
  const apiReceipt=operation.phases.find(row=>row.name==='API_DEPLOYMENT')?.receipt,edgeReceipt=operation.phases.find(row=>row.name==='EDGE_DEPLOYMENT')?.receipt;if(apiReceipt?.kind!=='API_DEPLOYMENT'||apiReceipt.deploymentId!==installed.apiDeploymentId||apiReceipt.url!==installed.apiUrl||edgeReceipt?.kind!=='EDGE_DEPLOYMENT'||edgeReceipt.id!==installed.edgeId||edgeReceipt.version!==installed.edgeVersion)throw fail();
  z.array(z.object({allowed:z.literal(true)}).strict()).length(1).parse(await query(initialRuntimeRolesSql.replace('CUEVO_RUNTIME_INITIAL_ROLES','CUEVO_RUNTIME_RECOVERED_ROLES').replace('not rolcanlogin','rolcanlogin')));
  const controls=async()=>{const rows=z.array(z.object({enabled:z.literal(true),endpoint:z.literal(installed.endpoint),vault_secret_name:z.literal(installed.vaultSecretName),allow_local:z.literal(false),state:z.enum(['IDLE','REQUESTED','RUNNING']),wake_id:z.uuid().nullable(),lease_expires_at:timestamp.nullable(),network_request_id:z.number().nullable()}).strict()).length(1).parse(await query('/* CUEVO_ACTIVE_RUNTIME_CONTROL */ select enabled,endpoint,vault_secret_name,allow_local,state,wake_id,lease_expires_at,network_request_id from internal.worker_dispatch_control where singleton'));const row=rows[0];if(row.state==='IDLE'?(row.wake_id!==null||row.lease_expires_at!==null):(row.wake_id===null||row.lease_expires_at===null||Date.parse(row.lease_expires_at)<=Date.now()))throw fail();};await controls();
  z.array(z.object({matching:z.literal(true),count:z.literal(1)}).strict()).length(1).parse(await query('/* CUEVO_ACTIVE_RUNTIME_KEY */ select count(*)::integer as count,bool_and(decrypted_secret=$2) as matching from vault.decrypted_secrets where name=$1',[installed.vaultSecretName,original.wakeKey]));
  z.array(z.object({jobid:z.coerce.number().refine(value=>value===installed.jobId),jobname:z.literal('cuevo-worker-recovery'),schedule:z.literal('* * * * *'),command:z.literal('select internal.request_worker_wake();'),database:z.literal('postgres'),username:z.literal('postgres'),active:z.literal(true)}).strict()).length(1).parse(await query('/* CUEVO_ACTIVE_RUNTIME_CRON */ select jobid,jobname,schedule,command,database,username,active from cron.job where jobname=\'cuevo-worker-recovery\' or(active and(command ilike \'%request_worker_wake%\' or jobname ilike \'cuevo%\'))'));
  z.object({id:z.literal(installed.apiDeploymentId),projectId:z.literal(expected.targets.api.projectId),ownerId:z.literal(expected.targets.api.teamId),url:z.literal(new URL(installed.apiUrl).hostname),readyState:z.literal('READY'),target:z.null().or(z.literal('preview')),meta:z.object({cuevoCommitSha:z.literal(expected.releaseSha),cuevoArtifactSha256:z.literal(expected.fingerprints.apiArtifactSha256),cuevoProviderOperation:z.literal(providerStateSha256(operation.identity))})}).parse(await readJson(`https://api.vercel.com/v13/deployments/${installed.apiDeploymentId}?teamId=${expected.targets.api.teamId}`,input.vercelToken));
  const environments=z.object({envs:z.array(z.object({key:z.string(),value:z.string(),target:z.array(z.string()),type:z.literal('encrypted'),gitBranch:z.string().nullable().optional()}).passthrough()).max(100)}).parse(await readJson(`https://api.vercel.com/v10/projects/${expected.targets.api.projectId}/env?teamId=${expected.targets.api.teamId}&decrypt=true`,input.vercelToken)).envs;
  if(environments.length!==Object.keys(runtime.api).length||new Set(environments.map(row=>row.key)).size!==environments.length||environments.some(row=>row.target.length!==1||row.target[0]!=='preview'||row.gitBranch!=null||runtime.api[row.key as keyof typeof runtime.api]!==row.value))throw fail();
  z.object({id:z.literal(installed.edgeId),version:z.literal(installed.edgeVersion),slug:z.literal('cuevo-worker'),status:z.literal('ACTIVE'),verify_jwt:z.literal(false)}).parse(await readJson(`https://api.supabase.com/v1/projects/${project}/functions/cuevo-worker`,input.providerToken));
  const secrets=z.array(z.object({name:z.string(),value:z.string()})).max(100).parse(await readJson(`https://api.supabase.com/v1/projects/${project}/secrets`,input.providerToken));for(const[name,value]of Object.entries(runtime.edge)){const expectedHash=createHash('sha256').update(name==='CUEVO_WORKER_WAKE_KEY'?original.wakeKey:value).digest('hex');if(secrets.filter(row=>row.name===name&&row.value===expectedHash).length!==1)throw fail();}
  await readBackendReleaseAdmission({repoRoot:input.repoRoot,expected,prepared,githubToken:input.githubToken});await controls();if(hash(await read())!==hash(original))throw fail();validatePreparedBackendReleaseIntent(prepared,{...expected,now:Date.now()});
  result.status='INSTALLED_RUNTIME_REVALIDATED';result.sourceSha=expected.releaseSha;result.runId=expected.releaseRunId;result.runAttempt=expected.runAttempt;result.packageSha256=prepared.sha256;result.original=installed;result.activation=original.activation;result.cleanup=original.cleanup;result.nativeExecutionVerified=true;result.observedAt=new Date().toISOString();
 }catch{result.status='REQUIRES_REVIEW';}finally{if(client){if(locked)try{const rows=(await client.query('select pg_advisory_unlock(hashtextextended($1,0))as released',[lockKey])).rows;result.lockReleased=rows.length===1&&rows[0].released===true&&!lost;if(!result.lockReleased)result.status='REQUIRES_REVIEW';}catch{result.status='REQUIRES_REVIEW';}ending=true;try{await client.end();}catch{result.status='REQUIRES_REVIEW';result.lockReleased=false;}}}return result;
}

/** The approved operator alone recovers the exact private original configuration.
 * No management-API/public projection or replacement credential is used. */
export async function readActiveRuntimeConfiguration(value:unknown){
 const input=z.object({repoRoot:z.string(),expected:z.unknown(),preparedApproval:z.unknown(),githubToken:z.string().min(1),operatorDatabaseUrl:z.string(),operatorPassword:z.string().min(1),certificate:z.string().min(1).max(512*1024)}).strict().parse(JSON.parse(canonicalReleaseExecutionJson(value))),expected=input.expected as BackendReleaseExpected;
 if(!expected.installedRuntime||expected.executionScope!=='installed-runtime'||expected.installedRuntime.sourceSha!==expected.releaseSha||expected.installedRuntime.treeSha!==expected.treeSha||!input.certificate.includes('-----BEGIN CERTIFICATE-----'))throw fail();
 const prepared=validatePreparedBackendReleaseIntent(input.preparedApproval,{...expected,now:Date.now()});await readBackendReleaseAdmission({repoRoot:input.repoRoot,expected,prepared,githubToken:input.githubToken});const project=expected.targets.supabase.projectRef,url=new URL(input.operatorDatabaseUrl),direct=url.hostname===`db.${project}.supabase.co`,pooler=/^aws-[0-9]+-[a-z0-9-]+\.pooler\.supabase\.com$/.test(url.hostname);
 if(url.protocol!=='postgresql:'||url.password||url.port!=='5432'||url.pathname!=='/postgres'||url.search!=='?sslmode=verify-full'||url.hash||!(direct||pooler)||decodeURIComponent(url.username)!==(direct?'postgres':'postgres.'+project)
   ||hash({projectRef:project,kind:direct?'direct':'session-pooler',host:url.hostname,port:5432,database:'postgres'})!==expected.fingerprints.migrationEndpointSha256)throw fail();
 const client=new Client({host:url.hostname,port:5432,database:'postgres',user:decodeURIComponent(url.username),password:input.operatorPassword,ssl:{rejectUnauthorized:true,ca:input.certificate,minVersion:'TLSv1.2'},connectionTimeoutMillis:5000,statement_timeout:5000,query_timeout:7000,lock_timeout:2000,application_name:'cuevo-active-runtime-private-reader'});let locked=false,lost=false,ending=false;client.on('error',()=>{if(!ending)lost=true;});client.on('end',()=>{if(!ending)lost=true;});
 const live=()=>{const peer=client.connection.stream as TLSSocket;if(lost||!peer.encrypted||peer.authorized!==true||!peer.getPeerCertificate()?.raw?.length||checkServerIdentity(url.hostname,peer.getPeerCertificate()))throw fail();};let recovered:{runtimeConfig:unknown;original:ReturnType<typeof readInstalledRuntimeMetadata>}|undefined;
 try{await client.connect();live();z.array(z.object({operator:z.literal('postgres'),role:z.literal('postgres'),database:z.literal('postgres'),ssl:z.literal(true)}).strict()).length(1).parse((await client.query('/* CUEVO_ACTIVE_RUNTIME_IDENTITY */ select session_user::text as operator,current_user::text as role,current_database()::text as database,(select ssl from pg_stat_ssl where pid=pg_backend_pid()) as ssl')).rows);const lock=(await client.query('select pg_try_advisory_lock(hashtextextended($1,0))as locked',[project+':HOSTED_SCHEMA_MIGRATION'])).rows;live();if(lock.length!==1||lock[0].locked!==true)throw fail();locked=true;
  const rows=(await client.query('/* CUEVO_ACTIVE_RUNTIME_READ */ select decrypted_secret from vault.decrypted_secrets where name=$1',['cuevo_active_runtime_'+project])).rows;live();if(rows.length!==1||typeof rows[0].decrypted_secret!=='string'||Buffer.byteLength(rows[0].decrypted_secret)>49152)throw fail();const state=activeRuntimeStateSchema.parse(JSON.parse(rows[0].decrypted_secret)),original=readInstalledRuntimeMetadata([{state:Object.fromEntries(Object.entries(state).filter(([key])=>!['wakeKey','runtimeConfig'].includes(key)))}],project);
  if(hash(original)!==hash(expected.installedRuntime)||state.runtimeConfig===undefined||prepareHostedRuntimeRecipients(state.runtimeConfig,expected).runtimeSha256!==original.runtimeSha256)throw fail();await readBackendReleaseAdmission({repoRoot:input.repoRoot,expected,prepared,githubToken:input.githubToken});live();recovered={runtimeConfig:state.runtimeConfig,original};
 }finally{try{if(locked){try{const released=(await client.query('select pg_advisory_unlock(hashtextextended($1,0))as released',[project+':HOSTED_SCHEMA_MIGRATION'])).rows;live();if(released.length!==1||released[0].released!==true)recovered=undefined;}catch{recovered=undefined;}}}finally{ending=true;try{await client.end();}catch{recovered=undefined;}}}
 if(!recovered)throw fail();return recovered;
}
