import assert from 'node:assert/strict';
import {test} from 'node:test';
import {registerHooks} from 'node:module';
import {readFileSync} from 'node:fs';
import {mkdtemp,mkdir,writeFile,readFile,unlink,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {z} from 'zod';
import {createPreparedEdgeFixture} from './prepared-edge-artifact.fixture';
import {preparedEdgeContentBindingSchema} from '../database/hosted-provider-state';
import {readPreparedEdgeBody} from '../runtime/edge-prepared-artifact';
import {canonicalReleaseReviewJson} from './release-review';
import {createHash} from 'node:crypto';
import {transformSync} from 'esbuild';
import {canonicalReleaseExecutionJson} from './release-review';
import {runtimeReleaseStateSha256} from '../database/hosted-active-runtime-state';
import {providerStateSha256} from '../database/hosted-provider-state';
import {hostedSyntheticSeedSha256,installedPopulationFingerprint} from '../database/hosted-installed-state';
import type {NativeBackendAdmissionHandle} from './backend-release-admission';
import {stagingHostContractSha256} from './backend-staging-host-contract';
const edgeFixture=createPreparedEdgeFixture(),edgeBinding={artifactVersion:2 as const,rawEszipSha256:edgeFixture.manifest.rawEszipSha256,ezbrSha256:edgeFixture.manifest.ezbrSha256,rawByteSize:edgeFixture.manifest.rawByteSize,entrypoint:'edge/index.ts' as const};
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),project='abcdefghijklmnopqrst',source='a'.repeat(40),tree='b'.repeat(40),ca='-----BEGIN CERTIFICATE-----\nfixture\n-----END CERTIFICATE-----',config={sourceSha:source,api:{CUEVO_DATABASE_TLS_CA:ca,EXAMPLE:'private-api-config'},edge:{CUEVO_WORKER_WAKE_KEY:'',EXAMPLE:'private-edge-config'}},originalHash=runtimeReleaseStateSha256(config),manifestBytes=readFileSync(join(process.cwd(),'supabase/seed/identities.json')),manifest=JSON.parse(manifestBytes.toString('utf8')) as {schoolId:string;actors:{actorId:string;schoolId:string;role:string}[]},admin=manifest.actors.find(row=>row.schoolId===manifest.schoolId&&row.role==='admin')!,migration={name:'20261008124909_worker_rollout_admission.sql',bytes:Buffer.from('begin;\nselect 1;\ncommit;\n')},migrations=[{name:migration.name,version:migration.name.slice(0,14),sha256:hash(migration.bytes)}],fingerprints={apiArtifactSha256:'1'.repeat(64),edgeArtifactSha256:'2'.repeat(64),denoLockSha256:'3'.repeat(64)};
type Fixture={raw:unknown;intent:unknown|null;calls:string[];secrets:{name:string;value:string}[];mode:string;closed:number;paused:boolean;generation:string|null;operation:string|null;events:Map<string,()=>void>;post:number;preparations?:number;disposals?:number;admissionHandle?:object;binding?:unknown;connected?:boolean};let state:Fixture|undefined;
function initialHostContract(){const settings=(rootDirectory:string|null,framework:string|null)=>({nodeVersion:'24.x',fluid:true,functionDefaultRegions:['sin1'],autoAssignCustomDomains:false,ssoDeploymentType:'all_except_custom_domains',rootDirectory,framework});return{version:1,purpose:'CUEVO_STAGING_HOST_CONTRACT',sourceSha:source,treeSha:tree,deploymentEnvironment:'synthetic-staging',targets:{api:{teamId:'team_fixture',projectId:'prj_fixture',origin:'https://cuevo-api.vercel.app',target:'preview'},web:{teamId:'team_fixture',projectId:'prj_web',origin:'https://cuevo.vercel.app',target:'preview'},supabase:{projectRef:project,authOrigin:`https://${project}.supabase.co`,edgeOrigin:`https://${project}.supabase.co/functions/v1/cuevo-worker`}},settings:{api:settings(null,null),web:settings('apps/web','nextjs'),supabase:{region:'ap-southeast-1',postgresEngine:'17',applicationConnection:{kind:'direct',host:`db.${project}.supabase.co`,port:5432,database:'postgres'}}},sourceBounds:{api:{node:'24',maxDurationSeconds:60,poolMax:10,connectionTimeoutMs:3000,idleTimeoutMs:10000,statementTimeoutMs:5000},worker:{poolMax:1,connectionTimeoutMs:3000,statementTimeoutMs:5000,processingDeadlineMs:20000,claimReserveMs:15000,eventLeaseSeconds:30,invocationLeaseSeconds:60,deliveryTimeoutMs:30000,recoveryIntervalSeconds:60}},capacity:{postgres:{maxConnections:60,superuserReservedConnections:3},sessionPoolerClientCeiling:{state:'UNKNOWN',value:null}},exposure:{audience:'PRIVATE_SYNTHETIC_OPERATORS',roleScope:'FIVE_REFERENCE_ROLES',gatewayPolicy:'EXISTING_PROTECTED_PREVIEW_AND_RESERVED_ORIGIN',clientAddressPolicy:'HOSTED_VERIFICATION_PENDING',fleetProtection:'NOT_VERIFIED'}};}
class FakeClient{
 connection={stream:{encrypted:true,authorized:true,getProtocol:()=> 'TLSv1.3',getPeerCertificate:()=>({raw:Buffer.from('fixture')})}};on(name:string,callback:()=>void){state!.events.set(name,callback);}async connect(){state!.connected=true;state!.calls.push('CONNECT');}async end(){state!.connected=false;state!.calls.push('END');state!.closed++;}async query(sql:string,args:unknown[]=[]){const f=state!;f.calls.push(sql);let rows:Record<string,unknown>[]=[];
 if(sql.includes('pg_try_advisory_lock'))rows=[{locked:true}];else if(sql.includes('pg_advisory_unlock')){assert.equal(args[0],project+':HOSTED_SCHEMA_MIGRATION');rows=[{released:true}];}
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_IDENTITY'))rows=[{operator:'postgres',role:'postgres',database:'postgres',ssl:true,private:true}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_STATE'))rows=[{id:'10000000-0000-4000-8000-000000000001',decrypted_secret:canonicalReleaseExecutionJson(f.raw)}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_INTENT'))rows=f.intent?[{id:'10000000-0000-4000-8000-000000000003',decrypted_secret:canonicalReleaseExecutionJson(f.intent)}]:[];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_SOURCE'))rows=[{synthetic:true,peopleMatching:true,authMatching:true,currentMemberships:true,analyticsDisabled:f.mode!=='analytics-enabled'}];
 else if(sql.includes('CUEVO_RUNTIME_RECOVERED_ROLES'))rows=[{allowed:f.mode!=='roles-denied'}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_INSTALLED'))rows=[{decrypted_secret:canonicalReleaseExecutionJson({version:1,purpose:'CUEVO_COMPLETED_INSTALLED_MIGRATIONS',projectRef:project,sourceSha:source,treeSha:tree,migrationCount:1,migrations:migrations.map(({version,sha256})=>({version,sha256}))})}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_HISTORY'))rows=[{version:migration.name.slice(0,14),name:migration.name.slice(15,-4),statements:[f.mode==='history-drift'?'select 9':migration.bytes.toString('utf8').trim()]}];
 else if(sql.includes('CUEVO_INSTALLED_POPULATION_RECEIPT')){const receipt={version:1 as const,purpose:'CUEVO_INSTALLED_SYNTHETIC_POPULATION' as const,projectRef:project,sourceSha:source,treeSha:tree,seedSha256:hostedSyntheticSeedSha256 as typeof hostedSyntheticSeedSha256,manifestSha256:runtimeReleaseStateSha256(JSON.parse(manifestBytes.toString('utf8')))};rows=[{fingerprint:installedPopulationFingerprint(receipt),state:'COMPLETED',response:receipt}];}
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_PRIVATE'))rows=[{privateStorage:true,privateRealtime:true,private:true}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_AUTHORITY'))rows=[{rls:true,privateRelations:f.mode!=='grants-drift',privateFunctions:true,noRuntimeOwnership:true}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_CONTROL')){const active=f.generation===null&&f.mode.startsWith('requested-');rows=[{enabled:true,endpoint:original().identity.endpoint,vault_secret_name:original().identity.vaultSecretName,allow_local:false,admission_paused:f.mode==='control-drift'?!f.paused:f.paused,execution_generation:f.generation,rollout_operation_sha256:f.mode==='paused-operation-drift'&&f.paused?'f'.repeat(64):f.operation,state:f.generation===null&&f.mode==='backoff-after-pause'&&f.paused?'BACKOFF':active?'REQUESTED':'IDLE',wake_id:active?(f.mode==='requested-missing-wake'&&f.paused?null:'10000000-0000-4000-8000-000000000004'):null,lease_expires_at:active?(f.mode==='requested-missing-expiry'&&f.paused?null:new Date(Date.now()+(f.mode==='requested-expired'?-1000:60000)).toISOString()):null}];}
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_KEY'))rows=[{count:1,matching:true}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_CRON'))rows=[{jobid:f.mode==='cron-drift'?43:42,jobname:'cuevo-worker-recovery',schedule:'* * * * *',command:'select internal.request_worker_wake();',database:'postgres',username:'postgres',active:true}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_EVENT'))rows=[{id:original().activation.probeEventId,school_id:manifest.schoolId,actor_id:admin.actorId,state:'COMPLETED',processed:true,audit:true,command_count:f.mode==='event-missing'?0:1}];
 else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_PROVIDER'))rows=[{decrypted_secret:canonicalReleaseExecutionJson(provider())}];
 else if(sql.includes('vault.create_secret')){if(f.mode!=='intent-absent-unknown')f.intent=JSON.parse(String(args[0]));rows=[{id:'10000000-0000-4000-8000-000000000003'}];if(['intent-unknown','intent-absent-unknown'].includes(f.mode))throw Error('PRIVATE lost intent acknowledgement');}
 else if(sql.includes('pause_worker_admission')){f.paused=true;f.operation=String(args[2]);rows=[{paused:true}];}else if(sql.includes('CUEVO_RUNTIME_INITIALIZATION_DRAIN')){rows=[{active:f.mode==='malformed-drain'?'unknown':f.mode==='requested-pending'?1:0}];if(f.mode==='requested-pending')f.mode='requested-expired';if(f.mode.startsWith('late-edge-')){assert.equal(f.calls.filter(row=>row==='EDGE_BODY_OBSERVATION').length,1);f.mode=f.mode.replace('late-edge-','drift-edge-');f.calls.push('LATE_EDGE_METADATA_DRIFT');}}
 else if(sql.includes('vault.update_secret'))f.raw=JSON.parse(String(args[1]));else if(sql.includes('resume_worker_admission')){f.paused=false;f.generation='1';f.operation=null;rows=[{resumed:true}];}
 else if(sql==='COMMIT'&&f.mode==='commit-unknown')throw Error('PRIVATE lost commit acknowledgement');else if(!['BEGIN','COMMIT','ROLLBACK'].includes(sql))throw Error('Unexpected owned SQL');return{rows};
 }
}
Object.assign(globalThis,{runtimeInitializeFixture:{Client:FakeClient,admit:async(_input?:unknown,handle?:object)=>{assert(handle&&state!.admissionHandle);assert.equal(handle,state!.admissionHandle);state!.calls.push('ADMISSION');if(state!.mode==='late-admission'&&state!.calls.includes('CONNECT'))throw Error('Current approval revoked');},prepare:async(input:{repoRoot:string;expected:unknown;prepared:unknown;effectScope:string})=>{assert.notEqual(state!.connected,true);state!.calls.push('PREPARE_ADMISSION');state!.preparations=(state!.preparations??0)+1;state!.admissionHandle=Object.freeze({});state!.binding={repoRoot:input.repoRoot,expected:input.expected,prepared:input.prepared,effectScope:input.effectScope};return state!.admissionHandle;},read:async(handle:object,binding:unknown)=>{assert.equal(handle,state!.admissionHandle);assert.deepEqual(binding,state!.binding);state!.calls.push('CURRENT_ADMISSION');if(state!.mode==='late-admission'&&state!.calls.includes('CONNECT'))throw Error('Current approval revoked');return{expected:(binding as {expected:unknown}).expected,observedAt:new Date().toISOString(),approval:{packageSha256:(binding as {prepared:{sha256:string}}).prepared.sha256}};},dispose:(handle:object)=>{assert.equal(handle,state!.admissionHandle);assert(state!.closed>=1||!state!.calls.includes('CONNECT'));state!.calls.push('DISPOSE_ADMISSION');state!.disposals=(state!.disposals??0)+1;state!.admissionHandle=undefined;},validate:(value:unknown)=>value,recipients:(value:typeof config)=>({api:value.api,edge:value.edge,runtimeSha256:runtimeReleaseStateSha256(value)}),contracts:()=>({migrationSetSha256:runtimeReleaseStateSha256(migrations),migrationList:migrations}),sources:()=>({sources:[migration]}),operating:async(_input?:unknown,handle?:object)=>{assert(state!.closed>=1,'The initializer must close its original lock before the generation proof opens');if(state!.admissionHandle)assert.equal(handle,state!.admissionHandle);state!.calls.push('OPERATING_PROOF');if(state!.mode==='operating-failed')throw Error('Private operating proof failed');return{status:'INITIAL_RUNTIME_OPERATING_VERIFIED',generation:'1',confirmationSha256:'9'.repeat(64),currentStateSha256:'8'.repeat(64),lockReleased:true,sessionClosed:true,hostedAcceptance:false};}}});
registerHooks({load(url,context,next){const name=url.split('/').at(-1);if(name==='backend-runtime-initialize.ts')return{format:'module',shortCircuit:true,source:transformSync(readFileSync(new URL(url),'utf8').replace("import {Client} from 'pg';","const {Client}=globalThis.runtimeInitializeFixture;").replace("import {checkServerIdentity,type TLSSocket} from 'node:tls';","const checkServerIdentity=()=>undefined;"),{loader:'ts',format:'esm'}).code};if(name==='backend-release-admission.ts')return{format:'module',shortCircuit:true,source:'export const prepareNativeBackendReleaseAdmission=globalThis.runtimeInitializeFixture.prepare;export const readNativeBackendReleaseAdmission=globalThis.runtimeInitializeFixture.read;export const disposeNativeBackendReleaseAdmission=globalThis.runtimeInitializeFixture.dispose;export const readBackendActivationExecutionAdmission=globalThis.runtimeInitializeFixture.admit;export const readBackendReleaseAdmission=async input=>{await globalThis.runtimeInitializeFixture.admit();return{expected:input.expected,observedAt:new Date().toISOString(),approval:{packageSha256:input.prepared.sha256}};};'};if(name==='backend-release-contracts.ts')return{format:'module',shortCircuit:true,source:'export const validatePreparedBackendReleaseIntent=globalThis.runtimeInitializeFixture.validate;export const readBackendRuntimeFingerprints=value=>Object.fromEntries(["apiArtifactSha256","edgeArtifactSha256","denoLockSha256"].map(key=>[key,value[key]]));'};if(name==='backend-provider-deploy.ts')return{format:'module',shortCircuit:true,source:'export const observePreparedEdgeContent=(...args)=>globalThis.initializationObserveEdge(...args);export const observePreparedEdgeMetadata=(...args)=>globalThis.initializationObserveMetadata(...args);export const prepareHostedRuntimeRecipients=globalThis.runtimeInitializeFixture.recipients;export const prepareHostedOperatingRecipients=globalThis.runtimeInitializeFixture.recipients;'};if(name==='backend-runtime-resume.ts')return{format:'module',shortCircuit:true,source:'export const verifyInitialRuntimeGeneration=globalThis.runtimeInitializeFixture.operating;'};if(name==='runtime-contract-manifest.ts')return{format:'module',shortCircuit:true,source:'export const readRuntimeContractManifest=globalThis.runtimeInitializeFixture.contracts;'};if(name==='hosted-migration-plan.ts')return{format:'module',shortCircuit:true,source:'export const readCanonicalMigrationSources=globalThis.runtimeInitializeFixture.sources;'};if(name==='hosted-migration-provider.ts')return{format:'module',shortCircuit:true,source:'export const readHostedMigrationProvider=async()=>({observedAtMs:Date.now()});export const requireCurrentHostedMigrationEndpoint=value=>value;'};return next(url,context);}});
const edgeSource=readFileSync(resolve(import.meta.dirname,'backend-provider-deploy.ts'),'utf8'),edgeAst=ts.createSourceFile('provider.ts',edgeSource,ts.ScriptTarget.Latest,true),edgeCode=ts.transpileModule(edgeAst.statements.filter(ts.isFunctionDeclaration).filter(node=>['responseBytes','providerRequest','observePreparedEdgeMetadata','observePreparedEdgeContent'].includes(node.name?.text??'')).map(node=>node.getText(edgeAst)).join('\n')+'\n({observePreparedEdgeContent,observePreparedEdgeMetadata})',{compilerOptions:{target:ts.ScriptTarget.ES2023,module:ts.ModuleKind.None}}).outputText;
const providerObserver=()=>runInNewContext(edgeCode,{exports:{},z,preparedEdgeContentBindingSchema,readPreparedEdgeBody:(value:Uint8Array,expected:unknown)=>readPreparedEdgeBody(value,JSON.parse(JSON.stringify(expected))),canonicalReleaseReviewJson,fetch:globalThis.fetch,AbortSignal,AbortController,Buffer,TextDecoder,setTimeout,clearTimeout,failure:()=>Error('Controlled content requires review.')});
Object.assign(globalThis,{initializationObserveEdge:async(input:Parameters<typeof import('./backend-provider-deploy').observePreparedEdgeContent>[0])=>{assert.deepEqual(input.binding,edgeBinding);state!.calls.push('EDGE_BODY_OBSERVATION');return providerObserver().observePreparedEdgeContent(input);},initializationObserveMetadata:async(input:Parameters<typeof import('./backend-provider-deploy').observePreparedEdgeMetadata>[0])=>{assert.deepEqual(input.binding,edgeBinding);return providerObserver().observePreparedEdgeMetadata(input);}});function original(){const activation={status:'ACTIVATED_SIGNED_SOURCE_VERIFIED' as const,sourceSha:source,projectRef:project,runId:'51',runAttempt:1,packageSha256:'c'.repeat(64),runtimeSha256:originalHash,apiDeploymentId:'dpl_old',edgeVersion:1,jobId:42,sourceProcessed:true as const,duplicateWakeDenied:true as const,originalCommandReplayed:true as const,recoveryScheduled:true as const,scheduledRecoveryVerified:true as const,configurationEvidenceObservedManual:true as const,sessionsClosed:true as const,keyOperation:'CONFIRMED' as const,dispatchOperation:'CONFIRMED' as const,probeEventId:'10000000-0000-4000-8000-000000000001',observedAt:'2026-10-07T12:00:00Z'};return{version:1,purpose:'CUEVO_PRIVATE_ACTIVE_RUNTIME_STATE',projectRef:project,phase:'CONFIRMED',identity:{sourceSha:source,treeSha:tree,originalRunId:'51',originalRunAttempt:1,originalPackageSha256:'c'.repeat(64),runtimeSha256:originalHash,apiDeploymentId:'dpl_old',apiUrl:'https://cuevo-old.vercel.app',edgeId:'edge_old',edgeVersion:1,activationId:'10000000-0000-4000-8000-000000000002',vaultSecretName:'cuevo_worker_10000000000040008000000000000002',endpoint:`https://${project}.supabase.co/functions/v1/cuevo-worker`,createdAt:'2026-10-07T11:59:00Z'},wakeKey:'e'.repeat(64),runtimeConfig:config,jobId:42,activation,cleanup:{status:activation.status,sourceSha:source,projectRef:project,runId:'51',runAttempt:1,lockReleased:true,sessionsClosed:true,resultSha256:runtimeReleaseStateSha256(activation),observedAt:'2026-10-07T12:00:01Z'}};}
function provider(){const identity={sourceSha:state?.mode==='edge-source'?'f'.repeat(40):source,treeSha:tree,...fingerprints,...(state?.mode==='edge-artifact'?{edgeArtifactSha256:'f'.repeat(64)}:{}),runtimeSha256:originalHash,teamId:'team_fixture',projectId:'prj_fixture',originalRunId:'51',originalRunAttempt:1,originalPackageSha256:'c'.repeat(64),...(state?.mode.startsWith('host-contract-')&&state.mode!=='host-contract-missing'?{stagingHostContractSha256:state.mode==='host-contract-changed'?'f'.repeat(64):stagingHostContractSha256(initialHostContract())}:{})};return{version:1,purpose:'CUEVO_PRIVATE_PROVIDER_DEPLOYMENT_STATE',projectRef:project,operations:[{identity,phases:[{name:'API_ENVIRONMENT',state:'CONFIRMED',receipt:{kind:'API_ENVIRONMENT',keysSha256:runtimeReleaseStateSha256(Object.keys(config.api).sort()),valuesSha256:runtimeReleaseStateSha256(config.api),variables:Object.entries(config.api).map(([key,value],index)=>({key,id:'env_'+index,valueSha256:hash(value)}))}},{name:'API_DEPLOYMENT',state:'CONFIRMED',receipt:{kind:'API_DEPLOYMENT',deploymentId:'dpl_old',url:'https://cuevo-old.vercel.app'}},{name:'EDGE_SECRETS',state:'CONFIRMED',receipt:{kind:'EDGE_SECRETS',valuesSha256:runtimeReleaseStateSha256(config.edge),variables:Object.entries(config.edge).map(([name,value])=>({name,valueSha256:hash(value)}))}},{name:'EDGE_DEPLOYMENT',state:'CONFIRMED',receipt:{kind:'EDGE_DEPLOYMENT',id:'edge_old',version:state?.mode==='edge-version'?2:1,...(state?.mode==='edge-legacy'?{}:edgeBinding)}}]}]};}
async function fixture(mode:string,work:(input:Record<string,unknown>,root:string)=>Promise<void>){const root=await mkdtemp(join(tmpdir(),'cuevo-runtime-init-')),fetcher=globalThis.fetch;try{await mkdir(join(root,'.local/hosted-release'),{recursive:true});await mkdir(join(root,'supabase/seed'),{recursive:true});await writeFile(join(root,'supabase/seed/identities.json'),manifestBytes);const path=join(root,'.local/hosted-release/ca.pem');await writeFile(path,ca);const previous=original();await writeFile(join(root,'.local/hosted-release/worker-activation-intent.json'),canonicalReleaseExecutionJson({activationId:previous.identity.activationId,sourceSha:source,projectRef:project,packageSha256:'c'.repeat(64),runtimeSha256:originalHash,apiDeploymentId:'dpl_old',edgeDeployment:{id:'edge_old',version:1},originalKey:`worker-activation:51:1:${previous.identity.activationId}`,endpoint:previous.identity.endpoint}));state={raw:previous,intent:null,calls:[],secrets:[{name:'CUEVO_WORKER_WAKE_KEY',value:hash('e'.repeat(64))},{name:'EXAMPLE',value:hash(config.edge.EXAMPLE)}],mode,closed:0,paused:false,generation:null,operation:null,events:new Map(),post:0};
 globalThis.fetch=async(url,options)=>{const f=state!;assert(options?.signal);if(options?.method==='POST'){f.calls.push('PROVIDER_POST');f.post++;if(f.mode!=='provider-absent-unknown')f.secrets.push({name:'CUEVO_WORKER_RELEASE_GENERATION',value:hash('1')});if(['provider-unknown','provider-absent-unknown'].includes(f.mode))throw Error('PRIVATE provider outcome');return new Response(null,{status:201});}f.calls.push('PROVIDER_GET');const path=String(url);if(f.mode==='oversize-provider')return new Response('x',{status:200,headers:{'content-length':'131073'}});if(f.mode==='session-lost'){f.events.get('error')!();return Response.json({});}if(path.endsWith('/postgrest')){const response=Response.json({db_schema:state!.mode==='configuration-enabled'?'public':state!.mode==='configuration-unknown'?null:''});Object.defineProperty(response,'url',{value:path});return response;}if(path.includes('/deployments/'))return Response.json({id:'dpl_old',projectId:'prj_fixture',ownerId:'team_fixture',url:'cuevo-old.vercel.app',readyState:f.mode==='api-drift'?'ERROR':'READY',target:'preview',meta:{cuevoCommitSha:source,cuevoArtifactSha256:fingerprints.apiArtifactSha256,cuevoProviderOperation:providerStateSha256(provider().operations[0].identity)}});if(path.includes('/env?'))return Response.json({envs:Object.entries(config.api).map(([key,value],index)=>({id:'env_'+index,key,value:f.mode==='env-drift'?'changed':value,type:'encrypted',target:['preview'],gitBranch:null,comment:'Cuevo source-bound synthetic runtime '+source}))});if(path.endsWith('/functions/cuevo-worker/body'))return new Response(f.mode==='edge-body'?Buffer.from('ESZIP2.3changed'):edgeFixture.raw);if(path.includes('/functions/')){f.calls.push('EDGE_METADATA_GET');return Response.json({id:'edge_old',version:f.mode==='drift-edge-version'?2:1,slug:'cuevo-worker',status:f.mode==='drift-edge-status'?'ERROR':'ACTIVE',verify_jwt:f.mode==='edge-drift'||f.mode==='drift-edge-jwt',entrypoint_path:f.mode==='drift-edge-entrypoint'?'wrong/index.ts':edgeBinding.entrypoint,ezbr_sha256:f.mode==='drift-edge-digest'?'f'.repeat(64):edgeBinding.ezbrSha256});}return Response.json(f.mode==='secret-drift'?f.secrets.filter(row=>row.name!=='EXAMPLE'):f.secrets);};
 const expected={executionScope:'complete-backend',handoff:'operating-staging',releaseSha:source,treeSha:tree,releaseRunId:'51',runAttempt:1,targets:{supabase:{projectRef:project},api:{teamId:'team_fixture',projectId:'prj_fixture'}},fingerprints:{...fingerprints,migrationEndpointSha256:'f'.repeat(64)}},input={repoRoot:root,expected,preparedApproval:{sha256:'c'.repeat(64),canonicalJson:JSON.stringify({expiresAt:new Date(Date.now()+3600000).toISOString()})},githubToken:'private-gh',providerToken:'private-provider',vercelToken:'private-vercel',runtimeConfig:config,syntheticPassword:'private-synthetic-password',operator:{databaseUrl:`postgresql://postgres@db.${project}.supabase.co:5432/postgres?sslmode=verify-full`,password:'private-operator',certificate:{path,sha256:hash(ca)}}};await work(input,root);
 }finally{globalThis.fetch=fetcher;state=undefined;await rm(root,{recursive:true,force:true});}}
test('initial generation verifies native and provider proof, preserves original bytes, and retains exactly one intent',async()=>{const subject=await import('./backend-runtime-initialize');await fixture('normal',async(input,root)=>{const result=await subject.initializeHostedRuntimeGeneration(input);assert.equal(result.status,'INITIAL_RUNTIME_CONFIRMED');assert.equal(result.commitment,'CONFIRMED');assert.equal(result.operatingConfirmationSha256,'9'.repeat(64));assert(state!.calls.indexOf('OPERATING_PROOF')>state!.calls.findLastIndex(row=>row.includes('pg_advisory_unlock')));assert.equal(state!.closed,1);assert.equal(result.lockReleased,true);assert.equal(state!.post,1);assert.equal(canonicalReleaseExecutionJson((state!.raw as {original:unknown}).original),canonicalReleaseExecutionJson(original()));assert(!JSON.stringify(result).includes('private-operator'));const file=JSON.parse(await readFile(join(root,'.local/hosted-release/runtime-generation-private.json'),'utf8'));assert.equal(file.edge.CUEVO_WORKER_RELEASE_GENERATION,'1');assert.equal(file.edge.CUEVO_WORKER_WAKE_KEY,original().wakeKey);assert(state!.calls.some(row=>row.includes('INITIALIZATION_HISTORY')));assert(state!.calls.some(row=>row.includes('INITIALIZATION_EVENT')));});});
test('unknown native and provider acknowledgement retains original intent and never replays either upload',async()=>{const subject=await import('./backend-runtime-initialize');for(const mode of ['provider-unknown','provider-absent-unknown','commit-unknown','intent-unknown','intent-absent-unknown'])await fixture(mode,async(input)=>{const first=await subject.initializeHostedRuntimeGeneration(input);assert.equal(first.status,'REQUIRES_REVIEW',mode);assert.equal(first.commitment,'UNKNOWN',mode);const create=state!.calls.filter(row=>row.includes('vault.create_secret')).length,post=state!.post;state!.mode='normal';const repeated=await subject.initializeHostedRuntimeGeneration(input);assert.equal(state!.calls.filter(row=>row.includes('vault.create_secret')).length,create,mode);assert.equal(state!.post,post,mode);assert.equal(repeated.status,['commit-unknown','provider-unknown'].includes(mode)?'INITIAL_RUNTIME_CONFIRMED':'REQUIRES_REVIEW',mode);assert.equal(state!.closed,2);});});
test('v2 exact observation reconstructs missing private configuration after fresh proof and refuses conflicting recovery bytes',async()=>{const subject=await import('./backend-runtime-initialize');await fixture('normal',async(input,root)=>{assert.equal((await subject.initializeHostedRuntimeGeneration(input)).status,'INITIAL_RUNTIME_CONFIRMED');const path=join(root,'.local/hosted-release/runtime-generation-private.json'),exact=await readFile(path);await unlink(path);const post=state!.post,count=state!.calls.length;assert.equal((await subject.initializeHostedRuntimeGeneration(input)).status,'INITIAL_RUNTIME_CONFIRMED');assert.deepEqual(await readFile(path),exact);assert.equal(state!.post,post);const fresh=state!.calls.slice(count);assert(fresh.some(row=>row.includes('INITIALIZATION_SOURCE')));assert(fresh.some(row=>row.includes('INITIALIZATION_CRON')));assert(fresh.includes('PROVIDER_GET'));await writeFile(path,'{}');assert.equal((await subject.initializeHostedRuntimeGeneration(input)).status,'REQUIRES_REVIEW');assert.equal(await readFile(path,'utf8'),'{}');assert.equal(state!.post,post);});});
test('fresh source, native control, Cron, original execution and provider drift refuse effects even with retained v2 success',async()=>{const subject=await import('./backend-runtime-initialize');for(const mode of ['analytics-enabled','grants-drift','roles-denied','history-drift','control-drift','cron-drift','event-missing','api-drift','env-drift','edge-drift','secret-drift','oversize-provider','session-lost'])await fixture('normal',async(input,root)=>{assert.equal((await subject.initializeHostedRuntimeGeneration(input)).status,'INITIAL_RUNTIME_CONFIRMED');await unlink(join(root,'.local/hosted-release/runtime-generation-private.json'));state!.mode=mode;const post=state!.post;const observed=await subject.initializeHostedRuntimeGeneration(input);assert.equal(observed.status,'REQUIRES_REVIEW',mode);assert.equal(observed.admissionResumed,false,mode);assert.equal(observed.edgeEnvironmentConfirmed,false,mode);assert.equal(state!.post,post,mode);await assert.rejects(readFile(join(root,'.local/hosted-release/runtime-generation-private.json')));});});
test('invalid drain counts and changed first-use private posture refuse generation upload',async()=>{const subject=await import('./backend-runtime-initialize');for(const mode of ['malformed-drain','history-drift','cron-drift','secret-drift'])await fixture(mode,async(input)=>{assert.equal((await subject.initializeHostedRuntimeGeneration(input)).status,'REQUIRES_REVIEW',mode);assert.equal(state!.post,0,mode);});});

test('generation operating proof failure preserves initialized native state and retries proof without repeating initialization effects',async()=>{const subject=await import('./backend-runtime-initialize');await fixture('operating-failed',async(input)=>{const first=await subject.initializeHostedRuntimeGeneration(input);assert.equal(first.status,'REQUIRES_REVIEW');assert.equal(first.commitment,'CONFIRMED');assert.equal(first.operatingConfirmationSha256,null);assert.equal(first.receiptSha256,null);assert.equal((state!.raw as {version:number}).version,2);assert.equal(state!.post,1);state!.mode='normal';const second=await subject.initializeHostedRuntimeGeneration(input);assert.equal(second.status,'INITIAL_RUNTIME_CONFIRMED');assert.equal(second.operatingConfirmationSha256,'9'.repeat(64));assert.equal(state!.post,1);assert.equal(state!.calls.filter(row=>row.includes('vault.create_secret')).length,1);});});
test('owned pause drains an expired requested wake or a held completion backoff before generation initialization',async()=>{const subject=await import('./backend-runtime-initialize');for(const mode of ['requested-pending','backoff-after-pause'])await fixture(mode,async input=>{const result=await subject.initializeHostedRuntimeGeneration(input);assert.equal(result.status,'INITIAL_RUNTIME_CONFIRMED',mode);assert.equal(result.commitment,'CONFIRMED');assert.equal(state!.paused,false);assert.equal(state!.generation,'1');assert.equal(state!.post,1);assert(state!.calls.some(sql=>sql.includes('INITIALIZATION_DRAIN')));});});
test('paused malformed wake expiry or changed operation cannot permit upload or resume',async()=>{const subject=await import('./backend-runtime-initialize');for(const mode of ['requested-missing-wake','requested-missing-expiry','paused-operation-drift'])await fixture(mode,async input=>{const result=await subject.initializeHostedRuntimeGeneration(input);assert.equal(result.status,'REQUIRES_REVIEW',mode);assert.equal(state!.post,0);assert.equal(state!.generation,null);assert.equal(state!.calls.some(sql=>sql.includes('resume_worker_admission')),false);});});


test('initial generation refuses unconfirmed provider configuration before pause or upload and returns distinct current observation',async()=>{const api=await import('./backend-runtime-initialize');for(const selected of ['', 'configuration-enabled','configuration-unknown'])await fixture(selected,async input=>{const original=canonicalReleaseExecutionJson(state!.raw),result=await api.initializeHostedRuntimeGeneration(input);if(selected){assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(state!.post,0);assert.equal(state!.paused,false);assert.equal(canonicalReleaseExecutionJson(state!.raw),original);}else{assert.equal(result.status,'INITIAL_RUNTIME_CONFIRMED');assert.equal(result.configurationObservation?.evidence.source,'SUPABASE_MANAGEMENT_POSTGREST_CONFIG');}});});

test('initializer retains one current admission owner through native cleanup and post-initialization proof',async()=>{const subject=await import('./backend-runtime-initialize');await fixture('normal',async input=>{const result=await subject.initializeHostedRuntimeGeneration(input);assert.equal(result.status,'INITIAL_RUNTIME_CONFIRMED');assert.equal(state!.preparations,1);assert.equal(state!.disposals,1);assert(state!.calls.indexOf('PREPARE_ADMISSION')<state!.calls.indexOf('CONNECT'));assert(state!.calls.indexOf('OPERATING_PROOF')<state!.calls.indexOf('DISPOSE_ADMISSION'));assert.equal(state!.admissionHandle,undefined);});});
test('initializer borrows exact current admission through cleanup and generation proof without another capture or disposal',async()=>{const subject=await import('./backend-runtime-initialize');await fixture('normal',async input=>{const handle=Object.freeze({}) as NativeBackendAdmissionHandle;state!.admissionHandle=handle;state!.binding={repoRoot:input.repoRoot,expected:input.expected,prepared:input.preparedApproval,effectScope:'COMPLETE_BACKEND'};const result=await subject.initializeHostedRuntimeGeneration(input,handle);assert.equal(result.status,'INITIAL_RUNTIME_CONFIRMED');assert.equal(state!.preparations??0,0);assert.equal(state!.disposals??0,0);assert.equal(state!.admissionHandle,handle);assert.equal(state!.closed,1);assert(state!.calls.includes('CURRENT_ADMISSION'));assert(state!.calls.includes('OPERATING_PROOF'));});});
test('initializer refuses null or foreign borrowed admission before native or provider effects without recapture',async()=>{const subject=await import('./backend-runtime-initialize');for(const borrowed of [null,Object.freeze({})])await fixture('normal',async input=>{const result=await subject.initializeHostedRuntimeGeneration(input,borrowed as NativeBackendAdmissionHandle);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(state!.preparations??0,0);assert.equal(state!.disposals??0,0);assert.equal(state!.post,0);assert.equal(state!.calls.includes('CONNECT'),false);assert.equal(state!.calls.includes('PROVIDER_GET'),false);});});
test('initializer leaves a borrowed owner with its parent after current approval is lost during the native session',async()=>{const subject=await import('./backend-runtime-initialize');await fixture('late-admission',async input=>{const handle=Object.freeze({}) as NativeBackendAdmissionHandle;state!.admissionHandle=handle;state!.binding={repoRoot:input.repoRoot,expected:input.expected,prepared:input.preparedApproval,effectScope:'COMPLETE_BACKEND'};const result=await subject.initializeHostedRuntimeGeneration(input,handle);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(state!.preparations??0,0);assert.equal(state!.disposals??0,0);assert.equal(state!.admissionHandle,handle);assert.equal(state!.closed,1);assert.equal(state!.post,0);});});
test('initializer current approval loss stops before upload and disposes only after native cleanup',async()=>{const subject=await import('./backend-runtime-initialize');await fixture('late-admission',async input=>{const original=canonicalReleaseExecutionJson(state!.raw),result=await subject.initializeHostedRuntimeGeneration(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(state!.post,0);assert.equal(state!.preparations,1);assert.equal(state!.disposals,1);assert.equal(state!.closed,1);assert.equal(canonicalReleaseExecutionJson(state!.raw),original);assert(state!.calls.indexOf('END')<state!.calls.indexOf('DISPOSE_ADMISSION'));});});

test('initial runtime observes native prepared Edge content once and refuses source artifact version legacy or altered bytes before generation effects',async()=>{const subject=await import('./backend-runtime-initialize');await fixture('',async input=>{const result=await subject.initializeHostedRuntimeGeneration(input);assert.equal(result.status,'INITIAL_RUNTIME_CONFIRMED');assert.equal(state!.calls.filter(row=>row==='EDGE_BODY_OBSERVATION').length,1);});for(const mode of ['edge-source','edge-artifact','edge-version','edge-legacy','edge-body'])await fixture(mode,async input=>{const result=await subject.initializeHostedRuntimeGeneration(input);assert.equal(result.status,'REQUIRES_REVIEW',mode);assert.equal(state!.post,0);assert.equal(result.admissionResumed,false);assert.equal(state!.calls.some(row=>row.includes('pause_worker_admission')||row.includes('resume_worker_admission')||row.includes('vault.create_secret')),false);});});

test('initialization binds the optional approved host digest without stripping it or upgrading historical provider identity',async()=>{const subject=await import('./backend-runtime-initialize');for(const mode of ['host-contract-match','host-contract-changed','host-contract-missing'])await fixture(mode,async input=>{const expected=input.expected as Record<string,unknown>;expected.stagingHostContract=initialHostContract();const result=await subject.initializeHostedRuntimeGeneration(input);assert.equal(result.status,mode==='host-contract-match'?'INITIAL_RUNTIME_CONFIRMED':'REQUIRES_REVIEW',mode);if(mode!=='host-contract-match'){assert.equal(state!.post,0);assert.equal(state!.calls.some(row=>row.includes('pause_worker_admission')||row.includes('resume_worker_admission')||row.includes('vault.create_secret')),false);}else assert.equal(state!.calls.filter(row=>row==='EDGE_BODY_OBSERVATION').length,1);});});
test('late Edge metadata drift after owned drain refuses generation effects without another body download',async()=>{const subject=await import('./backend-runtime-initialize');for(const field of ['version','jwt','entrypoint','digest','status'])await fixture('late-edge-'+field,async input=>{const result=await subject.initializeHostedRuntimeGeneration(input),drift=state!.calls.indexOf('LATE_EDGE_METADATA_DRIFT');assert(drift>=0,field);assert.equal(result.status,'REQUIRES_REVIEW',field);assert.equal(state!.post,0,field);assert.equal(state!.generation,null,field);assert.equal(state!.calls.filter(row=>row==='EDGE_BODY_OBSERVATION').length,1,field);assert(state!.calls.slice(drift+1).some(row=>row==='EDGE_METADATA_GET'),field);assert.equal(state!.calls.slice(drift+1).some(row=>row.includes('vault.create_secret')||row.includes('vault.update_secret')||row.includes('resume_worker_admission')),false,field);});});
