import { createHash, randomUUID } from 'node:crypto';
import { lstat, mkdir, mkdtemp, open, readdir, readFile, readlink, realpath, rm, writeFile } from 'node:fs/promises';
import { constants, type Stats } from 'node:fs';
import { isAbsolute, join, relative, resolve, dirname, basename } from 'node:path';
import { types } from 'node:util';
import { z } from 'zod';
import { spawnOwnedProcess, stopOwnedProcesses } from '../runtime/process';

const fail=()=>Error('Protected API deployment input or execution requires review; private contents withheld.');
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
const digest=z.string().regex(/^[a-f0-9]{64}$/),imageDigest=z.string().regex(/^sha256:[a-f0-9]{64}$/);
const identitySchema=z.object({sourceSha:z.string().regex(/^[a-f0-9]{40}$/),artifactSha256:digest,teamId:z.string().regex(/^team_[A-Za-z0-9]+$/),projectId:z.string().regex(/^prj_[A-Za-z0-9]+$/),operationSha256:digest}).strict();
export type BackendProviderCliIdentity=z.infer<typeof identitySchema>;
export type BackendProviderLaunchAdmission={consume:()=>void;notAfterMs:number};
export type PreparedBackendProviderCli={readonly prepared:Readonly<{executorSourceSha:string;identitySha256:string;inputSha256:string;imageId:string;lockSha256:string;files:number;bytes:number;packages:number}>;run(admit:()=>Promise<BackendProviderLaunchAdmission>):Promise<{kind:'URL';url:string}|{kind:'UNKNOWN'}>;dispose():Promise<void>};
export const backendProviderCliFailureSchema=z.object({purpose:z.literal('CUEVO_PROVIDER_CLI_PREPARATION_FAILURE'),phase:z.enum(['SUPERVISOR','BASE','BUILD','IMAGE','CREATE','INSPECT']),ownerId:z.uuid(),cleanup:z.enum(['UNCONFIRMED','CONFIRMED_STOPPED'])}).strict();
export type BackendProviderCliFailure=z.infer<typeof backendProviderCliFailureSchema>;
export class BackendProviderCliPreparationError extends Error{
 readonly evidence:Readonly<BackendProviderCliFailure>;
 constructor(evidence:BackendProviderCliFailure){super(fail().message);this.evidence=Object.freeze(backendProviderCliFailureSchema.parse(own(evidence)));}
}
const baseImage='docker.io/library/node@sha256:ca520832af80fa37a57c14077ed0fcdd83b5aefccc356059fdc3a9a05b78ae1f';
const baseConfig='sha256:d9e872c3ee59358dc71c3c99957c2d8ccd3f21419fee87b742faddcf00a6ecee';
const docker='/usr/bin/docker',containerPath='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';
const scratch={'/scratch':'rw,noexec,nosuid,nodev,size=64m,uid=65532,gid=65532,mode=700'};
const fixedEnv={PATH:containerPath,HOME:'/scratch',TMPDIR:'/scratch',TMP:'/scratch',TEMP:'/scratch',VERCEL_CLI_USE_NATIVE_BINARY:'0',NO_UPDATE_NOTIFIER:'1',VERCEL:'1',NODE_DISABLE_COMPILE_CACHE:'1',VERCEL_TELEMETRY_DISABLED:'1'};
type Captured={name:string;bytes:Buffer;mode:number;link?:string};
function own(value:unknown,depth=0):unknown{
 if(value&&typeof value==='object'&&types.isProxy(value))throw fail();if(depth>12)throw fail();if(value===null||typeof value==='string'||typeof value==='number'&&Number.isFinite(value)||typeof value==='boolean')return value;
 if(Buffer.isBuffer(value)||value instanceof Uint8Array)return Buffer.from(value);if(value instanceof AbortSignal)return value;
 if(!value||typeof value!=='object'||types.isProxy(value)||!Array.isArray(value)&&![Object.prototype,null].includes(Object.getPrototypeOf(value)))throw fail();
 if(Array.isArray(value)&&(value.length>30000||Reflect.ownKeys(value).length!==value.length+1))throw fail();const result:Record<string,unknown>|unknown[]=Array.isArray(value)?[]:Object.create(null);
 for(const key of Reflect.ownKeys(value)){if(Array.isArray(value)&&key==='length')continue;const field=Object.getOwnPropertyDescriptor(value,key);if(typeof key!=='string'||!field||!('value'in field)||!field.enumerable)throw fail();Object.defineProperty(result,key,{value:own(field.value,depth+1),enumerable:true});}return result;
}
function requireRunner(root:string){if(process.platform!=='linux'||process.arch!=='x64'||process.version!=='v24.16.0'||process.env.GITHUB_ACTIONS!=='true'||process.env.RUNNER_ENVIRONMENT!=='github-hosted'||process.env.GITHUB_WORKSPACE!==root||!root.startsWith('/home/runner/work/')||['DOCKER_HOST','DOCKER_CONTEXT','DOCKER_CONFIG','NODE_OPTIONS','NODE_PATH'].some(key=>process.env[key]))throw fail();}
async function requireSupervisor(){const binary=await lstat(docker),socket=await lstat('/var/run/docker.sock');if(!binary.isFile()||binary.isSymbolicLink()||await realpath(docker)!==docker||binary.uid!==0||(binary.mode&0o022)!==0||!socket.isSocket()||socket.isSymbolicLink()||socket.uid!==0)throw fail();}
async function physical(root:string,path:string,kind:'file'|'directory'){
 if(!isAbsolute(root)||resolve(root)!==root||!isAbsolute(path)||resolve(path)!==path)throw fail();const part=relative(root,path);if(isAbsolute(part)||part.split(/[\\/]/).some(x=>x==='..'))throw fail();let current=root;
 for(const piece of [...part.split(/[\\/]/).filter(Boolean),'']){const stat=await lstat(current);if(stat.isSymbolicLink()||await realpath(current)!==current||(piece||current!==path?!stat.isDirectory():kind==='file'?!stat.isFile()||stat.nlink!==1:!stat.isDirectory()))throw fail();if(piece)current=join(current,piece);}
}
async function bytes(root:string,path:string,max:number){await physical(root,path,'file');const before=await lstat(path),value=await readFile(path),after=await lstat(path);if(value.length>max||before.ino!==after.ino||before.dev!==after.dev||before.size!==after.size||before.mtimeMs!==after.mtimeMs||before.ctimeMs!==after.ctimeMs)throw fail();return value;}
function samePhysical(before:Stats,after:Stats){return before.ino===after.ino&&before.dev===after.dev&&before.size===after.size&&before.mtimeMs===after.mtimeMs&&before.ctimeMs===after.ctimeMs&&before.mode===after.mode&&before.nlink===after.nlink;}
/** The recursive owner already checks each directory. Read this exact regular
 * file through one descriptor and recheck its full resolution after the await. */
async function captureRegular(prefix:string,path:string,max:number,expected?:Stats){
 const part=relative(prefix,path);if(!isAbsolute(prefix)||resolve(prefix)!==prefix||!isAbsolute(path)||resolve(path)!==path||isAbsolute(part)||part.split(/[\\/]/).some(x=>x==='..'))throw fail();
 const before=await lstat(path);if(expected&&!samePhysical(expected,before))throw fail();if(!before.isFile()||before.isSymbolicLink()||before.nlink!==1||before.size>max||await realpath(path)!==path)throw fail();
 const file=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));try{if(!samePhysical(before,await file.stat()))throw fail();const value=await file.readFile(),after=await file.stat(),leaf=await lstat(path);if(value.length>max||!samePhysical(before,after)||!samePhysical(before,leaf)||!leaf.isFile()||leaf.isSymbolicLink()||await realpath(path)!==path)throw fail();return value;}finally{await file.close();}
}
async function command(binary:string,args:string[],stdin?:Uint8Array,env:Record<string,string>={},timeoutMs=30000,signal?:AbortSignal){
 if(signal?.aborted)throw fail();const child=spawnOwnedProcess(binary,args,{env:{PATH:containerPath,LANG:'C',HOME:'/home/runner',...(binary===docker?{DOCKER_CONFIG:'/home/runner/.docker'}:{}),...env},stdio:['pipe','pipe','pipe'],shell:false,windowsHide:true});
 return new Promise<{code:number;stdout:Buffer}>((done,reject)=>{let settled=false,stopping=false,size=0;const chunks:Buffer[]=[];const finish=(code:number)=>{if(settled||stopping)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);done({code,stdout:Buffer.concat(chunks)});};const stop=()=>{if(settled||stopping)return;stopping=true;void stopOwnedProcesses([child]).then(()=>{settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);reject(fail());},()=>{settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);reject(fail());});};const abort=()=>stop(),timer=setTimeout(stop,timeoutMs);signal?.addEventListener('abort',abort,{once:true});const collect=(part:Buffer,keep:boolean)=>{size+=part.length;if(size>4*1024*1024)return stop();if(keep)chunks.push(Buffer.from(part));};child.stdout?.on('data',(part:Buffer)=>collect(part,true));child.stderr?.on('data',(part:Buffer)=>collect(part,false));child.once('error',stop);child.once('close',(code,termination)=>termination||code===null?stop():finish(code));child.stdin?.on('error',stop);child.stdin?.end(stdin);if(signal?.aborted)abort();});
}
function safeName(name:string){if(!name||name.startsWith('/')||name.includes('\\')||/[\x00-\x1f\x7f]/.test(name)||name.split('/').some(x=>!x||x==='.'||x==='..'))throw fail();}
async function captureLink(prefix:string,path:string,before:{ino:number;dev:number;mtimeMs:number;ctimeMs:number;mode:number}){
 const target=await readlink(path),resolved=await realpath(path),lexical=resolve(dirname(path),target),part=relative(prefix,lexical);
 if(isAbsolute(target)||lexical!==resolved||isAbsolute(part)||part.split(/[\\/]/).some(x=>x==='..')||!part.replaceAll('\\','/').startsWith('node_modules/'))throw fail();
 await physical(prefix,resolved,'file');const after=await lstat(path);if(before.ino!==after.ino||before.dev!==after.dev||before.mtimeMs!==after.mtimeMs||before.ctimeMs!==after.ctimeMs||before.mode!==after.mode||await readlink(path)!==target)throw fail();return target.replaceAll('\\','/');
}
// GNU long-name records preserve real dependency folder shape; all bytes and
// internal links are captured first. Docker receives no host build-context path.
function tar(files:Captured[]){const chunks:Buffer[]=[];const row=(name:string,data:Buffer,mode:number,type='0',link='')=>{const h=Buffer.alloc(512);h.write(name.slice(0,100));const oct=(offset:number,len:number,v:number)=>h.write(v.toString(8).padStart(len-1,'0')+'\0',offset,len,'ascii');oct(100,8,mode);oct(108,8,0);oct(116,8,0);oct(124,12,data.length);oct(136,12,0);h.fill(32,148,156);h.write(type,156);h.write(link.slice(0,100),157);h.write('ustar\0',257);h.write('00',263);let sum=0;for(const b of h)sum+=b;h.write(sum.toString(8).padStart(6,'0')+'\0 ',148,8);chunks.push(h,data,Buffer.alloc((512-data.length%512)%512));};for(const f of files){safeName(f.name);if(Buffer.byteLength(f.name)>99)row('././@LongLink',Buffer.from(f.name+'\0'),0o444,'L');if(f.link&&Buffer.byteLength(f.link)>99)row('././@LongLink',Buffer.from(f.link+'\0'),0o444,'K');row(f.name,f.link?Buffer.alloc(0):f.bytes,f.mode,f.link?'2':'0',f.link);}chunks.push(Buffer.alloc(1024));return Buffer.concat(chunks);}
async function installSnapshot(root:string,executorSourceSha:string,signal?:AbortSignal){
 const gitEnv={GIT_NO_REPLACE_OBJECTS:'1',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'};
 const git=async(args:string[])=>{const result=await command('/usr/bin/git',['-C',root,...args],undefined,gitEnv,15000,signal);if(result.code!==0)throw fail();return result.stdout;};
 const sourceLive=async()=>{if((await git(['rev-parse','HEAD'])).toString().trim()!==executorSourceSha||(await git(['for-each-ref','--format=%(refname)','refs/replace'])).length)throw fail();const graft=(await git(['rev-parse','--git-path','info/grafts'])).toString().trim();try{await lstat(isAbsolute(graft)?graft:resolve(root,graft));throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}};
 await sourceLive();
 const source=join(root,'scripts/verification/provider-cli'),manifestBytes=await git(['show',executorSourceSha+':scripts/verification/provider-cli/package.json']),lockBytes=await git(['show',executorSourceSha+':scripts/verification/provider-cli/package-lock.json']),physicalManifest=await bytes(root,join(source,'package.json'),65536),physicalLock=await bytes(root,join(source,'package-lock.json'),4*1024*1024),manifest=z.object({name:z.literal('cuevo-provider-cli-private'),version:z.literal('1.0.0'),private:z.literal(true),dependencies:z.object({vercel:z.literal('62.1.0')}).strict(),overrides:z.object({'@fastify/busboy':z.literal('3.2.3'),ajv:z.literal('8.20.0'),'js-yaml':z.literal('4.3.2'),minimatch:z.literal('10.2.6'),'smol-toml':z.literal('1.9.1'),tar:z.literal('7.5.22'),undici:z.literal('6.29.0'),'path-to-regexp@^8.0.0':z.literal('8.4.2'),'path-to-regexp@^8.1.0':z.literal('8.4.2'),'path-to-regexp@6.1.0':z.literal('6.3.0'),'path-to-regexp@^6.1.0':z.literal('6.3.0'),'ts-morph':z.literal('28.0.0')}).strict().optional()}).strict().parse(JSON.parse(manifestBytes.toString())),lock=z.object({name:z.literal(manifest.name),version:z.literal(manifest.version),lockfileVersion:z.literal(3),packages:z.record(z.string(),z.object({version:z.string().optional(),name:z.string().optional(),dependencies:z.record(z.string(),z.string()).optional(),resolved:z.string().optional(),integrity:z.string().optional(),optional:z.boolean().optional(),link:z.boolean().optional()}).passthrough())}).passthrough().parse(JSON.parse(lockBytes.toString()));
 if(!manifestBytes.equals(physicalManifest)||!lockBytes.equals(physicalLock))throw fail();if(lock.packages['']?.name!==manifest.name||JSON.stringify(lock.packages[''].dependencies)!==JSON.stringify(manifest.dependencies)||lock.packages['node_modules/vercel']?.version!=='62.1.0')throw fail();
 const wanted=new Map(Object.entries(lock.packages).filter(([name,row])=>name&&!row.optional));for(const[name,row]of wanted){safeName(name);if(!name.startsWith('node_modules/')||row.link||!row.version||!row.resolved?.startsWith('https://registry.npmjs.org/')||!/^sha512-[A-Za-z0-9+/]+={0,2}$/.test(row.integrity??''))throw fail();}
 const local=join(root,'.local/hosted-release');await mkdir(local,{recursive:true,mode:0o700});await physical(root,local,'directory');const folder=await mkdtemp(join(local,'provider-cli-'));await physical(root,folder,'directory');
 try{const home=join(folder,'private-home'),cache=join(folder,'private-cache'),prefix=join(folder,'input');for(const p of[home,cache,prefix])await mkdir(p,{mode:0o700});const config=join(folder,'empty-user.npmrc'),globalConfig=join(folder,'empty-global.npmrc');await writeFile(config,'',{mode:0o600});await writeFile(globalConfig,'',{mode:0o600});await writeFile(join(prefix,'package.json'),manifestBytes,{mode:0o600});await writeFile(join(prefix,'package-lock.json'),lockBytes,{mode:0o600});
  const node=await command(process.execPath,['--version'],undefined,{},15000,signal);if(node.code!==0||node.stdout.toString().trim()!=='v24.16.0')throw fail();
  const npm=join(dirname(process.execPath),'npm');const installEnv={HOME:home,TMPDIR:home,TMP:home,TEMP:home,npm_config_cache:cache,npm_config_userconfig:config,npm_config_globalconfig:globalConfig,npm_config_registry:'https://registry.npmjs.org/',NODE_DISABLE_COMPILE_CACHE:'1'};const version=await command(npm,['--version'],undefined,installEnv,15000,signal);if(version.code!==0||version.stdout.toString().trim()!=='11.17.0')throw fail();const installed=await command(npm,['ci','--prefix',prefix,'--ignore-scripts','--omit=optional','--no-audit','--no-fund'],undefined,installEnv,300000,signal);if(installed.code!==0||hash(await bytes(folder,join(prefix,'package-lock.json'),4*1024*1024))!==hash(lockBytes))throw fail();
  const files:Captured[]=[{name:'cli/package.json',bytes:manifestBytes,mode:0o444},{name:'cli/package-lock.json',bytes:lockBytes,mode:0o444}],seen=new Set<string>();let total=manifestBytes.length+lockBytes.length;
  const walk=async(directory:string)=>{const before=await lstat(directory);if(!before.isDirectory()||before.isSymbolicLink()||await realpath(directory)!==directory)throw fail();const entries=(await readdir(directory,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name));for(const entry of entries){const p=join(directory,entry.name),name=relative(prefix,p).replaceAll('\\','/');safeName(name);const stat=await lstat(p);if(stat.isSymbolicLink()){const target=await captureLink(prefix,p,stat);files.push({name:'cli/'+name,bytes:Buffer.alloc(0),mode:0o555,link:target});}
   else if(stat.isDirectory()){if(wanted.has(name)){const pkg=JSON.parse((await captureRegular(prefix,join(p,'package.json'),2*1024*1024)).toString()),expected=wanted.get(name)!;const expectedName=expected.name??name.split('/node_modules/').at(-1)!.replace(/^node_modules\//,'');if(pkg.name!==expectedName||pkg.version!==expected.version)throw fail();seen.add(name);}else if((basename(directory)==='node_modules'||basename(directory).startsWith('@')&&basename(dirname(directory))==='node_modules')&&entry.name!=='.bin'&&!entry.name.startsWith('@')&&!Array.from(wanted.keys()).some(x=>x.startsWith(name+'/')))throw fail();await walk(p);}
   else{const data=await captureRegular(prefix,p,40*1024*1024,stat);total+=data.length;if(total>256*1024*1024||files.length>=20000)throw fail();files.push({name:'cli/'+name,bytes:data,mode:stat.mode&0o111?0o555:0o444});}}
   const after=await lstat(directory);if(!samePhysical(before,after)||!after.isDirectory()||after.isSymbolicLink()||await realpath(directory)!==directory||JSON.stringify((await readdir(directory)).sort())!==JSON.stringify(entries.map(entry=>entry.name).sort()))throw fail();
  };await walk(join(prefix,'node_modules'));if(seen.size!==wanted.size||[...wanted.keys()].some(x=>!seen.has(x)))throw fail();await sourceLive();if(hash(await bytes(root,join(source,'package.json'),65536))!==hash(manifestBytes)||hash(await bytes(root,join(source,'package-lock.json'),4*1024*1024))!==hash(lockBytes))throw fail();const cli=files.find(x=>x.name==='cli/node_modules/vercel/package.json');if(!cli||JSON.parse(cli.bytes.toString()).bin?.vercel!=='./dist/vc.js'&&JSON.parse(cli.bytes.toString()).bin?.vercel!=='dist/vc.js'||!files.some(x=>x.name==='cli/node_modules/vercel/dist/vc.js'))throw fail();return{files,lockSha256:hash(lockBytes),packages:seen.size};
 }finally{await physical(root,folder,'directory');await rm(folder,{recursive:true});}
}

/** Provider-only prepared input. Approval, native lease and durable original
 * upload identity remain owned by backend-provider-deploy, never by this helper. */
export async function createBackendProviderCli(value:unknown):Promise<PreparedBackendProviderCli>{
 let input:{repoRoot:string;executorSourceSha:string;identity:BackendProviderCliIdentity;artifactFiles:{path:string;bytes:Buffer}[];expiresAtMs:number;token:string;timeoutMs:number;signal?:AbortSignal};
 try{input=z.object({repoRoot:z.string(),executorSourceSha:z.string().regex(/^[a-f0-9]{40}$/),identity:identitySchema,artifactFiles:z.array(z.object({path:z.string(),bytes:z.instanceof(Buffer)}).strict()).min(1).max(20000),expiresAtMs:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),token:z.string().min(20).max(4096).regex(/^[\x21-\x7e]+$/),timeoutMs:z.number().int().min(100).max(1200000).default(1200000),signal:z.instanceof(AbortSignal).optional()}).strict().parse(own(value));requireRunner(input.repoRoot);if(input.signal?.aborted||Date.now()>=input.expiresAtMs)throw fail();for(const row of input.artifactFiles){safeName(row.path);if(!row.path.startsWith('.vercel/output/')||row.bytes.length>32*1024*1024)throw fail();}if(new Set(input.artifactFiles.map(x=>x.path)).size!==input.artifactFiles.length)throw fail();}catch{throw fail();}
 const graph=await installSnapshot(input.repoRoot,input.executorSourceSha,input.signal),project=Buffer.from(JSON.stringify({orgId:input.identity.teamId,projectId:input.identity.projectId})),files:Captured[]=[...graph.files,...input.artifactFiles.map(x=>({name:'delivery/'+x.path,bytes:x.bytes,mode:0o444})),{name:'delivery/.vercel/project.json',bytes:project,mode:0o444}];let total=0;for(const row of files)total+=row.bytes.length;if(total>384*1024*1024)throw fail();
 const identitySha256=hash(JSON.stringify(input.identity)),inputSha256=hash(JSON.stringify({executorSourceSha:input.executorSourceSha,identity:input.identity,lock:graph.lockSha256,baseImage,baseConfig,files:files.map(x=>({name:x.name,sha256:hash(x.bytes),mode:x.mode,link:x.link??null}))}));
 const owner=randomUUID(),tag='cuevo-provider-private:'+owner,name='cuevo-provider-'+owner;
 const args=['--global-config','/scratch/config','deploy','--prebuilt','--yes','--target=preview','--meta','cuevoCommitSha='+input.identity.sourceSha,'--meta','cuevoArtifactSha256='+input.identity.artifactSha256,'--meta','cuevoProviderOperation='+input.identity.operationSha256,'--scope',input.identity.teamId];
 const gate=Buffer.from('set -euo pipefail\nIFS= read -r deadline\n[[ "$deadline" =~ ^[0-9]{1,16}$ ]] || exit 124\nnow=$(/usr/bin/date +%s%3N)\n(( now < deadline )) || exit 124\nexec /usr/local/bin/node --no-global-search-paths /cuevo/cli/node_modules/vercel/dist/vc.js "$@"\n');
 const sums=Buffer.from(files.filter(x=>!x.link).map(x=>hash(x.bytes)+'  /cuevo/'+x.name+'\n').join(''));
 const dockerfile=Buffer.from(`FROM ${baseImage}\nUSER root\nCOPY . /cuevo/\nRUN /usr/bin/sha256sum -c /cuevo/files.sha256 && /bin/mkdir -p /delivery /scratch && /bin/cp -a /cuevo/delivery/. /delivery/ && /bin/chmod -R a+rX /cuevo /delivery && /bin/chown 65532:65532 /scratch && /usr/local/bin/node --version | /bin/grep -Fx v24.16.0\nENV ${Object.entries(fixedEnv).map(([key,v])=>key+'='+v).join(' ')}\nLABEL cuevo.provider.owner=${owner} cuevo.provider.input=${inputSha256}\nWORKDIR /delivery\nUSER 65532:65532\nRUN /usr/local/bin/node --no-global-search-paths /cuevo/cli/node_modules/vercel/dist/vc.js --global-config /scratch/config --version | /bin/grep -Fx 62.1.0 && /usr/local/bin/node --no-global-search-paths /cuevo/cli/node_modules/vercel/dist/vc.js --global-config /scratch/config deploy --help >/dev/null\nENTRYPOINT ["/bin/bash","/cuevo/launch.sh"]\nCMD []\n`);
 let imageId:string|undefined,containerId:string|undefined,phase:BackendProviderCliFailure['phase']='SUPERVISOR',buildAttempted=false,createAttempted=false,buildAcknowledged=false,createAcknowledged=false,attempted=false,closing=false,disposed=false,active:Promise<{kind:'URL';url:string}|{kind:'UNKNOWN'}>|undefined,expectedEnv:string[]=[];
 const inspect=async()=>{if(!imageId||!containerId)throw fail();const result=await command(docker,['inspect',containerId]);if(result.code!==0)throw fail();const row=z.array(z.object({Id:z.literal(containerId),Name:z.literal('/'+name),Image:z.literal(imageId),Config:z.object({Image:z.literal(imageId),User:z.literal('65532:65532'),WorkingDir:z.literal('/delivery'),Entrypoint:z.array(z.string()),Cmd:z.array(z.string()),Env:z.array(z.string()),OpenStdin:z.literal(true),StdinOnce:z.literal(true),Tty:z.literal(false)}),HostConfig:z.object({ReadonlyRootfs:z.literal(true),CapDrop:z.array(z.string()),SecurityOpt:z.array(z.string()),Privileged:z.literal(false),NetworkMode:z.literal('host'),Binds:z.null(),Tmpfs:z.record(z.string(),z.string()),AutoRemove:z.literal(false)}),Mounts:z.array(z.unknown()),State:z.object({Status:z.string(),Running:z.boolean(),Paused:z.literal(false),Restarting:z.literal(false),Dead:z.boolean(),ExitCode:z.number().int(),Error:z.literal('')})})).length(1).parse(JSON.parse(result.stdout.toString()))[0];if(JSON.stringify(row.Config.Entrypoint)!==JSON.stringify(['/bin/bash','/cuevo/launch.sh'])||JSON.stringify(row.Config.Cmd)!==JSON.stringify(args)||JSON.stringify([...row.Config.Env].sort())!==JSON.stringify([...expectedEnv].sort())||JSON.stringify(row.HostConfig.CapDrop)!==JSON.stringify(['ALL'])||JSON.stringify(row.HostConfig.SecurityOpt)!==JSON.stringify(['no-new-privileges'])||JSON.stringify(row.HostConfig.Tmpfs)!==JSON.stringify(scratch))throw fail();if(row.Mounts.length)z.array(z.object({Type:z.literal('tmpfs'),Destination:z.literal('/scratch'),Source:z.literal('').optional(),RW:z.literal(true),Propagation:z.literal('').optional(),Mode:z.string().optional(),Driver:z.literal('').optional(),Name:z.literal('').optional()}).strict()).length(1).parse(row.Mounts);return row;};
 const stop=async()=>{const row=await inspect();if(row.State.Running){if((await command(docker,['kill',containerId!])).code!==0)throw fail();}const after=await inspect();if(after.State.Running||!['created','exited','dead'].includes(after.State.Status))throw fail();};
 const dispose=async()=>{closing=true;if(disposed)return;if(active)await active.catch(()=>undefined);if(containerId){await stop();if((await command(docker,['rm',containerId])).code!==0)throw fail();const missing=await command(docker,['container','ls','--all','--no-trunc','--quiet','--filter','id='+containerId]);if(missing.code!==0||missing.stdout.toString().trim())throw fail();containerId=undefined;}if(imageId){if((await command(docker,['rmi',imageId])).code!==0)throw fail();const missing=await command(docker,['image','ls','--quiet','--no-trunc','--filter','reference='+tag]);if(missing.code!==0||missing.stdout.toString().trim())throw fail();imageId=undefined;}disposed=true;};
 try{await requireSupervisor();phase='BASE';if((await command(docker,['pull','--platform=linux/amd64',baseImage],undefined,{},300000,input.signal)).code!==0)throw fail();const raw=await command(docker,['buildx','imagetools','inspect','--raw',baseImage],undefined,{},30000,input.signal);if(raw.code!==0)throw fail();z.object({schemaVersion:z.literal(2),config:z.object({digest:z.literal(baseConfig)})}).passthrough().parse(JSON.parse(raw.stdout.toString()));if(hash(raw.stdout)!==baseImage.split('@sha256:')[1])throw fail();const base=await command(docker,['image','inspect',baseImage]);if(base.code!==0)throw fail();const baseRow=z.array(z.object({Id:imageDigest,RepoDigests:z.array(z.string()),Os:z.literal('linux'),Architecture:z.literal('amd64'),Config:z.object({Volumes:z.null(),Env:z.array(z.string())})})).length(1).parse(JSON.parse(base.stdout.toString()))[0];if(!baseRow.RepoDigests.includes('node@'+baseImage.split('@')[1])||!baseRow.Config.Env.includes('NODE_VERSION=24.16.0'))throw fail();
  phase='BUILD';buildAttempted=true;const built=await command(docker,['build','--quiet','--network=none','--pull=false','--platform=linux/amd64','--tag',tag,'-'],tar([...files,{name:'launch.sh',bytes:gate,mode:0o444},{name:'files.sha256',bytes:sums,mode:0o444},{name:'Dockerfile',bytes:dockerfile,mode:0o444}]),{},300000,input.signal);if(built.code!==0)throw fail();imageId=imageDigest.parse(built.stdout.toString().trim());buildAcknowledged=true;
  phase='IMAGE';const checked=await command(docker,['image','inspect',imageId]);if(checked.code!==0)throw fail();const config=z.array(z.object({Id:z.literal(imageId),Os:z.literal('linux'),Architecture:z.literal('amd64'),Config:z.object({Volumes:z.null(),Labels:z.object({'cuevo.provider.owner':z.literal(owner),'cuevo.provider.input':z.literal(inputSha256)}),User:z.literal('65532:65532'),WorkingDir:z.literal('/delivery'),Entrypoint:z.array(z.string()),Cmd:z.array(z.string()).nullable(),Env:z.array(z.string())})})).length(1).parse(JSON.parse(checked.stdout.toString()))[0].Config;if(JSON.stringify(config.Entrypoint)!==JSON.stringify(['/bin/bash','/cuevo/launch.sh'])||config.Cmd?.length||new Set(config.Env.map(x=>x.split('=',1)[0])).size!==config.Env.length||config.Env.some(x=>!['NODE_VERSION','YARN_VERSION',...Object.keys(fixedEnv)].includes(x.split('=',1)[0]))||!config.Env.includes('NODE_VERSION=24.16.0')||Object.entries(fixedEnv).some(([key,v])=>!config.Env.includes(key+'='+v)))throw fail();expectedEnv=[...config.Env,'VERCEL_TOKEN='+input.token,'VERCEL_ORG_ID='+input.identity.teamId,'VERCEL_PROJECT_ID='+input.identity.projectId];
  phase='CREATE';createAttempted=true;const created=await command(docker,['create','--name',name,'--read-only','--cap-drop=ALL','--security-opt=no-new-privileges','--user','65532:65532','--network=host','--interactive','--env','VERCEL_TOKEN','--env','VERCEL_ORG_ID','--env','VERCEL_PROJECT_ID','--tmpfs','/scratch:'+scratch['/scratch'],imageId,...args],undefined,{VERCEL_TOKEN:input.token,VERCEL_ORG_ID:input.identity.teamId,VERCEL_PROJECT_ID:input.identity.projectId},30000,input.signal);if(created.code!==0)throw fail();containerId=z.string().regex(/^[a-f0-9]{64}$/).parse(created.stdout.toString().trim());createAcknowledged=true;phase='INSPECT';if((await inspect()).State.Status!=='created'||input.signal?.aborted)throw fail();
 }catch{let confirmed=false;try{if(buildAttempted&&!imageId){const found=await command(docker,['image','ls','--quiet','--no-trunc','--filter','reference='+tag,'--filter','label=cuevo.provider.owner='+owner]);if(found.code!==0)throw fail();const ids=found.stdout.toString().trim().split('\n').filter(Boolean);if(ids.length>1)throw fail();if(ids.length)imageId=imageDigest.parse(ids[0]);}if(createAttempted&&!containerId){const found=await command(docker,['container','ls','--all','--no-trunc','--quiet','--filter','name=^/'+name+'$']);if(found.code!==0)throw fail();const ids=found.stdout.toString().trim().split('\n').filter(Boolean);if(ids.length>1)throw fail();if(ids.length)containerId=z.string().regex(/^[a-f0-9]{64}$/).parse(ids[0]);}await dispose();confirmed=(!buildAttempted||buildAcknowledged)&&(!createAttempted||createAcknowledged);}catch{/* Unknown owner cleanup remains review, never a second upload. */}throw new BackendProviderCliPreparationError({purpose:'CUEVO_PROVIDER_CLI_PREPARATION_FAILURE',phase,ownerId:owner,cleanup:confirmed?'CONFIRMED_STOPPED':'UNCONFIRMED'});}
 const prepared=Object.freeze({executorSourceSha:input.executorSourceSha,identitySha256,inputSha256,imageId,lockSha256:graph.lockSha256,files:files.length,bytes:total,packages:graph.packages});
 const run=async(admit:()=>Promise<BackendProviderLaunchAdmission>):Promise<{kind:'URL';url:string}|{kind:'UNKNOWN'}>=>{if(attempted||closing||disposed)return{kind:'UNKNOWN'};attempted=true;let deadline:number;try{if(typeof admit!=='function'||input.signal?.aborted)throw fail();const before=await inspect();if(closing||before.State.Status!=='created'||before.State.Running)throw fail();const admission=await admit();if(closing)throw fail();if(!admission||types.isProxy(admission)||![Object.prototype,null].includes(Object.getPrototypeOf(admission)))throw fail();const fields=Object.getOwnPropertyDescriptors(admission);if(Reflect.ownKeys(fields).sort().join(',')!=='consume,notAfterMs'||Object.values(fields).some(x=>!('value'in x)||!x.enumerable)||typeof fields.consume.value!=='function')throw fail();deadline=z.number().int().positive().max(input.expiresAtMs).parse(fields.notAfterMs.value);const after=await inspect();if(closing||after.State.Status!=='created'||after.State.Running||input.signal?.aborted||Date.now()>=deadline)throw fail();fields.consume.value();if(closing||input.signal?.aborted||Date.now()>=deadline)throw fail();}catch{return{kind:'UNKNOWN'};}
  active=(async()=>{try{if(closing||input.signal?.aborted||Date.now()>=deadline)throw fail();const result=await command(docker,['start','--attach','--interactive',containerId!],Buffer.from(String(deadline)+'\n'),{},input.timeoutMs,input.signal);const after=await inspect();if(after.State.Running||after.State.Status!=='exited'||after.State.ExitCode!==0||result.code!==0||input.signal?.aborted)throw fail();const url=result.stdout.toString().trim();if(!/^https:\/\/[a-z0-9-]+\.vercel\.app\/?$/.test(url)||url.includes(input.token))throw fail();return{kind:'URL' as const,url:url.replace(/\/$/,'')};}catch{await stop();return{kind:'UNKNOWN' as const};}})();return active;
 };
 return Object.freeze({prepared,run,dispose});
}
