import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createHash, createHmac } from 'node:crypto';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { registerHooks } from 'node:module';
import { transformSync } from 'esbuild';
import * as actualFiles from 'node:fs/promises';
import type {NativeBackendAdmissionHandle} from './backend-release-admission';

const sha='a'.repeat(40),ref='mqxdjvsyckzocokuikmx',auth=`https://${ref}.supabase.co`,host='aws-0-ap-southeast-1.pooler.supabase.com',api='https://cuevo-api-fixture.vercel.app';
const hash=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex');
const manifest=readFileSync(resolve(import.meta.dirname,'../../supabase/seed/identities.json'));
let mode='normal';
const calls:string[]=[];
const secret='private-activation-fixture-token';
const fixtureState={key:'',enabled:false,endpoint:null as string|null,name:null as string|null,cron:0,event:'10000000-0000-4000-8000-000000000099',wake:'10000000-0000-4000-8000-000000000098',source:'10000000-0000-4000-8000-000000000001',processed:false,recoveryReleased:false,recoveryRelease:null as string|null};
let durableState:unknown=null;
let preparationCount=0,disposalCount=0,preparedHandle:object|undefined,preparedBinding:unknown;
const admissionRecords=new WeakMap<object,{binding:unknown;disposed:boolean}>();
Object.assign(globalThis,{activationFixture:{
 validate:(v:unknown)=>v,admission:async(input:{expected:unknown})=>{calls.push('admission');if(mode==='admission'||mode==='late-admission'&&calls.includes('connect'))throw Error(secret);return{expected:input.expected,observedAt:new Date().toISOString(),approval:{packageSha256:'b'.repeat(64)}};},
 prepare:async(input:Record<string,unknown>)=>{assert.equal(calls.includes('connect'),false);calls.push('prepare');preparationCount++;preparedHandle=Object.freeze({});preparedBinding={repoRoot:input.repoRoot,expected:input.expected,prepared:input.prepared,effectScope:input.effectScope};admissionRecords.set(preparedHandle,{binding:preparedBinding,disposed:false});return preparedHandle;},
 read:async(handle:object,binding:{expected:unknown})=>{const record=admissionRecords.get(handle);assert(record&&!record.disposed);assert.deepEqual(record.binding,binding);return(globalThis as unknown as{activationFixture:{admission:(input:{expected:unknown})=>Promise<unknown>}}).activationFixture.admission(binding);},
 dispose:(handle:object)=>{const record=admissionRecords.get(handle);assert(record&&!record.disposed);record.disposed=true;calls.push('dispose');disposalCount++;preparedHandle=undefined;},
 runtime:()=>({api:{DATABASE_URL:`postgresql://cuevo_api.${ref}:api-password@${host}:5432/postgres`,CUEVO_DATABASE_TLS_CA:'-----BEGIN CERTIFICATE-----\nfixture\n-----END CERTIFICATE-----',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_fixture_key',SUPABASE_SERVICE_ROLE_KEY:'sb_secret_fixture_key'},edge:{CUEVO_WORKER_DATABASE_URL:`postgresql://cuevo_worker.${ref}:worker-password@${host}:5432/postgres`,CUEVO_WORKER_TLS_CA:'-----BEGIN CERTIFICATE-----\nfixture\n-----END CERTIFICATE-----',CUEVO_WORKER_WAKE_KEY:'',CUEVO_WORKER_EXECUTION_MODE:'synthetic-staging',POSTHOG_CAPTURE_MODE:'DISABLED'},runtimeSha256:hash('runtime')}),
 provider:async()=>({projectRef:ref,projectStatus:'ACTIVE_HEALTHY',directEndpoint:{projectRef:ref,kind:'direct',host:`db.${ref}.supabase.co`,port:5432,database:'postgres'},sessionEndpoint:{projectRef:ref,kind:'session-pooler',host,port:5432,database:'postgres'}}),
 endpoint:(v:unknown)=>v,
 prerequisites:async(_input:unknown,borrowed?:object)=>{assert.equal(borrowed,preparedHandle);return{status:mode==='prerequisites'?'REQUIRES_REVIEW':'PREREQUISITES_OBSERVED',apiReady:true,roleSessions:5,crossSchoolDenied:true};},
 private:async(input:{purpose:string},borrowed?:object)=>{assert.equal(borrowed,preparedHandle);calls.push('private');assert.equal(input.purpose,'PRE_ACTIVATION');return{status:mode==='private'?'REQUIRES_REVIEW':'PRIVATE_PROBES_CONFIRMED',freshProof:mode!=='private-stale',restrictedDatabaseGrants:true,privateStorage:true,privateRealtime:true,sessionsClosed:true};},
 peer:()=>({encrypted:true,authorized:mode!=='tls',getPeerCertificate:()=>({raw:Buffer.from('fixture')}),getProtocol:()=> 'TLSv1.3'}),
 identity:()=>undefined,
 Client:class{
  connection={stream:(globalThis as unknown as {activationFixture:{peer:()=>object}}).activationFixture.peer()};
  constructor(public config:Record<string,unknown>){calls.push('client');assert.equal((config.ssl as {rejectUnauthorized:boolean}).rejectUnauthorized,true);assert.equal((config.ssl as {minVersion:string}).minVersion,'TLSv1.2');assert.equal(config.host,host);assert.equal(config.port,5432);assert.equal(config.database,'postgres');}
  async connect(){calls.push('connect');}on(event:string,callback:()=>void){if(event==='error')Object.assign(globalThis,{activationIdleLoss:callback});return this;}async end(){calls.push('close');if(mode==='initial-close')throw Error(secret);}
  async query(sql:string,args:unknown[]=[]){calls.push(sql.split('\n')[0]);
   if(sql.includes('CUEVO_ACTIVE_RUNTIME_READ'))return{rows:durableState===null?[]:[{id:'10000000-0000-4000-8000-000000000096',decrypted_secret:JSON.stringify(durableState)}]};
   if(sql.includes('CUEVO_ACTIVE_RUNTIME_SAVE')){durableState=JSON.parse(String(sql.includes('update_secret')?args[1]:args[0]));return{rows:[]};}
   if(sql.includes('CUEVO_ACTIVATION_IDENTITY'))return{rows:[{operator:'postgres',database:'postgres',ssl:true,serverVersion:170011}]};
   if(sql.includes('pg_try_advisory_lock'))return{rows:[{locked:true}]};
   if(sql.includes('pg_advisory_unlock'))return{rows:[{released:mode!=='initial-unlock'}]};
   if(sql.includes('CUEVO_ACTIVATION_SOURCE'))return{rows:[{people:133,synthetic:true,populationMatches:true,schools:2,currentActors:true,transportPrivate:mode!=='transport',analyticsDisabled:true,workerReady:true,cronAvailable:true}]};
   if(sql.includes('CUEVO_ACTIVATION_PRE_KEY'))return{rows:[{transportPrivate:mode!=='transport-after-probes',synthetic:true,analyticsDisabled:true}]};
   if(sql.includes('CUEVO_ACTIVATION_CONTROL'))return{rows:[{enabled:fixtureState.enabled,endpoint:fixtureState.endpoint,vault_secret_name:mode==='foreign-dispatch'&&fixtureState.enabled?'foreign_operator':fixtureState.name,allow_local:false,state:fixtureState.enabled?'IDLE':'DISABLED',wake_id:null,lease_expires_at:null,network_request_id:null}]};
   if(sql.includes('CUEVO_ACTIVATION_CRON'))return{rows:fixtureState.cron?[{jobid:fixtureState.cron,jobname:'cuevo-worker-recovery',schedule:'* * * * *',command:'select internal.request_worker_wake();',database:'postgres',username:'postgres',active:true}]:[]};
   if(sql.includes('vault.create_secret'))return{rows:[{id:'10000000-0000-4000-8000-000000000097'}]};
   if(sql.includes('CUEVO_ACTIVATION_VAULT'))return{rows:[{count:1,matching:true}]};
   if(sql.includes('configure_worker_dispatch')){fixtureState.enabled=args[0]===true;fixtureState.endpoint=fixtureState.enabled?String(args[1]):null;fixtureState.name=fixtureState.enabled?String(args[2]):null;return{rows:[{configured:true}]};}
   if(sql.includes('cron.schedule')){fixtureState.cron=42;return{rows:[{jobid:42}]};}
   if(sql.includes('cron.unschedule')){fixtureState.cron=0;return{rows:[{removed:true}]};}
   if(sql.includes('CUEVO_ACTIVATION_SCHOOL'))return{rows:[{name:'Cuevo Reference Academy – Doha',country_code:'QA',languages:['en','ar']}]};
   if(sql.includes('CUEVO_ACTIVATION_EVENT'))return{rows:[{id:fixtureState.event,entity_id:fixtureState.source,entity_type:'school_operation',type:'school.updated',version:1,actor_id:'20000000-0000-4000-8000-000000000001',school_id:'10000000-0000-4000-8000-000000000001',state:fixtureState.processed?'COMPLETED':'PENDING',processed:fixtureState.processed,audit:true,command_count:1}]};
   if(sql.includes('CUEVO_ACTIVATION_GENERATION'))return{rows:[{wake_id:fixtureState.wake,state:'REQUESTED',network_request_id:12}]};
   if(sql.includes('request_worker_wake'))return{rows:[{requested:true}]};
   if(sql.includes('CUEVO_ACTIVATION_HEALTH'))return{rows:[{ready:true,transportPrivate:true,enabled:true,state:'IDLE',pending:0,processing:0,failed:0}]};
   if(sql.includes('CUEVO_RECOVERY_CONTROL'))return{rows:[{enabled:true,endpoint:fixtureState.endpoint,vault_secret_name:fixtureState.name,allow_local:false,state:'IDLE',wake_id:null,lease_expires_at:null,network_request_id:null,failure_count:0,last_error_code:null,last_requested_at:fixtureState.recoveryReleased?fixtureState.recoveryRelease:null,last_started_at:fixtureState.recoveryReleased?fixtureState.recoveryRelease:null,last_finished_at:fixtureState.recoveryReleased?fixtureState.recoveryRelease:null,last_processed_count:fixtureState.recoveryReleased?1:0}]};
   if(sql.includes('CUEVO_RECOVERY_BASELINE')||sql.includes('CUEVO_RECOVERY_FINAL'))return{rows:[{pending:mode==='recovery-backlog'?1:0,processing:0,transportPrivate:true,analyticsDisabled:true}]};
   if(sql.includes('CUEVO_RECOVERY_CRON_JOB'))return{rows:[{jobid:42,jobname:'cuevo-worker-recovery',schedule:'* * * * *',command:'select internal.request_worker_wake();',database:'postgres',username:'postgres',active:true}]};
   if(sql.includes('CUEVO_RECOVERY_EVENT'))return{rows:[{id:'93000000-0000-4000-8000-000000000001',school_id:'10000000-0000-4000-8000-000000000001',actor_id:'20000000-0000-4000-8000-000000000001',entity_id:fixtureState.source,type:'school.updated',entity_type:'school_operation',version:1,state:fixtureState.recoveryReleased?'COMPLETED':'PENDING',attempt_count:fixtureState.recoveryReleased?1:0,lease_token:null,lease_until:null,completed_at:fixtureState.recoveryReleased?fixtureState.recoveryRelease:null,processed:fixtureState.recoveryReleased,audit:true,command_count:1}]};
   if(sql.includes('CUEVO_RECOVERY_RELEASE_TIME')){fixtureState.recoveryRelease=new Date().toISOString();fixtureState.recoveryReleased=true;return{rows:[{releasedAt:fixtureState.recoveryRelease}]};}
   if(sql.includes('CUEVO_RECOVERY_CRON_RUN'))return{rows:[{runid:4,jobid:42,status:'succeeded',start_time:fixtureState.recoveryRelease,end_time:fixtureState.recoveryRelease}]};
   if(sql==='COMMIT'&&fixtureState.recoveryRelease)fixtureState.recoveryReleased=true;
   if(sql==='COMMIT'&&mode==='cron-commit-unknown'&&fixtureState.cron>0)throw Error(secret);
   if(['BEGIN','COMMIT','ROLLBACK'].includes(sql)||sql.startsWith('BEGIN ')||sql.startsWith('SET '))return{rows:[]};
   throw Error('Unexpected fixed SQL fixture');
  }
 }
}});
Object.assign(globalThis,{activationFiles:{...actualFiles,open:async(path:string,flags:string,permissions:number)=>{const handle=await actualFiles.open(path,flags,permissions),terminal=path.endsWith('worker-activation-result.json');return{writeFile:async(value:string)=>handle.writeFile(value),sync:async()=>{if(terminal&&mode==='terminal-sync')throw Error(secret);await handle.sync();},close:async()=>{await handle.close();if(terminal&&mode==='terminal-close')throw Error(secret);}};}}});
registerHooks({resolve(specifier,context,next){if(['./backend-release-contracts','./backend-release-admission','./backend-provider-deploy','./backend-hosted-verification','./backend-hosted-private','../database/hosted-migration-provider'].includes(specifier))return{shortCircuit:true,url:new URL(specifier+'.ts',context.parentURL).href};return next(specifier,context);},load(url,context,next){
 const name=url.split('/').at(-1),fixture='globalThis.activationFixture';if(name==='backend-hosted-activation-confirmation.ts')return{format:'module',shortCircuit:true,source:'export const confirmHostedWorkerActivation=(...args)=>globalThis.activationConfirm(...args);'};if (name === 'backend-preview-transport.ts') return { format: 'module', shortCircuit: true, source: 'export const createBackendPreviewTransport=async()=>({status:"CONFIRMED"});export const backendPreviewHeaders=async input=>new URL(input.url).origin===new URL(input.apiDeployment.url).origin?{"x-vercel-protection-bypass":"private-gateway-canary"}:{};' };
 const replacements:Record<string,string>={'backend-release-contracts.ts':`export const validatePreparedBackendReleaseIntent=${fixture}.validate;`,'backend-release-admission.ts':`export const readBackendReleaseAdmission=${fixture}.admission;export const prepareNativeBackendReleaseAdmission=${fixture}.prepare;export const readNativeBackendReleaseAdmission=${fixture}.read;export const disposeNativeBackendReleaseAdmission=${fixture}.dispose;`,'backend-provider-deploy.ts':`export const prepareHostedRuntimeRecipients=${fixture}.runtime;`,'backend-hosted-verification.ts':`export const verifyHostedBackendPrerequisites=${fixture}.prerequisites;`,'backend-hosted-private.ts':`export const verifyHostedPrivateAccess=${fixture}.private;`,'hosted-migration-provider.ts':`export const readHostedMigrationProvider=${fixture}.provider;export const requireCurrentHostedMigrationEndpoint=${fixture}.endpoint;`};
 if(name&&replacements[name])return{format:'module',shortCircuit:true,source:replacements[name]};
 if(name==='backend-hosted-activation.ts')return{format:'module',shortCircuit:true,source:transformSync(readFileSync(new URL(url),'utf8').replace("import { Client } from 'pg';",`const Client=${fixture}.Client;`).replace("import { lstat, mkdir, open, readFile, realpath } from 'node:fs/promises';",'const {lstat,mkdir,open,readFile,realpath}=globalThis.activationFiles;').replace("checkServerIdentity(url.hostname,stream.getPeerCertificate())",`${fixture}.identity()`),{loader:'ts',format:'esm'}).code};return next(url,context);
}});
async function subject(){let module:Record<string,unknown>={};try{module=await import(pathToFileURL(resolve(import.meta.dirname,'backend-hosted-activation.ts')).href);}catch(error){if((error as NodeJS.ErrnoException).code!=='ERR_MODULE_NOT_FOUND')throw error;}assert.equal(typeof module.activateHostedWorker,'function');return module as typeof import('./backend-hosted-activation');}
async function fixture(selected:string,run:(input:Record<string,unknown>,root:string)=>Promise<void>){const root=await mkdtemp(join(tmpdir(),'cuevo-activation-')),fetchPrevious=globalThis.fetch;mode=selected;calls.length=0;Object.assign(fixtureState,{key:'',enabled:false,endpoint:null,name:null,cron:0,processed:false,recoveryReleased:false,recoveryRelease:null});
 preparationCount=0;disposalCount=0;preparedHandle=undefined;preparedBinding=undefined;
 durableState=null;Object.assign(globalThis,{activationConfirm:async(_input?:unknown,borrowed?:object)=>{if(preparedHandle)assert.equal(borrowed,preparedHandle);calls.push('confirmation');const state=durableState as {phase:string;cleanup:unknown};if(mode.startsWith('confirmation-'))return{status:'REQUIRES_REVIEW',canonicalReceipt:null,lockReleased:mode!=='confirmation-unlock',sessionClosed:mode!=='confirmation-close'};state.phase='CONFIRMED';state.cleanup={lockReleased:true,sessionsClosed:true};return{status:'ORIGINAL_ACTIVATION_CONFIRMED',canonicalReceipt:'{}',lockReleased:true,sessionClosed:true};}});
 try{await mkdir(join(root,'.local/hosted-release'),{recursive:true});await mkdir(join(root,'supabase/seed'),{recursive:true});await writeFile(join(root,'supabase/seed/identities.json'),manifest);const observedAt=new Date().toISOString(),artifact={sourceSha:sha,dataApi:'DISABLED',observer:'Authenticated operator',status:'OBSERVED_PROVIDER_UI',visibleText:'Data API is disabled',observedAt,projectRef:ref,source:`https://supabase.com/dashboard/project/${ref}/integrations/data_api/settings`};const bytes=JSON.stringify(artifact);void bytes;
 const input={repoRoot:root,expected:{releaseSha:sha,treeSha:'b'.repeat(40),releaseRunId:'51',runAttempt:1,targets:{api:{teamId:'team_Cuevo',projectId:'prj_Api'},supabase:{projectRef:ref,authOrigin:auth,edgeOrigin:auth+'/functions/v1/cuevo-worker'}},fingerprints:{migrationEndpointSha256:hash('endpoint')}},preparedApproval:{sha256:hash('package'),canonicalJson:JSON.stringify({expiresAt:new Date(Date.now()+3600000).toISOString()})},githubToken:secret,providerToken:secret,vercelToken:secret,runtimeConfig:{},apiDeployment:{url:api,id:'dpl_fixture'},edgeDeployment:{id:'edge_fixture',version:1},syntheticPassword:'protected-synthetic-password',operatorDatabaseUrl:`postgresql://postgres.${ref}@${host}:5432/postgres?sslmode=verify-full`,operatorPassword:'protected-operator-password',prerequisitesReceipt:{status:'PREREQUISITES_OBSERVED'},privateReceipt:{status:'PRIVATE_PROBES_CONFIRMED',sessionsClosed:true}};
 globalThis.fetch=async(raw,options)=>{const url=new URL(String(raw)),headers=new Headers(options?.headers);calls.push((options?.method??'GET')+':'+url.pathname); const gateway = new Headers(options?.headers).get('x-vercel-protection-bypass'); assert.equal(gateway, url.origin === api ? 'private-gateway-canary' : null); if (url.origin === api && url.pathname !== '/health/live' && url.pathname !== '/health/ready') assert.match(new Headers(options?.headers).get('Authorization') ?? '', /^Bearer /);
  if(url.origin==='https://api.supabase.com'&&url.pathname.endsWith('/postgrest')){const response=Response.json({db_schema:mode==='data-api-enabled'?'public':mode==='data-api-unknown'?null:'',jwt_secret:secret});Object.defineProperty(response,'url',{value:url.href});return response;}
  if(url.origin==='https://api.vercel.com')return Response.json({id:'dpl_fixture',projectId:'prj_Api',ownerId:'team_Cuevo',url:new URL(api).hostname,readyState:'READY',target:'preview',meta:{cuevoCommitSha:sha}});
  if(url.origin==='https://api.supabase.com'&&url.pathname.endsWith('/functions/cuevo-worker'))return Response.json({id:'edge_fixture',slug:'cuevo-worker',status:'ACTIVE',version:1,verify_jwt:false});
  if(url.origin==='https://api.supabase.com'&&url.pathname.endsWith('/secrets')){if(options?.method==='POST'){fixtureState.key=JSON.parse(String(options.body))[0].value;if(mode==='key-unknown')throw Error(secret);return new Response(null,{status:201});}if(mode==='idle-loss')(globalThis as unknown as {activationIdleLoss:()=>void}).activationIdleLoss();return Response.json([{name:'CUEVO_WORKER_WAKE_KEY',value:hash(fixtureState.key)}, {name:'CUEVO_WORKER_DATABASE_URL',value:hash(`postgresql://cuevo_worker.${ref}:worker-password@${host}:5432/postgres`)},{name:'CUEVO_WORKER_TLS_CA',value:hash('-----BEGIN CERTIFICATE-----\nfixture\n-----END CERTIFICATE-----')},{name:'CUEVO_WORKER_EXECUTION_MODE',value:hash('synthetic-staging')},{name:'POSTHOG_CAPTURE_MODE',value:hash('DISABLED')}]);}
  if(url.pathname==='/auth/v1/token')return Response.json({access_token:'protected-native-probe-session',user:{id:'20000000-0000-4000-8000-000000000001',email:'synthetic-001@cuevo.test'}});
  if(url.pathname==='/auth/v1/logout'){if(mode==='logout')throw Error(secret);return new Response(null,{status:204});}
  if(url.pathname==='/v1/school/details')return Response.json({id:fixtureState.source,schoolId:'10000000-0000-4000-8000-000000000001',command:'details.update'});
  if(url.pathname==='/functions/v1/cuevo-worker'){const body=JSON.parse(String(options?.body));if(!headers.get('X-Cuevo-Wake-Signature')||headers.get('X-Cuevo-Wake-Signature')!==createHmac('sha256',fixtureState.key).update(`cuevo.worker.wake.v1\n${headers.get('X-Cuevo-Wake-Time')}\n${body.wakeId}`).digest('hex'))return Response.json({code:'WORKER_AUTH_REQUIRED'},{status:401});if(mode==='signed-failed'||mode==='foreign-dispatch')return Response.json({code:'WORKER_UNAVAILABLE'},{status:503});if(fixtureState.processed)return Response.json({status:'NOT_ADMITTED'},{status:202});fixtureState.processed=true;return Response.json({status:'COMPLETED',processed:1});}
  throw Error('Unexpected activation HTTP fixture');
 };
 await run(input,root);
 }finally{globalThis.fetch=fetchPrevious;await rm(root,{recursive:true,force:true});}}
test('activation performs current gates before key then verifies signed source and exact original scheduled recovery',async()=>{const api=await subject();await fixture('normal',async(input,root)=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'ACTIVATED_SIGNED_SOURCE_VERIFIED');assert.equal(result.hostedAcceptance,false);assert.equal(result.recoveryVerified,false);assert.equal(result.recoveryScheduled,true);assert.equal(result.scheduledRecoveryVerified,true);assert.equal(result.recovery?.expiredLeaseRecoveryVerified,false);assert.equal(result.sourceProcessed,true);assert.equal(result.duplicateWakeDenied,true);assert.equal(calls.filter(c=>c.startsWith('POST:/v1/projects/')&&c.endsWith('/secrets')).length,1);assert(calls.indexOf('private')<calls.findIndex(c=>c.startsWith('POST:')&&c.endsWith('/secrets')));assert.equal(JSON.stringify(result).includes(fixtureState.key),false);const retained=await readFile(join(root,'.local/hosted-release/worker-activation-intent.json'),'utf8');assert.equal(retained.includes(fixtureState.key),false);});});
test('activation retains its private original key before provider writes and confirms only after terminal cleanup',async()=>{const api=await subject();await fixture('normal',async input=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'ACTIVATED_SIGNED_SOURCE_VERIFIED');const state=durableState as {phase:string;wakeKey:string;cleanup:{lockReleased:boolean;sessionsClosed:boolean}};assert.equal(state.phase,'CONFIRMED');assert.equal(state.wakeKey,fixtureState.key);assert.equal(state.cleanup.lockReleased,true);assert.equal(state.cleanup.sessionsClosed,true);assert(calls.findIndex(row=>row.includes('CUEVO_ACTIVE_RUNTIME_SAVE'))<calls.findIndex(row=>row.startsWith('POST:')&&row.endsWith('/secrets')));});});
test('caller receipts cannot overcome unavailable current private transport TLS idle-connection or approval evidence',async()=>{const api=await subject();for(const mode of ['admission','prerequisites','private','private-stale','transport','transport-after-probes','tls','idle-loss'])await fixture(mode,async input=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(fixtureState.key,'');assert.equal(fixtureState.enabled,false);assert.equal(JSON.stringify(result).includes(secret),false);});});
test('stale changed Data API and unknown key operation never issue dispatch or duplicate signing key',async()=>{const api=await subject();await fixture('normal',async input=>{input.dataApiConfigurationEvidence={source:'AUTHENTICATED_DASHBOARD',observedAt:'2026-01-01T00:00:00Z'};const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(fixtureState.key,'');});await fixture('key-unknown',async(input,root)=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.keyOperation,'UNKNOWN');assert.equal(fixtureState.enabled,false);const again=await api.activateHostedWorker(input);assert.equal(again.status,'REQUIRES_REVIEW');assert.equal(calls.filter(c=>c.startsWith('POST:')&&c.endsWith('/secrets')).length,1);assert(await readFile(join(root,'.local/hosted-release/worker-activation-intent.json'),'utf8'));});});
test('failed signed processing and uncertain Cron commit disable only the confirmed owned dispatch',async()=>{const api=await subject();for(const selected of ['signed-failed','cron-commit-unknown'])await fixture(selected,async input=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.keyOperation,'CONFIRMED');assert.equal(result.dispatchDisabledOnFailure,true);assert.equal(fixtureState.enabled,false);assert.equal(fixtureState.cron,0);assert.equal(result.recoveryVerified,false);if(selected==='cron-commit-unknown')assert.equal(result.jobId,42);});});
test('cleanup refuses a foreign dispatch change and exact input guards reject redirected credentials before effects',async()=>{const api=await subject();await fixture('foreign-dispatch',async input=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.dispatchDisabledOnFailure,false);assert.equal(fixtureState.enabled,true);});for(const database of [`postgresql://postgres.${ref}:exposed@${host}:5432/postgres?sslmode=verify-full`,`postgresql://postgres.${ref}@${host}:5432/postgres?sslmode=disable`,`postgresql://postgres.${ref}@${host}:5432/other?sslmode=verify-full`])await fixture('normal',async input=>{input.operatorDatabaseUrl=database;const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(fixtureState.key,'');assert.equal(calls.includes('connect'),false);});});
test('unconfirmed scheduled recovery keeps its separate false gate and pauses the exact activation',async()=>{const api=await subject();await fixture('recovery-backlog',async input=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.scheduledRecoveryVerified,false);assert.equal(result.recoveryVerified,false);assert.equal(result.recovery?.status,'REQUIRES_REVIEW');assert.equal(result.dispatchDisabledOnFailure,true);assert.equal(fixtureState.enabled,false);assert.equal(fixtureState.cron,0);});});
test('late confirmation review preserves healthy original dispatch and publishes truthful current terminal files',async()=>{const api=await subject();await fixture('confirmation-review',async(input,root)=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.canonicalReceipt,null);assert.equal(fixtureState.enabled,true);assert.equal(fixtureState.cron,42);assert.equal(result.dispatchDisabledOnFailure,null);const final=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-result.json'),'utf8'));const cleanup=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-cleanup.json'),'utf8'));const execution=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-execution-result.json'),'utf8'));assert.equal(final.status,'REQUIRES_REVIEW');assert.equal(cleanup.status,final.status);assert.equal(cleanup.resultSha256,hash((await import('./release-review')).canonicalReleaseExecutionJson(final)));assert.equal(execution.status,'ACTIVATED_SIGNED_SOURCE_VERIFIED');assert.equal((durableState as {phase:string}).phase,'CONFIGURED');assert(calls.indexOf('confirmation')>calls.indexOf('close'));});});
test('successful current activation receipt is published after confirmation cleanup with matched final hash',async()=>{const api=await subject();await fixture('normal',async(input,root)=>{const result=await api.activateHostedWorker(input);const final=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-result.json'),'utf8'));const cleanup=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-cleanup.json'),'utf8'));assert.equal(result.status,'ACTIVATED_SIGNED_SOURCE_VERIFIED');assert.equal(result.phase,'FINAL');assert(calls.includes('confirmation'));assert.equal(cleanup.resultSha256,hash((await import('./release-review')).canonicalReleaseExecutionJson(final)));assert.equal(cleanup.lockReleased,true);assert.equal(cleanup.sessionsClosed,true);});});
test('late current receipt conflict and original native close failure preserve healthy configured dispatch',async()=>{const api=await subject();for(const selected of['final-write','initial-close'])await fixture(selected,async(input,root)=>{if(selected==='final-write')await writeFile(join(root,'.local/hosted-release/worker-activation-result.json'),'Existing original result');const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.canonicalReceipt,null);assert.equal(fixtureState.enabled,true);assert.equal(fixtureState.cron,42);assert.equal((durableState as {phase:string}).phase,selected==='final-write'?'CONFIRMED':'CONFIGURED');if(selected==='final-write')assert.equal(await readFile(join(root,'.local/hosted-release/worker-activation-result.json'),'utf8'),'Existing original result');});});
test('late original unlock or Auth closure refusal retains review evidence and closes its native owner without pausing verified work',async()=>{const api=await subject();for(const selected of['initial-unlock','logout'])await fixture(selected,async(input,root)=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.canonicalReceipt,null);assert.equal(fixtureState.enabled,true);assert.equal(fixtureState.cron,42);assert.equal(calls.filter(row=>row==='close').length,1);assert.equal(calls.includes('confirmation'),false);const cleanup=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-execution-cleanup.json'),'utf8'));assert.equal(cleanup.status,'REQUIRES_REVIEW');assert.equal(cleanup.lockReleased,selected!=='initial-unlock');assert.equal(cleanup.sessionsClosed,selected!=='logout');});});
test('current terminal cleanup includes confirmation lease and socket failures separately from original execution cleanup',async()=>{const api=await subject();for(const selected of['confirmation-unlock','confirmation-close'])await fixture(selected,async(input,root)=>{const result=await api.activateHostedWorker(input);const cleanup=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-cleanup.json'),'utf8'));const originalCleanup=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-execution-cleanup.json'),'utf8'));assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.canonicalReceipt,null);assert.equal(cleanup.lockReleased,selected!=='confirmation-unlock');assert.equal(cleanup.sessionsClosed,selected!=='confirmation-close');assert.equal(originalCleanup.lockReleased,true);assert.equal(originalCleanup.sessionsClosed,true);assert.equal(fixtureState.enabled,true);});});
test('after-write final fsync or close uncertainty returns review even when local success bytes exist',async()=>{const api=await subject();for(const selected of['terminal-sync','terminal-close'])await fixture(selected,async(input,root)=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.canonicalReceipt,null);assert.equal(fixtureState.enabled,true);const partial=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-result.json'),'utf8'));assert.equal(partial.status,'ACTIVATED_SIGNED_SOURCE_VERIFIED');assert.equal((durableState as {phase:string}).phase,'CONFIRMED');});});
test('original identity export is retained exactly before effects without deriving its creation clock',async()=>{const api=await subject();await fixture('normal',async(input,root)=>{await api.activateHostedWorker(input);const identity=JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-identity.json'),'utf8'));assert.deepEqual(identity,(durableState as {identity:unknown}).identity);assert.equal(JSON.stringify(identity).includes(fixtureState.key),false);});});


test('new activation records provider evidence with false manual flag and refuses unconfirmed provider configuration before key effects',async()=>{const api=await subject();for(const mode of ['verified','data-api-enabled','data-api-unknown'])await fixture(mode,async input=>{const result=await api.activateHostedWorker(input);if(mode==='verified'){assert.equal(result.status,'ACTIVATED_SIGNED_SOURCE_VERIFIED');assert.equal(result.configurationEvidenceObservedManual,false);assert.equal(result.configurationObservation?.evidence.source,'SUPABASE_MANAGEMENT_POSTGREST_CONFIG');assert.equal(result.version,2);}else{assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(fixtureState.key,'');assert.equal(fixtureState.enabled,false);}});});

test('activation owns one admission through both cleanup sessions and terminal publication',async()=>{const api=await subject();await fixture('normal',async(input,root)=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'ACTIVATED_SIGNED_SOURCE_VERIFIED');assert.equal(preparationCount,1);assert.equal(disposalCount,1);assert(calls.indexOf('prepare')<calls.indexOf('connect'));assert(calls.indexOf('close')<calls.indexOf('confirmation'));assert(calls.indexOf('confirmation')<calls.indexOf('dispose'));assert.equal(preparedHandle,undefined);assert.equal(JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-result.json'),'utf8')).status,result.status);});});
test('activation current admission failure blocks key and Cron effects and disposes after native cleanup',async()=>{const api=await subject();for(const selected of ['admission','late-admission'])await fixture(selected,async input=>{const result=await api.activateHostedWorker(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(preparationCount,1);assert.equal(disposalCount,1);assert.equal(fixtureState.key,'');assert.equal(fixtureState.cron,0);assert.equal(fixtureState.enabled,false);if(selected==='late-admission')assert(calls.indexOf('close')<calls.indexOf('dispose'));});});
test('activation borrows the exact current owner through confirmation and publication without recapture or disposal',async()=>{const api=await subject();await fixture('normal',async(input,root)=>{const handle=Object.freeze({}) as NativeBackendAdmissionHandle;preparedHandle=handle;preparedBinding={repoRoot:input.repoRoot,expected:input.expected,prepared:input.preparedApproval,effectScope:'COMPLETE_BACKEND'};admissionRecords.set(handle,{binding:preparedBinding,disposed:false});const result=await api.activateHostedWorker(input,handle);assert.equal(result.status,'ACTIVATED_SIGNED_SOURCE_VERIFIED');assert.equal(preparationCount,0);assert.equal(disposalCount,0);assert.equal(preparedHandle,handle);assert.equal(admissionRecords.get(handle)?.disposed,false);assert(calls.indexOf('close')<calls.indexOf('confirmation'));assert.equal(JSON.parse(await readFile(join(root,'.local/hosted-release/worker-activation-result.json'),'utf8')).status,result.status);});});
test('activation refuses null or foreign borrowed owners before native or provider effects without recapture',async()=>{const api=await subject();for(const borrowed of [null,Object.freeze({})])await fixture('normal',async input=>{const result=await api.activateHostedWorker(input,borrowed as NativeBackendAdmissionHandle);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(preparationCount,0);assert.equal(disposalCount,0);assert.equal(fixtureState.key,'');assert.equal(fixtureState.cron,0);assert.equal(calls.includes('connect'),false);assert.equal(calls.some(row=>row.startsWith('GET:')||row.startsWith('POST:')),false);});});
test('activation borrowed current admission loss closes its native session without disposing its parent owner',async()=>{const api=await subject();await fixture('late-admission',async input=>{const handle=Object.freeze({}) as NativeBackendAdmissionHandle;preparedHandle=handle;preparedBinding={repoRoot:input.repoRoot,expected:input.expected,prepared:input.preparedApproval,effectScope:'COMPLETE_BACKEND'};admissionRecords.set(handle,{binding:preparedBinding,disposed:false});const result=await api.activateHostedWorker(input,handle);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(preparationCount,0);assert.equal(disposalCount,0);assert.equal(preparedHandle,handle);assert(calls.includes('close'));assert.equal(fixtureState.key,'');assert.equal(fixtureState.cron,0);});});
