import { createHash } from 'node:crypto';
import { lstat,readFile,realpath,open } from 'node:fs/promises';
import { isAbsolute,join,resolve } from 'node:path';
import { z } from 'zod';
import { canonicalReleaseExecutionJson } from './release-review';
import { prepareNativeBackendReleaseAdmission,readNativeBackendReleaseAdmission,disposeNativeBackendReleaseAdmission,type NativeBackendAdmissionHandle,readBackendActivationExecutionAdmission,readBackendRuntimeInitializationAdmission } from './backend-release-admission';
import { validatePreparedBackendReleaseIntent,type BackendReleaseExpected } from './backend-release-contracts';
import { prepareHostedRuntimeRecipients,prepareHostedOperatingRecipients } from './backend-provider-deploy';
import {revalidateActiveRuntime,revalidateCurrentRuntime} from './backend-runtime-resume';
import {confirmHostedWorkerActivation} from './backend-hosted-activation-confirmation';
import {assertNativeRuntimeRolloutLease,type NativeRuntimeRolloutLease} from '../database/hosted-runtime-rollout-session';
import {runtimeRolloutBindingSchema,readBackendRuntimeFingerprints} from './backend-release-contracts';

const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),fail=()=>Error('Staging API origin binding requires review; private contents withheld.');
const origin='https://cuevo-api.vercel.app',project='prj_QtcVui11hMayZcqBF3KAxZcLaocs',team='team_Gvw1Dz7IlxIG5evqwlsNkZHb';
const schema=z.object({lane:z.enum(['FULL_CUSTOMER_PREREQUISITES','OPERATING_SYNTHETIC_STAGING']).default('FULL_CUSTOMER_PREREQUISITES'),repoRoot:z.string(),expected:z.unknown(),preparedApproval:z.unknown(),runtimeConfig:z.unknown(),githubToken:z.string().min(1),vercelToken:z.string().min(20),syntheticPassword:z.string().min(16).max(128),activeOperator:z.object({providerToken:z.string().min(20),operatorDatabaseUrl:z.string(),operatorPassword:z.string().min(1)}).strict().optional()}).strict();
export type BackendApiOriginResult={purpose:'CUEVO_STAGING_API_ORIGIN';status:'API_ORIGIN_BOUND'|'REQUIRES_REVIEW';sourceSha:string|null;projectRef:string|null;runId:string|null;runAttempt:number|null;packageSha256:string|null;runtimeSha256:string|null;apiDeploymentId:string|null;origin:'https://cuevo-api.vercel.app';observedAt:string;aliasOperation:'NONE'|'UNKNOWN'|'CONFIRMED'|'NOOP';aliasId:string|null;healthVerified:boolean;currentActorVerified:boolean;corsVerified:boolean;sessionsClosed:boolean;hostedAcceptance:false;canonicalReceipt:string|null};
async function owned(root:string,name:string,max=131072){let path=root;for(const part of ['.local','hosted-release',name]){path=join(path,part);const s=await lstat(path);if(s.isSymbolicLink()||await realpath(path)!==path||(part===name?!s.isFile()||s.nlink!==1||s.size>max:!s.isDirectory()))throw fail();}const before=await lstat(path),bytes=await readFile(path),after=await lstat(path);if(bytes.length>max||before.ino!==after.ino||before.dev!==after.dev||before.size!==after.size||before.mtimeMs!==after.mtimeMs)throw fail();return bytes;}
async function persist(path:string,value:unknown){const handle=await open(path,'wx',0o600);try{await handle.writeFile(canonicalReleaseExecutionJson(value));await handle.sync();}finally{await handle.close();}}
async function http(url:string,method:'GET'|'POST'|'PATCH'|'OPTIONS',headers:Record<string,string>,body?:unknown){const signal=AbortSignal.timeout(10000),response=await fetch(url,{method,headers:{...headers,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'error',credentials:'omit',cache:'no-store',signal});if(response.redirected||response.url&&response.url!==url)throw fail();if(!response.body&&response.status===204)return{status:204,value:null as unknown,headers:response.headers};const size=response.headers.get('content-length');if(!response.body||size!==null&&(!/^\d+$/.test(size)||Number(size)>65536))throw fail();const reader=response.body.getReader(),chunks:Uint8Array[]=[];let total=0;try{for(;;){const r=await new Promise<ReadableStreamReadResult<Uint8Array>>((done,reject)=>{const abort=()=>{signal.removeEventListener('abort',abort);reject(fail());};if(signal.aborted)return abort();signal.addEventListener('abort',abort,{once:true});void reader.read().then(v=>{signal.removeEventListener('abort',abort);done(v);},()=>{signal.removeEventListener('abort',abort);reject(fail());});});if(r.done)break;total+=r.value.byteLength;if(total>65536||signal.aborted)throw fail();chunks.push(r.value);}return{status:response.status,value:JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(Buffer.concat(chunks)))as unknown,headers:response.headers};}finally{void reader.cancel().catch(()=>undefined);try{reader.releaseLock();}catch{/* Pending cancelled read owns cleanup. */}}}

export type RuntimeApiOriginResult={purpose:'CUEVO_RUNTIME_API_ORIGIN_TRANSITION';status:'ALIAS_BOUND'|'REQUIRES_REVIEW';operation:'NONE'|'UNKNOWN'|'CONFIRMED'|'NOOP';sourceSha:string|null;treeSha:string|null;generation:string|null;previousDeploymentId:string|null;desiredDeploymentId:string|null;aliasId:string|null;originalIntentSha256:string|null;observedAt:string;receiptSha256:string|null;hostedAcceptance:false};
export type BackendApiOriginObservation={purpose:'CUEVO_STAGING_API_ORIGIN_OBSERVATION';status:'API_ORIGIN_OBSERVED'|'REQUIRES_REVIEW';sourceSha:string|null;treeSha:string|null;runId:string|null;runAttempt:number|null;packageSha256:string|null;projectRef:string|null;apiDeploymentId:string|null;runtimeSha256:string|null;origin:string|null;healthVerified:boolean;currentActorVerified:boolean;corsVerified:boolean;sessionsClosed:boolean;observedAt:string;canonicalReceipt:string|null;hostedAcceptance:false};
/** Read-only provider mapping plus current fictional actor/CORS probes. Alias
 * assignment remains a distinct original effect and is never retried here. */
export async function observeBackendApiOrigin(value:unknown,borrowed?:NativeBackendAdmissionHandle):Promise<BackendApiOriginObservation>{
 const result:BackendApiOriginObservation={purpose:'CUEVO_STAGING_API_ORIGIN_OBSERVATION',status:'REQUIRES_REVIEW',sourceSha:null,treeSha:null,runId:null,runAttempt:null,packageSha256:null,projectRef:null,apiDeploymentId:null,runtimeSha256:null,origin:null,healthVerified:false,currentActorVerified:false,corsVerified:false,sessionsClosed:true,observedAt:new Date().toISOString(),canonicalReceipt:null,hostedAcceptance:false};let auth='',publishable='',sessionToken='',admissionHandle:NativeBackendAdmissionHandle|undefined;
 try{
  const input=schema.extend({apiDeployment:z.object({id:z.string().regex(/^dpl_[A-Za-z0-9]+$/),url:z.string().url(),artifactSha256:z.string().regex(/^[a-f0-9]{64}$/)}).strict()}).parse(JSON.parse(canonicalReleaseExecutionJson(value))),expected=input.expected as BackendReleaseExpected,prepared=validatePreparedBackendReleaseIntent(input.preparedApproval,{...expected,now:Date.now()}),runtime=prepareHostedOperatingRecipients(input.runtimeConfig,expected),fingerprints=readBackendRuntimeFingerprints(expected.fingerprints);
  const componentSha=expected.runtimeRollout?.desired.sourceSha??expected.currentRuntime?.current.sourceSha??expected.releaseSha,active=expected.currentRuntime?.current;
  if(active&&((active.executorSourceSha??active.sourceSha)!==expected.releaseSha||(active.executorTreeSha??active.treeSha)!==expected.treeSha||active.apiDeploymentId!==input.apiDeployment.id||active.apiUrl!==input.apiDeployment.url||active.apiArtifactSha256!==fingerprints.apiArtifactSha256))throw fail();
  if(expected.targets.api.projectId!==project||expected.targets.api.teamId!==team||expected.targets.api.origin!==origin||expected.targets.api.target!=='preview'||input.apiDeployment.artifactSha256!==fingerprints.apiArtifactSha256)throw fail();auth=expected.targets.supabase.authOrigin;publishable=runtime.api.SUPABASE_PUBLISHABLE_KEY;const deploymentUrl=new URL(input.apiDeployment.url);if(auth!==`https://${expected.targets.supabase.projectRef}.supabase.co`||deploymentUrl.protocol!=='https:'||deploymentUrl.username||deploymentUrl.password||deploymentUrl.pathname!=='/'||deploymentUrl.search||deploymentUrl.hash||deploymentUrl.port||!deploymentUrl.hostname.endsWith('.vercel.app'))throw fail();
  const binding={repoRoot:input.repoRoot,expected,prepared,effectScope:'COMPLETE_BACKEND' as const};admissionHandle=borrowed===undefined?await prepareNativeBackendReleaseAdmission({...binding,githubToken:input.githubToken}):borrowed;const admission=()=>readNativeBackendReleaseAdmission(admissionHandle,binding),credentials={Authorization:'Bearer '+input.vercelToken},scope='?teamId='+team;
  const mapping=async()=>{const deploymentRead=await http('https://api.vercel.com/v13/deployments/'+input.apiDeployment.id+scope,'GET',credentials);if(deploymentRead.status!==200)throw fail();z.object({id:z.literal(input.apiDeployment.id),projectId:z.literal(project),ownerId:z.literal(team),url:z.literal(deploymentUrl.hostname),readyState:z.literal('READY'),target:z.null().or(z.literal('preview')),meta:z.object({cuevoCommitSha:z.literal(componentSha),cuevoArtifactSha256:z.literal(input.apiDeployment.artifactSha256)})}).parse(deploymentRead.value);const aliasRead=await http('https://api.vercel.com/v4/aliases/cuevo-api.vercel.app'+scope,'GET',credentials);if(aliasRead.status!==200)throw fail();return z.object({uid:z.string().min(1),alias:z.literal('cuevo-api.vercel.app'),projectId:z.literal(project),deploymentId:z.literal(input.apiDeployment.id),redirect:z.null()}).parse(aliasRead.value);};
  await admission();const original=await mapping();Object.assign(result,{sourceSha:expected.releaseSha,treeSha:expected.treeSha,runId:expected.releaseRunId,runAttempt:expected.runAttempt,packageSha256:prepared.sha256,projectRef:expected.targets.supabase.projectRef,apiDeploymentId:input.apiDeployment.id,runtimeSha256:runtime.runtimeSha256,origin});
  const health=await http(origin+'/health/ready','GET',{});if(health.status!==200||!z.object({status:z.literal('ready'),database:z.literal(true),authentication:z.literal(true)}).safeParse(health.value).success)throw fail();result.healthVerified=true;
  const bytes=await readFile(join(input.repoRoot,'supabase/seed/identities.json'));if(hash(bytes)!=='7464b3487adc3998d8f4ad4582ffd08ebafbdc8fd9a568433ddc687f4f03ac21')throw fail();const manifest=z.object({synthetic:z.literal(true),schoolId:z.uuid(),actors:z.array(z.object({actorId:z.uuid(),schoolId:z.uuid(),role:z.string(),email:z.string().email()})).length(133)}).parse(JSON.parse(bytes.toString('utf8'))),actor=manifest.actors.find(row=>row.schoolId===manifest.schoolId&&row.role==='admin');if(!actor)throw fail();
  const login=await http(auth+'/auth/v1/token?grant_type=password','POST',{apikey:publishable},{email:actor.email,password:input.syntheticPassword});if(login.status!==200)throw fail();sessionToken=z.object({access_token:z.string().min(20)}).parse(login.value).access_token;result.sessionsClosed=false;z.object({user:z.object({id:z.literal(actor.actorId),email:z.literal(actor.email)})}).parse(login.value);
  const preflight=await http(origin+'/v1/me','OPTIONS',{Origin:expected.targets.web.origin,'Access-Control-Request-Method':'GET','Access-Control-Request-Headers':'authorization,x-school-id'});if(![200,204].includes(preflight.status)||preflight.headers.get('access-control-allow-origin')!==expected.targets.web.origin||!preflight.headers.get('access-control-allow-methods')?.split(',').map(value=>value.trim().toUpperCase()).includes('GET')||!['authorization','x-school-id'].every(name=>preflight.headers.get('access-control-allow-headers')?.split(',').map(value=>value.trim().toLowerCase()).includes(name)))throw fail();
  const me=await http(origin+'/v1/me','GET',{Authorization:'Bearer '+sessionToken,'X-School-Id':manifest.schoolId,Origin:expected.targets.web.origin});if(me.status!==200||me.headers.get('access-control-allow-origin')!==expected.targets.web.origin)throw fail();z.object({userId:z.literal(actor.actorId),schoolId:z.literal(manifest.schoolId),role:z.literal('admin')}).parse(me.value);result.currentActorVerified=true;result.corsVerified=true;
  await admission();const final=await mapping();if(final.uid!==original.uid)throw fail();validatePreparedBackendReleaseIntent(prepared,{...expected,now:Date.now()});result.status='API_ORIGIN_OBSERVED';result.observedAt=new Date().toISOString();
 }catch{result.status='REQUIRES_REVIEW';}finally{if(sessionToken)try{result.sessionsClosed=[200,204].includes((await http(auth+'/auth/v1/logout?scope=local','POST',{apikey:publishable,Authorization:'Bearer '+sessionToken},{})).status);if(!result.sessionsClosed)result.status='REQUIRES_REVIEW';}catch{result.sessionsClosed=false;result.status='REQUIRES_REVIEW';}if(admissionHandle&&borrowed===undefined)disposeNativeBackendReleaseAdmission(admissionHandle);}if(result.status==='API_ORIGIN_OBSERVED'&&result.sessionsClosed)result.canonicalReceipt=canonicalReleaseExecutionJson({...result,canonicalReceipt:null});return result;
}

/** The held native rollout lease, current paused state and approved previous
 * tuple authorize one reserved staging alias transition. Lost acknowledgement
 * retains the original intent; this owner never guesses or repeats the write. */
export async function transitionRuntimeApiOrigin(input:{repoRoot:string;expected:BackendReleaseExpected;preparedApproval:unknown;githubToken:string;vercelToken:string;lease:NativeRuntimeRolloutLease;desired:{apiDeploymentId:string;apiUrl:string;apiArtifactSha256:string}},borrowed?:NativeBackendAdmissionHandle):Promise<RuntimeApiOriginResult>{
 const result:RuntimeApiOriginResult={purpose:'CUEVO_RUNTIME_API_ORIGIN_TRANSITION',status:'REQUIRES_REVIEW',operation:'NONE',sourceSha:null,treeSha:null,generation:null,previousDeploymentId:null,desiredDeploymentId:null,aliasId:null,originalIntentSha256:null,observedAt:new Date().toISOString(),receiptSha256:null,hostedAcceptance:false};let admissionHandle:NativeBackendAdmissionHandle|undefined;
 try{
  const expected=input.expected,prepared=validatePreparedBackendReleaseIntent(input.preparedApproval,{...expected,now:Date.now()}),rollout=runtimeRolloutBindingSchema.parse(expected.runtimeRollout),fingerprints=readBackendRuntimeFingerprints(expected.fingerprints),desired=z.object({apiDeploymentId:z.string().regex(/^dpl_[A-Za-z0-9]+$/),apiUrl:z.string().url(),apiArtifactSha256:z.string().regex(/^[a-f0-9]{64}$/)}).strict().parse(input.desired),root=input.repoRoot;
  if(expected.executionScope!=='runtime-rollout'||expected.targets.api.projectId!==project||expected.targets.api.teamId!==team||expected.targets.api.origin!==origin||expected.targets.api.target!=='preview'||desired.apiArtifactSha256!==fingerprints.apiArtifactSha256||!isAbsolute(root)||resolve(root)!==root||await realpath(root)!==root||(await lstat(root)).isSymbolicLink()||input.vercelToken.length<20)throw fail();
  const desiredUrl=new URL(desired.apiUrl),previousUrl=new URL(rollout.previous.apiUrl);for(const url of[desiredUrl,previousUrl])if(url.protocol!=='https:'||url.username||url.password||url.pathname!=='/'||url.search||url.hash||url.port||!url.hostname.endsWith('.vercel.app'))throw fail();
  const binding={repoRoot:root,expected,prepared,effectScope:'RUNTIME_ROLLOUT' as const};admissionHandle=borrowed===undefined?await prepareNativeBackendReleaseAdmission({...binding,githubToken:input.githubToken}):borrowed;const admission=()=>readNativeBackendReleaseAdmission(admissionHandle,binding);
  const session=assertNativeRuntimeRolloutLease(input.lease,expected),assertCurrent=async()=>{
   assertNativeRuntimeRolloutLease(input.lease,expected);await session.refresh();await session.requireDrained();const state=await session.readState(),current=state.current.identity,pending=state.pending;if(!pending||state.projectRef!==expected.targets.supabase.projectRef||!['PRIVATE_VERIFIED','ALIAS_CONFIRMED'].includes(pending.phase)||pending.operationSha256!==rollout.operationSha256)throw fail();
   for(const key of['generation','sourceSha','treeSha','runtimeSha256','apiDeploymentId','apiUrl','edgeId','edgeVersion','apiArtifactSha256','edgeArtifactSha256','denoLockSha256'] as const)if(current[key]!==rollout.previous[key])throw fail();
   for(const key of['generation','sourceSha','treeSha','apiArtifactSha256','edgeArtifactSha256','denoLockSha256','compatibilitySha256'] as const)if(pending.identity[key]!==rollout.desired[key])throw fail();
   if(pending.identity.runId!==(rollout.version===2&&rollout.action==='RECOVER_ORIGINAL'?rollout.recoveryOriginal!.runId:expected.releaseRunId)||pending.identity.runAttempt!==(rollout.version===2&&rollout.action==='RECOVER_ORIGINAL'?rollout.recoveryOriginal!.runAttempt:expected.runAttempt)||pending.identity.packageSha256!==(rollout.version===2&&rollout.action==='RECOVER_ORIGINAL'?rollout.recoveryOriginal!.packageSha256:prepared.sha256)||pending.identity.apiDeploymentId!==desired.apiDeploymentId||pending.identity.apiUrl!==desired.apiUrl||pending.identity.apiArtifactSha256!==desired.apiArtifactSha256)throw fail();validatePreparedBackendReleaseIntent(prepared,{...expected,now:Date.now()});
  };
  await assertCurrent();Object.assign(result,{sourceSha:expected.releaseSha,treeSha:expected.treeSha,generation:rollout.desired.generation,previousDeploymentId:rollout.previous.apiDeploymentId,desiredDeploymentId:desired.apiDeploymentId});
  const directory=join(root,'.local/hosted-release'),intentPath=join(directory,'runtime-api-origin-intent.json');for(const path of[join(root,'.local'),directory])if(!(await lstat(path)).isDirectory()||(await lstat(path)).isSymbolicLink()||await realpath(path)!==path)throw fail();
  let originalIntent:Record<string,unknown>|null=null;try{const stat=await lstat(intentPath);if(!(rollout.version===2&&rollout.action==='RECOVER_ORIGINAL')||stat.isSymbolicLink()||!stat.isFile()||stat.nlink!==1||stat.size>16384)throw fail();originalIntent=JSON.parse(await readFile(intentPath,'utf8'));if(originalIntent!.operationSha256!==rollout.operationSha256||originalIntent!.runId!==rollout.recoveryOriginal!.runId||originalIntent!.runAttempt!==rollout.recoveryOriginal!.runAttempt||originalIntent!.packageSha256!==rollout.recoveryOriginal!.packageSha256)throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}
  const credentials={Authorization:'Bearer '+input.vercelToken},scope='?teamId='+team;
  const exact=async(id:string,url:string,sourceSha:string,artifactSha256:string)=>{const response=await http('https://api.vercel.com/v13/deployments/'+id+scope,'GET',credentials);if(response.status!==200)throw fail();z.object({id:z.literal(id),projectId:z.literal(project),ownerId:z.literal(team),url:z.literal(new URL(url).hostname),readyState:z.literal('READY'),target:z.null().or(z.literal('preview')),meta:z.object({cuevoCommitSha:z.literal(sourceSha),cuevoArtifactSha256:z.literal(artifactSha256)})}).parse(response.value);};
  const alias=async()=>{const response=await http('https://api.vercel.com/v4/aliases/cuevo-api.vercel.app'+scope,'GET',credentials);if(response.status!==200)throw fail();return z.object({uid:z.string().min(1),alias:z.literal('cuevo-api.vercel.app'),projectId:z.literal(project),deploymentId:z.enum([rollout.previous.apiDeploymentId,desired.apiDeploymentId]),redirect:z.null()}).parse(response.value);};
  await exact(rollout.previous.apiDeploymentId,rollout.previous.apiUrl,rollout.previous.sourceSha,rollout.previous.apiArtifactSha256);await exact(desired.apiDeploymentId,desired.apiUrl,rollout.desired.sourceSha,desired.apiArtifactSha256);const prior=await alias();
  const intent={version:1,purpose:result.purpose,sourceSha:expected.releaseSha,treeSha:expected.treeSha,runId:expected.releaseRunId,runAttempt:expected.runAttempt,packageSha256:prepared.sha256,operationSha256:rollout.operationSha256,generation:rollout.desired.generation,previous:rollout.previous,desired,projectId:project,teamId:team,origin,aliasId:prior.uid,operation:prior.deploymentId===desired.apiDeploymentId?'NOOP':'INTENT',observedAt:new Date().toISOString()};if(originalIntent){if(prior.deploymentId!==desired.apiDeploymentId||prior.uid!==originalIntent.aliasId)throw fail();}else await persist(intentPath,intent);result.originalIntentSha256=hash(canonicalReleaseExecutionJson(originalIntent??intent));result.aliasId=prior.uid;
  if(prior.deploymentId===desired.apiDeploymentId)result.operation='NOOP';else{
   await admission();await assertCurrent();await exact(rollout.previous.apiDeploymentId,rollout.previous.apiUrl,rollout.previous.sourceSha,rollout.previous.apiArtifactSha256);await exact(desired.apiDeploymentId,desired.apiUrl,rollout.desired.sourceSha,desired.apiArtifactSha256);const currentAlias=await alias();if(currentAlias.uid!==prior.uid||currentAlias.deploymentId!==rollout.previous.apiDeploymentId)throw fail();validatePreparedBackendReleaseIntent(prepared,{...expected,now:Date.now()});assertNativeRuntimeRolloutLease(input.lease,expected);
   result.operation='UNKNOWN';const response=await http('https://api.vercel.com/v2/deployments/'+desired.apiDeploymentId+'/aliases'+scope,'POST',credentials,{alias:'cuevo-api.vercel.app',redirect:null});if(response.status!==200)throw fail();z.object({uid:z.literal(prior.uid),alias:z.literal('cuevo-api.vercel.app'),oldDeploymentId:z.literal(rollout.previous.apiDeploymentId)}).parse(response.value);const readback=await alias();if(readback.uid!==prior.uid||readback.deploymentId!==desired.apiDeploymentId)throw fail();result.operation='CONFIRMED';
  }
  await assertCurrent();await exact(desired.apiDeploymentId,desired.apiUrl,rollout.desired.sourceSha,desired.apiArtifactSha256);const finalAlias=await alias();if(finalAlias.uid!==prior.uid||finalAlias.deploymentId!==desired.apiDeploymentId)throw fail();validatePreparedBackendReleaseIntent(prepared,{...expected,now:Date.now()});result.status='ALIAS_BOUND';result.observedAt=new Date().toISOString();result.receiptSha256=hash(canonicalReleaseExecutionJson({...result,receiptSha256:null}));if(!originalIntent)await persist(join(directory,'runtime-api-origin-result.json'),result);
 }catch{result.status='REQUIRES_REVIEW';result.receiptSha256=null;}finally{if(admissionHandle&&borrowed===undefined)disposeNativeBackendReleaseAdmission(admissionHandle);}return result;
}

/** Assigns only the preapproved staging API alias from a source-bound package.
 * Any foreign/older mapping or uncertain intent refuses replacement. This never
 * promotes the web project or changes a production/customer domain. */
export async function bindBackendApiOrigin(value:unknown,borrowed?:NativeBackendAdmissionHandle):Promise<BackendApiOriginResult>{
 const r:BackendApiOriginResult={purpose:'CUEVO_STAGING_API_ORIGIN',status:'REQUIRES_REVIEW',sourceSha:null,projectRef:null,runId:null,runAttempt:null,packageSha256:null,runtimeSha256:null,apiDeploymentId:null,origin,observedAt:new Date().toISOString(),aliasOperation:'NONE',aliasId:null,healthVerified:false,currentActorVerified:false,corsVerified:false,sessionsClosed:true,hostedAcceptance:false,canonicalReceipt:null};
 let folder='',token='',auth='',publishable='',admissionHandle:NativeBackendAdmissionHandle|undefined;
 try{
  const input=schema.parse(JSON.parse(canonicalReleaseExecutionJson(value))),expected=input.expected as BackendReleaseExpected,prepared=validatePreparedBackendReleaseIntent(input.preparedApproval,{...expected,now:Date.now()}),runtime=input.lane==='OPERATING_SYNTHETIC_STAGING'?prepareHostedOperatingRecipients(input.runtimeConfig,expected):prepareHostedRuntimeRecipients(input.runtimeConfig,expected),root=input.repoRoot;
  if(!isAbsolute(root)||resolve(root)!==root||await realpath(root)!==root||expected.targets.api.projectId!==project||expected.targets.api.teamId!==team||expected.targets.api.origin!==origin||expected.targets.api.target!=='preview'||expected.targets.web.origin===origin)throw fail();
  const binding={repoRoot:root,expected,prepared,effectScope:'COMPLETE_BACKEND' as const};admissionHandle=borrowed===undefined?await prepareNativeBackendReleaseAdmission({...binding,githubToken:input.githubToken}):borrowed;const admission=()=>readNativeBackendReleaseAdmission(admissionHandle,binding);
  Object.assign(r,{sourceSha:expected.releaseSha,projectRef:expected.targets.supabase.projectRef,runId:expected.releaseRunId,runAttempt:expected.runAttempt,packageSha256:prepared.sha256,runtimeSha256:runtime.runtimeSha256});auth=expected.targets.supabase.authOrigin;publishable=runtime.api.SUPABASE_PUBLISHABLE_KEY;if(auth!==`https://${r.projectRef}.supabase.co`)throw fail();folder=join(root,'.local/hosted-release');
  const intentPath=join(folder,'api-origin-intent.json');try{await lstat(intentPath);throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}
  const read=async(name:string)=>JSON.parse((await owned(root,name)).toString('utf8'))as unknown;
  const provider=z.object({status:z.literal(expected.installedRuntime?'DEPLOYED_ACTIVE_REVALIDATED':'DEPLOYED_INACTIVE'),api:z.object({deploymentId:z.string().regex(/^dpl_[A-Za-z0-9]+$/),url:z.string().url(),artifactSha256:z.literal(expected.fingerprints.apiArtifactSha256)}),edge:z.object({id:z.string(),version:z.number().int().positive()})}).parse(await read('provider-result.json'));r.apiDeploymentId=provider.api.deploymentId;
  const identity=z.object({sourceSha:z.literal(expected.releaseSha),projectRef:z.literal(r.projectRef),runId:z.literal(expected.releaseRunId),runAttempt:z.literal(expected.runAttempt),packageSha256:z.literal(prepared.sha256),runtimeSha256:z.literal(runtime.runtimeSha256),apiDeploymentId:z.literal(r.apiDeploymentId)}),at=z.iso.datetime({offset:true});
  const current=(v:string)=>{if(Date.parse(v)>Date.now()||Date.now()-Date.parse(v)>3600000)throw fail();};
  z.object({status:z.literal('PREREQUISITES_OBSERVED'),apiReady:z.literal(true),roleSessions:z.literal(5),crossSchoolDenied:z.literal(true)}).parse(await read('prerequisites-result.json'));
  z.object({status:z.literal('PRIVATE_PROBES_CONFIRMED'),privateStorage:z.literal(true),privateRealtime:z.literal(true),restrictedDatabaseGrants:z.literal(true),sessionsClosed:z.literal(true)}).parse(await read('private-access-result.json'));
  if(input.lane==='OPERATING_SYNTHETIC_STAGING'){
   if(!input.activeOperator)throw fail();if(expected.executionScope==='complete-backend')await readBackendRuntimeInitializationAdmission({repoRoot:root,expected,prepared,githubToken:input.githubToken},admissionHandle);
   const native=await revalidateCurrentRuntime({repoRoot:root,expected,preparedApproval:prepared,runtimeConfig:input.runtimeConfig,githubToken:input.githubToken,vercelToken:input.vercelToken,providerToken:input.activeOperator.providerToken,operator:{databaseUrl:input.activeOperator.operatorDatabaseUrl,password:input.activeOperator.operatorPassword,certificate:{path:join(folder,'database-ca.pem'),sha256:hash(await owned(root,'database-ca.pem',512*1024))}}},admissionHandle);
   if(native.status!=='CURRENT_RUNTIME_REVALIDATED'||!native.current||!native.nativeExecutionVerified||!native.privateTransportVerified||native.admissionPaused!==false||!native.lockReleased||!native.sessionClosed||native.current.current.apiDeploymentId!==provider.api.deploymentId||native.current.current.edgeId!==provider.edge.id||native.current.current.edgeVersion!==provider.edge.version||native.current.current.runtimeSha256!==runtime.runtimeSha256)throw fail();
  }else{
  const resumed=expected.installedRuntime?await revalidateActiveRuntime({repoRoot:root,expected,preparedApproval:prepared,runtimeConfig:input.runtimeConfig,githubToken:input.githubToken,vercelToken:input.vercelToken,...input.activeOperator},admissionHandle):null;
  if(resumed&&(resumed.status!=='INSTALLED_RUNTIME_REVALIDATED'||!resumed.nativeExecutionVerified||!resumed.lockReleased||!resumed.original))throw fail();
  if(!resumed){await readBackendActivationExecutionAdmission({repoRoot:root,expected,prepared,githubToken:input.githubToken},admissionHandle);if(!input.activeOperator)throw fail();const current=await confirmHostedWorkerActivation({repoRoot:root,expected,preparedApproval:prepared,runtimeConfig:input.runtimeConfig,githubToken:input.githubToken,vercelToken:input.vercelToken,...input.activeOperator,observationOnly:true},admissionHandle);if(current.status!=='ORIGINAL_ACTIVATION_CONFIRMED'||!current.canonicalReceipt||!current.lockReleased||!current.sessionClosed||current.basis!=='EXACT_CONFIRMED_READBACK')throw fail();}
  const activationIdentity=resumed?.original?identity.extend({runId:z.literal(resumed.original.originalRunId),runAttempt:z.literal(resumed.original.originalRunAttempt),packageSha256:z.literal(resumed.original.originalPackageSha256)}):identity;
  const activation=activationIdentity.extend({purpose:z.literal('CUEVO_HOSTED_WORKER_ACTIVATION'),status:z.literal('ACTIVATED_SIGNED_SOURCE_VERIFIED'),observedAt:at,edgeVersion:z.literal(provider.edge.version),sourceProcessed:z.literal(true),scheduledRecoveryVerified:z.literal(true),duplicateWakeDenied:z.literal(true),sessionsClosed:z.literal(true)}).passthrough().parse(resumed?.activation??await read('worker-activation-result.json'));if(!resumed)current(activation.observedAt);
  activationIdentity.pick({sourceSha:true,projectRef:true,runId:true,runAttempt:true}).extend({purpose:z.literal('CUEVO_HOSTED_WORKER_ACTIVATION_CLEANUP'),status:z.literal(activation.status),resultSha256:z.literal(hash(canonicalReleaseExecutionJson(activation))),sessionsClosed:z.literal(true),lockReleased:z.literal(true)}).parse(resumed?.cleanup??await read('worker-activation-cleanup.json'));
  const fault=identity.extend({purpose:z.literal('CUEVO_HOSTED_WORKER_FAULT_RECOVERY'),status:z.literal('FAULT_RECOVERY_VERIFIED'),observedAt:at,edgeVersion:z.literal(provider.edge.version),expiredLeaseRecoveryVerified:z.literal(true),eventRetryVerified:z.literal(true),dispatchBackoffVerified:z.literal(true),ownedControlVerified:z.literal(true),sessionsClosed:z.literal(true),lockReleased:z.literal(true),cleanupStatus:z.literal('RELEASED')}).passthrough().parse(await read('worker-fault-recovery-result.json'));current(fault.observedAt);
  identity.pick({sourceSha:true,projectRef:true,runId:true,runAttempt:true}).extend({purpose:z.literal('CUEVO_HOSTED_WORKER_FAULT_RECOVERY_CLEANUP'),status:z.literal(fault.status),resultSha256:z.literal(hash(canonicalReleaseExecutionJson(fault))),sessionsClosed:z.literal(true),lockReleased:z.literal(true),cleanupStatus:z.literal('RELEASED')}).parse(await read('worker-fault-recovery-cleanup.json'));
  const restored=identity.extend({purpose:z.literal('CUEVO_HOSTED_DATABASE_RESTORE'),status:z.literal('VERIFIED'),observedAt:at,backupVerified:z.literal(true),restoredDatabaseVerified:z.literal(true),restoredRestrictedGrantsVerified:z.literal(true),restoredRlsVerified:z.literal(true),restoredAuthVerified:z.literal(true),restoredPrivateStorageVerified:z.literal(true),recoveryVerified:z.literal(true),cleanupConfirmed:z.literal(true)}).passthrough().parse(await read('database-restore-result.json'));current(restored.observedAt);
  identity.pick({sourceSha:true,projectRef:true,runId:true,runAttempt:true}).extend({purpose:z.literal('CUEVO_HOSTED_DATABASE_RESTORE_CLEANUP'),status:z.literal(restored.status),resultSha256:z.literal(hash(canonicalReleaseExecutionJson(restored))),cleanupConfirmed:z.literal(true),sessionsClosed:z.literal(true),lockReleased:z.literal(true)}).parse(await read('database-restore-cleanup.json'));
  }
  await admission();
  const api=new URL(provider.api.url);if(api.protocol!=='https:'||!api.hostname.endsWith('.vercel.app')||api.username||api.password||api.pathname!=='/'||api.search||api.hash)throw fail();const credentials={Authorization:'Bearer '+input.vercelToken},scope='?teamId='+team;
  const projectRead=await http('https://api.vercel.com/v9/projects/'+project+scope,'GET',credentials);if(projectRead.status!==200)throw fail();const protectedProject=z.object({id:z.literal(project),accountId:z.literal(team),ssoProtection:z.object({deploymentType:z.string()}).nullable().optional()}).parse(projectRead.value);
  const domains=await http('https://api.vercel.com/v9/projects/'+project+'/domains'+scope,'GET',credentials);if(domains.status!==200)throw fail();const domainSet=z.object({domains:z.array(z.object({name:z.string(),projectId:z.literal(project),verified:z.boolean()})),pagination:z.object({next:z.null()}).optional()}).parse(domains.value);if(domainSet.domains.filter(d=>d.name===new URL(origin).hostname&&d.verified).length!==1)throw fail();
  const exact=async()=>{const response=await http('https://api.vercel.com/v13/deployments/'+r.apiDeploymentId+scope,'GET',credentials);if(response.status!==200)throw fail();z.object({id:z.literal(r.apiDeploymentId),projectId:z.literal(project),ownerId:z.literal(team),url:z.literal(api.hostname),readyState:z.literal('READY'),target:z.null().or(z.literal('preview')),meta:z.object({cuevoCommitSha:z.literal(expected.releaseSha)})}).parse(response.value);};await exact();
  const aliasUrl='https://api.vercel.com/v4/aliases/cuevo-api.vercel.app'+scope;
  const alias=async()=>{const response=await http(aliasUrl,'GET',credentials);if(response.status===404){if(!z.object({error:z.object({code:z.literal('alias_not_found')})}).safeParse(response.value).success)throw fail();return null;}if(response.status!==200)throw fail();return z.object({uid:z.string().min(1),alias:z.literal('cuevo-api.vercel.app'),projectId:z.literal(project),deploymentId:z.literal(r.apiDeploymentId),redirect:z.null(),protectionBypass:z.record(z.string(),z.unknown()).optional()}).parse(response.value);};
  const prior=await alias();await persist(intentPath,{purpose:r.purpose,sourceSha:r.sourceSha,projectRef:r.projectRef,runId:r.runId,runAttempt:r.runAttempt,packageSha256:r.packageSha256,runtimeSha256:r.runtimeSha256,apiDeploymentId:r.apiDeploymentId,origin,aliasOperation:prior?'NOOP':'INTENT',observedAt:new Date().toISOString()});
  if(prior){r.aliasOperation='NOOP';r.aliasId=prior.uid;}else{await admission();await exact();if(await alias())throw fail();validatePreparedBackendReleaseIntent(prepared,{...expected,now:Date.now()});r.aliasOperation='UNKNOWN';const assigned=await http('https://api.vercel.com/v2/deployments/'+r.apiDeploymentId+'/aliases'+scope,'POST',credentials,{alias:'cuevo-api.vercel.app',redirect:null});if(assigned.status!==200)throw fail();z.object({uid:z.string().min(1),alias:z.literal('cuevo-api.vercel.app'),oldDeploymentId:z.undefined().optional()}).parse(assigned.value);const fresh=await alias();if(!fresh)throw fail();r.aliasId=fresh.uid;r.aliasOperation='CONFIRMED';}
  const overridePresent=(value:Awaited<ReturnType<typeof alias>>)=>!!value&&Object.values(value.protectionBypass??{}).some(entry=>{const parsed=z.object({scope:z.literal('alias-protection-override'),createdAt:z.number().int().nonnegative(),createdBy:z.string().min(1)}).safeParse(entry);return parsed.success&&parsed.data.createdAt<=Date.now();});
  let normalAlias=await alias();if(!normalAlias)throw fail();
  if(protectedProject.ssoProtection&&!overridePresent(normalAlias)){
    const protectionIntent=join(folder,'api-origin-protection-intent.json');try{await lstat(protectionIntent);throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}
    await admission();await exact();normalAlias=await alias();if(!normalAlias)throw fail();
    await persist(protectionIntent,{purpose:'CUEVO_NORMAL_STAGING_ALIAS_PROTECTION',sourceSha:r.sourceSha,runId:r.runId,runAttempt:r.runAttempt,packageSha256:r.packageSha256,projectId:project,teamId:team,deploymentId:r.apiDeploymentId,aliasId:normalAlias.uid,origin,operation:'INTENT',observedAt:new Date().toISOString()});
    // Final original package consumption follows durable intent; expiry is not renewed.
    validatePreparedBackendReleaseIntent(prepared,{...expected,now:Date.now()});
    const overridden=await http('https://api.vercel.com/aliases/'+encodeURIComponent(normalAlias.uid)+'/protection-bypass'+scope,'PATCH',credentials,{override:{action:'create',scope:'alias-protection-override'}});if(overridden.status!==200)throw fail();
    await admission();await exact();if(!overridePresent(await alias()))throw fail();
  }
  const ready=await http(origin+'/health/ready','GET',{});if(ready.status!==200||!z.object({status:z.literal('ready'),database:z.literal(true),authentication:z.literal(true)}).safeParse(ready.value).success)throw fail();r.healthVerified=true;
  const manifestBytes=await readFile(join(root,'supabase/seed/identities.json'));if(hash(manifestBytes)!=='7464b3487adc3998d8f4ad4582ffd08ebafbdc8fd9a568433ddc687f4f03ac21')throw fail();const manifest=z.object({synthetic:z.literal(true),schoolId:z.uuid(),actors:z.array(z.object({actorId:z.uuid(),schoolId:z.uuid(),role:z.string(),email:z.string().email()})).length(133)}).parse(JSON.parse(manifestBytes.toString('utf8')));const admin=manifest.actors.find(a=>a.schoolId===manifest.schoolId&&a.role==='admin');if(!admin)throw fail();const login=await http(auth+'/auth/v1/token?grant_type=password','POST',{apikey:publishable},{email:admin.email,password:input.syntheticPassword});if(login.status!==200)throw fail();token=z.object({access_token:z.string().min(20)}).parse(login.value).access_token;r.sessionsClosed=false;z.object({user:z.object({id:z.literal(admin.actorId),email:z.literal(admin.email)})}).parse(login.value);
  const preflight=await http(origin+'/v1/me','OPTIONS',{Origin:expected.targets.web.origin,'Access-Control-Request-Method':'GET','Access-Control-Request-Headers':'authorization,x-school-id'});if(![200,204].includes(preflight.status)||preflight.headers.get('access-control-allow-origin')!==expected.targets.web.origin||!preflight.headers.get('access-control-allow-methods')?.split(',').map(v=>v.trim().toUpperCase()).includes('GET')||!['authorization','x-school-id'].every(header=>preflight.headers.get('access-control-allow-headers')?.split(',').map(v=>v.trim().toLowerCase()).includes(header)))throw fail();
  const me=await http(origin+'/v1/me','GET',{Authorization:'Bearer '+token,'X-School-Id':manifest.schoolId,Origin:expected.targets.web.origin});if(me.status!==200)throw fail();z.object({userId:z.literal(admin.actorId),schoolId:z.literal(manifest.schoolId),role:z.literal('admin')}).parse(me.value);r.currentActorVerified=true;r.corsVerified=me.headers.get('access-control-allow-origin')===expected.targets.web.origin;if(!r.corsVerified)throw fail();await admission();await exact();if(!await alias())throw fail();r.status='API_ORIGIN_BOUND';r.observedAt=new Date().toISOString();
 }catch{r.status='REQUIRES_REVIEW';}
 finally{if(token)try{r.sessionsClosed=[200,204].includes((await http(auth+'/auth/v1/logout?scope=local','POST',{apikey:publishable,Authorization:'Bearer '+token},{})).status);if(!r.sessionsClosed)r.status='REQUIRES_REVIEW';}catch{r.sessionsClosed=false;r.status='REQUIRES_REVIEW';}if(folder&&r.aliasOperation!=='NONE')try{r.canonicalReceipt=canonicalReleaseExecutionJson({...r,canonicalReceipt:null});await persist(join(folder,'api-origin-result.json'),{...r,canonicalReceipt:null});}catch{r.status='REQUIRES_REVIEW';r.canonicalReceipt=null;}if(admissionHandle&&borrowed===undefined)disposeNativeBackendReleaseAdmission(admissionHandle);}
 return r;
}
