import { createHash } from 'node:crypto';
import { lstat,readFile,realpath,open } from 'node:fs/promises';
import { isAbsolute,join,relative,resolve } from 'node:path';
import { z } from 'zod';
import { canonicalReleaseExecutionJson } from './release-review';
import { prepareBackendWebHandover,revalidateOperatingStagingHandoff } from './backend-web-handover';
import {validateOperatingStagingHandoff} from './operating-staging-handoff';
import {prepareNativeBackendReleaseAdmission,readNativeBackendReleaseAdmission,disposeNativeBackendReleaseAdmission,type NativeBackendAdmissionHandle} from './backend-release-admission';
import { validatePreparedBackendReleaseIntent,type BackendReleaseExpected } from './backend-release-contracts';

const project='prj_lvJJsVg0WeZAJhCovTlHCPOi0JaR',team='team_Gvw1Dz7IlxIG5evqwlsNkZHb';
const hash=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex'),fail=()=>Error('Public web settings require current backend handover; contents withheld.');
const schema=z.object({handoff:z.enum(['customer-candidate','operating-staging']).default('customer-candidate'),syntheticPassword:z.string().min(16).max(128).optional(),repoRoot:z.string(),bundleSha256:z.string().regex(/^[a-f0-9]{64}$/),githubToken:z.string().min(1),vercelToken:z.string().min(20),installedOperator:z.object({providerToken:z.string().min(20),journalStorageKey:z.string().min(20),migrationPassword:z.string().min(1)}).strict().optional()}).strict();
const publicSchema=z.object({apiUrl:z.string().url(),supabaseUrl:z.string().url(),supabasePublishableKey:z.string().startsWith('sb_publishable_').min(20)}).strict();
export type BackendWebSettingsResult={purpose:'CUEVO_STAGING_PUBLIC_WEB_SETTINGS';status:'WEB_PUBLIC_SETTINGS_CONFIRMED'|'REQUIRES_REVIEW';operation:'NONE'|'UNKNOWN'|'CONFIRMED'|'NOOP';sourceSha:string|null;runId:string|null;runAttempt:number|null;packageSha256:string|null;manifestSha256:string|null;webProjectId:string;teamId:string;observedAt:string;settingsSha256:string|null;manifestPath:string|null;publicConfigurationPath:string|null;pendingGates:string[];hostedAcceptance:false;canonicalReceipt:string|null};
async function file(root:string,path:string,maximum=131072){if(!isAbsolute(path)||resolve(path)!==path||isAbsolute(relative(root,path))||relative(root,path).split(/[\\/]/).some(p=>p==='..'))throw fail();let current=root;const parts=relative(root,path).split(/[\\/]/);for(const[index,part]of parts.entries()){current=join(current,part);const stat=await lstat(current);if(stat.isSymbolicLink()||await realpath(current)!==current||(index===parts.length-1?!stat.isFile()||stat.nlink!==1||stat.size>maximum:!stat.isDirectory()))throw fail();}const before=await lstat(path),bytes=await readFile(path),after=await lstat(path);if(bytes.length>maximum||before.dev!==after.dev||before.ino!==after.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs)throw fail();return bytes;}
async function persist(path:string,value:unknown){const f=await open(path,'wx',0o600);try{await f.writeFile(canonicalReleaseExecutionJson(value));await f.sync();}finally{await f.close();}}
async function request(url:string,method:'GET'|'POST',token:string,body?:unknown){const signal=AbortSignal.timeout(10000),response=await fetch(url,{method,headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'error',cache:'no-store',credentials:'omit',signal});if(response.redirected||response.url&&response.url!==url||!response.body)throw fail();const declared=response.headers.get('content-length');if(declared!==null&&(!/^\d+$/.test(declared)||Number(declared)>131072))throw fail();const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{for(;;){const part=await new Promise<ReadableStreamReadResult<Uint8Array>>((done,reject)=>{const abort=()=>{signal.removeEventListener('abort',abort);reject(fail());};if(signal.aborted)return abort();signal.addEventListener('abort',abort,{once:true});void reader.read().then(v=>{signal.removeEventListener('abort',abort);done(v);},()=>{signal.removeEventListener('abort',abort);reject(fail());});});if(part.done)break;size+=part.value.byteLength;if(size>131072||signal.aborted)throw fail();chunks.push(part.value);}return{status:response.status,value:JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(Buffer.concat(chunks)))as unknown};}finally{void reader.cancel().catch(()=>undefined);try{reader.releaseLock();}catch{/* Pending cancellation owns its stream cleanup. */}}}

/** Consumes the native handover rather than duplicating its readiness gates.
 * Public fields are stored as plain preview values; unknown/conflicting project
 * variables refuse admission and no existing variable is overwritten/deleted. */
export async function configureBackendWebSettings(value:unknown,borrowedAdmission?:NativeBackendAdmissionHandle):Promise<BackendWebSettingsResult>{
 const r:BackendWebSettingsResult={purpose:'CUEVO_STAGING_PUBLIC_WEB_SETTINGS',status:'REQUIRES_REVIEW',operation:'NONE',sourceSha:null,runId:null,runAttempt:null,packageSha256:null,manifestSha256:null,webProjectId:project,teamId:team,observedAt:new Date().toISOString(),settingsSha256:null,manifestPath:null,publicConfigurationPath:null,pendingGates:[],hostedAcceptance:false,canonicalReceipt:null};let folder='',admissionHandle:NativeBackendAdmissionHandle|undefined;
 try{
  const input=schema.parse(JSON.parse(canonicalReleaseExecutionJson(value))),root=input.repoRoot;if(!isAbsolute(root)||resolve(root)!==root||await realpath(root)!==root)throw fail();folder=join(root,'.local/hosted-release');const intent=join(folder,'web-settings-intent.json');try{await lstat(intent);throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}
  const bundleBytes=await file(root,join(folder,'backend-bundle.json'),1024*1024);if(hash(bundleBytes)!==input.bundleSha256)throw fail();const bundle=z.object({version:z.union([z.literal(1),z.literal(2)]),purpose:z.literal('CUEVO_BACKEND_RELEASE_EXECUTION'),repoRoot:z.literal(root),expected:z.unknown(),preparedApproval:z.unknown()}).parse(JSON.parse(bundleBytes.toString('utf8'))),expected=bundle.expected as BackendReleaseExpected,prepared=validatePreparedBackendReleaseIntent(bundle.preparedApproval,{...expected,now:Date.now()});
  if(expected.targets.web.projectId!==project||expected.targets.web.teamId!==team||expected.targets.web.target!=='preview')throw fail();Object.assign(r,{sourceSha:expected.releaseSha,runId:expected.releaseRunId,runAttempt:expected.runAttempt,packageSha256:prepared.sha256});
  const binding={repoRoot:root,expected,prepared,effectScope:'COMPLETE_BACKEND' as const};admissionHandle=borrowedAdmission===undefined?await prepareNativeBackendReleaseAdmission({...binding,githubToken:input.githubToken}):borrowedAdmission;const admission=()=>readNativeBackendReleaseAdmission(admissionHandle,binding);await admission();
  const{handoff:_handoff,syntheticPassword:_password,...fullInputs}=input;void _handoff;void _password;
  const operating=input.handoff==='operating-staging'?await revalidateOperatingStagingHandoff({...fullInputs,syntheticPassword:input.syntheticPassword},admissionHandle):null;
  const full=operating?null:await prepareBackendWebHandover(fullInputs,admissionHandle),handover=operating?{status:operating.status==='OPERATING_STAGING_PREPARED'?'PREPARED_STAGING_MANIFEST':'REQUIRES_REVIEW',pendingGates:operating.pendingGates,manifestPath:operating.handoffPath,publicConfigurationPath:operating.publicConfigurationPath,manifestSha256:operating.handoffSha256}:full!;r.pendingGates=handover.pendingGates;if(handover.status!=='PREPARED_STAGING_MANIFEST'||handover.pendingGates.length||!handover.manifestPath||!handover.publicConfigurationPath||!handover.manifestSha256)throw fail();if(handover.manifestPath!==join(folder,operating?'operating-staging-handoff.json':'web-handover-manifest.json')||handover.publicConfigurationPath!==join(folder,operating?'operating-staging-public.json':'web-handover-public.json'))throw fail();
  const manifestBytes=await file(root,handover.manifestPath,1024*1024);if(hash(manifestBytes)!==handover.manifestSha256)throw fail();const publicConfig=publicSchema.parse(JSON.parse((await file(root,handover.publicConfigurationPath,16384)).toString('utf8'))),manifest=operating?validateOperatingStagingHandoff(JSON.parse(manifestBytes.toString('utf8')),Date.now()):z.object({version:z.literal(2),environment:z.literal('staging'),commitSha:z.literal(expected.releaseSha),publicConfig:publicSchema}).parse(JSON.parse(manifestBytes.toString('utf8')));if(canonicalReleaseExecutionJson(publicConfig)!==canonicalReleaseExecutionJson(manifest.publicConfig)||publicConfig.apiUrl!==expected.targets.api.origin)throw fail();r.manifestPath=handover.manifestPath;r.publicConfigurationPath=handover.publicConfigurationPath;r.manifestSha256=handover.manifestSha256;
  const settings={NEXT_PUBLIC_API_URL:publicConfig.apiUrl,NEXT_PUBLIC_SUPABASE_URL:publicConfig.supabaseUrl,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:publicConfig.supabasePublishableKey};r.settingsSha256=hash(canonicalReleaseExecutionJson(settings));
  const scope='?teamId='+team,base='https://api.vercel.com';const metadata=await request(base+'/v9/projects/'+project+scope,'GET',input.vercelToken);if(metadata.status!==200)throw fail();z.object({id:z.literal(project),accountId:z.literal(team),rootDirectory:z.literal('apps/web')}).parse(metadata.value);
  const domains=await request(base+'/v9/projects/'+project+'/domains'+scope,'GET',input.vercelToken);if(domains.status!==200)throw fail();const domainSet=z.object({domains:z.array(z.object({name:z.string(),projectId:z.literal(project),verified:z.boolean()})),pagination:z.object({next:z.null()}).optional()}).parse(domains.value);if(domainSet.domains.filter(d=>d.name===new URL(expected.targets.web.origin).hostname&&d.verified).length!==1)throw fail();
  const path=base+'/v10/projects/'+project+'/env'+scope;
  const inventory=async()=>{const response=await request(path+'&decrypt=false','GET',input.vercelToken);if(response.status!==200)throw fail();return z.object({envs:z.array(z.object({id:z.string().optional(),key:z.string(),value:z.string().optional(),type:z.string(),target:z.array(z.string()),gitBranch:z.string().nullable().optional(),customEnvironmentIds:z.array(z.string()).optional()}).passthrough()).max(100)}).parse(response.value).envs;};
  const exact=(rows:Awaited<ReturnType<typeof inventory>>)=>rows.length===3&&new Set(rows.map(v=>v.key)).size===3&&rows.every(row=>Object.hasOwn(settings,row.key)&&row.type==='plain'&&row.target.length===1&&row.target[0]==='preview'&&!row.gitBranch&&(!row.customEnvironmentIds||!row.customEnvironmentIds.length)&&row.value===settings[row.key as keyof typeof settings]);
  const before=await inventory();if(before.length&&!exact(before))throw fail();await persist(intent,{purpose:r.purpose,sourceSha:r.sourceSha,runId:r.runId,runAttempt:r.runAttempt,packageSha256:r.packageSha256,manifestSha256:r.manifestSha256,webProjectId:project,teamId:team,settingsSha256:r.settingsSha256,keys:Object.keys(settings),target:'preview',createdAt:new Date().toISOString()});
  if(before.length){r.operation='NOOP';}else{await admission();if((await inventory()).length)throw fail();r.operation='UNKNOWN';const response=await request(path,'POST',input.vercelToken,Object.entries(settings).map(([key,v])=>({key,value:v,type:'plain',target:['preview'],comment:'Cuevo source-bound public configuration '+expected.releaseSha})));if(![200,201].includes(response.status)||!z.object({failed:z.array(z.unknown()).length(0)}).safeParse(response.value).success)throw fail();if(!exact(await inventory()))throw fail();r.operation='CONFIRMED';}
  await admission();if(!exact(await inventory()))throw fail();r.status='WEB_PUBLIC_SETTINGS_CONFIRMED';r.observedAt=new Date().toISOString();
 }catch{r.status='REQUIRES_REVIEW';}
 finally{try{if(folder&&r.operation!=='NONE')try{r.canonicalReceipt=canonicalReleaseExecutionJson({...r,canonicalReceipt:null});await persist(join(folder,'web-settings-result.json'),{...r,canonicalReceipt:null});}catch{r.status='REQUIRES_REVIEW';r.canonicalReceipt=null;}}finally{if(admissionHandle&&borrowedAdmission===undefined)disposeNativeBackendReleaseAdmission(admissionHandle);}}
 return r;
}
