import {createHash} from 'node:crypto';
import {readFile,lstat,realpath,open} from 'node:fs/promises';
import {join,relative,isAbsolute,resolve} from 'node:path';
import {z} from 'zod';
import {canonicalReleaseExecutionJson,parseReleaseExecutionJson} from './release-review';
import {backendReleaseExecutionSchema} from './backend-release-delivery';
import {validatePreparedBackendReleaseIntent,type BackendReleaseExpected} from './backend-release-contracts';
import {publicRuntimeReleaseStateSchema,runtimeReleaseStateSha256,readInstalledRuntimeMetadata,validateRuntimeReleasePublicState} from '../database/hosted-active-runtime-state';
import {runtimeRolloutCompatibilitySchema,runtimeContractSha256,validateRuntimeRolloutCompatibility} from './runtime-rollout-compatibility';
const digest=z.string().regex(/^[a-f0-9]{64}$/),sha=z.string().regex(/^[a-f0-9]{40}$/),id=z.string().regex(/^[1-9][0-9]*$/),positive=z.number().int().positive().max(Number.MAX_SAFE_INTEGER),stamp=z.iso.datetime({offset:true}),hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),fail=()=>Error('Original runtime recovery export requires exact immutable evidence; contents withheld.');
const encrypted=z.object({version:z.literal(1),purpose:z.literal('CUEVO_ENCRYPTED_RUNTIME_HISTORY'),projectRef:z.string().regex(/^[a-z]{20}$/),generation:z.string().regex(/^[1-9][0-9]{0,18}$/),operationSha256:digest,previousSha256:digest.nullable(),nonce:z.string(),ciphertext:z.string(),tag:z.string()}).strict();
const operationIntent=z.object({purpose:z.literal('CUEVO_HOSTED_RUNTIME_ROLLOUT'),sourceSha:sha,runId:id,runAttempt:positive,packageSha256:digest,operationSha256:digest,previousStateSha256:digest,desiredGeneration:z.string(),compatibilitySha256:digest,archiveSha256:digest}).strict();
export const runtimeRolloutRecoveryExportSchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_RUNTIME_ROLLOUT_RECOVERY_EXPORT'),originalPreparedApproval:z.unknown(),originalExpected:z.unknown(),publicState:publicRuntimeReleaseStateSchema,compatibility:runtimeRolloutCompatibilitySchema,encryptedHistoryEnvelopeBase64:z.string().max(65536),encryptedHistorySha256:digest,operationIntent,observedAt:stamp,hostedAcceptance:z.literal(false)}).strict();
export function validateRuntimeRolloutRecoveryExport(value:unknown,now=Date.now()){
 const result=runtimeRolloutRecoveryExportSchema.parse(JSON.parse(canonicalReleaseExecutionJson(value))),expected=result.originalExpected as BackendReleaseExpected,prepared=validatePreparedBackendReleaseIntent(result.originalPreparedApproval,expected),binding=expected.runtimeRollout,pending=result.publicState.pending,intent=result.operationIntent;
 const activation=result.publicState.original.activation;if(!activation||Object.keys(activation).some(key=>!['status','sourceSha','projectRef','runId','runAttempt','packageSha256','runtimeSha256','apiDeploymentId','edgeVersion','jobId','sourceProcessed','duplicateWakeDenied','originalCommandReplayed','recoveryScheduled','scheduledRecoveryVerified','configurationEvidenceObservedManual','sessionsClosed','keyOperation','dispatchOperation','probeEventId','observedAt','purpose','phase','dispatchDisabledOnFailure','recovery','recoveryVerified','hostedAcceptance','canonicalReceipt'].includes(key)))throw fail();
 for(const[key,want]of Object.entries({purpose:'CUEVO_HOSTED_WORKER_ACTIVATION',phase:'FINAL',dispatchDisabledOnFailure:null,recoveryVerified:false,hostedAcceptance:false,canonicalReceipt:null}))if(Object.hasOwn(activation,key)&&activation[key]!==want)throw fail();
 if(Object.keys(expected.ciRun).some(key=>!['id','head_sha','head_branch','event','status','conclusion','path','repository','run_attempt'].includes(key))||Object.keys(expected.backendRun).some(key=>!['id','head_sha','head_branch','event','status','conclusion','path','repository','run_attempt'].includes(key))||Object.keys(expected.ciRun.repository).some(key=>key!=='full_name')||Object.keys(expected.backendRun.repository).some(key=>key!=='full_name'))throw fail();
 if(activation.recovery!==undefined&&activation.recovery!==null)z.object({status:z.literal('SCHEDULED_RECOVERY_VERIFIED'),basis:z.literal('ACTUAL_CRON_AFTER_MISSED_POST_COMMIT_HINT'),originalKey:z.string().max(200),eventId:z.uuid(),releasedAt:stamp,cronRunId:positive,missedHintVerified:z.literal(true),scheduledRecoveryVerified:z.literal(true),eventRetryVerified:z.literal(false),expiredLeaseRecoveryVerified:z.literal(false),dispatchBackoffVerified:z.literal(false),hostedAcceptance:z.literal(false),elapsedMs:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER)}).strict().parse(activation.recovery);
 if(activation.recovery!==undefined&&activation.recovery!==null&&z.object({originalKey:z.string(),eventId:z.string()}).parse(activation.recovery).originalKey!==`worker-activation:${result.publicState.original.identity.originalRunId}:${result.publicState.original.identity.originalRunAttempt}:${result.publicState.original.identity.activationId}`)throw fail();
 if(expected.executionScope!=='runtime-rollout'||!binding||binding.version!==1||!pending||pending.identity.sourceSha!==binding.desired.sourceSha||pending.identity.treeSha!==binding.desired.treeSha||pending.identity.runId!==expected.releaseRunId||pending.identity.runAttempt!==expected.runAttempt||pending.identity.packageSha256!==prepared.sha256||pending.operationSha256!==binding.operationSha256||pending.identity.generation!==binding.desired.generation||result.publicState.projectRef!==expected.targets.supabase.projectRef||runtimeContractSha256(result.compatibility)!==binding.desired.compatibilitySha256||intent.sourceSha!==expected.releaseSha||intent.runId!==expected.releaseRunId||intent.runAttempt!==expected.runAttempt||intent.packageSha256!==prepared.sha256||intent.operationSha256!==binding.operationSha256||intent.previousStateSha256!==binding.previous.stateSha256||intent.desiredGeneration!==binding.desired.generation||intent.compatibilitySha256!==binding.desired.compatibilitySha256||intent.archiveSha256!==result.encryptedHistorySha256)throw fail();
 if(!samePublicBase(result.publicState,binding.previous.stateSha256))throw fail();const approvedBody=JSON.parse(prepared.canonicalJson) as Record<string,unknown>,{version:_version,purpose:_purpose,preparedAt:_preparedAt,expiresAt:_expiresAt,reviews:_reviews,...identity}=approvedBody;void _version;void _purpose;void _preparedAt;void _expiresAt;void _reviews;const approvedExpected={...identity,reviews:expected.reviews,now:expected.now,currentMainSha:expected.currentMainSha,ciRun:expected.ciRun,backendRun:expected.backendRun};if(canonicalReleaseExecutionJson(expected)!==canonicalReleaseExecutionJson(approvedExpected))throw fail();
 const bytes=Buffer.from(result.encryptedHistoryEnvelopeBase64,'base64');if(bytes.length>49152||bytes.toString('base64')!==result.encryptedHistoryEnvelopeBase64||hash(bytes)!==result.encryptedHistorySha256)throw fail();const envelope=encrypted.parse(parseReleaseExecutionJson(bytes.toString('utf8')));if(envelope.projectRef!==result.publicState.projectRef||envelope.generation!==binding.previous.generation||envelope.operationSha256!==binding.operationSha256||envelope.previousSha256!==(result.publicState.historyHead?.sha256??null)||Buffer.from(envelope.nonce,'base64').length!==12||Buffer.from(envelope.tag,'base64').length!==16||!envelope.ciphertext)throw fail();
 for(const value of[envelope.nonce,envelope.tag,envelope.ciphertext])if(!/^[A-Za-z0-9+/]+={0,2}$/.test(value)||Buffer.from(value,'base64').toString('base64')!==value)throw fail();
 if(!Number.isSafeInteger(now)||now<0||Date.parse(result.observedAt)>now||now-Date.parse(result.observedAt)>14*86400000||expected.now>now)throw fail();const body=z.object({preparedAt:stamp,expiresAt:stamp}).passthrough().parse(JSON.parse(prepared.canonicalJson));if(Date.parse(result.observedAt)<Date.parse(body.preparedAt))throw fail();
 validateRuntimeReleasePublicState(result.publicState,result.publicState.projectRef);readInstalledRuntimeMetadata([{state:result.publicState.original}],result.publicState.projectRef); if((activation.purpose!==undefined&&activation.purpose!=='CUEVO_HOSTED_WORKER_ACTIVATION')||(activation.phase!==undefined&&activation.phase!=='FINAL')||[result.publicState.original.identity.createdAt,result.publicState.original.activation!.observedAt,result.publicState.original.cleanup!.observedAt,...result.publicState.current.receipts.map(row=>row.observedAt)].some(clock=>Date.parse(clock)>Date.parse(result.observedAt)))throw fail();const current=result.publicState.current;if(current.phase!=='CONFIRMED'||current.identity.generation!==binding.previous.generation)throw fail();for(const key of['generation','sourceSha','treeSha','runtimeSha256','apiDeploymentId','apiUrl','edgeId','edgeVersion','apiArtifactSha256','edgeArtifactSha256','denoLockSha256'] as const)if(current.identity[key]!==binding.previous[key])throw fail();
 if(current.receipts.at(-1)?.sha256!==binding.previous.activationReceiptSha256||pending.previousStateSha256!==binding.previous.stateSha256||pending.runtimeConfigurationSha256!==pending.identity.runtimeSha256||pending.identity.apiArtifactSha256!==binding.desired.apiArtifactSha256||pending.identity.edgeArtifactSha256!==binding.desired.edgeArtifactSha256||pending.identity.denoLockSha256!==binding.desired.denoLockSha256||pending.identity.compatibilitySha256!==binding.desired.compatibilitySha256||pending.identity.executorSourceSha||pending.identity.executorTreeSha||BigInt(pending.identity.generation)!==BigInt(current.identity.generation)+1n)throw fail();
 const compatibility=validateRuntimeRolloutCompatibility(result.compatibility,{previousSourceSha:binding.previous.sourceSha,desiredSourceSha:binding.desired.sourceSha,desiredTreeSha:binding.desired.treeSha,runId:expected.releaseRunId,runAttempt:expected.runAttempt});if(compatibility.pendingMigrations.length||compatibility.manifest.basis==='PAIRED_RUNTIME_VERIFICATION'||pending.identity.migrationSetSha256!==runtimeContractSha256(compatibility.manifest.desired.migrations)||current.identity.migrationSetSha256!==runtimeContractSha256(compatibility.manifest.previous.migrations))throw fail();
 const phases=['INTENT','PAUSED','DRAINED','PROVIDERS_CONFIRMED','PRIVATE_VERIFIED','ALIAS_CONFIRMED','EXECUTION_ENABLED','CONFIRMED'];if(!phases.includes(pending.phase)||pending.receipts.length!==phases.indexOf(pending.phase)+1||pending.receipts.some((receipt,index)=>receipt.phase!==phases[index]||Date.parse(receipt.observedAt)>Date.parse(result.observedAt)||Date.parse(receipt.observedAt)<Date.parse(body.preparedAt)||Date.parse(receipt.observedAt)>=Date.parse(body.expiresAt)||index>0&&Date.parse(receipt.observedAt)<Date.parse(pending.receipts[index-1].observedAt)))throw fail();
 if(pending.phase==='CONFIRMED'){const proof=pending.confirmationEvidence;if(!proof||proof.sourceSha!==pending.identity.sourceSha||proof.generation!==pending.identity.generation||proof.operationSha256!==pending.operationSha256||runtimeReleaseStateSha256(proof)!==pending.receipts.at(-1)!.sha256||proof.observedAt!==pending.receipts.at(-1)!.observedAt)throw fail();}else if(pending.confirmationEvidence)throw fail();
 return{envelope:result,jsonSha256:hash(canonicalReleaseExecutionJson(result)),pendingStateSha256:runtimeReleaseStateSha256(result.publicState),operationSha256:binding.operationSha256};
}
function samePublicBase(state:z.infer<typeof publicRuntimeReleaseStateSchema>,wanted:string){return runtimeReleaseStateSha256({...state,pending:null})===wanted;}
async function owned(root:string,path:string,maximum:number){if(!isAbsolute(root)||resolve(root)!==root||await realpath(root)!==root)throw fail();const part=relative(root,path);if(!part||isAbsolute(part)||part.split(/[\\/]/).some(value=>!value||value==='.'||value==='..'))throw fail();let current=root;for(const name of part.split(/[\\/]/)){current=join(current,name);const row=await lstat(current);if(row.isSymbolicLink()||await realpath(current)!==current)throw fail();}const before=await lstat(path);if(!before.isFile()||before.nlink!==1||before.size>maximum)throw fail();const bytes=await readFile(path),after=await lstat(path);if(before.ino!==after.ino||before.dev!==after.dev||before.mtimeMs!==after.mtimeMs||before.ctimeMs!==after.ctimeMs)throw fail();return bytes;}
/** Reads fixed public native observation and encrypted original history only.
 * No native/provider/GitHub access or cleartext private configuration occurs. */
export async function exportRuntimeRolloutRecovery(value:{repoRoot:string;bundlePath:string;bundleSha256:string;publicStatePath:string}){
 const folder=join(value.repoRoot,'.local/hosted-release');if(value.bundlePath!==join(folder,'backend-bundle.json')||value.publicStatePath!==join(folder,'runtime-rollout-public-state.json'))throw fail();const bytes=await owned(value.repoRoot,value.bundlePath,1024*1024);if(hash(bytes)!==value.bundleSha256)throw fail();const bundle=backendReleaseExecutionSchema.parse(parseReleaseExecutionJson(bytes.toString('utf8'))),expected=bundle.expected as BackendReleaseExpected,binding=expected.runtimeRollout;if(!binding||binding.version!==1)throw fail();
 const publicState=parseReleaseExecutionJson((await owned(value.repoRoot,value.publicStatePath,49152)).toString('utf8')),compatibility=parseReleaseExecutionJson((await owned(value.repoRoot,join(folder,'runtime-compatibility.json'),49152)).toString('utf8')),encryptedBytes=await owned(value.repoRoot,join(folder,'runtime-history-envelope-'+binding.operationSha256+'.json'),49152),intent=parseReleaseExecutionJson((await owned(value.repoRoot,join(folder,'runtime-rollout-'+binding.operationSha256+'.json'),49152)).toString('utf8'));
 const proof=validateRuntimeRolloutRecoveryExport({version:1,purpose:'CUEVO_RUNTIME_ROLLOUT_RECOVERY_EXPORT',originalPreparedApproval:bundle.preparedApproval,originalExpected:bundle.expected,publicState,compatibility,encryptedHistoryEnvelopeBase64:encryptedBytes.toString('base64'),encryptedHistorySha256:hash(encryptedBytes),operationIntent:intent,observedAt:new Date().toISOString(),hostedAcceptance:false}),path=join(folder,'runtime-rollout-recovery.json'),file=await open(path,'wx',0o600);try{await file.writeFile(canonicalReleaseExecutionJson(proof.envelope));await file.sync();}finally{await file.close();}return{status:'ORIGINAL_RUNTIME_RECOVERY_EXPORTED' as const,path,sha256:proof.jsonSha256,hostedAcceptance:false as const};
}
