import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createHash } from 'node:crypto';
import { canonicalReleaseExecutionJson } from './release-review';

const hash=(value:unknown)=>createHash('sha256').update(canonicalReleaseExecutionJson(value)).digest('hex');
const id=(number:number)=>`91000000-0000-4000-8000-${String(number).padStart(12,'0')}`;
const school=id(1),teacher=id(2),student=id(3),admin=id(4),reference=id(5),course=id(6),unit=id(7),lesson=id(8),activity=id(9),completion=id(10);
const at='2026-10-06T08:00:00Z',finished='2026-10-06T08:00:25Z',observed='2026-10-06T08:00:30Z';
const identity={projectRef:'mqxdjvsyckzocokuikmx',schoolId:school,sourceSha:'a'.repeat(40),treeSha:'b'.repeat(40),ciRunId:'123',runId:'456',runAttempt:1,backendTransferSha256:'c'.repeat(64),webDeploymentId:'dpl_fixture',uiArtifactSha256:'d'.repeat(64),journalSha256:'e'.repeat(64),companionManifestSha256:'f'.repeat(64)};
// Mutable malformed synthetic counterexamples are intentionally test-only.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Fixture={ [key:string]:any };
function fixture():Fixture{
 const originals:Fixture[]=[],commands:Fixture[]=[],audits:Fixture[]=[],outbox:Fixture[]=[],processed:Fixture[]=[];
 function add(operation:string,path:string,actorId:string,role:string,response:Fixture,event:string|null,entityType:string,entityId:string,dedup:string|null){
  const n=originals.length+1,key='original-'+n,requestId='req-'+n,fingerprint=hash(['owner-native-fingerprint',n]);
  const target=path.split('/').find(part=>/^[a-f0-9-]{36}$/.test(part))??null;
  const journalIdentity={...identity};for(const field of ['uiArtifactSha256','journalSha256','companionManifestSha256'])delete (journalIdentity as Fixture)[field];
  const original={identity:journalIdentity,command:{step:'step.'+n,actorId,role,schoolId:school,path,operation,sourceIds:target?[target]:[],sourceRevision:null,key,requestBodySha256:hash(['exact-request-bytes',n])},intentSequence:n,intentRecordSha256:hash(['intent',n])};
  const receiptIdentity={id:response.id,...(response.revision===undefined?{}:{revision:response.revision}),...(operation==='intelligence.policy.approve'?{policyVersion:response.version}:{})};
  originals.push({original,targetId:target,nativeFingerprint:fingerprint,http:{status:200,requestId,receiptSha256:hash(operation==='intelligence.policy.approve'?{id:response.id,policy:{version:response.version}}:response),receiptIdentity}});
  commands.push({school_id:school,actor_id:actorId,key,command:operation,fingerprint,state:'COMPLETED',response,created_at:at,completed_at:finished});
  const action=operation==='intelligence.policy.approve'?'intelligence.policy.approved':operation.startsWith('improvement.')?event:operation;
  audits.push({id:id(1000+n),school_id:school,actor_id:actorId,action,entity_type:entityType,entity_id:entityId,request_id:requestId,outcome:'succeeded',metadata:operation==='intelligence.policy.approve'?{version:response.version,purpose:'NEXT_LEARNING_ACTION'}:{},occurred_at:at});
  if(event){const eventId=id(2000+n);outbox.push({id:eventId,school_id:school,actor_id:actorId,type:event,entity_type:entityType,entity_id:entityId,version:response.revision??1,metadata:operation.startsWith('course.')||operation.startsWith('unit.')||operation.startsWith('lesson.')||operation.startsWith('activity.')||operation.startsWith('assessment.')||operation.startsWith('submission.')?{schoolAuthored:true}:{},deduplication_key:dedup??createHash('sha256').update(actorId+':'+operation+':'+key).digest('hex'),occurred_at:at,state:'COMPLETED',attempt_count:1,max_attempts:5,available_at:at,lease_token:null,lease_until:null,completed_at:finished,last_error_code:null});processed.push({event_id:eventId,school_id:school,source_type:null,source_id:null,processed_at:finished});}
 }
 add('course.create','/v1/courses',teacher,'teacher',{id:course},'course.create','course',course,null);
 add('unit.create',`/v1/courses/${course}/units`,teacher,'teacher',{id:unit},'unit.create','unit',unit,null);
 add('lesson.create',`/v1/units/${unit}/lessons`,teacher,'teacher',{id:lesson},'lesson.create','lesson',lesson,null);
 add('activity.create',`/v1/lessons/${lesson}/activities`,teacher,'teacher',{id:activity},'activity.create','activity',activity,null);
 add('course.publish',`/v1/courses/${course}/publish`,teacher,'teacher',{id:course},'course.publish','course',course,null);
 const assessmentIds=[id(20),id(21)],submissionIds=[id(30),id(31)],markingIds=[id(40),id(41)],resultIds=[id(50),id(51)],evidenceIds=[id(60),id(61)];
 for(const assessment of assessmentIds){add('assessment.create','/v1/assessments',teacher,'teacher',{id:assessment,courseId:course},'assessment.create','assessment',assessment,null);add('assessment.preparation',`/v1/assessments/${assessment}/preparation`,teacher,'teacher',{id:assessment,referenceId:reference},'assessment.preparation','assessment',assessment,null);add('assessment.publish',`/v1/assessments/${assessment}/publish`,teacher,'teacher',{id:assessment,status:'PUBLISHED'},'assessment.publish','assessment',assessment,null);}
 add('activity.complete',`/v1/activities/${activity}/complete`,student,'student',{id:completion,activityId:activity,learnerId:student},'activity.complete','activity',completion,null);
 add('submission.draft',`/v1/assessments/${assessmentIds[0]}/draft`,student,'student',{id:id(70),assessmentId:assessmentIds[0],revision:1,status:'DRAFT'},'submission.draft_saved','submission',id(70),null);
 for(let n=0;n<2;n++){add('submission.create',`/v1/assessments/${assessmentIds[n]}/submissions`,student,'student',{id:submissionIds[n],assessmentId:assessmentIds[n],learnerId:student,revision:1},'submission.create','submission',submissionIds[n],null);add('marking.create',`/v1/submissions/${submissionIds[n]}/results`,teacher,'teacher',{id:markingIds[n],submissionId:submissionIds[n],revision:1,score:n?7:2,maxScore:10},'assessment.marked','marking',markingIds[n],null);add('result.release',`/v1/results/${markingIds[n]}/release`,teacher,'teacher',{id:resultIds[n],submissionId:submissionIds[n],assessmentId:assessmentIds[n],learnerId:student,evidenceId:evidenceIds[n],referenceId:reference,referenceVersion:'1',policyVersion:1,revision:1,score:n?7:2,maxScore:10},'result.released','result',resultIds[n],null);const event=outbox.at(-1)!;event.metadata={learnerId:student,referenceId:reference,resultId:resultIds[n],evidenceId:evidenceIds[n],revision:1,policyVersion:1};}
 const proposal=id(80),intervention=id(81),interventionCompletion=id(82),outcome=id(83),portfolio=id(84),portfolioRevision=id(85),observation=id(86);
 add('intelligence.analyze','/v1/intelligence/analyze',teacher,'teacher',{id:proposal,learnerId:student,baselineResultId:resultIds[0],intelligenceRunId:id(87),generationMode:'FIXTURE',origin:'AI_GENERATED',status:'AWAITING_HUMAN'},'recommendation.created','recommendation',proposal,'recommendation.created:'+proposal);audits.at(-1)!.action='recommendation.created';outbox.at(-1)!.metadata={intelligenceRunId:id(87),generationMode:'FIXTURE'};
 for(const [op,path,response,event,entity,entityId]of [
  ['decision',`/v1/recommendations/${proposal}/decision`,{id:proposal,recommendationId:proposal,interventionId:intervention,status:'APPROVED',decision:'APPROVE'},'recommendation.approved','intervention',proposal],
  ['complete',`/v1/interventions/${intervention}/complete`,{id:intervention,status:'COMPLETED',learnerId:student,baselineResultId:resultIds[0]},'intervention.completed','intervention',intervention],
  ['reassessment',`/v1/interventions/${intervention}/reassessment`,{id:intervention,followUpAssessmentId:assessmentIds[1]},'reassessment.linked','intervention',intervention],
  ['measure',`/v1/interventions/${intervention}/measure`,{id:outcome,baselineResultId:resultIds[0],followUpResultId:resultIds[1],baseline:{score:2,maxScore:10},followUp:{score:7,maxScore:10},difference:5,minimumChange:1,status:'improved',limitation:'OBSERVED_CHANGE_NOT_CAUSAL_PROOF'},'outcome.measured','outcome',outcome],
 ]as const)add('improvement.'+op,path,op==='complete'?student:teacher,op==='complete'?'student':'teacher',response,event,entity,entityId,createHash('sha256').update(event+':'+entityId).digest('hex'));
 for(const [op,path,status]of [['create','/v1/portfolio/items','AWAITING_REVIEW'],['review',`/v1/portfolio/items/${portfolio}/review`,'REVIEWED'],['revoke',`/v1/portfolio/items/${portfolio}/parent-revoke`,'PARENT_REVOKED']]as const){const actor=op==='create'?student:teacher;add('portfolio.'+op,path,actor,op==='create'?'student':'teacher',{id:portfolio,revisionId:portfolioRevision,revision:1,status},'portfolio.updated','portfolio',portfolio,'portfolio:'+actor+':original-'+(originals.length+1));}
 const tupleFor=(event:Fixture):[string,string]|null=>event.type==='activity.complete'?['COMPLETION',completion]:event.type==='result.released'?['RESULT',event.entity_id]:event.type==='recommendation.approved'?['RECOMMENDATION_APPROVAL',proposal]:event.type==='intervention.completed'?['INTERVENTION_COMPLETION',interventionCompletion]:event.type==='reassessment.linked'?['REASSESSMENT',intervention]:event.type==='outcome.measured'?['OUTCOME',outcome]:null;
 for(const event of outbox){const tuple=tupleFor(event),row=processed.find(row=>row.event_id===event.id)!;if(tuple){row.source_type=tuple[0];row.source_id=tuple[1];}}
 const sourceEvents=outbox.filter(event=>tupleFor(event)),completionEvent=sourceEvents.find(event=>event.type==='activity.complete')!.id;
 const chain={
  learning:{course_id:course,class_id:id(90),subject_id:id(91),created_by:teacher,status:'PUBLISHED',unit_id:unit,lesson_id:lesson,activity_id:activity,kind:'practice',completion_id:completion,learner_id:student,completed_at:at,content_context:{course_revision_id:id(92),unit_revision_id:id(93),lesson_revision_id:id(94),activity_revision_id:id(95),published:true}},
  results:resultIds.map((result,n)=>({id:result,school_id:school,learner_id:student,submission_id:submissionIds[n],assessment_id:assessmentIds[n],course_id:course,marking_id:markingIds[n],reference_id:reference,reference_version:'1',reference_status:'APPROVED',policy_version:1,revision:1,score:n?7:2,max_score:10,created_by:teacher,created_at:n?'2026-10-06T08:00:12Z':at,submitted_at:n?'2026-10-06T08:00:11Z':at,current:true,model:'numeric',evidence_id:evidenceIds[n],evidence:{id:evidenceIds[n],result_id:result,source_object_id:submissionIds[n],learner_id:student,reference_id:reference,reference_version:'1',policy_version:1,revision:1},source_registered:true,parent_published:true})),
  support:{recommendation_id:proposal,intelligence_run_id:id(87),learner_id:student,reference_id:reference,baseline_result_id:resultIds[0],generation_mode:'FIXTURE',origin:'AI_GENERATED',run_state:'PROPOSAL_READY',evaluation_status:'PASSED',run_actor_id:teacher,run_key:originals.find(row=>row.original.command.operation==='intelligence.analyze')!.original.command.key,run_fingerprint:originals.find(row=>row.original.command.operation==='intelligence.analyze')!.nativeFingerprint,execution_binding_id:id(96),execution_binding_version:1,policy_version:1,provider:'deterministic-fixture',model:'source-locked-v1',provider_data_policy:'HOSTED_SYNTHETIC_FIXTURE',approval_source:'EXPLICIT_SCHOOL_POLICY',decision:'APPROVE',decision_actor_id:teacher,intervention_id:intervention,completion_id:interventionCompletion,completion_learner_id:student,completed_at:'2026-10-06T08:00:10Z',follow_up_assessment_id:assessmentIds[1],status:'MEASURED'},
  outcome:{id:outcome,school_id:school,intervention_id:intervention,learner_id:student,baseline_result_id:resultIds[0],follow_up_result_id:resultIds[1],model:'numeric',baseline_score:2,baseline_max_score:10,follow_up_score:7,follow_up_max_score:10,difference:5,minimum_change:1,status:'improved',limitation:'OBSERVED_CHANGE_NOT_CAUSAL_PROOF',native_baseline:null,native_follow_up:null,comparability:null,measured_at:'2026-10-06T08:00:20Z'},
  observation:{id:observation,school_id:school,learner_id:student,kind:'practice',source_type:'ACTIVITY_COMPLETION',source_object_id:completion,activity_completion_id:completion,submission_id:null,occurred_at:at,source_event_id:completionEvent},
  signal:{school_id:school,learner_id:student,type:'practice_observed',count:1,rule_version:1,observation_ids:[observation],source_event_ids:sourceEvents.map(row=>row.id),window_start:'2026-09-22T08:00:25Z',window_end:finished,expires_at:'2026-10-20T08:00:00Z'},
  snapshot:{school_id:school,learner_id:student,version:2,generated_at:finished,observation_policy_version:1,academic:resultIds.map((result,n)=>({resultId:result,evidenceId:evidenceIds[n],nativeResult:{type:'numeric',score:n?7:2,maxScore:10,policyVersion:1,normalized:null}})),development:{practice:{count:1,observationIds:[observation]},revision:{count:null,observationIds:[]},reflection:{count:0,observationIds:[]},windowEnd:finished},support:{items:[{id:intervention,recommendationId:proposal,status:'MEASURED',followUpAssessmentId:assessmentIds[1]}]},impact:{measurementIds:[outcome],outcomes:[{id:outcome,difference:5,minimumChange:1,limitation:'OBSERVED_CHANGE_NOT_CAUSAL_PROOF'}]},source_event_ids:sourceEvents.filter(event=>!['intervention.completed','reassessment.linked'].includes(event.type)).map(event=>event.id)},
  snapshot_event_owners:sourceEvents.map(event=>({event_id:event.id,school_id:school,learner_id:student,source_type:tupleFor(event)![0],source_id:tupleFor(event)![1]})),
  observation_policy:{version:1,development_window_days:14},
  portfolio:{item_id:portfolio,learner_id:student,source_model:'numeric',evidence_id:evidenceIds[1],revision_id:portfolioRevision,revision:1,reviewed_by:teacher,review_parent_visible:true,parent_revision_id:null,revocation_actor_id:teacher},
  api_projection:{learnerId:student,status:'READY',freshness:'CURRENT',observedAt:observed,generatedAt:finished,version:2,windowEnd:finished,academicResultIds:resultIds,observationIds:[observation],interventionIds:[intervention],measurementIds:[outcome],sourceEventIds:sourceEvents.filter(event=>!['intervention.completed','reassessment.linked'].includes(event.type)).map(event=>event.id)},
 };
 const manifest={version:'teacher-insight-1',purpose:'NEXT_LEARNING_ACTION',capabilities:['GROUNDED_EXPLANATION','RECOMMENDATION'],mode:'FIXTURE',provider:'deterministic-fixture',model:'source-locked-v1',promptId:'next-learning-action',promptVersion:'1',promptDigest:'a54af580544321d5cd3d9b212f423dd01bb4599a2ce3ec7a2bf9d3c32dfe5077',promptSource:'SOURCE_CONTROLLED_TASK_POLICY',promptEffectiveAt:'2026-10-01T00:00:00Z',evaluationVersion:'source-78-checked-evidence-1',dataClassification:'SCHOOL_CUSTOM_NUMERIC',providerDataPolicy:'HOSTED_SYNTHETIC_FIXTURE',maxOutputTokens:1000,timeoutMs:10000,maxCost:1};
 Object.assign(chain.support,{run_request_id:originals.find(row=>row.original.command.operation==='intelligence.analyze')!.http.requestId,run_completed_at:at,run_lease_token:null,run_lease_until:null});
 Object.assign(chain.learning.content_context,{revisions:[['course',course,id(92)],['unit',unit,id(93)],['lesson',lesson,id(94)],['activity',activity,id(95)]].map(([resource,source_id,revisionId])=>({id:revisionId,school_id:school,course_id:course,resource,source_id,state:'PUBLISHED'}))});
 const policy={school_id:school,version:chain.support.policy_version,approved_by:admin,approval_version:chain.support.policy_version,fixture_enabled:true,live_enabled:false,binding_id:chain.support.execution_binding_id,binding_version:chain.support.execution_binding_version,binding_policy_version:chain.support.policy_version,binding_approved_by:admin,approval_source:'EXPLICIT_SCHOOL_POLICY',manifest_sha256:hash(manifest),expected_manifest_sha256:hash(manifest),binding_manifest:manifest,current_manifest:manifest};
 return{identity,scope:{schoolId:school,teacherId:teacher,studentId:student,adminId:admin,classId:id(90),subjectId:id(91),referenceId:reference},mode:'FULL_LOOP',observedAt:observed,originals,evidence:{commands,audits,outbox,processed,chain,policy}};
}
async function subject(){let api:Record<string,unknown>={};try{api=await import('./backend-hosted-learning-loop-native');}catch(error){if((error as NodeJS.ErrnoException).code!=='ERR_MODULE_NOT_FOUND')throw error;}assert.equal(typeof api.validateHostedLearningLoopNativeEvidence,'function','The native evidence validator must exist.');return api as typeof import('./backend-hosted-learning-loop-native');}

test('complete original numeric loop validates exact native sources without granting hosted or approval authority',async()=>{const api=await subject(),result=api.validateHostedLearningLoopNativeEvidence(fixture());assert.equal(result.status,'VERIFIED');assert.equal(result.chainVerified,true);assert.equal(result.hostedAcceptance,false);assert.equal(result.customerReady,false);assert.equal(result.officialAdmissionVerified,false);assert.equal(result.nativeExecutionVerified,false);assert.deepEqual(result.nativeOutcome,{baseline:2,followUp:7,maxScore:10,difference:5,minimumChange:1,limitation:'OBSERVED_CHANGE_NOT_CAUSAL_PROOF'});});
test('UI CURRENT freshness is proven at its captured observation clock while native validation may occur later',async()=>{
 const api=await subject(),f=fixture();Object.assign(f.evidence.chain.api_projection,{observedAt:observed,generatedAt:finished,version:2,windowEnd:finished});f.observedAt='2026-10-06T08:05:00Z';
 assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'VERIFIED');
});
test('captured UI projection clock and snapshot identity cannot be missing stale future or replaced',async()=>{
 const api=await subject();for(const change of[(f:Fixture)=>delete f.evidence.chain.api_projection.observedAt,(f:Fixture)=>f.evidence.chain.api_projection.observedAt='2026-10-06T08:02:00Z',(f:Fixture)=>f.evidence.chain.api_projection.observedAt='2026-10-06T08:06:00Z',(f:Fixture)=>f.evidence.chain.api_projection.version=3,(f:Fixture)=>f.evidence.chain.api_projection.generatedAt=at,(f:Fixture)=>f.evidence.chain.api_projection.windowEnd=at]){const f=fixture();Object.assign(f.evidence.chain.api_projection,{observedAt:observed,generatedAt:finished,version:2,windowEnd:finished});f.observedAt='2026-10-06T08:05:00Z';change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}
});
test('protected admission brackets the read deadline without charging source admission time to native reads',async()=>{
 const api=await subject(),f=fixture();Object.assign(f.evidence.chain.api_projection,{observedAt:observed,generatedAt:finished,version:2,windowEnd:finished});let clock=Date.parse(observed),admissions=0;
 const result=await api.verifyHostedLearningLoopNativeEvidence({identity:f.identity,scope:f.scope,mode:f.mode,originals:f.originals,deadlineMs:1000},{admitCurrentQa:async()=>{admissions++;clock+=90000;},readEvidence:async()=>{clock+=100;return f.evidence;},now:()=>clock,pause:async()=>{}});
 assert.equal(result.status,'VERIFIED');assert.equal(admissions,2);assert.equal(result.nativeExecutionVerified,false);
});
test('empty or incomplete native and filtered API source-event sets cannot certify the original loop',async()=>{const api=await subject();for(const change of[(f:Fixture)=>{f.evidence.chain.snapshot.source_event_ids=[];f.evidence.chain.api_projection.sourceEventIds=[];},(f:Fixture)=>{f.evidence.chain.snapshot.source_event_ids=f.evidence.chain.snapshot.source_event_ids.slice(1);},(f:Fixture)=>{f.evidence.chain.api_projection.sourceEventIds=f.evidence.chain.api_projection.sourceEventIds.slice(1);},(f:Fixture)=>{f.evidence.chain.snapshot.source_event_ids.push(id(999));f.evidence.chain.snapshot_event_owners.push({event_id:id(999),school_id:school,learner_id:student});f.evidence.processed.push({event_id:id(999),school_id:school,source_type:'RESULT',source_id:id(998),processed_at:finished});}]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('the exact proposal run and execution approval identities cannot be replaced by unrelated native records',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.chain.support.intelligence_run_id=id(999),(f:Fixture)=>f.evidence.chain.support.execution_binding_id=id(999),(f:Fixture)=>f.evidence.chain.support.execution_binding_version=999,(f:Fixture)=>f.evidence.chain.support.policy_version=999]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('portfolio review and revocation retain the actual originally selected revision',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.chain.portfolio.revision_id=id(999),(f:Fixture)=>f.evidence.chain.portfolio.revision=999]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('snapshot generation must follow its measured source without inventing a generatedAt freshness TTL',async()=>{const api=await subject();for(const generated_at of ['2020-01-01T00:00:00Z','2026-10-06T08:01:00Z']){const f=fixture();f.evidence.chain.snapshot.generated_at=generated_at;assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('published completion revision tuples belong to the same original course and four resources',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.chain.learning.content_context.activity_revision_id=id(999),(f:Fixture)=>f.evidence.chain.learning.content_context.revisions[3].source_id=id(999),(f:Fixture)=>f.evidence.chain.learning.content_context.revisions[2].course_id=id(999),(f:Fixture)=>f.evidence.chain.learning.content_context.revisions[0].school_id=id(999)]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('the current full execution manifest and terminal run lease are source-bound',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.policy=null,(f:Fixture)=>f.evidence.policy.binding_approved_by=teacher,(f:Fixture)=>f.evidence.policy.current_manifest.maxOutputTokens=2,(f:Fixture)=>f.evidence.policy.binding_manifest.providerDataPolicy='LOCAL_SYNTHETIC_FIXTURE',(f:Fixture)=>f.evidence.chain.support.run_request_id='foreign-request',(f:Fixture)=>f.evidence.chain.support.run_lease_token=id(999),(f:Fixture)=>f.evidence.chain.support.run_completed_at=observed]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('valid earlier source events remain allowed when their native owner descriptors match processed records',async()=>{const api=await subject(),f=fixture(),event_id=id(998),source_id=id(997);f.evidence.chain.snapshot.source_event_ids.push(event_id);f.evidence.chain.api_projection.sourceEventIds.push(event_id);f.evidence.chain.snapshot_event_owners.push({event_id,school_id:school,learner_id:student,source_type:'RESULT',source_id});f.evidence.processed.push({event_id,school_id:school,source_type:'RESULT',source_id,processed_at:finished});assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'VERIFIED');f.evidence.chain.snapshot_event_owners.at(-1).source_id=id(999);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');});
test('foreign original keys fingerprints actors targets and response hashes fail closed',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.commands[0].key='another-key',(f:Fixture)=>f.evidence.commands[0].fingerprint='0'.repeat(64),(f:Fixture)=>f.originals[0].original.command.actorId=student,(f:Fixture)=>f.originals[1].targetId=id(999),(f:Fixture)=>f.originals[0].http.receiptSha256='0'.repeat(64)]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('audit request identity and exact outbox source identity are required',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.audits[0].request_id='foreign-request',(f:Fixture)=>f.evidence.outbox[0].entity_id=id(999),(f:Fixture)=>f.evidence.outbox[0].deduplication_key='foreign',(f:Fixture)=>f.evidence.audits.push(f.evidence.audits[0])]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('processed source completion identifies its completion row and never its intervention',async()=>{const api=await subject();const f=fixture(),event=f.evidence.outbox.find((row:Fixture)=>row.type==='intervention.completed');f.evidence.processed.find((row:Fixture)=>row.event_id===event.id).source_id=event.entity_id;assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');});
test('pending leases absent records and failed reads remain unknown without inferred zeros',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.commands=[],(f:Fixture)=>f.evidence.outbox[0].state='PENDING',(f:Fixture)=>f.evidence.outbox[0].lease_token=id(500),(f:Fixture)=>f.evidence.processed=[],(f:Fixture)=>f.evidence.chain=null]){const f=fixture();change(f);const r=api.validateHostedLearningLoopNativeEvidence(f);assert.equal(r.status,'REQUIRES_REVIEW');assert.equal(r.chainVerified,false);assert.equal(r.nativeOutcome,null);}});
test('practice completion proves only its recorded kind and exact original source event',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.chain.observation.kind='reflection',(f:Fixture)=>f.evidence.chain.observation.source_event_id=id(500),(f:Fixture)=>f.evidence.chain.observation.source_object_id=id(500),(f:Fixture)=>f.evidence.chain.signal.count=null]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('native2to7 difference5 threshold1 and noncausal limitation are retained',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.chain.results[0].score=3,(f:Fixture)=>f.evidence.chain.outcome.difference=4,(f:Fixture)=>f.evidence.chain.outcome.minimum_change=2,(f:Fixture)=>f.evidence.chain.outcome.limitation='CAUSED_IMPROVEMENT',(f:Fixture)=>f.evidence.chain.results[1].submitted_at=at]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('current filtered snapshot and API event sets need not contain all processed support events',async()=>{const api=await subject();const f=fixture();assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'VERIFIED');f.evidence.chain.snapshot.source_event_ids.push(id(999));assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');});
test('stale or foreign learner snapshots cannot establish the current chain',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.chain.snapshot.learner_id=teacher,(f:Fixture)=>f.evidence.chain.snapshot.development.windowEnd='2026-10-06T07:58:00Z',(f:Fixture)=>f.evidence.chain.snapshot.observation_policy_version=2,(f:Fixture)=>f.evidence.chain.api_projection.sourceEventIds.push(id(999))]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('uncertain originals can reconcile native commitment without manufacturing UI or derived completion',async()=>{const api=await subject();const f=fixture();f.mode='ORIGINAL_RECONCILIATION';f.originals=f.originals.slice(0,1);f.originals[0].http=null;f.evidence.commands=f.evidence.commands.slice(0,1);f.evidence.audits=f.evidence.audits.slice(0,1);f.evidence.outbox=f.evidence.outbox.slice(0,1);f.evidence.outbox[0].state='PENDING';f.evidence.outbox[0].completed_at=null;f.evidence.processed=[];f.evidence.chain=null;const r=api.validateHostedLearningLoopNativeEvidence(f);assert.equal(r.status,'ORIGINAL_RECONCILIATION_VERIFIED');assert.equal(r.chainVerified,false);assert.equal(r.nativeOutcome,null);assert.equal(r.commands[0].httpReceiptObserved,false);});
test('opaque approval strings extra properties and accessors confer no native authority or leak content',async()=>{const api=await subject();const f=fixture();f.approval='OFFICIAL_APPROVED';assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');let reads=0;const r=api.validateHostedLearningLoopNativeEvidence({get identity(){reads++;throw Error('private-body');}});assert.equal(reads,0);assert.equal(r.status,'REQUIRES_REVIEW');assert.equal(JSON.stringify(r).includes('private-body'),false);});
test('read-only engine admits exact input before fixed reads and reports failed reads without resending',async()=>{const api=await subject(),f=fixture(),calls:string[]=[];const r=await api.verifyHostedLearningLoopNativeEvidence({identity:f.identity,scope:f.scope,mode:f.mode,originals:f.originals,deadlineMs:60000},{admitCurrentQa:async()=>{calls.push('admit');},readEvidence:async()=>{calls.push('read');throw Error('private-database-error');},now:()=>Date.parse(observed),pause:async()=>{calls.push('pause');}});assert.equal(r.status,'REQUIRES_REVIEW');assert.deepEqual(calls,['admit','read']);assert.equal(JSON.stringify(r).includes('private-database-error'),false);});

function policyFixture():Fixture{
 const f=fixture(),template=structuredClone(f.originals[0]),commandKey='policy-original',fingerprint=hash(['parsed-input','current-full-execution-manifest']),requestId='req-policy';
 template.original.command={...template.original.command,step:'policy.approve',actorId:admin,role:'admin',path:'/v1/intelligence/policy',operation:'intelligence.policy.approve',sourceIds:[],key:commandKey};template.original.intentSequence=32;template.original.intentRecordSha256=hash(['policy-intent']);template.targetId=null;template.nativeFingerprint=fingerprint;template.http={status:200,requestId,receiptSha256:hash({id:school,policy:{version:1,fixtureEnabled:true,liveEnabled:false}}),receiptIdentity:{id:school,policyVersion:1}};f.originals.push(template);
 f.evidence.commands.push({school_id:school,actor_id:admin,key:commandKey,command:'intelligence.policy.approve',fingerprint,state:'COMPLETED',response:{id:school,version:1},created_at:at,completed_at:finished});
 f.evidence.audits.push({id:id(600),school_id:school,actor_id:admin,action:'intelligence.policy.approved',entity_type:'school',entity_id:school,request_id:requestId,outcome:'succeeded',metadata:{version:1,purpose:'NEXT_LEARNING_ACTION'},occurred_at:at},{id:id(601),school_id:school,actor_id:admin,action:'intelligence.execution.approved',entity_type:'school',entity_id:school,request_id:requestId,outcome:'succeeded',metadata:{version:1,policyVersion:1},occurred_at:finished});
 f.evidence.outbox.push({id:id(602),school_id:school,actor_id:admin,type:'intelligence.execution.approved',entity_type:'school',entity_id:school,version:1,metadata:{policyVersion:1},deduplication_key:`intelligence-execution-approved:${school}:1`,occurred_at:finished,state:'COMPLETED',attempt_count:1,max_attempts:5,available_at:finished,lease_token:null,lease_until:null,completed_at:finished,last_error_code:null});f.evidence.processed.push({event_id:id(602),school_id:school,source_type:null,source_id:null,processed_at:finished});
 return f;
}
test('policy stored id/version is distinct from its HTTP projection and has only its real execution event',async()=>{const api=await subject();assert.equal(api.validateHostedLearningLoopNativeEvidence(policyFixture()).status,'VERIFIED');for(const change of[(f:Fixture)=>f.originals.at(-1).http.receiptIdentity.policyVersion=2,(f:Fixture)=>f.evidence.policy.manifest_sha256='0'.repeat(64),(f:Fixture)=>f.evidence.outbox.at(-1).type='intelligence.policy.approved',(f:Fixture)=>f.evidence.policy.approval_source='SOURCE_AUTHORIZED_FIXTURE']){const f=policyFixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('policy execution audit and processed acknowledgement cannot be missing',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.audits=f.evidence.audits.filter((row:Fixture)=>row.action!=='intelligence.execution.approved'),(f:Fixture)=>f.evidence.processed=f.evidence.processed.filter((row:Fixture)=>row.event_id!==id(602))]){const f=policyFixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('owner event metadata chronology and foreign extra native evidence refuse',async()=>{const api=await subject();for(const change of[(f:Fixture)=>f.evidence.outbox[0].metadata={schoolAuthored:false},(f:Fixture)=>f.evidence.outbox.find((row:Fixture)=>row.type==='result.released').metadata.evidenceId=id(999),(f:Fixture)=>f.evidence.outbox[0].completed_at='2026-10-06T07:00:00Z',(f:Fixture)=>f.evidence.processed.push({event_id:id(999),school_id:id(998),source_type:null,source_id:null,processed_at:finished})]){const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('native support and snapshot cannot replace failed analysis original receipt',async()=>{const api=await subject();const f=fixture(),row=f.evidence.commands.find((row:Fixture)=>row.command==='intelligence.analyze');row.response={id:f.evidence.chain.support.recommendation_id,failureCode:'INTELLIGENCE_TIMEOUT'};f.originals.find((row:Fixture)=>row.original.command.operation==='intelligence.analyze').http.receiptSha256=hash(row.response);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');});

test('academic reference outbox uses the actual academic owner metadata rather than learning metadata',async()=>{
 const api=await subject(),f=fixture(),source=f.originals.find((row:Fixture)=>row.original.command.operation==='assessment.preparation');
 const original=structuredClone(source);original.original.command.operation='assessment.reference';original.original.command.path='/v1/assessments/'+original.targetId+'/reference';
 original.original.command.key='original-academic-reference';original.original.intentRecordSha256=hash(['exact-academic-reference-intent']);
 const response={id:original.targetId};original.http.receiptSha256=hash(response);original.http.receiptIdentity={id:original.targetId};original.http.requestId='academic-reference-request';
 f.originals=[original];f.mode='ORIGINAL_RECONCILIATION';f.evidence.commands=[{school_id:school,actor_id:teacher,key:original.original.command.key,command:'assessment.reference',fingerprint:original.nativeFingerprint,state:'COMPLETED',response,created_at:at,completed_at:finished}];
 f.evidence.audits=[{id:id(990),school_id:school,actor_id:teacher,action:'assessment.reference',entity_type:'assessment',entity_id:original.targetId,request_id:original.http.requestId,outcome:'succeeded',metadata:{academic:true,model:null},occurred_at:at}];
 f.evidence.outbox=[{id:id(991),school_id:school,actor_id:teacher,type:'assessment.reference',entity_type:'assessment',entity_id:original.targetId,version:1,metadata:{},deduplication_key:createHash('sha256').update(teacher+':assessment.reference:'+original.original.command.key).digest('hex'),occurred_at:at,state:'PENDING',attempt_count:0,max_attempts:5,available_at:at,lease_token:null,lease_until:null,completed_at:null,last_error_code:null}];
 f.evidence.processed=[];f.evidence.chain=null;
 assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'ORIGINAL_RECONCILIATION_VERIFIED');
});

test('approved outcome bindings and snapshot ratios cannot point at a different native chain',async()=>{
 const api=await subject();
 for(const change of[(f:Fixture)=>{f.evidence.chain.support.intervention_id=id(998);f.originals.filter((row:Fixture)=>row.original.command.operation.startsWith('improvement.')&&row.original.command.operation!=='improvement.decision').forEach((row:Fixture)=>{row.original.command.path=row.original.command.path.replace(row.targetId,id(998));row.targetId=id(998);row.original.command.sourceIds=[id(998)];});},(f:Fixture)=>{f.evidence.chain.snapshot.impact.outcomes[0].minimumChange=2;},(f:Fixture)=>{f.evidence.chain.signal.source_event_ids=[];}]){
  const f=fixture();change(f);assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');
 }
});
test('fixed read engine rechecks admission and deadline after native evidence before success',async()=>{const api=await subject(),f=fixture(),input={identity:f.identity,scope:f.scope,mode:f.mode,originals:f.originals,deadlineMs:1000};let admission=0;const r=await api.verifyHostedLearningLoopNativeEvidence(input,{admitCurrentQa:async()=>{if(++admission>1)throw Error('revoked-private');},readEvidence:async()=>f.evidence,now:()=>Date.parse(observed),pause:async()=>{}});assert.equal(r.status,'REQUIRES_REVIEW');assert.equal(admission,2);let clock=Date.parse(observed);const timed=await api.verifyHostedLearningLoopNativeEvidence(input,{admitCurrentQa:async()=>{},readEvidence:async()=>{clock+=1000;return f.evidence;},now:()=>clock,pause:async()=>{}});assert.equal(timed.status,'REQUIRES_REVIEW');});
test('each original target follows the recorded source lineage rather than a different current object',async()=>{const api=await subject();for(const op of ['unit.create','lesson.create','activity.create','activity.complete','submission.create','improvement.decision','improvement.complete','improvement.reassessment','portfolio.review']as const){const f=fixture(),original=f.originals.find((row:Fixture)=>row.original.command.operation===op),old=original.targetId;original.targetId=id(999);original.original.command.path=original.original.command.path.replace(old,id(999));original.original.command.sourceIds=[id(999)];assert.equal(api.validateHostedLearningLoopNativeEvidence(f).status,'REQUIRES_REVIEW');}});
test('read port nonfinite clocks and final admission refusal fail closed',async()=>{const api=await subject(),f=fixture(),input={identity:f.identity,scope:f.scope,mode:f.mode,originals:f.originals,deadlineMs:1000};let clock=Date.parse(observed),admitted=0;const result=await api.verifyHostedLearningLoopNativeEvidence(input,{admitCurrentQa:async()=>{if(++admitted===2)throw Error('Original absolute approval expiry');},readEvidence:async()=>f.evidence,now:()=>clock,pause:async()=>{}});assert.equal(result.status,'REQUIRES_REVIEW');const nonfinite=await api.verifyHostedLearningLoopNativeEvidence(input,{admitCurrentQa:async()=>{},readEvidence:async()=>{clock=Number.NaN;return f.evidence;},now:()=>clock,pause:async()=>{}});assert.equal(nonfinite.status,'REQUIRES_REVIEW');});
