import assert from 'node:assert/strict';
import test from 'node:test';
import { createHash } from 'node:crypto';
import { mkdtemp,mkdir,writeFile,readFile,rm } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { join,resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { registerHooks } from 'node:module';
import { transformSync } from 'esbuild';
import { runInNewContext } from 'node:vm';

const project='prj_QtcVui11hMayZcqBF3KAxZcLaocs',team='team_Gvw1Dz7IlxIG5evqwlsNkZHb',sha='a'.repeat(40),ref='abcdefghijklmnopqrst',apiOrigin='https://cuevo-api.vercel.app',deployment='dpl_Fixture',url='https://cuevo-api-generated.vercel.app',web='https://cuevo-beta.vercel.app';
const hash=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v,Object.keys(v as object).sort())).digest('hex');
const canonicalHash=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
const canonical=(v:unknown):string=>JSON.stringify(v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,x&&typeof x==='object'?JSON.parse(canonical(x)):x])):Array.isArray(v)?v.map(x=>x&&typeof x==='object'?JSON.parse(canonical(x)):x):v);
let mode='normal',admissions=0,preparations=0,disposals=0,originHandles=new WeakSet<object>();
const rolloutNative={assert:(_lease:unknown,_expected:unknown)=>{throw Error('Native lease is absent');}};
Object.assign(globalThis,{apiOriginRolloutNative:rolloutNative,apiOriginFixture:{activationFailed:()=>mode==='activation-failed',initializationFailed:()=>mode==='initialization-failed',confirm:async()=>({status:mode==='native-unconfirmed'?'REQUIRES_REVIEW':'ORIGINAL_ACTIVATION_CONFIRMED',basis:'EXACT_CONFIRMED_READBACK',canonicalReceipt:'{}',lockReleased:true,sessionClosed:true}),prepared:(p:unknown)=>{const value=p as {expiresAt?:string};if(value.expiresAt&&Date.parse(value.expiresAt)<=Date.now())throw Error("Original approval expired");return p;},admit:async()=>{admissions++;if(mode==='admission')throw Error('private-token-canary');},runtime:()=>({api:{SUPABASE_PUBLISHABLE_KEY:'sb_publishable_fixture_key'},runtimeSha256:hash('runtime')})}});
Object.assign((globalThis as unknown as{apiOriginFixture:Record<string,unknown>}).apiOriginFixture,{prepare:async()=>{preparations++;const handle=Object.freeze({});originHandles.add(handle);return handle;},read:async(handle:object)=>{assert.ok(originHandles.has(handle));await(globalThis as unknown as{apiOriginFixture:{admit:()=>Promise<void>}}).apiOriginFixture.admit();},dispose:(handle:object)=>{assert.ok(originHandles.has(handle));originHandles.delete(handle);disposals++;}});
registerHooks({resolve(specifier,context,next){if(['./backend-release-contracts','./backend-release-admission','./backend-provider-deploy','../database/hosted-runtime-rollout-session'].includes(specifier))return{shortCircuit:true,url:new URL(specifier+'.ts',context.parentURL).href};return next(specifier,context);},load(url,context,next){const name=url.split('/').at(-1);if(name==='hosted-runtime-rollout-session.ts')return{shortCircuit:true,format:'module',source:'export const assertNativeRuntimeRolloutLease=(...args)=>globalThis.apiOriginRolloutNative.assert(...args);'};if(name==='backend-runtime-resume.ts')return{shortCircuit:true,format:'module',source:'export const revalidateActiveRuntime=async()=>null;export const revalidateCurrentRuntime=async()=>({status:"CURRENT_RUNTIME_REVALIDATED",nativeExecutionVerified:true,privateTransportVerified:true,admissionPaused:false,lockReleased:true,sessionClosed:true,current:{current:{apiDeploymentId:"dpl_Fixture",edgeId:"edge",edgeVersion:1,runtimeSha256:(globalThis.apiOriginFixture.runtime()).runtimeSha256}}});'};if(name==='backend-hosted-activation-confirmation.ts')return{shortCircuit:true,format:'module',source:'export const confirmHostedWorkerActivation=globalThis.apiOriginFixture.confirm;'};if(name==='backend-release-contracts.ts')return{shortCircuit:true,format:'module',source:'export const validatePreparedBackendReleaseIntent=globalThis.apiOriginFixture.prepared;export const readBackendRuntimeFingerprints=value=>value;export const runtimeRolloutBindingSchema={parse:value=>value};'};if(name==='backend-release-admission.ts')return{shortCircuit:true,format:'module',source:'export const readBackendReleaseAdmission=globalThis.apiOriginFixture.admit;export const prepareNativeBackendReleaseAdmission=globalThis.apiOriginFixture.prepare;export const readNativeBackendReleaseAdmission=globalThis.apiOriginFixture.read;export const disposeNativeBackendReleaseAdmission=globalThis.apiOriginFixture.dispose;export const readBackendActivationExecutionAdmission=async()=>{if(globalThis.apiOriginFixture.activationFailed())throw Error("Official activation step failed");return {activationStepVerified:true};};export const readBackendRuntimeInitializationAdmission=async()=>{if(globalThis.apiOriginFixture.initializationFailed())throw Error("Original initializer publication failed");return {initializationStepVerified:true};};'};if(name==='backend-provider-deploy.ts')return{shortCircuit:true,format:'module',source:'export const prepareHostedRuntimeRecipients=globalThis.apiOriginFixture.runtime;export const prepareHostedOperatingRecipients=globalThis.apiOriginFixture.runtime;'};if(name==='backend-api-origin.ts')return{shortCircuit:true,format:'module',source:transformSync(readFileSync(new URL(url),'utf8'),{loader:'ts',format:'esm'}).code};return next(url,context);}});
async function subject(){let value:Record<string,unknown>={};try{value=await import(pathToFileURL(resolve(import.meta.dirname,'backend-api-origin.ts')).href);}catch(error){if((error as NodeJS.ErrnoException).code!=='ERR_MODULE_NOT_FOUND')throw error;}assert.equal(typeof value.bindBackendApiOrigin,'function');return value as typeof import('./backend-api-origin');}
async function fixture(selected:string,run:(input:Record<string,unknown>,calls:string[],root:string)=>Promise<void>){const root=await mkdtemp(join(tmpdir(),'cuevo-api-origin-')),previous=globalThis.fetch,calls:string[]=[];mode=selected;admissions=0;preparations=0;disposals=0;originHandles=new WeakSet();let bound=selected==='same'||selected.startsWith('retained-'), override=bound;
 try{await mkdir(join(root,'.local/hosted-release'),{recursive:true});await writeFile(join(root,'.local/hosted-release/database-ca.pem'),'-----BEGIN CERTIFICATE-----\nfixture\n-----END CERTIFICATE-----');await mkdir(join(root,'supabase/seed'),{recursive:true});await writeFile(join(root,'supabase/seed/identities.json'),readFileSync(resolve(import.meta.dirname,'../../supabase/seed/identities.json')));
 const identity={sourceSha:sha,projectRef:ref,runId:'51',runAttempt:1,packageSha256:hash('package'),runtimeSha256:hash('runtime'),apiDeploymentId:deployment};
 const activation={...identity,purpose:'CUEVO_HOSTED_WORKER_ACTIVATION',status:'ACTIVATED_SIGNED_SOURCE_VERIFIED',observedAt:new Date().toISOString(),edgeVersion:1,sourceProcessed:true,scheduledRecoveryVerified:true,duplicateWakeDenied:true,sessionsClosed:true};
 const fault={...identity,purpose:'CUEVO_HOSTED_WORKER_FAULT_RECOVERY',status:'FAULT_RECOVERY_VERIFIED',observedAt:new Date().toISOString(),edgeVersion:1,expiredLeaseRecoveryVerified:true,eventRetryVerified:true,dispatchBackoffVerified:true,ownedControlVerified:true,sessionsClosed:true,lockReleased:true,cleanupStatus:'RELEASED'};
 const restore={...identity,purpose:'CUEVO_HOSTED_DATABASE_RESTORE',status:'VERIFIED',observedAt:new Date().toISOString(),backupVerified:true,restoredDatabaseVerified:true,restoredRestrictedGrantsVerified:true,restoredRlsVerified:true,restoredAuthVerified:true,restoredPrivateStorageVerified:true,recoveryVerified:true,cleanupConfirmed:true};
 const files={'provider-result.json':{status:'DEPLOYED_INACTIVE',api:{deploymentId:deployment,url,artifactSha256:hash('api')},edge:{id:'edge',version:1}},'prerequisites-result.json':{status:'PREREQUISITES_OBSERVED',apiReady:true,roleSessions:5,crossSchoolDenied:true},'private-access-result.json':{status:'PRIVATE_PROBES_CONFIRMED',privateStorage:true,privateRealtime:true,restrictedDatabaseGrants:true,sessionsClosed:true},'worker-activation-result.json':activation,'worker-activation-cleanup.json':{...identity,purpose:'CUEVO_HOSTED_WORKER_ACTIVATION_CLEANUP',status:activation.status,resultSha256:canonicalHash(activation),sessionsClosed:true,lockReleased:true},'worker-fault-recovery-result.json':fault,'worker-fault-recovery-cleanup.json':{...identity,purpose:'CUEVO_HOSTED_WORKER_FAULT_RECOVERY_CLEANUP',status:fault.status,resultSha256:canonicalHash(fault),sessionsClosed:true,lockReleased:true,cleanupStatus:'RELEASED'},'database-restore-result.json':restore,'database-restore-cleanup.json':{...identity,purpose:'CUEVO_HOSTED_DATABASE_RESTORE_CLEANUP',status:restore.status,resultSha256:canonicalHash(restore),cleanupConfirmed:true,sessionsClosed:true,lockReleased:true}};
 for(const[name,body]of Object.entries(files))await writeFile(join(root,'.local/hosted-release',name),JSON.stringify(body));if(mode==='gate')await writeFile(join(root,'.local/hosted-release/worker-fault-recovery-result.json'),JSON.stringify({...fault,eventRetryVerified:false}));
 const input={repoRoot:root,activeOperator:{providerToken:'protected-provider-token',operatorDatabaseUrl:'postgresql://postgres@db.fixture:5432/postgres?sslmode=verify-full',operatorPassword:'protected-operator'},expected:{repository:'attaulhaq0/Cuevo',releaseSha:sha,treeSha:'d'.repeat(40),executionScope:'complete-backend',releaseRunId:'51',runAttempt:1,targets:{api:{projectId:project,teamId:team,origin:apiOrigin,target:'preview'},web:{origin:web},supabase:{projectRef:ref,authOrigin:`https://${ref}.supabase.co`}},fingerprints:{apiArtifactSha256:hash('api')}},preparedApproval:{sha256:hash('package')},runtimeConfig:{},githubToken:'private-gh-canary',vercelToken:'private-token-canary',syntheticPassword:'private-pilot-password'};
 globalThis.fetch=async(raw,options)=>{const parsed=new URL(String(raw));calls.push((options?.method??'GET')+':'+parsed.pathname);assert.equal(options?.redirect,'error');
  if(parsed.origin==='https://api.vercel.com'){
   if(parsed.pathname===`/v9/projects/${project}`)return Response.json({id:project,accountId:team,ssoProtection:{deploymentType:'all_except_custom_domains'}});
   if(parsed.pathname===`/v9/projects/${project}/domains`)return Response.json({domains:[{name:'cuevo-api.vercel.app',projectId:project,verified:true}],pagination:{next:null}});
   if(parsed.pathname===`/v13/deployments/${deployment}`)return Response.json({id:deployment,projectId:mode==='retained-wrong-provider'?'prj_Foreign':project,ownerId:team,url:new URL(url).hostname,readyState:'READY',target:'preview',meta:{cuevoCommitSha:mode.startsWith('retained-')?'b'.repeat(40):sha,cuevoArtifactSha256:mode==='retained-wrong-artifact'?hash('foreign-api'):hash("api")}});
   if(parsed.pathname==='/v4/aliases/cuevo-api.vercel.app'){if(mode==='foreign')return Response.json({uid:'alias',alias:'cuevo-api.vercel.app',projectId:'prj_Foreign',deploymentId:'dpl_Old',redirect:null});if(mode==='old')return Response.json({uid:'alias',alias:'cuevo-api.vercel.app',projectId:project,deploymentId:'dpl_Old',redirect:null});return bound?Response.json({uid:'alias',alias:'cuevo-api.vercel.app',projectId:project,deploymentId:deployment,redirect:null,protectionBypass:override?{override:{scope:'alias-protection-override',createdAt:Date.now(),createdBy:'operator'}}:{}}):Response.json({error:{code:'alias_not_found'}},{status:404});}
   if(parsed.pathname===`/v2/deployments/${deployment}/aliases`){assert.deepEqual(JSON.parse(String(options?.body)),{alias:'cuevo-api.vercel.app',redirect:null});bound=true;if(mode==='unknown')throw Error('private-token-canary');return Response.json({uid:'alias',alias:'cuevo-api.vercel.app',created:'2026-10-06T00:00:00Z'});}
  }
  if(parsed.pathname==='/aliases/alias/protection-bypass'&&options?.method==='PATCH'){assert.deepEqual(JSON.parse(String(options.body)),{override:{action:'create',scope:'alias-protection-override'}});const original=JSON.parse(await readFile(join(root,'.local/hosted-release/api-origin-protection-intent.json'),'utf8'));assert.equal(original.aliasId,'alias');assert.equal(original.deploymentId,deployment);override=true;if(mode==='override-unknown')throw Error('private override acknowledgement');return Response.json({});}
  if(parsed.origin===apiOrigin&&!override)return Response.json({code:'VERCEL_PROTECTION_REQUIRED'},{status:401});
  if(parsed.origin===apiOrigin)assert.equal(new Headers(options?.headers).has('x-vercel-protection-bypass'),false);
  if(parsed.pathname==='/health/ready')return Response.json({status:'ready',database:true,authentication:true});
  if(parsed.pathname==='/auth/v1/token')return Response.json({access_token:'private-current-session',user:{id:'20000000-0000-4000-8000-000000000001',email:'synthetic-001@cuevo.test'}});
  if(parsed.pathname==='/auth/v1/logout')return new Response(null,{status:204});
  if(parsed.pathname==='/v1/me'&&options?.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':mode==='cors'?'https://foreign.example':web,'Access-Control-Allow-Methods':'GET,POST','Access-Control-Allow-Headers':'authorization,x-school-id'}});
  if(parsed.pathname==='/v1/me')return Response.json({userId:'20000000-0000-4000-8000-000000000001',schoolId:'10000000-0000-4000-8000-000000000001',role:'admin'},{headers:{'Access-Control-Allow-Origin':mode==='cors'?'https://foreign.example':web}});
  throw Error('Unexpected fixed API origin URL');
 };
 await run(input,calls,root);
 }finally{globalThis.fetch=previous;await rm(root,{recursive:true,force:true});}}
test('bound reserved staging API alias is assigned once only after actual backend receipts and verified after assignment',async()=>{const api=await subject();await fixture('normal',async(input,calls,root)=>{const result=await api.bindBackendApiOrigin(input);assert.equal(result.status,'API_ORIGIN_BOUND');assert.equal(result.aliasOperation,'CONFIRMED');assert.equal(result.origin,apiOrigin);assert.equal(result.hostedAcceptance,false);assert.equal(result.sessionsClosed,true);assert(admissions>=3);assert.equal(preparations,1);assert.equal(disposals,1);assert.equal(calls.filter(v=>v.startsWith('POST:/v2/')).length,1);assert((await readFile(join(root,'.local/hosted-release/api-origin-intent.json'),'utf8')).includes(deployment));assert(!JSON.stringify(result).includes('private-token-canary'));});});
test('same alias is read-only no-op while foreign old or missing backend authority refuses every alias mutation',async()=>{const api=await subject();await fixture('same',async(input,calls)=>{const r=await api.bindBackendApiOrigin(input);assert.equal(r.status,'API_ORIGIN_BOUND');assert.equal(r.aliasOperation,'NOOP');assert(!calls.some(v=>v.startsWith('POST:/v2/')));});for(const mode of ['foreign','old','gate','admission'])await fixture(mode,async(input,calls)=>{assert.equal((await api.bindBackendApiOrigin(input)).status,'REQUIRES_REVIEW');assert(!calls.some(v=>v.startsWith('POST:/v2/')));});});
test('explicit operating API origin can prepare staging without full restore evidence while default customer gate stays strict',async()=>{const api=await subject();await fixture('normal',async(input,calls,root)=>{for(const name of['worker-fault-recovery-result.json','worker-fault-recovery-cleanup.json','database-restore-result.json','database-restore-cleanup.json'])await rm(join(root,'.local/hosted-release',name));const result=await api.bindBackendApiOrigin({...input,lane:'OPERATING_SYNTHETIC_STAGING'});assert.equal(result.status,'API_ORIGIN_BOUND');assert.equal(result.hostedAcceptance,false);assert.equal(result.healthVerified,true);assert.equal(result.corsVerified,true);assert.equal(calls.filter(v=>v.startsWith('POST:/v2/')).length,1);});await fixture('normal',async(input,calls,root)=>{await rm(join(root,'.local/hosted-release/database-restore-result.json'));assert.equal((await api.bindBackendApiOrigin(input)).status,'REQUIRES_REVIEW');assert.equal(calls.some(v=>v.startsWith('POST:')),false);});});
test('matching operating flags cannot authorize API alias before original initialization publisher succeeds',async()=>{const api=await subject();await fixture('initialization-failed',async(input,calls)=>{assert.equal((await api.bindBackendApiOrigin({...input,lane:'OPERATING_SYNTHETIC_STAGING'})).status,'REQUIRES_REVIEW');assert.equal(calls.some(value=>value.startsWith('POST:')),false);});});
test('operating origin observation verifies exact current alias and customer CORS without another provider mutation',async()=>{const api=await subject();assert.equal(typeof api.observeBackendApiOrigin,'function');for(const selected of['same','foreign','old','cors'])await fixture(selected,async(input,calls)=>{const result=await api.observeBackendApiOrigin({...input,apiDeployment:{id:deployment,url,artifactSha256:hash('api')}});assert.equal(result.status,selected==='same'?'API_ORIGIN_OBSERVED':'REQUIRES_REVIEW',selected);assert.equal(result.sessionsClosed,true);assert.equal(result.hostedAcceptance,false);assert.equal(calls.some(v=>v.startsWith('POST:/v2/')||v.startsWith('PATCH:')),false);if(selected==='same'){assert.equal(result.healthVerified,true);assert.equal(result.corsVerified,true);assert.equal(result.currentActorVerified,true);assert.ok(result.canonicalReceipt);}});});

test('API origin borrows one opaque owner without serializing or disposing its outer operation handle',async()=>{const api=await subject();for(const observe of [false,true])await fixture(observe?'same':'normal',async(input,calls)=>{const handle=Object.freeze({}) as Parameters<typeof api.bindBackendApiOrigin>[1];originHandles.add(handle!);const result=observe?await api.observeBackendApiOrigin({...input,apiDeployment:{id:deployment,url,artifactSha256:hash('api')}},handle):await api.bindBackendApiOrigin(input,handle);assert.equal(result.status,observe?'API_ORIGIN_OBSERVED':'API_ORIGIN_BOUND');assert.equal(preparations,0);assert.equal(disposals,0);assert.ok(originHandles.has(handle!));assert.ok(admissions>=2);assert.ok(calls.some(value=>value==='POST:/auth/v1/logout'));});for(const forged of [Object.freeze({}),null])await fixture('normal',async(input,calls)=>{const result=await api.bindBackendApiOrigin(input,forged as Parameters<typeof api.bindBackendApiOrigin>[1]);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(preparations,0);assert.equal(disposals,0);assert.equal(calls.some(value=>value.startsWith('POST:/v2/')),false);});});

function retainedObservationInput(input:Record<string,unknown>):Record<string,unknown>{const expected=input.expected as Record<string,unknown>;input.expected={...expected,currentRuntime:{current:{sourceSha:'b'.repeat(40),treeSha:'c'.repeat(40),executorSourceSha:sha,executorTreeSha:expected.treeSha,apiDeploymentId:deployment,apiUrl:url,apiArtifactSha256:hash('api')}}};return{...input,apiDeployment:{id:deployment,url,artifactSha256:hash('api')}};}
test('operating current rollback observation binds retained component and current executor while performing real actor CORS probes',async()=>{const api=await subject();await fixture('retained-component',async(input,calls)=>{const result=await api.observeBackendApiOrigin(retainedObservationInput(input));assert.equal(result.status,'API_ORIGIN_OBSERVED');assert.equal(result.sourceSha,sha);assert.equal(result.currentActorVerified,true);assert.equal(result.corsVerified,true);assert.equal(result.sessionsClosed,true);assert.equal(calls.filter(row=>row==='/auth/v1/logout'||row==='POST:/auth/v1/logout').length,1);assert.equal(calls.some(row=>row.startsWith('PATCH:')||row.startsWith('POST:/v2/')),false);});});
test('operating current rollback observation denies wrong native source executor artifact deployment and provider',async()=>{const api=await subject();for(const selected of['retained-component','retained-wrong-provider','retained-wrong-artifact'])for(const change of selected==='retained-component'?['source','executor','artifact','deployment']:['none'])await fixture(selected,async(input,calls)=>{const value=retainedObservationInput(input),current=(value.expected as {currentRuntime:{current:Record<string,unknown>}}).currentRuntime.current;if(change==='source')current.sourceSha='f'.repeat(40);if(change==='executor')current.executorTreeSha='f'.repeat(40);if(change==='artifact')current.apiArtifactSha256=hash('foreign');if(change==='deployment')current.apiDeploymentId='dpl_Foreign';const result=await api.observeBackendApiOrigin(value);assert.equal(result.status,'REQUIRES_REVIEW',selected+'/'+change);assert.equal(calls.some(row=>row.startsWith('POST:')),false);});});
test('matching local activation success files cannot authorize API alias when official activation publisher failed',async()=>{const api=await subject();await fixture('activation-failed',async(input,calls)=>{const result=await api.bindBackendApiOrigin(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.aliasOperation,'NONE');assert.equal(calls.some(row=>row.startsWith('POST:')),false);});});
test('successful official activation provenance cannot overcome missing current native confirmation or operator scope',async()=>{const api=await subject();for(const selected of['native-unconfirmed','missing-operator'])await fixture(selected,async(input,calls)=>{if(selected==='missing-operator')delete input.activeOperator;const result=await api.bindBackendApiOrigin(input);assert.equal(result.status,'REQUIRES_REVIEW');assert.equal(result.aliasOperation,'NONE');assert.equal(calls.some(row=>row.startsWith('POST:')),false);});});
test('uncertain alias acknowledgement retains original intent and never performs a duplicate write',async()=>{const api=await subject();await fixture('unknown',async(input,calls)=>{const r=await api.bindBackendApiOrigin(input);assert.equal(r.status,'REQUIRES_REVIEW');assert.equal(r.aliasOperation,'UNKNOWN');assert.equal((await api.bindBackendApiOrigin(input)).status,'REQUIRES_REVIEW');assert.equal(calls.filter(v=>v.startsWith('POST:/v2/')).length,1);});await fixture('cors',async input=>{const r=await api.bindBackendApiOrigin(input);assert.equal(r.status,'REQUIRES_REVIEW');assert.equal(r.sessionsClosed,true);});});
test('wrong cleanup source or changed reserved target cannot reach assignment even when receipt flags are true',async()=>{const api=await subject();await fixture('normal',async(input,calls,root)=>{const path=join(root,'.local/hosted-release/worker-fault-recovery-cleanup.json'),value=JSON.parse(await readFile(path,'utf8'));value.runId='99';await writeFile(path,JSON.stringify(value));assert.equal((await api.bindBackendApiOrigin(input)).status,'REQUIRES_REVIEW');assert(!calls.some(v=>v.startsWith('POST:/v2/')));});await fixture('normal',async(input,calls)=>{(input.expected as{targets:{api:{origin:string}}}).targets.api.origin='https://other.vercel.app';assert.equal((await api.bindBackendApiOrigin(input)).status,'REQUIRES_REVIEW');assert.equal(calls.length,0);});});

test('uncertain alias-specific protection override preserves one original mutation and never retries',async()=>{const api=await subject();await fixture('override-unknown',async(input,calls)=>{const first=await api.bindBackendApiOrigin(input);assert.equal(first.status,'REQUIRES_REVIEW');assert.equal((await api.bindBackendApiOrigin(input)).status,'REQUIRES_REVIEW');assert.equal(calls.filter(v=>v==='PATCH:/aliases/alias/protection-bypass').length,1);});});

test('runtime alias moves only from the approved previous deployment to native desired identity and preserves uncertain intent',async()=>{
 const api=await subject();assert.equal(typeof api.transitionRuntimeApiOrigin,'function');
 for(const selected of ['valid','same','foreign','moving','native','phase','expired','unknown']){
  const root=await mkdtemp(join(tmpdir(),'cuevo-rollout-alias-')),previousFetch=globalThis.fetch,oldAssert=rolloutNative.assert,lease=Object.freeze({}),calls:string[]=[];let bound=selected==='same',reads=0;
  const previous={generation:'1',sourceSha:'b'.repeat(40),treeSha:'c'.repeat(40),runtimeSha256:hash('old-runtime'),apiDeploymentId:'dpl_Previous',apiUrl:'https://cuevo-api-previous.vercel.app',edgeId:'edge-old',edgeVersion:1,apiArtifactSha256:hash('old-api'),edgeArtifactSha256:hash('old-edge'),denoLockSha256:hash('old-lock'),activationReceiptSha256:hash('old-activation'),stateSha256:hash('old-state')};
  const desired={generation:'2',sourceSha:sha,treeSha:'d'.repeat(40),apiArtifactSha256:hash('api'),edgeArtifactSha256:hash('edge'),denoLockSha256:hash('lock'),compatibilitySha256:hash('compatibility')};
  const expected={executionScope:'runtime-rollout',releaseSha:sha,treeSha:desired.treeSha,releaseRunId:'51',runAttempt:1,targets:{api:{projectId:project,teamId:team,origin:apiOrigin,target:'preview'},supabase:{projectRef:ref}},fingerprints:{apiArtifactSha256:desired.apiArtifactSha256,edgeArtifactSha256:desired.edgeArtifactSha256,denoLockSha256:desired.denoLockSha256},runtimeRollout:{version:1,purpose:'CUEVO_ACTIVE_RUNTIME_ROLLOUT',previous,desired,operationSha256:hash('operation')}};
  const prepared={sha256:hash('package'),expiresAt:new Date(Date.now()+60000).toISOString()},identity={...desired,runId:'51',runAttempt:1,packageSha256:prepared.sha256,runtimeSha256:hash('runtime'),apiDeploymentId:deployment,apiUrl:url,edgeId:'edge-current',edgeVersion:2};
  const state={version:2,projectRef:ref,current:{identity:previous},pending:{phase:selected==='phase'?'PROVIDERS_CONFIRMED':'PRIVATE_VERIFIED',operationSha256:expected.runtimeRollout.operationSha256,identity}};
  const nativeSession={refresh:async()=>{calls.push('native-refresh');if(selected==='expired'&&reads>0)prepared.expiresAt=new Date(Date.now()-1).toISOString();},requireDrained:async()=>{calls.push('drained');},readState:async()=>state};
  rolloutNative.assert=((value:unknown,actual:unknown)=>{if(selected==='native'||value!==lease||canonical(actual)!==canonical(expected))throw Error('No native lease');return nativeSession;}) as typeof rolloutNative.assert;
  try{
   await mkdir(join(root,'.local/hosted-release'),{recursive:true});
   globalThis.fetch=async(raw,options)=>{const parsed=new URL(String(raw));calls.push((options?.method??'GET')+':'+parsed.pathname);assert.equal(options?.redirect,'error');
    if(parsed.pathname.startsWith('/v13/deployments/')){const id=parsed.pathname.split('/').at(-1),isPrevious=id===previous.apiDeploymentId;return Response.json({id,projectId:project,ownerId:team,url:new URL(isPrevious?previous.apiUrl:url).hostname,readyState:'READY',target:'preview',meta:{cuevoCommitSha:isPrevious?previous.sourceSha:sha,cuevoArtifactSha256:isPrevious?previous.apiArtifactSha256:desired.apiArtifactSha256}});}
    if(parsed.pathname==='/v4/aliases/cuevo-api.vercel.app'){reads++;return Response.json({uid:'alias-original',alias:'cuevo-api.vercel.app',projectId:selected==='foreign'?'prj_Foreign':project,deploymentId:bound?deployment:selected==='moving'&&reads>1?'dpl_Unapproved':previous.apiDeploymentId,redirect:null});}
    if(options?.method==='POST'){bound=true;if(selected==='unknown')throw Error('Lost provider acknowledgement');return Response.json({uid:'alias-original',alias:'cuevo-api.vercel.app',oldDeploymentId:previous.apiDeploymentId});}throw Error('Unexpected alias request');};
   const input={repoRoot:root,expected,preparedApproval:prepared,githubToken:'protected-gh',vercelToken:'protected-vercel-token',lease,desired:{apiDeploymentId:deployment,apiUrl:url,apiArtifactSha256:desired.apiArtifactSha256}},result=await api.transitionRuntimeApiOrigin(input as unknown as Parameters<typeof api.transitionRuntimeApiOrigin>[0]);
   if(selected==='valid'||selected==='same'){assert.equal(result.status,'ALIAS_BOUND',selected);assert.equal(result.operation,selected==='same'?'NOOP':'CONFIRMED');assert.equal(result.generation,'2');assert.equal(result.previousDeploymentId,previous.apiDeploymentId);assert.equal(result.desiredDeploymentId,deployment);assert.ok(result.receiptSha256);assert.equal(result.hostedAcceptance,false);}
   else{assert.equal(result.status,'REQUIRES_REVIEW',selected);assert.equal(calls.filter(v=>v.startsWith('POST:')).length,selected==='unknown'?1:0,selected);}
   if(selected==='unknown'){assert.equal(result.operation,'UNKNOWN');const before=await readFile(join(root,'.local/hosted-release/runtime-api-origin-intent.json'));await api.transitionRuntimeApiOrigin(input as unknown as Parameters<typeof api.transitionRuntimeApiOrigin>[0]);assert.equal(calls.filter(v=>v.startsWith('POST:')).length,1);assert.ok((await readFile(join(root,'.local/hosted-release/runtime-api-origin-intent.json'))).equals(before));const recoveryExpected={...expected,releaseRunId:'52',runtimeRollout:{...expected.runtimeRollout,version:2,action:'RECOVER_ORIGINAL',executor:{sourceSha:sha,treeSha:expected.treeSha,runId:'52',runAttempt:1},recoveryOriginal:{runId:identity.runId,runAttempt:identity.runAttempt,packageSha256:identity.packageSha256,pendingStateSha256:'a'.repeat(64),compatibilitySha256:desired.compatibilitySha256,archiveSha256:'b'.repeat(64)},rollbackArtifacts:null}};rolloutNative.assert=((value:unknown)=>{if(value!==lease)throw Error('No lease');return nativeSession;}) as unknown as typeof rolloutNative.assert;const recovered=await api.transitionRuntimeApiOrigin({...input,expected:recoveryExpected} as unknown as Parameters<typeof api.transitionRuntimeApiOrigin>[0]);assert.equal(recovered.status,'ALIAS_BOUND');assert.equal(recovered.operation,'NOOP');assert.equal(calls.filter(v=>v.startsWith('POST:')).length,1);assert.ok((await readFile(join(root,'.local/hosted-release/runtime-api-origin-intent.json'))).equals(before));}
  }finally{globalThis.fetch=previousFetch;rolloutNative.assert=oldAssert;await rm(root,{recursive:true,force:true});}
 }
});

test('API alias assignment consumes the original expiry after provider reads and never issues an expired POST',async()=>{
 const source=readFileSync(resolve(import.meta.dirname,'backend-api-origin.ts'),'utf8');
 const start=source.indexOf("  if(prior){r.aliasOperation='NOOP'"),end=source.indexOf('  const overridePresent=',start);
 assert(start>=0&&end>start);const block=source.slice(start,end);
 for(const expiryPhase of ['valid','deployment','alias','deadline']){
  const expired=expiryPhase!=='valid';
  const calls:string[]=[],r:{aliasOperation:string;apiDeploymentId:string;aliasId?:string}={aliasOperation:'NONE',apiDeploymentId:deployment};
  let now=1000;const prepared=Object.freeze({expiresAt:1500});
  const work=runInNewContext(`(async()=>{${block}})()`,{prior:null,r,root:'fixture-root',expected:{now:1000},prepared,input:{githubToken:'private-fixture'},scope:'?teamId=fixture',credentials:{},
   Date:{now:()=>now},fail:()=>Error('original expiry'),
   admission:async()=>{calls.push('admission');assert(now<prepared.expiresAt);},
   exact:async()=>{calls.push('deployment-read');now=expiryPhase==='deployment'?1600:1200;},
   alias:async()=>{calls.push('alias-read');if(expiryPhase==='alias')now=1600;if(expiryPhase==='deadline')now=1500;return r.aliasOperation==='NONE'?null:{uid:'fixture-alias'};},
   validatePreparedBackendReleaseIntent:(value:unknown,context:{now:number})=>{calls.push('original-expiry');assert.equal(value,prepared);assert(context.now<prepared.expiresAt);return value;},
   http:async(_url:string,method:string)=>{calls.push(method);return{status:200,value:{uid:'fixture-alias',alias:'cuevo-api.vercel.app'}};},z:{object:()=>({parse:()=>undefined}),string:()=>({min:()=>({})}),literal:()=>({}),undefined:()=>({optional:()=>({})})},
  });
  if(expired){await assert.rejects(work);assert(!calls.includes('POST'));assert.equal(r.aliasOperation,'NONE');}
  else{await work;assert.equal(r.aliasOperation,'CONFIRMED');assert.equal(calls.filter(value=>value==='POST').length,1);assert(calls.indexOf('original-expiry')>calls.indexOf('alias-read'));assert(calls.indexOf('original-expiry')<calls.indexOf('POST'));}
 }
});
