import { createHash, randomUUID } from 'node:crypto';
import { readFile,open,mkdir,lstat,realpath } from 'node:fs/promises';
import { join,isAbsolute,resolve } from 'node:path';
import { checkServerIdentity, TLSSocket } from 'node:tls';
import { Client } from 'pg';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';
import { canonicalReleaseExecutionJson } from './release-review';
import { readBackendReleaseAdmission } from './backend-release-admission';
import { validatePreparedBackendReleaseIntent, type BackendReleaseExpected } from './backend-release-contracts';
import { prepareHostedRuntimeRecipients } from './backend-provider-deploy';

const failure = () => Error('Hosted private access verification requires review; contents withheld.'), hash = (bytes: Uint8Array | string) => createHash('sha256').update(bytes).digest('hex');
const schema = z.object({ purpose: z.enum(['INITIAL', 'PRE_ACTIVATION']).default('INITIAL'), repoRoot: z.string(), expected: z.unknown(), preparedApproval: z.unknown(), githubToken: z.string().min(1), vercelToken: z.string().min(20), runtimeConfig: z.unknown(), apiDeployment: z.object({ url: z.string().url(), id: z.string().startsWith('dpl_') }).strict(), syntheticPassword: z.string().min(16).max(128), providerToken: z.string().min(20) }).strict();
export type HostedPrivateVerificationResult = { status: 'PRIVATE_PROBES_CONFIRMED' | 'REQUIRES_REVIEW'; freshProof: boolean; restrictedDatabaseGrants: boolean | null; privateStorage: boolean | null; privateRealtime: boolean | null; storageProbe: { assetId: string; objectPath: string; retired: boolean; removed: boolean } | null; realtimeProbe: { roomId: string; closed: boolean } | null; sessionsClosed: boolean; activationAllowed: false; hostedAcceptance: false };
const confirmedPrivateReceiptSchema=z.object({status:z.literal('PRIVATE_PROBES_CONFIRMED'),freshProof:z.boolean().optional(),restrictedDatabaseGrants:z.literal(true),privateStorage:z.literal(true),privateRealtime:z.literal(true),storageProbe:z.object({assetId:z.uuid(),objectPath:z.string(),retired:z.literal(true),removed:z.literal(true)}).strict(),realtimeProbe:z.object({roomId:z.uuid(),closed:z.literal(true)}).strict(),sessionsClosed:z.literal(true),activationAllowed:z.literal(false),hostedAcceptance:z.literal(false)}).strict();
async function http(url: string, method: 'GET' | 'POST' | 'DELETE', headers: Record<string, string>, body?: unknown) {
  const signal = AbortSignal.timeout(10000), response = await fetch(url, { method, headers: { ...headers, ...(body === undefined ? {} : { 'Content-Type': 'application/json' }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }), redirect: 'error', signal, credentials: 'omit', cache: 'no-store' });
  if (response.redirected || response.url && response.url !== url) throw failure();
  if (response.status === 204 && !response.body) return { status: response.status, bytes: Buffer.alloc(0), value: null as unknown };
  const declared = response.headers.get('content-length'); if (declared !== null && (!/^\d+$/.test(declared) || Number(declared) > 65536) || !response.body) throw failure();
  const reader = response.body.getReader(), chunks: Uint8Array[] = []; let size = 0;
  try { while (true) { const part = await new Promise<ReadableStreamReadResult<Uint8Array>>((done, reject) => { const abort = () => { signal.removeEventListener('abort', abort); reject(failure()); }; if (signal.aborted) return abort(); signal.addEventListener('abort', abort, { once: true }); void reader.read().then(v => { signal.removeEventListener('abort', abort); done(v); }, () => { signal.removeEventListener('abort', abort); reject(failure()); }); }); if (signal.aborted) throw failure(); if (part.done) break; size += part.value.byteLength; if (size > 65536) throw failure(); chunks.push(part.value); } const bytes = Buffer.concat(chunks); let value: unknown = null; try { value = JSON.parse(new TextDecoder('utf8', { fatal: true }).decode(bytes)); } catch { /* Private download bytes deliberately remain binary. */ } return { status: response.status, bytes, value }; } finally { void reader.cancel().catch(() => undefined); try { reader.releaseLock(); } catch { /* Pending cancelled read owns cleanup. */ } }
}
async function restricted(dsn: string, ca: string, role: 'cuevo_api' | 'cuevo_worker') {
  const url = new URL(dsn), client = new Client({ host: url.hostname, port: Number(url.port || 5432), database: 'postgres', user: decodeURIComponent(url.username), password: decodeURIComponent(url.password), ssl: { rejectUnauthorized: true, ca, minVersion: 'TLSv1.2' }, connectionTimeoutMillis: 5000, statement_timeout: 5000, query_timeout: 7000, application_name: 'cuevo-hosted-private-verification' });
  let lost = false, ending = false, failed = false;
  const disconnected = () => { if (!ending) lost = true; };
  client.on('error', disconnected); client.on('end', disconnected);
  const live = () => {
    const stream = (client as unknown as { connection: { stream: TLSSocket } }).connection.stream;
    if (lost || !stream.encrypted || !stream.authorized || checkServerIdentity(url.hostname, stream.getPeerCertificate())) throw failure();
  };
  try {
    await client.connect(); live();
    const who = (await client.query(`select current_user::text as role,session_user::text as "sessionRole",current_database()::text as database,(select not rolsuper and not rolbypassrls and not rolcreaterole and not rolcreatedb and not rolreplication and not rolinherit from pg_roles where rolname=current_user) as restricted`)).rows;
    live();
    if (who.length !== 1 || who[0].role !== role || who[0].sessionRole !== role || who[0].database !== 'postgres' || who[0].restricted !== true) throw failure();
    const checks = role === 'cuevo_api' ? ['select id from app.result_revisions limit 1', 'select id from internal.outbox_events limit 1', 'select internal.worker_transport_private()'] : ['select id from app.people limit 1', 'select internal.worker_transport_private()'];
    for (const sql of checks) { live(); let rejected = false; try { const result = await client.query(sql); if (role === 'cuevo_api' && sql.startsWith('select id from app.result_revisions') && result.rows.length === 0) rejected = true; } catch (error) { rejected = (error as { code?: string }).code === '42501'; } live(); if (!rejected) throw failure(); }
  } catch { failed = true; }
  finally { ending = true; try { await client.end(); } catch { failed = true; } }
  if (failed || lost) throw failure();
  return true;
}
async function privateJoin(authOrigin: string, publishable: string, token: string, topic: string) {
  const client = createClient(authOrigin, publishable, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }), channel = client.channel(topic, { config: { private: true } }).on('broadcast', { event: 'invalidate' }, () => undefined);
  try { await client.realtime.setAuth(token); return await new Promise<'SUBSCRIBED' | 'DENIED' | 'UNKNOWN'>(done => { const timeout = setTimeout(() => done('UNKNOWN'), 10000); channel.subscribe((status, error) => { if (status === 'SUBSCRIBED' || status === 'CHANNEL_ERROR' || status === 'TIMED_OUT' || status === 'CLOSED') { clearTimeout(timeout); const denied = status === 'CHANNEL_ERROR' && error?.message === 'You do not have permissions to read from this Channel topic: ' + topic; done(status === 'SUBSCRIBED' ? 'SUBSCRIBED' : denied ? 'DENIED' : 'UNKNOWN'); } }); }); }
  finally { await client.removeChannel(channel); client.realtime.disconnect(); }
}
/** Synthetic source-backed asset/room probes use ordinary protected commands;
 * current authorization remains the application and database owners' authority. */
export async function verifyHostedPrivateAccess(value: unknown): Promise<HostedPrivateVerificationResult> {
  const result: HostedPrivateVerificationResult = { status: 'REQUIRES_REVIEW', freshProof: false, restrictedDatabaseGrants: null, privateStorage: null, privateRealtime: null, storageProbe: null, realtimeProbe: null, sessionsClosed: false, activationAllowed: false, hostedAcceptance: false }, sessions: { token: string; role: string }[] = [];
  let authOrigin = '', publishable = '', service = '', apiOrigin = '', source: { schoolId: string; denialSchoolId: string; actors: { actorId: string; schoolId: string; role: string; email: string }[] } | null = null;
  let journal:{directory:string;prefix:string;identitySha256:string;createdAt:string;purpose:'INITIAL'|'PRE_ACTIVATION'}|null=null;
  const persist=async(suffix:string,body:unknown)=>{if(!journal)throw failure();const handle=await open(join(journal.directory,journal.prefix+suffix+'.json'),'wx',0o600);try{await handle.writeFile(canonicalReleaseExecutionJson(body));await handle.sync();}finally{await handle.close();}};
  try {
    const input = schema.parse(JSON.parse(canonicalReleaseExecutionJson(value))), expected = input.expected as BackendReleaseExpected, prepared = validatePreparedBackendReleaseIntent(input.preparedApproval, { ...expected, now: Date.now() }), runtime = prepareHostedRuntimeRecipients(input.runtimeConfig, expected);
    const api = new URL(input.apiDeployment.url); if (api.protocol !== 'https:' || !api.hostname.endsWith('.vercel.app') || api.pathname !== '/' || api.username || api.password || api.search || api.hash) throw failure(); apiOrigin = api.origin; authOrigin = expected.targets.supabase.authOrigin; publishable = runtime.api.SUPABASE_PUBLISHABLE_KEY; service = runtime.api.SUPABASE_SERVICE_ROLE_KEY;
    const manifestBytes = await readFile(join(input.repoRoot, 'supabase/seed/identities.json')); if (hash(manifestBytes) !== '7464b3487adc3998d8f4ad4582ffd08ebafbdc8fd9a568433ddc687f4f03ac21') throw failure(); source = JSON.parse(manifestBytes.toString('utf8'));
    if (!source) throw failure(); await readBackendReleaseAdmission({ repoRoot: input.repoRoot, expected, prepared, githubToken: input.githubToken });
    const deployment = await http(`https://api.vercel.com/v13/deployments/${input.apiDeployment.id}?teamId=${expected.targets.api.teamId}`, 'GET', { Authorization: 'Bearer ' + input.vercelToken }); z.object({ id: z.literal(input.apiDeployment.id), projectId: z.literal(expected.targets.api.projectId), ownerId: z.literal(expected.targets.api.teamId), url: z.literal(api.hostname), readyState: z.literal('READY'), meta: z.object({ cuevoCommitSha: z.literal(expected.releaseSha) }) }).parse(deployment.value); if (deployment.status !== 200) throw failure();
    if(!isAbsolute(input.repoRoot)||resolve(input.repoRoot)!==input.repoRoot||await realpath(input.repoRoot)!==input.repoRoot||!/^dpl_[A-Za-z0-9_]+$/.test(input.apiDeployment.id))throw failure();
    let directory=input.repoRoot;for(const part of ['.local','hosted-release']){directory=join(directory,part);try{await mkdir(directory,{mode:0o700});}catch(error){if((error as NodeJS.ErrnoException).code!=='EEXIST')throw failure();}const stat=await lstat(directory);if(!stat.isDirectory()||stat.isSymbolicLink()||await realpath(directory)!==directory)throw failure();}
    const prefix=(input.purpose==='PRE_ACTIVATION'?'private-probe-pre-activation-':'private-probe-')+input.apiDeployment.id,identitySha256=hash(canonicalReleaseExecutionJson({...(input.purpose==='PRE_ACTIVATION'?{purpose:input.purpose}:{}),sourceSha:expected.releaseSha,projectRef:expected.targets.supabase.projectRef,apiDeployment:input.apiDeployment,runtimeSha256:hash(canonicalReleaseExecutionJson(input.runtimeConfig))}));
    let exists=false;try{const stat=await lstat(join(directory,prefix+'-intent.json'));if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size>8192)throw failure();exists=true;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw failure();}
    if(exists){if(input.purpose==='PRE_ACTIVATION')throw failure();const intent=z.object({identitySha256:z.literal(identitySha256),createdAt:z.iso.datetime({offset:true})}).parse(JSON.parse(await readFile(join(directory,prefix+'-intent.json'),'utf8')));const stat=await lstat(join(directory,prefix+'-result.json'));if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size>32768||Date.parse(intent.createdAt)>Date.now()||Date.now()-Date.parse(intent.createdAt)>3600000)throw failure();const previous=z.object({identitySha256:z.literal(identitySha256),createdAt:z.literal(intent.createdAt),verifiedAt:z.iso.datetime({offset:true}),result:confirmedPrivateReceiptSchema}).strict().parse(JSON.parse(await readFile(join(directory,prefix+'-result.json'),'utf8')));if(Date.parse(previous.verifiedAt)<Date.parse(intent.createdAt)||Date.parse(previous.verifiedAt)>Date.now()||Date.now()-Date.parse(previous.verifiedAt)>3600000)throw failure();return {...previous.result,freshProof:false};}
    journal={directory,prefix,identitySha256,createdAt:new Date().toISOString(),purpose:input.purpose};
    result.restrictedDatabaseGrants = await restricted(runtime.api.DATABASE_URL, runtime.api.CUEVO_DATABASE_TLS_CA, 'cuevo_api') && await restricted(runtime.edge.CUEVO_WORKER_DATABASE_URL, runtime.edge.CUEVO_WORKER_TLS_CA, 'cuevo_worker'); if (!result.restrictedDatabaseGrants) throw failure();
    const bucket = await http(authOrigin + '/storage/v1/bucket/learner-private', 'GET', { apikey: service }); if (bucket.status !== 200) throw failure(); z.object({ id: z.literal('learner-private'), name: z.literal('learner-private'), public: z.literal(false), file_size_limit: z.literal(524288), allowed_mime_types: z.array(z.string()) }).parse(bucket.value);
    const original='hosted-private-'+input.purpose.toLowerCase()+'-'+input.apiDeployment.id+'-'+randomUUID();await persist('-intent',{version:1,state:'INTENT',identitySha256,createdAt:journal.createdAt,purpose:input.purpose,apiDeploymentId:input.apiDeployment.id,sourceSha:expected.releaseSha,projectRef:expected.targets.supabase.projectRef,originalKey:original});
    for (const role of ['admin', 'student', 'parent']) { const actor = source.actors.find(actor => actor.schoolId === source!.schoolId && actor.role === role); if (!actor) throw failure(); const login = await http(authOrigin + '/auth/v1/token?grant_type=password', 'POST', { apikey: publishable }, { email: actor.email, password: input.syntheticPassword }); if (login.status !== 200) throw failure(); const token = z.object({ access_token: z.string().min(20) }).parse(login.value).access_token; sessions.push({ token, role }); z.object({ user: z.object({ id: z.literal(actor.actorId), email: z.literal(actor.email) }) }).parse(login.value); }
    const token = (role: string) => sessions.find(session => session.role === role)!.token, actor = source.actors.find(actor => actor.schoolId === source!.schoolId && actor.role === 'student')!, headers = (role: string) => ({ Authorization: 'Bearer ' + token(role), 'X-School-Id': source!.schoolId }), bytes = Buffer.from('Cuevo source-bound synthetic private access verification.\n');
    const staged = await http(apiOrigin + '/v1/assets', 'POST', { ...headers('student'), 'Idempotency-Key': original + ':stage' }, { ownerId: actor.actorId, name: 'Synthetic private verification.txt', contentType: 'text/plain', byteSize: bytes.length, sha256: hash(bytes) }); if (staged.status !== 200) throw failure(); const asset = z.object({ id: z.uuid(), objectPath: z.string(), ownerId: z.literal(actor.actorId), sha256: z.literal(hash(bytes)), state: z.literal('STAGED') }).parse(staged.value); if (asset.objectPath !== source.schoolId + '/' + actor.actorId + '/' + asset.id) throw failure(); result.storageProbe = { assetId: asset.id, objectPath: asset.objectPath, retired: false, removed: false };
    await persist('-asset',{identitySha256,assetId:asset.id,objectPath:asset.objectPath});
    const finalized = await http(apiOrigin + '/v1/assets/' + asset.id + '/finalize', 'POST', { ...headers('student'), 'Idempotency-Key': original + ':finalize' }, { contentBase64: bytes.toString('base64') }); if (finalized.status !== 200 || z.object({ id: z.literal(asset.id), state: z.literal('AVAILABLE') }).safeParse(finalized.value).success !== true) throw failure();
    const download = await http(apiOrigin + '/v1/assets/' + asset.id + '/download', 'GET', headers('student')); if (download.status !== 200 || !download.bytes.equals(bytes)) throw failure();
    const directHeaders: Record<string, string>[] = [{ apikey: publishable }, { apikey: publishable, Authorization: 'Bearer ' + token('student') }];
    for (const direct of directHeaders) { const response = await http(authOrigin + '/storage/v1/object/learner-private/' + asset.objectPath, 'GET', direct); if (![400, 401, 403, 404].includes(response.status)) throw failure(); }
    const parent = await http(apiOrigin + '/v1/assets/' + asset.id + '/download', 'GET', headers('parent')); if (![403, 404].includes(parent.status)) throw failure(); result.privateStorage = true;
    const room = await http(apiOrigin + '/v1/community/rooms', 'POST', { ...headers('admin'), 'Idempotency-Key': original + ':room' }, { classId: '30000000-0000-4000-8000-000000000001', name: 'Synthetic private update verification', type: 'GROUP', memberIds: [actor.actorId] }); if (room.status !== 200) throw failure(); const created = z.object({ id: z.uuid() }).parse(room.value); result.realtimeProbe = { roomId: created.id, closed: false }; const topic = 'cuevo:' + source.schoolId + ':room:' + created.id;
    await persist('-room',{identitySha256,roomId:created.id});
    if (await privateJoin(authOrigin, publishable, token('student'), topic) !== 'SUBSCRIBED' || await privateJoin(authOrigin, publishable, token('parent'), topic) !== 'DENIED' || await privateJoin(authOrigin, publishable, token('student'), 'cuevo:' + source.denialSchoolId + ':room:' + created.id) !== 'DENIED') throw failure(); result.privateRealtime = true;
    await readBackendReleaseAdmission({ repoRoot: input.repoRoot, expected, prepared, githubToken: input.githubToken }); result.status = 'PRIVATE_PROBES_CONFIRMED';
  } catch { result.status = 'REQUIRES_REVIEW'; }
  finally {
    let clean = true; const session = (role: string) => sessions.find(session => session.role === role)?.token;
    if (source && result.storageProbe && session('student')) { try { const retire = await http(apiOrigin + '/v1/assets/' + result.storageProbe.assetId + '/retire', 'POST', { Authorization: 'Bearer ' + session('student'), 'X-School-Id': source.schoolId, 'Idempotency-Key': 'hosted-private-retire:' + result.storageProbe.assetId }, { reason: 'Completed source-bound synthetic private verification.', confirmRetirement: true }); result.storageProbe.retired = retire.status === 200 && z.object({ id: z.literal(result.storageProbe.assetId), state: z.literal('RETIRED') }).safeParse(retire.value).success; if (result.storageProbe.retired) { const removed = await http(authOrigin + '/storage/v1/object/learner-private', 'DELETE', { apikey: service }, { prefixes: [result.storageProbe.objectPath] }); const removedRows = z.array(z.object({ name: z.literal(result.storageProbe.objectPath) }).passthrough()).length(1).safeParse(removed.value); const absent = await http(authOrigin + '/storage/v1/object/learner-private/' + result.storageProbe.objectPath, 'GET', { apikey: service }); result.storageProbe.removed = removed.status === 200 && removedRows.success && absent.status === 404; } clean &&= result.storageProbe.retired && result.storageProbe.removed; } catch { clean = false; } }
    if (source && result.realtimeProbe && session('admin')) { try { const closed = await http(apiOrigin + '/v1/community/groups/' + result.realtimeProbe.roomId + '/lifecycle', 'POST', { Authorization: 'Bearer ' + session('admin'), 'X-School-Id': source.schoolId, 'Idempotency-Key': 'hosted-private-close:' + result.realtimeProbe.roomId }, { name: 'Synthetic private update verification', state: 'CLOSED', expectedRevision: 1, reason: 'Completed synthetic private-channel verification.', confirmChange: true }); result.realtimeProbe.closed = closed.status === 200 && z.object({ id: z.literal(result.realtimeProbe.roomId), revision: z.literal(2), status: z.literal('CLOSED') }).strict().safeParse(closed.value).success; clean &&= result.realtimeProbe.closed; } catch { clean = false; } }
    for (const session of sessions) { try { const logout = await http(authOrigin + '/auth/v1/logout?scope=local', 'POST', { apikey: publishable, Authorization: 'Bearer ' + session.token }, {}); clean &&= [200, 204].includes(logout.status); } catch { clean = false; } }
    result.sessionsClosed = clean; if (!clean) result.status = 'REQUIRES_REVIEW';
    if(journal){result.freshProof=result.status==='PRIVATE_PROBES_CONFIRMED';try{await persist('-result',{identitySha256:journal.identitySha256,createdAt:journal.createdAt,verifiedAt:new Date().toISOString(),result});}catch{result.status='REQUIRES_REVIEW';result.freshProof=false;}}
  }
  return result;
}
