import { createHash, createHmac, randomBytes, randomUUID } from 'node:crypto';
import { lstat, mkdir, open, readFile, realpath } from 'node:fs/promises';
import { isAbsolute, join, relative, resolve } from 'node:path';
import { checkServerIdentity, type TLSSocket } from 'node:tls';
import { Client } from 'pg';
import { z } from 'zod';
import { canonicalReleaseExecutionJson } from './release-review';
import {prepareNativeBackendReleaseAdmission,readNativeBackendReleaseAdmission,disposeNativeBackendReleaseAdmission,type NativeBackendAdmissionHandle} from './backend-release-admission';
import { validatePreparedBackendReleaseIntent, type BackendReleaseExpected } from './backend-release-contracts';
import { prepareHostedRuntimeRecipients } from './backend-provider-deploy';
import { verifyHostedBackendPrerequisites } from './backend-hosted-verification';
import { verifyHostedPrivateAccess } from './backend-hosted-private';
import { readHostedMigrationProvider, requireCurrentHostedMigrationEndpoint } from '../database/hosted-migration-provider';
import { verifyScheduledWorkerRecovery, type ScheduledRecoveryResult } from './backend-hosted-recovery';
import { backendPreviewHeaders } from './backend-preview-transport';
import {activeRuntimeStateSchema,validateActiveRuntimeTransition,type ActiveRuntimeState} from '../database/hosted-active-runtime-state';
import {confirmHostedWorkerActivation} from './backend-hosted-activation-confirmation';
import {observeDisabledDataApiConfiguration,type DataApiConfigurationObservation} from './data-api-configuration';

const fail=()=>Error('Hosted worker activation requires review; private contents withheld.');
const hash=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex');
const uuid=z.uuid(),timestamp=z.iso.datetime({offset:true});
const schema=z.object({repoRoot:z.string(),expected:z.unknown(),preparedApproval:z.unknown(),githubToken:z.string().min(1),providerToken:z.string().min(20),vercelToken:z.string().min(20),runtimeConfig:z.unknown(),apiDeployment:z.object({url:z.string().url(),id:z.string().startsWith('dpl_')}).strict(),edgeDeployment:z.object({id:z.string().min(1),version:z.number().int().positive()}).strict(),syntheticPassword:z.string().min(16).max(128),operatorDatabaseUrl:z.string(),operatorPassword:z.string().min(1),prerequisitesReceipt:z.unknown(),privateReceipt:z.unknown(),dataApiConfigurationEvidence:z.unknown().optional()}).strict();
export type HostedWorkerActivationInput=z.infer<typeof schema>;
export type HostedWorkerActivationResult={version:2;configurationObservation:DataApiConfigurationObservation|null;configurationEvidenceSha256:string|null;status:'ACTIVATED_SIGNED_SOURCE_VERIFIED'|'REQUIRES_REVIEW';purpose:'CUEVO_HOSTED_WORKER_ACTIVATION';phase:string;observedAt:string;runId:string|null;runAttempt:number|null;apiDeploymentId:string|null;packageSha256:string|null;runtimeSha256:string|null;keyOperation:'NONE'|'UNKNOWN'|'CONFIRMED';dispatchOperation:'NONE'|'UNKNOWN'|'CONFIRMED';dispatchDisabledOnFailure:boolean|null;sourceProcessed:boolean;duplicateWakeDenied:boolean;originalCommandReplayed:boolean;recoveryScheduled:boolean;scheduledRecoveryVerified:boolean;recovery:ScheduledRecoveryResult|null;recoveryVerified:false;configurationEvidenceObservedManual:boolean;sessionsClosed:boolean;sourceSha:string|null;projectRef:string|null;edgeVersion:number|null;jobId:number|null;probeEventId:string|null;hostedAcceptance:false;canonicalReceipt:string|null};
const command='select internal.request_worker_wake();',jobName='cuevo-worker-recovery';

async function http(url:string,method:'GET'|'POST',headers:Record<string,string>,body?:unknown){
 const signal=AbortSignal.timeout(10000),response=await fetch(url,{method,headers:{...headers,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'error',credentials:'omit',cache:'no-store',signal});
 if(response.redirected||response.url&&response.url!==url)throw fail();
 if(!response.body&&[201,204].includes(response.status))return{status:response.status,value:null as unknown};
 const declared=response.headers.get('content-length');if(declared!==null&&(!/^\d+$/.test(declared)||Number(declared)>65536)||!response.body)throw fail();
 const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;
 try{while(true){const part=await new Promise<ReadableStreamReadResult<Uint8Array>>((done,reject)=>{const abort=()=>{signal.removeEventListener('abort',abort);reject(fail());};if(signal.aborted)return abort();signal.addEventListener('abort',abort,{once:true});void reader.read().then(value=>{signal.removeEventListener('abort',abort);done(value);},()=>{signal.removeEventListener('abort',abort);reject(fail());});});if(part.done)break;size+=part.value.byteLength;if(size>65536||signal.aborted)throw fail();chunks.push(part.value);}return{status:response.status,value:JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(Buffer.concat(chunks))) as unknown};}finally{void reader.cancel().catch(()=>undefined);try{reader.releaseLock();}catch{/* Cancelled stream owns its pending cleanup. */}}
}
async function ownedDirectory(root:string){if(!isAbsolute(root)||resolve(root)!==root||await realpath(root)!==root)throw fail();const folder=join(root,'.local/hosted-release');await mkdir(folder,{recursive:true});let path=root;for(const part of ['.local','hosted-release']){path=join(path,part);const stat=await lstat(path);if(!stat.isDirectory()||stat.isSymbolicLink()||await realpath(path)!==path)throw fail();}return folder;}
async function file(root:string,path:string,maximum:number){if(!isAbsolute(path)||resolve(path)!==path||relative(root,path).split(/[\\/]/).some(p=>p==='..')||isAbsolute(relative(root,path)))throw fail();const stat=await lstat(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size>maximum||await realpath(path)!==path)throw fail();const bytes=await readFile(path),after=await lstat(path);if(bytes.length>maximum||stat.ino!==after.ino||stat.dev!==after.dev||stat.size!==after.size||stat.mtimeMs!==after.mtimeMs)throw fail();return bytes;}
async function exclusive(path:string,value:unknown){const handle=await open(path,'wx',0o600);try{await handle.writeFile(canonicalReleaseExecutionJson(value)+'\n');await handle.sync();}finally{await handle.close();}}
async function append(path:string,value:unknown){const handle=await open(path,'a',0o600);try{await handle.writeFile(canonicalReleaseExecutionJson(value)+'\n');await handle.sync();}finally{await handle.close();}}
function signed(key:string,wakeId:string){const seconds=Math.floor(Date.now()/1000);return{'Content-Type':'application/json','X-Cuevo-Wake-Time':String(seconds),'X-Cuevo-Wake-Signature':createHmac('sha256',key).update(`cuevo.worker.wake.v1\n${seconds}\n${wakeId}`).digest('hex')};}
function tls(client:Client,url:URL){const stream=(client as unknown as {connection:{stream:TLSSocket}}).connection.stream;if(!stream.encrypted||!stream.authorized||!['TLSv1.2','TLSv1.3'].includes(stream.getProtocol()??'')||checkServerIdentity(url.hostname,stream.getPeerCertificate()))throw fail();}

/** One initial activation consumes existing release/probe owners. The operator
 * journal refuses replay after uncertainty; it neither changes grants nor resets
 * source/lease history. Cron installation is not a lost-wake recovery proof. */
export async function activateHostedWorker(value:unknown,borrowed?:NativeBackendAdmissionHandle):Promise<HostedWorkerActivationResult>{
 const result:HostedWorkerActivationResult={version:2,configurationObservation:null,configurationEvidenceSha256:null,status:'REQUIRES_REVIEW',purpose:'CUEVO_HOSTED_WORKER_ACTIVATION',phase:'ADMISSION',observedAt:new Date().toISOString(),runId:null,runAttempt:null,apiDeploymentId:null,packageSha256:null,runtimeSha256:null,keyOperation:'NONE',dispatchOperation:'NONE',dispatchDisabledOnFailure:null,sourceProcessed:false,duplicateWakeDenied:false,originalCommandReplayed:false,recoveryScheduled:false,scheduledRecoveryVerified:false,recovery:null,recoveryVerified:false,configurationEvidenceObservedManual:false,sessionsClosed:true,sourceSha:null,projectRef:null,edgeVersion:null,jobId:null,probeEventId:null,hostedAcceptance:false,canonicalReceipt:null};
 let client:Client|undefined,locked=false,transaction=false,connectionLost=false,ending=false,token:string|undefined,auth='',publishable='',folder='',journal='',key='',secretName='',endpoint='',input:HostedWorkerActivationInput|undefined,url:URL|undefined,durable:ActiveRuntimeState|undefined;
 let verifiedExecution:Readonly<{sourceSha:string;runId:string;runAttempt:number;packageSha256:string;runtimeSha256:string;activationId:string;endpoint:string;vaultSecretName:string;probeEventId:string;jobId:number}>|undefined;
 let preview:Parameters<typeof backendPreviewHeaders>[0]|undefined;
 const requestApi=async(path:string,method:'GET'|'POST',headers:Record<string,string>,body?:unknown)=>http(path,method,{...(preview?await backendPreviewHeaders({...preview,url:path}):{}),...headers},body);
 const record=async(phase:string,detail:Record<string,unknown>={})=>{result.phase=phase;if(journal)await append(journal,{phase,at:new Date().toISOString(),...detail});};
 const saveActive=async(connection:Client,next:ActiveRuntimeState)=>{
   if(!input||!url)throw fail();tls(connection,url);const name='cuevo_active_runtime_'+next.projectRef,rows=(await connection.query('/* CUEVO_ACTIVE_RUNTIME_READ */ select id,decrypted_secret from vault.decrypted_secrets where name=$1',[name])).rows;if(rows.length>1)throw fail();const prior=rows.length?activeRuntimeStateSchema.parse(JSON.parse(String(rows[0].decrypted_secret))):null;
   validateActiveRuntimeTransition(prior,next,next.projectRef);await connection.query('BEGIN');try{const current=(await connection.query('/* CUEVO_ACTIVE_RUNTIME_READ */ select id,decrypted_secret from vault.decrypted_secrets where name=$1',[name])).rows;if(current.length!==rows.length||current.length&&hash(canonicalReleaseExecutionJson(JSON.parse(String(current[0].decrypted_secret))))!==hash(canonicalReleaseExecutionJson(prior)))throw fail();
    if(rows.length)await connection.query('/* CUEVO_ACTIVE_RUNTIME_SAVE */ select vault.update_secret($1,$2,$3,$4)',[rows[0].id,canonicalReleaseExecutionJson(next),name,'Cuevo original active runtime state']);else await connection.query('/* CUEVO_ACTIVE_RUNTIME_SAVE */ select vault.create_secret($1,$2,$3)',[canonicalReleaseExecutionJson(next),name,'Cuevo original active runtime state']);await connection.query('COMMIT');
   }catch{await connection.query('ROLLBACK').catch(()=>undefined);throw fail();}tls(connection,url);const after=(await connection.query('/* CUEVO_ACTIVE_RUNTIME_READ */ select id,decrypted_secret from vault.decrypted_secrets where name=$1',[name])).rows;if(after.length!==1||canonicalReleaseExecutionJson(activeRuntimeStateSchema.parse(JSON.parse(String(after[0].decrypted_secret))))!==canonicalReleaseExecutionJson(next))throw fail();durable=next;
 };
 let admissionHandle:NativeBackendAdmissionHandle|undefined;
 try{try{
  input=schema.parse(JSON.parse(canonicalReleaseExecutionJson(value)));const expected=input.expected as BackendReleaseExpected,prepared=validatePreparedBackendReleaseIntent(input.preparedApproval,{...expected,now:Date.now()}),runtime=prepareHostedRuntimeRecipients(input.runtimeConfig,expected),project=expected.targets.supabase.projectRef;
  result.sourceSha=expected.releaseSha;result.projectRef=project;result.edgeVersion=input.edgeDeployment.version;result.runId=expected.releaseRunId;result.runAttempt=expected.runAttempt;result.apiDeploymentId=input.apiDeployment.id;result.packageSha256=prepared.sha256;result.runtimeSha256=runtime.runtimeSha256;auth=expected.targets.supabase.authOrigin;endpoint=expected.targets.supabase.edgeOrigin;publishable=runtime.api.SUPABASE_PUBLISHABLE_KEY;
  if(auth!==`https://${project}.supabase.co`||endpoint!==auth+'/functions/v1/cuevo-worker')throw fail();
  folder=await ownedDirectory(input.repoRoot);const intentPath=join(folder,'worker-activation-intent.json');try{await lstat(intentPath);throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}
  if(input.dataApiConfigurationEvidence!==undefined)throw fail();
  const admissionBinding={repoRoot:input.repoRoot,expected,prepared,effectScope:'COMPLETE_BACKEND' as const};admissionHandle=borrowed===undefined?await prepareNativeBackendReleaseAdmission({...admissionBinding,githubToken:input.githubToken}):borrowed;const admission=()=>readNativeBackendReleaseAdmission(admissionHandle,admissionBinding),expiresAt=z.object({expiresAt:timestamp}).parse(JSON.parse(prepared.canonicalJson)).expiresAt;
  const observeConfiguration=()=>observeDisabledDataApiConfiguration({projectRef:project,sourceSha:expected.releaseSha,treeSha:expected.treeSha,token:input!.providerToken,expiresAt},admission);
  const configurationObservation=await observeConfiguration(),configurationBytes=Buffer.from(canonicalReleaseExecutionJson(configurationObservation.evidence)+'\n');
  await exclusive(join(folder,'data-api-configuration.json'),configurationObservation.evidence);result.configurationObservation=configurationObservation;result.configurationEvidenceSha256=hash(configurationBytes);

  await admission();
  const provider=await readHostedMigrationProvider({projectRef:project,boundProjectRef:project,providerToken:input.providerToken});url=new URL(input.operatorDatabaseUrl);const selected={projectRef:project,kind:url.hostname===`db.${project}.supabase.co`?'direct':'session-pooler',host:url.hostname,port:5432,database:'postgres'};requireCurrentHostedMigrationEndpoint(selected,provider,expected.fingerprints.migrationEndpointSha256);
  if(url.protocol!=='postgresql:'||url.password||url.port!=='5432'||url.pathname!=='/postgres'||url.search!=='?sslmode=verify-full'||url.hash||decodeURIComponent(url.username)!==(selected.kind==='direct'?'postgres':'postgres.'+project))throw fail();
  const api=new URL(input.apiDeployment.url);if(api.protocol!=='https:'||api.username||api.password||api.pathname!=='/'||api.search||api.hash||!api.hostname.endsWith('.vercel.app'))throw fail();
  preview={repoRoot:input.repoRoot,expected,prepared,apiDeployment:input.apiDeployment,url:api.origin+'/'};
  const deployment=await http(`https://api.vercel.com/v13/deployments/${input.apiDeployment.id}?teamId=${expected.targets.api.teamId}`,'GET',{Authorization:'Bearer '+input.vercelToken});if(deployment.status!==200)throw fail();z.object({id:z.literal(input.apiDeployment.id),projectId:z.literal(expected.targets.api.projectId),ownerId:z.literal(expected.targets.api.teamId),url:z.literal(api.hostname),readyState:z.literal('READY'),target:z.null().or(z.literal('preview')),meta:z.object({cuevoCommitSha:z.literal(expected.releaseSha)})}).parse(deployment.value);
  const edge=await http(`https://api.supabase.com/v1/projects/${project}/functions/cuevo-worker`,'GET',{Authorization:'Bearer '+input.providerToken});if(edge.status!==200)throw fail();z.object({id:z.literal(input.edgeDeployment.id),slug:z.literal('cuevo-worker'),status:z.literal('ACTIVE'),version:z.literal(input.edgeDeployment.version),verify_jwt:z.literal(false)}).parse(edge.value);
  const ca=runtime.api.CUEVO_DATABASE_TLS_CA;if(!ca.includes('-----BEGIN CERTIFICATE-----'))throw fail();client=new Client({host:url.hostname,port:5432,database:'postgres',user:decodeURIComponent(url.username),password:input.operatorPassword,ssl:{rejectUnauthorized:true,ca,minVersion:'TLSv1.2'},connectionTimeoutMillis:5000,statement_timeout:5000,query_timeout:7000,lock_timeout:2000,application_name:'cuevo-hosted-worker-activation'});const lost=()=>{if(!ending)connectionLost=true;};client.on('error',lost);client.on('end',lost);await client.connect();tls(client,url);
  const live=()=>{if(connectionLost)throw fail();tls(client!,url!);};
  const one=async(sql:string,args:unknown[]=[])=>{live();const query=await client!.query(sql,args);live();if(query.rows.length!==1)throw fail();return query.rows[0] as Record<string,unknown>;};
  const who=await one(`/* CUEVO_ACTIVATION_IDENTITY */ select session_user::text as operator,current_database()::text as database,(select ssl from pg_stat_ssl where pid=pg_backend_pid())as ssl,current_setting('server_version_num')::integer as "serverVersion"`);if(who.operator!=='postgres'||who.database!=='postgres'||who.ssl!==true||Number(who.serverVersion)<170000||Number(who.serverVersion)>=180000)throw fail();
  const lock=await one('select pg_try_advisory_lock(hashtextextended($1,0))as locked',[project+':HOSTED_SCHEMA_MIGRATION']);if(lock.locked!==true)throw fail();locked=true;
  const manifestBytes=await file(input.repoRoot,join(input.repoRoot,'supabase/seed/identities.json'),128*1024);if(hash(manifestBytes)!=='7464b3487adc3998d8f4ad4582ffd08ebafbdc8fd9a568433ddc687f4f03ac21')throw fail();const manifest=JSON.parse(manifestBytes.toString('utf8')) as {schoolId:string;denialSchoolId:string;actors:{actorId:string;schoolId:string;role:string;email:string}[]};
  const source=await one(`/* CUEVO_ACTIVATION_SOURCE */ select (select count(*)::integer from app.people)as people,(select bool_and(synthetic)from app.people)as synthetic,not exists(select 1 from app.people p full join jsonb_to_recordset($1::jsonb)as e("schoolId"uuid,"actorId"uuid)on p.school_id=e."schoolId"and p.actor_id=e."actorId"where p.actor_id is null or e."actorId"is null or p.synthetic is distinct from true)as "populationMatches",(select count(*)::integer from app.schools)as schools,not exists(select 1 from jsonb_to_recordset($1::jsonb)as e("schoolId"uuid,"actorId"uuid,role text)where not exists(select 1 from app.memberships m where m.school_id=e."schoolId"and m.actor_id=e."actorId"and m.role=e.role and m.status='active'and m.effective_from<=now()and(m.effective_to is null or m.effective_to>now())))as "currentActors",internal.worker_transport_private()as "transportPrivate",not exists(select 1 from internal.posthog_school_activation where enabled)as "analyticsDisabled",exists(select 1 from pg_roles where rolname='cuevo_worker'and rolcanlogin and not rolsuper and not rolbypassrls and not rolcreaterole and not rolcreatedb and not rolreplication and not rolinherit)as "workerReady",to_regprocedure('cron.schedule(text,text,text)')is not null as "cronAvailable"`,[JSON.stringify(manifest.actors)]);if(source.people!==133||source.schools!==2||['synthetic','populationMatches','currentActors','transportPrivate','analyticsDisabled','workerReady','cronAvailable'].some(k=>source[k]!==true))throw fail();
  const control=()=>one('/* CUEVO_ACTIVATION_CONTROL */ select enabled,endpoint,vault_secret_name,allow_local,state,wake_id,lease_expires_at,network_request_id from internal.worker_dispatch_control where singleton');
  const initial=await control();if(initial.enabled!==false||initial.state!=='DISABLED'||initial.endpoint!==null||initial.vault_secret_name!==null||initial.allow_local!==false||initial.wake_id!==null)throw fail();
  const jobs=await client.query(`/* CUEVO_ACTIVATION_CRON */ select jobid,jobname,schedule,command,database,username,active from cron.job where jobname=$1 or(active and(command ilike '%request_worker_wake%'or jobname ilike 'cuevo%'))`,[jobName]);if(jobs.rows.length)throw fail();
  const originalActive=(await client.query('/* CUEVO_ACTIVE_RUNTIME_READ */ select id,decrypted_secret from vault.decrypted_secrets where name=$1',['cuevo_active_runtime_'+project])).rows;if(originalActive.length)throw fail();
  const activationId=randomUUID(),originalKey='worker-activation:'+expected.releaseRunId+':'+expected.runAttempt+':'+activationId;
  await exclusive(intentPath,{version:2,configurationEvidenceObservedManual:false,configurationObservation,purpose:result.purpose,activationId,sourceSha:expected.releaseSha,projectRef:project,packageSha256:prepared.sha256,runtimeSha256:runtime.runtimeSha256,apiDeploymentId:input.apiDeployment.id,edgeDeployment:input.edgeDeployment,configurationEvidenceSha256:result.configurationEvidenceSha256,originalKey,endpoint,createdAt:new Date().toISOString()});journal=join(folder,'worker-activation-journal.jsonl');await exclusive(journal,{phase:'INTENT_RECORDED',at:new Date().toISOString()});
  const probeInput={repoRoot:input.repoRoot,expected,preparedApproval:prepared,githubToken:input.githubToken,providerToken:input.providerToken,vercelToken:input.vercelToken,runtimeConfig:input.runtimeConfig,apiDeployment:input.apiDeployment,syntheticPassword:input.syntheticPassword};
  z.object({status:z.literal('PREREQUISITES_OBSERVED')}).parse(input.prerequisitesReceipt);z.object({status:z.literal('PRIVATE_PROBES_CONFIRMED'),sessionsClosed:z.literal(true)}).parse(input.privateReceipt);
  const prerequisites=await verifyHostedBackendPrerequisites({...probeInput,edgeDeployment:input.edgeDeployment},admissionHandle);if(prerequisites.status!=='PREREQUISITES_OBSERVED'||prerequisites.roleSessions!==5||prerequisites.apiReady!==true||prerequisites.crossSchoolDenied!==true)throw fail();
  await record('PRIVATE_PROBE_INTENT');const privateAccess=await verifyHostedPrivateAccess({...probeInput,purpose:'PRE_ACTIVATION'},admissionHandle);if(privateAccess.status!=='PRIVATE_PROBES_CONFIRMED'||privateAccess.freshProof!==true||privateAccess.sessionsClosed!==true||privateAccess.privateStorage!==true||privateAccess.privateRealtime!==true||privateAccess.restrictedDatabaseGrants!==true)throw fail();await record('PRIVATE_PROBES_CONFIRMED');
  const preKeyConfiguration=await observeConfiguration();if(preKeyConfiguration.evidence.configurationValueSha256!==configurationObservation.evidence.configurationValueSha256)throw fail();await admission();
  const refreshed=z.object({transportPrivate:z.literal(true),synthetic:z.literal(true),analyticsDisabled:z.literal(true)}).parse(await one('/* CUEVO_ACTIVATION_PRE_KEY */ select internal.worker_transport_private()as "transportPrivate",(select bool_and(synthetic)from app.people)as synthetic,not exists(select 1 from internal.posthog_school_activation where enabled)as "analyticsDisabled"'));if(!refreshed)throw fail();
  const secretsUrl=`https://api.supabase.com/v1/projects/${project}/secrets`,secretHeaders={Authorization:'Bearer '+input.providerToken},beforeSecrets=await http(secretsUrl,'GET',secretHeaders);if(beforeSecrets.status!==200)throw fail();const secretRows=z.array(z.object({name:z.string(),value:z.string()})).max(100).parse(beforeSecrets.value);for(const[name,v]of Object.entries(runtime.edge)){const found=secretRows.filter(r=>r.name===name);if(found.length!==1||found[0].value!==hash(v))throw fail();}
  secretName='cuevo_worker_'+activationId.replaceAll('-','');key=randomBytes(32).toString('hex');await record('KEY_PREPARED',{vaultSecretName:secretName,keySha256:hash(key)});await exclusive(join(folder,'worker-activation-private.json'),{purpose:'PRIVATE_WORKER_ACTIVATION_KEY',activationId,projectRef:project,sourceSha:expected.releaseSha,key});
  const originalState=activeRuntimeStateSchema.parse({version:1,purpose:'CUEVO_PRIVATE_ACTIVE_RUNTIME_STATE',projectRef:project,phase:'INTENT',identity:{sourceSha:expected.releaseSha,treeSha:expected.treeSha,originalRunId:expected.releaseRunId,originalRunAttempt:expected.runAttempt,originalPackageSha256:prepared.sha256,runtimeSha256:runtime.runtimeSha256,apiDeploymentId:input.apiDeployment.id,apiUrl:api.origin,edgeId:input.edgeDeployment.id,edgeVersion:input.edgeDeployment.version,activationId,vaultSecretName:secretName,endpoint,createdAt:new Date().toISOString()},wakeKey:key,runtimeConfig:input.runtimeConfig,jobId:null,activation:null,cleanup:null});await exclusive(join(folder,'worker-activation-identity.json'),originalState.identity);await saveActive(client,originalState);
  live();result.keyOperation='UNKNOWN';await record('EDGE_KEY_INTENT');live();const installed=await http(secretsUrl,'POST',secretHeaders,[{name:'CUEVO_WORKER_WAKE_KEY',value:key}]);if(![200,201,204].includes(installed.status))throw fail();live();const secretAfter=await http(secretsUrl,'GET',secretHeaders);const keys=z.array(z.object({name:z.string(),value:z.string()})).max(100).parse(secretAfter.value);if(secretAfter.status!==200||keys.filter(r=>r.name==='CUEVO_WORKER_WAKE_KEY'&&r.value===hash(key)).length!==1)throw fail();result.keyOperation='CONFIRMED';await record('EDGE_KEY_CONFIRMED');
  const installedEdge=await http(`https://api.supabase.com/v1/projects/${project}/functions/cuevo-worker`,'GET',secretHeaders);z.object({id:z.literal(input.edgeDeployment.id),version:z.literal(input.edgeDeployment.version),status:z.literal('ACTIVE'),verify_jwt:z.literal(false)}).parse(installedEdge.value);
  result.dispatchOperation='UNKNOWN';await record('DISPATCH_INTENT');await client.query('BEGIN');transaction=true;const lockedControl=await one('/* CUEVO_ACTIVATION_CONTROL */ select enabled,endpoint,vault_secret_name,allow_local,state,wake_id,lease_expires_at,network_request_id from internal.worker_dispatch_control where singleton for update');if(lockedControl.enabled!==false||lockedControl.endpoint!==null||lockedControl.vault_secret_name!==null)throw fail();
  const vault=await one('select vault.create_secret($1,$2,$3)as id',[key,secretName,'Cuevo reviewed signed worker activation']);uuid.parse(vault.id);const vaultRead=await one('/* CUEVO_ACTIVATION_VAULT */ select count(*)::integer as count,bool_and(decrypted_secret=$2)as matching from vault.decrypted_secrets where name=$1',[secretName,key]);if(vaultRead.count!==1||vaultRead.matching!==true)throw fail();const configured=await one('select internal.configure_worker_dispatch($1,$2,$3,$4)as configured',[true,endpoint,secretName,false]);if(configured.configured!==true)throw fail();await client.query('COMMIT');transaction=false;result.dispatchOperation='CONFIRMED';await record('DISPATCH_CONFIRMED',{vaultSecretId:vault.id});
  const wrongWake=randomUUID(),unsigned=await http(endpoint,'POST',{'Content-Type':'application/json'},{version:1,wakeId:wrongWake}),wrong=await http(endpoint,'POST',signed(randomBytes(32).toString('hex'),wrongWake),{version:1,wakeId:wrongWake});if(unsigned.status!==401||wrong.status!==401||z.object({code:z.literal('WORKER_AUTH_REQUIRED')}).safeParse(unsigned.value).success!==true||z.object({code:z.literal('WORKER_AUTH_REQUIRED')}).safeParse(wrong.value).success!==true)throw fail();
  const admin=manifest.actors.find(a=>a.schoolId===manifest.schoolId&&a.role==='admin');if(!admin)throw fail();const login=await http(auth+'/auth/v1/token?grant_type=password','POST',{apikey:publishable},{email:admin.email,password:input.syntheticPassword});if(login.status!==200)throw fail();token=z.object({access_token:z.string().min(20)}).parse(login.value).access_token;result.sessionsClosed=false;z.object({user:z.object({id:z.literal(admin.actorId),email:z.literal(admin.email)})}).parse(login.value);
  const details=await one('/* CUEVO_ACTIVATION_SCHOOL */ select name,country_code,languages from app.schools where id=$1 and status=\'active\'',[manifest.schoolId]),body={name:details.name,countryCode:details.country_code,languages:details.languages},headers={Authorization:'Bearer '+token,'X-School-Id':manifest.schoolId,'Idempotency-Key':originalKey};
  await record('SOURCE_COMMAND_INTENT',{originalKey,command:'school.details.update',bodySha256:hash(canonicalReleaseExecutionJson(body))});await client.query('BEGIN');transaction=true;await one('/* CUEVO_ACTIVATION_CONTROL */ select enabled,endpoint,vault_secret_name,allow_local,state,wake_id,lease_expires_at,network_request_id from internal.worker_dispatch_control where singleton for update');const created=await requestApi(api.origin+'/v1/school/details','POST',headers,body);if(created.status!==200)throw fail();const sourceReceipt=z.object({id:uuid,schoolId:z.literal(manifest.schoolId),command:z.literal('details.update')}).parse(created.value);const replay=await requestApi(api.origin+'/v1/school/details','POST',headers,body);if(replay.status!==200||canonicalReleaseExecutionJson(replay.value)!==canonicalReleaseExecutionJson(created.value))throw fail();result.originalCommandReplayed=true;
  const eventQuery=`/* CUEVO_ACTIVATION_EVENT */ select e.id,e.entity_id,e.entity_type,e.type,e.version,e.actor_id,e.school_id,e.state,exists(select 1 from internal.processed_events p where p.event_id=e.id)as processed,exists(select 1 from internal.audit_events a where a.school_id=e.school_id and a.actor_id=e.actor_id and a.entity_id=e.entity_id and a.action='school.details.update'and a.outcome='succeeded')as audit,(select count(*)::integer from internal.idempotency_keys k where k.school_id=e.school_id and k.actor_id=e.actor_id and k.key=$3 and k.command='school.details.update'and k.state='COMPLETED'and k.response->>'id'=e.entity_id::text)as command_count from internal.outbox_events e where e.school_id=$1 and e.entity_id=$2 and e.type='school.updated'and e.metadata=jsonb_build_object('command','details.update') and e.deduplication_key='school:'||md5(e.actor_id::text||':details.update:'||$3)`;
  let event=await one(eventQuery,[manifest.schoolId,sourceReceipt.id,originalKey]);if(event.type!=='school.updated'||event.entity_type!=='school_operation'||event.actor_id!==admin.actorId||event.version!==1||event.audit!==true||event.command_count!==1)throw fail();result.probeEventId=uuid.parse(event.id);await one('select internal.request_worker_wake()as requested');const generation=await one('/* CUEVO_ACTIVATION_GENERATION */ select wake_id,state,network_request_id from internal.worker_dispatch_control where singleton');const wakeId=uuid.parse(generation.wake_id);if(generation.state!=='REQUESTED'||generation.network_request_id===null)throw fail();await record('SOURCE_AND_WAKE_CONFIRMED',{eventId:event.id,sourceId:sourceReceipt.id,wakeId});await client.query('COMMIT');transaction=false;
  const delivered=await http(endpoint,'POST',signed(key,wakeId),{version:1,wakeId});if(delivered.status===200){z.object({status:z.literal('COMPLETED'),processed:z.number().int().nonnegative().max(10)}).parse(delivered.value);}else if(delivered.status===202){z.object({status:z.literal('NOT_ADMITTED')}).parse(delivered.value);}else throw fail();
  const deadline=Date.now()+90000;while(Date.now()<deadline){event=await one(eventQuery,[manifest.schoolId,sourceReceipt.id,originalKey]);if(event.state==='COMPLETED'&&event.processed===true){result.sourceProcessed=true;break;}await new Promise(done=>setTimeout(done,1000));}if(!result.sourceProcessed)throw fail();const duplicate=await http(endpoint,'POST',signed(key,wakeId),{version:1,wakeId});if(duplicate.status!==202||z.object({status:z.literal('NOT_ADMITTED')}).safeParse(duplicate.value).success!==true)throw fail();result.duplicateWakeDenied=true;await record('SIGNED_SOURCE_VERIFIED',{eventId:event.id});
  const current=await control();if(current.enabled!==true||current.endpoint!==endpoint||current.vault_secret_name!==secretName)throw fail();await admission();await record('CRON_INTENT',{jobName,schedule:'* * * * *',command});await client.query('BEGIN');transaction=true;const again=await client.query(`/* CUEVO_ACTIVATION_CRON */ select jobid,jobname,schedule,command,database,username,active from cron.job where jobname=$1 or(active and(command ilike '%request_worker_wake%'or jobname ilike 'cuevo%'))`,[jobName]);if(again.rows.length)throw fail();const schedule=await one('select cron.schedule($1,$2,$3)as jobid',[jobName,'* * * * *',command]);const jobId=z.number().int().positive().parse(Number(schedule.jobid));result.jobId=jobId;await record('CRON_PENDING_COMMIT',{jobId});await client.query('COMMIT');transaction=false;
  const jobsAfter=await client.query('/* CUEVO_ACTIVATION_CRON */ select jobid,jobname,schedule,command,database,username,active from cron.job where jobname=$1',[jobName]);if(jobsAfter.rows.length!==1)throw fail();z.object({jobid:z.coerce.number().int().positive().refine(n=>n===jobId),jobname:z.literal(jobName),schedule:z.literal('* * * * *'),command:z.literal(command),database:z.literal('postgres'),username:z.literal('postgres'),active:z.literal(true)}).parse(jobsAfter.rows[0]);result.recoveryScheduled=true;await record('CRON_CONFIRMED',{jobId});
  const recovery=await verifyScheduledWorkerRecovery({schoolId:manifest.schoolId,actorId:admin.actorId,endpoint,vaultSecretName:secretName,jobId,originalKey:originalKey+':recovery',body},{
    query:async(sql,args=[])=>{live();const response=await client!.query(sql,args);live();return{rows:response.rows as Record<string,unknown>[]};},
    begin:async()=>{live();await client!.query('BEGIN');transaction=true;},commit:async()=>{live();await client!.query('COMMIT');transaction=false;live();},rollback:async()=>{await client!.query('ROLLBACK');transaction=false;},
    command:async(payload,commandKey)=>{live();const response=await requestApi(api.origin+'/v1/school/details','POST',{...headers,'Idempotency-Key':commandKey},payload);live();if(response.status!==200)throw fail();return response.value;},
    admit:async()=>{live();await admission();live();},record:async(phase,detail)=>record(phase,detail),now:Date.now,pause:()=>new Promise(done=>setTimeout(done,1000)),
  });result.recovery=recovery;result.scheduledRecoveryVerified=recovery.scheduledRecoveryVerified;await record('RECOVERY_RESULT',{...recovery});if(recovery.status!=='SCHEDULED_RECOVERY_VERIFIED')throw fail();
  live();const verifiedControl=await control();if(verifiedControl.enabled!==true||verifiedControl.endpoint!==endpoint||verifiedControl.vault_secret_name!==secretName||verifiedControl.allow_local!==false||result.keyOperation!=='CONFIRMED'||result.dispatchOperation!=='CONFIRMED'||!result.sourceProcessed||!result.duplicateWakeDenied||!result.originalCommandReplayed||!result.recoveryScheduled||!result.scheduledRecoveryVerified||result.probeEventId!==event.id||result.jobId!==jobId)throw fail();
  verifiedExecution=Object.freeze({sourceSha:expected.releaseSha,runId:expected.releaseRunId,runAttempt:expected.runAttempt,packageSha256:prepared.sha256,runtimeSha256:runtime.runtimeSha256,activationId,endpoint,vaultSecretName:secretName,probeEventId:result.probeEventId,jobId});result.status='ACTIVATED_SIGNED_SOURCE_VERIFIED';result.observedAt=new Date().toISOString();await record('ACTIVATION_VERIFIED');
 }catch{result.status='REQUIRES_REVIEW';}
 finally{
  if(client&&transaction){try{await client.query('ROLLBACK');}catch{/* The retained dispatch intent stays uncertain. */}transaction=false;}
  const pauseOwned=async()=>{if(verifiedExecution||!client||!secretName||!endpoint||result.dispatchOperation==='NONE')return;
   try{await client.query('BEGIN');const current=(await client.query('/* CUEVO_ACTIVATION_CONTROL */ select enabled,endpoint,vault_secret_name,allow_local,state,wake_id,lease_expires_at,network_request_id from internal.worker_dispatch_control where singleton for update')).rows;if(current.length!==1||current[0].enabled!==true||current[0].endpoint!==endpoint||current[0].vault_secret_name!==secretName)throw fail();const paused=await client.query('select internal.configure_worker_dispatch($1,$2,$3,$4)as configured',[false,null,null,false]);if(paused.rows[0]?.configured!==true)throw fail();if(result.jobId!==null){const owned=(await client.query('/* CUEVO_ACTIVATION_CRON */ select jobid,jobname,schedule,command,database,username,active from cron.job where jobname=$1',[jobName])).rows;if(owned.length!==1||Number(owned[0].jobid)!==result.jobId||owned[0].command!==command)throw fail();const removed=await client.query('select cron.unschedule($1::bigint)as removed',[result.jobId]);if(removed.rows[0]?.removed!==true)throw fail();}await client.query('COMMIT');result.dispatchDisabledOnFailure=true;await record('OWNED_DISPATCH_DISABLED');}catch{try{await client.query('ROLLBACK');}catch{/* Unknown cleanup remains retained. */}result.dispatchDisabledOnFailure=false;}
  };
  if(token){try{const logout=await http(auth+'/auth/v1/logout?scope=local','POST',{apikey:publishable,Authorization:'Bearer '+token},{});result.sessionsClosed=[200,204].includes(logout.status);}catch{result.sessionsClosed=false;}if(!result.sessionsClosed)result.status='REQUIRES_REVIEW';}
  if(result.status==='REQUIRES_REVIEW')await pauseOwned();
  if(journal){try{await record('EXECUTION_FINAL',{status:result.status,keyOperation:result.keyOperation,dispatchOperation:result.dispatchOperation,sessionsClosed:result.sessionsClosed});result.phase='FINAL';result.canonicalReceipt=canonicalReleaseExecutionJson({...result,canonicalReceipt:null});await exclusive(join(folder,'worker-activation-execution-result.json'),{...result,canonicalReceipt:null});if(result.status==='ACTIVATED_SIGNED_SOURCE_VERIFIED'&&client&&durable)await saveActive(client,activeRuntimeStateSchema.parse({...durable,phase:'CONFIGURED',jobId:result.jobId,activation:{...result,canonicalReceipt:null}}));}catch{result.status='REQUIRES_REVIEW';result.canonicalReceipt=null;await pauseOwned();}}
  let released=!locked,nativeClosed=!client;
  if(client){if(locked)try{const unlock=await client.query('select pg_advisory_unlock(hashtextextended($1,0))as released',[result.projectRef+':HOSTED_SCHEMA_MIGRATION']);released=unlock.rows[0]?.released===true&&!connectionLost;if(!released){result.status='REQUIRES_REVIEW';result.canonicalReceipt=null;await pauseOwned();}}catch{released=false;result.status='REQUIRES_REVIEW';result.canonicalReceipt=null;}ending=true;try{await client.end();nativeClosed=true;}catch{nativeClosed=false;result.status='REQUIRES_REVIEW';result.canonicalReceipt=null;}result.sessionsClosed=result.sessionsClosed&&nativeClosed;}
  if(journal){try{await exclusive(join(folder,'worker-activation-execution-cleanup.json'),{purpose:'CUEVO_HOSTED_WORKER_ACTIVATION_CLEANUP',sourceSha:result.sourceSha,projectRef:result.projectRef,runId:result.runId,runAttempt:result.runAttempt,status:result.status,lockReleased:released,sessionsClosed:result.sessionsClosed,resultSha256:result.canonicalReceipt===null?null:hash(result.canonicalReceipt),observedAt:new Date().toISOString()});}catch{result.status='REQUIRES_REVIEW';result.canonicalReceipt=null;}}
  let confirmationReleased=true,confirmationClosed=true;
  if(result.status==='ACTIVATED_SIGNED_SOURCE_VERIFIED'&&released&&result.sessionsClosed&&durable?.phase==='CONFIGURED'&&input&&url){
    const confirmation=await confirmHostedWorkerActivation({repoRoot:input.repoRoot,expected:input.expected,preparedApproval:input.preparedApproval,githubToken:input.githubToken,providerToken:input.providerToken,vercelToken:input.vercelToken,runtimeConfig:input.runtimeConfig,operatorDatabaseUrl:input.operatorDatabaseUrl,operatorPassword:input.operatorPassword},admissionHandle);
    confirmationReleased=confirmation.lockReleased;confirmationClosed=confirmation.sessionClosed;
    if(confirmation.status!=='ORIGINAL_ACTIVATION_CONFIRMED'||!confirmation.canonicalReceipt||!confirmation.lockReleased||!confirmation.sessionClosed){result.status='REQUIRES_REVIEW';result.canonicalReceipt=null;}
  }
  // Current terminal files are completion evidence only after both sessions
  // settle. A late observation/publication failure never pauses healthy work.
  if(journal){try{result.sessionsClosed=result.sessionsClosed&&confirmationClosed;result.observedAt=new Date().toISOString();await record('FINAL',{status:result.status,keyOperation:result.keyOperation,dispatchOperation:result.dispatchOperation,sessionsClosed:result.sessionsClosed});const terminal={...result,canonicalReceipt:null},canonical=canonicalReleaseExecutionJson(terminal);await exclusive(join(folder,'worker-activation-cleanup.json'),{purpose:'CUEVO_HOSTED_WORKER_ACTIVATION_CLEANUP',sourceSha:result.sourceSha,projectRef:result.projectRef,runId:result.runId,runAttempt:result.runAttempt,status:result.status,lockReleased:released&&confirmationReleased,sessionsClosed:result.sessionsClosed,resultSha256:hash(canonical),observedAt:new Date().toISOString()});await exclusive(join(folder,'worker-activation-result.json'),terminal);result.canonicalReceipt=result.status==='ACTIVATED_SIGNED_SOURCE_VERIFIED'?canonical:null;}catch{result.status='REQUIRES_REVIEW';result.canonicalReceipt=null;}}
 }
 return result;
 }finally{if(admissionHandle&&borrowed===undefined)disposeNativeBackendReleaseAdmission(admissionHandle);}
}
