import assert from 'node:assert/strict';
import { test } from 'node:test';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

async function subject(){let module:Record<string,unknown>={};try{module=await import(pathToFileURL(resolve(import.meta.dirname,'backend-hosted-recovery-faults.ts')).href);}catch(error){if((error as NodeJS.ErrnoException).code!=='ERR_MODULE_NOT_FOUND')throw error;}assert.equal(typeof module.verifyWorkerFaultRecovery,'function');return module as typeof import('./backend-hosted-recovery-faults');}
const school='10000000-0000-4000-8000-000000000001',actor='20000000-0000-4000-8000-000000000001',endpoint='https://abcdefghijklmnopqrst.supabase.co/functions/v1/cuevo-worker';
type Row=Record<string,unknown>;
async function fixture(mode:string,run:(input:Record<string,unknown>,ports:unknown,calls:string[])=>Promise<void>){
 let clock=Date.parse('2026-10-06T08:00:00Z'),number=0,state='PENDING',attempt=0,lease:string|null=null,leaseUntil:number|null=null,available=clock,controlState='IDLE',failureCount=0,nextAttempt=clock,wake:string|null=null,held=false,processed=false,lastError:string|null=null;
 const events:Record<string,Row>={},calls:string[]=[], input={schoolId:school,actorId:actor,endpoint,vaultSecretName:'cuevo_worker_owned',jobId:42,originalKey:'worker-activation:51:1:faults',body:{name:'Cuevo Reference Academy – Doha',countryCode:'QA',languages:['en','ar']}};
 const current=()=>({enabled:true,endpoint,vault_secret_name:mode==='foreign-control'?'foreign':input.vaultSecretName,allow_local:false,state:controlState,wake_id:wake,lease_expires_at:wake?new Date(clock+60000).toISOString():null,network_request_id:null,failure_count:failureCount,last_error_code:controlState==='BACKOFF'?'WORKER_REQUIRES_REVIEW':null,next_attempt_at:new Date(nextAttempt).toISOString(),last_requested_at:processed?new Date(clock).toISOString():null,last_started_at:processed?new Date(clock).toISOString():null,last_finished_at:processed||controlState==='BACKOFF'?new Date(clock).toISOString():null,last_processed_count:processed?1:0});
 const event=()=>({id:String(number).padStart(8,'0')+'-0000-4000-8000-000000000001',school_id:school,actor_id:actor,entity_id:school,entity_type:'school_operation',type:'school.updated',version:1,metadata:{command:'details.update'},deduplication_key:'owned-'+number,occurred_at:'2026-10-06T07:59:00Z',state,attempt_count:attempt,max_attempts:5,lease_token:lease,lease_until:leaseUntil?new Date(leaseUntil).toISOString():null,available_at:new Date(available).toISOString(),completed_at:processed?new Date(clock).toISOString():null,last_error_code:lastError,processed,audit:true,command_count:1});
 const operator=async(sql:string,args:unknown[]=[])=>{calls.push('operator:'+sql.split('\n')[0]);
  if(sql==='BEGIN'){held=true;return{rows:[]};}if(sql==='COMMIT'||sql==='ROLLBACK'){held=false;if(mode==='commit-unknown'&&sql==='COMMIT')throw Error('private-commit');return{rows:[]};}
  if(sql.includes('CUEVO_FAULT_CONTROL')){if(mode==='generation-locks'&&held&&sql.endsWith(' for update'))throw Error('Operator UPDATE lock would block the generation SHARE claim');return{rows:[current()]};}
  if(sql.includes('CUEVO_FAULT_BASELINE'))return{rows:[{pending:0,processing:0,failed:0,transportPrivate:true,analyticsDisabled:true,synthetic:true}]};
  if(sql.includes('CUEVO_FAULT_CRON'))return{rows:mode==='wrong-job'?[]:[{jobid:42,jobname:'cuevo-worker-recovery',schedule:'* * * * *',command:'select internal.request_worker_wake();',database:'postgres',username:'postgres',active:true}]};
  if(sql.includes('CUEVO_FAULT_OWNED_QUEUE'))return{rows:[{foreignWork:mode==='foreign-work'?1:0}]};
  if(sql.includes('CUEVO_FAULT_PRE_DUE_EVENT')){const beforeDue=clock<nextAttempt;if(mode==='early-backoff'&&controlState==='BACKOFF'){processed=true;state='COMPLETED';attempt=1;}if(mode==='cron-at-due'&&!beforeDue){processed=true;state='COMPLETED';attempt=1;controlState='IDLE';failureCount=0;}return{rows:[{...event(),beforeDue}]};}
  if(sql.includes('CUEVO_FAULT_EVENT')){if(mode==='early-backoff'&&controlState==='BACKOFF'){processed=true;state='COMPLETED';attempt=1;}return{rows:[event()]};}
  if(sql.includes('CUEVO_FAULT_DB_TIME'))return{rows:[{now:new Date(clock).toISOString()}]};
  if(sql.includes('CUEVO_FAULT_GENERATION')){wake=String(args[0]);controlState='REQUESTED';return{rows:[{injected:mode==='injection-unknown'?false:true}]};}
  if(sql.includes('request_worker_wake')){if(clock<nextAttempt)return{rows:[{requested:false}]};controlState='IDLE';failureCount=0;wake=null;state='COMPLETED';processed=true;attempt=1;return{rows:[{requested:true}]};}
  if(sql.includes('CUEVO_FAULT_BACKOFF'))return{rows:[{state:controlState,failureCount,lastErrorCode:'WORKER_REQUIRES_REVIEW',waitSeconds:30,future:clock<nextAttempt}]};
  if(sql.includes('CUEVO_FAULT_FINAL'))return{rows:[{pending:0,processing:0,transportPrivate:true,analyticsDisabled:true}]};
  throw Error('Unknown fixed operator SQL '+sql);
 };
 const worker=async(sql:string,args:unknown[]=[])=>{calls.push('worker:'+sql.split('\n')[0]);if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[]};
  if(sql.includes('CUEVO_FAULT_WORKER_IDENTITY'))return{rows:[{role:mode==='owner-worker'?'postgres':'cuevo_worker',sessionRole:'cuevo_worker',database:'postgres',restricted:true,ready:true}]};
  if(sql.includes('claim_outbox')){if(state==='COMPLETED'||clock<available||state==='PROCESSING'&&leaseUntil!==null&&clock<=leaseUntil)return{rows:[]};attempt++;lease=String(attempt).padStart(8,'0')+'-0000-4000-8000-000000000099';leaseUntil=clock+Number(args[1])*1000;state='PROCESSING';const r=event();return{rows:[{...r,id:mode==='foreign-claim'?'93000000-0000-4000-8000-000000000999':r.id}]};}
  if(sql.includes('process_learner_event')){if(args[1]!==lease||leaseUntil===null||clock>=leaseUntil){const e=Object.assign(Error('private-lease'),{code:mode==='stale-wrong-error'?'42501':'22023'});throw e;}state='COMPLETED';processed=true;lease=null;leaseUntil=null;return{rows:[{process_learner_event:mode==='malformed-processing'?{status:'ACKNOWLEDGED',extra:true}:{status:'ACKNOWLEDGED'}}]};}
  if(sql.includes('fail_outbox')){if(mode==='fail-unknown')return{rows:[{acknowledged:false}]};state='PENDING';available=clock+Number(args[3])*1000;lastError=String(args[2]);lease=null;leaseUntil=null;return{rows:[{acknowledged:true}]};}
  if(sql.includes('begin_worker_wake')){if(args[0]!==wake||mode==='admission-denied')return{rows:[{admitted:false}]};controlState='RUNNING';return{rows:[{admitted:true}]};}
  if(sql.includes('finish_worker_wake')){if(mode==='finish-unknown')return{rows:[{receipt:false}]};controlState='BACKOFF';failureCount=1;nextAttempt=clock+30000;wake=null;return{rows:[{receipt:true}]};}
  throw Error('Unknown fixed worker SQL '+sql);
 };
 const ports={operatorQuery:operator,workerQuery:worker,workerTlsVerified:true,command:async(_body:unknown,key:string)=>{calls.push('command:'+key);if(!events[key]){number++;events[key]={};state='PENDING';attempt=0;lease=null;leaseUntil=null;available=clock;processed=false;lastError=null;}return{id:school,schoolId:school,command:'details.update'};},admit:async()=>{calls.push('admit');},record:async(phase:string)=>{calls.push('record:'+phase);},now:()=>clock,pause:async()=>{clock+=1000;},isControlHeld:()=>held};
 await run(input,ports,calls);
}
test('fault recovery uses restricted worker lease expiry retry and real native review backoff with exact source identities',async()=>{const api=await subject();await fixture('normal',async(input,ports,calls)=>{const r=await api.verifyWorkerFaultRecovery(input,ports as import('./backend-hosted-recovery-faults').WorkerFaultRecoveryPorts);assert.equal(r.status,'FAULT_RECOVERY_VERIFIED');assert.equal(r.expiredLeaseRecoveryVerified,true);assert.equal(r.eventRetryVerified,true);assert.equal(r.dispatchBackoffVerified,true);assert.equal(r.hostedAcceptance,false);assert.equal(r.faultInjectionBasis,'EXACT_SYNTHETIC_REQUESTED_GENERATION');assert.equal(calls.filter(c=>c.startsWith('command:')).length,6);assert(calls.some(c=>c.includes('fail_outbox')));assert(calls.some(c=>c.includes('begin_worker_wake')));assert(calls.some(c=>c.includes('finish_worker_wake')));assert(!calls.some(c=>/update .*outbox|delete from|configure_worker_dispatch/.test(c)));});});
test('current release generation is required by real claims and wake admission throughout full fault verification',async()=>{const api=await subject();await fixture('normal',async(input,raw)=>{const ports=raw as import('./backend-hosted-recovery-faults').WorkerFaultRecoveryPorts,original=ports.workerQuery;let claims=0,begins=0;ports.workerQuery=async(sql,args=[])=>{if(sql.includes('claim_outbox')){claims++;assert.equal(args[2],'2');}if(sql.includes('begin_worker_wake')){begins++;assert.equal(args[1],'2');}return original(sql,args);};const result=await api.verifyWorkerFaultRecovery({...input,releaseGeneration:'2'},ports);assert.equal(result.status,'FAULT_RECOVERY_VERIFIED');assert(claims>=4);assert.equal(begins,1);});});
test('fault source guard permits generation claims while excluding concurrent wake and pause writers',async()=>{const api=await subject();await fixture('generation-locks',async(input,raw,calls)=>{const result=await api.verifyWorkerFaultRecovery({...input,releaseGeneration:'2'},raw as import('./backend-hosted-recovery-faults').WorkerFaultRecoveryPorts);assert.equal(result.status,'FAULT_RECOVERY_VERIFIED');assert.equal(calls.filter(call=>call.includes('CUEVO_FAULT_CONTROL')&&call.endsWith(' for key share')).length,3);assert.equal(calls.some(call=>call.includes('CUEVO_FAULT_CONTROL')&&call.endsWith(' for update')),false);});});
test('unknown worker authority foreign queue or claim identity refuse and preserve false proof',async()=>{const api=await subject();for(const selected of ['owner-worker','foreign-control','foreign-work','foreign-claim','wrong-job'])await fixture(selected,async(input,ports,calls)=>{const r=await api.verifyWorkerFaultRecovery(input,ports as import('./backend-hosted-recovery-faults').WorkerFaultRecoveryPorts);assert.equal(r.status,'REQUIRES_REVIEW');assert.equal(r.dispatchBackoffVerified,false);if(selected==='foreign-claim')assert(calls.includes('worker:ROLLBACK'));});});
test('uncertain lease failure malformed processing and unknown dispatch admission cannot manufacture proof',async()=>{const api=await subject();for(const selected of ['stale-wrong-error','fail-unknown','malformed-processing','admission-denied','finish-unknown','commit-unknown','injection-unknown'])await fixture(selected,async(input,ports)=>{const r=await api.verifyWorkerFaultRecovery(input,ports as import('./backend-hosted-recovery-faults').WorkerFaultRecoveryPorts);assert.equal(r.status,'REQUIRES_REVIEW');assert.equal(r.dispatchBackoffVerified,false);assert(r.originalKey);});});
test('foreign claim rejection rolls back before committing any worker attempt and natural waits never rewrite leases',async()=>{const api=await subject();await fixture('foreign-claim',async(input,ports,calls)=>{const r=await api.verifyWorkerFaultRecovery(input,ports as import('./backend-hosted-recovery-faults').WorkerFaultRecoveryPorts);assert.equal(r.status,'REQUIRES_REVIEW');const start=calls.indexOf('worker:BEGIN'),rollback=calls.indexOf('worker:ROLLBACK');assert(start>=0&&rollback>start);assert(!calls.slice(start,rollback).includes('worker:COMMIT'));assert(!calls.some(c=>/set lease_until|set available_at|set attempt_count|delete from/i.test(c)));});});
test('processing during the native backoff window cannot count as dispatch recovery',async()=>{const api=await subject();await fixture('early-backoff',async(input,ports)=>{const r=await api.verifyWorkerFaultRecovery(input,ports as import('./backend-hosted-recovery-faults').WorkerFaultRecoveryPorts);assert.equal(r.status,'REQUIRES_REVIEW');assert.equal(r.expiredLeaseRecoveryVerified,true);assert.equal(r.eventRetryVerified,true);assert.equal(r.dispatchBackoffVerified,false);});});
test('a Cron delivery that wins at the native due time remains valid recovery',async()=>{const api=await subject();await fixture('cron-at-due',async(input,ports)=>{const r=await api.verifyWorkerFaultRecovery(input,ports as import('./backend-hosted-recovery-faults').WorkerFaultRecoveryPorts);assert.equal(r.status,'FAULT_RECOVERY_VERIFIED');assert.equal(r.dispatchBackoffVerified,true);});});
