import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {createHash} from 'node:crypto';
import type {BackendProviderCliIdentity,BackendProviderLaunchAdmission,PreparedBackendProviderCli} from './backend-provider-cli';

// Actual small deployment-owner wrappers with controlled prepared execution.
// Full graph and physical container proof live in backend-provider-cli.test.ts.
function wrappers(){const path=resolve(import.meta.dirname,'backend-provider-deploy.ts'),source=ts.createSourceFile(path,readFileSync(path,'utf8'),ts.ScriptTarget.Latest,true);return ts.transpileModule(source.statements.filter(ts.isFunctionDeclaration).filter(n=>['prepareApiCli','apiCli'].includes(n.name?.text??'')).map(n=>n.getText(source)).join('\n')+'\n({prepareApiCli,apiCli})',{compilerOptions:{target:ts.ScriptTarget.ES2023,module:ts.ModuleKind.None}}).outputText;}
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
const expected={releaseSha:'a'.repeat(40),fingerprints:{apiArtifactSha256:'b'.repeat(64)},targets:{api:{teamId:'team_Cuevo',projectId:'prj_Api'}}};
const operation='c'.repeat(64),identity={sourceSha:expected.releaseSha,artifactSha256:expected.fingerprints.apiArtifactSha256,teamId:expected.targets.api.teamId,projectId:expected.targets.api.projectId,operationSha256:operation};
type ArtifactFile={path:string;bytes:Uint8Array};
type CliCreationInput={repoRoot:string;executorSourceSha:string;identity:BackendProviderCliIdentity;artifactFiles:ArtifactFile[];expiresAtMs:number;token:string;signal:AbortSignal};
type CliPreparationOptions=Pick<CliCreationInput,'executorSourceSha'|'expiresAtMs'|'token'|'signal'>&{operationSha256:string};
type PreparedCliPort={prepared:Pick<PreparedBackendProviderCli['prepared'],'identitySha256'>;run:PreparedBackendProviderCli['run']};
type CliWrappers={prepareApiCli:(root:string,artifact:{sha256:string;files:ArtifactFile[]},context:typeof expected,options:CliPreparationOptions)=>Promise<PreparedCliPort>;apiCli:(prepared:PreparedCliPort,context:typeof expected,token:string,operationSha256:string,signal:AbortSignal,admit:()=>Promise<BackendProviderLaunchAdmission>)=>Promise<string>};
function subject(create:(input:CliCreationInput)=>Promise<PreparedCliPort>){return runInNewContext(wrappers(),{createBackendProviderCli:create,readBackendRuntimeFingerprints:(v:unknown)=>v,hash,JSON,failure:()=>Error('Launch binding requires review.')}) as CliWrappers;}

test('deployment wrapper snapshots only admitted prebuilt bytes with exact identity before live launch admission',async()=>{const captured:{input?:CliCreationInput}={};let admitted=false,consumed=false,attempts=0;const controller=new AbortController(),port:PreparedCliPort={prepared:{identitySha256:hash(JSON.stringify(identity))},run:async(admit)=>{attempts++;const admission=await admit();assert.equal(admission.notAfterMs,2000);admission.consume();return{kind:'URL',url:'https://cuevo-api-fixture.vercel.app'};}};const api=subject(async(input)=>{assert.equal(admitted,false);captured.input=input;return port;}),artifact={sha256:identity.artifactSha256,files:[{path:'.vercel/output/config.json',bytes:Buffer.from('{"version":3}')},{path:'api/index.mjs',bytes:Buffer.from('not public input')}]};const prepared=await api.prepareApiCli('/prepared/root',artifact,expected,{executorSourceSha:'d'.repeat(40),token:'private-token-canary',operationSha256:operation,expiresAtMs:5000,signal:controller.signal});assert.ok(captured.input);const preparedInput=captured.input;assert.deepEqual(JSON.parse(JSON.stringify(preparedInput.identity)),identity);assert.equal(preparedInput.artifactFiles.length,1);assert.equal(preparedInput.artifactFiles[0].path,'.vercel/output/config.json');assert.equal(preparedInput.executorSourceSha,'d'.repeat(40));assert.equal(preparedInput.expiresAtMs,5000);assert.equal(await api.apiCli(prepared,expected,'private-token-canary',operation,controller.signal,async()=>{admitted=true;return{consume:()=>{consumed=true;},notAfterMs:2000};}),'https://cuevo-api-fixture.vercel.app');assert.equal(consumed,true);assert.equal(attempts,1);});

test('deployment wrapper refuses changed source artifact target operation or abort before prepared execution',async()=>{for(const mode of ['source','artifact','team','project','operation','abort']){let attempts=0;const api=subject(()=>{throw Error('Unexpected CLI preparation.');}),controller=new AbortController(),selected=structuredClone(expected);if(mode==='source')selected.releaseSha='d'.repeat(40);if(mode==='artifact')selected.fingerprints.apiArtifactSha256='e'.repeat(64);if(mode==='team')selected.targets.api.teamId='team_Foreign';if(mode==='project')selected.targets.api.projectId='prj_Foreign';if(mode==='abort')controller.abort();await assert.rejects(api.apiCli({prepared:{identitySha256:hash(JSON.stringify(identity))},run:async()=>{attempts++;return{kind:'URL',url:'https://cuevo-api-fixture.vercel.app'};}},selected,'private-token-canary',mode==='operation'?'f'.repeat(64):operation,controller.signal,async()=>({consume:()=>undefined,notAfterMs:2000})));assert.equal(attempts,0,mode);}});

test('deployment wrapper keeps unknown execution unavailable to provider confirmation',async()=>{const api=subject(()=>{throw Error('Unexpected CLI preparation.');});await assert.rejects(api.apiCli({prepared:{identitySha256:hash(JSON.stringify(identity))},run:async()=>({kind:'UNKNOWN'})},expected,'private-token-canary',operation,new AbortController().signal,async()=>({consume:()=>undefined,notAfterMs:2000})))});

test('API launch deadline includes the beginning of actual current official admission without extending thirty seconds',async()=>{
 const file=resolve(import.meta.dirname,'backend-provider-deploy.ts'),source=ts.createSourceFile(file,readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true);let callback:ts.ArrowFunction|undefined;
 const visit=(node:ts.Node)=>{if(ts.isCallExpression(node)&&node.expression.getText(source)==='apiCli'){const last=node.arguments.at(-1);if(last&&ts.isArrowFunction(last))callback=last;}ts.forEachChild(node,visit);};visit(source);assert.ok(callback);
 let now=1000,renewed=0,consumed=0,hostConsumed=0;const hostObservation:{target:string;officialBeganAt:number;observedAt:number}[]=[];const context={Date:{now:()=>now,parse:Date.parse},JSON,Math,prepared:{canonicalJson:JSON.stringify({expiresAt:new Date(100000).toISOString()})},expected:{},rollout:undefined,postureObservedAt:50000,admission:async()=>{renewed++;now+=31000;},inactive:async()=>undefined,observeHost:async(target:string,officialBeganAt:number):Promise<BackendProviderLaunchAdmission>=>{hostObservation.push({target,officialBeganAt,observedAt:now});return{notAfterMs:90000,consume:()=>{hostConsumed++;}};},live:()=>{consumed++;},recoveryLive:()=>undefined,validatePreparedBackendReleaseIntent:()=>undefined,failure:()=>Error('Current launch expired.')};
 const code=ts.transpileModule('('+callback!.getText(source)+')',{compilerOptions:{target:ts.ScriptTarget.ES2023,module:ts.ModuleKind.None}}).outputText;const admit=runInNewContext(code,context) as ()=>Promise<BackendProviderLaunchAdmission>;const result=await admit();assert.equal(renewed,1);assert.deepEqual(hostObservation,[{target:'api',officialBeganAt:1000,observedAt:32000}]);assert.equal(result.notAfterMs,31000);assert.throws(result.consume,/expired/);assert.equal(hostConsumed,1);assert.equal(consumed,1);
});
