import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createHash} from 'node:crypto';
import {canonicalReleaseExecutionJson} from './release-review';
import {EventEmitter} from 'node:events';
import {readFile} from 'node:fs/promises';
import {transformSync} from 'esbuild';
import {runInNewContext} from 'node:vm';
import {types as pgTypes} from 'pg';
import type {ActiveRuntimeRevalidation} from './backend-runtime-resume';

const sha='a'.repeat(40),tree='b'.repeat(40),project='abcdefghijklmnopqrst';
const hash=(value:unknown)=>createHash('sha256').update(canonicalReleaseExecutionJson(value)).digest('hex');
function saved(){const activation={status:'ACTIVATED_SIGNED_SOURCE_VERIFIED',sourceSha:sha,projectRef:project,runId:'51',runAttempt:1,packageSha256:'c'.repeat(64),runtimeSha256:'d'.repeat(64),apiDeploymentId:'dpl_fixture',edgeVersion:1,jobId:42,sourceProcessed:true,duplicateWakeDenied:true,originalCommandReplayed:true,recoveryScheduled:true,scheduledRecoveryVerified:true,configurationEvidenceObservedManual:true,sessionsClosed:true,keyOperation:'CONFIRMED',dispatchOperation:'CONFIRMED',probeEventId:'10000000-0000-4000-8000-000000000001',observedAt:'2026-10-07T12:00:00Z'};return{version:1,purpose:'CUEVO_PRIVATE_ACTIVE_RUNTIME_STATE',projectRef:project,phase:'CONFIRMED',identity:{sourceSha:sha,treeSha:tree,originalRunId:'51',originalRunAttempt:1,originalPackageSha256:'c'.repeat(64),runtimeSha256:'d'.repeat(64),apiDeploymentId:'dpl_fixture',apiUrl:'https://cuevo-fixture.vercel.app',edgeId:'edge_fixture',edgeVersion:1,activationId:'10000000-0000-4000-8000-000000000002',vaultSecretName:'cuevo_worker_10000000000040008000000000000002',endpoint:`https://${project}.supabase.co/functions/v1/cuevo-worker`,createdAt:'2026-10-07T11:59:00Z'},wakeKey:'e'.repeat(64),jobId:42,activation,cleanup:{status:activation.status,sourceSha:sha,projectRef:project,runId:'51',runAttempt:1,lockReleased:true,sessionsClosed:true,resultSha256:hash(activation),observedAt:'2026-10-07T12:00:01Z'}};}

test('resume public contract exports retain the single pure state owner',async()=>{
 const resume=await import('./backend-runtime-resume'),state=await import('../database/hosted-active-runtime-state');
 for(const key of ['activeRuntimeStateSchema','activeRuntimePublicQuery','readInstalledRuntimeMetadata','validateActiveRuntimeTransition'] as const)assert.equal(resume[key],state[key]);
});

test('native installed runtime observation binds original key provider and Cron without a write or reactivation',async t=>{
 const source=await readFile(new URL('./backend-runtime-resume.ts',import.meta.url),'utf8'),subject=await import('./backend-runtime-resume'),pure=await import('../database/hosted-active-runtime-state');assert.equal(typeof subject.revalidateActiveRuntime,'function');
 const compiled=transformSync(source,{loader:'ts',format:'cjs'}).code,state=saved(),metadata=subject.readInstalledRuntimeMetadata([{state:Object.fromEntries(Object.entries(state).filter(([key])=>key!=='wakeKey'))}],project),queries:string[]=[],requests:string[]=[],now=Date.parse('2026-10-07T12:01:00Z');
 const runtime={api:{CUEVO_DATABASE_TLS_CA:'fixture-ca'},edge:{CUEVO_WORKER_WAKE_KEY:'',CUEVO_WORKER_DATABASE_URL:'private-runtime'},runtimeSha256:'d'.repeat(64)};Object.assign(state,{runtimeConfig:{private:'originalconfiguration'}});let fault='',closes=0,preparations=0,disposals=0,currentReads=0;const handles=new WeakSet<object>();
 let controlState='IDLE',controlWake:string|null=null,controlLease:string|null=null,networkRequestId:unknown=null;
 const projectedControlSql=`/* CUEVO_ACTIVE_RUNTIME_CONTROL */ select enabled,endpoint,vault_secret_name,allow_local,state,wake_id,to_char(lease_expires_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') as lease_expires_at,network_request_id::text as network_request_id from internal.worker_dispatch_control where singleton`;
 const providerIdentity={sourceSha:sha,treeSha:tree,apiArtifactSha256:'1'.repeat(64),edgeArtifactSha256:'2'.repeat(64),denoLockSha256:'3'.repeat(64),runtimeSha256:'d'.repeat(64),teamId:'team_Cuevo',projectId:'prj_Api',originalRunId:'51',originalRunAttempt:1,originalPackageSha256:'c'.repeat(64)},providerState={version:1,purpose:'CUEVO_PRIVATE_PROVIDER_DEPLOYMENT_STATE',projectRef:project,operations:[{identity:providerIdentity,phases:[{name:'API_ENVIRONMENT',state:'CONFIRMED',receipt:{kind:'API_ENVIRONMENT',keysSha256:'4'.repeat(64),valuesSha256:'5'.repeat(64),variables:[{key:'CUEVO_DATABASE_TLS_CA',id:'env1',valueSha256:'6'.repeat(64)}]}},{name:'API_DEPLOYMENT',state:'CONFIRMED',receipt:{kind:'API_DEPLOYMENT',deploymentId:'dpl_fixture',url:'https://cuevo-fixture.vercel.app'}},{name:'EDGE_SECRETS',state:'CONFIRMED',receipt:{kind:'EDGE_SECRETS',valuesSha256:'7'.repeat(64),variables:[{name:'CUEVO_WORKER_DATABASE_URL',valueSha256:'8'.repeat(64)}]}},{name:'EDGE_DEPLOYMENT',state:'CONFIRMED',receipt:{kind:'EDGE_DEPLOYMENT',id:'edge_fixture',version:1}}]}]};
 class ControlledClient extends EventEmitter{connection={stream:{encrypted:true,authorized:true,getProtocol:()=> 'TLSv1.3',getPeerCertificate:()=>({raw:Buffer.from('fixture-peer')})}};async connect(){}async end(){closes++;}async query(sql:string){queries.push(sql);if(sql.includes('CUEVO_ACTIVE_RUNTIME_IDENTITY'))return{rows:[{operator:'postgres',role:'postgres',database:'postgres',ssl:true}]};if(sql.includes('pg_try_advisory_lock'))return{rows:[{locked:true}]};if(sql.includes('pg_advisory_unlock')&&fault==='unlock-throw')throw Error('PRIVATE unlock error');if(sql.includes('pg_advisory_unlock'))return{rows:[{released:fault!=='unlock'}]};if(sql.includes('CUEVO_ACTIVE_RUNTIME_ACTORS'))return{rows:[{peopleMatching:true,authMatching:true,currentMemberships:true}]};if(sql.includes('CUEVO_ACTIVE_RUNTIME_PROVIDER'))return{rows:[{decrypted_secret:canonicalReleaseExecutionJson(providerState)}]};if(sql.includes('CUEVO_ACTIVE_RUNTIME_READ'))return{rows:[{decrypted_secret:canonicalReleaseExecutionJson(state)}]};if(sql.includes('CUEVO_ACTIVE_RUNTIME_CONTROL'))return{rows:[{enabled:fault==='control-boolean'?'true':true,endpoint:metadata.endpoint,vault_secret_name:metadata.vaultSecretName,allow_local:false,state:controlState,wake_id:controlWake,lease_expires_at:controlLease===null?null:sql===projectedControlSql?controlLease:pgTypes.getTypeParser(1184,'text')(controlLease.replace('T',' ').replace('Z','+00')),network_request_id:networkRequestId}]};if(sql.includes('CUEVO_RUNTIME_RECOVERED_ROLES'))return{rows:[{allowed:fault!=='roles'}]};if(sql.includes('CUEVO_ACTIVE_RUNTIME_SOURCE'))return{rows:[{operator:'postgres',database:'postgres',ssl:true,transportPrivate:true,synthetic:true,currentActors:true,runtimeRoles:true,analyticsDisabled:true}]};if(sql.includes('CUEVO_ACTIVE_RUNTIME_KEY'))return{rows:[{matching:fault!=='key',count:1}]};if(sql.includes('CUEVO_ACTIVE_RUNTIME_CRON'))return{rows:[{jobid:42,jobname:'cuevo-worker-recovery',schedule:'* * * * *',command:'select internal.request_worker_wake();',database:'postgres',username:'postgres',active:true}]};throw Error('Unexpected query');}}
 const pureExports={...pure,activeRuntimeStateSchema:{parse:(value:unknown)=>pure.activeRuntimeStateSchema.parse(JSON.parse(JSON.stringify(value)))},publicActiveRuntimeStateSchema:{parse:(value:unknown)=>pure.publicActiveRuntimeStateSchema.parse(JSON.parse(JSON.stringify(value)))},readInstalledRuntimeMetadata:(value:unknown,projectRef:string)=>pure.readInstalledRuntimeMetadata(JSON.parse(JSON.stringify(value)),projectRef),validateActiveRuntimeTransition:(before:unknown,after:unknown,projectRef:string)=>pure.validateActiveRuntimeTransition(JSON.parse(JSON.stringify(before)),JSON.parse(JSON.stringify(after)),projectRef)};
 const dataApiSource=transformSync(await readFile(new URL('./data-api-configuration.ts',import.meta.url),'utf8'),{loader:'ts',format:'cjs'}).code,dataApiModule={exports:{} as Record<string,unknown>};
 const fakeRequire=(name:string)=>name==='./data-api-configuration'?dataApiModule.exports:name==='../database/hosted-runtime-rollout-session'?{openNativeRuntimeRolloutSession:()=>{throw Error('Legacy test cannot invoke currentgenerationowner');},readBoundedRuntimeResponse:async()=>{throw Error('Legacy owner cannot consume newtransport helper');}}:name==='../database/hosted-active-runtime-state'?pureExports:name==='node:fs/promises'?{readFile:async()=>await readFile(new URL('../../supabase/seed/identities.json',import.meta.url))}:name==='pg'?{Client:ControlledClient}:name==='node:tls'?{checkServerIdentity:()=>undefined}:name==='./release-review'?{canonicalReleaseExecutionJson:(value:unknown)=>canonicalReleaseExecutionJson(JSON.parse(JSON.stringify(value)))}:name==='./backend-release-admission'?{prepareNativeBackendReleaseAdmission:async()=>{preparations++;const handle={};handles.add(handle);return handle;},readNativeBackendReleaseAdmission:async(handle:object,input:{expected:unknown})=>{assert.ok(handles.has(handle));currentReads++;return{expected:input.expected,observedAt:new Date(now).toISOString(),approval:{packageSha256:'1'.repeat(64)},provenance:'OFFICIAL_GITHUB_AND_VERIFIED_GIT_SOURCE'};},disposeNativeBackendReleaseAdmission:(handle:object)=>{assert.ok(handles.has(handle));assert.ok(closes>0);handles.delete(handle);disposals++;}}:name==='./backend-release-contracts'?{validatePreparedBackendReleaseIntent:(value:unknown)=>value}:name==='./backend-provider-deploy'?{prepareHostedRuntimeRecipients:()=>runtime}:name==='../database/hosted-migration-provider'?{readHostedMigrationProvider:async()=>({observedAtMs:now}),requireCurrentHostedMigrationEndpoint:()=>({kind:'direct',host:`db.${project}.supabase.co`})}:requireBuiltin(name);
 function requireBuiltin(name:string){return (globalThis as unknown as {testRequire:(name:string)=>unknown}).testRequire(name);}
 const {createRequire}=await import('node:module');Object.assign(globalThis,{testRequire:createRequire(import.meta.url)});
 const exports:Record<string,unknown>={},context={require:fakeRequire,exports,module:{exports},URL,Buffer,Date:class extends Date{static now(){return now;}},AbortSignal,fetch:async(url:string,options:RequestInit)=>{const target=new URL(url);if(target.protocol!=='https:'||target.username||target.password||target.hash||target.port)throw Error('Unexpected provider test URL');requests.push(options.method+':'+url);assert.equal(options.method,'GET');if(target.pathname.endsWith('/postgrest')){const response=Response.json({db_schema:''});Object.defineProperty(response,'url',{value:url});return response;}if(target.origin==='https://api.vercel.com'&&target.pathname==='/v10/projects/prj_Api/env'&&target.search==='?teamId=team_Cuevo&decrypt=true')return Response.json({envs:[{key:'CUEVO_DATABASE_TLS_CA',value:fault==='env'?'wrong':'fixture-ca',target:['preview'],type:'encrypted',gitBranch:null}]});if(target.origin==='https://api.vercel.com'&&target.pathname==='/v13/deployments/dpl_fixture'&&target.search==='?teamId=team_Cuevo')return Response.json({id:'dpl_fixture',projectId:fault==='provider'?'prj_Foreign':'prj_Api',ownerId:'team_Cuevo',url:'cuevo-fixture.vercel.app',readyState:'READY',target:'preview',meta:{cuevoCommitSha:sha,cuevoArtifactSha256:'1'.repeat(64),cuevoProviderOperation:hash(providerIdentity)}});if(target.origin==='https://api.supabase.com'&&target.pathname==='/v1/projects/'+project+'/secrets'&&target.search==='')return Response.json([{name:'CUEVO_WORKER_WAKE_KEY',value:createHash('sha256').update(state.wakeKey).digest('hex')},{name:'CUEVO_WORKER_DATABASE_URL',value:createHash('sha256').update('private-runtime').digest('hex')}]);if(target.origin==='https://api.supabase.com'&&target.pathname==='/v1/projects/'+project+'/functions/cuevo-worker'&&target.search==='')return Response.json({id:'edge_fixture',version:1,slug:'cuevo-worker',status:'ACTIVE',verify_jwt:false});throw Error('Unexpected provider test URL');},Response,TextDecoder,setTimeout,clearTimeout};
 for(const url of ['https://api.vercel.com.evil.invalid/v13/deployments/dpl_fixture?teamId=team_Cuevo','https://evil.invalid/path?next=api.vercel.com','https://evil.invalid/env?teamId=team_Cuevo&decrypt=true','https://api.vercel.com/v13/deployments/dpl_fixture?teamId=team_Foreign','https://api.supabase.com/v1/projects/'+project+'/secrets?foreign=1'])await assert.rejects(context.fetch(url,{method:'GET'}));
 runInNewContext(dataApiSource,{...context,module:dataApiModule,exports:dataApiModule.exports});runInNewContext(compiled,context);const run=context.module.exports.revalidateActiveRuntime as (value:unknown)=>Promise<ActiveRuntimeRevalidation>;
 const input={repoRoot:'C:/fixture',expected:{releaseSha:sha,treeSha:tree,releaseRunId:'91',runAttempt:1,installedRuntime:metadata,targets:{api:{teamId:'team_Cuevo',projectId:'prj_Api'},supabase:{projectRef:project}},fingerprints:{migrationEndpointSha256:hash({projectRef:project,kind:'direct',host:`db.${project}.supabase.co`,port:5432,database:'postgres'}),apiArtifactSha256:'1'.repeat(64),edgeArtifactSha256:'2'.repeat(64),denoLockSha256:'3'.repeat(64)}},preparedApproval:{sha256:'1'.repeat(64),canonicalJson:JSON.stringify({expiresAt:new Date(now+3600000).toISOString()})},githubToken:'fixture-github',providerToken:'fixture-provider-token',vercelToken:'fixture-vercel-token',runtimeConfig:{},operatorDatabaseUrl:`postgresql://postgres@db.${project}.supabase.co:5432/postgres?sslmode=verify-full`,operatorPassword:'fixture-operator'};const result=await run(input);
 const recover=context.module.exports.readActiveRuntimeConfiguration as (value:unknown)=>Promise<{runtimeConfig:unknown;original:unknown}>;const expected=input.expected as typeof input.expected&{executionScope:string};expected.executionScope='installed-runtime';const recovered=await recover({repoRoot:input.repoRoot,expected,preparedApproval:input.preparedApproval,githubToken:input.githubToken,operatorDatabaseUrl:input.operatorDatabaseUrl,operatorPassword:input.operatorPassword,certificate:'-----BEGIN CERTIFICATE-----fixture-----END CERTIFICATE-----'});assert.deepEqual(JSON.parse(JSON.stringify(recovered.runtimeConfig)),{private:'originalconfiguration'});const beforeClose=closes;fault='unlock-throw';await assert.rejects(recover({repoRoot:input.repoRoot,expected,preparedApproval:input.preparedApproval,githubToken:input.githubToken,operatorDatabaseUrl:input.operatorDatabaseUrl,operatorPassword:input.operatorPassword,certificate:'-----BEGIN CERTIFICATE-----fixture-----END CERTIFICATE-----'}),error=>!String(error).includes('PRIVATE'));assert.equal(closes,beforeClose+1);fault='';
 assert.equal(result.status,'INSTALLED_RUNTIME_REVALIDATED');assert.equal(queries.some(sql=>/\b(?:insert|update|alter|create|configure_worker|request_worker|cron.schedule)\b/i.test(sql)),false);assert.equal(requests.some(value=>value.startsWith('POST:')),false);for(const mode of ['key','roles','env','provider','unlock']){fault=mode;assert.equal((await run(input)).status,'REQUIRES_REVIEW',mode);}fault='';state.phase='CONFIGURED';assert.equal((await run(input)).status,'REQUIRES_REVIEW');state.phase='CONFIRMED';
 await t.test('native pg int8 decimal request IDs admit installed state without Number conversion',async()=>{
  for(const decimal of ['1','9007199254740993','9223372036854775807']){
   networkRequestId=pgTypes.getTypeParser(20,'text')(decimal);const beforeCloses=closes,observed=await run(input);
   assert.equal(observed.status,'INSTALLED_RUNTIME_REVALIDATED',decimal);assert.equal(closes,beforeCloses+1);
   assert.deepEqual(JSON.parse(JSON.stringify(observed.original)),metadata);
   assert.equal((observed.activation as {packageSha256:string}).packageSha256,'c'.repeat(64));
  }
 });
 await t.test('REQUESTED and RUNNING keep native lease time and nullable request ID semantics',async()=>{
  controlWake='10000000-0000-4000-8000-000000000003';controlLease='2026-10-07T12:02:00.123456Z';
  const nativeLease=pgTypes.getTypeParser(1184,'text')(controlLease.replace('T',' ').replace('Z','+00'));assert.ok(nativeLease instanceof Date);assert.equal(nativeLease.toISOString(),'2026-10-07T12:02:00.123Z');
  for(const nextState of ['REQUESTED','RUNNING'])for(const requestId of [null,'9223372036854775807']){
   controlState=nextState;networkRequestId=requestId;assert.equal((await run(input)).status,'INSTALLED_RUNTIME_REVALIDATED',nextState+':'+requestId);
  }
  controlState='IDLE';controlWake=null;controlLease=null;networkRequestId=null;
 });
 await t.test('malformed out-of-range and numeric request IDs remain review states',async()=>{
  for(const requestId of ['', '0','-1','+1','01',' 1','1 ','1.0','1e3','9223372036854775808','99999999999999999999',1,1.5,9007199254740992,true,{},NaN,Infinity]){
   networkRequestId=requestId;const beforeCloses=closes;
   assert.equal((await run(input)).status,'REQUIRES_REVIEW',JSON.stringify(requestId));assert.equal(closes,beforeCloses+1);
  }
  networkRequestId=null;
 });
 await t.test('expired leases missing wake context and non-confirmed authority remain refused',async()=>{
  controlState='REQUESTED';controlWake='10000000-0000-4000-8000-000000000003';networkRequestId='9007199254740993';
  for(const expired of ['2026-10-07T12:00:59.999999Z','2026-10-07T12:01:00.000000Z']){controlLease=expired;assert.equal((await run(input)).status,'REQUIRES_REVIEW',expired);}
  controlLease='2026-10-07T12:02:00.000000Z';controlWake=null;assert.equal((await run(input)).status,'REQUIRES_REVIEW');
  controlWake='10000000-0000-4000-8000-000000000003';controlState='IDLE';assert.equal((await run(input)).status,'REQUIRES_REVIEW');
  controlState='RUNNING';state.phase='CONFIGURED';assert.equal((await run(input)).status,'REQUIRES_REVIEW');state.phase='CONFIRMED';
  controlState='IDLE';controlWake=null;controlLease=null;networkRequestId=null;
 });
 await t.test('malformed native lease and string boolean results do not acquire authority',async()=>{
  controlState='RUNNING';controlWake='10000000-0000-4000-8000-000000000003';networkRequestId='1';
  for(const malformed of ['not-a-date','2026-10-07','2026-10-07T12:02:00','2026-13-07T12:02:00Z','infinity']){controlLease=malformed;assert.equal((await run(input)).status,'REQUIRES_REVIEW',malformed);}
  controlState='IDLE';controlWake=null;controlLease=null;networkRequestId=null;fault='control-boolean';assert.equal((await run(input)).status,'REQUIRES_REVIEW');fault='';
 });
 const priorPrep=preparations,priorDispose=disposals,priorReads=currentReads;assert.equal((await run(input)).status,'INSTALLED_RUNTIME_REVALIDATED');assert.equal(preparations-priorPrep,1);assert.equal(disposals-priorDispose,1);assert.ok(currentReads-priorReads>=2);
 assert.ok(queries.filter(sql=>sql.includes('CUEVO_ACTIVE_RUNTIME_CONTROL')).every(sql=>sql===projectedControlSql));
 assert.equal(queries.some(sql=>/\b(?:insert|update|alter|create|configure_worker|request_worker|cron.schedule)\b/i.test(sql)),false);assert.equal(requests.some(value=>value.startsWith('POST:')),false);
});

test('current configuration and initial-generation proof reuse their opaque owner through session cleanup and deny borrowed null',async()=>{
 const source=await readFile(new URL('./backend-runtime-resume.ts',import.meta.url),'utf8'),compiled=transformSync(source,{loader:'ts',format:'cjs'}).code,pure=await import('../database/hosted-active-runtime-state'),{createRequire}=await import('node:module'),nativeRequire=createRequire(import.meta.url);
 for(const phase of ['configuration','initial']as const)for(const borrowed of [false,true,'null']as const){const events:string[]=[],handles=new WeakSet<object>(),prepared={sha256:'c'.repeat(64),canonicalJson:JSON.stringify({expiresAt:'2099-01-01T00:00:00Z'})},config={private:'unchanged'},state={projectRef:project,original:{phase:'CONFIRMED'},current:{basis:'ORIGINAL_ACTIVATION',identity:{sourceSha:sha,treeSha:tree,generation:'1'},operationSha256:'d'.repeat(64),runtimeConfigurationSha256:pure.runtimeReleaseStateSha256(config),confirmationEvidence:null},pending:null,currentRuntimeConfiguration:config};let closed=false,openHandle:object|undefined;
  const admission={prepareNativeBackendReleaseAdmission:async()=>{events.push('prepare');const handle=Object.freeze({});handles.add(handle);return handle;},readNativeBackendReleaseAdmission:async(handle:object)=>{assert.ok(handles.has(handle));events.push('read');return{};},disposeNativeBackendReleaseAdmission:(handle:object)=>{assert.ok(handles.has(handle));assert.equal(closed,true);handles.delete(handle);events.push('dispose');}};
  const session={signal:new AbortController().signal,refresh:async()=>{await admission.readNativeBackendReleaseAdmission(openHandle!);events.push('refresh');},readState:async()=>state,verifySignedExecution:async()=>{events.push('proof');return{positiveWakeVerified:true,duplicateWakeDenied:true,staleGenerationDenied:true,originalSourcePreserved:true,sourceProcessed:true,scheduledRecoveryVerified:true};},persistState:async(value:typeof state)=>{events.push('persist');Object.assign(state,value);},close:async()=>{closed=true;events.push('close');return{lockReleased:true,sessionClosed:true};}};
  const modules:Record<string,unknown>={'./release-review':{canonicalReleaseExecutionJson:(v:unknown)=>canonicalReleaseExecutionJson(JSON.parse(JSON.stringify(v)))},'./backend-release-admission':admission,'./backend-release-contracts':{validatePreparedBackendReleaseIntent:()=>prepared,runtimeRolloutBindingSchema:{parse:(v:unknown)=>v}},'../database/hosted-active-runtime-state':{...pure,runtimeReleasePublicState:(value:unknown)=>JSON.parse(JSON.stringify(value)),runtimeReleaseStateSha256:(value:unknown)=>pure.runtimeReleaseStateSha256(JSON.parse(JSON.stringify(value)))},'./backend-provider-deploy':{},'../database/hosted-migration-provider':{},'../database/hosted-runtime-role-membership':{},'../database/hosted-provider-state':{},'../database/hosted-runtime-rollout-session':{openNativeRuntimeRolloutSession:async(_input:unknown,handle:object)=>{events.push('open');assert.ok(handles.has(handle));openHandle=handle;return session;},readBoundedRuntimeResponse:async()=>''},'./data-api-configuration':{observeDisabledDataApiConfiguration:async(_input:unknown,current:()=>Promise<unknown>)=>{await current();await current();return{purpose:'controlled-current-configuration',effectAuthority:false,hostedAcceptance:false};}}};
  const exports:Record<string,unknown>={},context={exports,module:{exports},require:(name:string)=>modules[name]??nativeRequire(name),URL,Buffer,Date,AbortSignal};runInNewContext(compiled,context);const input={repoRoot:'fixture',expected:{executionScope:phase==='configuration'?'installed-runtime':'complete-backend',releaseSha:sha,treeSha:tree,currentRuntime:{current:{generation:'1'}}},preparedApproval:prepared,githubToken:'fixture-gh',providerToken:'fixture-provider',syntheticPassword:'private-synthetic-password',operator:{databaseUrl:'postgresql://fixture',password:'private-operator',certificate:{path:'fixture',sha256:'e'.repeat(64)}}};if(phase==='configuration')delete(input as{syntheticPassword?:string}).syntheticPassword;let outer:object|null|undefined;if(borrowed===true){outer=Object.freeze({});handles.add(outer);}else if(borrowed==='null')outer=null;
  const fn=context.module.exports[phase==='configuration'?'readCurrentRuntimeConfiguration':'verifyInitialRuntimeGeneration'] as(value:unknown,handle?:unknown)=>Promise<unknown>;if(borrowed==='null'){await assert.rejects(fn(input,outer));assert.equal(events.includes('prepare'),false);assert.equal(events.includes('proof'),false);}else{const result=await fn(input,outer);assert.ok(result);assert.equal(events.filter(e=>e==='prepare').length,borrowed?0:1);assert.equal(events.filter(e=>e==='dispose').length,borrowed?0:1);assert.ok(events.indexOf('open')<events.indexOf('close'));if(!borrowed)assert.ok(events.indexOf('close')<events.indexOf('dispose'));else assert.ok(handles.has(outer!));if(phase==='initial'){assert.ok(events.filter(e=>e==='read').length>=4);assert.equal(events.filter(e=>e==='proof').length,1);}}}
});
