import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { z } from 'zod';
import { canonicalReleaseExecutionJson } from './release-review';
import { captureCanonicalSourceContext } from './canonical-source-jobs';
import { ciDatabaseJob } from './verification-workflows';
import { readSingleJsonArchive } from './single-json-archive';
import { createGithubCodeqlArtifactReader, type GithubArtifactReader } from './staging-security';
import { parseHostedChildCatalogueReceipt } from '../database/hosted-child-catalogue-reference';
import { originalChildCatalogueReferenceSchema } from '../database/hosted-original-child-recovery';
import { readCanonicalMigrationSources, readHistoricalMigrationSources } from '../database/hosted-migration-plan';
import { replayPlan } from '../database/replay-plan';

const fail=()=>Error('Original child catalogue producer admission requires review; contents withheld.');
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),same=(a:unknown,b:unknown)=>canonicalReleaseExecutionJson(a)===canonicalReleaseExecutionJson(b);
const sha=z.string().regex(/^[a-f0-9]{40}$/),positive=z.number().int().positive().safe(),id=z.string().regex(/^[1-9][0-9]*$/).refine(value=>Number.isSafeInteger(Number(value))),date=z.iso.datetime({offset:true});
const expectedSchema=z.object({repoRoot:z.string().min(1).max(4096),repository:z.literal('attaulhaq0/Cuevo'),sourceSha:sha,treeSha:sha,ciRunId:id,ciRunAttempt:positive}).strict();
const runSchema=z.object({id:positive,run_attempt:positive,head_sha:sha,head_branch:z.literal('main'),event:z.literal('push'),path:z.literal('.github/workflows/ci.yml'),status:z.enum(['queued','in_progress','completed']),conclusion:z.string().nullable(),repository:z.object({full_name:z.literal('attaulhaq0/Cuevo')})});
const stepSchema=z.object({name:z.string(),number:positive,status:z.literal('completed'),conclusion:z.string().nullable(),started_at:date.nullable(),completed_at:date.nullable()});
const jobSchema=z.object({id:positive,name:z.literal('database-checks'),run_id:positive,run_attempt:positive,head_sha:sha,head_branch:z.literal('main'),status:z.literal('completed'),conclusion:z.literal('success'),started_at:date,completed_at:date,steps:z.array(stepSchema).min(1).max(100)});
const artifactSchema=z.object({id:positive,name:z.string(),size_in_bytes:positive.max(2*1024*1024),expired:z.literal(false),digest:z.string().regex(/^sha256:[a-f0-9]{64}$/),created_at:date,expires_at:date,workflow_run:z.object({id:positive,head_sha:sha,head_branch:z.literal('main')})});
const snapshot=(value:unknown)=>JSON.parse(canonicalReleaseExecutionJson(value)) as unknown;
/** A seconds-only GitHub upper bound names its whole second. Preserve exact
 * receipt clocks and compare fractional official timestamps at their precision. */
const afterOfficialUpperBound=(actual:string,official:string)=>/\.\d+(?:Z|[+-]\d{2}:\d{2})$/.test(official)?Date.parse(actual)>Date.parse(official):Math.floor(Date.parse(actual)/1000)>Math.floor(Date.parse(official)/1000);
const producerFiles=['scripts/database/hosted-child-catalogue-producer.ts','scripts/database/hosted-child-catalogue-reference.ts','scripts/database/hosted-child-catalogue-bootstrap.sql','scripts/database/hosted-schema-catalogue.ts','scripts/database/replay-plan.ts','scripts/database/unknown-prefix-catalogue-policy.json'] as const;
/** Acquires one immutable small artifact. Refresh checks original metadata/expiry only. Native SQL authority remains elsewhere. */
export async function readChildCatalogueReferenceAndGuard(value:unknown,github:(path:string)=>Promise<unknown>,artifact:GithubArtifactReader){
 try{const expected=expectedSchema.parse(snapshot(value)),context=captureCanonicalSourceContext(expected.repoRoot,expected.sourceSha,expected.treeSha),runPath=`actions/runs/${expected.ciRunId}`,jobsPath=`${runPath}/attempts/${expected.ciRunAttempt}/jobs?per_page=100`,artifactPath=`${runPath}/artifacts?per_page=100`;
  const source=(path:string)=>context.git(['show',expected.sourceSha+':'+path]);
  const yaml=createRequire(import.meta.url)('js-yaml') as {load(text:string):unknown},workflow=z.object({jobs:z.record(z.string(),z.unknown())}).parse(yaml.load(source('.github/workflows/ci.yml').toString('utf8')));if(!same(workflow.jobs['database-checks'],ciDatabaseJob))throw fail();
  const fingerprints={producerSha256:hash(canonicalReleaseExecutionJson(producerFiles.filter(path=>!path.endsWith('bootstrap.sql')).map(path=>({path,sha256:hash(source(path))})))),bootstrapSha256:hash(source('scripts/database/hosted-child-catalogue-bootstrap.sql')),sourceLockSha256:hash(source('package-lock.json'))};
  context.git(['merge-base','--is-ancestor','1a493ad735798bb6d3fa0ffaabc779e62149ac37',expected.sourceSha]);
  const baseline=readHistoricalMigrationSources(expected.repoRoot,'1a493ad735798bb6d3fa0ffaabc779e62149ac37','a207a7ec44dd29d61adc0490b85fedbf1e696fcd'),current=readCanonicalMigrationSources({repoRoot:expected.repoRoot,sourceSha:expected.sourceSha,treeSha:expected.treeSha}),plan=replayPlan(baseline),names=[...plan.before,plan.prerequisite,...plan.remaining].slice(0,144),rows=names.map(name=>baseline.find(row=>row.name===name)!),currentByName=new Map(current.sources.map(row=>[row.name,row.bytes]));if(rows.some(row=>!currentByName.has(row.name)||hash(currentByName.get(row.name)!)!==hash(row.bytes)))throw fail();
  const sourceInventorySha256=hash(canonicalReleaseExecutionJson(rows.map(row=>({name:row.name,sha256:hash(row.bytes)}))));
  const observeCurrent=async()=>{const main=z.object({object:z.object({type:z.literal('commit'),sha})}).parse(snapshot(await github('git/ref/heads/main'))),commit=z.object({sha,commit:z.object({tree:z.object({sha}),verification:z.object({verified:z.literal(true),reason:z.literal('valid')})})}).parse(snapshot(await github('commits/'+expected.sourceSha))),run=runSchema.parse(snapshot(await github(runPath)));if(main.object.sha!==expected.sourceSha||commit.sha!==expected.sourceSha||commit.commit.tree.sha!==expected.treeSha||run.id!==Number(expected.ciRunId)||run.run_attempt!==expected.ciRunAttempt||run.head_sha!==expected.sourceSha||(run.status==='completed'?!['success','failure'].includes(run.conclusion??''):run.conclusion!==null))throw fail();const{status:_status,conclusion:_conclusion,...stable}=run;void _status;void _conclusion;return stable;};
  const readJob=async()=>{const all:Record<string,unknown>[]=[],ids=new Set<number>();let total:number|undefined;for(let page=1;page<=10;page++){const response=z.object({total_count:z.number().int().nonnegative().max(1000),jobs:z.array(z.object({id:positive,name:z.string()}).passthrough()).max(100)}).parse(snapshot(await github(`${jobsPath}&page=${page}`)));if(total!==undefined&&response.total_count!==total)throw fail();total=response.total_count;for(const item of response.jobs){if(ids.has(item.id))throw fail();ids.add(item.id);all.push(item);}if(all.length===total)break;if(response.jobs.length!==100||all.length>total||page===10)throw fail();}const selected=all.filter(row=>row.name==='database-checks');if(all.length!==total||selected.length!==1)throw fail();const job=jobSchema.parse(selected[0]);if(job.run_id!==Number(expected.ciRunId)||job.run_attempt!==expected.ciRunAttempt||job.head_sha!==expected.sourceSha||Date.parse(job.started_at)>Date.parse(job.completed_at)||Date.parse(job.completed_at)>Date.now())throw fail();
   const names=ciDatabaseJob.steps.map(step=>'name'in step?step.name:'Run '+('uses'in step?step.uses:step.run)),authored:string[]=[];for(const[index,step]of job.steps.entries()){if(index&&step.number<=job.steps[index-1].number||new Set(job.steps.map(row=>row.name)).size!==job.steps.length)throw fail();if(names.includes(step.name)){if(step.conclusion!=='success')throw fail();authored.push(step.name);}else if(['Set up job','Complete job'].includes(step.name)){if(step.conclusion!=='success')throw fail();}else if(!['Post Run actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1','Post Run actions/setup-node@820762786026740c76f36085b0efc47a31fe5020','Post Retain exact safe database lane','Post Retain exact source child144 catalogue reference','Post Retain minimized source child144 failure'].includes(step.name)||!['success','skipped'].includes(step.conclusion??''))throw fail();}if(!same(names,authored))throw fail();return job;};
  const readArtifact=async(job:z.infer<typeof jobSchema>)=>{const page=z.object({total_count:z.number().int().nonnegative().max(100),artifacts:z.array(z.object({id:positive,name:z.string()}).passthrough()).max(100)}).parse(snapshot(await github(artifactPath)));if(page.total_count!==page.artifacts.length||new Set(page.artifacts.map(row=>row.id)).size!==page.artifacts.length)throw fail();const selected=page.artifacts.filter(row=>row.name===`cuevo-child144-catalogue-${expected.ciRunId}-${expected.ciRunAttempt}`);if(selected.length!==1)throw fail();const a=artifactSchema.parse(selected[0]),retention=job.steps.find(row=>row.name==='Retain exact source child144 catalogue reference');if(a.workflow_run.id!==Number(expected.ciRunId)||a.workflow_run.head_sha!==expected.sourceSha||Date.parse(a.expires_at)<=Date.now()||!retention?.started_at||!retention.completed_at||Date.parse(a.created_at)<Date.parse(retention.started_at)||afterOfficialUpperBound(a.created_at,retention.completed_at))throw fail();return a;};
  const currentRun=await observeCurrent(),job=await readJob(),original=await readArtifact(job),bytes=await artifact(original.id);if(bytes.byteLength!==original.size_in_bytes)throw fail();const decoded=await readSingleJsonArchive(bytes,{archiveSha256:original.digest.slice(7),fileName:'reference.json',maximumJsonBytes:49152}),receipt=parseHostedChildCatalogueReceipt(decoded.value),producer=job.steps.find(row=>row.name==='Build exact source child144 catalogue reference');
  if(!producer?.started_at||!producer.completed_at||receipt.sourceSha!==expected.sourceSha||receipt.treeSha!==expected.treeSha||receipt.runId!==expected.ciRunId||receipt.runAttempt!==expected.ciRunAttempt||receipt.sourceInventorySha256!==sourceInventorySha256||Object.entries(fingerprints).some(([key,value])=>receipt[key as keyof typeof fingerprints]!==value)||Date.parse(receipt.startedAt)<Date.parse(producer.started_at)||afterOfficialUpperBound(receipt.cleanupCompletedAt,producer.completed_at))throw fail();
  const reference=originalChildCatalogueReferenceSchema.parse({version:1,purpose:'CUEVO_CHILD144_CATALOGUE_REFERENCE',repository:expected.repository,sourceSha:expected.sourceSha,treeSha:expected.treeSha,baselineSourceSha:receipt.baselineSourceSha,baselineTreeSha:receipt.baselineTreeSha,appliedMigrationCount:144,migrationRowsSha256:receipt.migrationRowsSha256,querySha256:receipt.querySha256,policySha256:receipt.policySha256,artifactSha256:original.digest.slice(7),artifactId:String(original.id),runId:expected.ciRunId,runAttempt:expected.ciRunAttempt,createdAt:original.created_at,catalogueSummary:receipt.catalogueSummary,receiptSha256:decoded.jsonSha256,producerJobId:String(job.id)});
  let poisoned=false,refreshing=false;
  const assertOriginalValidity=()=>{try{if(poisoned||Date.now()>=Date.parse(original.expires_at))throw fail();context.finalMetadata();}catch{poisoned=true;throw fail();}};
  const refreshOriginalMetadata=async()=>{if(poisoned||refreshing){poisoned=true;throw fail();}refreshing=true;try{if(!same(currentRun,await observeCurrent())||!same(job,await readJob())||!same(original,await readArtifact(job)))throw fail();assertOriginalValidity();}catch{poisoned=true;throw fail();}finally{refreshing=false;}};await refreshOriginalMetadata();return{reference,summary:receipt.catalogueSummary,receipt,assertOriginalValidity,refreshOriginalMetadata};
 }catch{throw fail();}
}
export async function readOriginalChildCatalogueReference(value:unknown){
 try{const input=expectedSchema.extend({githubToken:z.string().min(1).max(24576).regex(/^[\x21-\x7e]+$/)}).strict().parse(snapshot(value)),{githubToken,...expected}=input;
  const github=async(path:string)=>{const signal=AbortSignal.timeout(15000),url=`https://api.github.com/repos/${input.repository}/${path}`,response=await fetch(url,{method:'GET',redirect:'error',credentials:'omit',cache:'no-store',headers:{Authorization:`Bearer ${githubToken}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'},signal});if(response.status!==200||response.redirected||response.url&&response.url!==url||!response.body||!/^application\/json(?:;|$)/i.test(response.headers.get('content-type')??''))throw fail();const length=response.headers.get('content-length');if(length!==null&&(!/^[0-9]+$/.test(length)||Number(length)>1024*1024))throw fail();const reader=response.body.getReader(),parts:Uint8Array[]=[];let size=0;
   try{for(;;){if(signal.aborted)throw fail();const part=await reader.read();if(signal.aborted)throw fail();if(part.done)break;size+=part.value.byteLength;if(size>1024*1024)throw fail();parts.push(part.value);}return JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(Buffer.concat(parts))) as unknown;}finally{void reader.cancel().catch(()=>undefined);try{reader.releaseLock();}catch{/* Active cancellation owns cleanup. */}}
  };
  return await readChildCatalogueReferenceAndGuard(expected,github,createGithubCodeqlArtifactReader(input.repository,githubToken));
 }catch{throw fail();}
}
