import {createHash} from 'node:crypto';
import {prepareBackendReleaseIntent} from './backend-release-contracts';
import {canonicalReleaseExecutionJson} from './release-review';
const sha='a'.repeat(40),tree='b'.repeat(40),base='c'.repeat(40),project='abcdefghijklmnopqrst',wakeKey='d'.repeat(64),created='2026-10-07T12:00:00Z',execution='2026-10-07T12:01:00Z',closed='2026-10-07T12:01:01Z',now=Date.parse('2026-10-08T12:00:00Z');
const rawHash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),hash=(value:unknown)=>rawHash(canonicalReleaseExecutionJson(value)),bytes=(value:unknown)=>Buffer.from(canonicalReleaseExecutionJson(value)+'\n');
export function originalWorkerExportFixture(){
 const fingerprints={sourceManifestSha256:'1'.repeat(64),diffSha256:'2'.repeat(64),migrationPlanSha256:'3'.repeat(64),migrationHistorySha256:'4'.repeat(64),migrationToolchainSha256:'5'.repeat(64),migrationEndpointSha256:'6'.repeat(64),operatorStoragePolicySha256:'7'.repeat(64),apiArtifactSha256:'8'.repeat(64),edgeArtifactSha256:'9'.repeat(64),denoLockSha256:'a'.repeat(64)},targets={web:{teamId:'team_Cuevo',projectId:'prj_Web',origin:'https://cuevo-web.vercel.app',target:'preview' as const},api:{teamId:'team_Cuevo',projectId:'prj_Api',origin:'https://cuevo-api.vercel.app',target:'preview' as const},supabase:{projectRef:project,authOrigin:`https://${project}.supabase.co`,edgeOrigin:`https://${project}.supabase.co/functions/v1/cuevo-worker`}},reviews=[{category:'source-spec-code' as const,taskId:'source-review',reportSha256:'b'.repeat(64),evidenceSha256:'c'.repeat(64)},{category:'qa-regression-operations' as const,taskId:'qa-review',reportSha256:'e'.repeat(64),evidenceSha256:'f'.repeat(64)}],identity={repository:'attaulhaq0/Cuevo',releaseSha:sha,treeSha:tree,baseSha:base,ciRunId:'31',releaseRunId:'51',runAttempt:1,environmentId:123,environmentName:'staging' as const,deploymentEnvironment:'synthetic-staging' as const,executionScope:'complete-backend' as const,canonicalRuntimeVerification:{runAttempt:2,jobsSha256:'b'.repeat(64)}};
 const expected={...identity,targets,fingerprints,reviews,now:Date.parse(execution),currentMainSha:sha,ciRun:{id:31,head_sha:sha,head_branch:'main' as const,event:'push' as const,status:'completed' as const,conclusion:'success' as const,path:'.github/workflows/ci.yml' as const,repository:{full_name:'attaulhaq0/Cuevo'}},backendRun:{id:51,run_attempt:1,head_sha:sha,head_branch:'main' as const,event:'workflow_dispatch' as const,status:'in_progress' as const,conclusion:null,path:'.github/workflows/backend-release.yml' as const,repository:{full_name:'attaulhaq0/Cuevo'}}};
 const body={version:1 as const,purpose:'BACKEND_SYNTHETIC_STAGING' as const,...identity,targets,fingerprints,preparedAt:'2026-10-07T11:59:00Z',expiresAt:'2026-10-07T12:59:00Z',reviews:reviews.map(row=>({...row,releaseSha:sha,treeSha:tree,baseSha:base,sourceManifestSha256:fingerprints.sourceManifestSha256,diffSha256:fingerprints.diffSha256,reviewedAt:'2026-10-07T11:58:00Z'}))},preparedApproval=prepareBackendReleaseIntent(body,expected),runtimeConfig={version:1,purpose:'CUEVO_HOSTED_RUNTIME_CONFIGURATION',sourceSha:sha,projectRef:project,privateCanary:'PRIVATE runtime-secret-canary'};
 const activeIdentity={sourceSha:sha,treeSha:tree,originalRunId:'51',originalRunAttempt:1,originalPackageSha256:preparedApproval.sha256,runtimeSha256:hash(runtimeConfig),apiDeploymentId:'dpl_fixture',apiUrl:'https://cuevo-api-fixture.vercel.app',edgeId:'edge_fixture',edgeVersion:1,activationId:'10000000-0000-4000-8000-000000000002',vaultSecretName:'cuevo_worker_10000000000040008000000000000002',endpoint:targets.supabase.edgeOrigin,createdAt:created},originalKey='worker-activation:51:1:'+activeIdentity.activationId,probeEvent='10000000-0000-4000-8000-000000000003',recoveryEvent='10000000-0000-4000-8000-000000000004',recovery={status:'SCHEDULED_RECOVERY_VERIFIED' as const,basis:'ACTUAL_CRON_AFTER_MISSED_POST_COMMIT_HINT' as const,originalKey:originalKey+':recovery',eventId:recoveryEvent,releasedAt:'2026-10-07T12:00:30Z',cronRunId:4,missedHintVerified:true as const,scheduledRecoveryVerified:true as const,eventRetryVerified:false as const,expiredLeaseRecoveryVerified:false as const,dispatchBackoffVerified:false as const,hostedAcceptance:false as const,elapsedMs:500};
 const activation={status:'ACTIVATED_SIGNED_SOURCE_VERIFIED',purpose:'CUEVO_HOSTED_WORKER_ACTIVATION',phase:'FINAL',observedAt:execution,runId:'51',runAttempt:1,apiDeploymentId:'dpl_fixture',packageSha256:preparedApproval.sha256,runtimeSha256:activeIdentity.runtimeSha256,keyOperation:'CONFIRMED',dispatchOperation:'CONFIRMED',dispatchDisabledOnFailure:null,sourceProcessed:true,duplicateWakeDenied:true,originalCommandReplayed:true,recoveryScheduled:true,scheduledRecoveryVerified:true,recovery,recoveryVerified:false,configurationEvidenceObservedManual:true,sessionsClosed:true,sourceSha:sha,projectRef:project,edgeVersion:1,jobId:42,probeEventId:probeEvent,hostedAcceptance:false,canonicalReceipt:null},cleanup={purpose:'CUEVO_HOSTED_WORKER_ACTIVATION_CLEANUP',status:activation.status,sourceSha:sha,projectRef:project,runId:'51',runAttempt:1,lockReleased:true,sessionsClosed:true,resultSha256:hash(activation),observedAt:closed},intent={version:1,purpose:activation.purpose,activationId:activeIdentity.activationId,sourceSha:sha,projectRef:project,packageSha256:preparedApproval.sha256,runtimeSha256:activeIdentity.runtimeSha256,apiDeploymentId:'dpl_fixture',edgeDeployment:{id:'edge_fixture',version:1},configurationEvidenceSha256:'e'.repeat(64),originalKey,endpoint:activeIdentity.endpoint,createdAt:created};
 const stages=[['INTENT_RECORDED',{}],['PRIVATE_PROBE_INTENT',{}],['PRIVATE_PROBES_CONFIRMED',{}],['KEY_PREPARED',{vaultSecretName:activeIdentity.vaultSecretName,keySha256:rawHash(wakeKey)}],['EDGE_KEY_INTENT',{}],['EDGE_KEY_CONFIRMED',{}],['DISPATCH_INTENT',{}],['DISPATCH_CONFIRMED',{vaultSecretId:'10000000-0000-4000-8000-000000000005'}],['SOURCE_COMMAND_INTENT',{originalKey,command:'school.details.update',bodySha256:'f'.repeat(64)}],['SOURCE_AND_WAKE_CONFIRMED',{eventId:probeEvent,sourceId:'10000000-0000-4000-8000-000000000006',wakeId:'10000000-0000-4000-8000-000000000007'}],['SIGNED_SOURCE_VERIFIED',{eventId:probeEvent}],['CRON_INTENT',{jobName:'cuevo-worker-recovery',schedule:'* * * * *',command:'select internal.request_worker_wake();'}],['CRON_PENDING_COMMIT',{jobId:42}],['CRON_CONFIRMED',{jobId:42}],['RECOVERY_SOURCE_INTENT',{originalKey:recovery.originalKey,jobId:42}],['RECOVERY_PENDING_RELEASE',{eventId:recoveryEvent}],['RECOVERY_RELEASE_CONFIRMED',{eventId:recoveryEvent,releasedAt:recovery.releasedAt}],['SCHEDULED_RECOVERY_VERIFIED',{eventId:recoveryEvent,cronRunId:4,releasedAt:recovery.releasedAt,elapsedMs:500}],['RECOVERY_RESULT',recovery],['ACTIVATION_VERIFIED',{}],['EXECUTION_FINAL',{status:activation.status,keyOperation:'CONFIRMED',dispatchOperation:'CONFIRMED',sessionsClosed:true}]] as const;
 const journal=stages.map(([phase,detail],index)=>({phase,at:index<16?created:index<19?recovery.releasedAt:execution,...detail}));
 return{expected,preparedApproval,identityBytes:bytes(activeIdentity),intentBytes:bytes(intent),activationBytes:bytes(activation),cleanupBytes:bytes(cleanup),journalBytes:Buffer.from(journal.map(row=>canonicalReleaseExecutionJson(row)+'\n').join('')),wakeKey,runtimeConfig,now};
}
