import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { execFileSync } from 'node:child_process';
import { registerHooks } from 'node:module';
import { transformSync } from 'esbuild';
import { readFileSync } from 'node:fs';
import { readCanonicalMigrationSources, planHostedMigrations, canonicalHostedMigrationPlan } from '../database/hosted-migration-plan';
import { canonicalReleaseReviewJson, canonicalReleaseExecutionJson, parseReleaseExecutionJson } from './release-review';

const digest = (bytes: Uint8Array | string) => createHash('sha256').update(bytes).digest('hex'), ref = 'mqxdjvsyckzocokuikmx', repository = 'attaulhaq0/Cuevo', githubToken = 'private-backend-prepare-github', providerToken = 'private-backend-prepare-provider';
const realRoot = resolve(import.meta.dirname, '../..'), realSha = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: realRoot, encoding: 'utf8' }).trim(), realTree = execFileSync('git', ['rev-parse', 'HEAD^{tree}'], { cwd: realRoot, encoding: 'utf8' }).trim();
const originalSources = readCanonicalMigrationSources({ repoRoot: realRoot, sourceSha: realSha, treeSha: realTree }).sources;
type Fixture = { root: string; responses: Map<string, unknown>; calls: string[]; builds: string[]; failBuild: boolean; input?: Record<string, unknown> };
let state: Fixture;
Object.assign(globalThis, { backendPrepareFixture: {
  root: () => state.root,
  migration: (input: { repoRoot: string; sourceSha: string; treeSha: string; target: unknown; now: number }) => ({ plan: planHostedMigrations({ sources: originalSources, source: { sha: input.sourceSha, tree: input.treeSha }, target: input.target, now: input.now }), sourceProvenance: { kind: 'VERIFIED_GIT_BLOBS' } }),
  workdirs: async (input: { plan: ReturnType<typeof planHostedMigrations> }) => {
    const root = join(state.root, '.local/hosted-release/migration-fixture'), config = 'project_id = "cuevo"\n\n[db]\nmajor_version = 17\n\n[db.migrations]\nenabled = true\n\n[db.seed]\nenabled = false\n';
    await mkdir(root); await writeFile(join(root, 'builder-state.json'), '{}'); let boundary = 0;
    const stages = [];
    for (const stage of input.plan.stages) { const before = boundary; boundary += stage.names.length; const workdir = join(root, stage.id), folder = join(workdir, 'supabase/migrations'), included = input.plan.migrations.slice(0, boundary); await mkdir(folder, { recursive: true }); await writeFile(join(workdir, 'supabase/config.toml'), config); for (const row of included) await writeFile(join(folder, row.name), originalSources.find(source => source.name === row.name)!.bytes); stages.push({ id: stage.id, workdir, included, pending: included.filter(row => stage.names.includes(row.name)), expectedBeforeVersions: input.plan.migrations.slice(0, before).map(row => row.version).sort(), expectedAfterVersions: included.map(row => row.version).sort(), configSha256: digest(config), commandArgs: ['db', 'push', '--linked', '--project-ref', ref, '--include-all', '--skip-vault', '--workdir', workdir, '--yes', '--output-format', 'json'] }); }
    return { root, projectRef: ref, sourceSha: input.plan.source.sha, treeSha: input.plan.source.tree, planSha256: canonicalHostedMigrationPlan(input.plan).sha256, execution: 'NOT_EXECUTED', stages };
  },
  api: async () => { state.builds.push('api'); if (state.failBuild) throw Error(providerToken); const folder = join(state.root, '.local/runtime-artifacts/api-vercel'); await mkdir(folder, { recursive: true }); const artifact = { schemaVersion: 1, service: 'api', files: [{ path: 'api.mjs', sha256: digest('api source') }] }; await writeFile(join(folder, 'api.mjs'), 'api source'); await writeFile(join(folder, 'artifact.json'), JSON.stringify(artifact)); return artifact; },
  edge: async () => { state.builds.push('edge'); const folder = join(state.root, '.local/edge-artifacts/cuevo-worker'); await mkdir(folder, { recursive: true }); const artifact = { schemaVersion: 1, service: 'cuevo-worker', denoLockSha256: digest('locked edge'), files: [{ path: 'index.ts', sha256: digest('edge source') }, { path: 'deno.lock', sha256: digest('locked edge') }] }; await writeFile(join(folder, 'index.ts'), 'edge source'); await writeFile(join(folder, 'deno.lock'), 'locked edge'); await writeFile(join(folder, 'artifact.json'), JSON.stringify(artifact)); return artifact; },
} });
// Only module-bound owners are replaced: all Git source checks, fixed requests, policy,
// lockfile/toolchain and physical output verification execute the production implementation.
registerHooks({ load(url, context, next) { const name = url.split('/').at(-1); if (name === 'hosted-migration-plan.ts') return { format: 'module', shortCircuit: true, source: 'export const createCanonicalHostedMigrationPlan=globalThis.backendPrepareFixture.migration;export const canonicalHostedMigrationPlan=globalThis.backendPrepareCanonicalPlan;' }; if (name === 'hosted-migration-workdirs.ts') return { format: 'module', shortCircuit: true, source: 'export const createHostedMigrationWorkdirs=globalThis.backendPrepareFixture.workdirs;' }; if (name === 'build-artifacts.ts') return { format: 'module', shortCircuit: true, source: 'export const buildRuntimeArtifact=globalThis.backendPrepareFixture.api;' }; if (name === 'build-edge-artifact.ts') return { format: 'module', shortCircuit: true, source: 'export const buildEdgeArtifact=globalThis.backendPrepareFixture.edge;' }; if (name === 'backend-release-prepare.ts') return { format: 'module', shortCircuit: true, source: transformSync(readFileSync(new URL(url), 'utf8').replace('if (root !== builderRepoRoot)', 'if (root !== globalThis.backendPrepareFixture.root())'), { loader: 'ts', format: 'esm' }).code }; return next(url, context); } });
Object.assign(globalThis, { backendPrepareCanonicalPlan: canonicalHostedMigrationPlan });
function git(root: string, ...args: string[]) { return execFileSync('git', ['-C', root, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], windowsHide: true }).trim(); }
async function api() { let module: Record<string, unknown> = {}; try { module = await import(pathToFileURL(resolve(import.meta.dirname, 'backend-release-prepare.ts')).href); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ERR_MODULE_NOT_FOUND') throw error; } assert.equal(typeof module.prepareNativeBackendRelease, 'function'); return module as typeof import('./backend-release-prepare'); }
async function fixture(run: (input: Record<string, unknown>) => Promise<void>) {
  const root = await mkdtemp(join(tmpdir(), 'cuevo-backend-prepare-')), originalFetch = globalThis.fetch;
  try {
    await writeFile(join(root, '.gitignore'), '.local/\nnode_modules/\n'); await writeFile(join(root, 'README.md'), 'Reviewed original source\n');
    const cliPlatform = process.platform === 'win32' ? 'windows' : process.platform;
    await writeFile(join(root, 'package-lock.json'), JSON.stringify({ lockfileVersion: 3, packages: Object.fromEntries(['node_modules/supabase', 'node_modules/@supabase/cli-' + cliPlatform + '-' + process.arch].map(path => [path, { version: '2.119.0', integrity: 'sha512-fixture-pinned-integrity', resolved: 'https://registry.npmjs.org/' + path.slice('node_modules/'.length) + '/-/cli.tgz' }])) }));
    await mkdir(join(root, 'supabase/migrations'), { recursive: true }); for (const source of originalSources) await writeFile(join(root, 'supabase/migrations', source.name), source.bytes);
    git(root, 'init', '--quiet'); git(root, 'config', 'core.autocrlf', 'false'); git(root, 'add', '.'); git(root, '-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgsign=false', 'commit', '--quiet', '-m', 'source'); const sha = git(root, 'rev-parse', 'HEAD'), treeSha = git(root, 'rev-parse', 'HEAD^{tree}'), environment = { id: 123, name: 'staging', can_admins_bypass: false, protection_rules: [{ type: 'required_reviewers', prevent_self_review: false, reviewers: [{ type: 'User', reviewer: { id: 95836629, login: 'attaulhaq0', type: 'User' } }] }], deployment_branch_policy: { protected_branches: false, custom_branch_policies: true } }, ci = { id: 31, head_sha: sha, head_branch: 'main', event: 'push', status: 'completed', conclusion: 'success', path: '.github/workflows/ci.yml', repository: { full_name: repository } }, backend = { id: 51, run_attempt: 1, head_sha: sha, head_branch: 'main', event: 'workflow_dispatch', status: 'in_progress', conclusion: null, path: '.github/workflows/backend-release.yml', repository: { full_name: repository } };
    state = { root, calls: [], builds: [], failBuild: false, responses: new Map<string, unknown>([['', { full_name: repository, name: 'Cuevo', owner: { id: 95836629, login: 'attaulhaq0', type: 'User' } }], ['git/ref/heads/main', { object: { type: 'commit', sha } }], ['actions/runs/31', ci], ['actions/runs/51', backend], ['environments/staging', environment], ['environments/staging/deployment-branch-policies', { total_count: 1, branch_policies: [{ name: 'main', type: 'branch' }] }], ['branches/main/protection', { enforce_admins: { enabled: true }, allow_force_pushes: { enabled: false }, allow_deletions: { enabled: false }, required_status_checks: { strict: true, contexts: ['required'] }, required_pull_request_reviews: { dismiss_stale_reviews: true, require_code_owner_reviews: false, required_approving_review_count: 0, require_last_push_approval: false } }], ['branches/main/protection/required_signatures', { enabled: true }], ['provider', { id: ref, name: 'Cuevo', status: 'ACTIVE_HEALTHY', database: { host: `db.${ref}.supabase.co`, version: '17.11.0', postgres_engine: '17' } }], ['target', [{ authUsers: 0, storageObjects: 0, appSchemas: [], runtimeRoles: [], historyPresent: false, recoveryCronPresent: false }]]]) };
    state.responses.set('git/commits/' + sha, { sha, tree: { sha: treeSha }, verification: { verified: true, reason: 'valid', signature: 'official fixture signed bytes', payload: 'official fixture signed payload' } });
    const targets = { web: { teamId: 'team_Cuevo', projectId: 'prj_Web', origin: 'https://cuevo-web.vercel.app', target: 'preview' }, api: { teamId: 'team_Cuevo', projectId: 'prj_Api', origin: 'https://cuevo-api.vercel.app', target: 'preview' }, supabase: { projectRef: ref, authOrigin: `https://${ref}.supabase.co`, edgeOrigin: `https://${ref}.supabase.co/functions/v1/cuevo-worker` } }, fingerprint = digest(execFileSync('git', ['-C', root, 'ls-tree', '-r', '-z', sha])), diff = digest(execFileSync('git', ['-C', root, 'diff', '--no-ext-diff', '--no-textconv', '--binary', sha, sha, '--'])), reviews = ['source-spec-code', 'qa-regression-operations'].map((category, index) => ({ category, taskId: 'real-independent-' + index, reportSha256: String(index + 1).repeat(64), evidenceSha256: String(index + 3).repeat(64), releaseSha: sha, treeSha, baseSha: sha, sourceManifestSha256: fingerprint, diffSha256: diff, reviewedAt: new Date(Date.now() - 1000).toISOString() }));
    const eventPath = join(root, '.local-event.json'); await writeFile(eventPath, JSON.stringify({ ref: 'refs/heads/main', inputs: { commit_sha: sha, ci_run_id: '31' }, repository: { full_name: repository } })); await mkdir(join(root, '.local/hosted-release'), { recursive: true }); await rm(eventPath); const actualEvent = join(root, '.local/hosted-release/event.json'); await writeFile(actualEvent, JSON.stringify({ ref: 'refs/heads/main', inputs: { commit_sha: sha, ci_run_id: '31' }, repository: { full_name: repository } }));
    const platform = process.platform === 'win32' ? 'windows' : process.platform, suffix = process.platform === 'win32' ? '.exe' : ''; for (const folder of ['node_modules/supabase/dist', `node_modules/@supabase/cli-${platform}-${process.arch}/bin`]) await mkdir(join(root, folder), { recursive: true }); await writeFile(join(root, 'node_modules/supabase/package.json'), JSON.stringify({ name: 'supabase', version: '2.119.0', type: 'module' })); await writeFile(join(root, `node_modules/@supabase/cli-${platform}-${process.arch}/package.json`), JSON.stringify({ name: `@supabase/cli-${platform}-${process.arch}`, version: '2.119.0' })); await writeFile(join(root, 'node_modules/supabase/dist/supabase.js'), 'pinned shim'); for (const name of ['supabase', 'supabase-go']) await writeFile(join(root, `node_modules/@supabase/cli-${platform}-${process.arch}/bin/${name}${suffix}`), name);
    const input = { repoRoot: root, eventPath: actualEvent, repository, sha, ref: 'refs/heads/main', eventName: 'workflow_dispatch', runId: '51', runAttempt: 1, githubToken, providerToken, input: { targets, baseSha: sha, ciRunId: '31', reviews } }; state.input = input;
    globalThis.fetch = async (raw, options) => { const url = new URL(String(raw)); state.calls.push(url.pathname); assert.equal(options?.redirect, 'error'); if (url.origin === 'https://api.github.com') { assert.equal(options?.method, 'GET'); const path = url.pathname.slice(`/repos/${repository}`.length).replace(/^\//, ''); return Response.json(state.responses.get(path)); } assert.equal(url.origin, 'https://api.supabase.com'); if (url.pathname.endsWith('/database/query')) { assert.equal(options?.method, 'POST'); assert.equal(new Headers(options?.headers).get('Authorization'), 'Bearer ' + providerToken); const body = JSON.parse(String(options?.body)); assert.deepEqual(Object.keys(body), ['query']); assert.doesNotMatch(body.query, /\b(?:insert|update|delete|drop|create|truncate)\b/i); return Response.json(state.responses.get('target')); } return Response.json(url.pathname.endsWith('/config/database/pooler')?[{identifier:ref,database_type:'PRIMARY',db_user:'postgres.'+ref,db_host:'aws-0-ap-southeast-1.pooler.supabase.com',db_port:6543,db_name:'postgres',pool_mode:'transaction'}]:state.responses.get('provider')); };
    await run(input);
  } finally { globalThis.fetch = originalFetch; await rm(root, { recursive: true, force: true }); }
}

test('native preparation assembles exact source plan policy toolchain and built artifacts before secret-free package persistence', async () => { const { prepareNativeBackendRelease } = await api(); await fixture(async input => { state.responses.set('target', [{ authUsers: '0', storageObjects: '0', appSchemas: [], runtimeRoles: [], historyPresent: false, recoveryCronPresent: false }]); const result = await prepareNativeBackendRelease(input); assert.equal(result.purpose, 'CUEVO_BACKEND_RELEASE_EXECUTION'); assert.equal(result.preparedApproval.status, 'PREPARED_ONLY'); assert.equal(result.plan.migrations.length, 229); assert.equal(result.stages.length, 4); assert.equal(result.migrationEndpoint.kind,'session-pooler'); assert.equal(result.migrationEndpoint.port,5432); assert.equal(result.expected.fingerprints.migrationEndpointSha256,digest(canonicalReleaseExecutionJson(result.migrationEndpoint))); assert.deepEqual(result.stages.map(stage => stage.included.length), [123, 124, 180, 229]); assert.deepEqual(state.builds, ['api', 'edge']); const bytes = await readFile(result.bundlePath, 'utf8'); assert.equal(digest(bytes), result.bundleSha256); assert.equal(bytes.includes(githubToken) || bytes.includes(providerToken), false); assert.equal(result.expected.fingerprints.operatorStoragePolicySha256.length, 64); assert.ok(Buffer.byteLength(bytes) > 48 * 1024); assert.ok(Buffer.byteLength(bytes) < 1024 * 1024); assert.equal(canonicalReleaseExecutionJson(parseReleaseExecutionJson(bytes)), bytes); assert.throws(() => canonicalReleaseReviewJson(JSON.parse(bytes))); assert.equal(result.expected.fingerprints.apiArtifactSha256, digest(JSON.stringify(JSON.parse(await readFile(join(result.artifacts.apiRoot, 'artifact.json'), 'utf8'))))); assert.equal(state.calls.filter(path => path.endsWith('/database/query')).length, 2); await assert.rejects(prepareNativeBackendRelease(input)); assert.equal(await readFile(result.bundlePath, 'utf8'), bytes); }); });
test('wrong main CI backend run source ref and fabricated review fields refuse without deployment preparation', async () => { const { prepareNativeBackendRelease } = await api(); for (const mode of ['main', 'ci', 'run', 'ref', 'review', 'dirty']) await fixture(async input => { if (mode === 'main') state.responses.set('git/ref/heads/main', { object: { type: 'commit', sha: '0'.repeat(40) } }); if (mode === 'ci') state.responses.set('actions/runs/31', {}); if (mode === 'run') state.responses.set('actions/runs/51', {}); if (mode === 'ref') input.ref = 'refs/heads/other'; if (mode === 'review') ((input.input as { reviews: Record<string, unknown>[] }).reviews[0]).sourceManifestSha256 = '0'.repeat(64); if (mode === 'dirty') await writeFile(join(state.root, 'unreviewed.ts'), 'unreviewed source'); await assert.rejects(prepareNativeBackendRelease(input)); assert.equal(state.builds.length, 0); }); });
test('actual unknown or nonempty provider target never becomes an empty migration plan', async () => { const { prepareNativeBackendRelease } = await api(); for (const target of [{ authUsers: 1, storageObjects: 0, appSchemas: [], runtimeRoles: [], historyPresent: false, recoveryCronPresent: false }, { authUsers: 0, storageObjects: null, appSchemas: [], runtimeRoles: [], historyPresent: false, recoveryCronPresent: false }, { authUsers: 0, storageObjects: 0, appSchemas: ['app'], runtimeRoles: [], historyPresent: false, recoveryCronPresent: false }]) await fixture(async input => { state.responses.set('target', [target]); await assert.rejects(prepareNativeBackendRelease(input)); assert.equal(state.builds.length, 0); }); });
test('unexpected secret fields and getters cannot enter the prepared package or execute hooks', async () => { const { prepareNativeBackendRelease } = await api(); await fixture(async input => { let traps = 0; await assert.rejects(prepareNativeBackendRelease({ ...input, get githubToken() { traps++; return githubToken; } })); await assert.rejects(prepareNativeBackendRelease({ ...input, storageKey: providerToken })); assert.equal(traps, 0); assert.equal(state.calls.length, 0); }); });
test('execution encoding preserves the approval bound and rejects oversized lossy or executable envelopes', () => { const text = canonicalReleaseExecutionJson({ payload: 'a'.repeat(60 * 1024) }); assert.deepEqual(parseReleaseExecutionJson(text), { payload: 'a'.repeat(60 * 1024) }); assert.throws(() => canonicalReleaseReviewJson({ payload: 'a'.repeat(60 * 1024) })); assert.throws(() => canonicalReleaseExecutionJson({ payload: 'a'.repeat(1024 * 1024) })); assert.throws(() => parseReleaseExecutionJson('{"payload":1,"payload":2}')); assert.throws(() => parseReleaseExecutionJson(text + '\n')); assert.throws(() => canonicalReleaseExecutionJson({ payload: '\ud800' })); let getters = 0; assert.throws(() => canonicalReleaseExecutionJson({ get payload() { getters++; return 1; } })); assert.equal(getters, 0); });
