import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { readFile, lstat, realpath } from 'node:fs/promises';
import { isAbsolute, join, resolve } from 'node:path';
import type { Readable } from 'node:stream';
import {types} from 'node:util';
import { z } from 'zod';
import { intelligenceExecutionManifestSchema } from '@cuevo/contracts';
import { canonicalReleaseExecutionJson, canonicalReleaseReviewJson, parseReleaseExecutionJson, parseCanonicalReleaseReviewJson } from './release-review';
import type { HostedLearningLoopNativeSelection } from './backend-hosted-learning-loop-native';

const fail=()=>Error('Official learning-loop artifact requires review; metadata and private contents withheld.');
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
const same=(left:unknown,right:unknown)=>canonicalReleaseExecutionJson(left)===canonicalReleaseExecutionJson(right);
const digest=z.string().regex(/^[a-f0-9]{64}$/),sha=z.string().regex(/^[a-f0-9]{40}$/),uuid=z.uuid(),date=z.iso.datetime({offset:true});
const positive=z.number().int().positive().max(Number.MAX_SAFE_INTEGER),count=z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const runId=z.string().regex(/^[1-9][0-9]{0,19}$/).refine(value=>Number.isSafeInteger(Number(value)));
const mode=z.enum(['FULL_LOOP','ORIGINAL_RECONCILIATION']);
const ids=z.array(uuid).max(1000).refine(values=>new Set(values).size===values.length);
const origin=z.string().url().refine(value=>{const u=new URL(value);return u.protocol==='https:'&&u.origin===value&&!u.username&&!u.password&&!u.port;});
const repository=z.string().regex(/^[A-Za-z0-9_.-]{1,100}\/[A-Za-z0-9_.-]{1,100}$/).refine(value=>!value.split('/').some(part=>['.','..'].includes(part)));
const operations=['course.create','unit.create','lesson.create','activity.create','course.publish','assessment.create','assessment.preparation','assessment.publish','activity.complete','submission.draft','submission.create','assessment.reference','marking.create','result.release','intelligence.analyze','improvement.decision','improvement.complete','improvement.reassessment','improvement.measure','portfolio.create','portfolio.review','portfolio.revoke','intelligence.policy.approve'] as const;
const identitySchema=z.object({projectRef:z.string().regex(/^[a-z]{20}$/),schoolId:uuid,sourceSha:sha,treeSha:sha,ciRunId:runId,runId,runAttempt:positive,backendTransferSha256:digest,webDeploymentId:z.string().regex(/^dpl_[A-Za-z0-9]{1,100}$/)}).strict();
const commandSchema=z.object({step:z.string().regex(/^[a-z][a-z0-9_.:-]{0,99}$/),actorId:uuid,role:z.enum(['admin','teacher','student','coordinator','parent']),schoolId:uuid,path:z.string().min(5).max(400).regex(/^\/v1\/[a-z0-9-]+(?:\/[a-z0-9-]+)*$/),operation:z.enum(operations),sourceIds:ids.refine(values=>values.length<=16),sourceRevision:positive.nullable(),key:z.string().min(8).max(200).regex(/^[A-Za-z0-9_.:-]+$/),requestBodySha256:digest}).strict();
const originalSchema=z.object({identity:identitySchema,command:commandSchema,intentSequence:positive.refine(value=>value<=512),intentRecordSha256:digest}).strict();
const recordSchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_HOSTED_LEARNING_LOOP_COMMAND_JOURNAL'),sequence:positive.refine(value=>value<=512),previousRecordSha256:digest.nullable(),identity:identitySchema,command:commandSchema,state:z.enum(['INTENT','FORWARDING_AUTHORIZED','HTTP_CONFIRMED','NATIVE_CONFIRMED','UNCERTAIN']),intentSequence:positive.refine(value=>value<=512),intentRecordSha256:digest.nullable(),httpReceiptSha256:digest.nullable(),nativeReceiptSha256:digest.nullable(),nativeProof:z.literal('CALLER_ATTESTED_INDEPENDENT_NATIVE_ORIGINAL_COMMAND_PROOF').nullable(),localDurabilityOnly:z.literal(true),recordSha256:digest}).strict();
const headSchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_HOSTED_LEARNING_LOOP_COMMAND_JOURNAL'),sequence:positive,recordSha256:digest,previousRecordSha256:digest.nullable()}).strict();
const stateSchema=z.object({original:originalSchema,state:recordSchema.shape.state,httpReceiptSha256:digest.nullable(),nativeReceiptSha256:digest.nullable()}).strict();
const journalSchema=z.object({records:z.array(recordSchema).min(1).max(512),commands:z.array(stateSchema).min(1).max(32),lastRecordSha256:digest,evidence:z.literal('LOCAL_DURABLE_METADATA_ONLY'),hostedAcceptance:z.literal(false),runnerLossRecoveryVerified:z.literal(false)}).strict();
const metadataSchema=z.object({operation:z.enum(operations),targetId:uuid.nullable(),sourceIds:ids.refine(values=>values.length<=16),sourceRevision:positive.nullable(),requestBodySha256:digest,nativeFingerprint:digest}).strict();
const intentSchema=metadataSchema.extend({version:z.literal(1),purpose:z.literal('CUEVO_HOSTED_LEARNING_LOOP_ORIGINAL_COMMAND'),original:originalSchema}).strict();
const receiptIdentitySchema=z.object({id:uuid,revisionId:uuid.optional(),revision:positive.optional(),status:z.enum(['DRAFT','PUBLISHED','SUBMITTED','REVIEW','RELEASED','AWAITING_HUMAN','APPROVED','COMPLETED','improved','AWAITING_REVIEW','REVIEWED','PARENT_REVOKED']).optional(),classId:uuid.optional(),subjectId:uuid.optional(),courseId:uuid.optional(),activityId:uuid.optional(),learnerId:uuid.optional(),assessmentId:uuid.optional(),submissionId:uuid.optional(),referenceId:uuid.optional(),referenceVersion:z.string().min(1).max(100).optional(),policyVersion:positive.optional(),preparationVersion:positive.optional(),availabilityVersion:positive.optional(),evidenceId:uuid.optional(),intelligenceRunId:uuid.optional(),baselineResultId:uuid.optional(),recommendationId:uuid.optional(),interventionId:uuid.optional(),followUpAssessmentId:uuid.optional(),followUpResultId:uuid.optional()}).strict();
const httpSchema=metadataSchema.extend({version:z.literal(1),purpose:z.literal('CUEVO_HOSTED_LEARNING_LOOP_HTTP_RECEIPT'),original:originalSchema,originalCompanionSha256:digest,requestId:z.string().regex(/^[-A-Za-z0-9_.:]{1,200}$/),status:z.literal(200),receiptSha256:digest,receiptIdentity:receiptIdentitySchema,nativeChainVerified:z.literal(false)}).strict();
const scopeSchema=z.object({schoolId:uuid,adminId:uuid,teacherId:uuid,studentId:uuid,classId:uuid,subjectId:uuid,referenceId:uuid}).strict();
const selectedSchema=z.object({admin:uuid,coordinator:uuid,teacher:uuid,student:uuid,parent:uuid}).strict();
const backendSchema=z.object({repository,sourceSha:sha,treeSha:sha,baseSha:sha,ciRunId:runId,runId,runAttempt:positive,artifactId:runId,artifactSha256:digest,transferSha256:digest,manifestSha256:digest,packageSha256:digest,web:z.object({teamId:z.string().regex(/^team_[A-Za-z0-9]+$/),projectId:z.string().regex(/^prj_[A-Za-z0-9]+$/),origin,target:z.literal('preview')}).strict(),settingsSha256:digest,earliestProofAt:date,exportedAt:date,consumptionExpiresAt:date}).strict();
const webSchema=z.object({purpose:z.literal('PREBUILD_RELEASE_ADMISSION'),sourceSha:sha,treeSha:sha,ciRunId:runId,runId,runAttempt:positive,webDeploymentId:z.string().regex(/^dpl_[A-Za-z0-9]{1,100}$/),artifactSha256:digest,packageSha256:digest,backendTransferSha256:digest,populationReceiptSha256:digest,apiOrigin:origin,authOrigin:origin,webOrigin:origin,webPackageExpiresAt:date,observedAt:date}).strict();
const common={identity:identitySchema,backendIdentity:backendSchema,webAdmission:webSchema,scope:scopeSchema,selectedActorIds:selectedSchema,producerSha256:digest};
const runIntentSchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_HOSTED_LEARNING_LOOP_UI'),...common}).strict();
const sourceLoopSchema=z.object({course:uuid,learningCompletion:uuid,baseline:uuid,evidence:uuid,proposal:uuid,intervention:uuid,followUp:uuid,outcome:uuid}).strict();
const numericSchema=z.object({baseline:z.literal(2),followUp:z.literal(7),maxScore:z.literal(10),difference:z.literal(5),limitation:z.literal('OBSERVED_CHANGE_NOT_CAUSAL_PROOF')}).strict();
const projectionSchema=z.object({learnerId:uuid,status:z.literal('READY'),freshness:z.literal('CURRENT'),observedAt:date,generatedAt:date,version:positive,windowEnd:date,academicResultIds:ids,observationIds:ids,interventionIds:ids,measurementIds:ids,sourceEventIds:ids}).strict();
const manifestSchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_HOSTED_LEARNING_LOOP_UI_EVIDENCE'),...common,status:z.enum(['UI_LOOP_VERIFIED','REQUIRES_REVIEW']),expectedExecutionManifest:intelligenceExecutionManifestSchema.nullable(),apiProjection:projectionSchema.nullable(),journal:journalSchema,companions:z.array(z.object({path:z.string().regex(/^\d{6}\.(?:intent|http)\.json$/),sha256:digest}).strict()).min(1).max(64),commands:z.array(httpSchema.extend({companionSha256:digest}).strict()).max(32),sourceLoop:sourceLoopSchema.nullable(),numericOutcome:numericSchema.nullable(),nativeChainVerified:z.literal(false),runnerLossRecoveryVerified:z.literal(false),customerReady:z.literal(false),hostedAcceptance:z.literal(false)}).strict();
const resultSchema=z.object({purpose:z.literal('CUEVO_HOSTED_LEARNING_LOOP_UI'),status:z.enum(['UI_LOOP_VERIFIED','REQUIRES_REVIEW']),sourceSha:sha,treeSha:sha,ciRunId:runId,runId,runAttempt:positive,projectRef:identitySchema.shape.projectRef,schoolId:uuid,webDeploymentId:identitySchema.shape.webDeploymentId,webArtifactSha256:digest,webPackageSha256:digest,backendIdentity:backendSchema,populationReceiptSha256:digest,producerSha256:digest,confirmedCommandCount:count,roleSessions:count,roleSignouts:count,sessionsClosed:z.boolean(),unexpectedRequests:count,consoleErrors:count,consoleWarnings:count,pageErrors:count,sourceLoop:sourceLoopSchema.nullable(),numericOutcome:numericSchema.nullable(),apiProjection:projectionSchema.nullable(),journalLastRecordSha256:digest,companionManifestSha256:digest,nativeChainVerified:z.literal(false),runnerLossRecoveryVerified:z.literal(false),coreLearningLoopVerified:z.literal(false),allNestedWorkflowAcceptance:z.literal(false),customerReady:z.literal(false),hostedAcceptance:z.literal(false),observedAt:date,canonicalReceipt:z.null()}).strict();
const expectedSchema=z.object({sourceSha:sha,uiRunId:runId,uiRunAttempt:positive,commandManifestSha256:digest,journalHeadSha256:digest,producerSha256:digest,archiveSha256:digest,mode,now:z.number().int().nonnegative()}).strict();
export type HostedLearningLoopArtifactExpected=z.infer<typeof expectedSchema>;
export type HostedLearningLoopArtifact={selection:HostedLearningLoopNativeSelection;apiProjection:z.infer<typeof projectionSchema>|null;expectedExecutionManifest:z.infer<typeof intelligenceExecutionManifestSchema>|null;backendIdentity:z.infer<typeof backendSchema>;webAdmission:z.infer<typeof webSchema>;uiResult:z.infer<typeof resultSchema>;sourceIds:string[];scopeSha256:string;expiresAt:string;status:'UI_LOOP_VERIFIED'|'ORIGINALS_RETAINED';officialAdmissionVerified:false;nativeExecutionVerified:false;uiArtifactSha256:string;commandManifestSha256:string;journalHeadSha256:string};

type ZipEntry={fileName:string;uncompressedSize:number;compressedSize:number;generalPurposeBitFlag:number;compressionMethod:number;externalFileAttributes:number;extraFields:{id:number;data:Buffer}[]};
type Zip={entryCount:number;on(name:'error'|'entry'|'end',listener:(...args:never[])=>void):void;readEntry():void;close():void;openReadStream(entry:ZipEntry,callback:(error:Error|null,stream?:Readable)=>void):void};
const {yauzl}=createRequire(import.meta.url)('playwright-core/lib/utilsBundle') as {yauzl:{fromBuffer(bytes:Buffer,options:object,callback:(error:Error|null,zip?:Zip)=>void):void}};
async function archiveFiles(bytes:Uint8Array){
 if(bytes.byteLength<22||bytes.byteLength>8*1024*1024)throw fail();
 return new Promise<Map<string,Buffer>>((done,reject)=>{let opened:Zip|undefined,reader:Readable|undefined,settled=false,count=0,total=0;const files=new Map<string,Buffer>();
  const finish=(error?:Error)=>{if(settled)return;settled=true;clearTimeout(timer);reader?.destroy();opened?.close();if(error)reject(fail());else done(files);};const timer=setTimeout(()=>finish(fail()),10000);
  yauzl.fromBuffer(Buffer.from(bytes),{lazyEntries:true,autoClose:true,decodeStrings:true,validateEntrySizes:true,strictFileNames:true},(error,zip)=>{if(settled){zip?.close();return;}if(error||!zip)return finish(fail());opened=zip;if(zip.entryCount<1||zip.entryCount>1200)return finish(fail());
   zip.on('error',(()=>finish(fail())) as (...args:never[])=>void);zip.on('end',(()=>count===zip.entryCount?finish():finish(fail())) as (...args:never[])=>void);
   zip.on('entry',((entry:ZipEntry)=>{const kind=(entry.externalFileAttributes>>>16)&0xf000,name=entry.fileName;
    if(++count>1200||files.has(name)||name.length>260||!/^hosted-learning-loop(?:-ui)?\/scope-[a-f0-9]{64}\/(?:run-[1-9][0-9]{0,19}-[1-9][0-9]{0,9}\/)?(?:owner|run-intent|command-manifest|result|\d{6}\.(?:record|head|intent|http))\.json$/.test(name)||entry.generalPurposeBitFlag&1||![0,8].includes(entry.compressionMethod)||![0,0x8000].includes(kind)||entry.externalFileAttributes&0x10||entry.extraFields.some(field=>![0x5455,0x0001].includes(field.id))||!Number.isSafeInteger(entry.uncompressedSize)||entry.uncompressedSize<1||entry.uncompressedSize>1024*1024||entry.compressedSize>8*1024*1024||total+entry.uncompressedSize>8*1024*1024)return finish(fail());
    total+=entry.uncompressedSize;zip.openReadStream(entry,(readError,stream)=>{if(readError||!stream||settled){stream?.destroy();return finish(fail());}reader=stream;const parts:Buffer[]=[];let size=0;stream.on('error',()=>finish(fail()));stream.on('data',(chunk:Buffer)=>{size+=chunk.length;if(size>entry.uncompressedSize)return finish(fail());parts.push(chunk);});stream.on('end',()=>{if(settled||size!==entry.uncompressedSize)return finish(fail());files.set(name,Buffer.concat(parts));zip.readEntry();});});
   }) as (...args:never[])=>void);zip.readEntry();
  });
 });
}
function parsed<T>(files:Map<string,Buffer>,path:string,schema:z.ZodType<T>,journal=false):T{const bytes=files.get(path);if(!bytes)throw fail();const text=new TextDecoder('utf8',{fatal:true}).decode(bytes),value=journal?(text.endsWith('\n')?parseCanonicalReleaseReviewJson(text.slice(0,-1)):undefined):parseReleaseExecutionJson(text);return schema.parse(value);}

/** Reads bounded verified ZIP bytes without extraction. The supplied immutable
 * expectations bind metadata; official provider admission is a separate owner. */
export async function adaptHostedLearningLoopArtifactArchive(bytes:Uint8Array,value:unknown):Promise<HostedLearningLoopArtifact>{
 try{const expected=expectedSchema.parse(JSON.parse(canonicalReleaseExecutionJson(value)));if(hash(bytes)!==expected.archiveSha256)throw fail();const files=await archiveFiles(bytes),manifests=[...files.keys()].filter(name=>name.endsWith('/command-manifest.json'));if(manifests.length!==1)throw fail();const manifestPath=manifests[0],uiRoot=manifestPath.slice(0,-'command-manifest.json'.length),manifest=parsed(files,manifestPath,manifestSchema),{identity,scope,webAdmission:web,backendIdentity:backend}=manifest;
  const scopeName='scope-'+hash(JSON.stringify([identity.projectRef,identity.schoolId])),journalRoot='hosted-learning-loop/'+scopeName+'/';if(uiRoot!=='hosted-learning-loop-ui/'+scopeName+'/run-'+identity.runId+'-'+identity.runAttempt+'/')throw fail();
  const result=parsed(files,uiRoot+'result.json',resultSchema),intent=parsed(files,uiRoot+'run-intent.json',runIntentSchema),owner=parsed(files,journalRoot+'owner.json',z.object({version:z.literal(1),purpose:z.literal('CUEVO_HOSTED_LEARNING_LOOP_COMMAND_JOURNAL'),projectRef:identitySchema.shape.projectRef,schoolId:uuid}).strict(),true);
  if(hash(files.get(manifestPath)!)!==expected.commandManifestSha256||result.companionManifestSha256!==expected.commandManifestSha256||identity.sourceSha!==expected.sourceSha||identity.runId!==expected.uiRunId||identity.runAttempt!==expected.uiRunAttempt||manifest.producerSha256!==expected.producerSha256||result.producerSha256!==expected.producerSha256||owner.projectRef!==identity.projectRef||owner.schoolId!==identity.schoolId)throw fail();
  for(const key of Object.keys(common) as (keyof typeof common)[])if(!same(intent[key],manifest[key]))throw fail();
  if(!same(result.backendIdentity,backend)||result.status!==manifest.status||result.sourceSha!==identity.sourceSha||result.treeSha!==identity.treeSha||result.ciRunId!==identity.ciRunId||result.runId!==identity.runId||result.runAttempt!==identity.runAttempt||result.projectRef!==identity.projectRef||result.schoolId!==scope.schoolId||result.schoolId!==identity.schoolId||result.webDeploymentId!==identity.webDeploymentId||result.webArtifactSha256!==web.artifactSha256||result.webPackageSha256!==web.packageSha256||result.populationReceiptSha256!==web.populationReceiptSha256||!same(result.sourceLoop,manifest.sourceLoop)||!same(result.numericOutcome,manifest.numericOutcome)||!same(result.apiProjection,manifest.apiProjection)||result.confirmedCommandCount!==manifest.commands.length)throw fail();
  if(backend.sourceSha!==identity.sourceSha||backend.treeSha!==identity.treeSha||backend.ciRunId!==identity.ciRunId||backend.transferSha256!==identity.backendTransferSha256||backend.runId===identity.runId||web.sourceSha!==identity.sourceSha||web.treeSha!==identity.treeSha||web.ciRunId!==identity.ciRunId||web.runId!==identity.runId||web.runAttempt!==identity.runAttempt||web.webDeploymentId!==identity.webDeploymentId||web.backendTransferSha256!==identity.backendTransferSha256||web.webOrigin!==backend.web.origin||web.authOrigin!=='https://'+identity.projectRef+'.supabase.co'||scope.adminId!==manifest.selectedActorIds.admin||scope.teacherId!==manifest.selectedActorIds.teacher||scope.studentId!==manifest.selectedActorIds.student||new Set(Object.values(manifest.selectedActorIds)).size!==5||new Set([scope.adminId,scope.teacherId,scope.studentId]).size!==3)throw fail();
  const expires=Math.min(Date.parse(backend.consumptionExpiresAt),Date.parse(web.webPackageExpiresAt));if(!Number.isFinite(expires)||expires<=expected.now||Date.parse(result.observedAt)>expected.now||Date.parse(web.observedAt)>Date.parse(result.observedAt))throw fail();
  const used=new Set([manifestPath,uiRoot+'result.json',uiRoot+'run-intent.json',journalRoot+'owner.json']),states:z.infer<typeof stateSchema>[]=[];let previous:string|null=null;
  for(const [index,supplied]of manifest.journal.records.entries()){const filename=String(index+1).padStart(6,'0'),recordPath=journalRoot+filename+'.record.json',headPath=journalRoot+filename+'.head.json',record=parsed(files,recordPath,recordSchema,true),head=parsed(files,headPath,headSchema,true);used.add(recordPath);used.add(headPath);const payload:Partial<typeof record>={...record};delete payload.recordSha256;
   if(!same(record,supplied)||record.sequence!==index+1||record.previousRecordSha256!==previous||hash(canonicalReleaseReviewJson(payload))!==record.recordSha256||!same(head,{version:1,purpose:record.purpose,sequence:record.sequence,recordSha256:record.recordSha256,previousRecordSha256:record.previousRecordSha256})||!same(record.identity,identity)||record.command.schoolId!==scope.schoolId||record.nativeReceiptSha256!==null||record.nativeProof!==null||record.state==='NATIVE_CONFIRMED')throw fail();
   if(record.state==='INTENT'){if(record.intentSequence!==record.sequence||record.intentRecordSha256!==null||record.httpReceiptSha256!==null||states.some(row=>row.original.command.key===record.command.key)||states.some(row=>row.state!=='HTTP_CONFIRMED'))throw fail();states.push({original:{identity:record.identity,command:record.command,intentSequence:record.sequence,intentRecordSha256:record.recordSha256},state:'INTENT',httpReceiptSha256:null,nativeReceiptSha256:null});}
   else{const state=states.find(row=>row.original.intentRecordSha256===record.intentRecordSha256);if(!state||!same(state.original.identity,record.identity)||!same(state.original.command,record.command)||state.original.intentSequence!==record.intentSequence||!(record.state==='UNCERTAIN'&&state.state!=='UNCERTAIN'||state.state==='INTENT'&&record.state==='FORWARDING_AUTHORIZED'||state.state==='FORWARDING_AUTHORIZED'&&record.state==='HTTP_CONFIRMED')||record.state==='HTTP_CONFIRMED'&&record.httpReceiptSha256===null||record.state!=='HTTP_CONFIRMED'&&record.httpReceiptSha256!==state.httpReceiptSha256)throw fail();state.state=record.state;state.httpReceiptSha256=record.httpReceiptSha256;}
   previous=record.recordSha256;
  }
  if(!same(states,manifest.journal.commands)||previous!==manifest.journal.lastRecordSha256||previous!==result.journalLastRecordSha256||previous!==expected.journalHeadSha256)throw fail();
  const originals:HostedLearningLoopNativeSelection['originals']=[];const companionPaths=new Set<string>();
  for(const state of states){const number=String(state.original.intentSequence).padStart(6,'0'),intentName=number+'.intent.json',intentPath=uiRoot+intentName,original=parsed(files,intentPath,intentSchema),entries=manifest.companions.filter(row=>row.path===intentName);used.add(intentPath);companionPaths.add(intentName);
   if(entries.length!==1||hash(files.get(intentPath)!)!==entries[0].sha256||!same(original.original,state.original)||original.operation!==state.original.command.operation||!same(original.sourceIds,state.original.command.sourceIds)||original.sourceRevision!==state.original.command.sourceRevision||original.requestBodySha256!==state.original.command.requestBodySha256)throw fail();
   const command=state.original.command,role=command.operation==='intelligence.policy.approve'?'admin':['activity.complete','submission.create','submission.draft','improvement.complete','portfolio.create'].includes(command.operation)?'student':'teacher';if(command.role!==role||command.actorId!==(role==='admin'?scope.adminId:role==='student'?scope.studentId:scope.teacherId))throw fail();
   const pathTargets:Record<typeof operations[number],RegExp>={'course.create':/^\/v1\/courses$/,'unit.create':/^\/v1\/courses\/([^/]+)\/units$/,'lesson.create':/^\/v1\/units\/([^/]+)\/lessons$/,'activity.create':/^\/v1\/lessons\/([^/]+)\/activities$/,'course.publish':/^\/v1\/courses\/([^/]+)\/publish$/,'assessment.create':/^\/v1\/assessments$/,'assessment.preparation':/^\/v1\/assessments\/([^/]+)\/preparation$/,'assessment.publish':/^\/v1\/assessments\/([^/]+)\/publish$/,'activity.complete':/^\/v1\/activities\/([^/]+)\/complete$/,'submission.draft':/^\/v1\/assessments\/([^/]+)\/draft$/,'submission.create':/^\/v1\/assessments\/([^/]+)\/submissions$/,'assessment.reference':/^\/v1\/assessments\/([^/]+)\/reference$/,'marking.create':/^\/v1\/submissions\/([^/]+)\/results$/,'result.release':/^\/v1\/results\/([^/]+)\/release$/,'intelligence.analyze':/^\/v1\/intelligence\/analyze$/,'improvement.decision':/^\/v1\/recommendations\/([^/]+)\/decision$/,'improvement.complete':/^\/v1\/interventions\/([^/]+)\/complete$/,'improvement.reassessment':/^\/v1\/interventions\/([^/]+)\/reassessment$/,'improvement.measure':/^\/v1\/interventions\/([^/]+)\/measure$/,'portfolio.create':/^\/v1\/portfolio\/items$/,'portfolio.review':/^\/v1\/portfolio\/items\/([^/]+)\/review$/,'portfolio.revoke':/^\/v1\/portfolio\/items\/([^/]+)\/parent-revoke$/,'intelligence.policy.approve':/^\/v1\/intelligence\/policy$/};
   const target=pathTargets[command.operation].exec(command.path);if(!target||original.targetId!==(target[1]??null)||original.targetId&&!command.sourceIds.includes(original.targetId))throw fail();
   const httpName=number+'.http.json',httpPath=uiRoot+httpName,httpExists=files.has(httpPath);let http:HostedLearningLoopNativeSelection['originals'][number]['http']=null;
   if(httpExists){const receipt=parsed(files,httpPath,httpSchema),entries=manifest.companions.filter(row=>row.path===httpName),stored=manifest.commands.filter(row=>row.original.intentRecordSha256===state.original.intentRecordSha256);used.add(httpPath);companionPaths.add(httpName);
    const observedOnly=expected.mode==='ORIGINAL_RECONCILIATION'&&stored.length===0&&state.httpReceiptSha256===null&&['UNCERTAIN','FORWARDING_AUTHORIZED'].includes(state.state);
    const storedPayload=stored[0]?{...stored[0]}:null;if(storedPayload)delete (storedPayload as Partial<typeof stored[0]>).companionSha256;if(entries.length!==1||hash(files.get(httpPath)!)!==entries[0].sha256||!observedOnly&&(stored.length!==1||!storedPayload||stored[0].companionSha256!==entries[0].sha256||!same(storedPayload,receipt)))throw fail();
    const metadata=(value:z.infer<typeof metadataSchema>)=>({operation:value.operation,targetId:value.targetId,sourceIds:value.sourceIds,sourceRevision:value.sourceRevision,requestBodySha256:value.requestBodySha256,nativeFingerprint:value.nativeFingerprint});
    if(!same(receipt.original,state.original)||receipt.originalCompanionSha256!==hash(files.get(intentPath)!)||!same(metadata(receipt),metadata(original))||!observedOnly&&(receipt.receiptSha256!==state.httpReceiptSha256||!['HTTP_CONFIRMED','UNCERTAIN'].includes(state.state)))throw fail();http={status:200,requestId:receipt.requestId,receiptSha256:receipt.receiptSha256,receiptIdentity:receipt.receiptIdentity};
   }else if(state.httpReceiptSha256!==null||state.state==='HTTP_CONFIRMED'||manifest.commands.some(row=>row.original.intentRecordSha256===state.original.intentRecordSha256))throw fail();
   originals.push({original:state.original,targetId:original.targetId,nativeFingerprint:original.nativeFingerprint,http});
  }
  if(!same([...companionPaths].sort(),manifest.companions.map(row=>row.path).sort())||new Set(manifest.companions.map(row=>row.path)).size!==manifest.companions.length||!same([...used].sort(),[...files.keys()].sort()))throw fail();
  if(expected.mode==='FULL_LOOP'&&(result.status!=='UI_LOOP_VERIFIED'||!result.sessionsClosed||result.roleSessions<5||result.roleSignouts!==result.roleSessions||result.unexpectedRequests||result.consoleErrors||result.consoleWarnings||result.pageErrors||!manifest.sourceLoop||!manifest.numericOutcome||!manifest.apiProjection||!manifest.expectedExecutionManifest||states.some(row=>row.state!=='HTTP_CONFIRMED')||originals.some(row=>row.http===null)))throw fail();
  if(expected.mode==='FULL_LOOP'){const loop=manifest.sourceLoop!,projection=manifest.apiProjection!;
   const required:Partial<Record<typeof operations[number],number>>={'course.create':1,'course.publish':1,'unit.create':1,'lesson.create':1,'activity.create':1,'activity.complete':1,'assessment.create':2,'assessment.preparation':2,'assessment.publish':2,'submission.draft':1,'submission.create':2,'marking.create':2,'result.release':2,'intelligence.analyze':1,'improvement.decision':1,'improvement.complete':1,'improvement.reassessment':1,'improvement.measure':1,'portfolio.create':1,'portfolio.review':1,'portfolio.revoke':1};
   for(const [operation,total]of Object.entries(required))if(originals.filter(row=>row.original.command.operation===operation).length!==total)throw fail();if(originals.filter(row=>row.original.command.operation==='assessment.reference').length>2||originals.filter(row=>row.original.command.operation==='intelligence.policy.approve').length>1)throw fail();
   const one=(operation:typeof operations[number],id:string)=>{const matches=originals.filter(row=>row.original.command.operation===operation&&row.http?.receiptIdentity.id===id);if(matches.length!==1)throw fail();return matches[0];};
   for(const [operation,id]of [['course.create',loop.course],['activity.complete',loop.learningCompletion],['result.release',loop.baseline],['result.release',loop.followUp],['intelligence.analyze',loop.proposal],['improvement.decision',loop.proposal],['improvement.complete',loop.intervention],['improvement.reassessment',loop.intervention],['improvement.measure',loop.outcome]] as const)one(operation,id);
   const baseline=one('result.release',loop.baseline).http!.receiptIdentity;if(baseline.evidenceId!==loop.evidence||baseline.learnerId!==scope.studentId||baseline.referenceId!==scope.referenceId||loop.baseline===loop.followUp||!projection.academicResultIds.includes(loop.baseline)||!projection.academicResultIds.includes(loop.followUp)||!projection.interventionIds.includes(loop.intervention)||!projection.measurementIds.includes(loop.outcome)||projection.sourceEventIds.length<5||Date.parse(projection.observedAt)>Date.parse(result.observedAt)||Date.parse(projection.generatedAt)>Date.parse(projection.observedAt)||Date.parse(projection.windowEnd)>Date.parse(projection.observedAt)||Date.parse(projection.observedAt)-Date.parse(projection.windowEnd)>60000)throw fail();
  }
  if(manifest.expectedExecutionManifest&&(manifest.expectedExecutionManifest.mode!=='FIXTURE'||manifest.expectedExecutionManifest.providerDataPolicy!=='HOSTED_SYNTHETIC_FIXTURE'))throw fail();if(manifest.apiProjection&&manifest.apiProjection.learnerId!==scope.studentId)throw fail();
  const sourceIds=[...new Set(originals.flatMap(row=>[...row.original.command.sourceIds,...Object.values(row.http?.receiptIdentity??{}).filter((value):value is string=>typeof value==='string'&&uuid.safeParse(value).success)]))].sort();if(sourceIds.length<1||sourceIds.length>32)throw fail();
  return{selection:{identity:{...identity,uiArtifactSha256:expected.archiveSha256,journalSha256:expected.journalHeadSha256,companionManifestSha256:expected.commandManifestSha256},scope,mode:expected.mode,originals},apiProjection:manifest.apiProjection,expectedExecutionManifest:manifest.expectedExecutionManifest,backendIdentity:backend,webAdmission:web,uiResult:result,sourceIds,scopeSha256:hash(canonicalReleaseExecutionJson({projectRef:identity.projectRef,...scope,sourceIds})),expiresAt:new Date(expires).toISOString(),status:expected.mode==='FULL_LOOP'?'UI_LOOP_VERIFIED':'ORIGINALS_RETAINED',officialAdmissionVerified:false,nativeExecutionVerified:false,uiArtifactSha256:expected.archiveSha256,commandManifestSha256:expected.commandManifestSha256,journalHeadSha256:expected.journalHeadSha256};
 }catch{throw fail();}
}

const inputSchema=z.object({repoRoot:z.string().min(1).max(2048),githubToken:z.string().min(1).max(24576).regex(/^[\x21-\x7e]+$/),releaseSha:sha,uiRunId:runId,uiRunAttempt:positive,artifactId:runId,commandManifestSha256:digest,journalHeadSha256:digest,mode}).strict();
const officialRunSchema=z.object({id:positive,run_attempt:positive,repository:z.object({full_name:repository}),head_sha:sha,head_branch:z.literal('main'),path:z.literal('.github/workflows/release.yml'),event:z.literal('workflow_dispatch'),status:z.literal('completed'),conclusion:z.enum(['success','failure','cancelled']),created_at:date,updated_at:date});
async function body(response:Response,signal:AbortSignal,maximum:number){if(!response.ok||response.redirected||!response.body)throw fail();const length=response.headers.get('content-length');if(length!==null&&(!/^\d+$/.test(length)||Number(length)>maximum))throw fail();const reader=response.body.getReader(),parts:Uint8Array[]=[];let size=0;try{for(;;){const part=await new Promise<ReadableStreamReadResult<Uint8Array>>((done,reject)=>{const abort=()=>{signal.removeEventListener('abort',abort);reject(fail());};if(signal.aborted)return abort();signal.addEventListener('abort',abort,{once:true});void reader.read().then(value=>{signal.removeEventListener('abort',abort);done(value);},()=>{signal.removeEventListener('abort',abort);reject(fail());});});if(signal.aborted)throw fail();if(part.done)break;size+=part.value.byteLength;if(size>maximum)throw fail();parts.push(part.value);}return Buffer.concat(parts);}finally{void reader.cancel().catch(()=>undefined);try{reader.releaseLock();}catch{/* Pending canceled reads own cleanup. */}}}

/** Actual read-only GitHub metadata/archive admission for the current dedicated
 * native-QA workflow's preparation or protected execution job. */
export type OfficialHostedLearningLoopUiArtifact=Omit<Awaited<ReturnType<typeof adaptHostedLearningLoopArtifactArchive>>,'officialAdmissionVerified'>&{officialAdmissionVerified:true;ui:{runId:string;runAttempt:number;artifactId:string;archiveSha256:string;commandManifestSha256:string;journalHeadSha256:string};sourceSha:string;treeSha:string;provenance:'OFFICIAL_UI_ARTIFACT_ADMISSION'};
declare const officialUiArtifactGuardBrand:unique symbol;
export type OfficialHostedLearningLoopUiArtifactGuard={admitted:OfficialHostedLearningLoopUiArtifact;assertOriginalValidity:()=>void;refreshOriginalMetadata:()=>Promise<void>;dispose:()=>void;readonly[officialUiArtifactGuardBrand]:true};
const uiArtifactGuards=new WeakMap<object,{binding:string;assert:()=>void;invalidate:()=>void}>();
export function consumeOfficialHostedLearningLoopUiArtifactGuard(value:unknown,selection:unknown){if(!value||typeof value!=='object'||types.isProxy(value))throw fail();const registered=uiArtifactGuards.get(value);if(!registered)throw fail();try{const input=inputSchema.omit({githubToken:true}).strict().parse(JSON.parse(canonicalReleaseExecutionJson(selection)));if(canonicalReleaseExecutionJson(input)!==registered.binding)throw fail();registered.assert();return value as OfficialHostedLearningLoopUiArtifactGuard;}catch{registered.invalidate();throw fail();}}
/** One UI archive is retained while each read repeats original metadata and source checks. */
export async function readOfficialHostedLearningLoopUiArtifactAndGuard(value:unknown):Promise<OfficialHostedLearningLoopUiArtifactGuard>{
 try{const input=inputSchema.parse(JSON.parse(canonicalReleaseExecutionJson(value))),repo=repository.parse(process.env.GITHUB_REPOSITORY),root=input.repoRoot,envNames=['GITHUB_REPOSITORY','GITHUB_ACTIONS','RUNNER_ENVIRONMENT','GITHUB_WORKSPACE','GITHUB_SHA','GITHUB_REF','GITHUB_EVENT_NAME','GITHUB_JOB','GITHUB_WORKFLOW_REF','GITHUB_SERVER_URL','GITHUB_API_URL','RELEASE_ENVIRONMENT','NODE_OPTIONS'],envSnapshot=JSON.stringify(envNames.map(name=>process.env[name]??null));
  const currentRunner=async()=>{if(process.platform!=='linux'||process.env.GITHUB_REPOSITORY!==repo||process.env.GITHUB_ACTIONS!=='true'||process.env.RUNNER_ENVIRONMENT!=='github-hosted'||!isAbsolute(root)||resolve(root)!==root||await realpath(root)!==root||!root.startsWith('/home/runner/work/')||process.env.GITHUB_WORKSPACE!==root||process.env.GITHUB_SHA!==input.releaseSha||process.env.GITHUB_REF!=='refs/heads/main'||process.env.GITHUB_EVENT_NAME!=='workflow_dispatch'||!['prepare-qa','native-qa'].includes(process.env.GITHUB_JOB??'')||process.env.GITHUB_WORKFLOW_REF!==repo+'/.github/workflows/hosted-learning-qa.yml@refs/heads/main'||process.env.GITHUB_SERVER_URL!=='https://github.com'||process.env.GITHUB_API_URL!=='https://api.github.com'||process.env.RELEASE_ENVIRONMENT!=='staging'||process.env.NODE_OPTIONS||JSON.stringify(envNames.map(name=>process.env[name]??null))!==envSnapshot)throw fail();};await currentRunner();
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),60000),url=(path:string)=>'https://api.github.com/repos/'+repo+'/'+path;let acquisition=true;
  const get=async(path:string)=>{const signal=AbortSignal.any([...(acquisition?[controller.signal]:[]),AbortSignal.timeout(15000)]),response=await fetch(url(path),{method:'GET',headers:{Authorization:'Bearer '+input.githubToken,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'},redirect:'error',cache:'no-store',credentials:'omit',signal});return JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(await body(response,signal,512*1024))) as unknown;};
  try{const rawRun=JSON.parse(canonicalReleaseExecutionJson(await get('actions/runs/'+input.uiRunId))),run=officialRunSchema.parse(rawRun);if(run.id!==Number(input.uiRunId)||run.run_attempt!==input.uiRunAttempt||run.repository.full_name!==repo||run.head_sha!==input.releaseSha||input.mode==='FULL_LOOP'&&run.conclusion!=='success')throw fail();
   const artifactSchema=z.object({id:positive,name:z.literal('cuevo-learning-loop-ui-'+input.uiRunId+'-'+input.uiRunAttempt),size_in_bytes:positive.refine(value=>value<=8*1024*1024),expired:z.literal(false),digest:z.string().regex(/^sha256:[a-f0-9]{64}$/),created_at:date,expires_at:date,workflow_run:z.object({id:z.literal(Number(input.uiRunId)),head_branch:z.literal('main'),head_sha:z.literal(input.releaseSha)})});
   const rawArtifact=JSON.parse(canonicalReleaseExecutionJson(await get('actions/artifacts/'+input.artifactId))),artifact=artifactSchema.parse(rawArtifact);if(artifact.id!==Number(input.artifactId)||Date.parse(artifact.created_at)<Date.parse(run.created_at)||Date.parse(artifact.created_at)>Date.parse(run.updated_at)||Date.parse(artifact.expires_at)<=Date.now())throw fail();
   const signal=AbortSignal.any([controller.signal,AbortSignal.timeout(20000)]);let response=await fetch(url('actions/artifacts/'+input.artifactId+'/zip'),{method:'GET',headers:{Authorization:'Bearer '+input.githubToken,Accept:'application/vnd.github+json'},redirect:'manual',cache:'no-store',credentials:'omit',signal});
   if(response.status===302){const target=new URL(response.headers.get('location')??'');void response.body?.cancel().catch(()=>undefined);if(target.protocol!=='https:'||target.username||target.password||target.port||target.hash||!(/^productionresultssa[a-z0-9]+\.blob\.core\.windows\.net$/.test(target.hostname)||/^[a-z0-9-]+\.actions\.githubusercontent\.com$/.test(target.hostname)))throw fail();response=await fetch(target,{method:'GET',redirect:'error',cache:'no-store',credentials:'omit',signal});}
   const bytes=await body(response,signal,8*1024*1024);if(bytes.byteLength!==artifact.size_in_bytes||hash(bytes)!==artifact.digest.slice(7))throw fail();
   const producerPath=join(root,'scripts/verification/backend-hosted-learning-loop.ts'),readProducer=async()=>{let parent=root;for(const part of ['scripts','verification','backend-hosted-learning-loop.ts']){parent=join(parent,part);const stat=await lstat(parent);if(stat.isSymbolicLink()||await realpath(parent)!==parent)throw fail();}const stat=await lstat(producerPath);if(!stat.isFile()||stat.nlink!==1||stat.size>1024*1024)throw fail();const producer=await readFile(producerPath),after=await lstat(producerPath);if(stat.dev!==after.dev||stat.ino!==after.ino||stat.size!==after.size||stat.mtimeMs!==after.mtimeMs||stat.ctimeMs!==after.ctimeMs)throw fail();return producer;},producer=await readProducer(),adapted=await adaptHostedLearningLoopArtifactArchive(bytes,{sourceSha:input.releaseSha,uiRunId:input.uiRunId,uiRunAttempt:input.uiRunAttempt,archiveSha256:artifact.digest.slice(7),commandManifestSha256:input.commandManifestSha256,journalHeadSha256:input.journalHeadSha256,producerSha256:hash(producer),mode:input.mode,now:Date.now()});
   if(adapted.backendIdentity.repository!==repo||Date.parse(adapted.uiResult.observedAt)<Date.parse(run.created_at)||Date.parse(adapted.uiResult.observedAt)>Date.parse(run.updated_at)||Date.parse(run.updated_at)>Date.now())throw fail();
   const admitted:OfficialHostedLearningLoopUiArtifact=JSON.parse(canonicalReleaseExecutionJson({...adapted,officialAdmissionVerified:true,ui:{runId:input.uiRunId,runAttempt:input.uiRunAttempt,artifactId:input.artifactId,archiveSha256:artifact.digest.slice(7),commandManifestSha256:input.commandManifestSha256,journalHeadSha256:input.journalHeadSha256},sourceSha:input.releaseSha,treeSha:adapted.selection.identity.treeSha,provenance:'OFFICIAL_UI_ARTIFACT_ADMISSION'})),originalEvidence=canonicalReleaseExecutionJson(admitted),runSnapshot=canonicalReleaseExecutionJson(rawRun),artifactSnapshot=canonicalReleaseExecutionJson(rawArtifact),expiresAtMs=Math.min(Date.parse(artifact.expires_at),Date.parse(adapted.expiresAt));let invalid=false,refreshing=false,disposed=false;
   const assertOriginalValidity=()=>{try{if(invalid||disposed||Date.now()>=expiresAtMs||JSON.stringify(envNames.map(name=>process.env[name]??null))!==envSnapshot||canonicalReleaseExecutionJson(admitted)!==originalEvidence)throw fail();}catch{invalid=true;throw fail();}};
   const refreshOriginalMetadata=async()=>{if(invalid||disposed||refreshing){invalid=true;throw fail();}refreshing=true;try{assertOriginalValidity();await currentRunner();const observed=await Promise.allSettled([get('actions/runs/'+input.uiRunId).then(raw=>canonicalReleaseExecutionJson(raw)),get('actions/artifacts/'+input.artifactId).then(raw=>canonicalReleaseExecutionJson(raw)),readProducer()]);if(observed[0].status!=='fulfilled'||observed[0].value!==runSnapshot||observed[1].status!=='fulfilled'||observed[1].value!==artifactSnapshot||observed[2].status!=='fulfilled'||!observed[2].value.equals(producer))throw fail();await currentRunner();if(!(await readProducer()).equals(producer))throw fail();await currentRunner();assertOriginalValidity();}catch{invalid=true;throw fail();}finally{refreshing=false;}};
   await refreshOriginalMetadata();if(controller.signal.aborted)throw fail();const{githubToken:_token,...binding}=input;void _token;const guard=Object.freeze({admitted,assertOriginalValidity,refreshOriginalMetadata,dispose:()=>{disposed=true;invalid=true;}}) as OfficialHostedLearningLoopUiArtifactGuard;uiArtifactGuards.set(guard,{binding:canonicalReleaseExecutionJson(binding),assert:()=>{if(refreshing){invalid=true;throw fail();}assertOriginalValidity();},invalidate:()=>{invalid=true;}});return guard;
  }finally{acquisition=false;clearTimeout(timer);controller.abort();}
 }catch{throw fail();}
}
export async function readOfficialHostedLearningLoopUiArtifact(value:unknown):Promise<OfficialHostedLearningLoopUiArtifact>{const guard=await readOfficialHostedLearningLoopUiArtifactAndGuard(value);try{return guard.admitted;}finally{guard.dispose();}}
