import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {test} from 'node:test';
import {createRequire} from 'node:module';
import type {Readable} from 'node:stream';
import {prepareBackendReleaseIntent} from './backend-release-contracts';
import {providerWorkerExportFixture} from './backend-hosted-activation-export.fixture';
import {canonicalReleaseExecutionJson} from './release-review';
const sha='a'.repeat(40),tree='b'.repeat(40),base='c'.repeat(40),project='abcdefghijklmnopqrst',wakeKey='d'.repeat(64),created='2026-10-07T12:00:00Z',execution='2026-10-07T12:01:00Z',closed='2026-10-07T12:01:01Z',now=Date.parse('2026-10-08T12:00:00Z');
const rawHash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),hash=(value:unknown)=>rawHash(canonicalReleaseExecutionJson(value)),bytes=(value:unknown)=>Buffer.from(canonicalReleaseExecutionJson(value)+'\n');
function originalWorkerExportFixture(){
 const fingerprints={sourceManifestSha256:'1'.repeat(64),diffSha256:'2'.repeat(64),migrationPlanSha256:'3'.repeat(64),migrationHistorySha256:'4'.repeat(64),migrationToolchainSha256:'5'.repeat(64),migrationEndpointSha256:'6'.repeat(64),operatorStoragePolicySha256:'7'.repeat(64),apiArtifactSha256:'8'.repeat(64),edgeArtifactSha256:'9'.repeat(64),denoLockSha256:'a'.repeat(64)},targets={web:{teamId:'team_Cuevo',projectId:'prj_Web',origin:'https://cuevo-web.vercel.app',target:'preview' as const},api:{teamId:'team_Cuevo',projectId:'prj_Api',origin:'https://cuevo-api.vercel.app',target:'preview' as const},supabase:{projectRef:project,authOrigin:`https://${project}.supabase.co`,edgeOrigin:`https://${project}.supabase.co/functions/v1/cuevo-worker`}},reviews=[{category:'source-spec-code' as const,taskId:'source-review',reportSha256:'b'.repeat(64),evidenceSha256:'c'.repeat(64)},{category:'qa-regression-operations' as const,taskId:'qa-review',reportSha256:'e'.repeat(64),evidenceSha256:'f'.repeat(64)}],identity={repository:'attaulhaq0/Cuevo',releaseSha:sha,treeSha:tree,baseSha:base,ciRunId:'31',releaseRunId:'51',runAttempt:1,environmentId:123,environmentName:'staging' as const,deploymentEnvironment:'synthetic-staging' as const,executionScope:'complete-backend' as const,canonicalRuntimeVerification:{runAttempt:2,jobsSha256:'b'.repeat(64)}};
 const expected={...identity,targets,fingerprints,reviews,now:Date.parse(execution),currentMainSha:sha,ciRun:{id:31,head_sha:sha,head_branch:'main' as const,event:'push' as const,status:'completed' as const,conclusion:'success' as const,path:'.github/workflows/ci.yml' as const,repository:{full_name:'attaulhaq0/Cuevo'}},backendRun:{id:51,run_attempt:1,head_sha:sha,head_branch:'main' as const,event:'workflow_dispatch' as const,status:'in_progress' as const,conclusion:null,path:'.github/workflows/backend-release.yml' as const,repository:{full_name:'attaulhaq0/Cuevo'}}};
 const body={version:1 as const,purpose:'BACKEND_SYNTHETIC_STAGING' as const,...identity,targets,fingerprints,preparedAt:'2026-10-07T11:59:00Z',expiresAt:'2026-10-07T12:59:00Z',reviews:reviews.map(row=>({...row,releaseSha:sha,treeSha:tree,baseSha:base,sourceManifestSha256:fingerprints.sourceManifestSha256,diffSha256:fingerprints.diffSha256,reviewedAt:'2026-10-07T11:58:00Z'}))},preparedApproval=prepareBackendReleaseIntent(body,expected),runtimeConfig={version:1,purpose:'CUEVO_HOSTED_RUNTIME_CONFIGURATION',sourceSha:sha,projectRef:project,privateCanary:'PRIVATE runtime-secret-canary'};
 const activeIdentity={sourceSha:sha,treeSha:tree,originalRunId:'51',originalRunAttempt:1,originalPackageSha256:preparedApproval.sha256,runtimeSha256:hash(runtimeConfig),apiDeploymentId:'dpl_fixture',apiUrl:'https://cuevo-api-fixture.vercel.app',edgeId:'edge_fixture',edgeVersion:1,activationId:'10000000-0000-4000-8000-000000000002',vaultSecretName:'cuevo_worker_10000000000040008000000000000002',endpoint:targets.supabase.edgeOrigin,createdAt:created},originalKey='worker-activation:51:1:'+activeIdentity.activationId,probeEvent='10000000-0000-4000-8000-000000000003',recoveryEvent='10000000-0000-4000-8000-000000000004',recovery={status:'SCHEDULED_RECOVERY_VERIFIED' as const,basis:'ACTUAL_CRON_AFTER_MISSED_POST_COMMIT_HINT' as const,originalKey:originalKey+':recovery',eventId:recoveryEvent,releasedAt:'2026-10-07T12:00:30Z',cronRunId:4,missedHintVerified:true as const,scheduledRecoveryVerified:true as const,eventRetryVerified:false as const,expiredLeaseRecoveryVerified:false as const,dispatchBackoffVerified:false as const,hostedAcceptance:false as const,elapsedMs:500};
 const activation={status:'ACTIVATED_SIGNED_SOURCE_VERIFIED',purpose:'CUEVO_HOSTED_WORKER_ACTIVATION',phase:'FINAL',observedAt:execution,runId:'51',runAttempt:1,apiDeploymentId:'dpl_fixture',packageSha256:preparedApproval.sha256,runtimeSha256:activeIdentity.runtimeSha256,keyOperation:'CONFIRMED',dispatchOperation:'CONFIRMED',dispatchDisabledOnFailure:null,sourceProcessed:true,duplicateWakeDenied:true,originalCommandReplayed:true,recoveryScheduled:true,scheduledRecoveryVerified:true,recovery,recoveryVerified:false,configurationEvidenceObservedManual:true,sessionsClosed:true,sourceSha:sha,projectRef:project,edgeVersion:1,jobId:42,probeEventId:probeEvent,hostedAcceptance:false,canonicalReceipt:null},cleanup={purpose:'CUEVO_HOSTED_WORKER_ACTIVATION_CLEANUP',status:activation.status,sourceSha:sha,projectRef:project,runId:'51',runAttempt:1,lockReleased:true,sessionsClosed:true,resultSha256:hash(activation),observedAt:closed},intent={version:1,purpose:activation.purpose,activationId:activeIdentity.activationId,sourceSha:sha,projectRef:project,packageSha256:preparedApproval.sha256,runtimeSha256:activeIdentity.runtimeSha256,apiDeploymentId:'dpl_fixture',edgeDeployment:{id:'edge_fixture',version:1},configurationEvidenceSha256:'e'.repeat(64),originalKey,endpoint:activeIdentity.endpoint,createdAt:created};
 const stages=[['INTENT_RECORDED',{}],['PRIVATE_PROBE_INTENT',{}],['PRIVATE_PROBES_CONFIRMED',{}],['KEY_PREPARED',{vaultSecretName:activeIdentity.vaultSecretName,keySha256:rawHash(wakeKey)}],['EDGE_KEY_INTENT',{}],['EDGE_KEY_CONFIRMED',{}],['DISPATCH_INTENT',{}],['DISPATCH_CONFIRMED',{vaultSecretId:'10000000-0000-4000-8000-000000000005'}],['SOURCE_COMMAND_INTENT',{originalKey,command:'school.details.update',bodySha256:'f'.repeat(64)}],['SOURCE_AND_WAKE_CONFIRMED',{eventId:probeEvent,sourceId:'10000000-0000-4000-8000-000000000006',wakeId:'10000000-0000-4000-8000-000000000007'}],['SIGNED_SOURCE_VERIFIED',{eventId:probeEvent}],['CRON_INTENT',{jobName:'cuevo-worker-recovery',schedule:'* * * * *',command:'select internal.request_worker_wake();'}],['CRON_PENDING_COMMIT',{jobId:42}],['CRON_CONFIRMED',{jobId:42}],['RECOVERY_SOURCE_INTENT',{originalKey:recovery.originalKey,jobId:42}],['RECOVERY_PENDING_RELEASE',{eventId:recoveryEvent}],['RECOVERY_RELEASE_CONFIRMED',{eventId:recoveryEvent,releasedAt:recovery.releasedAt}],['SCHEDULED_RECOVERY_VERIFIED',{eventId:recoveryEvent,cronRunId:4,releasedAt:recovery.releasedAt,elapsedMs:500}],['RECOVERY_RESULT',recovery],['ACTIVATION_VERIFIED',{}],['EXECUTION_FINAL',{status:activation.status,keyOperation:'CONFIRMED',dispatchOperation:'CONFIRMED',sessionsClosed:true}]] as const;
 const journal=stages.map(([phase,detail],index)=>({phase,at:index<16?created:index<19?recovery.releasedAt:execution,...detail}));
 return{expected,preparedApproval,identityBytes:bytes(activeIdentity),intentBytes:bytes(intent),activationBytes:bytes(activation),cleanupBytes:bytes(cleanup),journalBytes:Buffer.from(journal.map(row=>canonicalReleaseExecutionJson(row)+'\n').join('')),wakeKey,runtimeConfig,now};
}

async function subject(){let module:Record<string,unknown>={};try{module=await import('./backend-hosted-activation-export-admission');}catch(error){if((error as NodeJS.ErrnoException).code!=='ERR_MODULE_NOT_FOUND')throw error;}assert.equal(typeof module.readOriginalWorkerActivationExecutionAdmission,'function');return module as typeof import('./backend-hosted-activation-export-admission');}
const requiredNames=['Re-admit official founder package before private credentials','Verify signed worker execution and scheduled recovery','Export immutable original worker execution evidence','Retain original worker activation execution evidence'];
 const {yazl}=createRequire(import.meta.url)('playwright-core/lib/utilsBundle') as{yazl:{ZipFile:new()=>{outputStream:Readable;addBuffer(bytes:Buffer,name:string,options?:object):void;addEmptyDirectory(name:string):void;end():void}}};
function mutateZip(bytes:Buffer,mode:string){const output=Buffer.from(bytes);for(let index=0;index<output.length-4;index++){const signature=output.readUInt32LE(index);if(signature!==0x04034b50&&signature!==0x02014b50)continue;if(mode==='encrypted'){const at=index+(signature===0x04034b50?6:8);output.writeUInt16LE(output.readUInt16LE(at)|1,at);}else{const sizeAt=index+(signature===0x04034b50?26:28),nameAt=index+(signature===0x04034b50?30:46),size=output.readUInt16LE(sizeAt);Buffer.from(mode==='traversal'?'../'+ 'x'.repeat(size-3):'/'+ 'x'.repeat(size-1)).copy(output,nameAt);}}return output;}
async function zipFile(value:unknown,mode='valid'){
 const zip=new yazl.ZipFile(),parts:Buffer[]=[],finished=new Promise<Buffer>((done,reject)=>{zip.outputStream.on('data',part=>parts.push(part));zip.outputStream.on('error',reject);zip.outputStream.on('end',()=>done(Buffer.concat(parts)));});
 const content=mode==='invalid-json'?Buffer.from('{"bad":1,"bad":2}'):mode==='oversized'?Buffer.from('x'.repeat(256*1024+1)):Buffer.from(canonicalReleaseExecutionJson(value));
 zip.addBuffer(content,mode==='wrong-name'?'other.json':'worker-activation-execution-export.json',{mode:mode==='symlink'?0o120777:0o100644});
 if(mode==='extra')zip.addBuffer(Buffer.from('{}'),'extra.json');if(mode==='directory')zip.addEmptyDirectory('extra/');if(mode==='duplicate')zip.addBuffer(Buffer.from('{}'),'worker-activation-execution-export.json');zip.end();const completed=await finished;return ['encrypted','traversal','absolute'].includes(mode)?mutateZip(completed,mode):completed;
}
async function officialFixture(runConclusion='failure'){
 const pure=await import('./backend-hosted-activation-export-contracts'),input=originalWorkerExportFixture(),validated=pure.createOriginalWorkerActivationExecutionExport(input),envelope=validated.envelope;
 const run={id:51,run_attempt:1,head_sha:sha,head_branch:'main',repository:{full_name:'attaulhaq0/Cuevo'},path:'.github/workflows/backend-release.yml',event:'workflow_dispatch',status:'completed',conclusion:runConclusion,created_at:'2026-10-07T11:57:00Z',updated_at:'2026-10-07T12:02:00Z'};
 const approvals=[{environments:[{id:123,name:'staging'}],state:'approved',user:{id:95836629,login:'attaulhaq0',type:'User'},comment:input.preparedApproval.comment}];
 const stepTimes=[['2026-10-07T11:59:30Z','2026-10-07T11:59:35Z'],['2026-10-07T12:00:00Z','2026-10-07T12:01:10Z'],['2026-10-07T12:01:11Z','2026-10-07T12:01:21Z'],['2026-10-07T12:01:22Z','2026-10-07T12:01:30Z']];
 // This fixture exports historical execution while still inside its original job.
 envelope.exportedAt='2026-10-07T12:01:20Z';
 const exactArchive=await zipFile(envelope),artifact={id:71,name:'cuevo-worker-activation-execution-51-1',size_in_bytes:exactArchive.length,expired:false,digest:'sha256:'+rawHash(exactArchive),created_at:'2026-10-07T12:01:25Z',expires_at:'2026-10-21T12:01:25Z',workflow_run:{id:51,head_sha:sha,head_branch:'main'}};
 const jobs={total_count:1,jobs:[{id:61,name:'schema',run_id:51,run_attempt:1,head_sha:sha,head_branch:'main',status:'completed',conclusion:runConclusion,started_at:'2026-10-07T11:59:20Z',completed_at:'2026-10-07T12:01:50Z',steps:requiredNames.map((name,index)=>({name,number:index+1,status:'completed',conclusion:index===1?runConclusion:'success',started_at:stepTimes[index][0],completed_at:stepTimes[index][1]}))}]};
 const selection={repository:'attaulhaq0/Cuevo' as const,sourceSha:sha,originalRunId:'51',runAttempt:1,artifactId:'71',exportJsonSha256:hash(envelope),now};
 return{input,envelope,run,approvals,artifact,jobs,selection,archive:exactArchive};
}
function readerFor(value:Awaited<ReturnType<typeof officialFixture>>,mutate?:(path:string,call:number,value:unknown)=>unknown){const calls=new Map<string,number>();return async(path:string)=>{const call=(calls.get(path)??0)+1;calls.set(path,call);const row=path==='actions/runs/51'?value.run:path==='actions/artifacts/71'?value.artifact:path==='actions/runs/51/attempts/1/jobs?per_page=100&page=1'?value.jobs:path==='actions/runs/51/approvals'?value.approvals:undefined;if(row===undefined)throw Error('Unexpected fixed metadata read');return structuredClone(mutate?mutate(path,call,row):row);};}

test('historical admission exports are available before a metadata reader can certify original evidence',async()=>{await subject();});

test('terminal original failure and success preserve exact original approval without current effect authority',async()=>{
 const api=await subject();for(const conclusion of ['failure','success']){const value=await officialFixture(conclusion),before=canonicalReleaseExecutionJson(value.run),result=api.validateOriginalWorkerActivationExecutionApproval(value.run,value.approvals,value.envelope,now);
  assert.equal(result.originalFounderId,95836629);assert.equal(result.effectAuthority,false);assert.equal(result.original.originalRunId,'51');assert.equal(canonicalReleaseExecutionJson(value.run),before);
  const admitted=await api.readOriginalWorkerActivationExecutionEvidence(value.selection,readerFor(value),async id=>{assert.equal(id,71);return value.archive;});assert.equal(admitted.effectAuthority,false);assert.equal(admitted.artifactId,'71');assert.equal(admitted.exportJsonSha256,value.selection.exportJsonSha256);assert.equal(admitted.envelope.originalCleanup.observedAt,closed);
 }
});

test('historical run approval and immutable execution conflicts refuse without rewriting original status',async()=>{
 const api=await subject();for(const mode of ['cancelled','timed_out','skipped','in_progress','source','attempt','run','workflow','branch','future','founder','login','type','comment','environment','duplicate','pending','execution','cleanup','canary']){
  const value=await officialFixture();if(['cancelled','timed_out','skipped'].includes(mode))value.run.conclusion=mode;else if(mode==='in_progress')value.run.status=mode;else if(mode==='source')value.run.head_sha='f'.repeat(40);else if(mode==='attempt')value.run.run_attempt=2;else if(mode==='run')value.run.id=52;else if(mode==='workflow')value.run.path='.github/workflows/release.yml';else if(mode==='branch')value.run.head_branch='candidate';else if(mode==='future')value.run.updated_at='2099-01-01T00:00:00Z';else if(mode==='founder')value.approvals[0].user.id=1;else if(mode==='login')value.approvals[0].user.login='other';else if(mode==='type')value.approvals[0].user.type='Bot';else if(mode==='comment')value.approvals[0].comment='approved';else if(mode==='environment')value.approvals[0].environments[0].name='production';else if(mode==='duplicate')value.approvals.push(value.approvals[0]);else if(mode==='pending')value.approvals[0].state='pending';else if(mode==='execution')value.envelope.originalActivation.sourceProcessed=false as true;else if(mode==='cleanup')value.envelope.originalCleanup.lockReleased=false as true;else Object.assign(value.envelope,{privateCanary:'PRIVATE export canary'});
  assert.throws(()=>api.validateOriginalWorkerActivationExecutionApproval(value.run,value.approvals,value.envelope,now),mode);
 }
});

test('artifact identity expiry step discovery clocks and stable second reads are required',async()=>{
 const api=await subject();for(const mode of ['name','id','expired','expiry','size','digest','artifact-source','artifact-run','artifact-time','skip-export','skip-approval','cancel-activate','missing-activate','step-order','duplicate-step','duplicate-job','attempt-job','source-job','run-drift','artifact-drift','jobs-drift','approvals-drift']){
  const value=await officialFixture();if(mode==='name')value.artifact.name='cuevo-backend-schema-result-51-1';else if(mode==='id')value.artifact.id=72;else if(mode==='expired')value.artifact.expired=true;else if(mode==='expiry')value.artifact.expires_at='2026-10-08T11:59:59Z';else if(mode==='size')value.artifact.size_in_bytes++;else if(mode==='digest')value.artifact.digest='sha256:'+'f'.repeat(64);else if(mode==='artifact-source')value.artifact.workflow_run.head_sha='f'.repeat(40);else if(mode==='artifact-run')value.artifact.workflow_run.id=52;else if(mode==='artifact-time')value.artifact.created_at='2026-10-07T12:00:50Z';else if(mode==='skip-export')value.jobs.jobs[0].steps[2].conclusion='skipped';else if(mode==='skip-approval')value.jobs.jobs[0].steps[0].conclusion='skipped';else if(mode==='cancel-activate')value.jobs.jobs[0].steps[1].conclusion='cancelled';else if(mode==='missing-activate')value.jobs.jobs[0].steps.splice(1,1);else if(mode==='step-order')value.jobs.jobs[0].steps.reverse();else if(mode==='duplicate-step')value.jobs.jobs[0].steps.push(value.jobs.jobs[0].steps[2]);else if(mode==='duplicate-job'){value.jobs.jobs.push(value.jobs.jobs[0]);value.jobs.total_count++;}else if(mode==='attempt-job')value.jobs.jobs[0].run_attempt=2;else if(mode==='source-job')value.jobs.jobs[0].head_sha='f'.repeat(40);
  const drift=mode.endsWith('-drift')?mode.split('-')[0]:null,reader=readerFor(value,(path,call,row)=>call===2&&((drift==='run'&&path==='actions/runs/51')||(drift==='artifact'&&path==='actions/artifacts/71')||(drift==='jobs'&&path.includes('/jobs'))||(drift==='approvals'&&path.endsWith('/approvals')))?Array.isArray(row)?[...row,{changed:true}]:{...row as object,changed:true}:row);
  await assert.rejects(api.readOriginalWorkerActivationExecutionEvidence(value.selection,reader,async()=>value.archive),mode);
 }
});

test('historical approval has no caller verification flag and native evidence cannot predate its protected execution',async()=>{
 const api=await subject();for(const mode of ['selection-flag','repository','artifact-before-export','job-before-run','job-after-run','step-before-job','step-no-clock','approval-after-activation','export-before-cleanup','export-before-step','upload-before-export','matching-two-environments','unrelated-approval','duplicate-artifact-clock']){
  const value=await officialFixture();let selection:unknown=value.selection;
  if(mode==='selection-flag')selection={...value.selection,verified:true};else if(mode==='repository')selection={...value.selection,repository:'other/Cuevo'};else if(mode==='artifact-before-export')value.artifact.created_at='2026-10-07T12:01:19Z';else if(mode==='job-before-run')value.jobs.jobs[0].started_at='2026-10-07T11:56:00Z';else if(mode==='job-after-run')value.jobs.jobs[0].completed_at='2026-10-07T12:03:00Z';else if(mode==='step-before-job')value.jobs.jobs[0].steps[0].started_at='2026-10-07T11:59:19Z';else if(mode==='step-no-clock')(value.jobs.jobs[0].steps[0] as {started_at:string|null}).started_at=null;else if(mode==='approval-after-activation')value.jobs.jobs[0].steps[0].completed_at='2026-10-07T12:00:01Z';else if(mode==='export-before-cleanup')value.envelope.exportedAt='2026-10-07T12:01:00Z';else if(mode==='export-before-step')value.envelope.exportedAt='2026-10-07T12:01:10Z';else if(mode==='upload-before-export')value.jobs.jobs[0].steps[3].started_at='2026-10-07T12:01:19Z';else if(mode==='matching-two-environments')value.approvals[0].environments.push({id:124,name:'production'});else if(mode==='unrelated-approval')value.approvals[0].environments[0]={id:124,name:'production'};else value.artifact.expires_at=value.artifact.created_at;
  value.archive=await zipFile(value.envelope);value.artifact.size_in_bytes=value.archive.length;value.artifact.digest='sha256:'+rawHash(value.archive);value.selection.exportJsonSha256=hash(value.envelope);
  await assert.rejects(api.readOriginalWorkerActivationExecutionEvidence(selection as typeof value.selection,readerFor(value),async()=>value.archive),mode);
 }
});

test('only the fixed bounded canonical export member can enter historical admission',async()=>{
 const api=await subject();for(const mode of ['extra','directory','duplicate','wrong-name','symlink','encrypted','traversal','absolute','invalid-json','oversized','private-canary']){const value=await officialFixture();const envelope=mode==='private-canary'?{...value.envelope,private:'PRIVATE_CANARY'}:value.envelope,archive=await zipFile(envelope,mode);value.artifact.size_in_bytes=archive.length;value.artifact.digest='sha256:'+rawHash(archive);
  await assert.rejects(api.readOriginalWorkerActivationExecutionEvidence(value.selection,readerFor(value),async()=>archive),mode);
 }
});

test('native export fractions agree with whole-second official metadata without renewing clocks',async()=>{
 const api=await subject(),value=await officialFixture();value.envelope.exportedAt='2026-10-07T12:01:21.500Z';value.jobs.jobs[0].steps[3].started_at='2026-10-07T12:01:21Z';value.artifact.created_at='2026-10-07T12:01:21Z';value.archive=await zipFile(value.envelope);value.artifact.size_in_bytes=value.archive.length;value.artifact.digest='sha256:'+rawHash(value.archive);value.selection.exportJsonSha256=hash(value.envelope);
 const admitted=await api.readOriginalWorkerActivationExecutionEvidence(value.selection,readerFor(value),async()=>value.archive);assert.equal(admitted.envelope.exportedAt,'2026-10-07T12:01:21.500Z');assert.equal(admitted.envelope.originalCleanup.observedAt,closed);
 value.envelope.exportedAt='2026-10-07T12:01:22.500Z';value.archive=await zipFile(value.envelope);value.artifact.size_in_bytes=value.archive.length;value.artifact.digest='sha256:'+rawHash(value.archive);value.selection.exportJsonSha256=hash(value.envelope);
 await assert.rejects(api.readOriginalWorkerActivationExecutionEvidence(value.selection,readerFor(value),async()=>value.archive));
});

test('native wrapper uses fixed GETs and never forwards its GitHub canary to signed artifact hosts',async()=>{
 const api=await subject(),value=await officialFixture(),token='PRIVATE_original_GitHub_canary',originalFetch=globalThis.fetch,originalNow=Date.now,requests:{url:string;authorization:string|null}[]=[];Date.now=()=>now;
 globalThis.fetch=async(raw,options)=>{const url=new URL(String(raw)),headers=new Headers(options?.headers);requests.push({url:String(raw),authorization:headers.get('Authorization')});assert.equal(options?.method,'GET');assert.equal(options?.body,undefined);
  if(url.hostname==='productionresultssa123.blob.core.windows.net'){assert.equal(headers.get('Authorization'),null);return new Response(new Uint8Array(value.archive));}assert.equal(url.origin,'https://api.github.com');assert.equal(headers.get('Authorization'),'Bearer '+token);if(url.pathname.endsWith('/zip'))return new Response(null,{status:302,headers:{location:'https://productionresultssa123.blob.core.windows.net/signed?token=fixture'}});return Response.json(await readerFor(value)(url.pathname.slice('/repos/attaulhaq0/Cuevo/'.length)+url.search));};
 try{const {now:_now,...selection}=value.selection;void _now;const result=await api.readOriginalWorkerActivationExecutionAdmission({...selection,githubToken:token});assert.equal(result.evidence,'OFFICIAL_ORIGINAL_WORKER_EXECUTION_METADATA');assert.equal(result.effectAuthority,false);assert.equal(JSON.stringify(result).includes(token),false);assert(requests.some(row=>row.url.startsWith('https://productionresultssa')));}
 finally{globalThis.fetch=originalFetch;Date.now=originalNow;}
});

test('native wrapper refuses foreign signed-host redirects and credential canaries stay withheld',async()=>{
 const api=await subject(),value=await officialFixture(),token='PRIVATE_canary_redirect_token',originalFetch=globalThis.fetch,originalNow=Date.now;Date.now=()=>now;
 try{for(const target of ['https://evil.invalid/private','http://productionresultssa123.blob.core.windows.net/file','https://user:password@productionresultssa123.blob.core.windows.net/file']){
  globalThis.fetch=async(raw,options)=>{const url=new URL(String(raw));assert.equal(url.origin,'https://api.github.com');assert.equal(new Headers(options?.headers).get('Authorization'),'Bearer '+token);if(url.pathname.endsWith('/zip'))return new Response(null,{status:302,headers:{location:target}});return Response.json(await readerFor(value)(url.pathname.slice('/repos/attaulhaq0/Cuevo/'.length)+url.search));};
  const {now:_now,...selection}=value.selection;void _now;await assert.rejects(api.readOriginalWorkerActivationExecutionAdmission({...selection,githubToken:token}),error=>!String(error).includes(token));
 }}finally{globalThis.fetch=originalFetch;Date.now=originalNow;}
});


test('official original approval admits provider version two without converting it to manual evidence',async()=>{const api=await subject(),value=await officialFixture(),contracts=await import('./backend-hosted-activation-export-contracts'),fixture=providerWorkerExportFixture(),exported=contracts.createOriginalWorkerActivationExecutionExport(fixture);const result=api.validateOriginalWorkerActivationExecutionApproval({...value.run,updated_at:exported.envelope.exportedAt},[{...value.approvals[0],comment:fixture.preparedApproval.comment}],exported.envelope,now);assert.equal(result.envelope.version,2);assert.equal(result.envelope.originalActivation.configurationEvidenceObservedManual,false);assert.equal(result.effectAuthority,false);});
