import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { canonicalReleaseExecutionJson } from './release-review';

const uuid=z.uuid();
const inputSchema=z.object({releaseGeneration:z.string().regex(/^[1-9][0-9]{0,18}$/).refine(value=>BigInt(value)<=9223372036854775807n).optional(),schoolId:uuid,actorId:uuid,endpoint:z.string().url(),vaultSecretName:z.string().regex(/^[A-Za-z][A-Za-z0-9_-]{0,99}$/),jobId:z.number().int().positive(),originalKey:z.string().min(1).max(160),body:z.object({name:z.string().min(1),countryCode:z.string().regex(/^[A-Z]{2}$/),languages:z.array(z.enum(['en','ar'])).min(1).max(2)}).strict()}).strict();
export type WorkerFaultRecoveryInput=z.infer<typeof inputSchema>;
export type WorkerFaultRecoveryPorts={operatorQuery(sql:string,args?:unknown[]):Promise<{rows:Record<string,unknown>[]}>;workerQuery(sql:string,args?:unknown[]):Promise<{rows:Record<string,unknown>[]}>;workerTlsVerified:boolean;command(body:WorkerFaultRecoveryInput['body'],originalKey:string):Promise<unknown>;admit():Promise<void>;record(phase:string,detail:Record<string,unknown>):Promise<void>;now():number;pause():Promise<void>};
export type WorkerFaultRecoveryResult={status:'FAULT_RECOVERY_VERIFIED'|'REQUIRES_REVIEW';basis:'ORIGINAL_WORKER_LEASE_RETRY_REVIEW_BACKOFF';originalKey:string;eventIds:string[];expiredLeaseRecoveryVerified:boolean;eventRetryVerified:boolean;dispatchBackoffVerified:boolean;faultInjectionBasis:'EXACT_SYNTHETIC_REQUESTED_GENERATION';cleanupStatus:'RELEASED'|'REQUIRES_REVIEW';hostedAcceptance:false};
const fail=()=>Error('Hosted worker fault recovery requires review; private contents withheld.');
export const workerFaultControlSql=`/* CUEVO_FAULT_CONTROL */ select enabled,endpoint,vault_secret_name,allow_local,state,wake_id,lease_expires_at::text,network_request_id,next_attempt_at::text,failure_count,last_error_code,last_requested_at::text,last_started_at::text,last_finished_at::text,last_processed_count from internal.worker_dispatch_control where singleton`;
const eventSql=`/* CUEVO_FAULT_EVENT */ select e.id,e.school_id,e.actor_id,e.entity_id,e.entity_type,e.type,e.version,e.metadata,e.deduplication_key,e.occurred_at::text,e.state,e.attempt_count,e.max_attempts,e.available_at::text,e.lease_token,e.lease_until::text,e.completed_at::text,e.last_error_code,exists(select 1 from internal.processed_events p where p.event_id=e.id)as processed,exists(select 1 from internal.audit_events a join internal.idempotency_keys k on k.school_id=a.school_id and k.actor_id=a.actor_id and k.key=$3 and k.command='school.details.update'where a.school_id=e.school_id and a.actor_id=e.actor_id and a.entity_id=e.entity_id and a.action='school.details.update'and a.outcome='succeeded'and a.entity_type='school_operation'and a.metadata=jsonb_build_object('command','details.update')and a.occurred_at>=k.created_at and a.occurred_at<=k.completed_at and a.occurred_at<=e.occurred_at)as audit,(select count(*)::integer from internal.idempotency_keys k where k.school_id=e.school_id and k.actor_id=e.actor_id and k.key=$3 and k.command='school.details.update'and k.state='COMPLETED'and k.response->>'id'=e.entity_id::text)as command_count from internal.outbox_events e where e.school_id=$1 and e.entity_id=$2 and e.actor_id=$4 and e.type='school.updated'and e.entity_type='school_operation'and e.metadata=jsonb_build_object('command','details.update')and e.deduplication_key='school:'||md5(e.actor_id::text||':details.update:'||$3)`;
const stamp=(value:unknown)=>typeof value==='string'?Date.parse(value):value instanceof Date?value.getTime():NaN;
const envelope=(row:Record<string,unknown>)=>canonicalReleaseExecutionJson(Object.fromEntries(['id','school_id','actor_id','entity_id','entity_type','type','version','metadata','deduplication_key','occurred_at'].map(key=>[key,row[key]])));
const acknowledged=(value:unknown)=>z.object({rows:z.array(z.object({process_learner_event:z.object({status:z.literal('ACKNOWLEDGED')}).strict()}).strict()).length(1)}).safeParse(value).success;

/** Native query ports must be backed by separate peer-verified operator and real
 * cuevo_worker sessions. Fault injection is only one exact synthetic generation;
 * original source, audit, attempts, leases and processed history are never reset. */
export async function verifyWorkerFaultRecovery(value:unknown,ports:WorkerFaultRecoveryPorts):Promise<WorkerFaultRecoveryResult>{
 const r:WorkerFaultRecoveryResult={status:'REQUIRES_REVIEW',basis:'ORIGINAL_WORKER_LEASE_RETRY_REVIEW_BACKOFF',originalKey:'',eventIds:[],expiredLeaseRecoveryVerified:false,eventRetryVerified:false,dispatchBackoffVerified:false,faultInjectionBasis:'EXACT_SYNTHETIC_REQUESTED_GENERATION',cleanupStatus:'RELEASED',hostedAcceptance:false};let operatorTransaction=false,workerTransaction=false;
 try{
  const input=inputSchema.parse(JSON.parse(canonicalReleaseExecutionJson(value)));r.originalKey=input.originalKey;if(!ports.workerTlsVerified)throw fail();
  const op=async(sql:string,args:unknown[]=[])=>{const rows=(await ports.operatorQuery(sql,args)).rows;if(rows.length!==1)throw fail();return rows[0];};
  const worker=async(sql:string,args:unknown[]=[])=>{const rows=(await ports.workerQuery(sql,args)).rows;if(rows.length!==1)throw fail();return rows[0];};
  const owns=(c:Record<string,unknown>)=>c.enabled===true&&c.endpoint===input.endpoint&&c.vault_secret_name===input.vaultSecretName&&c.allow_local===false;
  const idle=(c:Record<string,unknown>)=>owns(c)&&c.state==='IDLE'&&c.wake_id===null&&c.lease_expires_at===null&&c.network_request_id===null&&c.failure_count===0&&c.last_error_code===null;
  await ports.admit();const identity=await worker(`/* CUEVO_FAULT_WORKER_IDENTITY */ select current_user::text as role,session_user::text as "sessionRole",current_database()::text as database,(select not rolsuper and not rolbypassrls and not rolcreaterole and not rolcreatedb and not rolreplication and not rolinherit from pg_roles where rolname=current_user)as restricted,(internal.worker_health()->>'ready')::boolean as ready`);if(identity.role!=='cuevo_worker'||identity.sessionRole!=='cuevo_worker'||identity.database!=='postgres'||identity.restricted!==true||identity.ready!==true)throw fail();
  const checkJob=async()=>{const rows=(await ports.operatorQuery(`/* CUEVO_FAULT_CRON */ select jobid,jobname,schedule,command,database,username,active from cron.job where jobid=$1 or(active and(command ilike '%request_worker_wake%'or jobname ilike 'cuevo%'))`,[input.jobId])).rows;if(rows.length!==1)throw fail();z.object({jobid:z.coerce.number().refine(n=>n===input.jobId),jobname:z.literal('cuevo-worker-recovery'),schedule:z.literal('* * * * *'),command:z.literal('select internal.request_worker_wake();'),database:z.literal('postgres'),username:z.literal('postgres'),active:z.literal(true)}).parse(rows[0]);};await checkJob();
  const now=async()=>stamp((await op(`/* CUEVO_FAULT_DB_TIME */ select to_char(clock_timestamp()at time zone'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')as now`)).now);
  const wait=async(predicate:()=>Promise<boolean>,milliseconds:number)=>{const end=ports.now()+milliseconds;for(let count=0;count<180&&ports.now()<end;count++){if(await predicate())return;await ports.pause();}throw fail();};
  const read=(key:string)=>op(eventSql,[input.schoolId,input.schoolId,key,input.actorId]);
  const queue=async(eventId:string)=>{const q=await op(`/* CUEVO_FAULT_OWNED_QUEUE */ select count(*)::integer as "foreignWork" from internal.outbox_events where internal.outbox_event_owner(type)='WORKER'and state in('PENDING','PROCESSING')and id<>$1`,[eventId]);if(q.foreignWork!==0)throw fail();};
  const claim=async(source:Record<string,unknown>,key:string,seconds:number)=>{
   await queue(String(source.id));await ports.workerQuery('BEGIN');workerTransaction=true;
   const rows=(await ports.workerQuery(input.releaseGeneration?'select *from internal.claim_outbox($1,$2,$3::bigint)':'select *from internal.claim_outbox($1,$2)',input.releaseGeneration?[1,seconds,input.releaseGeneration]:[1,seconds])).rows;
   if(rows.length!==1||rows[0].id!==source.id||rows[0].school_id!==input.schoolId||rows[0].actor_id!==input.actorId||rows[0].type!=='school.updated'||rows[0].entity_id!==input.schoolId||rows[0].version!==1)throw fail();
   uuid.parse(rows[0].lease_token);await queue(String(source.id));await ports.record('WORKER_CLAIM_PENDING_COMMIT',{eventId:source.id,originalKey:key,attemptCount:rows[0].attempt_count});await ports.workerQuery('COMMIT');workerTransaction=false;return rows[0];
  };
  const prepare=async(kind:string)=>{
   const c=await op(workerFaultControlSql);if(!idle(c))throw fail();const baseline=await op(`/* CUEVO_FAULT_BASELINE */ select count(*)filter(where state='PENDING')::integer as pending,count(*)filter(where state='PROCESSING')::integer as processing,count(*)filter(where state='FAILED')::integer as failed,internal.worker_transport_private()as "transportPrivate",not exists(select 1 from internal.posthog_school_activation where enabled)as "analyticsDisabled",(select bool_and(synthetic)from app.people)as synthetic from internal.outbox_events where internal.outbox_event_owner(type)='WORKER'`);if(baseline.pending!==0||baseline.processing!==0||baseline.transportPrivate!==true||baseline.analyticsDisabled!==true||baseline.synthetic!==true)throw fail();
   // KEY SHARE excludes wake/pause UPDATE admission while allowing the
   // generation-fenced worker's SHARE claim on this separate session.
   const key=input.originalKey+':'+kind;await ports.record('FAULT_SOURCE_INTENT',{kind,originalKey:key});await ports.operatorQuery('BEGIN');operatorTransaction=true;const held=await op(workerFaultControlSql+' for key share');if(!idle(held))throw fail();
   const receipt=await ports.command(input.body,key);z.object({id:z.literal(input.schoolId),schoolId:z.literal(input.schoolId),command:z.literal('details.update')}).parse(receipt);const replay=await ports.command(input.body,key);if(canonicalReleaseExecutionJson(replay)!==canonicalReleaseExecutionJson(receipt))throw fail();
   const e=await read(key);if(e.school_id!==input.schoolId||e.actor_id!==input.actorId||e.entity_id!==input.schoolId||e.type!=='school.updated'||e.entity_type!=='school_operation'||e.version!==1||e.state!=='PENDING'||e.attempt_count!==0||e.lease_token!==null||e.lease_until!==null||e.processed!==false||e.audit!==true||e.command_count!==1||Number(e.max_attempts)<2)throw fail();r.eventIds.push(uuid.parse(e.id));await queue(String(e.id));await ports.record('FAULT_SOURCE_COMMITTED',{kind,eventId:e.id,originalKey:key});return{key,e,basis:envelope(e)};
  };
  const confirm=async(probe:{key:string;e:Record<string,unknown>;basis:string},token:string)=>{
   await ports.workerQuery('BEGIN');workerTransaction=true;const response=await ports.workerQuery('select internal.process_learner_event($1,$2)',[probe.e.id,token]);if(!acknowledged(response))throw fail();await ports.workerQuery('COMMIT');workerTransaction=false;
   const completed=await read(probe.key);if(envelope(completed)!==probe.basis||completed.state!=='COMPLETED'||completed.processed!==true||completed.audit!==true||completed.command_count!==1||completed.lease_token!==null)throw fail();
   await ports.operatorQuery('COMMIT');operatorTransaction=false;await ports.record('FAULT_SOURCE_PROCESSED',{eventId:probe.e.id,originalKey:probe.key});
  };
  const expired=await prepare('lease'),first=await claim(expired.e,expired.key,5);if(first.attempt_count!==1)throw fail();const leased=await read(expired.key);if(leased.lease_token!==first.lease_token||stamp(leased.lease_until)<await now())throw fail();await wait(async()=>await now()>stamp(leased.lease_until),12000);
  await ports.workerQuery('BEGIN');workerTransaction=true;let staleDenied=false;try{await ports.workerQuery('select internal.process_learner_event($1,$2)',[expired.e.id,first.lease_token]);}catch(error){staleDenied=(error as{code?:string}).code==='22023';}await ports.workerQuery('ROLLBACK');workerTransaction=false;if(!staleDenied)throw fail();
  const second=await claim(expired.e,expired.key,30);if(second.lease_token===first.lease_token||second.attempt_count!==2)throw fail();await confirm(expired,String(second.lease_token));r.expiredLeaseRecoveryVerified=true;
  const retry=await prepare('retry'),attempt=await claim(retry.e,retry.key,30);await ports.workerQuery('BEGIN');workerTransaction=true;const failed=await worker('select internal.fail_outbox($1,$2,$3,$4)as acknowledged',[retry.e.id,attempt.lease_token,'PROCESSING_REQUIRES_REVIEW',5]);if(failed.acknowledged!==true)throw fail();await ports.workerQuery('COMMIT');workerTransaction=false;
  const pending=await read(retry.key);if(pending.state!=='PENDING'||pending.attempt_count!==1||pending.lease_token!==null||pending.last_error_code!=='PROCESSING_REQUIRES_REVIEW'||stamp(pending.available_at)<=await now())throw fail();await queue(String(retry.e.id));await ports.workerQuery('BEGIN');workerTransaction=true;const premature=(await ports.workerQuery(input.releaseGeneration?'select *from internal.claim_outbox($1,$2,$3::bigint)':'select *from internal.claim_outbox($1,$2)',input.releaseGeneration?[1,30,input.releaseGeneration]:[1,30])).rows;await ports.workerQuery('ROLLBACK');workerTransaction=false;if(premature.length)throw fail();await wait(async()=>await now()>=stamp(pending.available_at),12000);const retried=await claim(retry.e,retry.key,30);if(retried.attempt_count!==2||retried.lease_token===attempt.lease_token)throw fail();await confirm(retry,String(retried.lease_token));r.eventRetryVerified=true;
  const backoff=await prepare('backoff'),generation=randomUUID();await ports.record('EXACT_GENERATION_FAULT_INTENT',{eventId:backoff.e.id,wakeId:generation,basis:r.faultInjectionBasis});
  const injected=await op(`/* CUEVO_FAULT_GENERATION */ update internal.worker_dispatch_control set state='REQUESTED',wake_id=$1,lease_expires_at=clock_timestamp()+interval'60 seconds',network_request_id=null,last_requested_at=clock_timestamp()where singleton and enabled and endpoint=$2 and vault_secret_name=$3 and not allow_local and state='IDLE'and wake_id is null and failure_count=0 returning true as injected`,[generation,input.endpoint,input.vaultSecretName]);if(injected.injected!==true)throw fail();await ports.operatorQuery('COMMIT');operatorTransaction=false;
  const admitted=await worker(input.releaseGeneration?'select internal.begin_worker_wake($1,$2::bigint)as admitted':'select internal.begin_worker_wake($1)as admitted',input.releaseGeneration?[generation,input.releaseGeneration]:[generation]);if(admitted.admitted!==true)throw fail();const review=await worker('select internal.finish_worker_wake($1,$2,$3)as receipt',[generation,'REQUIRES_REVIEW',0]);if(review.receipt!==true)throw fail();
  const delayed=await op(`/* CUEVO_FAULT_BACKOFF */ select state,failure_count as "failureCount",last_error_code as "lastErrorCode",extract(epoch from(next_attempt_at-last_finished_at))as "waitSeconds",next_attempt_at>clock_timestamp()as future from internal.worker_dispatch_control where singleton`);if(delayed.state!=='BACKOFF'||delayed.failureCount!==1||delayed.lastErrorCode!=='WORKER_REQUIRES_REVIEW'||Number(delayed.waitSeconds)<29||Number(delayed.waitSeconds)>31||delayed.future!==true)throw fail();const before=await op(workerFaultControlSql);if(!owns(before)||before.wake_id!==null||before.lease_expires_at!==null)throw fail();const notDue=await op('select internal.request_worker_wake()as requested');if(notDue.requested!==false||canonicalReleaseExecutionJson(await op(workerFaultControlSql))!==canonicalReleaseExecutionJson(before))throw fail();await ports.record('NATIVE_BACKOFF_OBSERVED',{wakeId:generation,eventId:backoff.e.id,seconds:delayed.waitSeconds});
  const preserved=async()=>{const e=await op(`/* CUEVO_FAULT_PRE_DUE_EVENT */ select source.*,clock_timestamp()<$5::timestamptz as "beforeDue" from(${eventSql})source`,[input.schoolId,input.schoolId,backoff.key,input.actorId,before.next_attempt_at]);if(envelope(e)!==backoff.basis||e.audit!==true||e.command_count!==1)throw fail();if(e.beforeDue===true&&(e.state!=='PENDING'||e.attempt_count!==0||e.processed!==false||e.lease_token!==null))throw fail();return e.beforeDue===false;};await preserved();
  await wait(preserved,40000);await op('select internal.request_worker_wake()as requested');await wait(async()=>{const e=await read(backoff.key),c=await op(workerFaultControlSql);if(!owns(c)||envelope(e)!==backoff.basis||e.audit!==true||e.command_count!==1)throw fail();return e.state==='COMPLETED'&&e.processed===true&&e.attempt_count===1&&stamp(e.completed_at)>=stamp(before.next_attempt_at)&&idle(c)&&stamp(c.last_requested_at)>=stamp(before.next_attempt_at)&&stamp(c.last_started_at)>=stamp(c.last_requested_at)&&stamp(c.last_finished_at)>=stamp(c.last_started_at)&&Number(c.last_processed_count)>0;},120000);r.dispatchBackoffVerified=true;
  await ports.admit();await checkJob();const final=await op(`/* CUEVO_FAULT_FINAL */ select count(*)filter(where state='PENDING')::integer as pending,count(*)filter(where state='PROCESSING')::integer as processing,internal.worker_transport_private()as "transportPrivate",not exists(select 1 from internal.posthog_school_activation where enabled)as "analyticsDisabled" from internal.outbox_events where internal.outbox_event_owner(type)='WORKER'`);if(final.pending!==0||final.processing!==0||final.transportPrivate!==true||final.analyticsDisabled!==true)throw fail();r.status='FAULT_RECOVERY_VERIFIED';await ports.record('FAULT_RECOVERY_VERIFIED',{...r});
 }catch{r.status='REQUIRES_REVIEW';}
 finally{if(workerTransaction)try{await ports.workerQuery('ROLLBACK');}catch{r.cleanupStatus='REQUIRES_REVIEW';}if(operatorTransaction)try{await ports.operatorQuery('ROLLBACK');}catch{r.cleanupStatus='REQUIRES_REVIEW';}if(r.cleanupStatus==='REQUIRES_REVIEW')r.status='REQUIRES_REVIEW';}
 return r;
}
