import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {execFileSync,spawnSync} from 'node:child_process';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import type {Readable} from 'node:stream';
import {canonicalReleaseExecutionJson} from './release-review';
import {createCanonicalSourceJobFixture} from './canonical-source-job-fixtures';

const hash=(value:Uint8Array|string)=>createHash('sha256').update(value).digest('hex');
const ids=['source-native','source-contracts','source-delivery'];
const {yazl}=createRequire(import.meta.url)('playwright-core/lib/utilsBundle')as{yazl:{ZipFile:new()=>{outputStream:Readable;addBuffer(bytes:Buffer,name:string):void;end():void}}};
async function zip(value:unknown){const archive=new yazl.ZipFile(),parts:Buffer[]=[],done=new Promise<Buffer>((yes,no)=>{archive.outputStream.on('data',part=>parts.push(part));archive.outputStream.on('error',no);archive.outputStream.on('end',()=>yes(Buffer.concat(parts)));});archive.addBuffer(Buffer.from(canonicalReleaseExecutionJson(value)),'result.json');archive.end();return done;}

test('canonical source owner admits exact original compressed producer and aggregate artifacts and refuses changed authority',async()=>{
 const root=await mkdtemp(join(tmpdir(),'cuevo-canonical-source-'));
 try{
  const files=ids.map((_,index)=>`scripts/verification/source-${index}.test.ts`),steps=files.map((path,index)=>({name:'source-'+index,args:['--import','tsx','--test',path]}));
  await mkdir(join(root,'scripts/verification'),{recursive:true});await mkdir(join(root,'.local'));await writeFile(join(root,'.gitignore'),'.local/\n');await writeFile(join(root,'.gitattributes'),'* -text\n');await writeFile(join(root,'package-lock.json'),'{}\n');
  for(const file of files)await writeFile(join(root,file),'one exact committed source\n');
  const manifest={version:1,purpose:'CUEVO_FIXED_CI_PARTITIONS',source:ids.map((id,index)=>({id,files:[files[index]]})),integration:[],separateSource:[],separateIntegration:[],nonTestChecks:[],measurements:{source:[],integration:[],provenance:{sourceSha:'a'.repeat(40),runId:'31',runAttempt:2,basis:'ORIGINAL_CASE_FILE_DURATION'}}};await writeFile(join(root,'scripts/verification/ci-partitions.json'),JSON.stringify(manifest)+'\n');
  const git=(args:string[])=>execFileSync('git',['-C',root,...args],{encoding:'utf8',windowsHide:true}).trim();git(['init','--quiet']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','Exact source fixture']);const sourceSha=git(['rev-parse','HEAD']),treeSha=git(['rev-parse','HEAD^{tree}']);
  const coverage={...manifest,manifestSha256:hash(await readFile(join(root,'scripts/verification/ci-partitions.json'))),effectAuthority:false,timeTargetAchieved:false},all=git(['ls-files','-z']).split('\0').filter(Boolean).sort(),descriptors=await Promise.all(all.map(async path=>({path,sha256:hash(await readFile(join(root,path)))}))),sourceLockSha256=hash(await readFile(join(root,'package-lock.json'))),nodeVersion='v24.16.0',nodeBinarySha256='c'.repeat(64),identity={repository:'owner/repo',sourceSha,treeSha,sourceDigest:hash(JSON.stringify(descriptors)),sourceLockSha256,partitionManifestSha256:coverage.manifestSha256,nodeVersion,nodeBinarySha256,toolchainSha256:hash(canonicalReleaseExecutionJson({nodeVersion,nodeBinarySha256,sourceLockSha256,platform:'linux',arch:'x64'})),environmentPolicySha256:hash(canonicalReleaseExecutionJson({CI:'true',NEXT_TELEMETRY_DISABLED:'1',SCARF_ANALYTICS:'false',CUEVO_REQUIRE_LIVE_INTELLIGENCE:'0',fileConcurrency:'NODE_DEFAULT_PROCESS_ISOLATION',partitionManifestSha256:coverage.manifestSha256})),runId:'31',runAttempt:2,job:'source-contracts'};
  const receipts=ids.map((partition,index)=>{const body={version:1,purpose:'CUEVO_STATELESS_SOURCE_PARTITION',partition,status:'PASSED',identity:{...identity,job:'source-fixtures-'+partition.slice(7)},files:[{path:files[index],sha256:descriptors.find(row=>row.path===files[index])!.sha256,group:steps[index].name,durationMs:1,cases:[{definitionSha256:'d'.repeat(64),outcome:'PASSED'}]}],startedAtMs:Date.parse('2026-10-08T00:00:10Z'),completedAtMs:Date.parse('2026-10-08T00:00:50Z'),exitCode:0,signal:null,frozenBefore:true,frozenAfter:true,cleanupConfirmed:true,reasons:[]};return{...body,payloadSha256:hash(canonicalReleaseExecutionJson(body))};});
  const summary={version:1,purpose:'CUEVO_PARTITIONED_SOURCE_CONTRACTS',status:'PASSED',identity,partitions:receipts.map(row=>({partition:row.partition,job:row.identity.job,payloadSha256:row.payloadSha256,receiptSha256:hash(canonicalReleaseExecutionJson(row))})).sort((a,b)=>a.partition.localeCompare(b.partition)),files:receipts.flatMap(row=>row.files).sort((a,b)=>a.path.localeCompare(b.path)),checks:[]};
  const bodies=[summary,...receipts],archives=await Promise.all(bodies.map(zip)),jobs=['source-contracts',...ids.map(id=>'source-fixtures-'+id.slice(7))].map((name,index)=>({id:index+1,name,run_id:31,run_attempt:2,head_sha:sourceSha,head_branch:'main',status:'completed',conclusion:'success',started_at:index?'2026-10-08T00:00:00Z':'2026-10-08T00:01:00Z',completed_at:index?'2026-10-08T00:01:00Z':'2026-10-08T00:02:00Z'})),artifacts=archives.map((bytes,index)=>({id:71+index,name:index?`cuevo-source-partition-${ids[index-1]}-31-2`:'cuevo-source-contracts-31-2',size_in_bytes:bytes.length,expired:false,digest:'sha256:'+hash(bytes),created_at:index?'2026-10-08T00:00:55Z':'2026-10-08T00:01:50Z',expires_at:'2026-10-21T00:00:00Z',workflow_run:{id:31,head_sha:sourceSha,head_branch:'main'}}));
  const hook=join(root,'.local/hook.mjs');await writeFile(hook,`import{registerHooks}from'node:module';registerHooks({load(url,context,next){if(url.endsWith('/steps.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('export const statelessVerificationSteps='+JSON.stringify(steps)+';')}};if(url.endsWith('/ci-partition-coverage.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('const coverage='+JSON.stringify(coverage)+';export const readCiPartitionCoverage=()=>coverage;export const ciPartitionFiles=(_value,_scope,id)=>coverage.source.find(row=>row.id===id).files;')}};return next(url,context);}});`);
  const subject=pathToFileURL(resolve('scripts/verification/canonical-source-jobs.ts')).href,script=join(root,'.local/runner.mjs');await writeFile(script,`import{readCanonicalSourceArtifacts}from ${JSON.stringify(subject)};import{readFileSync}from'node:fs';const input=JSON.parse(readFileSync(${JSON.stringify(join(root,'.local/input.json'))},'utf8'));let calls=0;try{const proof=await readCanonicalSourceArtifacts(input.run,input.treeSha,input.jobs,async()=>{calls++;return{total_count:input.artifacts.length,artifacts:input.mode==='metadata-drift'&&calls>1?input.artifacts.map((row,index)=>index?row:{...row,digest:'sha256:'+'0'.repeat(64)}):input.artifacts};},async(id)=>Buffer.from(input.archives[id-71],'base64'));if(input.mode==='valid')console.log(JSON.stringify(proof));else process.exitCode=2;}catch(error){if(input.mode==='valid'){console.error(String(error));process.exitCode=1;}else if(String(error).includes('private-canary'))process.exitCode=3;}`);
  const run={id:31,run_attempt:2,head_sha:sourceSha,head_branch:'main',repository:{full_name:'owner/repo'}},invoke=async(mode:string)=>{const input={run:structuredClone(run),treeSha,jobs:structuredClone(jobs),artifacts:structuredClone(artifacts),archives:archives.map(bytes=>bytes.toString('base64')),mode};if(mode==='missing')input.artifacts.pop();if(mode==='duplicate')input.artifacts.push(input.artifacts[1]);if(mode==='expiry')input.artifacts[0].expires_at='2026-10-01T00:00:00Z';if(mode==='source')input.artifacts[1].workflow_run.head_sha='0'.repeat(40);if(mode==='attempt')input.run.run_attempt=3;if(mode==='clock')input.artifacts[1].created_at='2026-10-08T00:02:00Z';if(mode==='archive')input.archives[1]=Buffer.from('{}').toString('base64');if(['cleanup','cancelled','filehash','toolchain','extra'].includes(mode)){const changed=structuredClone(receipts),body=changed[0]as typeof receipts[number]&{private?:string};if(mode==='cleanup')body.cleanupConfirmed=false;if(mode==='cancelled')body.status='CANCELLED';if(mode==='filehash')body.files[0].sha256='0'.repeat(64);if(mode==='toolchain')body.identity.toolchainSha256='0'.repeat(64);if(mode==='extra')body.private='private-canary';const{payloadSha256:_hash,...raw}=body;void _hash;body.payloadSha256=hash(canonicalReleaseExecutionJson(raw));const bytes=await zip(body);input.archives[1]=bytes.toString('base64');input.artifacts[1].size_in_bytes=bytes.length;input.artifacts[1].digest='sha256:'+hash(bytes);}await writeFile(join(root,'.local/input.json'),JSON.stringify(input));return spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(hook).href,script],{cwd:root,encoding:'utf8',env:process.env});};
  const valid=await invoke('valid');assert.equal(valid.status,0,valid.stderr);assert.equal(JSON.parse(valid.stdout).effectAuthority,false);for(const mode of ['missing','duplicate','expiry','source','attempt','clock','archive','metadata-drift','cleanup','cancelled','filehash','toolchain','extra']){const result=await invoke(mode);assert.equal(result.status,0,mode+': '+result.stderr);}
 }finally{await rm(root,{recursive:true,force:true});}
});

test('historical partition evidence reads its exact older source while the current checkout and manifest advance',async()=>{
 const f=await createCanonicalSourceJobFixture();
 try{
  const git=(args:string[])=>execFileSync('git',['-C',f.root,...args],{encoding:'utf8',windowsHide:true}).trim();await writeFile(join(f.root,'scripts/verification/new-current.test.ts'),'new current test fixture\n');const changed=JSON.parse(await readFile(join(f.root,'scripts/verification/ci-partitions.json'),'utf8'));changed.source[0].files.push('scripts/verification/new-current.test.ts');await writeFile(join(f.root,'scripts/verification/ci-partitions.json'),JSON.stringify(changed)+'\n');git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','Current source advances without changing original proof']);assert.notEqual(git(['rev-parse','HEAD']),f.sourceSha);
  const input={run:{id:31,run_attempt:2,head_sha:f.sourceSha,head_branch:'main',repository:{full_name:'owner/repo'}},tree:f.treeSha,jobs:f.jobs,artifacts:f.artifacts,archives:f.archives.map(bytes=>bytes.toString('base64'))},script=join(f.root,'.local/historical-runner.mjs');await writeFile(join(f.root,'.local/historical.json'),JSON.stringify(input));await writeFile(script,`import{readCanonicalSourceArtifacts}from ${JSON.stringify(pathToFileURL(resolve('scripts/verification/canonical-source-jobs.ts')).href)};import{readFileSync}from'node:fs';const input=JSON.parse(readFileSync(${JSON.stringify(join(f.root,'.local/historical.json'))},'utf8'));try{console.log(JSON.stringify(await readCanonicalSourceArtifacts(input.run,input.tree,input.jobs,async()=>({total_count:input.artifacts.length,artifacts:input.artifacts}),async id=>Buffer.from(input.archives[id-71],'base64'),process.env.CUEVO_CANONICAL_PURPOSE)));}catch(error){console.error(String(error));process.exitCode=1;}`);
  const invoke=(purpose:string)=>spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(f.hook).href,script],{cwd:f.root,encoding:'utf8',env:{...process.env,CUEVO_CANONICAL_PURPOSE:purpose}});const historical=invoke('ORIGINAL_RUNTIME_METADATA');assert.equal(historical.status,0,historical.stderr);assert.equal(JSON.parse(historical.stdout).effectAuthority,false);assert.notEqual(invoke('CURRENT_SOURCE').status,0);
  for(const mode of ['tree','attempt','policy']){const value=structuredClone(input);if(mode==='tree')value.tree='0'.repeat(40);if(mode==='attempt')value.run.run_attempt=3;if(mode==='policy'){await writeFile(join(f.root,'scripts/verification/stateless-checks.ts'),'changed current policy\n');git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','Changed policy is unsupported for old evidence']);}await writeFile(join(f.root,'.local/historical.json'),JSON.stringify(value));assert.notEqual(invoke('ORIGINAL_RUNTIME_METADATA').status,0,mode);}
 }finally{await f.destroy();}
});

test('source metadata changing during the final artifact listing refuses before evidence is returned',async()=>{
 for(const mode of ['head','replace','graft']){const f=await createCanonicalSourceJobFixture();try{
  const script=join(f.root,'.local/final-metadata.mjs'),input=join(f.root,'.local/final-metadata.json');await writeFile(input,JSON.stringify({run:{id:31,run_attempt:2,head_sha:f.sourceSha,head_branch:'main',repository:{full_name:'owner/repo'}},tree:f.treeSha,jobs:f.jobs,artifacts:f.artifacts,archives:f.archives.map(bytes=>bytes.toString('base64'))}));await writeFile(script,`import{readCanonicalSourceArtifacts}from ${JSON.stringify(pathToFileURL(resolve('scripts/verification/canonical-source-jobs.ts')).href)};import{readFileSync,writeFileSync}from'node:fs';import{execFileSync}from'node:child_process';const input=JSON.parse(readFileSync(${JSON.stringify(input)},'utf8'));let reads=0,mutated=false;try{await readCanonicalSourceArtifacts(input.run,input.tree,input.jobs,async()=>{if(++reads===2){mutated=true;const git=args=>execFileSync('git',args,{encoding:'utf8',windowsHide:true});if(${JSON.stringify(mode)}==='head'){writeFileSync('new-source.txt','changed');git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','Changed after final read']);}if(${JSON.stringify(mode)}==='replace')git(['replace',input.run.head_sha,input.run.head_sha]);if(${JSON.stringify(mode)}==='graft')writeFileSync(git(['rev-parse','--git-path','info/grafts']).trim(),'untrusted graft');}return{total_count:input.artifacts.length,artifacts:input.artifacts};},async id=>Buffer.from(input.archives[id-71],'base64'));process.exitCode=2;}catch{if(!mutated)process.exitCode=3;else console.log('Exact final metadata mutation rejected');}`);
  const result=spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(f.hook).href,script],{cwd:f.root,encoding:'utf8',env:process.env});assert.equal(result.status,0,mode+': '+result.stderr);assert.match(result.stdout,/Exact final metadata mutation rejected/);
 }finally{await f.destroy();}}
});
