import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync,lstatSync,realpathSync} from 'node:fs';
import {resolve} from 'node:path';
import {z} from 'zod';
import {canonicalReleaseExecutionJson} from './release-review';
import {readCiPartitionCoverage} from './ci-partition-coverage';
import {validateStatelessSourceSummary,sourceSummarySchema,partitionReceiptSchema,validateParsedPartitionOutcome} from './stateless-checks';
import {statelessVerificationSteps} from './steps';
import {ciSourceJobs} from './verification-workflows';
import {createRequire} from 'node:module';
import {readSingleJsonArchive} from './single-json-archive';
import type {GithubArtifactReader} from './staging-security';
import {discoverSourceTestCohortPlan,readSourceTestCohortPlan,validateSourceTestCohortEvidence,SOURCE_TEST_COHORT_FILE,type SourceTestCohortPlan} from './source-test-cohorts';

const fail=()=>Error('Original canonical source partitions require review; contents withheld.'),hash=(bytes:Uint8Array|string)=>createHash('sha256').update(bytes).digest('hex'),same=(a:unknown,b:unknown)=>canonicalReleaseExecutionJson(a)===canonicalReleaseExecutionJson(b);
const positive=z.number().int().positive().max(Number.MAX_SAFE_INTEGER),sha=z.string().regex(/^[a-f0-9]{40}$/),date=z.iso.datetime({offset:true});
const runSchema=z.object({id:positive,run_attempt:positive,head_sha:sha,head_branch:z.literal('main'),repository:z.object({full_name:z.string().regex(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/)})});
const jobSchema=z.object({id:positive,name:z.string(),run_id:positive,run_attempt:positive,head_sha:sha,head_branch:z.literal('main'),status:z.literal('completed'),conclusion:z.literal('success'),started_at:date,completed_at:date});
const artifactSchema=z.object({id:positive,name:z.string().max(200),size_in_bytes:positive.max(2*1024*1024),expired:z.literal(false),digest:z.string().regex(/^sha256:[a-f0-9]{64}$/),created_at:date,expires_at:date,workflow_run:z.object({id:positive,head_sha:sha,head_branch:z.literal('main')})});
const partitions=['source-native','source-contracts','source-delivery']as const;

/** Captured checkout metadata only. The closure is not serialized evidence or
 * effect authority and never reacquires the immutable source blob inventory. */
export function captureCanonicalSourceContext(rootValue:string,sourceShaValue:string,treeShaValue:string|undefined,purpose:'CURRENT_SOURCE'|'ORIGINAL_RUNTIME_METADATA'='CURRENT_SOURCE'){
 const root=resolve(rootValue),sourceSha=sha.parse(sourceShaValue),env=Object.fromEntries(['PATH','Path','SystemRoot','SYSTEMROOT','WINDIR','TEMP','TMP','LANG','LC_ALL'].filter(key=>process.env[key]!==undefined).map(key=>[key,process.env[key]!]).concat([['GIT_NO_REPLACE_OBJECTS','1'],['GIT_CONFIG_NOSYSTEM','1'],['GIT_CONFIG_GLOBAL',process.platform==='win32'?'NUL':'/dev/null']]));
 if(!['CURRENT_SOURCE','ORIGINAL_RUNTIME_METADATA'].includes(purpose))throw fail();
 const git=(args:string[],input?:string)=>execFileSync('git',['-C',root,...args],{env,input,shell:false,windowsHide:true,stdio:['pipe','pipe','ignore'],timeout:15000,maxBuffer:32*1024*1024});
 if(realpathSync(root)!==root||lstatSync(root).isSymbolicLink()||realpathSync(git(['rev-parse','--show-toplevel']).toString().trim())!==root||git(['rev-parse','--is-shallow-repository']).toString().trim()!=='false'||git(['for-each-ref','--format=%(refname)','refs/replace']).length)throw fail();
 const graft=git(['rev-parse','--git-path','info/grafts']).toString().trim();try{if(readFileSync(resolve(root,graft)).length)throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}
 const currentSha=git(['rev-parse','HEAD']).toString().trim(),currentTree=git(['rev-parse','HEAD^{tree}']).toString().trim(),treeSha=sha.parse(git(['rev-parse',sourceSha+'^{tree}']).toString().trim());if(purpose==='CURRENT_SOURCE'&&currentSha!==sourceSha||treeShaValue!==undefined&&treeSha!==sha.parse(treeShaValue)||git(['status','--porcelain','--untracked-files=all']).length)throw fail();
 const finalMetadata=()=>{if(realpathSync(root)!==root||lstatSync(root).isSymbolicLink()||git(['for-each-ref','--format=%(refname)','refs/replace']).length||git(['rev-parse','HEAD']).toString().trim()!==currentSha||git(['rev-parse','HEAD^{tree}']).toString().trim()!==currentTree||git(['rev-parse',sourceSha+'^{tree}']).toString().trim()!==treeSha||git(['status','--porcelain','--untracked-files=all']).length)throw fail();try{if(readFileSync(resolve(root,graft)).length)throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}};
 return{root,treeSha,git,finalMetadata};
}

/** Exact committed descriptor, not an admission cache or caller supplied proof. */
function sourceDescriptor(sourceSha:string,treeSha:string,purpose:'CURRENT_SOURCE'|'ORIGINAL_RUNTIME_METADATA'){
 const{root,git,finalMetadata}=captureCanonicalSourceContext(resolve('.'),sourceSha,treeSha,purpose),tree=git(['ls-tree','-r','-z',sourceSha]),entries=new TextDecoder('utf8',{fatal:true}).decode(tree).split('\0').filter(Boolean).map(text=>{const row=/^100(?:644|755) blob ([a-f0-9]{40})\t([^\0]+)$/.exec(text);if(!row||row[2].split('/').some(part=>!part||part==='.'||part==='..'))throw fail();return{blob:row[1],path:row[2]};});if(!entries.length||entries.length>20000||new Set(entries.map(row=>row.path)).size!==entries.length)throw fail();
 const files:{path:string;sha256:string}[]=[],bytesByPath=new Map<string,Uint8Array>();let total=0;
 const sizes=git(['cat-file','--batch-check'],entries.map(row=>row.blob).join('\n')+'\n').toString('ascii').trim().split('\n');if(sizes.length!==entries.length)throw fail();const groups:typeof entries[]=[];let group:typeof entries=[],groupBytes=0;for(const[index,row]of entries.entries()){const header=/^([a-f0-9]{40}) blob ([0-9]+)$/.exec(sizes[index]);if(!header||header[1]!==row.blob)throw fail();const size=Number(header[2]);if(!Number.isSafeInteger(size)||size>16*1024*1024)throw fail();if(group.length&&(groupBytes+size>24*1024*1024||group.length>=512)){groups.push(group);group=[];groupBytes=0;}group.push(row);groupBytes+=size;}if(group.length)groups.push(group);for(const selected of groups){const batch=git(['cat-file','--batch'],selected.map(row=>row.blob).join('\n')+'\n');let offset=0;for(const row of selected){const end=batch.indexOf(10,offset),header=end<0?null:/^([a-f0-9]{40}) blob ([0-9]+)$/.exec(batch.subarray(offset,end).toString('ascii'));if(!header||header[1]!==row.blob)throw fail();const size=Number(header[2]);if(!Number.isSafeInteger(size)||size>16*1024*1024)throw fail();total+=size;if(total>512*1024*1024)throw fail();offset=end+1;const bytes=batch.subarray(offset,offset+size);if(bytes.length!==size||batch[offset+size]!==10)throw fail();offset+=size+1;files.push({path:row.path,sha256:hash(bytes)});if(row.path==='package-lock.json'||row.path==='scripts/verification/ci-partitions.json'||row.path===SOURCE_TEST_COHORT_FILE)bytesByPath.set(row.path,new Uint8Array(bytes));}if(offset!==batch.length)throw fail();}
 const lock=bytesByPath.get('package-lock.json'),manifest=bytesByPath.get('scripts/verification/ci-partitions.json');if(!lock||!manifest)throw fail();const coverage=purpose==='CURRENT_SOURCE'?readCiPartitionCoverage(root):historicalCoverage(root,sourceSha,manifest,files,git),cohortPlan=coverage.sourceCohorts?(purpose==='CURRENT_SOURCE'?readSourceTestCohortPlan(root):discoverSourceTestCohortPlan(new TextDecoder('utf8',{fatal:true}).decode(bytesByPath.get(SOURCE_TEST_COHORT_FILE)!))):undefined;if(hash(manifest)!==coverage.manifestSha256||cohortPlan&&cohortPlan.policySha256!==coverage.sourceCohorts!.policySha256)throw fail();return{root,coverage,cohortPlan,finalMetadata,files:files.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0),sourceDigest:hash(JSON.stringify(files.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0))),sourceLockSha256:hash(lock)};
}

function historicalCoverage(root:string,sourceSha:string,manifest:Uint8Array,files:{path:string;sha256:string}[],git:(args:string[],input?:string)=>Buffer){
 const path=z.string().regex(/^scripts\/[a-z0-9_./-]+[.]test[.]ts$/),parsed=z.object({version:z.literal(1),purpose:z.literal('CUEVO_FIXED_CI_PARTITIONS'),source:z.array(z.object({id:z.enum(partitions),files:z.array(path).min(1).max(300)}).strict()).length(3),sourceCohorts:z.object({version:z.literal(1),file:z.literal(SOURCE_TEST_COHORT_FILE),policySha256:z.string().regex(/^[a-f0-9]{64}$/)}).strict().optional(),separateSource:z.array(z.object({file:path,reason:z.enum(['SEPARATE_PILOT_ACCEPTANCE','SEPARATE_SECRET_SCANNER_OWNER'])}).strict()).max(20),nonTestChecks:z.array(z.object({name:z.string(),commandSha256:z.string().regex(/^[a-f0-9]{64}$/)}).strict()).max(30)}).passthrough().parse(JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(manifest)));
 const separate=['pilot-evidence','pilot-private-cleanup','pilot-window-rules','pilot-window','pilot-workflow-contracts','secret-scan-policy','secret-scan'].map(name=>'scripts/verification/'+name+'.test.ts'),selected=parsed.source.flatMap(row=>row.files).sort(),discovered=files.filter(row=>/^scripts\/.+[.]test[.]ts$/.test(row.path)).map(row=>row.path).sort();if(new Set(parsed.source.map(row=>row.id)).size!==3||new Set(selected).size!==selected.length||!same(parsed.separateSource.map(row=>row.file).sort(),separate.sort())||!same([...selected,...separate].sort(),discovered))throw fail();
 for(const policy of ['scripts/verification/stateless-checks.ts','scripts/verification/stateless-source-aggregate.ts','scripts/verification/ci-test-timings-reporter.ts','scripts/verification/ci-test-timings.ts','scripts/verification/ci-partition-coverage.ts','scripts/verification/release-review.ts',...(parsed.sourceCohorts?['scripts/verification/source-test-cohorts.ts']:[])])if(files.find(row=>row.path===policy)?.sha256!==hash(readFileSync(resolve(root,policy))))throw fail();
 const yaml=createRequire(import.meta.url)('js-yaml')as{load(text:string):unknown},workflow=z.object({jobs:z.record(z.string(),z.unknown())}).parse(yaml.load(git(['show',sourceSha+':.github/workflows/ci.yml']).toString('utf8')));for(const[name,job]of Object.entries(ciSourceJobs).filter(([name])=>name!=='fast-checks'))if(!same(workflow.jobs[name],job))throw fail();
 return{...parsed,manifestSha256:hash(manifest),effectAuthority:false as const,timeTargetAchieved:false as const}as ReturnType<typeof readCiPartitionCoverage>;
}
function historicalSummary(value:unknown,expected:{repository:string;sourceSha:string;treeSha:string;runId:string;runAttempt:number},coverage:ReturnType<typeof readCiPartitionCoverage>,receipts:unknown[],cohortPlan?:SourceTestCohortPlan){
 const summary=sourceSummarySchema.parse(value),parsed=receipts.map(row=>partitionReceiptSchema.parse(row));for(const key of Object.keys(expected)as(keyof typeof expected)[])if(summary.identity[key]!==expected[key])throw fail();if(summary.identity.job!=='source-contracts'||summary.identity.partitionManifestSha256!==coverage.manifestSha256||parsed.length!==3||new Set(parsed.map(row=>row.partition)).size!==3)throw fail();
 for(const row of parsed){validateParsedPartitionOutcome(row);if(row.status!=='PASSED'||!same({...row.identity,job:'source-contracts'},summary.identity)||!same(row.files.map(file=>file.path),coverage.source.find(part=>part.id===row.partition)!.files)||row.files.some(file=>!statelessVerificationSteps.some(step=>step.name===file.group)))throw fail();}
 for(const row of parsed)for(const file of row.files){if(coverage.sourceCohorts?.file===file.path){if(!cohortPlan||!file.cohortEvidence||!same(file,validateSourceTestCohortEvidence(cohortPlan,file.cohortEvidence,{sourceSha:row.identity.sourceSha,treeSha:row.identity.treeSha,sourceLockSha256:row.identity.sourceLockSha256,nodeVersion:row.identity.nodeVersion,runId:row.identity.runId,runAttempt:row.identity.runAttempt,scope:'source-contracts',partitionSha256:row.identity.partitionManifestSha256}))||row.completedAtMs===null||file.cohortEvidence.receipts.some(item=>item.reportStartedAtMs<row.startedAtMs||item.reportCompletedAtMs>row.completedAtMs!))throw fail();}else if(file.cohortEvidence)throw fail();}
 if(!same(summary.checks.map(row=>({name:row.name,commandSha256:row.commandSha256})),coverage.nonTestChecks))throw fail();const rebuilt={version:1,purpose:'CUEVO_PARTITIONED_SOURCE_CONTRACTS',status:'PASSED',identity:summary.identity,partitions:parsed.map(row=>({partition:row.partition,job:row.identity.job,payloadSha256:row.payloadSha256,receiptSha256:hash(canonicalReleaseExecutionJson(row))})).sort((a,b)=>a.partition.localeCompare(b.partition)),files:parsed.flatMap(row=>row.files).sort((a,b)=>a.path.localeCompare(b.path)),checks:summary.checks};if(!same(summary,rebuilt))throw fail();return summary;
}

/** Four original private artifact reads are evidence only. Native source, lease
 * and human effect approval remain with their current admission owners. */
export async function readCanonicalSourceArtifactsAndInputs(value:unknown,treeShaValue:string,jobsValue:unknown,github:(path:string)=>Promise<unknown>,artifact?:GithubArtifactReader,purpose:'CURRENT_SOURCE'|'ORIGINAL_RUNTIME_METADATA'='CURRENT_SOURCE'){
 try{
  if(!artifact||!['CURRENT_SOURCE','ORIGINAL_RUNTIME_METADATA'].includes(purpose))throw fail();const run=runSchema.parse(value),treeSha=sha.parse(treeShaValue),descriptor=sourceDescriptor(run.head_sha,treeSha,purpose),wanted=['source-contracts',...partitions.map(id=>'source-fixtures-'+id.slice(7))],allJobs=z.array(z.unknown()).max(1000).parse(jobsValue),jobs=wanted.map(name=>{const matching=allJobs.filter(row=>z.object({name:z.literal(name)}).passthrough().safeParse(row).success);if(matching.length!==1)throw fail();return jobSchema.parse(matching[0]);});
  for(const job of jobs)if(job.run_id!==run.id||job.run_attempt!==run.run_attempt||job.head_sha!==run.head_sha||Date.parse(job.completed_at)<Date.parse(job.started_at)||Date.parse(job.completed_at)>Date.now())throw fail();
  const artifactNames=[`cuevo-source-contracts-${run.id}-${run.run_attempt}`,...partitions.map(id=>`cuevo-source-partition-${id}-${run.id}-${run.run_attempt}`)],read=async()=>{const page=z.object({total_count:z.number().int().nonnegative().max(100),artifacts:z.array(z.object({id:positive,name:z.string()}).passthrough()).max(100)}).parse(await github(`actions/runs/${run.id}/artifacts?per_page=100`));if(page.total_count!==page.artifacts.length||new Set(page.artifacts.map(row=>row.id)).size!==page.artifacts.length)throw fail();return artifactNames.map((name,index)=>{const matching=page.artifacts.filter(row=>row.name===name);if(matching.length!==1)throw fail();const item=artifactSchema.parse(matching[0]),job=jobs[index];if(item.workflow_run.id!==run.id||item.workflow_run.head_sha!==run.head_sha||Date.parse(item.expires_at)<=Date.now()||Date.parse(item.created_at)<Date.parse(job.started_at)||Date.parse(item.created_at)>Date.parse(job.completed_at))throw fail();return item;});};
  const original=await read(),decoded:Awaited<ReturnType<typeof readSingleJsonArchive>>[]=[];for(const item of original){const bytes=await artifact(item.id);if(bytes.byteLength!==item.size_in_bytes)throw fail();decoded.push(await readSingleJsonArchive(bytes,{archiveSha256:item.digest.slice(7),fileName:'result.json',maximumJsonBytes:1024*1024}));}
  const expected={repository:run.repository.full_name,sourceSha:run.head_sha,treeSha,runId:String(run.id),runAttempt:run.run_attempt},summary=purpose==='CURRENT_SOURCE'?validateStatelessSourceSummary(decoded[0].value,expected,descriptor.coverage,decoded.slice(1).map(row=>row.value)):historicalSummary(decoded[0].value,expected,descriptor.coverage,decoded.slice(1).map(row=>row.value),descriptor.cohortPlan),identity=summary.identity;
  if(identity.sourceDigest!==descriptor.sourceDigest||identity.sourceLockSha256!==descriptor.sourceLockSha256||identity.toolchainSha256!==hash(canonicalReleaseExecutionJson({nodeVersion:identity.nodeVersion,nodeBinarySha256:identity.nodeBinarySha256,sourceLockSha256:identity.sourceLockSha256,platform:'linux',arch:'x64'}))||identity.environmentPolicySha256!==hash(canonicalReleaseExecutionJson({CI:'true',NEXT_TELEMETRY_DISABLED:'1',SCARF_ANALYTICS:'false',CUEVO_REQUIRE_LIVE_INTELLIGENCE:'0',fileConcurrency:'NODE_DEFAULT_PROCESS_ISOLATION',partitionManifestSha256:descriptor.coverage.manifestSha256})))throw fail();
  for(const file of summary.files)if(descriptor.files.find(row=>row.path===file.path)?.sha256!==file.sha256)throw fail();
  for(const[index,row]of decoded.slice(1).entries()){const receipt=z.object({partition:z.literal(partitions[index]),startedAtMs:z.number().int(),completedAtMs:z.number().int()}).passthrough().parse(row.value),job=jobs[index+1];if(receipt.startedAtMs<Date.parse(job.started_at)||Math.floor(receipt.completedAtMs/1000)>Math.floor(Date.parse(job.completed_at)/1000)||Math.floor(receipt.completedAtMs/1000)>Math.floor(Date.parse(jobs[0].started_at)/1000))throw fail();}
  if(!same(original,await read())||purpose==='CURRENT_SOURCE'&&!same(descriptor.coverage,readCiPartitionCoverage(descriptor.root)))throw fail();descriptor.finalMetadata();
  const proof={version:1 as const,purpose:'CUEVO_ORIGINAL_CANONICAL_SOURCE_PARTITIONS' as const,effectAuthority:false as const,sourceDigest:identity.sourceDigest,partitionManifestSha256:identity.partitionManifestSha256,artifacts:original.map((item,index)=>({artifactId:item.id,archiveSha256:item.digest.slice(7),jsonSha256:decoded[index].jsonSha256,expiresAt:item.expires_at})),summarySha256:hash(canonicalReleaseExecutionJson(summary))};
  const expiresAtMs=Math.min(...original.map(row=>Date.parse(row.expires_at))),assertOriginalValidity=()=>{if(Date.now()>=expiresAtMs)throw fail();},refreshOriginalMetadata=async()=>{if(!same(original,await read()))throw fail();descriptor.finalMetadata();assertOriginalValidity();};
  assertOriginalValidity();return{proof,descriptor:{files:descriptor.files,coverage:descriptor.coverage,sourceDigest:descriptor.sourceDigest,sourceLockSha256:descriptor.sourceLockSha256},sourceIdentity:identity,refreshOriginalMetadata,assertOriginalValidity};
 }catch{throw fail();}
}

/** Public source proof keeps its original serialized shape. The enclosing
 * runtime reader consumes already acquired immutable inputs in the same call;
 * neither result grants effect authority or replaces its final live checks. */
export async function readCanonicalSourceArtifacts(value:unknown,treeShaValue:string,jobsValue:unknown,github:(path:string)=>Promise<unknown>,artifact?:GithubArtifactReader,purpose:'CURRENT_SOURCE'|'ORIGINAL_RUNTIME_METADATA'='CURRENT_SOURCE'){
 return(await readCanonicalSourceArtifactsAndInputs(value,treeShaValue,jobsValue,github,artifact,purpose)).proof;
}
