import { readFile } from 'node:fs/promises';
import { validateWorkflows } from './cicd-contracts';
import { validatePilotWorkflow } from './pilot-workflow-contracts';
import { validateHostedLearningQaWorkflow } from './hosted-learning-qa-workflow';
import { validateStagingVerificationWorkflow } from './staging-verification';
import { validateFullRegressionWorkflow } from './verification-workflows';
import { validateDailyWatchdogWorkflow } from './daily-watchdog';
const issues = validateWorkflows(await readFile('.github/workflows/ci.yml', 'utf8'), await readFile('.github/workflows/release.yml', 'utf8'));
issues.push(...validatePilotWorkflow(await readFile('.github/workflows/pilot.yml', 'utf8')));
issues.push(...validateHostedLearningQaWorkflow(await readFile('.github/workflows/hosted-learning-qa.yml', 'utf8')));
issues.push(...validateStagingVerificationWorkflow(await readFile('.github/workflows/staging-verification.yml', 'utf8')));
issues.push(...validateFullRegressionWorkflow(await readFile('.github/workflows/full-regression.yml', 'utf8')));
issues.push(...validateDailyWatchdogWorkflow(await readFile('.github/workflows/daily-watchdog.yml', 'utf8')));
if (issues.length) throw Error(issues.join('\n'));
console.log('CI/CD workflow trust and artifact contracts passed.');
