import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {writeFile} from 'node:fs/promises';
import {readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {test} from 'node:test';
import {withCanonicalJobFixture} from './canonical-source-job-fixtures';
import {backendWebTransferProducerPaths} from './backend-web-transfer';

// Fixed test program; only official transport/native evidence and local runner
// portability are controlled. All three authentic issuer/consumer registries,
// actual Git/source admission and ZIP/native evidence parsers stay unchanged.
const program=String.raw`
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{readFile}from'node:fs/promises';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';import{createRequire,registerHooks}from'node:module';
const input=JSON.parse(readFileSync(process.env.CUEVO_QA_JOIN_INPUT,'utf8')),hash=value=>createHash('sha256').update(value).digest('hex'),root=process.cwd(),paths=input.paths;
registerHooks({load(url,context,next){if(url.endsWith('/hosted-migration-provider.ts'))return{format:'module',shortCircuit:true,source:"export * from './hosted-migration-provider.ts?actual-qa-schema';export const readHostedMigrationProvider=(...args)=>globalThis.qaJoinTransport.provider(...args);export const requireCurrentHostedMigrationEndpoint=(...args)=>globalThis.qaJoinTransport.endpoint(...args);"};if(url.endsWith('/hosted-migration-database.ts'))return{format:'module',shortCircuit:true,source:"export * from './hosted-migration-database.ts?actual-qa-native-contracts';export const createHostedMigrationDatabase=(...args)=>globalThis.qaJoinTransport.database(...args);"};const source=input.portable[url];if(source)return{format:'module',shortCircuit:true,source};return next(url,context);}});
const{canonicalReleaseExecutionJson:json,canonicalReleaseReviewJson:review}=await import(paths.review),{readCanonicalRuntimeJobsAndGuard}=await import(paths.canonical),{backendWebTransferFixture}=await import(paths.transferFixture),{prepareBackendReleaseIntent}=await import(paths.contracts),{prepareHostedLearningLoopNativePackage}=await import(paths.qa),{runHostedLearningQa}=await import(paths.runner);
const counts={uiZip:0,transferZip:0,canonicalZip:0,uiMetadata:0,backendMetadata:0,qaRunMetadata:0,webDeployment:0,webAlias:0,nativeReads:0},events=[],now=Date.parse('2026-10-10T09:00:00Z');let clock=now;Date.now=()=>clock;
const canonicalGet=async path=>path==='actions/runs/31'?input.run:path.includes('/jobs?')?{total_count:input.jobs.length,jobs:input.jobs}:path.includes('/artifacts?')?{total_count:input.artifacts.length,artifacts:input.artifacts}:path.startsWith('git/commits/')?{sha:input.run.head_sha,tree:{sha:input.tree}}:assert.fail('Unexpected canonical fixture metadata');
const originalCanonical=await readCanonicalRuntimeJobsAndGuard(input.run,canonicalGet,async id=>Buffer.from(input.archives[String(id)],'base64')),proof=originalCanonical.proof;originalCanonical.assertOriginalValidity();
const fixture=backendWebTransferFixture({now,sourceSha:input.run.head_sha,treeSha:input.tree,baseSha:input.run.head_sha,sourceManifestSha256:hash(execFileSync('git',['ls-tree','-r','-z',input.run.head_sha])),diffSha256:hash(Buffer.alloc(0))});
fixture.transfer.manifest.database.migrations=[{version:'20261001000000',sha256:hash(Buffer.from('select 1;\n'))}];fixture.transfer.producers=input.producerPaths.map(path=>({path,sha256:hash(readFileSync(path))}));fixture.transfer.manifestSha256=hash(json(fixture.transfer.manifest));
const backendBody=JSON.parse(fixture.transfer.preparedApproval.canonicalJson);fixture.transfer.preparedApproval=prepareBackendReleaseIntent({...backendBody,canonicalRuntimeVerification:proof},{...fixture.expected,canonicalRuntimeVerification:proof});fixture.approvals[0].comment=fixture.transfer.preparedApproval.comment;
const transferText=json(fixture.transfer),transferZip=await zip([{name:'web-transfer.json',bytes:Buffer.from(transferText)}]),transferArtifact={id:901,name:'cuevo-web-handover-51-1',size_in_bytes:transferZip.length,expired:false,digest:'sha256:'+hash(transferZip),created_at:new Date(now-20000).toISOString(),expires_at:new Date(now+3600000).toISOString(),workflow_run:{id:51,head_sha:input.run.head_sha,head_branch:'main'}};
const id=n=>'93000000-0000-4000-8000-'+String(n).padStart(12,'0'),project='mqxdjvsyckzocokuikmx',scope={schoolId:id(1),adminId:id(2),teacherId:id(3),studentId:id(4),classId:id(5),subjectId:id(6),referenceId:id(7)},identity={projectRef:project,schoolId:scope.schoolId,sourceSha:input.run.head_sha,treeSha:input.tree,ciRunId:'31',runId:'81',runAttempt:2,backendTransferSha256:hash(transferText),webDeploymentId:'dpl_Web'},at=new Date(now-10000).toISOString();
const backendIdentity={repository:'owner/repo',sourceSha:input.run.head_sha,treeSha:input.tree,baseSha:input.run.head_sha,ciRunId:'31',runId:'51',runAttempt:1,artifactId:'901',artifactSha256:hash(transferZip),transferSha256:hash(transferText),manifestSha256:fixture.transfer.manifestSha256,packageSha256:fixture.transfer.preparedApproval.sha256,web:backendBody.targets.web,settingsSha256:fixture.transfer.settings.settingsSha256,earliestProofAt:fixture.transfer.earliestProofAt,exportedAt:fixture.transfer.exportedAt,consumptionExpiresAt:fixture.transfer.consumptionExpiresAt};
if(input.mode==='backend-binding')backendIdentity.ciRunId='32';
const webAdmission={purpose:'PREBUILD_RELEASE_ADMISSION',sourceSha:input.run.head_sha,treeSha:input.tree,ciRunId:'31',runId:'81',runAttempt:2,webDeploymentId:'dpl_Web',artifactSha256:'d'.repeat(64),packageSha256:'e'.repeat(64),backendTransferSha256:hash(transferText),populationReceiptSha256:'f'.repeat(64),apiOrigin:'https://cuevo-api.vercel.app',authOrigin:'https://'+project+'.supabase.co',webOrigin:'https://cuevo-beta.vercel.app',webPackageExpiresAt:fixture.transfer.consumptionExpiresAt,observedAt:at},common={identity,backendIdentity,webAdmission,scope,selectedActorIds:{admin:scope.adminId,coordinator:id(8),teacher:scope.teacherId,student:scope.studentId,parent:id(9)},producerSha256:hash(readFileSync('scripts/verification/backend-hosted-learning-loop.ts'))};
const command={step:'course.create',actorId:scope.teacherId,role:'teacher',schoolId:scope.schoolId,path:'/v1/courses',operation:'course.create',sourceIds:[scope.classId,scope.subjectId],sourceRevision:null,key:'original-qa-join-course',requestBodySha256:'1'.repeat(64)},records=[];
for(const state of['INTENT','FORWARDING_AUTHORIZED','UNCERTAIN']){const sequence=records.length+1,payload={version:1,purpose:'CUEVO_HOSTED_LEARNING_LOOP_COMMAND_JOURNAL',sequence,previousRecordSha256:records.at(-1)?.recordSha256??null,identity,command,state,intentSequence:1,intentRecordSha256:sequence===1?null:records[0].recordSha256,httpReceiptSha256:null,nativeReceiptSha256:null,nativeProof:null,localDurabilityOnly:true};records.push({...payload,recordSha256:hash(review(payload))});}
const original={identity,command,intentSequence:1,intentRecordSha256:records[0].recordSha256},intent={version:1,purpose:'CUEVO_HOSTED_LEARNING_LOOP_ORIGINAL_COMMAND',original,operation:'course.create',targetId:null,sourceIds:command.sourceIds,sourceRevision:null,requestBodySha256:command.requestBodySha256,nativeFingerprint:'3'.repeat(64)},journal={records,commands:[{original,state:'UNCERTAIN',httpReceiptSha256:null,nativeReceiptSha256:null}],lastRecordSha256:records.at(-1).recordSha256,evidence:'LOCAL_DURABLE_METADATA_ONLY',hostedAcceptance:false,runnerLossRecoveryVerified:false};
const manifest={version:1,purpose:'CUEVO_HOSTED_LEARNING_LOOP_UI_EVIDENCE',...common,status:'REQUIRES_REVIEW',expectedExecutionManifest:null,apiProjection:null,journal,companions:[{path:'000001.intent.json',sha256:hash(json(intent))}],commands:[],sourceLoop:null,numericOutcome:null,nativeChainVerified:false,runnerLossRecoveryVerified:false,customerReady:false,hostedAcceptance:false};
const uiResult={purpose:'CUEVO_HOSTED_LEARNING_LOOP_UI',status:'REQUIRES_REVIEW',sourceSha:identity.sourceSha,treeSha:identity.treeSha,ciRunId:'31',runId:'81',runAttempt:2,projectRef:project,schoolId:scope.schoolId,webDeploymentId:'dpl_Web',webArtifactSha256:webAdmission.artifactSha256,webPackageSha256:webAdmission.packageSha256,backendIdentity,populationReceiptSha256:webAdmission.populationReceiptSha256,producerSha256:common.producerSha256,confirmedCommandCount:0,roleSessions:1,roleSignouts:1,sessionsClosed:true,unexpectedRequests:0,consoleErrors:0,consoleWarnings:0,pageErrors:0,sourceLoop:null,numericOutcome:null,apiProjection:null,journalLastRecordSha256:journal.lastRecordSha256,companionManifestSha256:hash(json(manifest)),nativeChainVerified:false,runnerLossRecoveryVerified:false,coreLearningLoopVerified:false,allNestedWorkflowAcceptance:false,customerReady:false,hostedAcceptance:false,observedAt:at,canonicalReceipt:null};
const scopeName='scope-'+hash(JSON.stringify([project,scope.schoolId])),journalRoot='hosted-learning-loop/'+scopeName+'/',uiRoot='hosted-learning-loop-ui/'+scopeName+'/run-81-2/',files=[{name:journalRoot+'owner.json',bytes:Buffer.from(review({version:1,purpose:'CUEVO_HOSTED_LEARNING_LOOP_COMMAND_JOURNAL',projectRef:project,schoolId:scope.schoolId})+'\n')},...records.flatMap(row=>{const index=String(row.sequence).padStart(6,'0');return[{name:journalRoot+index+'.record.json',bytes:Buffer.from(review(row)+'\n')},{name:journalRoot+index+'.head.json',bytes:Buffer.from(review({version:1,purpose:row.purpose,sequence:row.sequence,recordSha256:row.recordSha256,previousRecordSha256:row.previousRecordSha256})+'\n')}];}),{name:uiRoot+'run-intent.json',bytes:Buffer.from(json({version:1,purpose:'CUEVO_HOSTED_LEARNING_LOOP_UI',...common}))},{name:uiRoot+'command-manifest.json',bytes:Buffer.from(json(manifest))},{name:uiRoot+'result.json',bytes:Buffer.from(json(uiResult))},{name:uiRoot+'000001.intent.json',bytes:Buffer.from(json(intent))}],uiZip=await zip(files),uiArtifact={id:902,name:'cuevo-learning-loop-ui-81-2',size_in_bytes:uiZip.length,expired:false,digest:'sha256:'+hash(uiZip),created_at:new Date(now-5000).toISOString(),expires_at:new Date(now+3600000).toISOString(),workflow_run:{id:81,head_branch:'main',head_sha:identity.sourceSha}},uiRun={id:81,run_attempt:2,repository:{full_name:'owner/repo'},head_sha:identity.sourceSha,head_branch:'main',path:'.github/workflows/release.yml',event:'workflow_dispatch',status:'completed',conclusion:'failure',created_at:new Date(now-20000).toISOString(),updated_at:new Date(now-1000).toISOString()};
const endpoint={projectRef:project,kind:'session-pooler',host:'aws-1-ap-southeast-1.pooler.supabase.com',port:5432,database:'postgres'},ui={runId:'81',runAttempt:2,artifactId:'902',archiveSha256:hash(uiZip),commandManifestSha256:uiResult.companionManifestSha256,journalHeadSha256:journal.lastRecordSha256},prepared=prepareHostedLearningLoopNativePackage({repository:'owner/repo',sourceSha:identity.sourceSha,treeSha:identity.treeSha,baseSha:identity.sourceSha,ciRunId:'31',qaRunId:'91',qaRunAttempt:2,environmentId:123,environmentName:'staging',sourceManifestSha256:hash(execFileSync('git',['ls-tree','-r','-z',identity.sourceSha])),diffSha256:hash(Buffer.alloc(0)),migrationEndpoint:endpoint,migrationEndpointSha256:hash(review(endpoint)),backend:{runId:'51',runAttempt:1,artifactId:'901',archiveSha256:hash(transferZip),transferSha256:hash(transferText)},web:{deploymentId:'dpl_Web',origin:webAdmission.webOrigin,artifactSha256:webAdmission.artifactSha256,packageSha256:webAdmission.packageSha256},ui,scope:{projectRef:project,...scope,sourceIds:[...command.sourceIds].sort()},mode:'ORIGINAL_RECONCILIATION',deadlineMs:60000,preparedAt:new Date(now-5000).toISOString(),expiresAt:input.mode==='package-expiry'?new Date(now+30000).toISOString():fixture.transfer.consumptionExpiresAt},now);
const environment={id:123,name:'staging',can_admins_bypass:false,protection_rules:[{type:'required_reviewers',prevent_self_review:false,reviewers:[{type:'User',reviewer:{id:95836629,login:'attaulhaq0',type:'User'}}]}],deployment_branch_policy:{protected_branches:false,custom_branch_policies:true}},protection={allow_force_pushes:{enabled:false},allow_deletions:{enabled:false},enforce_admins:{enabled:true},required_status_checks:{strict:true,contexts:['required']},required_pull_request_reviews:{dismiss_stale_reviews:true,require_code_owner_reviews:false,required_approving_review_count:0,require_last_push_approval:false}},qaRun={id:91,run_attempt:2,repository:{full_name:'owner/repo'},head_sha:identity.sourceSha,head_branch:'main',path:'.github/workflows/hosted-learning-qa.yml',event:'workflow_dispatch',status:'in_progress',conclusion:null},qaApprovals=[{state:'approved',environments:[{id:123,name:'staging'}],user:{id:95836629,login:'attaulhaq0',type:'User'},comment:prepared.comment}];
const responses={'':{full_name:'owner/repo',name:'repo',owner:{id:1,login:'owner',type:'User'}},'git/ref/heads/main':{object:{type:'commit',sha:identity.sourceSha}},'actions/runs/31':input.run,'actions/runs/51':fixture.completedRun,'actions/runs/81':uiRun,'actions/runs/91':qaRun,'actions/artifacts/901':transferArtifact,'actions/artifacts/902':uiArtifact,'environments/staging':environment,'environments/staging/deployment-branch-policies':{total_count:1,branch_policies:[{name:'main',type:'branch'}]},'branches/main/protection':protection,'branches/main/protection/required_signatures':{enabled:true},['git/commits/'+identity.sourceSha]:{sha:identity.sourceSha,tree:{sha:identity.treeSha},verification:{verified:true,reason:'valid',signature:'controlled-signature',payload:'controlled-payload'}},'actions/runs/51/approvals':fixture.approvals,'actions/runs/91/approvals':qaApprovals};
globalThis.fetch=async(raw,options)=>{const url=new URL(String(raw));assert.equal(options.method,'GET');if(url.hostname==='api.vercel.com'){assert.equal(new Headers(options.headers).get('Authorization'),'Bearer private-vercel-fixture');if(url.pathname.includes('/deployments/')){counts.webDeployment++;return Response.json({id:'dpl_Web',projectId:'prj_Web',ownerId:'team_Cuevo',readyState:'READY',target:null,meta:{cuevoCommitSha:identity.sourceSha}});}counts.webAlias++;return Response.json({alias:'cuevo-beta.vercel.app',projectId:'prj_Web',deploymentId:'dpl_Web',redirect:null});}
assert.equal(url.origin,'https://api.github.com');assert.equal(new Headers(options.headers).get('Authorization'),'Bearer private-github-fixture');const path=url.pathname.replace('/repos/owner/repo/','');if(path.endsWith('/zip')){const id=Number(path.split('/').at(-2));if(id===901){counts.transferZip++;return new Response(new Uint8Array(transferZip));}if(id===902){counts.uiZip++;return new Response(new Uint8Array(uiZip));}counts.canonicalZip++;assert(input.archives[String(id)]);return new Response(new Uint8Array(Buffer.from(input.archives[String(id)],'base64')));}
if(path==='actions/runs/81')counts.uiMetadata++;if(path==='actions/runs/51')counts.backendMetadata++;if(path==='actions/runs/91')counts.qaRunMetadata++;const value=url.pathname==='/repos/owner/repo'?responses['']:path.includes('/jobs')?{total_count:input.jobs.length,jobs:input.jobs}:path.endsWith('/artifacts')?{total_count:input.artifacts.length,artifacts:input.artifacts}:responses[path];assert(value,'Unexpected official path '+path);return Response.json(value);};
Object.assign(process.env,{GITHUB_ACTIONS:'true',RUNNER_ENVIRONMENT:'github-hosted',GITHUB_WORKSPACE:root,GITHUB_REPOSITORY:'owner/repo',GITHUB_SHA:identity.sourceSha,GITHUB_REF:'refs/heads/main',GITHUB_EVENT_NAME:'workflow_dispatch',GITHUB_JOB:'native-qa',GITHUB_WORKFLOW_REF:'owner/repo/.github/workflows/hosted-learning-qa.yml@refs/heads/main',GITHUB_SERVER_URL:'https://github.com',GITHUB_API_URL:'https://api.github.com',RELEASE_ENVIRONMENT:'staging',GITHUB_RUN_ID:'91',GITHUB_RUN_ATTEMPT:'2',GITHUB_EVENT_PATH:joinRoot('event.json'),GH_TOKEN:'private-github-fixture',VERCEL_TOKEN:'private-vercel-fixture',SUPABASE_ACCESS_TOKEN:'private-provider-fixture',CUEVO_MIGRATION_DATABASE_PASSWORD:'private-db-fixture',CUEVO_DATABASE_TLS_CA:'-----BEGIN CERTIFICATE-----\ncontrolled join CA\n-----END CERTIFICATE-----\n',NATIVE_REVIEW_BASE64:Buffer.from(json(prepared)).toString('base64'),NATIVE_REVIEW_DIGEST:prepared.sha256});delete process.env.NODE_OPTIONS;
writeFileSync(process.env.GITHUB_EVENT_PATH,json({inputs:{commit_sha:identity.sourceSha,ci_run_id:'31',ui_run_id:'81',ui_run_attempt:'2',ui_artifact_id:'902',command_manifest_sha256:ui.commandManifestSha256,journal_head_sha256:ui.journalHeadSha256,mode:'ORIGINAL_RECONCILIATION'}}));
globalThis.qaJoinTransport={provider:async()=>{events.push('provider');return{projectRef:project,sessionEndpoint:endpoint};},endpoint:(selected,provider,digest)=>{assert.deepEqual(selected,endpoint);assert.equal(provider.projectRef,project);assert.equal(digest,hash(review(endpoint)));return endpoint;},database:async value=>{assert.equal(value.repoRoot,root);assert.equal(value.projectRef,project);assert.equal(value.password,'private-db-fixture');assert.equal(value.certificate.sha256,hash(process.env.CUEVO_DATABASE_TLS_CA));return{readLearningLoopNativeEvidence:async value=>{counts.nativeReads++;events.push('native-read');assert.deepEqual(value.selection.scope,scope);assert.equal(value.selection.originals[0].original.command.key,command.key);const course=id(100),created=new Date(now-9000).toISOString(),completed=new Date(now-8000).toISOString(),evidence={commands:[{school_id:scope.schoolId,actor_id:scope.teacherId,key:command.key,command:'course.create',fingerprint:intent.nativeFingerprint,state:'COMPLETED',response:{id:course},created_at:created,completed_at:completed}],audits:[{id:id(101),school_id:scope.schoolId,actor_id:scope.teacherId,action:'course.create',entity_type:'course',entity_id:course,request_id:'original-native-request',outcome:'succeeded',metadata:{},occurred_at:completed}],outbox:[{id:id(102),school_id:scope.schoolId,actor_id:scope.teacherId,type:'course.create',entity_type:'course',entity_id:course,version:1,metadata:{schoolAuthored:true},deduplication_key:hash(scope.teacherId+':course.create:'+command.key),occurred_at:completed,state:'PENDING',attempt_count:0,max_attempts:5,available_at:completed,lease_token:null,lease_until:null,completed_at:null,last_error_code:null}],processed:[],chain:null,policy:null};events.push('native-closed');if(input.mode==='qa-revoked')responses['actions/runs/91/approvals']=[];if(input.mode==='artifact-revoked')responses['actions/artifacts/902']={...uiArtifact,expired:true};if(input.mode==='artifact-digest')responses['actions/artifacts/902']={...uiArtifact,digest:'sha256:'+'0'.repeat(64)};if(input.mode==='package-expiry')clock=now+30000;return evidence;}};}};
let error=false;try{await runHostedLearningQa('verify');}catch{error=true;}if(input.mode==='backend-binding'){assert.equal(error,true);assert.equal(counts.nativeReads,0);assert.equal(counts.uiZip,1);assert.equal(counts.transferZip,0);assert.equal(counts.canonicalZip,0);console.log(JSON.stringify({mode:input.mode,counts,events,resultStatus:'REQUIRES_REVIEW',fixtureScope:'ACTUAL_GIT_ZIP_ISSUERS_WITH_CONTROLLED_EXTERNAL_TRANSPORT',hostedAcceptance:false}));}else{const result=JSON.parse(await readFile(root+'/.local/hosted-release/learning-native-result.json','utf8'));assert.equal(counts.uiZip,1);assert.equal(counts.transferZip,1);assert.equal(counts.canonicalZip,10);assert.equal(counts.nativeReads,1);assert.equal(result.hostedAcceptance,false);assert.equal(result.customerReady,false);if(input.mode==='valid'){assert.equal(error,false);assert.equal(result.status,'NATIVE_PROOF_VERIFIED');assert.equal(result.result.status,'ORIGINAL_RECONCILIATION_VERIFIED');assert.equal(counts.webDeployment,4);assert.equal(counts.webAlias,4);assert.equal(counts.qaRunMetadata,4);}else{assert.equal(error,true);assert.equal(result.status,'REQUIRES_REVIEW');}
console.log(JSON.stringify({mode:input.mode,counts,events,resultStatus:result.status,fixtureScope:'ACTUAL_GIT_ZIP_ISSUERS_AND_NATIVE_VALIDATOR_WITH_CONTROLLED_EXTERNAL_TRANSPORT',hostedAcceptance:false}));}
function joinRoot(name){return root+'/.local/'+name;}
async function zip(files){const{yazl}=createRequire(paths.review)('playwright-core/lib/utilsBundle'),archive=new yazl.ZipFile(),parts=[],done=new Promise((yes,no)=>{archive.outputStream.on('data',part=>parts.push(part));archive.outputStream.on('error',no);archive.outputStream.on('end',()=>yes(Buffer.concat(parts)));});for(const file of files)archive.addBuffer(file.bytes,file.name);archive.end();return done;}
`;

async function composition(mode:'valid'|'qa-revoked'|'artifact-revoked'|'artifact-digest'|'package-expiry'|'backend-binding'){
 return withCanonicalJobFixture('runtime',()=>undefined,{additionalSources:[{path:'README.md',bytes:'Actual joined QA source\n'},...backendWebTransferProducerPaths.map(path=>({path,bytes:'controlled original producer\n'})),{path:'scripts/verification/backend-hosted-learning-loop.ts',bytes:'controlled immutable UI producer\n'},{path:'supabase/migrations/20261001000000_fixture.sql',bytes:'select 1;\n'}]},async({fixture,run,jobs,artifacts,archives,tree})=>{
  const names={runner:'hosted-learning-qa.ts',ui:'backend-hosted-learning-loop-artifact.ts',backend:'backend-web-transfer-admission.ts',qa:'backend-hosted-learning-loop-admission.ts',canonical:'canonical-runtime-jobs.ts',review:'release-review.ts',contracts:'backend-release-contracts.ts',transferFixture:'backend-web-transfer-fixtures.ts'},paths=Object.fromEntries(Object.entries(names).map(([key,name])=>[key,pathToFileURL(resolve('scripts/verification',name)).href]));
  const portable:Record<string,string>={};for(const name of[names.runner,names.ui,names.backend,names.qa]){const path=resolve('scripts/verification',name),source=readFileSync(path,'utf8').replaceAll("process.platform !== 'linux'",'false').replaceAll("process.platform!=='linux'",'false').replaceAll("!root.startsWith('/home/runner/work/')",'false').replaceAll("!input.repoRoot.startsWith('/home/runner/work/')",'false');portable[pathToFileURL(path).href]=source;}
  // tsx transpiles these actual sources before the local load hook sees them.
  const{transformSync}=await import('esbuild');for(const key of Object.keys(portable))portable[key]=transformSync(portable[key],{loader:'ts',format:'esm'}).code;
  const input=join(fixture.root,'.local/join-input.json'),script=join(fixture.root,'.local/join-runner.mjs');await writeFile(input,JSON.stringify({mode,run,jobs,artifacts,archives,tree,paths,portable,producerPaths:backendWebTransferProducerPaths}));await writeFile(script,program);
  const result=spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(fixture.hook).href,script],{cwd:fixture.root,env:{...process.env,CUEVO_CANONICAL_FIXTURE_CONFIG:fixture.hookInput,CUEVO_QA_JOIN_INPUT:input},encoding:'utf8',timeout:180000});assert.equal(result.status,0,result.stderr);return JSON.parse(result.stdout.trim().split('\n').at(-1)!) as{mode:string;counts:Record<string,number>;resultStatus:string};
 });
}

test('actual hosted QA adapter joins one UI transfer and ten canonical archives through both native admissions',async()=>{const result=await composition('valid');assert.equal(result.resultStatus,'NATIVE_PROOF_VERIFIED');assert.deepEqual([result.counts.uiZip,result.counts.transferZip,result.counts.canonicalZip],[1,1,10]);console.log(JSON.stringify(result));});
test('actual hosted QA adapter refuses current revocation after native reading without reacquisition or replay',async()=>{for(const mode of['qa-revoked','artifact-revoked']as const){const result=await composition(mode);assert.equal(result.resultStatus,'REQUIRES_REVIEW');assert.equal(result.counts.nativeReads,1);console.log(JSON.stringify(result));}});
test('actual hosted QA adapter refuses changed artifact digest after native reading',async()=>{const result=await composition('artifact-digest');assert.equal(result.resultStatus,'REQUIRES_REVIEW');assert.equal(result.counts.nativeReads,1);console.log(JSON.stringify(result));});
test('actual hosted QA adapter refuses original package expiry within the native read budget',async()=>{const result=await composition('package-expiry');assert.equal(result.resultStatus,'REQUIRES_REVIEW');assert.equal(result.counts.nativeReads,1);console.log(JSON.stringify(result));});
test('actual hosted QA adapter rejects a foreign backend CI binding before native reading',async()=>{const result=await composition('backend-binding');assert.equal(result.resultStatus,'REQUIRES_REVIEW');assert.equal(result.counts.nativeReads,0);console.log(JSON.stringify(result));});
