import {createHash} from 'node:crypto';
import {brotliCompressSync,constants} from 'node:zlib';

const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
/** Controlled envelope bytes exercise consumers, never certify native bundling. */
export function createPreparedEdgeFixture(input:{sourceSha?:string;treeSha?:string;sourceLockSha256?:string;denoLockSha256?:string;sources?:{path:string;sha256:string}[]}={}){
 const raw=Buffer.from('ESZIP2.3controlled consumer envelope'),ezbr=Buffer.concat([Buffer.from('EZBR'),brotliCompressSync(raw,{params:{[constants.BROTLI_PARAM_QUALITY]:6}})]),config=JSON.stringify({nodeModulesDir:'manual'}),sources=input.sources??[{path:'apps/worker/src/edge.ts',sha256:hash('controlled source')}],dependencies=[{path:'node_modules/pg',version:'8.23.1',integrity:'sha512-'+'A'.repeat(86)+'=='}],inputFiles=[{path:'index.ts',sha256:hash('controlled index'),byteSize:16},{path:'deno.json',sha256:hash(config),byteSize:Buffer.byteLength(config)},{path:'package.json',sha256:hash('controlled package'),byteSize:18},{path:'package-lock.json',sha256:hash('controlled lock'),byteSize:15},{path:'node_modules/pg/package.json',sha256:hash('controlled pg package'),byteSize:21}].sort((a,b)=>a.path.localeCompare(b.path)),packageFiles=inputFiles.filter(row=>row.path.startsWith('node_modules/'));
 const body={version:1 as const,purpose:'CUEVO_PREPARED_EDGE_ESZIP' as const,schemaVersion:2 as const,service:'cuevo-worker' as const,runtime:'deno' as const,entrypoint:'edge/index.ts' as const,imports:['pg' as const],sourceSha:input.sourceSha??'a'.repeat(40),treeSha:input.treeSha??'b'.repeat(40),runtimeVersion:'1.77.1' as const,platform:'linux/amd64' as const,baseImage:'public.ecr.aws/supabase/edge-runtime@sha256:645d0e45446181f3e9d87efeef637b494615f32365befff00e2d2b0fe8535fef',preparedImageId:'sha256:'+'d'.repeat(64),sourceLockSha256:input.sourceLockSha256??'c'.repeat(64),denoLockSha256:input.denoLockSha256??hash('lock'),configSha256:hash(config),sourceGraphSha256:hash(JSON.stringify(sources)),physicalGraphSha256:hash(JSON.stringify(inputFiles)),sources,dependencies,inputFiles,files:[{path:'worker.ezbr',sha256:hash(ezbr),byteSize:ezbr.length}],rawEszipSha256:hash(raw),ezbrSha256:hash(ezbr),rawByteSize:raw.length,compressedByteSize:ezbr.length,nativeUnbundleSha256:hash(JSON.stringify(packageFiles)),nativeUnbundleFileCount:packageFiles.length,cleanup:'CONFIRMED_REMOVED' as const,effectAuthority:false as const,hostedAcceptance:false as const};
 return{manifest:{...body,manifestSha256:hash(JSON.stringify(body))},ezbr,raw};
}
