import{execFileSync}from'node:child_process';import{mkdir,readFile,writeFile}from'node:fs/promises';import{resolve}from'node:path';import{Pool}from'pg';import{randomUUID,createHash}from'node:crypto';import{createClient}from'@supabase/supabase-js';import{assertCuevoLocalConfig,assertCuevoLocalTarget,type LocalStatus}from'../configure-local';import{validateRecoveryTarget}from'./rules';
import{verifyRestoredSecurity}from'./restored-security';
for(const port of[3000,4000,4001]){let reachable=false;try{await fetch('http://127.0.0.1:'+port+'/health/live',{signal:AbortSignal.timeout(1000)});reachable=true;}catch{/* Expected when local applications are stopped. */}if(reachable)throw Error('Stop Cuevo application processes before the recovery drill.');}
await readFile('supabase/config.toml','utf8').then(assertCuevoLocalConfig);const cli=resolve('node_modules/supabase/dist/supabase.js');const status=JSON.parse(execFileSync(process.execPath,[cli,'status','-o','json'],{encoding:'utf8',stdio:['ignore','pipe','ignore']}))as LocalStatus;assertCuevoLocalTarget(status);const scratch='cuevo_recovery_'+Date.now();validateRecoveryTarget(status.DB_URL,scratch);const directory=resolve('.local/verification',scratch);await mkdir(directory,{recursive:true});const archive=resolve(directory,'database.dump');
const admin=new Pool({connectionString:status.DB_URL,max:1});const checks:{name:string;passed:boolean}[]=[];let scratchCreated=false;let cleanupComplete=false;let backupTransaction=false;const objectPath='recovery/'+scratch+'/fixture.txt';let objectCreated=false;
const storage=createClient(status.API_URL,status.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{fetch:(input,init)=>fetch(input,{...init,signal:AbortSignal.timeout(10000)})}}).storage.from('learner-private');
try{
 const workerUrl=process.env.WORKER_DATABASE_URL?new URL(process.env.WORKER_DATABASE_URL):null;if(!workerUrl||workerUrl.hostname!=='127.0.0.1'||workerUrl.port!=='56322'||workerUrl.username!=='cuevo_worker')throw Error('Restricted local worker credentials required');
 const drain=new Pool({connectionString:workerUrl.toString(),max:2});try{for(let turn=0;turn<50;turn++){const pending=(await drain.query('select *from internal.claim_outbox(100,30)')).rows;if(!pending.length)break;for(const event of pending)await drain.query('select internal.process_learner_event($1,$2)',[event.id,event.lease_token]);}}finally{await drain.end();}
 const queue=(await admin.query("select count(*)::integer count from internal.outbox_events where state<>'COMPLETED'")).rows[0].count;
 if(queue!==0)throw Error('Queue requires review before the recovery drill.');
 // Ownership recovery is confined to a separate scratch DB; ordinary domain tests still use restricted roles.
 await admin.query('begin isolation level repeatable read read only');backupTransaction=true;const exported=(await admin.query('select pg_export_snapshot()as snapshot')).rows[0].snapshot as string;
 execFileSync('docker',['exec','supabase_db_cuevo','pg_dump','-U','supabase_admin','-d','postgres','-Fc','--no-owner','--snapshot='+exported,'-f','/tmp/'+scratch+'.dump'],{stdio:'ignore'});execFileSync('docker',['cp','supabase_db_cuevo:/tmp/'+scratch+'.dump',archive],{stdio:'ignore'});
 execFileSync('docker',['exec','supabase_db_cuevo','createdb','-U','supabase_admin','--template=template0',scratch],{stdio:'ignore'});scratchCreated=true;execFileSync('docker',['exec','supabase_db_cuevo','pg_restore','-U','supabase_admin','-d',scratch,'--no-owner','--exit-on-error','/tmp/'+scratch+'.dump'],{stdio:'ignore'});
 const fingerprint=async(pool:Pool)=>{const tables=(await pool.query("select n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('app','internal','authorization','auth','storage','supabase_migrations')and c.relkind='r'order by n.nspname,c.relname")).rows;const output:{table:string;hash:string;count:number}[]=[];for(const table of tables){const name='"'+String(table.nspname).replaceAll('"','""')+'"."'+String(table.relname).replaceAll('"','""')+'"';const data=(await pool.query('select to_jsonb(row)::text data from '+name+' row order by to_jsonb(row)::text')).rows;output.push({table:name,count:data.length,hash:createHash('sha256').update(data.map(r=>r.data).join('\n')).digest('hex')});}return output;};
 const before=await fingerprint(admin);await admin.query('rollback');backupTransaction=false;const scratchUrl=new URL(status.DB_URL);scratchUrl.pathname='/'+scratch;const restored=new Pool({connectionString:scratchUrl.toString()});try{const after=await fingerprint(restored);checks.push({name:'database_restore_source_hashes',passed:JSON.stringify(before)===JSON.stringify(after)});if(!process.env.DATABASE_URL)throw Error('Restricted API configuration required for restored verification.');checks.push(await verifyRestoredSecurity(restored,process.env.DATABASE_URL,scratch));}finally{await restored.end();}
 const bytes=Buffer.from('Synthetic Storage restore '+scratch);const digest=createHash('sha256').update(bytes).digest('hex');const upload=await storage.upload(objectPath,bytes,{contentType:'text/plain',upsert:false});if(upload.error)throw Error('Recovery synthetic object upload failed');objectCreated=true;const snapshot=await storage.download(objectPath);if(snapshot.error||!snapshot.data)throw Error('Recovery object snapshot failed');const saved=Buffer.from(await snapshot.data.arrayBuffer());await writeFile(resolve(directory,'object.bin'),saved,{mode:0o600});const removed=await storage.remove([objectPath]);if(removed.error)throw Error('Recovery synthetic object removal failed');const restoredObject=await storage.upload(objectPath,saved,{contentType:'text/plain',upsert:false});if(restoredObject.error)throw Error('Recovery object restore failed');const objectRead=await storage.download(objectPath);const output=objectRead.data?Buffer.from(await objectRead.data.arrayBuffer()):Buffer.alloc(0);checks.push({name:'private_storage_restore_bytes',passed:!objectRead.error&&createHash('sha256').update(output).digest('hex')===digest});
 // Dedicated temporary queue fixture proves two restricted clients cannot both own one lease.
 const key='recovery:'+randomUUID();const source=(await admin.query("insert into internal.outbox_events(school_id,actor_id,type,entity_type,entity_id,version,metadata,deduplication_key)values('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','recovery.fixture','recovery',gen_random_uuid(),1,'{}',$1)returning id",[key])).rows[0].id;
 const workers=new Pool({connectionString:workerUrl.toString(),max:2});try{const [a,b]=await Promise.all([workers.query('select *from internal.claim_outbox(1,5)'),workers.query('select *from internal.claim_outbox(1,5)')]);const claim=[...a.rows,...b.rows].filter(row=>row.id===source);checks.push({name:'two_worker_single_lease',passed:claim.length===1});if(claim.length!==1)throw Error('Recovery lease test failed');await admin.query("update internal.outbox_events set lease_until=clock_timestamp()-interval'1 second'where id=$1",[source]);const again=(await workers.query('select *from internal.claim_outbox(1,5)')).rows.find(row=>row.id===source);checks.push({name:'expired_lease_reclaimed',passed:Boolean(again&&again.lease_token!==claim[0].lease_token)});const stale=(await workers.query('select internal.complete_outbox($1,$2)ack',[source,claim[0].lease_token])).rows[0].ack;checks.push({name:'stale_lease_ack_denied',passed:stale===false});if(again)await workers.query('select internal.complete_outbox($1,$2)',[source,again.lease_token]);}finally{await workers.end();await admin.query('delete from internal.outbox_events where id=$1',[source]);}
 if(!checks.every(c=>c.passed))throw Error('Recovery check failed');
}catch(error){checks.push({name:'drill_completed',passed:false});throw error;}finally{let clean=true;try{if(backupTransaction)await admin.query('rollback');if(objectCreated){const removed=await storage.remove([objectPath]);if(removed.error)clean=false;}if(scratchCreated)execFileSync('docker',['exec','supabase_db_cuevo','dropdb','-U','supabase_admin','--force',scratch],{stdio:'ignore'});}catch{clean=false;}checks.push({name:'scratch_cleanup',passed:clean});await admin.end();await writeFile(resolve(directory,'recovery.json'),JSON.stringify({status:checks.every(c=>c.passed)?'VERIFIED':'FAILED',checks},null,2));cleanupComplete=clean;}
if(!cleanupComplete)throw Error('Recovery scratch cleanup requires review.');console.log('Guarded local recovery verified: '+directory);
