import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {lstatSync,readFileSync,realpathSync} from 'node:fs';
import {isAbsolute,resolve} from 'node:path';
import {z} from 'zod';
import {canonicalReleaseExecutionJson} from './release-review';
import {readCanonicalMigrationSources,readHistoricalMigrationSources} from '../database/hosted-migration-plan';

const digest=z.string().regex(/^[a-f0-9]{64}$/),sha=z.string().regex(/^[a-f0-9]{40}$/),row=z.object({path:z.string(),sha256:digest}).strict(),hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),fail=()=>Error('Source-owned runtime contracts require review.');
export const runtimeContractManifestSchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_SOURCE_RUNTIME_CONTRACTS'),sourceSha:sha,treeSha:sha,sourceLockSha256:digest,denoLockSha256:digest,protocolVersion:z.literal('cuevo.worker.wake.v1'),apiContractSha256:digest,workerContractSha256:digest,migrationSetSha256:digest,migrationList:z.array(z.object({name:z.string(),version:z.string().regex(/^\d{14}$/),sha256:digest}).strict()).min(1).max(1000),apiFiles:z.array(row).min(1).max(5000),workerFiles:z.array(row).min(1).max(5000)}).strict();
export type RuntimeContractManifest=z.infer<typeof runtimeContractManifestSchema>;
// Wire schemas alone cannot establish backward-compatible access authority.
// Changes to identity, tenant transaction context or account lifecycle require
// explicit compatibility review even when endpoint shapes remain unchanged.
const apiOwner=(path:string)=>/^packages\/contracts\/.*\.ts$/.test(path)||/^apps\/api\/src\/modules\/[^/]+\/.*\.(?:controller|service)\.ts$/.test(path)||path==='apps/api/src/app.ts'||path==='apps/api/src/main.ts'||path==='packages/domain/src/authorization.ts'||/^packages\/config\/src\/(?:index|auth-provisioning|synthetic-runtime)\.ts$/.test(path)||/^apps\/api\/src\/platform\/identity\/.*\.ts$/.test(path)||path==='apps/api/src/platform/database/database.ts'||path==='apps/api/src/platform/request-limits/request-limits.ts';
const workerOwner=(path:string)=>path==='apps/worker/src/jobs/outbox/edge-handler.ts'||path==='packages/config/src/synthetic-runtime.ts'||path==='packages/config/src/index.ts'||/^supabase\/migrations\/\d{14}_.*\.sql$/.test(path);
/** Private contract acquisition only. Batching immutable blob requests removes
 * per-file process work; it never caches physical source or native authority. */
function readContractBlobs(root:string,sourceSha:string,treeSha:string,purpose:'CURRENT_SOURCE'|'HISTORICAL_OBSERVATION'){
 const maximumBlob=16*1024*1024,maximumTotal=64*1024*1024,maximumBatch=16*1024*1024;
 const actual=realpathSync(root);if(!isAbsolute(root)||resolve(root)!==actual||lstatSync(root).isSymbolicLink()||!sha.safeParse(sourceSha).success||!sha.safeParse(treeSha).success)throw fail();root=actual;
 const env=Object.fromEntries(['PATH','Path','SystemRoot','SYSTEMROOT','WINDIR','TEMP','TMP','LANG','LC_ALL'].filter(key=>process.env[key]!==undefined).map(key=>[key,process.env[key]]).concat([['GIT_NO_REPLACE_OBJECTS','1'],['GIT_CONFIG_NOSYSTEM','1'],['GIT_CONFIG_GLOBAL',process.platform==='win32'?'NUL':'/dev/null']]));
 const git=(args:string[],input?:string)=>{try{return execFileSync('git',['-C',root,...args],{input,env,shell:false,windowsHide:true,stdio:['pipe','pipe','ignore'],maxBuffer:maximumTotal,timeout:15000});}catch{throw fail();}};
 if(!['CURRENT_SOURCE','HISTORICAL_OBSERVATION'].includes(purpose))throw fail();
 const metadata=()=>{if(realpathSync(root)!==root||lstatSync(root).isSymbolicLink()||resolve(git(['rev-parse','--show-toplevel']).toString('utf8').trim())!==root||git(['rev-parse','--verify',sourceSha+'^{commit}']).toString('ascii').trim()!==sourceSha||git(['rev-parse','--verify',sourceSha+'^{tree}']).toString('ascii').trim()!==treeSha||git(['for-each-ref','--format=%(refname)','refs/replace']).length)throw fail();const head=git(['rev-parse','--verify','HEAD^{commit}']).toString('ascii').trim(),headTree=git(['rev-parse','--verify','HEAD^{tree}']).toString('ascii').trim(),headRef=git(['rev-parse','--symbolic-full-name','HEAD']).toString('utf8').trim();if(!sha.safeParse(head).success||!sha.safeParse(headTree).success||purpose==='CURRENT_SOURCE'&&head!==sourceSha)throw fail();const graft=git(['rev-parse','--git-path','info/grafts']).toString('utf8').trim();try{if(readFileSync(isAbsolute(graft)?graft:resolve(root,graft)).length)throw fail();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw fail();}return{head,headTree,headRef,graft};},initialMetadata=metadata(),finish=()=>{if(canonicalReleaseExecutionJson(metadata())!==canonicalReleaseExecutionJson(initialMetadata))throw fail();};
 const tree=git(['ls-tree','-r','-z',sourceSha]);if(tree.length>16*1024*1024)throw fail();const raw=new TextDecoder('utf8',{fatal:true}).decode(tree).split('\0');if(raw.pop()!==''||raw.length>20000)throw fail();
 const paths=new Set<string>(),entries: {path:string;blob:string}[]=[];
 for(const row of raw){const match=/^([0-9]{6}) (blob|commit) ([a-f0-9]{40})\t(.+)$/.exec(row);if(!match)throw fail();const path=match[4];if(paths.has(path)||path.includes('\\')||/[\r\n\0]/.test(path)||path.startsWith('/')||path.split('/').some(piece=>!piece||piece==='.'||piece==='..'))throw fail();paths.add(path);if(path==='package-lock.json'||apiOwner(path)||workerOwner(path)){if(!['100644','100755'].includes(match[1])||match[2]!=='blob')throw fail();entries.push({path,blob:match[3]});}}
 if(!entries.some(row=>row.path==='package-lock.json')||!entries.length||entries.length>5001)throw fail();
 const check=git(['cat-file','--batch-check'],entries.map(row=>row.blob).join('\n')+'\n').toString('ascii').split('\n');if(check.pop()!==''||check.length!==entries.length)throw fail();let total=0;
 const sized=entries.map((row,index)=>{const match=/^([a-f0-9]{40}) blob ([0-9]+)$/.exec(check[index]);if(!match||match[1]!==row.blob)throw fail();const size=Number(match[2]);if(!Number.isSafeInteger(size)||size>maximumBlob)throw fail();total+=size;if(total>maximumTotal)throw fail();return{...row,size};});
 const files:{path:string;bytes:Uint8Array}[]=[];
 for(let start=0;start<sized.length;){const selected:typeof sized=[];let size=0;while(start<sized.length&&(!selected.length||size+sized[start].size<=maximumBatch)){size+=sized[start].size;selected.push(sized[start++]);}const batch=git(['cat-file','--batch'],selected.map(row=>row.blob).join('\n')+'\n');let offset=0;
  for(const row of selected){const end=batch.indexOf(10,offset);if(end<0||end-offset>100)throw fail();const match=/^([a-f0-9]{40}) blob ([0-9]+)$/.exec(batch.subarray(offset,end).toString('ascii'));if(!match||match[1]!==row.blob||Number(match[2])!==row.size)throw fail();offset=end+1;const bytes=batch.subarray(offset,offset+row.size);if(bytes.length!==row.size||batch[offset+row.size]!==10)throw fail();offset+=row.size+1;files.push({path:row.path,bytes:new Uint8Array(bytes)});}if(offset!==batch.length)throw fail();
 }return{files,finish};
}
export function createRuntimeContractManifest(input:{sourceSha:string;treeSha:string;sourceLockSha256:string;denoLockSha256:string;files:{path:string;bytes:Uint8Array}[];migrationList:RuntimeContractManifest['migrationList']}):RuntimeContractManifest{
 if(new Set(input.files.map(row=>row.path)).size!==input.files.length||input.files.some(row=>row.path.includes('\\')||row.path.startsWith('/')||row.path.split('/').some(part=>!part||part==='.'||part==='..')))throw fail();const group=(admit:(path:string)=>boolean)=>input.files.filter(row=>admit(row.path)).map(row=>({path:row.path,sha256:hash(row.bytes)})).sort((a,b)=>a.path.localeCompare(b.path)),apiFiles=group(apiOwner),workerFiles=group(workerOwner);if(!apiFiles.some(row=>row.path.startsWith('packages/contracts/'))||!apiFiles.some(row=>row.path.endsWith('.controller.ts'))||!workerFiles.some(row=>row.path==='apps/worker/src/jobs/outbox/edge-handler.ts')||!workerFiles.some(row=>row.path==='packages/config/src/synthetic-runtime.ts')||!workerFiles.some(row=>row.path.startsWith('supabase/migrations/')))throw fail();return runtimeContractManifestSchema.parse({version:1,purpose:'CUEVO_SOURCE_RUNTIME_CONTRACTS',sourceSha:input.sourceSha,treeSha:input.treeSha,sourceLockSha256:input.sourceLockSha256,denoLockSha256:input.denoLockSha256,protocolVersion:'cuevo.worker.wake.v1',apiContractSha256:hash(canonicalReleaseExecutionJson(apiFiles)),workerContractSha256:hash(canonicalReleaseExecutionJson(workerFiles)),migrationSetSha256:hash(canonicalReleaseExecutionJson(input.migrationList)),migrationList:input.migrationList,apiFiles,workerFiles});
}
/** Exact Git blob inventory and complete canonical migration set. No operator
 * compatibility assertion or supplied proof digest establishes these contracts. */
export function readRuntimeContractManifest(root:string,sourceSha:string,treeSha:string,denoLockSha256:string):RuntimeContractManifest{
 try{const acquired=readContractBlobs(root,sourceSha,treeSha,'CURRENT_SOURCE'),lock=acquired.files.find(row=>row.path==='package-lock.json')!,files=acquired.files.filter(row=>row!==lock),migrations=readCanonicalMigrationSources({repoRoot:root,sourceSha,treeSha}).sources.map(row=>({name:row.name,version:row.name.slice(0,14),sha256:hash(row.bytes)})),manifest=createRuntimeContractManifest({sourceSha,treeSha,sourceLockSha256:hash(lock.bytes),denoLockSha256,files,migrationList:migrations});acquired.finish();return manifest;}catch{throw fail();}
}
/** Installed-source observation only. Exact historical Git objects supply the
 * contract; current source admission, native state and effect approval remain
 * independent. No historical working files, binaries or approval are reused. */
export function readHistoricalRuntimeContractManifest(root:string,sourceSha:string,treeSha:string,denoLockSha256:string):RuntimeContractManifest{
 try{const acquired=readContractBlobs(root,sourceSha,treeSha,'HISTORICAL_OBSERVATION'),lock=acquired.files.find(row=>row.path==='package-lock.json')!,files=acquired.files.filter(row=>row!==lock),migrations=readHistoricalMigrationSources(root,sourceSha,treeSha).map(row=>({name:row.name,version:row.name.slice(0,14),sha256:hash(row.bytes)})),manifest=createRuntimeContractManifest({sourceSha,treeSha,sourceLockSha256:hash(lock.bytes),denoLockSha256,files,migrationList:migrations});acquired.finish();return manifest;}catch{throw fail();}
}
export function validateRuntimeContractManifest(value:unknown):RuntimeContractManifest{const manifest=runtimeContractManifestSchema.parse(JSON.parse(canonicalReleaseExecutionJson(value)));if(manifest.apiContractSha256!==hash(canonicalReleaseExecutionJson(manifest.apiFiles))||manifest.workerContractSha256!==hash(canonicalReleaseExecutionJson(manifest.workerFiles))||manifest.migrationSetSha256!==hash(canonicalReleaseExecutionJson(manifest.migrationList))||new Set(manifest.apiFiles.map(row=>row.path)).size!==manifest.apiFiles.length||new Set(manifest.workerFiles.map(row=>row.path)).size!==manifest.workerFiles.length||manifest.apiFiles.some(row=>!apiOwner(row.path))||manifest.workerFiles.some(row=>!workerOwner(row.path)))throw fail();return manifest;}
