import { execFileSync } from 'node:child_process';
import type { ChildProcess } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { lstat, mkdir, mkdtemp, chmod, readFile, realpath, rename, rm, writeFile } from 'node:fs/promises';
import {tmpdir} from 'node:os';
import { isAbsolute, join, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { performance } from 'node:perf_hooks';
import { stripVTControlCharacters } from 'node:util';
import { z } from 'zod';
import { spawnOwnedProcess, stopOwnedProcesses } from '../runtime/process';
import { statelessVerificationSteps } from './steps';
import {readCiPartitionCoverage,ciPartitionFiles,ciPartitionFileSelections,type CiPartitionCoverage} from './ci-partition-coverage';
import {canonicalReleaseExecutionJson} from './release-review';
import {readSourceTestCohortPlan,sourceTestCohortCommand,recordSourceTestCohort,aggregateSourceTestCohorts,validateSourceTestCohortEvidence,sourceTestCohortEvidenceSchema,SOURCE_TEST_COHORT_FILE,type SourceTestCohortReceipt,type SourceTestCohortPlan} from './source-test-cohorts';

const failure=()=>Error('Stateless source-contract evidence requires review; private contents withheld.');
const digest=z.string().regex(/^[a-f0-9]{64}$/),sha=z.string().regex(/^[a-f0-9]{40}$/),identifier=z.string().regex(/^[1-9][0-9]{0,18}$/);
const names=statelessVerificationSteps.map(step=>step.name),safePath=z.string().regex(/^scripts\/[a-zA-Z0-9_./-]+[.]ts$/).refine(value=>value.split('/').every(piece=>piece&&piece!=='.'&&piece!=='..'));
const count=z.number().int().min(0).max(1000000),testSummary=z.object({tests:count,pass:count,fail:count,cancelled:count,skipped:count,todo:count}).strict();
const groupSchema=z.object({name:z.string().refine(value=>names.includes(value as typeof names[number])),commandSha256:digest,files:z.array(z.object({path:safePath,sha256:digest}).strict()).max(200),status:z.enum(['NOT_STARTED','PASSED','FAILED','CANCELLED','PROCESS_ERROR','COVERAGE_UNCONFIRMED','STOP_UNCONFIRMED']),exitCode:z.number().int().min(0).max(255).nullable(),signal:z.enum(['SIGTERM','SIGKILL','SIGINT','OTHER']).nullable(),durationMs:z.number().int().min(0).max(86400000),startedAtMs:z.number().int().nonnegative().nullable(),completedAtMs:z.number().int().nonnegative().nullable(),scratchId:z.uuid(),failedFiles:z.array(safePath).max(200),failedTests:z.array(z.object({path:safePath,titleSha256:digest}).strict()).max(1000),summary:testSummary.nullable(),fileOnlyCases:count,stdoutBytes:z.number().int().min(0).max(2147483647),stderrBytes:z.number().int().min(0).max(2147483647)}).strict();
export const statelessChecksEvidenceSchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_STATELESS_SOURCE_CONTRACTS'),status:z.enum(['PASSED','FAILED','CANCELLED','SOURCE_CHANGED','INPUT_REQUIRES_REVIEW','STOP_UNCONFIRMED']),source:z.object({sourceSha:sha.nullable(),treeSha:sha.nullable(),sourceLockSha256:digest.nullable(),toolchainSha256:digest,nodeVersion:z.string().regex(/^v[0-9]+[.][0-9]+[.][0-9]+$/),nodeBinarySha256:digest.nullable(),runId:identifier.nullable(),runAttempt:z.number().int().positive().max(Number.MAX_SAFE_INTEGER).nullable(),frozenBefore:z.boolean(),frozenAfter:z.boolean()}).strict(),discoverySha256:digest,groups:z.array(groupSchema).min(1).max(30),failedGroup:z.string().refine(value=>names.includes(value as typeof names[number])).nullable(),recordedAt:z.iso.datetime({offset:true})}).strict().superRefine((value,context)=>{
 if(value.groups.length!==statelessVerificationSteps.length||value.groups.some((row,index)=>row.name!==statelessVerificationSteps[index].name||row.commandSha256!==hash(JSON.stringify([...statelessVerificationSteps[index].args]))||row.files.some(file=>!(statelessVerificationSteps[index].args as readonly string[]).includes(file.path))||row.failedFiles.some(path=>!row.files.some(file=>file.path===path))||row.failedTests.some(test=>!row.failedFiles.includes(test.path))||row.status==='PASSED'&&(row.exitCode!==0||row.signal!==null||row.fileOnlyCases!==0||(statelessVerificationSteps[index].args as readonly string[]).includes('--test')&&(!row.summary||row.summary.tests<1||row.summary.pass!==row.summary.tests||row.summary.fail+row.summary.cancelled+row.summary.skipped+row.summary.todo!==0))||row.status==='NOT_STARTED'&&(row.startedAtMs!==null||row.completedAtMs!==null||row.exitCode!==null)||row.startedAtMs!==null&&row.completedAtMs!==null&&row.startedAtMs>row.completedAtMs))context.addIssue({code:'custom',message:'Exact original group inventory and outcomes are required.'});
 if(value.status==='PASSED'&&(!value.source.frozenBefore||!value.source.frozenAfter||!value.source.sourceSha||!value.source.treeSha||!value.source.sourceLockSha256||!value.source.nodeBinarySha256||value.groups.some(row=>row.status!=='PASSED'))||(value.source.runId===null)!==(value.source.runAttempt===null))context.addIssue({code:'custom',message:'Complete frozen source and all groups are required for success.'});
 if(value.discoverySha256!==hash(JSON.stringify(value.groups.map(row=>({name:row.name,commandSha256:row.commandSha256,files:row.files}))))||value.groups.some((row,index)=>new Set(row.files.map(file=>file.path)).size!==row.files.length||row.status!=='NOT_STARTED'&&(row.startedAtMs===null||row.completedAtMs===null)||value.status!=='INPUT_REQUIRES_REVIEW'&&!same(row.files.map(file=>file.path),(statelessVerificationSteps[index].args as readonly string[]).filter(arg=>arg.startsWith('scripts/')&&arg.endsWith('.ts')))))context.addIssue({code:'custom',message:'Complete original discovery and actual execution clocks are required.'});
});
export type StatelessChecksEvidence=z.infer<typeof statelessChecksEvidenceSchema>;
const partitionIds=['source-native','source-contracts','source-delivery']as const;
const partitionStatus=z.enum(['NOT_VERIFIED','PASSED','FAILED','CANCELLED']);
export const partitionIdentitySchema=z.object({repository:z.string().regex(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/),sourceSha:sha,treeSha:sha,sourceDigest:digest,sourceLockSha256:digest,partitionManifestSha256:digest,nodeVersion:z.string().regex(/^v24[.][0-9]+[.][0-9]+$/),nodeBinarySha256:digest,toolchainSha256:digest,environmentPolicySha256:digest,runId:identifier,runAttempt:z.number().int().positive(),job:z.string()}).strict();
const partitionCaseSchema=z.object({definitionSha256:digest,outcome:z.enum(['PASSED','FAILED','SKIPPED','TODO'])}).strict();
const reportCaseSchema=z.object({titleSha256:digest,suiteSha256:digest.nullable(),line:z.number().int().positive().max(1000000),column:z.number().int().positive().max(1000000),nesting:z.number().int().nonnegative().max(100),outcome:z.enum(['PASSED','FAILED','SKIPPED','TODO'])}).passthrough();
const partitionFileSchema=z.object({path:safePath,sha256:digest,group:z.string(),durationMs:z.number().finite().min(0).max(86400000).nullable(),cases:z.array(partitionCaseSchema).max(10000),cohortEvidence:sourceTestCohortEvidenceSchema.optional()}).strict();
export const partitionReceiptSchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_STATELESS_SOURCE_PARTITION'),partition:z.enum(partitionIds),status:partitionStatus,identity:partitionIdentitySchema,files:z.array(partitionFileSchema).min(1).max(200),startedAtMs:observedClock(),completedAtMs:observedClock().nullable(),exitCode:z.number().int().min(0).max(255).nullable(),signal:z.enum(['SIGTERM','SIGKILL','SIGINT','OTHER']).nullable(),frozenBefore:z.boolean(),frozenAfter:z.boolean(),cleanupConfirmed:z.boolean(),reasons:z.array(z.enum(['INPUT_REQUIRES_REVIEW','PROCESS_FAILED','COVERAGE_UNCONFIRMED','SOURCE_CHANGED','STOP_UNCONFIRMED','CANCELLED'])).max(10),payloadSha256:digest}).strict();
export const sourceSummarySchema=z.object({version:z.literal(1),purpose:z.literal('CUEVO_PARTITIONED_SOURCE_CONTRACTS'),status:z.literal('PASSED'),identity:partitionIdentitySchema,partitions:z.array(z.object({partition:z.enum(partitionIds),job:z.string(),payloadSha256:digest,receiptSha256:digest}).strict()).length(3),files:z.array(partitionFileSchema).min(1).max(500),checks:z.array(z.object({name:z.string(),commandSha256:digest,exitCode:z.literal(0),durationMs:z.number().int().nonnegative()}).strict()).max(30)}).strict();
function observedClock(){return z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);}
export type StatelessPartitionReceipt=z.infer<typeof partitionReceiptSchema>;
export type StatelessPartitionIdentity=z.infer<typeof partitionIdentitySchema>;
export function validateParsedPartitionOutcome(result:StatelessPartitionReceipt){const{payloadSha256,...body}=result;if(hash(canonicalReleaseExecutionJson(body))!==payloadSha256||result.identity.job!==expectedJob(result.partition)||new Set(result.files.map(row=>row.path)).size!==result.files.length||result.files.some(file=>new Set(file.cases.map(row=>row.definitionSha256)).size!==file.cases.length))throw failure();if(result.status==='PASSED'&&(!result.frozenBefore||!result.frozenAfter||!result.cleanupConfirmed||result.exitCode!==0||result.signal!==null||result.reasons.length||result.completedAtMs===null||result.completedAtMs<result.startedAtMs||result.files.some(file=>!file.cases.length||file.durationMs===null||file.cases.some(row=>row.outcome!=='PASSED'))))throw failure();return result;}
const expectedJob=(partition:string)=>'source-fixtures-'+partition.slice(7);
const payload=(value:Omit<StatelessPartitionReceipt,'payloadSha256'>)=>({...value,payloadSha256:hash(canonicalReleaseExecutionJson(value))});
export function validateStatelessPartition(value:unknown,expected:StatelessPartitionIdentity,coverage:CiPartitionCoverage):StatelessPartitionReceipt{
 const result=validateParsedPartitionOutcome(partitionReceiptSchema.parse(JSON.parse(canonicalReleaseExecutionJson(value))));
 return validateSelectedStatelessPartition(result,expected,coverage,ciPartitionFiles(coverage,'source',result.partition,'full'));
}
function validateSelectedStatelessPartition(result:StatelessPartitionReceipt,expected:StatelessPartitionIdentity,coverage:CiPartitionCoverage,files:readonly string[]):StatelessPartitionReceipt{
 if(result.identity.partitionManifestSha256!==coverage.manifestSha256)throw failure();
 for(const key of Object.keys(partitionIdentitySchema.shape)as(keyof StatelessPartitionIdentity)[])if(key!=='job'&&result.identity[key]!==expected[key])throw failure();
 if(!same(result.files.map(row=>row.path),files)||new Set(result.files.map(row=>row.path)).size!==result.files.length)throw failure();
 for(const file of result.files){const group=statelessVerificationSteps.find(step=>(step.args as readonly string[]).includes(file.path));if(!group||file.group!==group.name||new Set(file.cases.map(row=>row.definitionSha256)).size!==file.cases.length)throw failure();if(coverage.sourceCohorts?.file===file.path){const plan=readSourceTestCohortPlan(resolve(import.meta.dirname,'../..'));if(plan.policySha256!==coverage.sourceCohorts.policySha256||!file.cohortEvidence)throw failure();const rebuilt=validateSourceTestCohortEvidence(plan,file.cohortEvidence,sourceCohortIdentity(result.identity));if(!same(rebuilt,file)||result.completedAtMs===null||file.cohortEvidence.receipts.some(row=>row.reportStartedAtMs<result.startedAtMs||row.reportCompletedAtMs>result.completedAtMs!))throw failure();}else if(file.cohortEvidence)throw failure();}
 return result;
}
const sourceCohortIdentity=(identity:StatelessPartitionIdentity)=>({sourceSha:identity.sourceSha,treeSha:identity.treeSha,sourceLockSha256:identity.sourceLockSha256,nodeVersion:identity.nodeVersion,runId:identity.runId,runAttempt:identity.runAttempt,scope:'source-contracts' as const,partitionSha256:identity.partitionManifestSha256});
export function combineStatelessPartitions(values:unknown,expected:StatelessPartitionIdentity,coverage:CiPartitionCoverage,checks:unknown){
 const parsed=z.array(partitionReceiptSchema).length(3).parse(JSON.parse(canonicalReleaseExecutionJson(values))).map(validateParsedPartitionOutcome),selected=ciPartitionFileSelections(coverage,parsed.map(row=>({scope:'source' as const,id:row.partition,profile:'full' as const}))),receipts=parsed.map((row,index)=>validateSelectedStatelessPartition(row,expected,coverage,selected[index]));if(new Set(receipts.map(row=>row.partition)).size!==3||receipts.some(row=>row.status!=='PASSED'))throw failure();
 const files=receipts.flatMap(row=>row.files).sort((a,b)=>a.path.localeCompare(b.path)),all=statelessVerificationSteps.flatMap(step=>[...step.args].filter(path=>path.endsWith('.test.ts'))).sort();if(!same(files.map(row=>row.path),all)||new Set(files.map(row=>row.path)).size!==files.length)throw failure();
 const checkRows=z.array(z.object({name:z.string(),commandSha256:digest,exitCode:z.literal(0),durationMs:z.number().int().nonnegative()}).strict()).max(30).parse(JSON.parse(canonicalReleaseExecutionJson(checks))),expectedChecks=statelessVerificationSteps.filter(step=>!(step.args as readonly string[]).includes('--test'));
 if(!same(checkRows.map(row=>({name:row.name,commandSha256:row.commandSha256})),expectedChecks.map(step=>({name:step.name,commandSha256:hash(JSON.stringify([...step.args]))}))))throw failure();
 if(!same(checkRows.map(row=>({name:row.name,commandSha256:row.commandSha256})),coverage.nonTestChecks))throw failure();
 const summary={version:1,purpose:'CUEVO_PARTITIONED_SOURCE_CONTRACTS',status:'PASSED',identity:{...expected,job:'source-contracts'},partitions:receipts.map(row=>({partition:row.partition,job:row.identity.job,payloadSha256:row.payloadSha256,receiptSha256:hash(canonicalReleaseExecutionJson(row))})).sort((a,b)=>a.partition.localeCompare(b.partition)),files,checks:checkRows};if(Buffer.byteLength(canonicalReleaseExecutionJson(summary))>1024*1024)throw failure();return summary;
}
export function validateStatelessSourceSummary(value:unknown,expected:{repository:string;sourceSha:string;treeSha:string;runId:string;runAttempt:number},coverage:CiPartitionCoverage,receipts:unknown){
 const summary=sourceSummarySchema.parse(JSON.parse(canonicalReleaseExecutionJson(value)));
 for(const key of ['repository','sourceSha','treeSha','runId','runAttempt']as const)if(summary.identity[key]!==expected[key])throw failure();if(summary.identity.job!=='source-contracts'||summary.identity.partitionManifestSha256!==coverage.manifestSha256)throw failure();
 const rebuilt=combineStatelessPartitions(receipts,summary.identity,coverage,summary.checks);if(canonicalReleaseExecutionJson(rebuilt)!==canonicalReleaseExecutionJson(summary))throw failure();return summary;
}
const hash=(bytes:Uint8Array|string)=>createHash('sha256').update(bytes).digest('hex'),same=(left:unknown,right:unknown)=>JSON.stringify(left)===JSON.stringify(right);
const sourceEnv=()=>Object.fromEntries(['PATH','Path','SystemRoot','SYSTEMROOT','WINDIR','TEMP','TMP','LANG','LC_ALL'].filter(key=>process.env[key]!==undefined).map(key=>[key,process.env[key]!]).concat([['GIT_NO_REPLACE_OBJECTS','1'],['GIT_CONFIG_NOSYSTEM','1'],['GIT_CONFIG_GLOBAL',process.platform==='win32'?'NUL':'/dev/null']]));
function git(root:string,args:string[]){return execFileSync('git',['-C',root,...args],{env:sourceEnv(),encoding:'utf8',stdio:['ignore','pipe','ignore'],shell:false,windowsHide:true,timeout:15000,maxBuffer:16*1024*1024}).trim();}
export async function requireStatelessPhysical(root:string,path:string,kind:'file'|'directory'){
 const part=relative(root,path);if(!isAbsolute(root)||resolve(root)!==root||!isAbsolute(path)||resolve(path)!==path||isAbsolute(part)||part.split(/[\\/]/).some(piece=>piece==='.'||piece==='..'))throw failure();const pieces=part.split(/[\\/]/).filter(Boolean);let current=root;
 for(const[index,piece]of [...pieces,''].entries()){const stat=await lstat(current);if(stat.isSymbolicLink()||await realpath(current)!==current||(index<pieces.length?!stat.isDirectory():kind==='directory'?!stat.isDirectory():!stat.isFile()||stat.nlink!==1))throw failure();if(piece)current=join(current,piece);}
}
const physical=requireStatelessPhysical;
/** Short create-only scratch keeps Windows fixture Git paths below their limit.
 * The caller's configured temp root and each operation remain independently owned. */
async function createStatelessScratch(){
 const parent=resolve(tmpdir());if(!isAbsolute(parent)||await realpath(parent)!==parent)throw failure();await physical(parent,parent,'directory');
 const root=await mkdtemp(join(parent,'cv-'));try{await physical(parent,root,'directory');await chmod(root,0o700);await physical(parent,root,'directory');return{parent,root};}catch{try{await physical(parent,root,'directory');await rm(root,{recursive:true,force:true});}catch{/* Unsafe or unconfirmed scratch is retained for review. */}throw failure();}
}
async function source(root:string){
 await physical(root,root,'directory');const sourceSha=sha.parse(git(root,['rev-parse','HEAD'])),treeSha=sha.parse(git(root,['rev-parse','HEAD^{tree}']));if(git(root,['status','--porcelain','--untracked-files=all']))throw failure();const lock=await readFile(join(root,'package-lock.json'));return{sourceSha,treeSha,sourceLockSha256:hash(lock)};
}
export async function readStatelessPartitionIdentity(root:string,job:string,env:NodeJS.ProcessEnv=process.env):Promise<StatelessPartitionIdentity>{
 if(env.CI!=='true'||env.GITHUB_ACTIONS!=='true'||!['push','pull_request','workflow_dispatch'].includes(env.GITHUB_EVENT_NAME??'')||env.GITHUB_JOB!==job)throw failure();
 const initial=await source(root),coverage=readCiPartitionCoverage(root);if(initial.sourceSha!==env.GITHUB_SHA)throw failure();
 const paths=git(root,['ls-files','--cached','--others','--exclude-standard','-z']).split('\0').filter(Boolean),files: {path:string;sha256:string}[]=[];for(const path of [...new Set(paths)].sort()){const owned=join(root,path);await physical(root,owned,'file');const before=await lstat(owned),bytes=await readFile(owned),after=await lstat(owned);if(before.dev!==after.dev||before.ino!==after.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs||before.ctimeMs!==after.ctimeMs)throw failure();files.push({path,sha256:hash(bytes)});}if(!same(initial,await source(root)))throw failure();
 const nodeBinarySha256=hash(await readFile(process.execPath)),sourceDigest=hash(JSON.stringify(files)),toolchainSha256=hash(canonicalReleaseExecutionJson({nodeVersion:process.version,nodeBinarySha256,sourceLockSha256:initial.sourceLockSha256,platform:process.platform,arch:process.arch})),environmentPolicySha256=hash(canonicalReleaseExecutionJson({CI:'true',NEXT_TELEMETRY_DISABLED:'1',SCARF_ANALYTICS:'false',CUEVO_REQUIRE_LIVE_INTELLIGENCE:'0',fileConcurrency:'NODE_DEFAULT_PROCESS_ISOLATION',partitionManifestSha256:coverage.manifestSha256}));
 return partitionIdentitySchema.parse({repository:env.GITHUB_REPOSITORY,...initial,sourceDigest,partitionManifestSha256:coverage.manifestSha256,nodeVersion:process.version,nodeBinarySha256,toolchainSha256,environmentPolicySha256,runId:env.GITHUB_RUN_ID,runAttempt:Number(env.GITHUB_RUN_ATTEMPT),job});
}
export async function runStatelessAggregateChecks(root:string,signal?:AbortSignal){
 const rows:{name:string;commandSha256:string;exitCode:0;durationMs:number}[]=[];
 for(const step of statelessVerificationSteps.filter(step=>!(step.args as readonly string[]).includes('--test'))){if(signal?.aborted)throw failure();const started=performance.now(),env={...process.env,CI:'true',NEXT_TELEMETRY_DISABLED:'1',SCARF_ANALYTICS:'false',CUEVO_REQUIRE_LIVE_INTELLIGENCE:'0'};delete(env as NodeJS.ProcessEnv).NODE_OPTIONS;const child=spawnOwnedProcess(process.execPath,[...step.args],{cwd:root,shell:false,windowsHide:true,stdio:['ignore','pipe','pipe'],env});child.stdout?.on('data',()=>undefined);child.stderr?.on('data',()=>undefined);const stop=()=>{void stopOwnedProcesses([child]).catch(()=>undefined);};signal?.addEventListener('abort',stop,{once:true});const code=await new Promise<number|null>(done=>{child.once('error',()=>done(null));child.once('close',done);});signal?.removeEventListener('abort',stop);await stopOwnedProcesses([child]);if(code!==0||signal?.aborted)throw failure();rows.push({name:step.name,commandSha256:hash(JSON.stringify([...step.args])),exitCode:0,durationMs:Math.floor(performance.now()-started)});}
 return rows;
}
async function persistPartition(root:string,result:StatelessPartitionReceipt){const folder=join(root,'.local/verification/source-partitions',result.partition);await mkdir(folder,{recursive:true,mode:0o700});await physical(root,folder,'directory');const bytes=canonicalReleaseExecutionJson(result);if(Buffer.byteLength(bytes)>1024*1024)throw failure();const temporary=join(folder,'result.'+randomUUID()+'.tmp');await writeFile(temporary,bytes,{flag:'wx',mode:0o600});await rename(temporary,join(folder,'result.json'));}
async function runSourceTestCohortProcesses(input:{root:string;plan:SourceTestCohortPlan;identity:StatelessPartitionIdentity;signal?:AbortSignal}){
 const identity=sourceCohortIdentity(input.identity);
 const run=async(id:string)=>{
  let operation:Awaited<ReturnType<typeof createStatelessScratch>>|undefined,child:ChildProcess|undefined,cleanupConfirmed=false,stdout=Buffer.alloc(0),oversized=false;
  const commandArgs=sourceTestCohortCommand({repoRoot:input.root,plan:input.plan,cohortId:id});
  try{
   if(input.signal?.aborted)throw failure();operation=await createStatelessScratch();if(input.signal?.aborted)throw failure();const scratch=operation.root,reporterInput={repoRoot:input.root,files:[input.plan.file],identity},env={...process.env,TEMP:scratch,TMP:scratch,TMPDIR:scratch,CI:'true',NEXT_TELEMETRY_DISABLED:'1',SCARF_ANALYTICS:'false',CUEVO_REQUIRE_LIVE_INTELLIGENCE:'0',CUEVO_CI_TEST_TIMING_INPUT:JSON.stringify(reporterInput)};delete(env as NodeJS.ProcessEnv).NODE_OPTIONS;delete(env as NodeJS.ProcessEnv).NODE_TEST_CONTEXT;
   child=spawnOwnedProcess(process.execPath,commandArgs,{cwd:input.root,shell:false,windowsHide:true,stdio:['ignore','pipe','pipe'],env});const selectedChild=child;
   const stop=()=>{void stopOwnedProcesses([selectedChild]).catch(()=>undefined);};input.signal?.addEventListener('abort',stop,{once:true});
   let terminal:{code:number|null;signal:NodeJS.Signals|null};try{terminal=await new Promise(done=>{selectedChild.stdout?.on('data',(part:Buffer)=>{if(stdout.length+part.length>4*1024*1024){oversized=true;stop();}else stdout=Buffer.concat([stdout,part]);});selectedChild.stderr?.on('data',()=>undefined);selectedChild.once('error',()=>undefined);selectedChild.once('close',(code,signal)=>done({code,signal}));if(input.signal?.aborted)stop();});}finally{input.signal?.removeEventListener('abort',stop);}
   await stopOwnedProcesses([selectedChild]);cleanupConfirmed=true;if(input.signal?.aborted||oversized)return{receipt:undefined,cases:[],code:terminal.code,signal:terminal.signal,cleanupConfirmed};
   const report=JSON.parse(stdout.toString('utf8').trim());const matching=report?.purpose==='CUEVO_CI_TEST_TIMINGS'&&same(report.identity,identity)&&report.files?.length===1&&report.files[0].path===input.plan.file.path&&report.files[0].sha256===input.plan.file.sha256;const cases=matching&&Array.isArray(report.files[0].cases)?report.files[0].cases.map((value:unknown)=>{const row=reportCaseSchema.parse(value);return partitionCaseSchema.parse({definitionSha256:hash(canonicalReleaseExecutionJson({titleSha256:row.titleSha256,suiteSha256:row.suiteSha256,line:row.line,column:row.column,nesting:row.nesting})),outcome:row.outcome});}):[];
   let receipt:SourceTestCohortReceipt|undefined;try{receipt=recordSourceTestCohort({repoRoot:input.root,plan:input.plan,cohortId:id,identity,report,commandArgs,exitCode:terminal.code,signal:terminal.signal,cleanupConfirmed});}catch{/* Failed original outcomes remain diagnostics, never an accepted cohort. */}
   return{receipt,cases,code:terminal.code,signal:terminal.signal,cleanupConfirmed};
  }finally{
   if(child&&!cleanupConfirmed){await stopOwnedProcesses([child]);cleanupConfirmed=true;}if(operation&&(!child||cleanupConfirmed)){await physical(operation.parent,operation.root,'directory');await rm(operation.root,{recursive:true,force:true});}
  }
 };
 const settled=await Promise.allSettled(input.plan.cohorts.map(cohort=>run(cohort.id)));const values=settled.flatMap(row=>row.status==='fulfilled'?[row.value]:[]),receipts=values.flatMap(row=>row.receipt?[row.receipt]:[]);
 if(receipts.length===input.plan.cohorts.length&&settled.every(row=>row.status==='fulfilled'))return{file:aggregateSourceTestCohorts(input.plan,receipts,identity),passed:true,cleanupConfirmed:true,cases:values.flatMap(row=>row.cases)};
 return{file:null,passed:false,cleanupConfirmed:settled.every(row=>row.status==='fulfilled'&&row.value.cleanupConfirmed),cases:values.flatMap(row=>row.cases)};
}
export async function runStatelessPartition(input:{repoRoot:string;partition:string;signal?:AbortSignal}):Promise<StatelessPartitionReceipt>{
 const partition=z.enum(partitionIds).parse(input.partition),root=input.repoRoot,coverage=readCiPartitionCoverage(root),identity=await readStatelessPartitionIdentity(root,expectedJob(partition)),files=ciPartitionFiles(coverage,'source',partition,'full');
 const rows:StatelessPartitionReceipt['files']=[];for(const path of files){await physical(root,join(root,path),'file');const group=statelessVerificationSteps.find(step=>(step.args as readonly string[]).includes(path));if(!group)throw failure();rows.push({path,sha256:hash(await readFile(join(root,path))),group:group.name,durationMs:null,cases:[]});}
 let body:Omit<StatelessPartitionReceipt,'payloadSha256'>={version:1,purpose:'CUEVO_STATELESS_SOURCE_PARTITION',partition,status:'NOT_VERIFIED',identity,files:rows,startedAtMs:Date.now(),completedAtMs:null,exitCode:null,signal:null,frozenBefore:true,frozenAfter:false,cleanupConfirmed:false,reasons:[]};await persistPartition(root,payload(body));
 let operation:Awaited<ReturnType<typeof createStatelessScratch>>|undefined;
 let cohortPlan:SourceTestCohortPlan|undefined;
 try{cohortPlan=coverage.sourceCohorts&&partition==='source-contracts'?readSourceTestCohortPlan(root):undefined;operation=await createStatelessScratch();await physical(operation.parent,operation.root,'directory');}catch{body={...body,status:'FAILED',completedAtMs:Date.now(),cleanupConfirmed:operation===undefined,reasons:['INPUT_REQUIRES_REVIEW']};if(operation){try{await physical(operation.parent,operation.root,'directory');await rm(operation.root,{recursive:true,force:true});body.cleanupConfirmed=true;}catch{body.reasons.push('STOP_UNCONFIRMED');}}const result=payload(body);await persistPartition(root,result);return result;}
 const scratch=operation.root,ordinaryFiles=cohortPlan?files.filter(path=>path!==SOURCE_TEST_COHORT_FILE):files,ordinaryRows=rows.filter(row=>ordinaryFiles.includes(row.path));
 const cohortController=new AbortController(),cohortSignal=input.signal?AbortSignal.any([input.signal,cohortController.signal]):cohortController.signal,cohortRun=cohortPlan?runSourceTestCohortProcesses({root,plan:cohortPlan,identity,signal:cohortSignal}):undefined;
 const reporter=join(import.meta.dirname,'ci-test-timings-reporter.ts'),reporterInput={repoRoot:root,files:ordinaryRows.map(row=>({path:row.path,sha256:row.sha256})),identity:{sourceSha:identity.sourceSha,treeSha:identity.treeSha,sourceLockSha256:identity.sourceLockSha256,nodeVersion:identity.nodeVersion,runId:identity.runId,runAttempt:identity.runAttempt,scope:partition,partitionSha256:coverage.manifestSha256}};
 const env={...process.env,TEMP:scratch,TMP:scratch,TMPDIR:scratch,CI:'true',NEXT_TELEMETRY_DISABLED:'1',SCARF_ANALYTICS:'false',CUEVO_REQUIRE_LIVE_INTELLIGENCE:'0',CUEVO_CI_TEST_TIMING_INPUT:JSON.stringify(reporterInput)};delete(env as NodeJS.ProcessEnv).NODE_TEST_CONTEXT;delete(env as NodeJS.ProcessEnv).NODE_OPTIONS;
 let child:ChildProcess|undefined,stdout=Buffer.alloc(0),cancelled=false,processFailed=false,cleanupConfirmed=false,oversized=false;
 try{
  if(input.signal?.aborted)throw failure();child=spawnOwnedProcess(process.execPath,['--import',pathToFileURL(join(import.meta.dirname,'../../node_modules/tsx/dist/loader.mjs')).href,'--test','--test-reporter',pathToFileURL(reporter).href,...ordinaryFiles],{cwd:root,shell:false,windowsHide:true,stdio:['ignore','pipe','pipe'],env});
  const onAbort=()=>{cancelled=true;void stopOwnedProcesses([child!]).catch(()=>{cleanupConfirmed=false;});};input.signal?.addEventListener('abort',onAbort,{once:true});
  const terminal=await new Promise<{code:number|null;signal:NodeJS.Signals|null}>(done=>{child!.stdout?.on('data',(part:Buffer)=>{if(stdout.length+part.length>4*1024*1024){oversized=true;void stopOwnedProcesses([child!]).catch(()=>undefined);}else stdout=Buffer.concat([stdout,part]);});child!.stderr?.on('data',()=>undefined);child!.once('error',()=>{processFailed=true;});child!.once('close',(code,signal)=>done({code,signal}));if(input.signal?.aborted)onAbort();});input.signal?.removeEventListener('abort',onAbort);
  body.exitCode=terminal.code;body.signal=terminal.signal?(['SIGTERM','SIGKILL','SIGINT'].includes(terminal.signal)?terminal.signal as 'SIGTERM'|'SIGKILL'|'SIGINT':'OTHER'):null;if(terminal.code!==0&&!cancelled)body.reasons.push('PROCESS_FAILED');
  await stopOwnedProcesses([child]);cleanupConfirmed=true;
  if(!oversized){const report=JSON.parse(stdout.toString('utf8').trim());if(report?.purpose!=='CUEVO_CI_TEST_TIMINGS'||!['PASSED','FAILED'].includes(report.status)||!same(report.identity,reporterInput.identity)||!Array.isArray(report.files)||!same(report.files.map((row:{path:string})=>row.path),ordinaryFiles))throw failure();
   for(const [index,file]of report.files.entries()){const target=ordinaryRows[index];if(file.sha256!==target.sha256||!Array.isArray(file.cases)||file.durationMs!==null&&(!Number.isFinite(file.durationMs)||file.durationMs<0||file.durationMs>86400000))throw failure();target.durationMs=file.durationMs;target.cases=file.cases.map((value:unknown)=>{const row=reportCaseSchema.parse(value);return partitionCaseSchema.parse({definitionSha256:hash(canonicalReleaseExecutionJson({titleSha256:row.titleSha256,suiteSha256:row.suiteSha256,line:row.line,column:row.column,nesting:row.nesting})),outcome:row.outcome});});}
   if(report.status!=='PASSED'||report.fileBytesConfirmed!==true||!report.summary?.success||report.reasons?.length||ordinaryRows.some(row=>row.durationMs===null||!row.cases.length||row.cases.some(test=>test.outcome!=='PASSED')))throw failure();
  }else throw failure();
 }catch{body.reasons.push(processFailed?'PROCESS_FAILED':'COVERAGE_UNCONFIRMED');}
 finally{if(child&&!cleanupConfirmed)try{await stopOwnedProcesses([child]);cleanupConfirmed=true;}catch{body.reasons.push('STOP_UNCONFIRMED');}if(cohortRun){try{const cohorts=await cohortRun,target=rows.find(row=>row.path===SOURCE_TEST_COHORT_FILE);if(!target){body.reasons.push('COVERAGE_UNCONFIRMED');cleanupConfirmed=false;}else{if(cohorts.file)Object.assign(target,cohorts.file);else target.cases=cohorts.cases;if(!cohorts.passed)body.reasons.push('COVERAGE_UNCONFIRMED');if(!cohorts.cleanupConfirmed){cleanupConfirmed=false;body.reasons.push('STOP_UNCONFIRMED');}}}catch{body.reasons.push('COVERAGE_UNCONFIRMED');cleanupConfirmed=false;}}cohortController.abort();}
 if(cleanupConfirmed){try{await physical(operation.parent,operation.root,'directory');await rm(operation.root,{recursive:true,force:true});}catch{cleanupConfirmed=false;body.reasons.push('STOP_UNCONFIRMED');}}
 try{body.frozenAfter=same(identity,await readStatelessPartitionIdentity(root,identity.job));}catch{body.frozenAfter=false;}if(!body.frozenAfter)body.reasons.push('SOURCE_CHANGED');if(cancelled||input.signal?.aborted)body.reasons.push('CANCELLED');
 body={...body,completedAtMs:Date.now(),cleanupConfirmed,reasons:[...new Set(body.reasons)],status:cancelled||input.signal?.aborted?'CANCELLED':body.exitCode===0&&body.signal===null&&body.frozenAfter&&cleanupConfirmed&&!body.reasons.length?'PASSED':'FAILED'};const result=payload(body);await persistPartition(root,result);return result;
}
async function persist(root:string,evidence:StatelessChecksEvidence,failed:boolean){
 const directory=join(root,'.local','verification','source-contracts');await mkdir(directory,{recursive:true,mode:0o700});await physical(root,directory,'directory');const bytes=JSON.stringify(statelessChecksEvidenceSchema.parse(evidence))+'\n';if(Buffer.byteLength(bytes)>256*1024)throw failure();
 for(const name of failed?['result.json','failure.json']:['result.json']){const temporary=join(directory,name+'.'+randomUUID()+'.tmp');await writeFile(temporary,bytes,{flag:'wx',mode:0o600});await rename(temporary,join(directory,name));}
}

/** Execute the unchanged source-owned groups once. Only the explicitly reviewed
 * CICD/replay fixture pair overlaps; artifact builders and all other groups keep
 * their serial order. Failures do not turn required undiscovered groups into a
 * pass. Raw child output is drained privately and never copied into evidence. */
export async function runStatelessChecks(input:{repoRoot:string;signal?:AbortSignal}):Promise<StatelessChecksEvidence>{
 const root=input.repoRoot;if(!isAbsolute(root)||resolve(root)!==root||input.signal!==undefined&&!(input.signal instanceof AbortSignal))throw failure();const signal=input.signal;
 const rows:StatelessChecksEvidence['groups']=statelessVerificationSteps.map(step=>({name:step.name,commandSha256:hash(JSON.stringify([...step.args])),files:[],status:'NOT_STARTED',exitCode:null,signal:null,durationMs:0,startedAtMs:null,completedAtMs:null,scratchId:randomUUID(),failedFiles:[],failedTests:[],summary:null,fileOnlyCases:0,stdoutBytes:0,stderrBytes:0}));
 const sourceIdentity:StatelessChecksEvidence['source']={sourceSha:null,treeSha:null,sourceLockSha256:null,toolchainSha256:hash(JSON.stringify({node:process.version,platform:process.platform,arch:process.arch,groups:rows.map(row=>({name:row.name,commandSha256:row.commandSha256}))})),nodeVersion:process.version,nodeBinarySha256:null,runId:null,runAttempt:null,frozenBefore:false,frozenAfter:false};
 const evidence:StatelessChecksEvidence={version:1,purpose:'CUEVO_STATELESS_SOURCE_CONTRACTS',status:'INPUT_REQUIRES_REVIEW',source:sourceIdentity,discoverySha256:hash(JSON.stringify(rows.map(row=>({name:row.name,commandSha256:row.commandSha256,files:row.files})))),groups:rows,failedGroup:null,recordedAt:new Date().toISOString()};
 let initial:Awaited<ReturnType<typeof source>>|undefined;
 try{
  if(process.env.GITHUB_ACTIONS==='true'){const runId=identifier.parse(process.env.GITHUB_RUN_ID),runAttempt=z.coerce.number().int().positive().max(Number.MAX_SAFE_INTEGER).parse(process.env.GITHUB_RUN_ATTEMPT);Object.assign(sourceIdentity,{runId,runAttempt});}
  initial=await source(root);Object.assign(sourceIdentity,initial,{frozenBefore:true});if(process.env.GITHUB_ACTIONS==='true'&&process.env.GITHUB_SHA!==initial.sourceSha)throw failure();sourceIdentity.nodeBinarySha256=hash(await readFile(process.execPath));sourceIdentity.toolchainSha256=hash(JSON.stringify({nodeVersion:process.version,nodeBinarySha256:sourceIdentity.nodeBinarySha256,platform:process.platform,arch:process.arch,packageManager:JSON.parse(git(root,['show',initial.sourceSha+':package.json'])).packageManager,sourceLockSha256:initial.sourceLockSha256}));
  if(new Set(rows.map(row=>row.name)).size!==rows.length||new Set(statelessVerificationSteps.flatMap(step=>[...step.args]).filter(arg=>arg.endsWith('.test.ts'))).size!==statelessVerificationSteps.flatMap(step=>[...step.args]).filter(arg=>arg.endsWith('.test.ts')).length)throw failure();
  for(const[index,step]of statelessVerificationSteps.entries()){const paths=[...step.args].filter(arg=>arg.startsWith('scripts/')&&arg.endsWith('.ts'));if(!paths.length)throw failure();for(const path of paths){safePath.parse(path);await physical(root,join(root,path),'file');rows[index].files.push({path,sha256:hash(await readFile(join(root,path)))});}}
  evidence.discoverySha256=hash(JSON.stringify(rows.map(row=>({name:row.name,commandSha256:row.commandSha256,files:row.files}))));
 }catch{evidence.discoverySha256=hash(JSON.stringify(rows.map(row=>({name:row.name,commandSha256:row.commandSha256,files:row.files}))));await persist(root,evidence,true);return statelessChecksEvidenceSchema.parse(evidence);}
 const directory=join(root,'.local','verification','source-contracts'),operation=await createStatelessScratch(),attempt=operation.root;try{await physical(root,join(directory,'failure.json'),'file');await rm(join(directory,'failure.json'));}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw failure();}
 const run=async(index:number)=>{
  const step=statelessVerificationSteps[index],row=rows[index];if(signal?.aborted)return;const started=performance.now();row.startedAtMs=Date.now();const scratch=join(attempt,row.scratchId);try{await physical(operation.parent,attempt,'directory');await mkdir(scratch,{mode:0o700});await physical(operation.parent,scratch,'directory');}catch{row.status='PROCESS_ERROR';row.completedAtMs=Date.now();row.durationMs=Math.max(0,Math.floor(performance.now()-started));return;}if(signal?.aborted){row.status='CANCELLED';row.completedAtMs=Date.now();return;}console.log('START source-contracts '+row.name);
  const environment:NodeJS.ProcessEnv={...process.env,TEMP:scratch,TMP:scratch,TMPDIR:scratch};delete environment.NODE_TEST_CONTEXT;
  let child:ChildProcess;try{child=spawnOwnedProcess(process.execPath,[...step.args],{cwd:root,shell:false,windowsHide:true,stdio:['ignore','pipe','pipe'],env:environment});}catch{row.status='PROCESS_ERROR';row.completedAtMs=Date.now();return;}
  await new Promise<void>(done=>{let settled=false,stopping=false,cancelled=false,error=false,summaryInvalid=false;const pending={stdout:Buffer.alloc(0),stderr:Buffer.alloc(0)},summary:Partial<z.infer<typeof testSummary>>={},labels=new Set<string>();let lastLocation:string|undefined,lastTitle:string|undefined;const failedTests=new Map<string,{path:string;titleSha256:string}>();
   const finish=(code:number|null,termination:NodeJS.Signals|null)=>{if(settled||stopping)return;settled=true;signal?.removeEventListener('abort',onAbort);const parsed=testSummary.safeParse(summary);if(parsed.success&&!summaryInvalid)row.summary=parsed.data;const coverage=(step.args as readonly string[]).includes('--test')&&(row.fileOnlyCases!==0||!row.summary||row.summary.tests<1||row.summary.pass!==row.summary.tests||row.summary.fail!==0||row.summary.cancelled!==0||row.summary.skipped!==0||row.summary.todo!==0);row.status=cancelled?'CANCELLED':error?'PROCESS_ERROR':code===0&&termination===null?(coverage?'COVERAGE_UNCONFIRMED':'PASSED'):code===null?'PROCESS_ERROR':'FAILED';row.exitCode=code!==null&&code>=0&&code<=255?code:null;row.signal=termination?(['SIGTERM','SIGKILL','SIGINT'].includes(termination)?termination as 'SIGTERM'|'SIGKILL'|'SIGINT':'OTHER'):null;row.durationMs=Math.min(86400000,Math.max(0,Math.floor(performance.now()-started)));row.completedAtMs=Date.now();row.failedFiles=[...labels].sort();row.failedTests=[...failedTests.values()].sort((left,right)=>left.path.localeCompare(right.path)||left.titleSha256.localeCompare(right.titleSha256));done();};
   const stop=()=>{if(stopping||settled)return;stopping=true;void stopOwnedProcesses([child]).then(()=>{stopping=false;finish(child.exitCode,child.signalCode);},()=>{stopping=false;error=true;row.status='STOP_UNCONFIRMED';settled=true;signal?.removeEventListener('abort',onAbort);row.durationMs=Math.min(86400000,Math.max(0,Math.floor(performance.now()-started)));row.completedAtMs=Date.now();done();});};
   const onAbort=()=>{cancelled=true;stop();};signal?.addEventListener('abort',onAbort,{once:true});
   const collect=(chunk:Buffer,kind:'stdout'|'stderr')=>{row[kind==='stdout'?'stdoutBytes':'stderrBytes']=Math.min(2147483647,row[kind==='stdout'?'stdoutBytes':'stderrBytes']+chunk.length);pending[kind]=Buffer.concat([pending[kind],chunk]);if(pending[kind].length>65536)pending[kind]=pending[kind].subarray(pending[kind].length-65536);const lines=pending[kind].toString('utf8').split(/\r?\n/);pending[kind]=Buffer.from(lines.pop()??'');for(const raw of lines){const line=stripVTControlCharacters(raw).trim(),metric=/^(?:#|ℹ) (tests|pass|fail|cancelled|skipped|todo) ([0-9]+)$/.exec(line);if(metric){const key=metric[1]as keyof typeof summary;if(summary[key]!==undefined)summaryInvalid=true;else summary[key]=Number(metric[2]);}const passed=/^(?:ok [0-9]+ - |✔ )(.+?)(?: \([0-9.]+ms\))?$/.exec(line);if(passed)for(const file of row.files)if(passed[1].replaceAll('\\','/')===file.path||passed[1].replaceAll('\\','/')===join(root,file.path).replaceAll('\\','/'))row.fileOnlyCases++;if(/^(?:# )?(?:test at|location:)/.test(line))for(const file of row.files)if(file.path.endsWith('.test.ts')&&line.replaceAll('\\','/').includes(file.path)){labels.add(file.path);lastLocation=file.path;}const failed=/^(?:not ok [0-9]+ - |✖ )(.+?)(?: \([0-9.]+ms\))?$/.exec(line);if(line==='✖ failing tests:'){lastLocation=undefined;lastTitle=undefined;}else if(failed)lastTitle=hash(failed[1]);if(lastLocation&&lastTitle){failedTests.set(lastLocation+':'+lastTitle,{path:lastLocation,titleSha256:lastTitle});lastLocation=undefined;lastTitle=undefined;}}};
   child.stdout?.on('data',(chunk:Buffer)=>collect(chunk,'stdout'));child.stderr?.on('data',(chunk:Buffer)=>collect(chunk,'stderr'));child.once('error',()=>{error=true;stop();});child.once('close',finish);if(signal?.aborted)onAbort();
  });console.log('END source-contracts '+row.name+' '+row.status+' '+row.durationMs+'ms');
 };
 const completed=new Set<number>();for(let index=0;index<rows.length;index++){
  if(completed.has(index)||signal?.aborted)continue;if(rows[index].name==='cicd-fixtures'){const other=rows.findIndex(row=>row.name==='migration-replay-rules');if(other>=0){completed.add(index);completed.add(other);const outcomes=await Promise.allSettled([run(index),run(other)]);for(const[position,outcome]of outcomes.entries())if(outcome.status==='rejected'){const row=rows[position?other:index];row.status='PROCESS_ERROR';row.startedAtMs??=Date.now();row.completedAtMs=Date.now();}continue;}}completed.add(index);await run(index);
 }
 evidence.failedGroup=rows.find(row=>!['PASSED','NOT_STARTED'].includes(row.status))?.name??null;
 try{const final=await source(root);sourceIdentity.frozenAfter=same(initial,final);}catch{sourceIdentity.frozenAfter=false;}
 evidence.status=rows.some(row=>row.status==='STOP_UNCONFIRMED')?'STOP_UNCONFIRMED':signal?.aborted?'CANCELLED':!sourceIdentity.frozenAfter?'SOURCE_CHANGED':rows.every(row=>row.status==='PASSED')?'PASSED':'FAILED';evidence.recordedAt=new Date().toISOString();await persist(root,evidence,evidence.status!=='PASSED');return statelessChecksEvidenceSchema.parse(evidence);
}

if(process.argv[1]&&pathToFileURL(resolve(process.argv[1])).href===import.meta.url){const controller=new AbortController();process.once('SIGTERM',()=>controller.abort());process.once('SIGINT',()=>controller.abort());try{const args=process.argv.slice(2),partition=args.length===1&&args[0].startsWith('--partition=')?args[0].slice(12):undefined;if(args.length&&!partition)throw failure();const result=partition?await runStatelessPartition({repoRoot:resolve('.'),partition,signal:controller.signal}):await runStatelessChecks({repoRoot:resolve('.'),signal:controller.signal});console.log('Stateless source contracts '+result.status);process.exitCode=result.status==='PASSED'?0:1;}catch{console.error('Stateless source contracts require review; private output withheld.');process.exitCode=1;}}
