import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink,lstat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,relative} from 'node:path';
import {execFileSync,spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {statelessVerificationSteps} from './steps';
import ts from 'typescript';
import {pathToFileURL} from 'node:url';
const runningCancellationFixtureSource=String.raw`import{readFileSync,writeFileSync,existsSync}from'node:fs';const input=JSON.parse(readFileSync(new URL('./running-cancel-input.json',import.meta.url),'utf8'));const{runStatelessPartition}=await import(input.subject);const controller=new AbortController(),timer=setInterval(()=>{if(existsSync('.local/hold-started'))controller.abort();},20);try{const value=await runStatelessPartition({repoRoot:input.repoRoot,partition:'source-native',signal:controller.signal});writeFileSync(input.output,JSON.stringify(value));}finally{clearInterval(timer);}`;

test('allocated scratch cleanup refusal cannot be reported as confirmed partition cleanup',async()=>{
 const root=await mkdtemp(join(tmpdir(),'cuevo-scratch-outcome-')),scratchParent=join(root,'scratch');
 try{
  await mkdir(join(root,'scripts/verification'),{recursive:true});await mkdir(join(root,'.local'),{recursive:true});await mkdir(scratchParent);
  const file='scripts/verification/owned.test.ts';await writeFile(join(root,file),"import{test}from'node:test';test('must not start',()=>{});\n");await writeFile(join(root,'.gitignore'),'.local/\nscratch/\n');await writeFile(join(root,'.gitattributes'),'* text eol=lf\n');await writeFile(join(root,'package-lock.json'),'{}\n');await writeFile(join(root,'package.json'),'{}\n');
  const git=(args:string[])=>execFileSync('git',['-C',root,...args],{encoding:'utf8',windowsHide:true}).trim();git(['init','--quiet']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','source']);const sha=git(['rev-parse','HEAD']),steps=[{name:'cicd-fixtures',args:['--import','tsx','--test',file]}],coverage={manifestSha256:'c'.repeat(64),source:[{id:'source-native',files:[file]}],sourceCohorts:undefined};
  const hook=join(root,'.local/scratch-hook.mjs'),subject=pathToFileURL(resolve('scripts/verification/stateless-checks.ts')).href;
  await writeFile(hook,`import fs from'node:fs/promises';import{syncBuiltinESMExports,registerHooks}from'node:module';import{resolve,relative}from'node:path';const original={mkdtemp:fs.mkdtemp,chmod:fs.chmod,rm:fs.rm};let allocated=null,removals=0;globalThis.scratchOutcome=()=>({allocated,removals});fs.mkdtemp=async(...args)=>{if(process.env.CUEVO_SCRATCH_MODE==='allocate-refuse')throw Error('private-scratch-canary');const result=await original.mkdtemp(...args);allocated=result;return result;};fs.chmod=async(path,...args)=>{if(path===allocated)throw Error('private-scratch-canary');return original.chmod(path,...args);};fs.rm=async(path,...args)=>{if(path===allocated){removals++;if(process.env.CUEVO_SCRATCH_MODE==='remove-refuse')throw Error('private-scratch-canary');}return original.rm(path,...args);};syncBuiltinESMExports();registerHooks({load(url,context,next){if(url.endsWith('/steps.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('export const statelessVerificationSteps='+JSON.stringify(steps)+';')}};if(url.endsWith('/ci-partition-coverage.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('const coverage='+JSON.stringify(coverage)+';export const readCiPartitionCoverage=()=>coverage;export const ciPartitionFiles=()=>coverage.source[0].files;export const ciPartitionFileSelections=()=>[coverage.source[0].files];')}};return next(url,context);}});`);
  const runner=join(root,'.local/scratch-runner.mjs');await writeFile(runner,`import{runStatelessPartition,runStatelessChecks}from ${JSON.stringify(subject)};import{writeFileSync}from'node:fs';const result=process.env.CUEVO_SCRATCH_OWNER==='complete'?await runStatelessChecks({repoRoot:process.cwd()}):await runStatelessPartition({repoRoot:process.cwd(),partition:'source-native'});writeFileSync('.local/outcome.json',JSON.stringify({result,diagnostic:globalThis.scratchOutcome()}));`);
  for(const owner of ['partition','complete'])for(const mode of ['remove-refuse','remove-success','allocate-refuse']){
   const run=spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(hook).href,runner],{cwd:root,encoding:'utf8',env:{...process.env,TEMP:scratchParent,TMP:scratchParent,TMPDIR:scratchParent,CI:'true',GITHUB_ACTIONS:'true',GITHUB_EVENT_NAME:'pull_request',GITHUB_REPOSITORY:'owner/repo',GITHUB_SHA:sha,GITHUB_RUN_ID:'51',GITHUB_RUN_ATTEMPT:'2',GITHUB_JOB:'source-fixtures-native',CUEVO_SCRATCH_MODE:mode,CUEVO_SCRATCH_OWNER:owner}});
   assert.equal(run.status,0,run.stderr);const outcome=JSON.parse(await readFile(join(root,'.local/outcome.json'),'utf8'));
   if(owner==='partition'){assert.equal(outcome.result.status,'FAILED');assert.equal(outcome.result.exitCode,null);assert.equal(outcome.result.files[0].cases.length,0);assert.equal(outcome.result.cleanupConfirmed,mode==='remove-success','only actual guarded removal can confirm scratch cleanup');assert.equal(outcome.result.reasons.includes('STOP_UNCONFIRMED'),mode!=='remove-success');}
   else{assert.equal(outcome.result.status,mode==='remove-success'?'FAILED':'STOP_UNCONFIRMED');assert.equal(outcome.result.groups[0].status,mode==='remove-success'?'PROCESS_ERROR':'STOP_UNCONFIRMED');assert.equal(outcome.result.groups[0].exitCode,null);assert.equal(outcome.result.groups[0].summary,null);}
   assert.equal(JSON.stringify(outcome.result).includes('private-scratch-canary'),false);
   if(mode==='remove-refuse'){assert.equal(outcome.diagnostic.removals,1);const allocated=resolve(outcome.diagnostic.allocated);assert.equal(resolve(allocated,'..'),resolve(scratchParent));assert.match(relative(scratchParent,allocated),/^cv-[a-zA-Z0-9]+$/);assert.equal((await lstat(allocated)).isDirectory(),true);await rm(allocated,{recursive:true,force:true});}
   if(mode==='remove-success'){assert.equal(outcome.diagnostic.removals,1);await assert.rejects(lstat(outcome.diagnostic.allocated),{code:'ENOENT'});}
   if(mode==='allocate-refuse'){assert.equal(outcome.diagnostic.allocated,null);assert.equal(outcome.diagnostic.removals,0);}
  }
 }finally{await rm(root,{recursive:true,force:true});}
});

test('current closed cohort policy rejects passing file rows without original process coverage',async()=>{
 const api=await import('./stateless-checks'),cohorts=await import('./source-test-cohorts'),coverage=await import('./ci-partition-coverage'),review=await import('./release-review'),root=resolve(import.meta.dirname,'../..'),policy=coverage.readCiPartitionCoverage(root),plan=cohorts.readSourceTestCohortPlan(root);
 assert.deepEqual((policy as unknown as{sourceCohorts:unknown}).sourceCohorts,{version:1,file:cohorts.SOURCE_TEST_COHORT_FILE,policySha256:plan.policySha256});
 const identity={repository:'owner/repo',sourceSha:'a'.repeat(40),treeSha:'b'.repeat(40),sourceDigest:'c'.repeat(64),sourceLockSha256:'d'.repeat(64),partitionManifestSha256:policy.manifestSha256,nodeVersion:process.version,nodeBinarySha256:'e'.repeat(64),toolchainSha256:'f'.repeat(64),environmentPolicySha256:'1'.repeat(64),runId:'51',runAttempt:1,job:'source-fixtures-contracts'},files=policy.source.find(row=>row.id==='source-contracts')!.files;
 const body={version:1,purpose:'CUEVO_STATELESS_SOURCE_PARTITION',partition:'source-contracts',status:'PASSED',identity,files:files.map(path=>({path,sha256:path===cohorts.SOURCE_TEST_COHORT_FILE?plan.file.sha256:'2'.repeat(64),group:statelessVerificationSteps.find(step=>(step.args as readonly string[]).includes(path))!.name,durationMs:1,cases:[{definitionSha256:'3'.repeat(64),outcome:'PASSED'}]})),startedAtMs:1,completedAtMs:2,exitCode:0,signal:null,frozenBefore:true,frozenAfter:true,cleanupConfirmed:true,reasons:[]},receipt={...body,payloadSha256:createHash('sha256').update(review.canonicalReleaseExecutionJson(body)).digest('hex')};
 assert.throws(()=>api.validateStatelessPartition(receipt,identity,policy),'a passing reduced file cannot satisfy source-owned complete cohort coverage');
});

test('actual source partition dispatches five isolated cohorts once and refuses missing failed or cancelled coverage',async()=>{
 const cohorts=await import('./source-test-cohorts'),review=await import('./release-review'),actualRoot=resolve(import.meta.dirname,'../..'),actualPlan=cohorts.readSourceTestCohortPlan(actualRoot),root=await mkdtemp(join(tmpdir(),'cv-part-cohort-'));
 try{
  await mkdir(join(root,'scripts/database'),{recursive:true});await mkdir(join(root,'scripts/verification'),{recursive:true});await mkdir(join(root,'node_modules/tsx/dist'),{recursive:true});await mkdir(join(root,'.local'),{recursive:true});await writeFile(join(root,'.gitignore'),'.local/\nnode_modules/\n');await writeFile(join(root,'.gitattributes'),'* text eol=lf\n');await writeFile(join(root,'package-lock.json'),'{}\n');
  const source=ts.createSourceFile('owner.ts',await readFile(join(actualRoot,cohorts.SOURCE_TEST_COHORT_FILE),'utf8'),ts.ScriptTarget.Latest,true),titles=new Map<string,string>();
  const visit=(node:import('typescript').Node)=>{if(ts.isCallExpression(node)&&ts.isIdentifier(node.expression)&&node.expression.text==='test'&&ts.isStringLiteral(node.arguments[0]))titles.set(createHash('sha256').update(node.arguments[0].text).digest('hex'),node.arguments[0].text);ts.forEachChild(node,visit);};visit(source);
  const declaration="import{test}from'node:test';import{appendFileSync}from'node:fs';const mode=process.env.CUEVO_COHORT_TEST_MODE;\n"+actualPlan.inventory.map(row=>{
   const body=`appendFileSync('.local/executed.jsonl',JSON.stringify({ordinal:${row.ordinal},temp:process.env.TEMP})+'\\n');if(mode==='hold'){await new Promise(()=>{});}if(mode==='fail'&&${row.ordinal}===1)throw Error('private-cohort-canary');`;
   return row.ordinal===21?`test(${JSON.stringify(titles.get(row.titleSha256))},async t=>{${body}for(const mode of ['COMMIT_REPLY_LOST','READBACK_MISMATCH','LEASE_LOST_AFTER_CREATE'] as const)await t.test(mode,async()=>{appendFileSync('.local/children.jsonl',mode+'\\n');});});`:`test(${JSON.stringify(titles.get(row.titleSha256))},async()=>{${body}});`;
  }).join('\n')+'\n';
  await writeFile(join(root,cohorts.SOURCE_TEST_COHORT_FILE),declaration);const plan=cohorts.readSourceTestCohortPlan(root),ordinary='scripts/verification/ordinary.test.ts';await writeFile(join(root,ordinary),"import{test}from'node:test';import{appendFileSync}from'node:fs';test('ordinary only once',()=>appendFileSync('.local/ordinary.jsonl',process.env.TEMP+'\\n'));\n");
  await writeFile(join(root,'node_modules/tsx/dist/loader.mjs'),`import ${JSON.stringify(pathToFileURL(join(actualRoot,'node_modules/tsx/dist/loader.mjs')).href)};\n`);await writeFile(join(root,'scripts/verification/ci-test-timings-reporter.ts'),`export{default}from ${JSON.stringify(pathToFileURL(join(actualRoot,'scripts/verification/ci-test-timings-reporter.ts')).href)};\n`);
  const git=(args:string[])=>execFileSync('git',['-C',root,...args],{encoding:'utf8',windowsHide:true}).trim();git(['init','--quiet']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','closed cohort fixture']);const sha=git(['rev-parse','HEAD']);
  const coverage={source:[{id:'source-contracts',files:[cohorts.SOURCE_TEST_COHORT_FILE,ordinary]}],sourceCohorts:{version:1,file:plan.file.path,policySha256:plan.policySha256},manifestSha256:'c'.repeat(64)},steps=[{name:'migration-replay-rules',args:['--import','tsx','--test',cohorts.SOURCE_TEST_COHORT_FILE,ordinary]}],hook=join(root,'.local/hook.mjs');
  await writeFile(hook,`import{registerHooks}from'node:module';registerHooks({load(url,context,next){if(url.endsWith('/steps.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('export const statelessVerificationSteps='+JSON.stringify(steps)+';')}};if(url.endsWith('/ci-partition-coverage.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('const coverage='+JSON.stringify(coverage)+';export const readCiPartitionCoverage=()=>coverage;export const ciPartitionFiles=()=>coverage.source[0].files;export const ciPartitionFileSelections=()=>[coverage.source[0].files];')}};return next(url,context);}});`);
  const script=join(root,'.local/run.mjs'),subject=pathToFileURL(join(actualRoot,'scripts/verification/stateless-checks.ts')).href;
  await writeFile(script,`import{runStatelessPartition}from ${JSON.stringify(subject)};import{writeFileSync,existsSync}from'node:fs';const controller=new AbortController();let timer;if(process.env.CUEVO_COHORT_TEST_MODE==='hold')timer=setInterval(()=>{if(existsSync('.local/executed.jsonl'))controller.abort();},10);try{const result=await runStatelessPartition({repoRoot:${JSON.stringify(root)},partition:'source-contracts',signal:controller.signal});writeFileSync('.local/result.json',JSON.stringify(result));process.exitCode=result.status==='PASSED'?0:1;}finally{clearInterval(timer);}`);
  for(const mode of ['pass','fail','hold']){
   for(const name of ['executed.jsonl','children.jsonl','ordinary.jsonl'])await rm(join(root,'.local',name),{force:true});
   const result=spawnSync(process.execPath,['--import',pathToFileURL(join(actualRoot,'node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(hook).href,script],{cwd:root,encoding:'utf8',timeout:30000,maxBuffer:4*1024*1024,windowsHide:true,env:{...process.env,CI:'true',GITHUB_ACTIONS:'true',GITHUB_EVENT_NAME:'pull_request',GITHUB_REPOSITORY:'owner/repo',GITHUB_SHA:sha,GITHUB_RUN_ID:'51',GITHUB_RUN_ATTEMPT:'1',GITHUB_JOB:'source-fixtures-contracts',CUEVO_COHORT_TEST_MODE:mode}});
   const receipt=JSON.parse(await readFile(join(root,'.local/result.json'),'utf8'));assert.equal(receipt.cleanupConfirmed,true,mode);assert.equal((result.stdout+result.stderr+JSON.stringify(receipt)).includes('private-cohort-canary'),false);
   if(mode==='pass'){assert.equal(result.status,0,result.stderr);assert.equal(receipt.status,'PASSED');const file=receipt.files.find((row:{path:string})=>row.path===plan.file.path);assert.equal(file.cases.length,28);assert.equal(file.cohortEvidence.receipts.length,5);const identity={sourceSha:receipt.identity.sourceSha,treeSha:receipt.identity.treeSha,sourceLockSha256:receipt.identity.sourceLockSha256,nodeVersion:receipt.identity.nodeVersion,runId:'51',runAttempt:1,scope:'source-contracts',partitionSha256:coverage.manifestSha256};assert.equal(review.canonicalReleaseExecutionJson(cohorts.validateSourceTestCohortEvidence(plan,file.cohortEvidence,identity)),review.canonicalReleaseExecutionJson(file));const executed=(await readFile(join(root,'.local/executed.jsonl'),'utf8')).trim().split('\n').map(row=>JSON.parse(row));assert.equal(executed.length,25);assert.equal(new Set(executed.map(row=>row.ordinal)).size,25);assert.equal(new Set(executed.map(row=>row.temp)).size,5);for(const scratch of new Set<string>(executed.map(row=>row.temp)))await assert.rejects(lstat(scratch));assert.equal((await readFile(join(root,'.local/children.jsonl'),'utf8')).trim().split('\n').length,3);assert.equal((await readFile(join(root,'.local/ordinary.jsonl'),'utf8')).trim().split('\n').length,1);}
   else{assert.notEqual(result.status,0);assert.equal(receipt.status,mode==='hold'?'CANCELLED':'FAILED');assert(receipt.reasons.includes(mode==='hold'?'CANCELLED':'COVERAGE_UNCONFIRMED'));}
  }
 }finally{await rm(root,{recursive:true,force:true});}
});

test('actual fixed source producers and aggregate retain complete outcomes and refuse missing failed skipped or substituted evidence',async()=>{
 const source=await import('./stateless-checks')as Record<string,unknown>;assert.equal(typeof source.runStatelessPartition,'function','existing stateless owner must expose the closed partition producer');assert.equal(typeof source.combineStatelessPartitions,'function','existing owner must validate the complete partition union');
 const root=await mkdtemp(join(tmpdir(),'cuevo-source-partitions-'));
 try{
  const ids=['source-native','source-contracts','source-delivery'],files=ids.map((_,index)=>`scripts/verification/controlled-${index}.test.ts`),steps=files.map((path,index)=>({name:'fixture-'+index,args:['--import','tsx','--test',path]}));
  await mkdir(join(root,'scripts/verification'),{recursive:true});await writeFile(join(root,'.gitignore'),'.local/\n');await writeFile(join(root,'.gitattributes'),'* text eol=lf\n');await writeFile(join(root,'package-lock.json'),'{}\n');await writeFile(join(root,'package.json'),'{}\n');
  for(const path of files)await writeFile(join(root,path),"import {test}from'node:test';import{appendFileSync}from'node:fs';const mode=process.env.CUEVO_PARTITION_TEST_MODE;if(mode==='only'){test.only('focused case',()=>{});test('unfocused required case',()=>{});}else if(mode==='todo')test.todo('todo case');else if(mode!=='empty'){\n test('one actual controlled declaration',{skip:mode==='skip'},async()=>{if(mode==='hold'){appendFileSync('.local/hold-started','started');await new Promise(()=>{});}if(mode==='fail')throw Error('private-partition-canary');if(mode==='source-drift')appendFileSync('package-lock.json','changed');});\n  test('second actual controlled declaration',()=>{});}\n");
  const git=(args:string[])=>execFileSync('git',['-C',root,...args],{encoding:'utf8',windowsHide:true}).trim();git(['init','--quiet']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','--quiet','-m','source']);const sha=git(['rev-parse','HEAD']);
  const coverage={version:1,purpose:'CUEVO_FIXED_CI_PARTITIONS',source:ids.map((id,index)=>({id,files:[files[index]]})),integration:[],nonTestChecks:[],separateSource:[],separateIntegration:[],measurements:{source:files.map(path=>({path,durationMs:null})),integration:[],provenance:{sourceSha:sha,runId:'51',runAttempt:2,basis:'ORIGINAL_CASE_FILE_DURATION'}},manifestSha256:'c'.repeat(64),effectAuthority:false,timeTargetAchieved:false};
  const hook=join(root,'.local','fixtures.mjs');await mkdir(join(root,'.local'),{recursive:true});await writeFile(hook,`import {registerHooks}from'node:module';registerHooks({load(url,context,next){if(url.endsWith('/steps.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('export const statelessVerificationSteps='+JSON.stringify(steps)+';')}};if(url.endsWith('/ci-partition-coverage.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('const coverage='+JSON.stringify(coverage)+';export const readCiPartitionCoverage=()=>coverage;export const ciPartitionFiles=(_value,_scope,id)=>coverage.source.find(row=>row.id===id).files;export const ciPartitionFileSelections=(_value,requests)=>requests.map(row=>coverage.source.find(part=>part.id===row.id).files);')}};return next(url,context);}});`);
  const script=join(root,'.local','runner.mjs'),subject=pathToFileURL(resolve('scripts/verification/stateless-checks.ts')).href;await writeFile(script,`import {runStatelessPartition}from ${JSON.stringify(subject)};import{writeFileSync}from'node:fs';const value=await runStatelessPartition({repoRoot:${JSON.stringify(root)},partition:process.env.CUEVO_PARTITION_ID});writeFileSync(${JSON.stringify(join(root,'.local','returned.json'))},JSON.stringify(value));process.exitCode=value.status==='PASSED'?0:1;`);
  const run=(id:string,mode='pass')=>spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(hook).href,script],{cwd:root,encoding:'utf8',env:{...process.env,CI:'true',GITHUB_ACTIONS:'true',GITHUB_EVENT_NAME:'pull_request',GITHUB_REPOSITORY:'owner/repo',GITHUB_SHA:sha,GITHUB_RUN_ID:'51',GITHUB_RUN_ATTEMPT:'2',GITHUB_JOB:'source-fixtures-'+id.slice(7),CUEVO_PARTITION_ID:id,CUEVO_PARTITION_TEST_MODE:mode}});
  const receipts:unknown[]=[];for(const id of ids){const passed=run(id);assert.equal(passed.status,0,passed.stdout+passed.stderr+await readFile(join(root,'.local','returned.json'),'utf8'));const receipt=JSON.parse(await readFile(join(root,'.local','returned.json'),'utf8'));assert.equal(receipt.status,'PASSED');assert.equal(receipt.files.length,1);assert.equal(receipt.files[0].cases.length,2);assert.equal(receipt.files[0].sha256,createHash('sha256').update(await readFile(join(root,receipt.files[0].path))).digest('hex'));assert.ok(Buffer.byteLength(JSON.stringify(receipt))<1024*1024);assert.equal(JSON.stringify(receipt).includes('private-partition-canary'),false);receipts.push(receipt);}
  const schemas=source as unknown as typeof import('./stateless-checks');assert.deepEqual(schemas.validateParsedPartitionOutcome(schemas.partitionReceiptSchema.parse(receipts[0])),receipts[0]);assert.throws(()=>schemas.partitionReceiptSchema.parse({...receipts[0]as object,private:'private-canary'}));const malformed=structuredClone(receipts[0])as {files:{cases:{outcome:string}[]}[]};malformed.files[0].cases[0].outcome='invented';assert.throws(()=>schemas.partitionReceiptSchema.parse(malformed));
  const aggregateScript=join(root,'.local','aggregate.mjs');
  await writeFile(aggregateScript,`import {combineStatelessPartitions}from ${JSON.stringify(subject)};import{readFileSync,writeFileSync}from'node:fs';try{const input=JSON.parse(readFileSync(${JSON.stringify(join(root,'.local','aggregate-input.json'))},'utf8'));writeFileSync(${JSON.stringify(join(root,'.local','combined.json'))},JSON.stringify(combineStatelessPartitions(input.values,input.expected,input.coverage,[])));}catch{process.exitCode=1;}`);
  const combine=async(values:unknown)=>{await writeFile(join(root,'.local','aggregate-input.json'),JSON.stringify({values,expected:(receipts[0]as Record<string,unknown>).identity,coverage}));return spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(hook).href,aggregateScript],{cwd:root,encoding:'utf8',env:process.env});};
  assert.equal((await combine(receipts)).status,0);assert.equal(JSON.parse(await readFile(join(root,'.local','combined.json'),'utf8')).status,'PASSED');
  for(const mode of ['missing','duplicate','wrong-attempt','wrong-source','tamper','skip']){const changed=structuredClone(receipts)as Record<string,unknown>[];if(mode==='missing')changed.pop();if(mode==='duplicate')changed[1]=changed[0];if(mode==='wrong-attempt')(changed[1].identity as Record<string,unknown>).runAttempt=3;if(mode==='wrong-source')(changed[1].identity as Record<string,unknown>).sourceSha='f'.repeat(40);if(mode==='tamper')(changed[1].files as {sha256:string}[])[0].sha256='f'.repeat(64);if(mode==='skip')changed[1].status='FAILED';assert.notEqual((await combine(changed)).status,0,mode);}
  const aggregateCli=resolve('scripts/verification/stateless-source-aggregate.ts'),inputRoot=join(root,'.local/source-partition-inputs');for(const[index,id]of ids.entries()){await mkdir(join(inputRoot,id),{recursive:true});await writeFile(join(inputRoot,id,'result.json'),JSON.stringify(receipts[index]));}
  const canonical=await import('./release-review');for(const[index,id]of ids.entries())await writeFile(join(inputRoot,id,'result.json'),canonical.canonicalReleaseExecutionJson(receipts[index]));
  const cli=()=>spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(hook).href,aggregateCli],{cwd:root,encoding:'utf8',env:{...process.env,CI:'true',GITHUB_ACTIONS:'true',GITHUB_EVENT_NAME:'pull_request',GITHUB_REPOSITORY:'owner/repo',GITHUB_SHA:sha,GITHUB_RUN_ID:'51',GITHUB_RUN_ATTEMPT:'2',GITHUB_JOB:'source-contracts'}});
  const aggregatePass=cli();assert.equal(aggregatePass.status,0,aggregatePass.stderr);assert.equal(JSON.parse(await readFile(join(root,'.local/verification/source-contracts/result.json'),'utf8')).status,'PASSED');
  for(const mode of ['missing','extra','noncanonical','wrong-attempt','source-file','path-escape']){const id=ids[1],path=join(inputRoot,id,'result.json'),original=await readFile(path,'utf8');if(mode==='missing')await rm(path);if(mode==='extra')await writeFile(join(inputRoot,id,'private.txt'),'private-canary');if(mode==='noncanonical')await writeFile(path,original+'\n');if(mode==='wrong-attempt'){const row=JSON.parse(original);row.identity.runAttempt=3;await writeFile(path,canonical.canonicalReleaseExecutionJson(row));}if(mode==='source-file')await writeFile(join(root,files[1]),'changed source\n');if(mode==='path-escape'){const row=JSON.parse(original);row.files[0].path='../../private-key';await writeFile(path,canonical.canonicalReleaseExecutionJson(row));}const denied=cli();assert.notEqual(denied.status,0,mode);assert.equal((denied.stdout+denied.stderr).includes('private-canary'),false);if(mode==='extra')await rm(join(inputRoot,id,'private.txt'));if(mode==='source-file')await writeFile(join(root,files[1]),await readFile(join(root,files[0])));await writeFile(path,original);}
  const foreign=join(root,'.local/foreign-output');await mkdir(foreign);const output=join(root,'.local/verification/source-contracts');await rm(output,{recursive:true});await symlink(foreign,output,process.platform==='win32'?'junction':'dir');assert.notEqual(cli().status,0,'output parent symlink must refuse before writing');await assert.rejects(readFile(join(foreign,'result.json')),{code:'ENOENT'});await rm(output);await mkdir(output);const inputDirectory=join(inputRoot,ids[0]),backup=join(root,'.local/input-backup');await mkdir(backup);await writeFile(join(backup,'result.json'),canonical.canonicalReleaseExecutionJson(receipts[0]));await rm(inputDirectory,{recursive:true});await symlink(backup,inputDirectory,process.platform==='win32'?'junction':'dir');assert.notEqual(cli().status,0,'input symlink cannot substitute original artifact');await rm(inputDirectory);await mkdir(inputDirectory);await writeFile(join(inputDirectory,'result.json'),canonical.canonicalReleaseExecutionJson(receipts[0]));
  const cancelledScript=join(root,'.local/cancelled.mjs');await writeFile(cancelledScript,`import{runStatelessPartition}from ${JSON.stringify(subject)};import{writeFileSync}from'node:fs';const controller=new AbortController();controller.abort();const value=await runStatelessPartition({repoRoot:${JSON.stringify(root)},partition:'source-native',signal:controller.signal});writeFileSync(${JSON.stringify(join(root,'.local/cancelled.json'))},JSON.stringify(value));`);const cancelled=spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(hook).href,cancelledScript],{cwd:root,encoding:'utf8',env:{...process.env,CI:'true',GITHUB_ACTIONS:'true',GITHUB_EVENT_NAME:'pull_request',GITHUB_REPOSITORY:'owner/repo',GITHUB_SHA:sha,GITHUB_RUN_ID:'51',GITHUB_RUN_ATTEMPT:'2',GITHUB_JOB:'source-fixtures-native'}});assert.equal(cancelled.status,0,cancelled.stderr);const cancelledReceipt=JSON.parse(await readFile(join(root,'.local/cancelled.json'),'utf8'));assert.equal(cancelledReceipt.status,'CANCELLED');assert.equal(cancelledReceipt.exitCode,null);assert.ok(cancelledReceipt.reasons.includes('CANCELLED'));
  const runningCancelScript=join(root,'.local/running-cancel.mjs');await writeFile(runningCancelScript,runningCancellationFixtureSource);await writeFile(join(root,'.local/running-cancel-input.json'),JSON.stringify({subject,repoRoot:root,output:join(root,'.local/running-cancel.json')}));const runningCancel=spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(hook).href,runningCancelScript],{cwd:root,encoding:'utf8',timeout:30000,env:{...process.env,CI:'true',GITHUB_ACTIONS:'true',GITHUB_EVENT_NAME:'pull_request',GITHUB_REPOSITORY:'owner/repo',GITHUB_SHA:sha,GITHUB_RUN_ID:'51',GITHUB_RUN_ATTEMPT:'2',GITHUB_JOB:'source-fixtures-native',CUEVO_PARTITION_TEST_MODE:'hold'}});assert.equal(runningCancel.status,0,runningCancel.stderr);const runningReceipt=JSON.parse(await readFile(join(root,'.local/running-cancel.json'),'utf8'));assert.equal(runningReceipt.status,'CANCELLED');assert.equal(runningReceipt.cleanupConfirmed,true,'running owned child is stopped before cancellation receipt');assert.ok(runningReceipt.reasons.includes('CANCELLED'));
  const failedChecksHook=join(root,'.local/check-failure.mjs');await writeFile(failedChecksHook,`import{registerHooks}from'node:module';registerHooks({load(url,context,next){if(url.endsWith('/steps.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('export const statelessVerificationSteps=[{name:"fixed-check",args:["--eval","process.exit(1)"]}];')}};return next(url,context);}});`);const checksScript=join(root,'.local/checks.mjs');await writeFile(checksScript,`import{runStatelessAggregateChecks}from ${JSON.stringify(subject)};try{await runStatelessAggregateChecks(${JSON.stringify(root)});}catch{process.exitCode=1;}`);const failedChecks=spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(failedChecksHook).href,checksScript],{cwd:root,encoding:'utf8',env:process.env});assert.notEqual(failedChecks.status,0,'a failed original non-test check cannot be projected as complete');
  const envCheckHook=join(root,'.local/check-env.mjs');await writeFile(envCheckHook,`import{registerHooks}from'node:module';registerHooks({load(url,context,next){if(url.endsWith('/steps.ts'))return{format:'module',shortCircuit:true,source:${JSON.stringify('export const statelessVerificationSteps=[{name:"fixed-check",args:["--eval","if(process.env.NODE_OPTIONS!==undefined)process.exit(1)"]}];export const fullRuntimeVerificationSteps=[];export const mainStagingVerificationSteps=[];export const routineVerificationSteps=[];export const verificationSteps=[];')}};return next(url,context);}});`);await writeFile(checksScript,`import{runStatelessAggregateChecks}from ${JSON.stringify(subject)};process.env.NODE_OPTIONS='--unreviewed-child-hook';try{await runStatelessAggregateChecks(${JSON.stringify(root)});}catch{process.exitCode=1;}`);const envCheck=spawnSync(process.execPath,['--import',pathToFileURL(resolve('node_modules/tsx/dist/loader.mjs')).href,'--import',pathToFileURL(envCheckHook).href,checksScript],{cwd:root,encoding:'utf8',env:process.env});assert.equal(envCheck.status,0,'non-test child cannot inherit unrecorded Node options: '+envCheck.stderr+envCheck.stdout);
  const allReceipt=receipts[0]as {files:{cases:{definitionSha256:string;outcome:string}[]}[]};const compactCase=allReceipt.files[0].cases[0],budget=JSON.stringify({files:Array.from({length:145},(_,index)=>({path:'scripts/verification/current-owner-'+index+'.test.ts',sha256:'a'.repeat(64),group:'migration-replay-rules',durationMs:1000,cases:Array.from({length:Math.ceil(1483/145)},()=>compactCase)}))});assert.ok(Buffer.byteLength(budget)<1024*1024,'a declared upper bound of current historical case count fits compact source evidence; this is a size bound, not executed coverage');
  const ignoredFocus=run(ids[0],'only');assert.equal(ignoredFocus.status,0,'closed Node invocation executes every case instead of honoring --test-only');assert.equal(JSON.parse(await readFile(join(root,'.local','returned.json'),'utf8')).files[0].cases.length,2);
  for(const mode of ['skip','fail','todo','empty','source-drift']){const failed=run(ids[0],mode);assert.notEqual(failed.status,0,mode);const receipt=JSON.parse(await readFile(join(root,'.local','returned.json'),'utf8'));assert.notEqual(receipt.status,'PASSED');if(mode==='fail'||mode==='skip'||mode==='todo'){assert.ok(receipt.files[0].cases.some((row:{outcome:string})=>row.outcome===(mode==='fail'?'FAILED':mode==='skip'?'SKIPPED':'TODO')),'failed receipt retains observed case outcomes');assert.ok(receipt.files[0].durationMs!==null);assert.ok(receipt.reasons.includes('PROCESS_FAILED'));}assert.equal((failed.stdout+failed.stderr+JSON.stringify(receipt)).includes('private-partition-canary'),false);if(mode==='source-drift'){assert.equal(receipt.frozenAfter,false);await writeFile(join(root,'package-lock.json'),'{}\n');}}
 }finally{await rm(root,{recursive:true,force:true});}
});
