import{mkdir,writeFile,readFile}from'node:fs/promises';import{spawn,execFileSync}from'node:child_process';import{resolve}from'node:path';import{createHash}from'node:crypto';import{sameSourceManifest}from'./rules';import{commandArgs}from'./steps';
import{readVerificationProfile,readCiRuntimeSelection,verificationProfileSteps,verificationEvidence,validateCriticalBrowserReport,criticalBrowserArguments,criticalBrowserFiles}from'./verification-profiles';
const requestedProfile=readVerificationProfile(process.argv.slice(2)),selection=requestedProfile==='ci'?await readCiRuntimeSelection():{profile:requestedProfile,browserFiles:[...criticalBrowserFiles]},profile=selection.profile,selectedSteps=verificationProfileSteps(profile);
for(const port of[3000,4000,4001]){let active=false;try{await fetch('http://127.0.0.1:'+port+'/health/live',{signal:AbortSignal.timeout(1000)});active=true;}catch{/* Expected while stopped. */}if(active)throw Error('Stop Cuevo application processes before clean technical verification.');}
const directory=resolve('.local/verification',new Date().toISOString().replace(/[:.]/g,'-'));await mkdir(directory,{recursive:true});
const snapshot=async()=>{const sourceFiles=execFileSync('git',['ls-files','--cached','--others','--exclude-standard'],{encoding:'utf8'}).split(/\r?\n/).filter(Boolean);const manifest:{path:string;sha256:string}[]=[];for(const path of new Set(sourceFiles)){try{manifest.push({path,sha256:createHash('sha256').update(await readFile(path)).digest('hex')});}catch{/* Deleted tracked paths remain absent from current source state. */}}return manifest;};const manifest=await snapshot();await writeFile(resolve(directory,'source.json'),JSON.stringify(manifest,null,2));
const rows=[...selectedSteps.map(step=>({name:step.name,exitCode:null as number|null,required:true,durationMs:0})),{name:'source-freeze',exitCode:null as number|null,required:true,durationMs:0}];
const persist=()=>writeFile(resolve(directory,'evidence.json'),JSON.stringify(verificationEvidence(profile,rows),null,2));await persist();
let failed=false,bootstrapCompleted=false;
const runStep=async(step:typeof selectedSteps[number])=>{console.log('Required '+profile+' verification: '+step.name);const started=Date.now(),args=commandArgs(step);if(step.name==='critical-browser')args.push(...criticalBrowserArguments(selection.browserFiles));const code=await new Promise<number|null>(resolveCode=>{const child=spawn(process.execPath,args,{stdio:'inherit',env:{...process.env,CUEVO_REQUIRE_INTEGRATION:'1',CUEVO_REQUIRE_LIVE_INTELLIGENCE:'0',NEXT_TELEMETRY_DISABLED:'1',CI:['browser','browser-compatibility','critical-browser'].includes(step.name)?'true':process.env.CI}});child.on('error',()=>resolveCode(null));child.on('exit',resolveCode);});Object.assign(rows.find(r=>r.name===step.name)!,{exitCode:code,durationMs:Date.now()-started});await persist();return code;};
try{for(const step of selectedSteps){const code=await runStep(step);if(code!==0)throw Error('Required verification failed: '+step.name);if(step.name==='clean-bootstrap')bootstrapCompleted=true;if(step.name==='critical-browser'){try{validateCriticalBrowserReport(JSON.parse(await readFile(resolve('.local/customer-readiness/critical-browser-results.json'),'utf8')),selection.browserFiles);}catch{Object.assign(rows.find(row=>row.name===step.name)!,{exitCode:1});await persist();throw Error('Critical browser report requires review.');}}}}catch{failed=true;}
finally{
 if(['routine','main-staging'].includes(profile)&&bootstrapCompleted&&rows.find(row=>row.name==='demo-seed-restore')!.exitCode===null){try{if(await runStep(selectedSteps.find(step=>step.name==='demo-seed-restore')!)!==0)failed=true;}catch{failed=true;}}
 const finalManifest=await snapshot();await writeFile(resolve(directory,'source-final.json'),JSON.stringify(finalManifest,null,2));const unchanged=sameSourceManifest(manifest,finalManifest);Object.assign(rows.find(r=>r.name==='source-freeze')!,{exitCode:unchanged?0:1});await persist();if(!unchanged)failed=true;
}
if(failed){console.error(profile+' verification failed; evidence retained in '+directory);process.exitCode=1;}else console.log('Technical evidence '+verificationEvidence(profile,rows).status+': '+directory);
