import{readFile,realpath}from'node:fs/promises';import{resolve,relative,isAbsolute}from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{z}from'zod';import{DomainError}from'@cuevo/domain';import{curriculumVersionInputSchema,rubricInputSchema}from'@cuevo/contracts';import type{Database}from'../../platform/database/database';import{requireCapability,type ActorContext}from'@cuevo/domain';

// Bundled delivery supplies this private build-time URL; source runtime uses the owner location.
declare const CUEVO_LOCKED_PACK_ROOT_URL: string | undefined;
const runtimePackRoot = fileURLToPath(typeof CUEVO_LOCKED_PACK_ROOT_URL === 'string' ? new URL(CUEVO_LOCKED_PACK_ROOT_URL, import.meta.url) : new URL('../../../../../supabase/seed/curriculum/', import.meta.url));
export function loadRuntimeLockedPack(packDirectory: string) { return loadLockedPack(runtimePackRoot, packDirectory); }
const key=z.string().min(1).max(100).regex(/^[a-z0-9-]+$/);const ref=z.object({key,parent:key.nullable(),type:z.enum(['stage','year','subject','strand','objective','outcome','criterion','syllabus_item']),title:z.string().min(1).max(200),description:z.string().min(1).max(4000),sequence:z.number().int().min(0)}).strict();
const manifestSchema=z.object({packId:key,version:z.string().min(1),files:z.record(z.string(),z.string().regex(/^[a-f0-9]{64}$/))}).strict();
const normalizedSchema=z.object({references:z.array(ref).min(1).max(100)}).strict();const assessmentSchema=z.object({models:z.array(z.enum(['numeric','rubric'])).min(1),numeric:z.object({maxScore:z.number().positive().max(100000),normalization:z.null()}).strict(),rubric:rubricInputSchema.omit({courseId:true})}).strict();
const requiredFiles=['snapshot.txt','pack.json','sources.json','normalized.json','assessment.json','reporting.json','mappings.json','terminology.json','rights.json','unknowns.json','golden-cases.json'];
function fail():never{throw new DomainError('CURRICULUM_REQUIRES_REVIEW',409,'The locked curriculum artifact requires review.');}
async function lockedFile(root:string,path:string){if(isAbsolute(path)||path.includes('\\')||path.split('/').includes('..'))fail();const full=await realpath(resolve(root,path));if(relative(root,full).startsWith('..')||isAbsolute(relative(root,full)))fail();return readFile(full);}
export async function loadLockedPack(rootDirectory:string,packDirectory:string){const root=await realpath(rootDirectory);if(isAbsolute(packDirectory)||packDirectory.includes('..'))fail();const folder=await realpath(resolve(root,packDirectory));if(relative(root,folder).startsWith('..'))fail();const manifest=manifestSchema.parse(JSON.parse((await lockedFile(folder,'manifest.json')).toString()));const content:Record<string,unknown>={};for(const file of requiredFiles){const bytes=await lockedFile(folder,file);if(bytes.length>500000||manifest.files[file]!==createHash('sha256').update(bytes).digest('hex'))fail();content[file]=file==='snapshot.txt'?bytes.toString():JSON.parse(bytes.toString());}
 const pack=curriculumVersionInputSchema.parse(content['pack.json']);const normalized=normalizedSchema.parse(content['normalized.json']);const assessment=assessmentSchema.parse(content['assessment.json']);if(!pack.synthetic||pack.kind!=='school_custom'||pack.sourceStatus!=='VERIFIED'||pack.rightsStatus!=='PERMITTED'||pack.packId!==manifest.packId||pack.version!==manifest.version)fail();const ids=new Set(normalized.references.map(r=>r.key));if(ids.size!==normalized.references.length)fail();for(const reference of normalized.references){if(reference.parent&&!ids.has(reference.parent))fail();let cursor=reference;const seen=new Set<string>();while(cursor.parent){if(seen.has(cursor.key))fail();seen.add(cursor.key);cursor=normalized.references.find(r=>r.key===cursor.parent)!;}}
 const rights=z.object({status:z.literal('PERMITTED'),scope:z.string(),owner:z.string(),synthetic:z.literal(true)}).strict().parse(content['rights.json']);if(rights.scope!==pack.scope)fail();
 const source=z.object({sourceId:z.string().min(1),publisher:z.string().min(1),location:z.literal('snapshot.txt'),version:z.string().min(1),publishedOn:z.iso.date(),accessedAt:z.iso.datetime({offset:true}),status:z.literal('VERIFIED')}).strict().parse(content['sources.json']);if(source.version!==pack.version||pack.sourceChecksum!==manifest.files['snapshot.txt'])fail();
 z.object({nativeModels:z.array(z.enum(['numeric','rubric'])),missing:z.literal('UNKNOWN'),normalized:z.null(),officialQualification:z.literal(false)}).strict().parse(content['reporting.json']);
 z.object({officialSources:z.literal('REQUIRES_REVIEW'),officialRights:z.literal('UNKNOWN'),academicSignoff:z.literal('SYNTHETIC_OWNER_ONLY'),customerReady:z.literal(false),productionApproved:z.literal(false)}).strict().parse(content['unknowns.json']);
 z.object({required:z.array(z.string().min(1)).min(1),status:z.literal('TECHNICAL_FIXTURE')}).strict().parse(content['golden-cases.json']);
 const mappings=z.object({assessmentReference:key,courseReference:key}).strict().parse(content['mappings.json']);if(!ids.has(mappings.assessmentReference)||!ids.has(mappings.courseReference))fail();return{manifest,pack,normalized,assessment,mappings,artifacts:content};}
type LockedReference=z.infer<typeof ref>;
/** Parent-first traversal preserves each pinned edge independently of artifact array order. */
function referenceImportOrder(references:LockedReference[]){const byKey=new Map(references.map(reference=>[reference.key,reference]));const visited=new Set<string>();const visiting=new Set<string>();const ordered:LockedReference[]=[];function visit(reference:LockedReference){if(visited.has(reference.key))return;if(visiting.has(reference.key))fail();visiting.add(reference.key);if(reference.parent){const parent=byKey.get(reference.parent);if(!parent)fail();visit(parent);}visiting.delete(reference.key);visited.add(reference.key);ordered.push(reference);}for(const reference of references)visit(reference);return ordered;}
export function createPackAdapter(bundle:Awaited<ReturnType<typeof loadLockedPack>>){
 const references=bundle.normalized.references;const byKey=new Map(references.map(reference=>[reference.key,reference]));
 const descendantOf=(reference:LockedReference,parentKey:string)=>{let cursor:LockedReference|undefined=reference;while(cursor){if(cursor.key===parentKey)return true;cursor=cursor.parent?byKey.get(cursor.parent):undefined;}return false;};
 return{getProgrammeProfile:()=>({framework:bundle.pack.framework,programme:bundle.pack.programme,version:bundle.pack.version,synthetic:true}),listStages:()=>references.filter(r=>r.type==='stage'),
  listSubjects:(context:{version?:string;stageKey?:string}={})=>context.version!==undefined&&context.version!==bundle.pack.version?[]:references.filter(reference=>reference.type==='subject'&&(!context.stageKey||byKey.get(context.stageKey)?.type==='stage'&&descendantOf(reference,context.stageKey))),
  resolveReferences:()=>references,getAssessmentModels:()=>bundle.assessment.models,getGradeRepresentations:()=>bundle.assessment.models,
  validateCourseConfiguration:(input:{version:string;subjectKey:string;referenceKey:string;stageKey?:string})=>{const subject=byKey.get(input.subjectKey);const reference=byKey.get(input.referenceKey);const valid=input.version===bundle.pack.version&&subject?.type==='subject'&&!!reference&&['objective','outcome','criterion'].includes(reference.type)&&descendantOf(reference,input.subjectKey)&&(!input.stageKey||byKey.get(input.stageKey)?.type==='stage'&&descendantOf(subject,input.stageKey));return{valid:!!valid,status:valid?'VALID'as const:'REQUIRES_REVIEW'as const};},
  validateAssessmentConfiguration:(input:{version:string;model:string;maxScore?:number})=>input.version===bundle.pack.version&&bundle.assessment.models.includes(input.model as'numeric'|'rubric')&&(input.model!=='numeric'||input.maxScore===bundle.assessment.numeric.maxScore),explainNativeTerminology:()=>bundle.artifacts['terminology.json']};
}
export async function importLockedPack(actor:ActorContext,database:Database,root:string,directory:string){requireCapability(actor,actor.schoolId,'curriculum',['admin','coordinator']);const bundle=await loadLockedPack(root,directory);const hash=bundle.manifest.files['snapshot.txt']!;const input={...bundle.pack,sourceChecksum:hash};return database.actorTransaction(actor.userId,actor.schoolId,async client=>{
 const result=(await client.query('select internal.configure_curriculum($1,$2,$3::jsonb,$4,$5,$6)as receipt',['version.create',null,JSON.stringify(input),`locked-pack:${bundle.pack.packId}:${bundle.pack.version}`,createHash('sha256').update(JSON.stringify(input)).digest('hex'),'source-locked-import'])).rows[0].receipt;
 const references=new Map<string,string>();for(const reference of referenceImportOrder(bundle.normalized.references)){const parentId=reference.parent?references.get(reference.parent):null;if(reference.parent&&!parentId)fail();const body={packVersionId:result.id,parentId,type:reference.type,title:reference.title,description:reference.description,code:null,sequence:reference.sequence,subjectId:null,yearGroupId:null};const id=(await client.query('select internal.configure_curriculum($1,$2,$3::jsonb,$4,$5,$6)as receipt',['reference.create',null,JSON.stringify(body),`locked-ref:${bundle.pack.packId}:${bundle.pack.version}:${reference.key}`,createHash('sha256').update(JSON.stringify(body)).digest('hex'),'source-locked-import'])).rows[0].receipt.id;references.set(reference.key,id);}
 return{...result,pack:bundle.pack,normalized:bundle.normalized,assessment:bundle.assessment,referenceIds:Object.fromEntries(references)};
 });}
